function MenuRankupShop_Start()
  SYSTEM:DebugPrint("+++++Start+++++")
  MENU:LoadMenuTextPool("message/shop.bin", false)
  SCREEN_B:LoadWallpaper("WALLPAPER_SUB_WORLDMAP01")
end
function MenuRankupShop_SetTag()
  MENU:SetTag_Value(7, GROUND:GetNextChousadanRankPoint())
end
function MenuRankupShop_End()
  LOWER_SCREEN:ChangeLastWallpaper()
end
function MenuRankupShop_RankupEnd()
  SOUND:PlaySe(SymSnd("SE_SYS_ATLAS_ORB_PUT"))
end
function MenuRankupShop_CompleteEvent()
  SYSTEM:DebugPrint("+++++Start+++++")
  EFFECT:Create("effectAtlasBoot", SymEff("EV_ATLAS_BOOT"))
  EFFECT:SetPosition("effectAtlasBoot", SymPos("P_EFF_EV_ATLAS_BOOT"))
  EFFECT:Play("effectAtlasBoot")
  local taskKidouSe = function()
    SOUND:PlaySe(SymSnd("SE_EVT_RIPPLE"))
    SOUND:PlaySe(SymSnd("SE_EVT_ATLAS_KIDOU_01_LP"))
    TASK:Sleep(TimeSec(35, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ATLAS_KIDOU_02"))
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
  end
  TASK:Regist(taskKidouSe)
  TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
  SCREEN_A:WhiteOut(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
  SCREEN_A:WhiteIn(TimeSec(1), true)
  TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-246980233)
  WINDOW:SysMsg(-396603338)
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  SOUND:PlayMe(SymSnd("ME_EVT_TA_DAH"), Volume(256))
  SAJI:CreateSajiPlayer("confetti", "SCRATCH_CONFETTI")
  SAJI:CreateSajiPlayer("confetti", "SCRATCH_CONFETTI")
  SJ("confetti"):SetPosition(Vector2(200, 120))
  SJ("confetti"):SetDrawPriority(500)
  SJ("confetti"):SetParallax(-1)
  SJ("confetti"):Play(LOOP.ON)
  SJ("confetti"):SetVisible(true)
  TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-1016003595)
  WINDOW:SysMsg(-630574412)
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  SAJI:DestroySajiPlayer("confetti")
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
end
