function MenuWazaShop_Start()
  MENU:LoadMenuTextPool("message/shop.bin", false)
  MENU:LoadMenuTextPool("message/top.bin", true)
  SCREEN_B:LoadWallpaper("WALLPAPER_SUB_SKILL01")
end
function MenuWazaShop_SetTag()
  local wareId = GROUND:ShopFlowSystem_PokemonSelect_WarehouseId()
  MENU:SetTag_MonsterString(2, GROUND:GetPokemonWarehouseNameFromId(wareId))
  local remember = GROUND:ShopFlowSystem_WazaSelect_Rememver()
  MENU:SetTag_String(5, GROUND:ShopFlowSystem_WazaSelect_WazaName(remember, wareId))
  local forget = GROUND:ShopFlowSystem_WazaSelect_Forget()
  MENU:SetTag_String(6, GROUND:ShopFlowSystem_WazaSelect_WazaName(forget, wareId))
  local remember = GROUND:ShopFlowSystem_WazaSelect_Rememver()
  MENU:SetTag_String(8, GROUND:ShopFlowSystem_WazaSelect_WazaName(remember, wareId))
  local ability = GROUND:ShopFlowSystem_Next_Ability()
  MENU:SetTag_String(7, GROUND:GetAbilityName(ability))
end
function MenuWazaShop_WazaGuide()
  local wazaID = GROUND:ShopFlowSystem_WazaSelect()
  local textID = FUNC_COMMON:GetWazaExplainTextId(wazaID)
  local explainWindow = CommonSys:OpenBasicExplainMenu(textID)
  MENU:SetFocus(explainWindow)
  CommonSys:BeginLowerMenuNavi(nil, nil, true)
  FlowSys:WaitCloseMenu(explainWindow)
  CommonSys:EndLowerMenuNavi(true)
end
function MenuWazaShop_End()
  LOWER_SCREEN:ChangeLastWallpaper()
end
function MenuWazaShop_RememberMotion()
  CH("RUCHABURU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.4))
end
function FlashFlash()
  SOUND:PlaySe(SymSnd("SE_SHOP_RUCHABURU_JUMP"))
  CH("RUCHABURU"):SetMotion(SymMot("ROUND"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_SHOP_RUCHABURU_FLASH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_SHOP_RUCHABURU_FLASH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.5))
  CH("RUCHABURU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
end
