dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main02_numeragashinpai01_init()
end
function main02_numeragashinpai01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1036272982)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  TASK:Regist(subEveJump, {
    CH("SHIKIJIKA_SPRING")
  })
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct(""), -618624021)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct(""), -267528152)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct(""), -384374423)
  WINDOW:Talk(SymAct(""), -1504215122)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1085518097)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1805574868)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1921373075)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 182595746)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 335086051)
  subEveCloseMsg()
  CH("CHOBOMAKI"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1501532067)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):ResetFacialMotion()
  subEveNod(CH("CHOBOMAKI"))
  TASK:Sleep(TimeSec(0.3))
  CH("CHOBOMAKI"):WalkTo(SplinePath(SymPos("P00_CHOBOMAKI"), SymPos("P01_CHOBOMAKI")), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.LEFT)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("SHIKIJIKA_SPRING"):WalkTo(SplinePath(SymPos("P00_SHIKIJIKA"), SymPos("P01_SHIKIJIKA")), Speed(1.5))
  TASK:Sleep(TimeSec(2))
  CAMERA:MoveFollow2(SymCam("CAMERA_00"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(1080344290)
  WINDOW:Monologue(1800006945)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("SHIKIJIKA_SPRING"):SetVisible(false)
  CH("CHOBOMAKI"):SetVisible(false)
end
function main02_numeragashinpai01_end()
end
function groundEnd()
end
