dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main08_yorunomimawarikyoutou01_init()
end
function main08_yorunomimawarikyoutou01_start()
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1551216453)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main08_yorunomimawarikyoutou01_end()
end
function main08_yorunomimawarikyoutou02_init()
end
function main08_yorunomimawarikyoutou02_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main08_yorunomimawarikyoutou02_end()
end
function main08_yorunomimawarikyoutou03_init()
end
function main08_yorunomimawarikyoutou03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MIRUHOGGU"):WalkTo(SymPos("P00_MIRUHOGGU"), Speed(1.2))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("MIRUHOGGU"):WaitMove()
  TASK:Sleep(TimeSec(0.7))
  TASK:Regist(subEveMoveDir2, {
    CH("MIRUHOGGU"),
    SymPos("P01_MIRUHOGGU"),
    Speed(1.2),
    RotateTarget(90)
  })
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.3))
  CH("MIRUHOGGU"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.SAD)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1164877316)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1849937351)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 2002320518)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 941189697)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  CH("MIRUHOGGU"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 553802496)
  WINDOW:CloseMessage()
  subEveNod(CH("MIRUHOGGU"))
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(324, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 170854595)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("MIRUHOGGU"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 322189698)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1800657587)
  WINDOW:CloseMessage()
  local taskObake00 = function()
    EFFECT:StartMotionBlur(0, 0, 0)
    EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.4))
    EFFECT:ChangeMotionBlurAlpha(0.5, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.5))
    EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.4))
    EFFECT:EndMotionBlur()
  end
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(-1917381620)
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("MIRUHOGGU"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_QUESTION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("MIRUHOGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -314303963)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(-195089564)
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("MIRUHOGGU"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_QUESTION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -546146137)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  CH("MIRUHOGGU"):WalkTo(SymPos("P03_MIRUHOGGU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main08_yorunomimawarikyoutou03_end()
end
function main08_yorunomimawarikyoutou04_init()
end
function main08_yorunomimawarikyoutou04_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MIRUHOGGU"):WalkTo(SymPos("P00_MIRUHOGGU"), Speed(1.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("MIRUHOGGU"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  subEveLookAround(CH("MIRUHOGGU"), Speed(400))
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_QUESTION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("MIRUHOGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -966178330)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):WalkTo(SymPos("P01_MIRUHOGGU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main08_yorunomimawarikyoutou04_end()
end
function main08_yorunomimawarikyoutou05_init()
end
function main08_yorunomimawarikyoutou05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_02"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MIRUHOGGU"):WalkTo(SymPos("P00_MIRUHOGGU"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("MIRUHOGGU"):WaitMove()
  CH("MIRUHOGGU"):DirTo(RotateTarget(30), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  TASK:Sleep(TimeSec(0.7))
  CH("MIRUHOGGU"):DirTo(RotateTarget(-30), Speed(200), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("MIRUHOGGU"):WalkTo(SymPos("P01_MIRUHOGGU"), Speed(1.2))
  CH("MIRUHOGGU"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.2))
  local taskObake00 = function()
    EFFECT:StartMotionBlur(0, 0, 0)
    EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.4))
    EFFECT:ChangeMotionBlurAlpha(0.5, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.5))
    EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.4))
    EFFECT:EndMotionBlur()
  end
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(-1993810143)
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  CH("MIRUHOGGU"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  TASK:Sleep(TimeSec(0.7))
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE_02"), Volume(256))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(2, ACCEL_TYPE.HIGH, DECEL_TYPE.HIGH))
  subEveLookAround(CH("MIRUHOGGU"), Speed(400))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SysMsg(-1875644832)
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CH("MIRUHOGGU"):DirTo(RotateTarget(30), Speed(500), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_DOTEKKOTSU"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  TASK:Regist(subEveJumpSurprise, {
    CH("MIRUHOGGU")
  })
  TASK:Sleep(TimeSec(0.4))
  SCREEN_A:FadeOut(TimeSec(0), true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_GYAAAA"), Volume(256))
  CAMERA:SetShake(Vector2(0.06, 0.06), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1155613277)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
end
function main08_yorunomimawarikyoutou05_end()
end
