dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main06_dennryuunoyukue01_init()
end
function main06_dennryuunoyukue01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("ABAGOORA"):WalkTo(SymPos("P00_ABAGOORA"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1756627476, PARTNER_1 = -1907307347})
  subEveCloseMsg()
  CH("ABAGOORA"):WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), -1518493842)
  WINDOW:Talk(SymAct("ABAGOORA"), -1134121425)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -215533336, PARTNER_1 = -365164119})
  WINDOW:SwitchTalk({PARTNER_0 = -1055827350, PARTNER_1 = -670405845})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_QUESTION")
  CH("ABAGOORA"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("ABAGOORA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("ABAGOORA"), 1603434468)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_EXCLAMATION")
  CH("ABAGOORA"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), 1183401637)
  WINDOW:CloseMessage()
  CH("ABAGOORA"):DirTo(SymPos("P00_EXIT"), Speed(350), ROT_TYPE.RIGHT)
  CH("ABAGOORA"):WaitRotate()
  WINDOW:DrawFace(172, 8, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), 400877155)
  WINDOW:Talk(SymAct("ABAGOORA"), 251647778)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 634553569, PARTNER_1 = 1019852192})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_EXCLAMATION")
  CH("ABAGOORA"):WaitManpu()
  CH("ABAGOORA"):DirTo(CH("PARTNER"), Speed(500), ROT_TYPE.LEFT)
  CH("ABAGOORA"):WaitRotate()
  CH("ABAGOORA"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_FLY_SWEAT")
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  WINDOW:DrawFace(324, 20, SymAct("ABAGOORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("ABAGOORA"), 1938301799)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(324, 20, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), 1788023334)
  WINDOW:Talk(SymAct("ABAGOORA"), 1102987749)
  WINDOW:Talk(SymAct("ABAGOORA"), 1487237284)
  WINDOW:Talk(SymAct("ABAGOORA"), -549622677)
  WINDOW:CloseMessage()
  CH("ABAGOORA"):ResetManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -970564310, PARTNER_1 = 89213325})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("ABAGOORA"):WalkTo(SymPos("P01_ABAGOORA"), Speed(1.2))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P00_HERO"),
    Speed(1.5),
    SymPos("P01_ABAGOORA")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(SymPos("P01_ABAGOORA"), Speed(60), ROT_TYPE.NEAR)
  CH("ABAGOORA"):WaitMove()
  CH("ABAGOORA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.RIGHT)
  CH("ABAGOORA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), 474642636)
  WINDOW:Talk(SymAct("ABAGOORA"), 929508111)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 779885134, PARTNER_1 = 1631423625})
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveMoveDir2, {
    CH("ABAGOORA"),
    SymPos("P02_ABAGOORA"),
    Speed(1.2),
    SymPos("P02_ABAGOORA")
  })
  TASK:Sleep(TimeSec(1))
  CH("PARTNER"):ResetFacialMotion()
  TASK:Sleep(TimeSec(1.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 2015804872, PARTNER_1 = 1393290763})
  WINDOW:SwitchTalk({PARTNER_0 = 1242619722, PARTNER_1 = -846675067})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-728501564)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1108529432, PARTNER_1 = -1527373911})
  WINDOW:SwitchTalk({PARTNER_0 = -1881453462, PARTNER_1 = -1765769941})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -645796884, PARTNER_1 = -1063593299})
  WINDOW:SwitchTalk({PARTNER_0 = -340293266, PARTNER_1 = -223561681})
  WINDOW:CloseMessage()
  WINDOW:SysMsg(1966384352)
  WINDOW:SelectStart()
  WINDOW:SelectChain(1815057825, 1)
  WINDOW:SelectChain(540677713, 0)
  WINDOW:DefaultCursor(0)
  local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
  if id == 1 then
    SOUND:FadeOutBgm(TimeSec(0.5))
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    TASK:Sleep(TimeSec(0.5))
    return "select1"
  else
    SOUND:FadeOutBgm(TimeSec(0.5))
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    TASK:Sleep(TimeSec(0.2))
    return "select2"
  end
end
function main06_dennryuunoyukue01_end()
end
function groundEnd()
end
