dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_m09kaerimichi01_init()
end
function main09_m09kaerimichi01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KONOHANANOIE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.RIGHT)
  CH("HERO"):WaitRotate()
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1893605256, PARTNER_1 = -1774530247})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1122532614, PARTNER_1 = -1542671429})
  WINDOW:SwitchTalk({PARTNER_0 = -347265668, PARTNER_1 = -229239747})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -646232066, PARTNER_1 = -1067419969})
  WINDOW:SwitchTalk({PARTNER_0 = 1207462512, PARTNER_1 = 1591958321})
  subEveCloseMsg()
  while true do
    WINDOW:SysMsg(1641012686)
    WINDOW:SelectStart()
    WINDOW:SelectChain(2027220111, 1)
    WINDOW:SelectChain(1408876364, 0)
    WINDOW:DefaultCursor(0)
    local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
    if id == 0 then
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
      CH("PARTNER"):WaitManpu()
      WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
      WINDOW:SwitchTalk({PARTNER_0 = 1256361485, PARTNER_1 = 94574794})
      WINDOW:KeyWait()
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
      CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
      CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
      WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
      WINDOW:SwitchTalk({PARTNER_0 = 481831307, PARTNER_1 = 932543048})
      WINDOW:CloseMessage()
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
      CH("HERO"):SetManpu("MP_EXCLAMATION")
      CH("HERO"):WaitManpu()
      CAMERA:SetEye(SymCam("CAMERA_02"))
      CAMERA:SetTgt(SymCam("CAMERA_02"))
      CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
      TASK:Sleep(TimeSec(1.5))
      WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
      WINDOW:Monologue(781077257)
      WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
      WINDOW:Monologue(-1458153530)
      WINDOW:CloseMessage()
      CAMERA:SetEye(SymCam("CAMERA_01"))
      CAMERA:SetTgt(SymCam("CAMERA_01"))
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
      CH("PARTNER"):WaitManpu()
      WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
      WINDOW:SwitchTalk({PARTNER_0 = -1341299065, PARTNER_1 = 1937404448})
      WINDOW:CloseMessage()
    else
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("PARTNER"):ResetFacialMotion()
      break
    end
  end
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 1784759137, PARTNER_1 = 1095504034})
  WINDOW:SwitchTalk({PARTNER_0 = 1482105315, PARTNER_1 = 387364644})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(SymPos("P02_PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(SymPos("P02_PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 235767397, PARTNER_1 = 622908838})
  WINDOW:SwitchTalk({PARTNER_0 = 1010558183, PARTNER_1 = -1146882008})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1564948119, PARTNER_1 = -876210875})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P01_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -757259260, PARTNER_1 = -101681209})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -521451898, PARTNER_1 = -1347760063})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("PARTNER"):RunTo(SymPos("P02_PARTNER"), Speed(2.5))
  TASK:Sleep(TimeSec(0.7))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.2))
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main09_m09kaerimichi01_end()
end
function groundEnd()
end
