dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main18_dedennekaratsuushin01_init()
end
function main18_dedennekaratsuushin01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2.5))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2.5))
  CH("KONOHANA"):WalkTo(SymPos("P00_KONOHANA"), Speed(2.5))
  CH("AAKEN"):WalkTo(SymPos("P00_AAKEN"), Speed(2.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_TENSION_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNNE_ALERT"))
  WINDOW:SysMsg(-156318598)
  CH("AAKEN"):WaitManpu()
  SOUND:WaitSe(SymSnd("SE_EVT_DEDENNNE_ALERT"))
  subEveCloseMsg()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  local taskHero00 = function()
    CH("HERO"):DirTo(RotateTarget(135), Speed(200), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetMotion(SymMot("PUSH"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.2))
  local taskAaken00 = function()
    CH("AAKEN"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.NEAR)
    CH("AAKEN"):WaitRotate()
    TASK:Sleep(TimeSec(0.4))
    CH("AAKEN"):SetMotion(SymMot("PUSH"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.3))
    CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("AAKEN"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
    CH("AAKEN"):WaitRotate()
  end
  TASK:Regist(taskAaken00)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:SysMsg(-273287877)
  TASK:WaitTask()
  subEveCloseMsg()
  WINDOW:SysMsg(-996628744)
  WINDOW:SysMsg(-578578503)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(324, 20, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -1832779394)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1948700609, PARTNER_1 = -1594596356})
  CH("KONOHANA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:SwitchTalk({PARTNER_0 = -1175498051, PARTNER_1 = 1048006258})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("AAKEN"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 661421875)
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("AAKEN"), 1878663698)
  subEveCloseMsg()
  WINDOW:SysMsg(1994462035)
  WINDOW:SysMsg(1573666960)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 1154970065)
  subEveCloseMsg()
  WINDOW:SysMsg(194438934)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 311285335)
  WINDOW:Talk(SymAct("AAKEN"), 966821268)
  subEveCloseMsg()
  WINDOW:SysMsg(549172437)
  WINDOW:SysMsg(-1490835430)
  WINDOW:SysMsg(-1103586981)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("HERO"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):SetManpu("MP_NOTICE_L")
  CH("AAKEN"):SetManpu("MP_QUESTION")
  CH("AAKEN"):WaitManpu()
  CH("AAKEN"):DirTo(RotateTarget(-90), Speed(200), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:SysMsg(2102365692)
  WINDOW:SysMsg(1683274941)
  WINDOW:SysMsg(1333391230)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_SHOCK_L")
  CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):WaitManpu()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveJump, {
    CH("AAKEN")
  })
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 1449319999)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("AAKEN")
  })
  WINDOW:Talk(SymAct("AAKEN"), 421742840)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("AAKEN"), 3701177)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 722807418, PARTNER_1 = 839785275})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("AAKEN"), -1248458764)
  WINDOW:Talk(SymAct("AAKEN"), -1400031563)
  WINDOW:Talk(SymAct("AAKEN"), -973870439)
  WINDOW:Talk(SymAct("AAKEN"), -588719144)
  WINDOW:Talk(SymAct("AAKEN"), -138049509)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -287393446, PARTNER_1 = -1583403107})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("AAKEN"), -1199300900)
  WINDOW:Talk(SymAct("AAKEN"), -1817621217)
  WINDOW:Talk(SymAct("AAKEN"), -1968014242)
  WINDOW:CloseMessage()
  local taskHero00 = function()
    subEveNod(CH("HERO"))
  end
  local taskPartner00 = function()
    subEveNod(CH("PARTNER"))
  end
  local taskKonohana00 = function()
    subEveNod(CH("KONOHANA"))
  end
  TASK:Regist(taskHero00)
  TASK:Regist(taskPartner00)
  TASK:Regist(taskKonohana00)
  TASK:Sleep(TimeSec(0.8))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main18_dedennekaratsuushin01_end()
end
function groundEnd()
end
