dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_inisienohoneatochuukei1st01_init()
end
function main09_inisienohoneatochuukei1st01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Regist(Group("grpNyasupaa"), subEveMoveDir, {
    CH("NYASUPAA"),
    SymPos("P00_NYASUPAA"),
    Speed(1.5),
    RotateTarget(-90)
  })
  TASK:Regist(Group("grpShikijika"), subEveMoveDir, {
    CH("SHIKIJIKA_SPRING"),
    SymPos("P00_SHIKIJIKA"),
    Speed(1.5),
    RotateTarget(135)
  })
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P00_PARTNER"),
    Speed(1.5),
    RotateTarget(-135)
  })
  CH("NUMERA"):WalkTo(SymPos("P00_NUMERA"), Speed(1.5))
  SOUND:PlayBgm(SymSnd("SE_ENV_CLIFF_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask(Group("grpShikijika"))
  TASK:Sleep(TimeSec(0.2))
  subEveLookAround(CH("SHIKIJIKA_SPRING"), Speed(600))
  WINDOW:DrawFaceF(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1730597885)
  subEveCloseMsg()
  WINDOW:DrawFaceF(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -2117984958)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(500), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -1427157375, PARTNER_1 = -1275822144})
  WINDOW:SwitchTalk({PARTNER_0 = -55187193, PARTNER_1 = -441526202})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -830239867, PARTNER_1 = -677856572})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NUMERA"), 1342219787)
  subEveCloseMsg()
  CH("PARTNER"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.FAINT)
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.FAINT)
  WINDOW:SwitchTalk({PARTNER_0 = 1226544970, PARTNER_1 = 1071047824})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  WINDOW:DrawFace(324, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 651023825)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("NUMERA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Regist(subEveJump, {
    CH("NUMERA")
  })
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 232818194, PARTNER_1 = 352040787})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CH("NUMERA"):ResetFacialMotion()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1538924948, PARTNER_1 = 1117851861})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("NYASUPAA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("SHIKIJIKA_SPRING"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1770799894)
  WINDOW:Talk(SymAct("NYASUPAA"), 1888973399)
  WINDOW:Talk(SymAct("NYASUPAA"), -149983592)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main09_inisienohoneatochuukei1st01_end()
end
function groundEnd()
end
