dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main12_waiwaitownnoiriguchide01_init()
end
function main12_waiwaitownnoiriguchide01_start()
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CH("BURUU"):SetVisible(false)
  CH("KOROBOOSHI"):SetVisible(false)
  CH("SUKANPUU"):SetVisible(false)
  CH("RAPURASU"):SetShadow(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskMirutanku01 = function()
    CH("MIRUTANKU"):WalkTo(SymPos("P00_MIRUTANKU"), Speed(1.5))
    CH("MIRUTANKU"):WaitMove()
  end
  TASK:Regist(Group("grpMirutanku"), taskMirutanku01)
  local taskDoredyia01 = function()
    CH("NAZONOKUSA"):SetManpu("MP_SPREE_LP")
    CH("DOREDYIA"):WalkTo(SplinePath(SymPos("P00_DOREDYIA"), SymPos("P01_DOREDYIA")), Speed(1.5))
    TASK:Sleep(TimeSec(6.5))
    CH("NAZONOKUSA"):ResetManpu()
    TASK:Regist(subEveDoubleJump, {
      CH("NAZONOKUSA")
    })
    CH("DOREDYIA"):WaitMove()
    CH("DOREDYIA"):DirTo(CH("NAZONOKUSA"), Speed(350), ROT_TYPE.NEAR)
    CH("DOREDYIA"):WaitRotate()
    CH("DOREDYIA"):SetManpu("MP_SPREE_LP")
    TASK:Sleep(TimeSec(0.5))
    CH("DOREDYIA"):ResetManpu()
    CH("NAZONOKUSA"):DirTo(CH("DOREDYIA"), Speed(350), ROT_TYPE.NEAR)
    CH("NAZONOKUSA"):WaitRotate()
    TASK:Regist(subEveDoubleJump, {
      CH("NAZONOKUSA")
    })
    TASK:Sleep(TimeSec(0.5))
    CH("NAZONOKUSA"):SetManpu("MP_LAUGH_LP")
    TASK:Sleep(TimeSec(1.5))
    CH("NAZONOKUSA"):ResetManpu()
    CH("NAZONOKUSA"):DirTo(CH("KAKUREON"), Speed(350), ROT_TYPE.NEAR)
    CH("NAZONOKUSA"):WaitRotate()
  end
  TASK:Regist(taskDoredyia01)
  local taskDoodoo00 = function()
    CH("DOODOO"):WalkTo(SplinePath(SymPos("P00_DOODOO"), SymPos("P01_DOODOO")), Speed(1.5))
    CH("DOODOO"):WaitMove()
    CH("DOODOO"):SetVisible(false)
  end
  TASK:Regist(taskDoodoo00)
  local taskPuraMai00 = function()
    function TaskL.Loop()
      CH("MAINAN"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(2))
      CH("MAINAN"):ResetManpu()
      TASK:Sleep(TimeSec(0.3))
      CH("PURASURU"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(1.5))
      CH("PURASURU"):ResetManpu()
      TASK:Sleep(TimeSec(0.5))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskPuraMai00)
  local taskDesuWaru00 = function()
    function TaskL.Loop()
      CH("DESUKAAN"):SetManpu("MP_SPREE_LP")
      CH("DESUKAAN"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
      CH("DESUKAAN"):WaitPlayMotion()
      CH("DESUKAAN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(1))
      CH("WARUBIRU"):ResetManpu()
      CH("WARUBIRU"):SetNeckRot(RotateTarget(30), RotateTarget(0), RotateTarget(0), TimeSec(0.1))
      CH("WARUBIRU"):WaitNeckRot()
      CH("WARUBIRU"):SetNeckRot(RotateTarget(-30), RotateTarget(0), RotateTarget(0), TimeSec(0.15))
      CH("WARUBIRU"):WaitNeckRot()
      CH("WARUBIRU"):SetNeckRot(RotateTarget(30), RotateTarget(0), RotateTarget(0), TimeSec(0.15))
      CH("WARUBIRU"):WaitNeckRot()
      CH("WARUBIRU"):SetNeckRot(RotateTarget(-30), RotateTarget(0), RotateTarget(0), TimeSec(0.15))
      CH("WARUBIRU"):WaitNeckRot()
      CH("WARUBIRU"):ResetNeckRot(TimeSec(0.1))
      CH("WARUBIRU"):WaitNeckRot()
      TASK:Sleep(TimeSec(2))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskDesuWaru00)
  SOUND:PlayBgm(SymSnd("BGM_EVE_WAIWAITOWN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(3))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:WaitTask(Group("grpMirutanku"))
  local taskMassuguma00 = function()
    CH("MASSUGUMA"):WalkTo(SplinePath(SymPos("P00_MASSUGUMA"), SymPos("P01_MASSUGUMA")), Speed(1.5))
    CH("MASSUGUMA"):WaitMove()
    CH("MASSUGUMA"):SetVisible(false)
  end
  TASK:Regist(taskMassuguma00)
  local taskMirutanku02 = function()
    CH("MIRUTANKU"):SetPosition(SymPos("P00_MIRUTANKU"))
    CH("MIRUTANKU"):SetVisible(true)
    CH("MIRUTANKU"):WalkTo(SymPos("P01_MIRUTANKU"), Speed(1.5))
    CH("MIRUTANKU"):WaitMove()
    CH("MIRUTANKU"):SetVisible(false)
  end
  TASK:Regist(Group("grpMirutanku"), taskMirutanku02)
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(4))
  TASK:WaitTask(Group("grpMirutanku"))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(3))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):RunTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(3))
  CH("HERO"):RunTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(3))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1.5))
  local taskMirutanku03 = function()
    CH("MIRUTANKU"):SetPosition(SymPos("P01_MIRUTANKU"))
    CH("MIRUTANKU"):SetVisible(true)
    CH("MIRUTANKU"):WalkTo(SymPos("P02_MIRUTANKU"), Speed(1.5))
    CH("MIRUTANKU"):WaitMove()
    CH("MIRUTANKU"):SetVisible(false)
  end
  TASK:Regist(taskMirutanku03)
  local taskYamikarasu00 = function()
    function TaskL.Loop()
      CH("YAMIKARASU_TOWN"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(1.5))
      CH("YAMIKARASU_TOWN"):ResetManpu()
      TASK:Sleep(TimeSec(0.5))
      subEveNodDouble(CH("YAMIKARASU_TOWN"))
      TASK:Sleep(TimeSec(0.5))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskYamikarasu00)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1347397458, PARTNER_1 = -1230280209})
  WINDOW:SwitchTalk({PARTNER_0 = -1652147668, PARTNER_1 = -2070082707})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  local taskKorobooshi01 = function()
    CH("KOROBOOSHI"):SetVisible(true)
    CH("KOROBOOSHI"):WalkTo(SymPos("P00_KOROBOOSHI"), Speed(1.5))
    CH("KOROBOOSHI"):WaitMove()
    CH("KOROBOOSHI"):SetVisible(false)
  end
  TASK:Regist(taskKorobooshi01)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -874734166, PARTNER_1 = -758666005})
  WINDOW:SwitchTalk({PARTNER_0 = -102039768, PARTNER_1 = -521023895})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.8))
  CH("PARTNER"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  local taskBuruu00 = function()
    CH("BURUU"):SetVisible(true)
    CH("BURUU"):WalkTo(SymPos("P00_BURUU"), Speed(1.5))
    CH("BURUU"):WaitMove()
    CH("BURUU"):SetManpu("MP_NOTICE_R")
    CH("BURUU"):WaitManpu()
  end
  TASK:Regist(Group("grpBuruu"), taskBuruu00)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:MoveFollow2(SymCam("CAMERA_08"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P02_PARTNER"),
    Speed(1.5),
    CH("BURUU")
  })
  CH("HERO"):DirTo(SymPos("P00_BURUU"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1734988454, PARTNER_1 = 2121458663})
  TASK:WaitTask(Group("grpBuruu"))
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("BURUU"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("BURUU"), 1930929272)
  WINDOW:Talk(SymAct("BURUU"), 1779209529)
  WINDOW:CloseMessage()
  CH("BURUU"):ResetManpu()
  local taskSukanpuu01 = function()
    CH("SUKANPUU"):SetVisible(true)
    CH("SUKANPUU"):WalkTo(SymPos("P00_SUKANPUU"), Speed(1.5))
    CH("SUKANPUU"):WaitMove()
    CH("SUKANPUU"):SetVisible(false)
  end
  TASK:Regist(taskSukanpuu01)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1092732666, PARTNER_1 = 1480259515})
  WINDOW:SwitchTalk({PARTNER_0 = 393961852, PARTNER_1 = 241193021})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURUU"), 625804286)
  WINDOW:Talk(SymAct("BURUU"), 1012282047)
  WINDOW:Talk(SymAct("BURUU"), -1144115600)
  WINDOW:CloseMessage()
  CH("BURUU"):WalkTo(SymPos("P01_BURUU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):RunTo(SymPos("P03_PARTNER"), Speed(2))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(2.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  CAMERA:WaitMove()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1563091151, PARTNER_1 = 1638009750})
  WINDOW:SwitchTalk({PARTNER_0 = 2025405143, PARTNER_1 = 1402235156})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  CH("PARTNER"):RunTo(PosOffs(10, 0), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):RunTo(PosOffs(10, 0), Speed(3))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main12_waiwaitownnoiriguchide01_end()
end
function groundEnd()
end
