dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function sub01_myuuisourou01_init()
end
function sub01_myuuisourou01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -631708546)
  WINDOW:Talk(SymAct("AAKEN"), -1018964673)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -395409668)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("KUCHIITO"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -243943491)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(324, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1103879814)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_05"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BUIZERU"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):WaitRotate()
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("BUIZERU")
  })
  WINDOW:DrawFace(20, 20, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("BUIZERU"), -1490087877)
  WINDOW:CloseMessage()
  CH("BUIZERU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("KUCHIITO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("DEDENNE"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("BUIZERU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PEROPPAFU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1946008584)
  WINDOW:Talk(SymAct("DENRYUU"), -1793494343)
  WINDOW:Talk(SymAct("DENRYUU"), 310472310)
  WINDOW:Talk(SymAct("DENRYUU"), 194666295)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  CH("DENRYUU"):DirTo(CH("HORUBII"), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 821619496)
  WINDOW:Talk(SymAct("DENRYUU"), 702798441)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("HORUBII"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("HORUBII")
  })
  WINDOW:DrawFace(272, 16, SymAct("HORUBII"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HORUBII"), 47090090)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), 466991339)
  WINDOW:Talk(SymAct("DEDENNE"), 1418997292)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):DirTo(CH("DEDENNE"), Speed(60), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("JIRAACHI"):SetManpu("MP_FLY_SWEAT")
  CH("JIRAACHI"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), 1301225325)
  WINDOW:Talk(SymAct("JIRAACHI"), 1721912494)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 88, SymAct("AAKEN"), FACE_TYPE.HAPPY)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Talk(SymAct("AAKEN"), 2142862831)
  subEveCloseMsg()
  CH("KUCHIITO"):SetManpu("MP_LAUGH_LP")
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KUCHIITO"), -132030176)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -516272031)
  WINDOW:CloseMessage()
  CH("KUCHIITO"):ResetManpu()
  CH("KUCHIITO"):ResetFacialMotion()
  CH("AAKEN"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  CH("DEDENNE"):ResetFacialMotion()
  CH("HORUBII"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.1))
  CH("DENRYUU"):DirTo(RotateTarget(170), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("KUCHIITO"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PEROPPAFU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PEROPPAFU"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 575489222)
  WINDOW:Talk(SymAct("DENRYUU"), 995521927)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("MYUU"):SetManpu("MP_SPREE_LP")
  CH("MYUU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("MYUU")
  })
  WINDOW:DrawFace(20, 20, SymAct("MYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MYUU"), 276506180)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskHorubii00 = function()
    function TaskL.Loop()
      CH("HORUBII"):SetManpu("MP_SPREE_LP")
      TASK:Regist(subEveDoubleJump, {
        CH("HORUBII")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Regist(subEveDoubleJump, {
        CH("HORUBII")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("HORUBII"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
    end
    function TaskL.Finish()
      CH("HORUBII"):ResetManpu()
      return
    end
  end
  TASK:Regist(Group("grpHorubii"), taskHorubii00)
  local taskAaJira00 = function()
    function TaskL.Loop()
      CH("AAKEN"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("AAKEN"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("JIRAACHI"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("JIRAACHI"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("AAKEN"):ResetManpu()
      TASK:Sleep(TimeSec(0.2))
      CH("JIRAACHI"):ResetManpu()
      return
    end
  end
  TASK:Regist(Group("grpAajira"), taskAaJira00)
  local taskBuipero00 = function()
    function TaskL.Loop()
      CH("BUIZERU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("BUIZERU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PEROPPAFU"):SetManpu("MP_LAUGH_LP")
      subEveDoubleJump(CH("PEROPPAFU"))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PEROPPAFU"):ResetManpu()
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("BUIZERU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("PEROPPAFU"):ResetManpu()
      return
    end
  end
  TASK:Regist(Group("grpBuipero"), taskBuipero00)
  CH("KUCHIITO"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.5))
  WINDOW:NarrationBottomFrame(TimeSec(0.5), TimeSec(0.5), 157292293)
  WINDOW:NarrationBottomFrame(TimeSec(0.5), TimeSec(0.5), 1176601026)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function sub01_myuuisourou01_end()
end
function groundEnd()
end
