dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main15_ensokuzennya01_init()
end
function main15_ensokuzennya01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  elseif pokemonIndexHero == 5 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  end
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_03"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 2118908511)
  WINDOW:Talk(SymAct("DEDENNE"), 1733348126)
  WINDOW:CloseMessage()
  CH("DEDENNE"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"))
  local taskPartner00 = function()
    CH("PARTNER"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
    CH("PARTNER"):SetMotionRaito(Raito(2))
    CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
    CH("PARTNER"):SetManpu("MP_SPREE_LP")
  end
  TASK:Regist(taskPartner00)
  local taskHorubii00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("HORUBII"):WaitPlayMotion()
    CH("HORUBII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("HORUBII"):SetManpu("MP_SPREE_LP")
    TASK:Regist(subEveDoubleJump, {
      CH("HORUBII")
    })
  end
  TASK:Regist(taskHorubii00)
  local taskHero00 = function()
    CH("HERO"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
    CH("HERO"):SetManpu("MP_LAUGH_LP")
    TASK:Regist(subEveDoubleJump, {
      CH("HERO")
    })
    TASK:Sleep(TimeSec(0.5))
    TASK:Regist(subEveDoubleJump, {
      CH("HERO")
    })
  end
  TASK:Regist(taskHero00)
  local taskBuizeru00 = function()
    TASK:Sleep(TimeSec(0.1))
    CH("BUIZERU"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("BUIZERU"):WaitPlayMotion()
    CH("BUIZERU"):SetManpu("MP_SPREE_LP")
    CH("BUIZERU"):SetMotionRaito(Raito(2))
    CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
    CH("BUIZERU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Regist(subEveDoubleJump, {
      CH("BUIZERU")
    })
    TASK:Sleep(TimeSec(0.7))
    TASK:Regist(subEveDoubleJump, {
      CH("BUIZERU")
    })
  end
  TASK:Regist(taskBuizeru00)
  local taskAaken00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("AAKEN"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("AAKEN"):WaitPlayMotion()
    CH("AAKEN"):SetManpu("MP_SPREE_LP")
    CH("AAKEN"):SetMotionRaito(Raito(2))
    CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
    CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Regist(subEveDoubleJump, {
      CH("AAKEN")
    })
    TASK:Sleep(TimeSec(0.7))
    TASK:Regist(subEveDoubleJump, {
      CH("AAKEN")
    })
  end
  TASK:Regist(taskAaken00)
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("JIRAACHI")
  })
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 1283299549)
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(1))
  CH("BUIZERU"):ResetFacialMotion()
  CH("BUIZERU"):ResetManpu()
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):ResetManpu()
  WINDOW:KeyWait()
  CH("AAKEN"):ResetFacialMotion()
  CH("AAKEN"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  CH("HERO"):ResetFacialMotion()
  CH("HERO"):ResetManpu()
  WINDOW:Talk(SymAct("DEDENNE"), 1432791452)
  WINDOW:Talk(SymAct("DEDENNE"), 438779739)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 54267418)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PEROPPAFU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("KUCHIITO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  TASK:Sleep(TimeSec(0.7))
  CH("DEDENNE"):SetManpu("MP_SPREE_LP")
  CH("AAKEN"):SetManpu("MP_SPREE_LP")
  CH("HORUBII"):SetManpu("MP_SPREE_LP")
  CH("BUIZERU"):SetManpu("MP_SPREE_LP")
  CH("PEROPPAFU"):SetManpu("MP_SPREE_LP")
  CH("KUCHIITO"):SetManpu("MP_SPREE_LP")
  CH("JIRAACHI"):SetManpu("MP_SPREE_LP")
  CH("HERO"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("DEDENNE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("AAKEN"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("HORUBII"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("BUIZERU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("PEROPPAFU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("KUCHIITO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("JIRAACHI"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("HERO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("PARTNER"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  WINDOW:SysMsg(672226777)
  CH("PARTNER"):WaitPlayMotion()
  WINDOW:CloseMessage()
  CH("DEDENNE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HORUBII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("BUIZERU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PEROPPAFU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("KUCHIITO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("JIRAACHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DEDENNE"):ResetManpu()
  CH("AAKEN"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  CH("BUIZERU"):ResetManpu()
  CH("PEROPPAFU"):ResetManpu()
  CH("KUCHIITO"):ResetManpu()
  CH("HERO"):ResetManpu()
  CH("PARTNER"):ResetManpu()
  CH("JIRAACHI"):ResetManpu()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_GATSUGATSU_LP"), Volume(256))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("HORUBII"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PEROPPAFU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("DENRYUU"):SetManpu("EV_EAT_LP")
  CH("DENRYUU"):SetMotionRaito(Raito(2))
  CH("DENRYUU"):SetMotion(SymMot("EV014_EAT00"), LOOP.ON)
  CH("HERO"):SetManpu("EV_EAT_LP")
  CH("HERO"):SetMotionRaito(Raito(2))
  CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("AAKEN"):SetManpu("EV_EAT_LP")
  CH("AAKEN"):SetMotionRaito(Raito(2))
  CH("AAKEN"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("HORUBII"):SetManpu("EV_EAT_LP")
  CH("HORUBII"):SetMotionRaito(Raito(2))
  CH("HORUBII"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("EV_EAT_LP")
  CH("DEDENNE"):SetMotionRaito(Raito(2))
  CH("DEDENNE"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("PARTNER"):SetManpu("EV_EAT_LP")
  CH("PARTNER"):SetMotionRaito(Raito(2))
  CH("PARTNER"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("JIRAACHI"):SetManpu("EV_EAT_LP")
  CH("JIRAACHI"):SetMotionRaito(Raito(2))
  CH("JIRAACHI"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("PEROPPAFU"):SetManpu("EV_EAT_LP")
  CH("PEROPPAFU"):SetMotionRaito(Raito(2))
  CH("PEROPPAFU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):SetManpu("EV_EAT_LP")
  CH("BUIZERU"):SetMotionRaito(Raito(2))
  CH("BUIZERU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("KUCHIITO"):SetManpu("EV_EAT_LP")
  CH("KUCHIITO"):SetMotionRaito(Raito(2))
  CH("KUCHIITO"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  WINDOW:SysMsg(822766744)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1231916969)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1349959402)
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  SOUND:FadeOutSe(SymSnd("SE_EVT_GATSUGATSU_LP"), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function main15_ensokuzennya01_end()
end
function main15_ensokuzennya02_init()
end
function main15_ensokuzennya02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_04"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1181247419, PARTNER_1 = 1601394426})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("PARTNER"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1952318777, PARTNER_1 = 1833251960})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 570729151, PARTNER_1 = 991925246})
  WINDOW:KeyWait()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 271761469, PARTNER_1 = 153743740})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(1), true)
end
function main15_ensokuzennya02_end()
end
function main15_ensokuzennya03_init()
end
function main15_ensokuzennya03_start()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1900941901)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetDir(RotateTarget(-45))
  CH("PARTNER"):SetDir(RotateTarget(45))
  CH("HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP02"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV001_SLEEP02"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.25))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1750409998, PARTNER_1 = 1423820885})
  WINDOW:KeyWait()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1304885524, PARTNER_1 = 1726720727})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main15_ensokuzennya03_end()
end
function groundEnd()
end
