dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 62408293, PARTNER_1 = 446920484})
  WINDOW:SwitchTalk({PARTNER_0 = 831399143, PARTNER_1 = 680859046})
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("JIRAACHI"), 1741980513)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SEREBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SEREBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SEREBII"), 2127540768)
  WINDOW:Talk(SymAct("SEREBII"), 1440932323)
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("NYASUPAA"), 1291440290)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), -882783123)
  WINDOW:Talk(SymAct("DENRYUU"), -763691732)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MV_STAGING_POST_BACK()
  WINDOW:SysMsg(-1592378474)
  WINDOW:CloseMessage()
end
