dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -2060035343, PARTNER_1 = -1674744912})
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("JIRAACHI"), -1224722317)
  WINDOW:CloseMessage()
end
function SEREBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SEREBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SEREBII"), -1373959886)
  WINDOW:Talk(SymAct("SEREBII"), -514154507)
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -129913164)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("NYASUPAA"), -747831945)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -898118602)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), 1307562233)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
