dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  CH(chSymb0):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 20, SymAct(chSymb0), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 2076638012, PARTNER_1 = 1658702461})
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.2))
  CH(chSymb0):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb0):ResetFacialMotion()
end
function NUMERA(chSymb0)
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NUMERA"), 1240504766)
  WINDOW:CloseMessage()
end
function SHIKIJIKA_SPRING(chSymb0)
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1357621503)
  TASK:WaitTask()
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 531250744)
  WINDOW:Talk(SymAct("NYASUPAA"), 112267129)
  WINDOW:CloseMessage()
end
