dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main06_tsunagariorb01_init()
end
function main06_tsunagariorb01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("KAKUREON"):SetManpu("MP_LAUGH_LP")
  CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(272, 16, SymAct("KAKUREON"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KAKUREON"), -1086545199)
  WINDOW:CloseMessage()
  CH("KAKUREON"):ResetManpu()
  CH("KAKUREON"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1507355760, PARTNER_1 = -1928675245})
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("KAKUREON"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1810763502)
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KAKUREON"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("KAKUREON")
  })
  CH("KAKUREON"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("KAKUREON"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KAKUREON"), -615487531)
  WINDOW:Talk(SymAct("KAKUREON"), -1035250028)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -379189929, PARTNER_1 = -260230122})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(272, 16, SymAct("KAKUREON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAKUREON"), 2011506905)
  WINDOW:Talk(SymAct("KAKUREON"), 1862146456)
  WINDOW:Talk(SymAct("KAKUREON"), -2032612657)
  WINDOW:Talk(SymAct("KAKUREON"), -1614546034)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1259427763, PARTNER_1 = -1376413428})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(272, 16, SymAct("KAKUREON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAKUREON"), -491515957)
  WINDOW:Talk(SymAct("KAKUREON"), -72401270)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -796758711, PARTNER_1 = -912696312})
  WINDOW:CloseMessage()
  CH("RATTA"):SetManpu("MP_NOTICE_R")
  CH("RATTA"):WaitManpu()
  CH("RATTA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1308704967, PARTNER_1 = 1461350790})
  WINDOW:SwitchTalk({PARTNER_0 = -1804770015, PARTNER_1 = -1921624992})
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("KAKUREON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAKUREON"), -1503983709)
  WINDOW:Talk(SymAct("KAKUREON"), -1086310686)
  WINDOW:Talk(SymAct("KAKUREON"), -268328923)
  WINDOW:Talk(SymAct("KAKUREON"), -384134812)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1036533081, PARTNER_1 = -617810970})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("RATTA"):WalkTo(SymPos("P00_RATTA"), Speed(1.5))
  CH("RATTA"):WaitMove()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
    CH("KAKUREON"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), 1555361577)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("RATTA"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.LEFT)
  CH("RATTA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), 1169153640)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("RATTA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.RIGHT)
  CH("RATTA"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 751895108, PARTNER_1 = 902443781})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_00"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("KAKUREON"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 518480070, PARTNER_1 = 133976455})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.7))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
end
function main06_tsunagariorb01_end()
end
function groundEnd()
end
