dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main04_yumewowarawareru01_init()
end
function main04_yumewowarawareru01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KAMONEGI"):SetVisible(false)
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):SetManpu("MP_ANGRY_LP")
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(-147761849)
  CH("HERO"):WaitManpu()
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(-299211770)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHILDREN_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-989382715)
  subEveCloseMsg()
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("YANCHAMU"), -602143100)
  WINDOW:Talk(SymAct("YANCHAMU"), -1822584765)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetManpu()
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1975082750)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1586761023)
  subEveCloseMsg()
  CH("CHOBOMAKI"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = -1200569472, PARTNER_1 = 1072226127})
  WINDOW:SwitchTalk({PARTNER_0 = 653520398, PARTNER_1 = -2112173855})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HERO"):SetPosition(SymPos("P01_HERO"))
  CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.2))
  CH("YANCHAMU"):ResetFacialMotion()
  CH("YANCHAMU"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CH("CHOBOMAKI"):ResetFacialMotion()
  CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(72, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -1694369376)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = -1339250077, PARTNER_1 = -1455973598})
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetManpu()
  CH("YANCHAMU"):ResetFacialMotion()
  CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):ResetManpu()
  CH("CHOBOMAKI"):ResetFacialMotion()
  CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -428470811)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -9618268)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -733974681, PARTNER_1 = -849650138})
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1254310633)
  WINDOW:Talk(SymAct("YANCHAMU"), 1406694312)
  WINDOW:Talk(SymAct("YANCHAMU"), -1867553009)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(272, 272, SymAct("YANCHAMU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("YANCHAMU"), -1984670130)
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(-1567029875)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  CH("KAMONEGI"):SetVisible(true)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:SysMsg(-1149094708)
  CH("YANCHAMU"):ResetManpu()
  CH("YANCHAMU"):ResetFacialMotion()
  CH("YANCHAMU"):SetManpu("MP_NOTICE_L")
  CH("YANCHAMU"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):ResetManpu()
  CH("CHOBOMAKI"):ResetFacialMotion()
  CH("CHOBOMAKI"):SetManpu("MP_EXCLAMATION")
  CH("CHOBOMAKI"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("KAMONEGI"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(324, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -188505589)
  WINDOW:Talk(SymAct("KAMONEGI"), -304573622)
  WINDOW:CloseMessage()
  CH("KAMONEGI"):ResetManpu()
  CH("KAMONEGI"):WalkTo(SymPos("P00_KAMONEGI"), Speed(1.2))
  CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskZorozoro00 = function()
    CH("NUMERA"):WalkTo(SymPos("P00_NUMERA"), Speed(1.5))
    CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(1.5))
    TASK:Sleep(TimeSec(0.2))
    CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(1.5))
    TASK:Sleep(TimeSec(0.1))
    CH("CHOBOMAKI"):WalkTo(SymPos("P00_CHOBOMAKI"), Speed(1.5))
    TASK:Sleep(TimeSec(0.2))
    CH("YANCHAMU"):WalkTo(SymPos("P00_YANCHAMU"), Speed(1.5))
    TASK:Sleep(TimeSec(0.5))
    CH("HERO"):WalkTo(SymPos("P03_HERO"), Speed(1.5))
  end
  TASK:Regist(taskZorozoro00)
  CH("KAMONEGI"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("KAMONEGI"):SetManpu("MP_NOTICE_L")
  CH("KAMONEGI"):WaitManpu()
  CH("KAMONEGI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("KAMONEGI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -956972919)
  WINDOW:Talk(SymAct("KAMONEGI"), -537988664)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):SetPosition(SymPos("P01_SHIKIJIKA"))
  CH("NUMERA"):SetPosition(SymPos("P01_NUMERA"))
  CH("NYASUPAA"):SetPosition(SymPos("P01_NYASUPAA"))
  CH("YANCHAMU"):SetPosition(SymPos("P01_YANCHAMU"))
  CH("CHOBOMAKI"):SetPosition(SymPos("P01_CHOBOMAKI"))
  CH("SHIKIJIKA_SPRING"):SetDir(CH("PARTNER"))
  CH("NUMERA"):SetDir(CH("PARTNER"))
  CH("NYASUPAA"):SetDir(CH("PARTNER"))
  CH("YANCHAMU"):SetDir(CH("PARTNER"))
  CH("CHOBOMAKI"):SetDir(CH("PARTNER"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 1484188935, PARTNER_1 = 1097718854})
  WINDOW:SwitchTalk({PARTNER_0 = 672333930, PARTNER_1 = 822620459})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
  CH("PARTNER"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 438657768, PARTNER_1 = 54416297})
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = 1283442030, PARTNER_1 = 1432679471})
  TASK:WaitTask()
  WINDOW:KeyWait()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  WINDOW:SwitchTalk({PARTNER_0 = 2118756332, PARTNER_1 = 1733465773})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -523597214)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -103695581, PARTNER_1 = -1245431597})
  subEveCloseMsg()
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -1394669166)
  WINDOW:Talk(SymAct("KAMONEGI"), -2014160303)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1628869872, PARTNER_1 = -777454121})
  WINDOW:KeyWait()
  CH("PARTNER"):SetManpu("MP_LAUGH_LP")
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -927740778, PARTNER_1 = -476143787})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("KAMONEGI"):SetManpu("MP_SWEAT_R")
  CH("KAMONEGI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("KAMONEGI"), -91902444)
  WINDOW:Talk(SymAct("KAMONEGI"), 2099098331)
  subEveCloseMsg()
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1678148506, PARTNER_1 = 225992630})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("KAMONEGI"):DirTo(SymPos("P01_PARTNER"), Speed(60), ROT_TYPE.NEAR)
  CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(1.5))
  TASK:Sleep(TimeSec(1))
  CH("HERO"):WalkTo(SymPos("P04_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetDir(SymPos("P01_PARTNER"))
  CH("NUMERA"):SetDir(SymPos("P01_PARTNER"))
  CH("NYASUPAA"):SetDir(SymPos("P01_PARTNER"))
  CH("YANCHAMU"):SetDir(SymPos("P01_PARTNER"))
  CH("CHOBOMAKI"):SetDir(SymPos("P01_PARTNER"))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(RotateTarget(-125), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 342060791, PARTNER_1 = 1062092084})
  WINDOW:SwitchTalk({PARTNER_0 = 643107957, PARTNER_1 = 1762958002})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1880075251)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KAMONEGI"):SetManpu("MP_FLY_SWEAT")
  CH("KAMONEGI"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("KAMONEGI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KAMONEGI"), 1529018416)
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir, {
    CH("KAMONEGI"),
    SymPos("P01_KAMONEGI"),
    Speed(1.5),
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(SymPos("P01_KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P01_KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):DirTo(SymPos("P01_KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(SymPos("P01_KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.3))
  CH("KAMONEGI"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1111083377)
  WINDOW:CloseMessage()
  CH("KAMONEGI"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_SPREE_LP")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
  CH("CHOBOMAKI"):SetManpu("MP_SPREE_LP")
  CH("NUMERA"):SetManpu("MP_SPREE_LP")
  CH("YANCHAMU"):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymWord(2093398760), -979249730)
  WINDOW:CloseMessage()
  CH("HERO"):ResetManpu()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  CH("PARTNER"):ResetManpu()
  CH("NYASUPAA"):ResetManpu()
  CH("CHOBOMAKI"):ResetManpu()
  CH("NUMERA"):ResetManpu()
  CH("YANCHAMU"):ResetManpu()
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function main04_yumewowarawareru01_end()
end
function main04_yumewowarawareru02_init()
end
function main04_yumewowarawareru02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -591731457)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_03"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.2))
  CH("MIRUHOGGU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 533590104)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 114737433)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 771461850)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("MIRUHOGGU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 887137179)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  CH("MIRUHOGGU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 2074162524)
  WINDOW:CloseMessage()
  local taskLookAt01 = function()
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1656357917, PARTNER_1 = 1234655198})
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 20, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1351378591)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -686523824)
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:Talk(SymAct("MIRUHOGGU"), -837858543)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("MIRUHOGGU"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  local taskLookAt02 = function()
    CH("HERO"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("CHOBOMAKI"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("YANCHAMU"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("MIRUHOGGU"), Speed(200), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("MIRUHOGGU"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  local taskMiruhogguZ = function()
    CH("MIRUHOGGU"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetMotion(SymMot("CHARGE"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    SOUND:PlaySe(SymSnd("SE_EVT_SMZ"))
    CH("MIRUHOGGU"):SetMotion(SymMot("ATTACK"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.5))
    subEveFlash2()
  end
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1485727939)
  WINDOW:KeyWait()
  CH("MIRUHOGGU"):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1100306820)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("MIRUHOGGU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Regist(taskMiruhogguZ)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1790446145)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SWEAT_L")
  CH("YANCHAMU"):SetManpu("MP_SWEAT_L")
  CH("HERO"):SetManpu("MP_SWEAT_L")
  CH("CHOBOMAKI"):SetManpu("MP_SWEAT_L")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SWEAT_L")
  CH("NYASUPAA"):SetManpu("MP_SWEAT_L")
  CH("NUMERA"):SetManpu("MP_SWEAT_L")
  CH("NUMERA"):WaitManpu()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1940077314)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1021488583)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -637115528)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt03 = function()
    CH("HERO"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("SHIKIJIKA_SPRING"):DirTo(CH("MIRUHOGGU"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt03)
  local taskMiruhogguX = function()
    CH("MIRUHOGGU"):SetMotion(SymMot("ATTACK_ROUND"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetMotion(SymMot("CHARGE"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    SOUND:PlaySe(SymSnd("SE_EVT_SMX"))
    CH("MIRUHOGGU"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
    TASK:Sleep(TimeSec(0.5))
  end
  CH("MIRUHOGGU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -248827717)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("MIRUHOGGU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_04_5"))
  CAMERA:SetTgt(SymCam("CAMERA_04_5"))
  TASK:Regist(taskMiruhogguX)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -399506950)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SWEAT_L")
  CH("YANCHAMU"):SetManpu("MP_SWEAT_L")
  CH("HERO"):SetManpu("MP_SWEAT_L")
  CH("CHOBOMAKI"):SetManpu("MP_SWEAT_L")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SWEAT_L")
  CH("NYASUPAA"):SetManpu("MP_SWEAT_L")
  CH("NUMERA"):SetManpu("MP_SWEAT_L")
  CH("NUMERA"):WaitManpu()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("MIRUHOGGU"):SetMotion(SymMot("EV005_RISE"), LOOP.OFF)
  CH("MIRUHOGGU"):WaitPlayMotion()
  CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  local taskLookAt04 = function()
    TASK:Sleep(TimeSec(0.5))
    CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.4))
    CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(200), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.4))
    CH("PARTNER"):DirTo(CH("YANCHAMU"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt04)
  local taskChobomaki00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("CHOBOMAKI"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):WaitManpu()
    TASK:Sleep(TimeSec(0.3))
    CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
    CH("CHOBOMAKI"):WaitManpu()
  end
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1873288501)
  WINDOW:KeyWait()
  TASK:Regist(taskChobomaki00)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1991453812)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -15562901)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -435571158)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -853219863)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  local taskYanPa00 = function()
    CH("YANCHAMU"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
    CH("YANCHAMU"):WaitPlayMotion()
    CH("YANCHAMU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.5))
    CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
    CH("NUMERA"):WaitManpu()
  end
  CH("SHIKIJIKA_SPRING"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  TASK:Regist(taskYanPa00)
  WINDOW:DrawFace(20, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -734014296)
  subEveCloseMsg()
  subEveNod(CH("NYASUPAA"))
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1686224273)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):WalkTo(SplinePath(SymPos("P00_NYASUPAA"), SymPos("P01_NYASUPAA"), SymPos("P02_NYASUPAA")), Speed(1.5))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("MIRUHOGGU"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):DirTo(SymPos("P01_NYASUPAA"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(200), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = -2107280594, PARTNER_1 = -1454890771})
  TASK:WaitTask()
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("YANCHAMU"):WalkTo(SymPos("P00_YANCHAMU"), Speed(1.2))
  CH("YANCHAMU"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), -1336733268)
  CH("YANCHAMU"):WaitMove()
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.2))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = 936054115, PARTNER_1 = 785398818})
  CH("PARTNER"):WaitMove()
  subEveCloseMsg()
  CH("YANCHAMU"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), 1202642958)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetManpu()
  GROUND:MoveItemBagToBox()
  OverFlow_AddOverflowCheckItem(101, 3, false)
  OverFlow_AddOverflowCheckItem(113, 3, false)
  OverFlow_AddOverflowCheckItem(143, 1, false)
  OverFlow_AddOverflowCheckItem(115, 3, false)
  OverFlow_AddOverflowCheckItem(11, 3, false)
  OverFlow_AddOverflowCheckItem(245, 2, false)
  OverFlow_AddOverflowCheckItem(290, 5, false)
  OverFlow_AddOverflowCheckItem(529, 1, false)
  OverFlow_AddOverflowCheckItem(249, 1, false)
  GROUND:SortAndReduceBagItem()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH("NYASUPAA"):SetManpu("MP_NOTICE_L")
  CH("NYASUPAA"):WaitManpu()
  CH("PARTNER"):SetManpu("MP_ANGRY_LP")
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("MIRUHOGGU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveFollow(SymCam("CAMERA_08"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("MIRUHOGGU"):WalkTo(SymPos("P00_MIRUHOGGU"), Speed(1.2))
  WINDOW:DrawFace(20, 20, SymAct("MIRUHOGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1588973903)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("PARTNER"):ResetManpu()
  TASK:Sleep(TimeSec(1.5))
end
function main04_yumewowarawareru02_end()
end
function main04_yumewowarawareru03_init()
end
function main04_yumewowarawareru03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("MIRUHOGGU"):SetMotion(SymMot("EV004_TIRED"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT_LP")
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1972929164)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1820570573)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 599926026)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 987305035)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MIRUHOGGU"):ResetManpu()
  CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.3))
  CH("MIRUHOGGU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 301221768)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("MIRUHOGGU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  local taskMiruhogguBS = function()
    CH("MIRUHOGGU"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetMotion(SymMot("CHARGE"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetMotion(SymMot("SPECIAL"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    subEveFlash2()
  end
  TASK:Regist(taskMiruhogguBS)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 149911241)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("YANCHAMU"):SetManpu("MP_QUESTION")
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("CHOBOMAKI"):SetManpu("MP_QUESTION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_QUESTION")
  CH("NYASUPAA"):SetManpu("MP_QUESTION")
  CH("NUMERA"):SetManpu("MP_QUESTION")
  CH("NUMERA"):WaitManpu()
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_QUESTION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1887999482)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  local taskUnun00 = function()
    subEveNodDouble(CH("HERO"))
  end
  local taskUnun01 = function()
    subEveNodDouble(CH("PARTNER"))
  end
  local taskUnun02 = function()
    subEveNodDouble(CH("YANCHAMU"))
  end
  local taskUnun03 = function()
    subEveNodDouble(CH("SHIKIJIKA_SPRING"))
  end
  local taskUnun04 = function()
    subEveNodDouble(CH("NUMERA"))
  end
  local taskUnun05 = function()
    subEveNodDouble(CH("NYASUPAA"))
  end
  local taskUnun06 = function()
    subEveNodDouble(CH("CHOBOMAKI"))
  end
  TASK:Regist(taskUnun00)
  TASK:Regist(taskUnun01)
  TASK:Regist(taskUnun02)
  TASK:Regist(taskUnun03)
  TASK:Regist(taskUnun04)
  TASK:Regist(taskUnun05)
  TASK:Regist(taskUnun06)
  TASK:Sleep(TimeSec(1.3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1771283641)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1279602233)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("YANCHAMU"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("CHOBOMAKI"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(SymPos("P00_HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveMoveDir, {
    CH("NUMERA"),
    SymPos("P00_NUMERA"),
    Speed(1),
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.3))
  CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(1))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1))
  CH("HERO"):WaitMove()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1432231800)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main04_yumewowarawareru03_end()
end
function main04_yumewowarawareru04_init()
end
function main04_yumewowarawareru04_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV0401"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 2121485499)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1734901242)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 673835837)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 825416316)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 438274495)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 50641150, PARTNER_1 = -2070109135})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1652058768)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -184989348)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -303925219)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -959501346)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main04_yumewowarawareru04_end()
end
function main04_yumewowarawareru05_init()
end
function main04_yumewowarawareru05_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -539747681, PARTNER_1 = -1869247400})
  subEveCloseMsg()
  CH("PARTNER"):ResetManpu()
  CH("NUMERA"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NUMERA"), -1987134183)
  WINDOW:CloseMessage()
  CH("NUMERA"):ResetManpu()
  local taskYanChobo00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("YANCHAMU"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
      CH("CHOBOMAKI"):SetMotion(SymMot("WALK"), LOOP.ON)
      CH("CHOBOMAKI"):SetMotionRaito(Raito(2))
      TASK:Regist(subEveDoubleJump, {
        CH("CHOBOMAKI")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("YANCHAMU"):ResetManpu()
      TASK:Regist(subEveDoubleJump, {
        CH("YANCHAMU")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("CHOBOMAKI"):ResetManpu()
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("CHOBOMAKI"):ResetManpu()
      CH("YANCHAMU"):ResetManpu()
      CH("CHOBOMAKI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("YANCHAMU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("CHOBOMAKI"):SetMotionRaito(Raito(1))
      return
    end
  end
  local taskPaNume00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):SetManpu("MP_SPREE_LP")
      CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
      CH("PARTNER"):SetMotionRaito(Raito(2))
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NUMERA"):SetManpu("MP_LAUGH_LP")
      CH("NUMERA"):SetMotion(SymMot("WALK"), LOOP.ON)
      TASK:Regist(subEveDoubleJump, {
        CH("NUMERA")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Regist(subEveDoubleJump, {
        CH("NUMERA")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):ResetManpu()
      CH("PARTNER"):SetMotionRaito(Raito(1))
      TASK:Regist(subEveDoubleJump, {
        CH("PARTNER")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Regist(subEveDoubleJump, {
        CH("NUMERA")
      })
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NUMERA"):ResetManpu()
    end
    function TaskL.Finish()
      CH("PARTNER"):ResetManpu()
      CH("NUMERA"):ResetManpu()
      CH("PARTNER"):SetMotionRaito(Raito(1))
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("NUMERA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      return
    end
  end
  local taskHeroShikiNya00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("HERO"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Regist(subEveDoubleJump, {
        CH("HERO")
      })
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SHIKIJIKA_SPRING"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NYASUPAA"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("HERO"):ResetManpu()
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SHIKIJIKA_SPRING"):ResetManpu()
    end
    function TaskL.Finish()
      CH("HERO"):ResetManpu()
      CH("NYASUPAA"):ResetManpu()
      CH("SHIKIJIKA_SPRING"):ResetManpu()
      return
    end
  end
  SOUND:PlayEnv(SymSnd("SE_EVT_PARTY_02"), Volume(256))
  TASK:Regist(Group("grpYanchobo"), taskYanChobo00)
  TASK:Regist(Group("grpPaNume"), taskPaNume00)
  TASK:Regist(Group("grpHeroShikiNya"), taskHeroShikiNya00)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1566314790)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1145512037)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1008780116)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 624685589)
  WINDOW:CloseMessage()
  SOUND:VolumeEnv(Volume(64), TimeSec(0.25))
  TASK:ExitNotifyTasks(Group("grpYanchobo"))
  TASK:ExitNotifyTasks(Group("grpPaNume"))
  TASK:ExitNotifyTasks(Group("grpHeroShikiNya"))
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -431167822)
  WINDOW:CloseMessage()
  SOUND:VolumeEnv(Volume(256), TimeSec(0.25))
  TASK:Regist(Group("grpYanchobo"), taskYanChobo00)
  TASK:Regist(Group("grpPaNume"), taskPaNume00)
  TASK:Regist(Group("grpHeroShikiNya"), taskHeroShikiNya00)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -11020301)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -730168272)
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("grpYanchobo"))
  TASK:ExitNotifyTasks(Group("grpPaNume"))
  TASK:ExitNotifyTasks(Group("grpHeroShikiNya"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:FadeOutEnv(TimeSec(0.25))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("YANCHAMU"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("CHOBOMAKI"):SetManpu("MP_SHOCK_L")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_SHOCK_L")
  CH("NUMERA"):SetManpu("MP_SHOCK_L")
  WINDOW:Talk(SymWord(2093398760), -849234575)
  CH("NUMERA"):WaitManpu()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -2111822922)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1690627337)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1340718796)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
  CH("NYASUPAA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(72, 16, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1458737035)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 781544634)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 932077051)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1592820183)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("MIRUHOGGU"):SetMotion(SymMot("CHARGE"), LOOP.OFF)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1206628502)
  CH("MIRUHOGGU"):WaitPlayMotion()
  CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  subEveCloseMsg()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("MIRUHOGGU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  local taskMiruhogguDance = function()
    CH("MIRUHOGGU"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("MIRUHOGGU"):WaitPlayMotion()
    CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
    CH("MIRUHOGGU"):SetMotion(SymMot("EV005_CONFUSE"), LOOP.ON)
    CH("MIRUHOGGU"):SetMotionRaito(Raito(3))
  end
  SOUND:PlaySe(SymSnd("SE_EVT_DORYAA"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Regist(taskMiruhogguDance)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1824973653)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  subEveFlash2()
  SOUND:FadeOutSe(SymSnd("SE_EVT_DORYAA"), TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_WHITEOUT"))
  SCREEN_A:WhiteOut(TimeSec(0.5), true)
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("MIRUHOGGU"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(1))
end
function main04_yumewowarawareru05_end()
end
function main04_yumewowarawareru06_init()
end
function main04_yumewowarawareru06_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV0402"))
  MAP:SetVisibleBG(true)
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_02"), Volume(256))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NUMERA"), 1977471508)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 983319763)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 596080018)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 145368657)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 296818448)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1775694881)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1892533602)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1020806802)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -633567185)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -250487828)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -401937747)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1488225174)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -1102033621)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main04_yumewowarawareru06_end()
end
function main04_yumewowarawareru07_init()
end
function main04_yumewowarawareru07_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1786962200, PARTNER_1 = -1939460183})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 201208678)
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 316998183, PARTNER_1 = 2073812491})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("MIRUHOGGU")
  })
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1652617034)
  CH("MIRUHOGGU"):WaitManpu()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):WaitRotate()
  CH("PARTNER"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(72, 16, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Talk(SymAct("YANCHAMU"), 1236122761)
  WINDOW:Talk(SymAct("YANCHAMU"), 1354141128)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 536288015, PARTNER_1 = 116140622})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 767654285)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 886720716)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1287498749)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NUMERA"), -1436981950)
  WINDOW:Talk(SymAct("NUMERA"), 1764651493)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1882538148)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1528304487)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT_LP")
  CH("MIRUHOGGU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1107501606)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 222475489)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
  CH("NYASUPAA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 341411232, PARTNER_1 = 1064621667})
  WINDOW:CloseMessage()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("MIRUHOGGU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT")
  CH("MIRUHOGGU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("MIRUHOGGU"):SetMotionRaito(Raito(2))
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 644867874)
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1577583635)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1192441172)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -778955136)
  WINDOW:KeyWait()
  CH("MIRUHOGGU"):SetManpu("MP_SPREE_LP")
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:Talk(SymAct("MIRUHOGGU"), -930535487)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("MIRUHOGGU"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  EFFECT:Remove("effectBgConLp")
  CH("MIRUHOGGU"):SetManpu("MP_ANGRY_LP")
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("YANCHAMU"):SetManpu("MP_SPREE_LP")
  CH("HERO"):SetManpu("MP_SPREE_LP")
  CH("CHOBOMAKI"):SetManpu("MP_SPREE_LP")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SPREE_LP")
  CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
  CH("NUMERA"):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymWord(2093398760), -475761662)
  TASK:Sleep(TimeSec(0.3))
  CH("YANCHAMU"):ResetManpu()
  CH("HERO"):ResetManpu()
  CH("CHOBOMAKI"):ResetManpu()
  CH("NYASUPAA"):ResetManpu()
  CH("PARTNER"):ResetManpu()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  CH("NUMERA"):ResetManpu()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_RUN_ESCAPE"), Volume(256))
  CH("PARTNER"):RunTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(4))
  CH("YANCHAMU"):DirTo(SymPos("P00_PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CH("NUMERA"):DirTo(SymPos("P00_PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):RunTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(4))
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):RunTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(4))
  TASK:Sleep(TimeSec(1))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -88128189)
  WINDOW:CloseMessage()
  local taskUnun00 = function()
    subEveNod(CH("HERO"))
  end
  local taskUnun05 = function()
    subEveNod(CH("NYASUPAA"))
  end
  TASK:Regist(taskUnun00)
  TASK:Regist(taskUnun05)
  TASK:Sleep(TimeSec(0.7))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CH("MIRUHOGGU"):ResetManpu()
end
function main04_yumewowarawareru07_end()
end
function groundEnd()
end
