dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main23_kodaiisekitochuu01_init()
end
function main23_kodaiisekitochuu01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1671445511, PARTNER_1 = 2059078982})
  WINDOW:SwitchTalk({PARTNER_0 = 1368809093, PARTNER_1 = 1217228740})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("OOBEMU"):RunTo(SymPos("P00_OOBEMU"), Speed(3))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitMove()
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 130873603, PARTNER_1 = 517457986})
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYOMUNOSEKAI"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_DOON_01"), Volume(128))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU"):RunTo(SymPos("P01_OOBEMU"), Speed(2.5))
  CH("HERO"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(905616257)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 752986816, PARTNER_1 = -1418086897})
  WINDOW:SwitchTalk({PARTNER_0 = -1302165682, PARTNER_1 = 1175308937})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(500), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(500), ROT_TYPE.LEFT)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = 1595341768, PARTNER_1 = 1950066699})
  subEveCloseMsg()
  CH("PARTNER"):ResetManpu()
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), 1830852938)
  WINDOW:Talk(SymAct("OOBEMU"), 576786317)
  WINDOW:Talk(SymAct("OOBEMU"), 997867212)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = 274165007, PARTNER_1 = 155999310})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -1898692479)
  WINDOW:Talk(SymAct("OOBEMU"), -1748012608)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CH("OOBEMU"):WalkTo(SplinePath(SymSpl("S00_OOBEMU")), Speed(2.5))
  CH("PARTNER"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.LEFT)
  CH("HERO"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.LEFT)
  TASK:Sleep(TimeSec(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.15))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.15))
  CH("HERO"):WaitNeckRot()
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  CH("HERO"):WaitNeckRot()
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):RunTo(SplinePath(SymPos("P02_HERO"), SymPos("P03_HERO")), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):RunTo(SplinePath(SymPos("P02_PARTNER"), SymPos("P03_PARTNER")), Speed(3))
  CAMERA:MoveFollow2(SymCam("CAMERA_09"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("HERO"):DirTo(RotateTarget(-120), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(-120), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1421370727, PARTNER_1 = 1302549542})
  WINDOW:SwitchTalk({PARTNER_0 = 1720584165, PARTNER_1 = 2140485284})
  WINDOW:SwitchTalk({PARTNER_0 = 819241059, PARTNER_1 = 701468962})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CH("HERO"):RunTo(SymPos("P04_HERO"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):RunTo(SymPos("P04_PARTNER"), Speed(3))
  SOUND:FadeOutBgm(TimeSec(1.5))
  TASK:Sleep(TimeSec(1.2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main23_kodaiisekitochuu01_end()
end
function groundEnd()
end
