dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_moguryutankouretry01_init()
end
function main03_moguryutankouretry01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
  CH("MOGURYUU"):SetMotion(SymMot("PUSH"), LOOP.ON)
  CH("MOGURYUU2"):WalkTo(SymPos("P00_MOGURYUU2"), Speed(1.5))
  CH("MOGURYUU3"):WalkTo(SymPos("P00_MOGURYUU3"), Speed(1.5))
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU2"):SetManpu("MP_SHOCK_L")
  CH("MOGURYUU3"):SetManpu("MP_SHOCK_R")
  CH("MOGURYUU3"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("MOGURYUU3"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MOGURYUU3"), -815532553)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("MOGURYUU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("MOGURYUU"), -696728394)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("MOGURYUU3"), -44722315)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):RunTo(SymPos("P01_ENTER"), Speed(4))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):RunTo(SymPos("P01_ENTER"), Speed(4))
  TASK:Sleep(TimeSec(0.3))
  CH("MOGURYUU2"):DirTo(SymPos("P00_ENTER"), Speed(350), ROT_TYPE.LEFT)
  CH("MOGURYUU2"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("MOGURYUU2"):SetManpu("MP_SHOCK_R")
  CH("MOGURYUU2"):WaitManpu()
  CH("MOGURYUU"):DirTo(SymPos("P00_ENTER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU3"):DirTo(SymPos("P00_ENTER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("MOGURYUU3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOGURYUU3"), -464607692)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(1))
  CH("MOGURYUU"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("MOGURYUU2"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU3"):DirTo(CH("MOGURYUU2"), Speed(350), ROT_TYPE.NEAR)
  CH("MOGURYUU3"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
  CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT")
  CH("MOGURYUU3"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("MOGURYUU3"), -1425067789)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main03_moguryutankouretry01_end()
end
function groundEnd()
end
