dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main21_chitenboss1st01_init()
end
function main21_chitenboss1st01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:FadeInEnv(SymSnd("SE_EVT_JIGOKU_UZU_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1.5))
  SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main21_chitenboss1st01_end()
end
function main21_chitenboss1st02_init()
end
function main21_chitenboss1st02_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_JIGOKU_UZU_LP"), Volume(128))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("ENTEI"):WalkTo(SymPos("P00_ENTEI"), Speed(1.5))
  CH("RAIKOU"):WalkTo(SymPos("P00_RAIKOU"), Speed(1.5))
  local taskPartner00 = function()
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.ON)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskPartner00)
  local taskKuchiito00 = function()
    CH("KUCHIITO"):WalkTo(SymPos("P00_KUCHIITO"), Speed(1.5))
    CH("KUCHIITO"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    CH("KUCHIITO"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
    CH("KUCHIITO"):WaitRotate()
    TASK:Sleep(TimeSec(0.5))
    CH("KUCHIITO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("KUCHIITO"):WaitRotate()
  end
  TASK:Regist(taskKuchiito00)
  local taskHero00 = function()
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.4))
    CH("HERO"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.ON)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskHero00)
  local taskSuikun00 = function()
    CH("SUIKUN"):WalkTo(SymPos("P00_SUIKUN"), Speed(1.5))
    CH("SUIKUN"):WaitMove()
    TASK:Sleep(TimeSec(0.4))
    CH("SUIKUN"):DirTo(RotateTarget(-160), Speed(350), ROT_TYPE.NEAR)
    CH("SUIKUN"):WaitRotate()
  end
  TASK:Regist(taskSuikun00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("RAIKOU"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  CH("RAIKOU"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  CH("RAIKOU"):WaitRotate()
  TASK:Sleep(TimeSec(0.4))
  CH("RAIKOU"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("RAIKOU"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("RAIKOU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAIKOU"), -1478484177)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SUIKUN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUIKUN"), -1090834834)
  WINDOW:Talk(SymAct("SUIKUN"), -1781105235)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("ENTEI"):DirTo(RotateTarget(135), Speed(200), ROT_TYPE.NEAR)
  CH("ENTEI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ENTEI"), -1932702484)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), -1014179285)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("KUCHIITO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CH("KUCHIITO"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), -627578006)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenboss1st02_end()
end
function main21_chitenboss1st03_init()
end
function main21_chitenboss1st03_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_JIGOKU_UZU_LP"), Volume(128))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SOUND:VolumeEnv(Volume(256), TimeSec(0.5))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), -239421271)
  WINDOW:Talk(SymAct("KUCHIITO"), -392066584)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  EFFECT:Create("effectDropBlack01", SymEff("EV_DROP_BLACK"))
  EFFECT:SetPosition("effectDropBlack01", SymPos("P_EFF_EV_DROP_BLACK_01"))
  EFFECT:Play("effectDropBlack01")
  SOUND:PlaySe(SymSnd("SE_EVT_KK_AMEBA_APPEAR"), Volume(256))
  TASK:Sleep(TimeSec(2))
  SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenboss1st03_end()
end
function main21_chitenboss1st04_init()
end
function main21_chitenboss1st04_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_JIGOKU_UZU_LP"), Volume(128))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL"):SetVisible(false)
  CH("SHADOW_OF_NIHIL3"):SetMotionRaito(Raito(1.2))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  local taskEffBota01 = function()
    EFFECT:Create("effectDropFloorBlack01", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack01", SymPos("P_EFF_DROP_FLOOR_BLACK_01"))
    EFFECT:Play("effectDropFloorBlack01")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL"):SetVisible(true)
    CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota01)
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota02 = function()
    EFFECT:Create("effectDropFloorBlack02", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack02", SymPos("P_EFF_DROP_FLOOR_BLACK_02"))
    EFFECT:Play("effectDropFloorBlack02")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL3"):SetVisible(true)
    CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL3"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota02)
  TASK:Sleep(TimeSec(0.1))
  local taskEffBota03 = function()
    EFFECT:Create("effectDropFloorBlack03", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack03", SymPos("P_EFF_DROP_FLOOR_BLACK_03"))
    EFFECT:Play("effectDropFloorBlack03")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL2"):SetVisible(true)
    CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL2"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota03)
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CAMERA:SetFovy(SymCam("CAMERA_00_5"))
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), 1866044711)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 1981981798)
  WINDOW:CloseMessage()
  CH("ENTEI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("RAIKOU"):SetMotion(SymMot("EV020_BARK00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_ROAR"))
  EFFECT:Create("effectBodyElectric", SymEff("EV_BODY_ELECTRIC"))
  EFFECT:SetPosition("effectBodyElectric", SymPos("P_EFF_BODY_ELECTRIC"))
  EFFECT:Play("effectBodyElectric")
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_DENGEKI_01"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("RAIKOU"):SetMotion(SymMot("EV020_BARK01"), LOOP.ON)
  TASK:Sleep(TimeSec(1.2))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("ENTEI"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:SetRotateZ(SymCam("CAMERA_02"))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_DENGEKI_02"))
  EFFECT:Create("effectLightningWarp01", SymEff("EV_LIGHTNING_WARP_ZOOM"))
  EFFECT:SetPosition("effectLightningWarp01", SymPos("P_EFF_LIGHTNING_WARP_01"))
  EFFECT:Play("effectLightningWarp01")
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  local taskEffAway01 = function()
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    EFFECT:Create("effectSmokeupBlack01", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack01", SymPos("P_EFF_EV_SMOKEUP_BLACK_01"))
    EFFECT:Play("effectSmokeupBlack01")
    SOUND:PlaySe(SymSnd("SE_EVT_KK_OUT_02"))
    CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("SHADOW_OF_NIHIL"):SetVisible(false)
  end
  TASK:Regist(taskEffAway01)
  TASK:Sleep(TimeSec(0.2))
  local taskEffAway02 = function()
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    EFFECT:Create("effectSmokeupBlack02", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack02", SymPos("P_EFF_EV_SMOKEUP_BLACK_02"))
    EFFECT:Play("effectSmokeupBlack02")
    CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  end
  TASK:Regist(taskEffAway02)
  local taskEffAway03 = function()
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    EFFECT:Create("effectSmokeupBlack03", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack03", SymPos("P_EFF_EV_SMOKEUP_BLACK_03"))
    EFFECT:Play("effectSmokeupBlack03")
    CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  end
  TASK:Regist(taskEffAway03)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(2.5))
  SOUND:FadeOutEnv(TimeSec(1))
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeInEnv(SymSnd("SE_EVT_TENNOHIKARI_01_LP"), TimeSec(0.5), Volume(256))
  EFFECT:Create("effectBgLightupLp", SymEff("BG_LIGHTUP_LP"))
  EFFECT:SetPosition("effectBgLightupLp", SymPos("P_EFF_BG_LIGHTUP_LP"))
  EFFECT:ChangeColor("effectBgLightupLp", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  EFFECT:Play("effectBgLightupLp")
  EFFECT:ChangeColor("effectBgLightupLp", Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("SUIKUN"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  CH("KUCHIITO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  CH("RAIKOU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.1))
  CH("ENTEI"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  CH("SUIKUN"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.35))
  TASK:Sleep(TimeSec(0.2))
  CH("ENTEI"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.35))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.35))
  TASK:Sleep(TimeSec(0.1))
  CH("KUCHIITO"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.35))
  TASK:Sleep(TimeSec(0.1))
  CH("RAIKOU"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.35))
  CH("SUIKUN"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.35))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenboss1st04_end()
end
function main21_chitenboss1st05_init()
end
function main21_chitenboss1st05_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  EFFECT:Create("effectLightlineStartLp", SymEff("EV_LIGHTLINE_START_LP"))
  EFFECT:SetPosition("effectLightlineStartLp", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineStartLp")
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_02"))
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_03_LP"))
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenboss1st05_end()
end
function main21_chitenboss1st06_init()
end
function main21_chitenboss1st06_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  GM("EV21_DOOR"):SetVisible(false)
  EFFECT:Create("effectLightDoorXlStartLp", SymEff("EV_LIGHTDOOR_XL_START_LP"))
  EFFECT:SetPosition("effectLightDoorXlStartLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
  EFFECT:Play("effectLightDoorXlStartLp")
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("RAIKOU"):SetManpu("MP_EXCLAMATION")
  CH("SUIKUN"):SetManpu("MP_EXCLAMATION")
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.5))
  local taskDoorOpen00 = function()
    GM("EV21_DOOR"):SetVisible(true)
    GM("EV21_DOOR"):SetMotion(SymMot("OPEN"), LOOP.OFF)
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_OPEN"), Volume(256))
    TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
    GM("EV21_DOOR"):SetMotion(SymMot("LOOP"), LOOP.ON)
  end
  TASK:Regist(taskDoorOpen00)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  CAMERA:SetFovy(SymCam("CAMERA_02_5"))
  TASK:Sleep(TimeSec(3.5))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1187524335, PARTNER_1 = -1607671728})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectLightDoorXlStartLp")
end
function main21_chitenboss1st06_end()
end
function main21_chitenboss1st07_init()
end
function main21_chitenboss1st07_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:Create("effectLightlineLp", SymEff("EV_LIGHTLINE_LP"))
  EFFECT:SetPosition("effectLightlineLp", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineLp")
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  EFFECT:Create("effectDropBlack01", SymEff("EV_DROP_BLACK"))
  EFFECT:SetPosition("effectDropBlack01", SymPos("P_EFF_EV_DROP_BLACK_01"))
  EFFECT:Play("effectDropBlack01")
  SOUND:PlaySe(SymSnd("SE_EVT_KK_AMEBA_APPEAR"), Volume(256))
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectLightlineLp")
end
function main21_chitenboss1st07_end()
end
function main21_chitenboss1st08_init()
end
function main21_chitenboss1st08_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  MAP:SetVisibleMaterial("uzu", false)
  CH("SHADOW_OF_NIHIL"):SetVisible(false)
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):SetVisible(false)
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):SetVisible(false)
  CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  CH("SHADOW_OF_NIHIL3"):SetMotionRaito(Raito(1.2))
  CH("SHADOW_OF_NIHIL4"):SetMotionRaito(Raito(0.9))
  CH("SHADOW_OF_NIHIL5"):SetMotionRaito(Raito(0.7))
  EFFECT:Create("effectLightDoorXlEnd", SymEff("EV_LIGHTDOOR_XL_END"))
  EFFECT:SetPosition("effectLightDoorXlEnd", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
  EFFECT:Play("effectLightDoorXlEnd")
  GM("EV21_DOOR"):SetMotion(SymMot("LOOP"), LOOP.ON)
  local taskEffBota01 = function()
    EFFECT:Create("effectDropFloorBlack01", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack01", SymPos("P_EFF_DROP_FLOOR_BLACK_01"))
    EFFECT:Play("effectDropFloorBlack01")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL"):SetVisible(true)
    CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota01)
  CH("SUIKUN"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  local taskEffBota02 = function()
    EFFECT:Create("effectDropFloorBlack02", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack02", SymPos("P_EFF_DROP_FLOOR_BLACK_02"))
    EFFECT:Play("effectDropFloorBlack02")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL2"):SetVisible(true)
    CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL2"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota02)
  local taskEffBota03 = function()
    EFFECT:Create("effectDropFloorBlack03", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack03", SymPos("P_EFF_DROP_FLOOR_BLACK_03"))
    EFFECT:Play("effectDropFloorBlack03")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL3"):SetVisible(true)
    CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL3"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota03)
  TASK:Sleep(TimeSec(0.1))
  local taskEffBota04 = function()
    EFFECT:Create("effectDropFloorBlack04", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack04", SymPos("P_EFF_DROP_FLOOR_BLACK_04"))
    EFFECT:Play("effectDropFloorBlack04")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL4"):SetVisible(true)
    CH("SHADOW_OF_NIHIL4"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL4"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota04)
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota05 = function()
    EFFECT:Create("effectDropFloorBlack05", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack05", SymPos("P_EFF_DROP_FLOOR_BLACK_05"))
    EFFECT:Play("effectDropFloorBlack05")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL5"):SetVisible(true)
    CH("SHADOW_OF_NIHIL5"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL5"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL5"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL5"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota05)
  SOUND:FadeOutSe(SymSnd("SE_EVT_TENNOHIKARI_02"), TimeSec(1.5))
  SOUND:FadeOutSe(SymSnd("SE_EVT_TENNOHIKARI_03_LP"), TimeSec(1.5))
  TASK:Sleep(TimeSec(0.3))
  local taskDoorBack00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_CLOSE_01"), Volume(256))
    GM("EV21_DOOR"):SetMotion(SymMot("CLOSE"), LOOP.OFF)
    TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
    GM("EV21_DOOR"):SetVisible(false)
  end
  TASK:Regist(taskDoorBack00)
  TASK:Sleep(TimeSec(2.7))
  CH("SUIKUN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("SUIKUN"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("RAIKOU"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.7))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenboss1st08_end()
end
function main21_chitenboss1st09_init()
end
function main21_chitenboss1st09_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:Create("effectLightlineEnd", SymEff("EV_LIGHTLINE_END"))
  EFFECT:SetPosition("effectLightlineEnd", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineEnd")
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_CLOSE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenboss1st09_end()
end
function main21_chitenboss1st10_init()
end
function main21_chitenboss1st10_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):SetMotionRaito(Raito(1.2))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):SetMotionRaito(Raito(0.9))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):SetMotionRaito(Raito(0.7))
  CH("BANGIRASU_MEGA"):SetVisible(false)
  CH("GENGAA_MEGA"):SetVisible(false)
  CH("GENGAA_MEGA2"):SetVisible(false)
  CH("BANGIRASU_MEGA"):ChangeColor(Color(0, 0, 0, 1), TimeSec(0, TIME_TYPE.FRAME))
  CH("GENGAA_MEGA"):ChangeColor(Color(0, 0, 0, 1), TimeSec(0, TIME_TYPE.FRAME))
  CH("GENGAA_MEGA2"):ChangeColor(Color(0, 0, 0, 1), TimeSec(0, TIME_TYPE.FRAME))
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0))
  CAMERA:MoveFollow(SymCam("CAMERA_00_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_03"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1962822765, PARTNER_1 = -1843756334})
  WINDOW:SwitchTalk({PARTNER_0 = -581233643, PARTNER_1 = -1002429100})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("RAIKOU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), -278038889)
  WINDOW:Talk(SymAct("KUCHIITO"), -160020522)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CH("RAIKOU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1911446297, PARTNER_1 = 1760914008})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), -1417511169)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), -1298575426)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  EFFECT:Create("effectBossChange02", SymEff("EV_NIHIL_BOSSCHANGE"))
  EFFECT:SetPosition("effectBossChange02", SymPos("P_EFF_BOSSCHANGE_02"))
  EFFECT:Play("effectBossChange02")
  SOUND:PlaySe(SymSnd("SE_EVT_KK_TO_BOSS_TAKE02"), Volume(256))
  EFFECT:Create("effectBossChange03", SymEff("EV_NIHIL_BOSSCHANGE"))
  EFFECT:SetPosition("effectBossChange03", SymPos("P_EFF_BOSSCHANGE_03"))
  EFFECT:Play("effectBossChange03")
  CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("SPECIAL"), LOOP.OFF)
  CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("SPECIAL"), LOOP.OFF)
  CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("GENGAA_MEGA"):SetVisible(true)
  CH("GENGAA_MEGA"):ChangeColor(Color(1, 1, 1, 1), TimeSec(10, TIME_TYPE.FRAME))
  CH("GENGAA_MEGA2"):SetVisible(true)
  CH("GENGAA_MEGA2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(10, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1716249475, PARTNER_1 = -2136003268})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CH("SHADOW_OF_NIHIL"):SetVisible(false)
  CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03_6"))
  CAMERA:SetTgt(SymCam("CAMERA_03_6"))
  CAMERA:SetFovy(SymCam("CAMERA_03_6"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_7"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:Create("effectBossChange01", SymEff("EV_NIHIL_BOSSCHANGE"))
  EFFECT:SetPosition("effectBossChange01", SymPos("P_EFF_BOSSCHANGE_01"))
  EFFECT:Play("effectBossChange01")
  SOUND:PlaySe(SymSnd("SE_EVT_KK_TO_BOSS_TAKE02"), Volume(256))
  CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("SPECIAL"), LOOP.OFF)
  CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("BANGIRASU_MEGA"):SetVisible(true)
  CH("BANGIRASU_MEGA"):ChangeColor(Color(1, 1, 1, 1), TimeSec(10, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1))
  CAMERA:WaitMove()
  CAMERA:SetEye(SymCam("CAMERA_03_5"))
  CAMERA:SetTgt(SymCam("CAMERA_03_5"))
  CAMERA:SetFovy(SymCam("CAMERA_03_5"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("SUIKUN"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("RAIKOU"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitManpu()
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.1))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -806437893, PARTNER_1 = -688551238})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetRotateZ(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), -36120199)
  WINDOW:Talk(SymAct("ENTEI"), -456923080)
  WINDOW:CloseMessage()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CH("ENTEI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:SetRotateZ(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("RAIKOU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("RAIKOU"), 1666970871)
  WINDOW:CloseMessage()
  CH("ENTEI"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:SetRotateZ(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 2051065270)
  WINDOW:CloseMessage()
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:MoveFollow2(SymCam("CAMERA_08_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), 322836890)
  WINDOW:CloseMessage()
  subEveFlash2()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main21_chitenboss1st10_end()
end
function groundEnd()
end
