dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main11_tabidachi01_init()
end
function main11_tabidachi01_start()
  MAP:SetVisibleMaterial("m_tw00_all_night_light0", false)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("YANCHAMU"):SetVisible(false)
  CH("CHOBOMAKI"):SetVisible(false)
  CH("SHIKIJIKA_SPRING"):SetVisible(false)
  CH("NUMERA"):SetVisible(false)
  CH("NYASUPAA"):SetVisible(false)
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P00_HERO"),
    Speed(1.5),
    SymPos("P00_PARTNER")
  })
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -2101900546, PARTNER_1 = -1683178561})
  WINDOW:SwitchTalk({PARTNER_0 = -1333663620, PARTNER_1 = -1449469635})
  WINDOW:CloseMessage()
  local taskUnun00 = function()
    subEveNod(CH("HERO"))
  end
  local taskUnun01 = function()
    subEveNod(CH("PARTNER"))
  end
  TASK:Regist(taskUnun00)
  TASK:Regist(taskUnun01)
  TASK:Sleep(TimeSec(1))
  CH("HERO"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  local taskHeroPartner00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("HERO"):SetManpu("MP_NOTICE_R")
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskHeroPartner00)
  CH("YANCHAMU"):SetVisible(true)
  CH("CHOBOMAKI"):SetVisible(true)
  CH("SHIKIJIKA_SPRING"):SetVisible(true)
  CH("NUMERA"):SetVisible(true)
  CH("NYASUPAA"):SetVisible(true)
  SOUND:FadeOutEnv(TimeSec(0.5))
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -421834758)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -4161861, PARTNER_1 = -722653832})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -839508935, PARTNER_1 = 1248723190})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(2))
  CH("HERO"):WaitMove()
  WINDOW:DrawFace(72, 16, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1400189367)
  subEveCloseMsg()
  SOUND:PlayBgm(SymSnd("BGM_EVE_TABIDACHI_01"), Volume(256))
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1586403373, PARTNER_1 = -1200990574})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(72, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -1824062127)
  WINDOW:KeyWait()
  CH("YANCHAMU"):ResetManpu()
  WINDOW:Talk(SymAct("YANCHAMU"), -1973668848)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -987913513)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -603548778)
  subEveCloseMsg()
  local taskHeroPartner01 = function()
    CH("PARTNER"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskHeroPartner01)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -148127659, PARTNER_1 = -298782444})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1772678619)
  WINDOW:Talk(SymAct("NYASUPAA"), 1890835610)
  subEveCloseMsg()
  local taskHeroPartner02 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskHeroPartner02)
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 20, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), -1278949315)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 20, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NUMERA"), -1428162180)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -2114803009, PARTNER_1 = -1729520642})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  local taskHeroPartner03 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskHeroPartner03)
  WINDOW:DrawFace(72, 16, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -676852423)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -827114376)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(20, 20, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -442601541)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -58368262)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 2065515061, PARTNER_1 = 1644589940})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskHeroPartner01)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 192458584)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 308518425)
  WINDOW:Talk(SymAct("YANCHAMU"), 961465818)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 542506139, PARTNER_1 = 1863608924})
  WINDOW:SwitchTalk({PARTNER_0 = 1980717853, PARTNER_1 = 1562511582})
  WINDOW:SwitchTalk({PARTNER_0 = 1144600991, PARTNER_1 = -1012849328})
  WINDOW:SwitchTalk({PARTNER_0 = -625339375, PARTNER_1 = -1766877215})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.1))
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1883986272)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1533414045, PARTNER_1 = -1115503582})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("YANCHAMU"):WalkTo(SymPos("P00_YANCHAMU"), Speed(1.5))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitMove()
  WINDOW:DrawFace(172, 8, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -222080283)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(3))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.35))
  CH("YANCHAMU"):WalkTo(SymPos("P01_YANCHAMU"), Speed(1.5), LINK_DIR.OFF)
  CH("YANCHAMU"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -338140252, PARTNER_1 = -1057673113})
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(1), Volume(256))
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -638713562)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
  CH("PARTNER"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1584799209, PARTNER_1 = 1198337192})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 773058692)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 923320773)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 472224262)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 87991111)
  subEveCloseMsg()
  WINDOW:DrawFace(172, 8, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1249850752)
  WINDOW:Talk(SymAct("YANCHAMU"), 1399063745)
  SOUND:FadeOutEnv(TimeSec(0.5))
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(RotateTarget(-120), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.35))
  CH("PARTNER"):WaitNeckRot()
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-10), RotateTarget(0), TimeSec(0.3))
  WINDOW:SysMsg(2018072322)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_TABIDACHI_02"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1632790083)
  WINDOW:SysMsg(-422937972)
  WINDOW:SysMsg(-3060787)
  WINDOW:SysMsg(1017536362)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 633171499, PARTNER_1 = 244334056})
  subEveCloseMsg()
  WINDOW:SysMsg(394988713)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1489672814)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1104259887)
  WINDOW:SysMsg(1794963692)
  WINDOW:SysMsg(1944570285)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -192948894, PARTNER_1 = -312155101})
  subEveCloseMsg()
  WINDOW:SysMsg(-2078656497)
  WINDOW:SysMsg(-1660876466)
  WINDOW:SysMsg(-1238607219)
  WINDOW:SysMsg(-1355322420)
  WINDOW:SysMsg(-529072885)
  WINDOW:SysMsg(-110244790)
  WINDOW:SysMsg(-767516791)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -883183928, PARTNER_1 = 1287893511})
  subEveCloseMsg()
  WINDOW:SysMsg(1440252742)
  WINDOW:SysMsg(-596039591)
  WINDOW:SysMsg(-983426792)
  WINDOW:SysMsg(-296793381)
  WINDOW:SysMsg(-145458278)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.TEARS)
  WINDOW:Monologue(-1206522531)
  WINDOW:Monologue(-1592861668)
  WINDOW:Monologue(-1977380897)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1824997730, PARTNER_1 = 346071633})
  subEveCloseMsg()
  WINDOW:SysMsg(230396688)
  WINDOW:SysMsg(1690652476)
  WINDOW:SysMsg(2111733373)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1458777534, PARTNER_1 = 1340611839})
  subEveCloseMsg()
  WINDOW:SysMsg(11110968)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(431143801)
  WINDOW:SysMsg(849340602)
  WINDOW:SysMsg(730126843)
  WINDOW:SysMsg(-1407400652)
  subEveCloseMsg()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.TEARS)
  WINDOW:Monologue(-1257769867)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(-90), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -413341862, PARTNER_1 = -28846565})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -714439208, PARTNER_1 = -864963431})
  WINDOW:SwitchTalk({PARTNER_0 = -2093997474, PARTNER_1 = -1708453089})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(taskUnun00)
  TASK:Regist(taskUnun01)
  TASK:Sleep(TimeSec(1))
  local taskHero00 = function()
    CH("HERO"):DirTo(SymPos("P02_HERO"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    CH("HERO"):WalkTo(SymPos("P01_5_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  local taskPartner00 = function()
    CH("PARTNER"):DirTo(SymPos("P02_PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    CH("PARTNER"):WalkTo(SymPos("P01_5_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskPartner00)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(10, -10)
  WINDOW:SwitchTalk({PARTNER_0 = -1324990244, PARTNER_1 = -1474465379})
  WINDOW:SwitchTalk({PARTNER_0 = 797273426, PARTNER_1 = 916347923})
  WINDOW:CloseMessage()
  local taskHero01 = function()
    CH("HERO"):DirTo(SymPos("P02_HERO"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    CH("HERO"):WalkTo(SplinePath(SymPos("P02_HERO"), SymPos("P03_HERO"), SymPos("P04_HERO")), Speed(1.5))
  end
  local taskPartner01 = function()
    CH("PARTNER"):DirTo(SymPos("P02_PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    CH("PARTNER"):WalkTo(SplinePath(SymPos("P02_PARTNER"), SymPos("P03_PARTNER"), SymPos("P04_PARTNER")), Speed(1.5))
  end
  TASK:Regist(taskHero01)
  TASK:Sleep(TimeSec(0.4))
  TASK:Regist(taskPartner01)
  TASK:Sleep(TimeSec(0.5))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NUMERA"), 1608548415)
  subEveCloseMsg()
  local taskMiokuri00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.2))
      CH("YANCHAMU"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.5))
      TASK:Regist(subEveDoubleJump, {
        CH("NUMERA")
      })
      TASK:Sleep(TimeSec(0.5))
      CH("CHOBOMAKI"):SetManpu("MP_SPREE_LP")
      TASK:Regist(subEveDoubleJump, {
        CH("CHOBOMAKI")
      })
      CH("YANCHAMU"):ResetManpu()
      TASK:Sleep(TimeSec(0.5))
      CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
      TASK:Sleep(TimeSec(0.5))
      CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(2))
      CH("YANCHAMU"):ResetManpu()
      TASK:Sleep(TimeSec(1.5))
      CH("CHOBOMAKI"):ResetManpu()
      TASK:Sleep(TimeSec(1.5))
      TASK:Regist(subEveDoubleJump, {
        CH("YANCHAMU")
      })
      CH("NYASUPAA"):ResetManpu()
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskMiokuri00)
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(72, 16, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1190900094)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  SCREEN_A:FadeOut(TimeSec(1.5), true)
end
function main11_tabidachi01_end()
end
function groundEnd()
end
