dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main07_denryumurakarahanareru01_init()
end
function main07_denryumurakarahanareru01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1598478515, PARTNER_1 = -1180559860})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskDenryuu00 = function()
    CH("DENRYUU"):SetMotion(SymMot("EV006_WALK"), LOOP.ON)
    CH("DENRYUU"):MoveTo(SymPos("P00_DENRYUU"), Speed(1.2))
    CH("DENRYUU"):WaitMove()
    CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
    CH("DENRYUU"):WaitManpu()
    CH("DENRYUU"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskDenryuu00)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_02"), Volume(256))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1836104241, PARTNER_1 = -1953205106})
  WINDOW:CloseMessage()
  CH("HERO"):SetPosition(SymPos("P01_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P02_HERO"),
    Speed(2.5),
    CH("DENRYUU")
  })
  CH("PARTNER"):RunTo(SymPos("P02_PARTNER"), Speed(2.5))
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -992615863)
  WINDOW:Talk(SymAct("DENRYUU"), -573648120)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -152862517, PARTNER_1 = -268914294})
  WINDOW:SwitchTalk({PARTNER_0 = 1751166277, PARTNER_1 = 1903926276})
  subEveCloseMsg()
  CH("DENRYUU"):SetManpu("MP_LAUGH_LP")
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), -956405773)
  subEveCloseMsg()
  CH("DENRYUU"):ResetManpu()
  CH("DENRYUU"):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -538618190, PARTNER_1 = -188217999})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -304925648)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1567448329, PARTNER_1 = -1148611658})
  WINDOW:SwitchTalk({PARTNER_0 = -1868251019, PARTNER_1 = -1983909580})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 237497851)
  WINDOW:Talk(SymAct("DENRYUU"), 389864634)
  WINDOW:Talk(SymAct("DENRYUU"), -733231075)
  WINDOW:CloseMessage()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("DENRYUU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("DENRYUU"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_STYLISH"), Volume(256))
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE01"), LOOP.ON)
  CH("DENRYUU"):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("DENRYUU"), -850331300)
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("DENRYUU"):ResetManpu()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.25))
  TASK:Sleep(TimeSec(0.4))
  CH("DENRYUU"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -427971937)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -10052642, PARTNER_1 = -1339618023})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1455670184)
  WINDOW:Talk(SymAct("DENRYUU"), -2112786533)
  WINDOW:Talk(SymAct("DENRYUU"), -1693819174)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 479347221, PARTNER_1 = 92894036})
  WINDOW:SwitchTalk({PARTNER_0 = 1828171640, PARTNER_1 = 1978441273})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1589759482)
  WINDOW:Talk(SymAct("DENRYUU"), 1205533883)
  WINDOW:CloseMessage()
  local taskDenryuu01 = function()
    CH("DENRYUU"):DirTo(SymPos("P01_DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("DENRYUU"):WaitRotate()
    CH("DENRYUU"):SetMotion(SymMot("EV006_WALK"), LOOP.ON)
    CH("DENRYUU"):MoveTo(SymPos("P01_DENRYUU"), Speed(1.2))
    CH("DENRYUU"):WaitMove()
    CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskDenryuu01)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):DirTo(SymPos("P01_DENRYUU"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(SymPos("P01_DENRYUU"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.6))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 144403068, PARTNER_1 = 293624637})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  TASK:WaitTask()
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_FLY_SWEAT")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 984418558)
  WINDOW:CloseMessage()
  CH("DENRYUU"):DirTo(SymPos("P00_DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DENRYUU"):SetMotion(SymMot("EV006_WALK"), LOOP.ON)
  CH("DENRYUU"):MoveTo(SymPos("P00_DENRYUU"), Speed(1.7))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(SymPos("P00_DENRYUU"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P00_DENRYUU"), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitMove()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 599144895)
  WINDOW:CloseMessage()
  CH("DENRYUU"):DirTo(SymPos("P02_DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("DENRYUU"):SetMotion(SymMot("EV006_WALK"), LOOP.ON)
  CH("HERO"):DirTo(SymPos("P02_DENRYUU"), Speed(60), ROT_TYPE.NEAR)
  CH("DENRYUU"):MoveTo(SymPos("P02_DENRYUU"), Speed(1.5))
  TASK:Sleep(TimeSec(3))
  CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1540479632, PARTNER_1 = -1120594895})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -249522239, PARTNER_1 = -398743936})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -1021905597, PARTNER_1 = -636632062})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutBgm(TimeSec(0.7))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
end
function main07_denryumurakarahanareru01_end()
end
function groundEnd()
end
