dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_inisienohoneatoboss2nd01_init()
end
function main09_inisienohoneatoboss2nd01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("GIRATYINA_A"):SetScale(Scale(1.2))
  CH("GIRATYINA_A"):SetNeckRot(RotateTarget(0), RotateTarget(-10), RotateTarget(0), TimeSec(0))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SHIKIJIKA_SPRING"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("NUMERA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 998187992)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  WINDOW:DrawFace(20, 88, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 576983705)
  WINDOW:DrawFace(20, 88, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 155795802)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("PARTNER"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 273838107, PARTNER_1 = 1595139804})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08_3"))
  CAMERA:SetTgt(SymCam("CAMERA_08_3"))
  CAMERA:SetFovy(SymCam("CAMERA_08_3"))
  CH("HITOMOSHI2"):DirTo(CH("GIRATYINA_A"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI2"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI2"):WaitManpu()
  CH("HERO"):SetManpu("MP_NOTICE_L")
  WINDOW:DrawFace(324, 88, SymAct("HITOMOSHI2"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HITOMOSHI2"), 1174984605)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GIRATYINA_A"):SetManpu("MP_FLY_SWEAT")
  CH("GIRATYINA_A"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 1831175262)
  CH("HITOMOSHI2"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI2"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.2))
  CH("GIRATYINA_A"):ResetNeckRot(TimeSec(0))
  WINDOW:Talk(SymAct("GIRATYINA_A"), 1950266655)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SENKOU"), Volume(256))
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  SAJI:CreateSajiPlayer("kage_04", "EV09_050_04_04")
  SJ("kage_04"):SetPosition(Vector2(200, 120))
  SJ("kage_04"):SetDrawPriority(200)
  SJ("kage_04"):Play(LOOP.ON)
  SCREEN_A:WhiteOut(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(0.05), true)
  TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  SCREEN_A:FadeInAll(TimeSec(0.05), true)
  TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  SCREEN_A:WhiteIn(TimeSec(0), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(0.1), true)
  SAJI:DestroySajiPlayer("kage_04")
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  WINDOW:Talk(SymAct("GIRATYINA_A"), -207181360)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_11_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_GIRATYINA_ENTRY"))
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  CH("HERO"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  WINDOW:Talk(SymAct("GIRATYINA_A"), -356673391)
  WINDOW:CloseMessage()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("SHIKIJIKA_SPRING"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("NUMERA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  subEveFlash2()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main09_inisienohoneatoboss2nd01_end()
end
function groundEnd()
end
