dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_m03kaerimichi01_init()
end
function main03_m03kaerimichi01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GIMMICK:SetupLoopPlaced(SymGA("SCHOOL_ROAD"), 0, -10)
  GIMMICK:MoveLoopPlaced(Speed(0.8))
  CH("YANCHAMU"):SetVisible(false)
  CH("CHOBOMAKI"):SetVisible(false)
  CH("HERO"):SetMotion(SymMot("WALK"), LOOP.ON)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P00_PARTNER"),
    Speed(3),
    CH("HERO")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1770379896, PARTNER_1 = 1889463097})
  GIMMICK:MoveLoopPlaced(Speed(0))
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.LEFT)
  TASK:Sleep(TimeSec(1))
  CH("HERO"):DirTo(SymPos("P00_PARTNER"), Speed(60), ROT_TYPE.NEAR)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1538504954, PARTNER_1 = 1118341563})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.GLADNESS)
  WINDOW:SwitchTalk({PARTNER_0 = 233381756, PARTNER_1 = 351415869})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):ResetFacialMotion()
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  GIMMICK:MoveLoopPlaced(Speed(0.8))
  CH("HERO"):SetMotion(SymMot("WALK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("WALK"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1071611390, PARTNER_1 = 650398911})
  WINDOW:SwitchTalk({PARTNER_0 = -1587785616, PARTNER_1 = -1203281615})
  WINDOW:SwitchTalk({PARTNER_0 = -1480334632, PARTNER_1 = -1093086311})
  WINDOW:CloseMessage()
  GIMMICK:MoveLoopPlaced(Speed(0))
  CH("PARTNER"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1779072934, PARTNER_1 = -1930514149})
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(1))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  GIMMICK:MoveLoopPlaced(Speed(0.8))
  CH("HERO"):SetMotion(SymMot("WALK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1011931172, PARTNER_1 = -625731939})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -241613474, PARTNER_1 = -394103777})
  WINDOW:CloseMessage()
  local taskPartner00 = function()
    CH("PARTNER"):RunTo(SplinePath(SymPos("P01_PARTNER"), SymPos("P02_PARTNER")), Speed(3))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  TASK:Regist(taskPartner00)
  TASK:Sleep(TimeSec(0.5))
  GIMMICK:MoveLoopPlaced(Speed(0))
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1864001744, PARTNER_1 = 1979799953})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1250538186)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1402110857, PARTNER_1 = -2025836620})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1638195467, PARTNER_1 = -786790350})
  subEveCloseMsg()
  while true do
    WINDOW:SysMsg(-939411085)
    WINDOW:SelectStart()
    WINDOW:SelectChain(-483595600, 1)
    WINDOW:SelectChain(-97002511, 0)
    WINDOW:DefaultCursor(0)
    local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
    if id == 0 then
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
      CH("PARTNER"):SetManpu("MP_SHOCK_R")
      CH("PARTNER"):WaitManpu()
      WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
      WINDOW:SwitchTalk({PARTNER_0 = 2108671806, PARTNER_1 = 1689581183})
      WINDOW:KeyWait()
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
      CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
      WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
      WINDOW:SwitchTalk({PARTNER_0 = 231352915, PARTNER_1 = 349248274})
      WINDOW:KeyWait()
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
      CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
      WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
      WINDOW:SwitchTalk({PARTNER_0 = 1073498321, PARTNER_1 = 652704144})
      WINDOW:CloseMessage()
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
      CH("HERO"):SetManpu("MP_EXCLAMATION")
      CH("HERO"):WaitManpu()
      SCREEN_A:FadeOut(TimeSec(0.3), true)
      local taskEffTwinkle00 = function()
        EFFECT:Create("effectTwinkle_01", SymEff("EV_SHINKA_END_GLITTER"))
        EFFECT:SetScale("effectTwinkle_01", Scale(0.4))
        EFFECT:SetPosition("effectTwinkle_01", SymPos("P01_EFF_GLITTER_RANDOM"))
        EFFECT:Play("effectTwinkle_01")
        TASK:Sleep(TimeSec(0.4))
        EFFECT:Create("effectTwinkle_02", SymEff("EV_SHINKA_END_GLITTER"))
        EFFECT:ChangeColor("effectTwinkle_02", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
        EFFECT:SetScale("effectTwinkle_02", Scale(0.3))
        EFFECT:SetPosition("effectTwinkle_02", SymPos("P02_EFF_GLITTER_RANDOM"))
        EFFECT:Play("effectTwinkle_02")
        EFFECT:ChangeColor("effectTwinkle_02", Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
        TASK:Sleep(TimeSec(0.7))
        EFFECT:Create("effectTwinkle_03", SymEff("EV_SHINKA_END_GLITTER"))
        EFFECT:ChangeColor("effectTwinkle_03", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
        EFFECT:SetScale("effectTwinkle_03", Scale(0.5))
        EFFECT:SetPosition("effectTwinkle_03", SymPos("P03_EFF_GLITTER_RANDOM"))
        EFFECT:Play("effectTwinkle_03")
        EFFECT:ChangeColor("effectTwinkle_03", Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
        TASK:Sleep(TimeSec(0.8))
        EFFECT:Create("effectTwinkle_01", SymEff("EV_SHINKA_END_GLITTER"))
        EFFECT:ChangeColor("effectTwinkle_01", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
        EFFECT:SetScale("effectTwinkle_01", Scale(0.4))
        EFFECT:SetPosition("effectTwinkle_01", SymPos("P01_EFF_GLITTER_RANDOM"))
        EFFECT:Play("effectTwinkle_01")
        EFFECT:ChangeColor("effectTwinkle_01", Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
      end
      TASK:Regist(Group("grpKiraKira"), taskEffTwinkle00)
      CAMERA:SetEye(SymCam("CAMERA_01"))
      CAMERA:SetTgt(SymCam("CAMERA_01"))
      CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
      MAP:SetVisible(false)
      CH("HERO"):SetVisible(false)
      GIMMICK:SetVisibleLoopPlaced(false)
      MAP:SetBG(SymImg("IMEV0301"))
      MAP:SetVisibleBG(true)
      SCREEN_A:FadeIn(TimeSec(0.3), true)
      TASK:Sleep(TimeSec(2.5))
      SCREEN_A:FadeOut(TimeSec(0.3), true)
      CH("HERO"):SetVisible(true)
      GIMMICK:SetVisibleLoopPlaced(true)
      MAP:SetVisible(true)
      MAP:SetVisibleBG(false)
      EFFECT:Remove("effectTwinkle_01")
      EFFECT:Remove("effectTwinkle_02")
      EFFECT:Remove("effectTwinkle_03")
      CAMERA:SetEye(SymCam("CAMERA_00"))
      CAMERA:SetTgt(SymCam("CAMERA_00"))
      SCREEN_A:FadeIn(TimeSec(0.3), true)
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("HERO"):SetManpu("MP_FLY_SWEAT")
      CH("HERO"):WaitManpu()
      WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.SURPRISE)
      WINDOW:Monologue(1772547927)
      subEveCloseMsg()
      WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
      WINDOW:SwitchTalk({PARTNER_0 = 1891491350, PARTNER_1 = 1536200149})
      WINDOW:CloseMessage()
    else
      CH("PARTNER"):ResetFacialMotion()
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      break
    end
  end
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1116454036, PARTNER_1 = -988569509})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -603418342, PARTNER_1 = -1877142806})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.GLADNESS)
  WINDOW:SwitchTalk({PARTNER_0 = -1996086357, PARTNER_1 = -1574211480})
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetMotionRaito(Raito(2))
  CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1154465495, PARTNER_1 = -193865746})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -311761233, PARTNER_1 = -968379028})
  WINDOW:CloseMessage()
  CH("YANCHAMU"):SetVisible(true)
  CH("CHOBOMAKI"):SetVisible(true)
  CAMERA:MoveFollow(SymCam("CAMERA_04"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):RunTo(SymPos("P03_HERO"), Speed(2))
  CH("PARTNER"):RunTo(SymPos("P03_PARTNER"), Speed(2))
  TASK:Sleep(TimeSec(1.2))
  CH("HERO"):SetPosition(SymPos("P04_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P04_PARTNER"))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -547584979)
  WINDOW:CloseMessage()
  CH("HERO"):RunTo(SymPos("P03_HERO"), Speed(2))
  CH("PARTNER"):RunTo(SymPos("P03_PARTNER"), Speed(2))
  TASK:Sleep(TimeSec(1.3))
  SOUND:FadeOutBgm(TimeSec(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("YANCHAMU"):DirTo(SymPos("P05_HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("CHOBOMAKI"):DirTo(SymPos("P05_HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), 1489279202)
  WINDOW:CloseMessage()
  CH("HERO"):SetPosition(SymPos("P05_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P05_PARTNER"))
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("PARTNER"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1105176995, PARTNER_1 = 681670031})
  WINDOW:SwitchTalk({PARTNER_0 = 834290894, PARTNER_1 = 446109453})
  subEveCloseMsg()
  CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):WaitRotate()
  CH("CHOBOMAKI"):SetManpu("MP_ANGRY_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(72, 16, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 59516492)
  WINDOW:CloseMessage()
  CH("CHOBOMAKI"):ResetManpu()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHILDREN_02"), Volume(256))
  CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir, {
    CH("CHOBOMAKI"),
    SymPos("P00_CHOBOMAKI"),
    Speed(2),
    CH("HERO")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveMoveDir, {
    CH("YANCHAMU"),
    SymPos("P00_YANCHAMU"),
    Speed(2),
    CH("HERO")
  })
  TASK:WaitTask()
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1288548491)
  WINDOW:Talk(SymAct("YANCHAMU"), 1440121290)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):WalkTo(SymPos("P06_PARTNER"), Speed(2))
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2130432521, PARTNER_1 = 1742791496})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), -528941177)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetManpu()
  CH("YANCHAMU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -110899514)
  WINDOW:Talk(SymAct("YANCHAMU"), 974445153)
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(72, 16, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 588245792)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 136493283)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(72, 16, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 288983458)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1584930661, PARTNER_1 = 1197682212})
  WINDOW:CloseMessage()
  CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1817083367)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("CHOBOMAKI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1968524454)
  WINDOW:Talk(SymAct("YANCHAMU"), -221425559)
  WINDOW:Talk(SymAct("YANCHAMU"), -338271960)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -2102870780, PARTNER_1 = -1682731963})
  TASK:WaitTask()
  CH("PARTNER"):SetMotionRaito(Raito(2))
  CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), -1331765370)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetManpu()
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("PARTNER"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetMotionRaito(Raito(2))
  CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_SWEAT_L")
  CH("CHOBOMAKI"):SetManpu("MP_SWEAT_R")
  CH("CHOBOMAKI"):WaitManpu()
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):ResetManpu()
  TASK:Sleep(TimeSec(0.5))
end
function main03_m03kaerimichi01_end()
end
function main03_m03kaerimichi02_init()
end
function main03_m03kaerimichi02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskMoguryuu00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU"):WalkTo(SymPos("P00_MOGURYUU"), Speed(1.5))
      CH("MOGURYUU"):WaitMove()
      CH("MOGURYUU"):ResetManpu()
      CH("MOGURYUU"):SetMotion(SymMot("PUSH"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU"):WalkTo(SymPos("P01_MOGURYUU"), Speed(1))
      CH("MOGURYUU"):WaitMove()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
      CH("MOGURYUU"):WaitRotate()
      CH("MOGURYUU"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):ResetManpu()
      CH("MOGURYUU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    end
    function TaskL.Finish()
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("MOGURYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
      CH("MOGURYUU"):WaitRotate()
      return
    end
  end
  local taskMoguryuu02 = function()
    function TaskL.Loop()
      CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU2"):WalkTo(SymPos("P00_MOGURYUU2"), Speed(2))
      CH("MOGURYUU2"):WaitMove()
      CH("MOGURYUU2"):ResetManpu()
      CH("MOGURYUU2"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU2"):SetMotion(SymMot("ENDURE"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU2"):WalkTo(SymPos("P01_MOGURYUU2"), Speed(1.5))
      CH("MOGURYUU2"):WaitMove()
      CH("MOGURYUU2"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      CH("MOGURYUU2"):SetMotion(SymMot("PUSH"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
    end
    function TaskL.Finish()
      CH("MOGURYUU2"):WalkTo(SymPos("P00_MOGURYUU2"), Speed(1.5))
      CH("MOGURYUU2"):WaitMove()
      CH("MOGURYUU2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("MOGURYUU2"):ResetManpu()
      return
    end
  end
  local taskMoguryuu03 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU3"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):RunTo(SplinePath(SymPos("P01_MOGURYUU3"), SymPos("P00_MOGURYUU3")), Speed(2.5))
      CH("MOGURYUU3"):WaitMove()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU3"):RunTo(SplinePath(SymPos("P01_MOGURYUU3"), SymPos("P02_MOGURYUU3")), Speed(2.5))
      CH("MOGURYUU3"):WaitMove()
      CH("MOGURYUU3"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(Group("grpMoguryuu"), taskMoguryuu00)
  TASK:Regist(Group("grpMoguryuu02"), taskMoguryuu02)
  TASK:Regist(Group("grpMoguryuu03"), taskMoguryuu03)
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1450840377, PARTNER_1 = -423331840})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -2143935)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -722331006)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -840356925)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main03_m03kaerimichi02_end()
end
function main03_m03kaerimichi03_init()
end
function main03_m03kaerimichi03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskMoguryuu00 = function()
    function TaskL.Loop()
      CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU"):WalkTo(SymPos("P00_MOGURYUU"), Speed(1.5))
      CH("MOGURYUU"):WaitMove()
      CH("MOGURYUU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
      CH("MOGURYUU"):WaitRotate()
      CH("MOGURYUU"):ResetManpu()
      CH("MOGURYUU"):SetMotion(SymMot("PUSH"), LOOP.ON)
      TASK:Sleep(TimeSec(1.5))
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.5))
      CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU"):WalkTo(SymPos("P01_MOGURYUU"), Speed(1))
      CH("MOGURYUU"):WaitMove()
      CH("MOGURYUU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
      CH("MOGURYUU"):WaitRotate()
      CH("MOGURYUU"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(2))
      CH("MOGURYUU"):ResetManpu()
      CH("MOGURYUU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
      TASK:Sleep(TimeSec(3))
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    end
  end
  TASK:Regist(Group("grpMoguryuu"), taskMoguryuu00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1248933644)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1399457357)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main03_m03kaerimichi03_end()
end
function main03_m03kaerimichi04_init()
end
function main03_m03kaerimichi04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskMoguryuu00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU"):WalkTo(SymPos("P00_MOGURYUU"), Speed(1.5))
      CH("MOGURYUU"):WaitMove()
      CH("MOGURYUU"):ResetManpu()
      CH("MOGURYUU"):SetMotion(SymMot("PUSH"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU"):WalkTo(SymPos("P01_MOGURYUU"), Speed(1))
      CH("MOGURYUU"):WaitMove()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
      CH("MOGURYUU"):WaitRotate()
      CH("MOGURYUU"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):ResetManpu()
      CH("MOGURYUU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    end
    function TaskL.Finish()
      CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("MOGURYUU"):ResetManpu()
      CH("MOGURYUU"):WalkTo(SymPos("P01_MOGURYUU"), Speed(2))
      CH("MOGURYUU"):WaitMove()
      CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU"):SetMotion(SymMot("PUSH"), LOOP.ON)
      return
    end
  end
  local taskMoguryuu02 = function()
    function TaskL.Loop()
      CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU2"):WalkTo(SymPos("P00_MOGURYUU2"), Speed(2))
      CH("MOGURYUU2"):WaitMove()
      CH("MOGURYUU2"):ResetManpu()
      CH("MOGURYUU2"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU2"):SetMotion(SymMot("ENDURE"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU2"):WalkTo(SymPos("P02_MOGURYUU2"), Speed(1.5))
      CH("MOGURYUU2"):WaitMove()
      CH("MOGURYUU2"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
      CH("MOGURYUU2"):WaitRotate()
      CH("MOGURYUU2"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      CH("MOGURYUU2"):SetMotion(SymMot("PUSH"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
    end
    function TaskL.Finish()
      CH("MOGURYUU2"):WalkTo(SymPos("P00_MOGURYUU2"), Speed(1.5))
      CH("MOGURYUU2"):WaitMove()
      CH("MOGURYUU2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("MOGURYUU2"):ResetManpu()
      return
    end
  end
  local taskMoguryuu03 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU3"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):WalkTo(SymPos("P00_MOGURYUU3"), Speed(2))
      CH("MOGURYUU3"):WaitMove()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT_LP")
      CH("MOGURYUU3"):WalkTo(SymPos("P02_MOGURYUU3"), Speed(2))
      CH("MOGURYUU3"):WaitMove()
      CH("MOGURYUU3"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MOGURYUU3"):SetMotion(SymMot("PULL"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("MOGURYUU3"):ResetManpu()
      CH("MOGURYUU3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("MOGURYUU3"):WalkTo(SymPos("P00_MOGURYUU3"), Speed(2))
      CH("MOGURYUU3"):WaitMove()
      return
    end
  end
  TASK:Regist(Group("grpMoguryuu"), taskMoguryuu00)
  TASK:Regist(Group("grpMoguryuu02"), taskMoguryuu02)
  TASK:Regist(Group("grpMoguryuu03"), taskMoguryuu03)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -624186030)
  subEveCloseMsg()
  CH("PARTNER"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1009738733, PARTNER_1 = -386019376})
  WINDOW:SwitchTalk({PARTNER_0 = -236519791, PARTNER_1 = -1096325034})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -1480828649)
  WINDOW:KeyWait()
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("YANCHAMU"), -1936651564)
  subEveCloseMsg()
  CH("YANCHAMU"):ResetManpu()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1786102891, PARTNER_1 = 303179610})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("YANCHAMU"), 185144859)
  WINDOW:Talk(SymAct("YANCHAMU"), 1652017719)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 2070739830, PARTNER_1 = 1346480309})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_SHOCK_L")
  CH("YANCHAMU"):WaitManpu()
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), 1230674420)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 102436659, PARTNER_1 = 520109682})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 875392433, PARTNER_1 = 758537456})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("YANCHAMU"), -1431420865)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1279954562, PARTNER_1 = -1720037492})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_EXCLAMATION")
  CH("YANCHAMU"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("CHOBOMAKI")
  })
  CH("YANCHAMU"):WaitManpu()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), -2141094195)
  WINDOW:Talk(SymAct("YANCHAMU"), -1421071090)
  subEveCloseMsg()
  CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1302913969)
  WINDOW:CloseMessage()
  local taskChobomaki00 = function()
    CH("CHOBOMAKI"):DirTo(SymPos("P00_CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):WaitRotate()
    CH("CHOBOMAKI"):WalkTo(SymPos("P00_CHOBOMAKI"), Speed(1.5))
    CH("CHOBOMAKI"):WaitMove()
  end
  local taskYanchamu00 = function()
    CH("YANCHAMU"):DirTo(SymPos("P00_YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("YANCHAMU"):WaitRotate()
    CH("YANCHAMU"):WalkTo(SymPos("P00_YANCHAMU"), Speed(1.5))
    CH("YANCHAMU"):WaitMove()
    CH("YANCHAMU"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("YANCHAMU"):WaitRotate()
    CH("YANCHAMU"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
    CH("YANCHAMU"):WaitNeckRot()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
    CH("YANCHAMU"):SetManpu("MP_QUESTION")
    CH("YANCHAMU"):WaitManpu()
  end
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(taskChobomaki00)
  TASK:Regist(Group("grpYanchamu"), taskYanchamu00)
  TASK:WaitTask(Group("grpYanchamu"))
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -48854392)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -468862007)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -819927030)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -700720821)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetNeckRot(TimeSec(0.15))
  CH("YANCHAMU"):WaitNeckRot()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("YANCHAMU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1369687428)
  WINDOW:Talk(SymAct("YANCHAMU"), 1220080837)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CH("YANCHAMU"):RunTo(SymPos("P01_YANCHAMU"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(SymPos("P01_YANCHAMU"), Speed(60), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(SymPos("P01_YANCHAMU"), Speed(60), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):RunTo(SymPos("P01_CHOBOMAKI"), Speed(3))
  TASK:Sleep(TimeSec(2))
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 566634729, PARTNER_1 = 954014120})
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 334514795, PARTNER_1 = 183204650})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  TASK:ExitNotifyTasks(Group("grpMoguryuu"))
  TASK:ExitNotifyTasks(Group("grpMoguryuu02"))
  TASK:ExitNotifyTasks(Group("grpMoguryuu03"))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):RunTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):RunTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CH("MOGURYUU2"):WalkTo(SymPos("P01_MOGURYUU2"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU3"):WalkTo(SymPos("P02_MOGURYUU3"), Speed(1.5))
  TASK:Sleep(TimeSec(1.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("MOGURYUU2"):SetManpu("MP_EXCLAMATION")
  CH("MOGURYUU2"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU3"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("MOGURYUU3"):SetManpu("MP_SHOCK_L")
  CH("MOGURYUU"):ResetManpu()
  CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("MOGURYUU"):DirTo(CH("PARTNER"), Speed(500), ROT_TYPE.NEAR)
  CH("MOGURYUU"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 20, SymAct("MOGURYUU2"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MOGURYUU2"), 1168829933)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT")
  CH("MOGURYUU3"):WaitManpu()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_03"), Volume(256))
  WINDOW:DrawFace(324, 20, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("MOGURYUU3"), 1555160236)
  WINDOW:Talk(SymAct("MOGURYUU3"), 2006749039)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1854389806, PARTNER_1 = -383802655})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("MOGURYUU2"):SetManpu("MP_SHOCK_R")
  CH("MOGURYUU3"):SetManpu("MP_SHOCK_L")
  CH("MOGURYUU"):SetManpu("MP_EXCLAMATION")
  CH("MOGURYUU2"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("MOGURYUU2"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("MOGURYUU2"), -268135520)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT")
  CH("MOGURYUU3"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("MOGURYUU"), 863209223)
  WINDOW:Talk(SymAct("MOGURYUU3"), 711505478)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 21357957, PARTNER_1 = 408868036})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1461666307, PARTNER_1 = 1308914498})
  WINDOW:SwitchTalk({PARTNER_0 = 1697194113, PARTNER_1 = 2083656128})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_EXCLAMATION")
  CH("MOGURYUU2"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("MOGURYUU3")
  })
  CH("MOGURYUU3"):SetManpu("MP_SHOCK_L")
  CH("MOGURYUU"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("MOGURYUU3"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MOGURYUU3"), -72741617)
  WINDOW:Talk(SymAct("MOGURYUU"), -491701170)
  WINDOW:Talk(SymAct("MOGURYUU"), -1949310878)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("PARTNER"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1831546589, PARTNER_1 = -1174830368})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_EXCLAMATION")
  CH("MOGURYUU2"):SetManpu("MP_SHOCK_R")
  CH("MOGURYUU3"):SetManpu("MP_SHOCK_L")
  CH("MOGURYUU3"):WaitManpu()
  TASK:Regist(subEveJumpSurprise, {
    CH("MOGURYUU2")
  })
  WINDOW:DrawFace(20, 20, SymAct("MOGURYUU2"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MOGURYUU2"), -1595755615)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -274520730, PARTNER_1 = -155708377})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -577419292, PARTNER_1 = -997296475})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1125542506, PARTNER_1 = 1510824747})
  WINDOW:SwitchTalk({PARTNER_0 = 370727131, PARTNER_1 = 251914650})
  WINDOW:CloseMessage()
  WINDOW:SysMsg(607042137)
  WINDOW:SelectStart()
  WINDOW:SelectChain(1026919192, 1)
  WINDOW:SelectChain(1920212447, 0)
  WINDOW:DefaultCursor(1)
  local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
  if id == 1 then
    WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
    WINDOW:SwitchTalk({PARTNER_0 = 1802448030, PARTNER_1 = 1078099805})
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("MOGURYUU"):SetManpu("MP_EXCLAMATION")
    CH("MOGURYUU2"):SetManpu("MP_SHOCK_R")
    CH("MOGURYUU3"):SetManpu("MP_SHOCK_L")
    CH("MOGURYUU3"):WaitManpu()
    WINDOW:DrawFace(20, 20, SymAct("MOGURYUU2"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MOGURYUU2"), 1499024924)
    subEveCloseMsg()
    WINDOW:DrawFace(324, 20, SymAct("MOGURYUU3"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MOGURYUU3"), -557755693)
    subEveCloseMsg()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
    CH("MOGURYUU"):WaitManpu()
    WINDOW:DrawFace(20, 20, SymAct("MOGURYUU"), FACE_TYPE.SURPRISE)
    WINDOW:DrawFaceOffset(30, 0)
    WINDOW:Talk(SymAct("MOGURYUU"), -941988974)
    WINDOW:CloseMessage()
    CH("PARTNER"):DirTo(SymPos("P00_RINGO"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    CH("HERO"):DirTo(SymPos("P00_RINGO"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.15))
    CH("PARTNER"):WaitNeckRot()
    CH("HERO"):WaitRotate()
    CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.15))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):WaitManpu()
    WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
    WINDOW:SwitchTalk({PARTNER_0 = -1364934722, PARTNER_1 = -1212182785})
    WINDOW:KeyWait()
    TASK:Regist(subEveDoubleJump, {
      CH("PARTNER")
    })
    WINDOW:SwitchTalk({PARTNER_0 = -1668096708, PARTNER_1 = -2054558595})
    TASK:WaitTask()
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
    CH("MOGURYUU3"):SetManpu("MP_SWEAT_L")
    CH("MOGURYUU"):SetManpu("MP_SWEAT_R")
    CH("MOGURYUU2"):SetManpu("MP_SWEAT_R")
    CH("MOGURYUU"):WaitManpu()
    TASK:Sleep(TimeSec(0.7))
    CAMERA:SetEye(SymCam("CAMERA_06_5"))
    CAMERA:SetTgt(SymCam("CAMERA_06_5"))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
    CH("MOGURYUU"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("MOGURYUU"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MOGURYUU"), -892831046)
    WINDOW:Talk(SymAct("MOGURYUU"), -741127173)
    WINDOW:CloseMessage()
    CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
    CAMERA:WaitMove()
    WINDOW:DrawFace(20, 88, SymAct("MOGURYUU2"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MOGURYUU2"), -117565384)
    WINDOW:CloseMessage()
    CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
    CAMERA:WaitMove()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT")
    CH("MOGURYUU3"):WaitManpu()
    WINDOW:DrawFace(324, 88, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
    WINDOW:Talk(SymAct("MOGURYUU3"), -505075335)
    WINDOW:CloseMessage()
    SOUND:FadeOutBgm(TimeSec(1))
    CAMERA:SetEye(SymCam("CAMERA_04"))
    CAMERA:SetTgt(SymCam("CAMERA_04"))
    TASK:Sleep(TimeSec(0.2))
    CH("MOGURYUU3"):DirTo(SymPos("P00_RINGO"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("MOGURYUU"):DirTo(SymPos("P00_RINGO"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU2"):DirTo(SymPos("P00_RINGO"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU3"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.15))
    TASK:Sleep(TimeSec(0.2))
    CH("MOGURYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.15))
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU2"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.15))
    CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
    CH("HERO"):ResetNeckRot(TimeSec(0.1))
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
    WINDOW:SwitchTalk({PARTNER_0 = 1719481782, PARTNER_1 = 2137392375})
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("MOGURYUU"):SetManpu("MP_SHOCK_L")
    CH("MOGURYUU2"):SetManpu("MP_SHOCK_L")
    CH("MOGURYUU3"):SetManpu("MP_SHOCK_L")
    CH("MOGURYUU2"):WaitManpu()
    TASK:Sleep(TimeSec(0.3))
    CAMERA:SetEye(SymCam("CAMERA_05"))
    CAMERA:SetTgt(SymCam("CAMERA_05"))
    WINDOW:DrawFace(324, 88, SymAct("MOGURYUU3"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MOGURYUU3"), -1139732400)
    WINDOW:CloseMessage()
    CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
    CAMERA:WaitMove()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
    CH("MOGURYUU"):WaitManpu()
    WINDOW:DrawFace(324, 88, SymAct("MOGURYUU"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MOGURYUU"), -1526062831)
    WINDOW:CloseMessage()
    CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
    CAMERA:WaitMove()
    CH("PARTNER"):RunTo(SymPos("P01_ENTER"), Speed(4))
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):RunTo(SymPos("P01_ENTER"), Speed(4))
    WINDOW:DrawFace(324, 88, SymAct("MOGURYUU2"), FACE_TYPE.SPECIAL01)
    WINDOW:Talk(SymAct("MOGURYUU2"), -1910017326)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT")
    WINDOW:Talk(SymAct("MOGURYUU2"), -1757658221)
    WINDOW:CloseMessage()
    CH("MOGURYUU2"):ResetNeckRot(TimeSec(0.2))
    TASK:Sleep(TimeSec(0.2))
    CH("MOGURYUU2"):DirTo(SymPos("P00_ENTER"), Speed(200), ROT_TYPE.NEAR)
    CH("MOGURYUU2"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("MOGURYUU2"):SetManpu("MP_SHOCK_R")
    CH("MOGURYUU2"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("MOGURYUU3"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MOGURYUU3"), -662842028)
    WINDOW:CloseMessage()
    CAMERA:SetEye(SymCam("CAMERA_08"))
    CAMERA:SetTgt(SymCam("CAMERA_08"))
    CH("MOGURYUU"):ResetNeckRot(TimeSec(0.2))
    TASK:Sleep(TimeSec(0.2))
    CH("MOGURYUU"):DirTo(SymPos("P00_ENTER"), Speed(350), ROT_TYPE.NEAR)
    CH("MOGURYUU3"):ResetNeckRot(TimeSec(0.2))
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU3"):DirTo(SymPos("P00_ENTER"), Speed(350), ROT_TYPE.NEAR)
    CH("MOGURYUU3"):WaitRotate()
    WINDOW:DrawFace(324, 20, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
    WINDOW:Talk(SymAct("MOGURYUU3"), -1050221547)
    WINDOW:CloseMessage()
    CH("MOGURYUU"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("MOGURYUU2"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU3"):DirTo(CH("MOGURYUU2"), Speed(350), ROT_TYPE.NEAR)
    CH("MOGURYUU3"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
    CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT")
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT")
    CH("MOGURYUU3"):WaitManpu()
    WINDOW:DrawFace(20, 20, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
    WINDOW:Talk(SymAct("MOGURYUU3"), -364136490)
    subEveCloseMsg()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
    CH("MOGURYUU3"):SetManpu("MP_SWEAT_L")
    CH("MOGURYUU3"):WaitManpu()
    WINDOW:DrawFace(324, 20, SymAct("MOGURYUU3"), FACE_TYPE.SPECIAL01)
    WINDOW:Talk(SymAct("MOGURYUU3"), -212826473)
    WINDOW:CloseMessage()
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    return "select1"
  else
    WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
    WINDOW:SwitchTalk({PARTNER_0 = 1959303768, PARTNER_1 = 1842588441})
    WINDOW:CloseMessage()
    SOUND:FadeOutBgm(TimeSec(0.5))
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    TASK:Sleep(TimeSec(0.5))
    return "select2"
  end
end
function main03_m03kaerimichi04_end()
end
function groundEnd()
end
