dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main05_hachimitsushuukakunojiki01_init()
end
function main05_hachimitsushuukakunojiki01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(163612036)
  WINDOW:Monologue(282834117)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(3),
    CH("HASUBURERO")
  })
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_02"), Volume(256))
  CH("HASUBURERO"):WalkTo(SymPos("P00_HASUBURERO"), Speed(1.5))
  CH("HASUBURERO"):WaitMove()
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), 1006036742)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HASUBURERO"):SetManpu("MP_FLY_SWEAT")
  CH("HASUBURERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), 586012231)
  subEveCloseMsg()
  CH("HIPOPOTASU"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(72, 16, SymAct("HIPOPOTASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 1840005248)
  WINDOW:CloseMessage()
  CH("HIPOPOTASU"):ResetManpu()
  CH("SUBOMII"):WalkTo(SymPos("P00_SUBOMII"), Speed(1.5))
  CH("SUBOMII"):WaitMove()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("SUBOMII"):SetManpu("MP_QUESTION")
  CH("SUBOMII"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SUBOMII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBOMII"), 1958179265)
  WINDOW:CloseMessage()
  local taskLookAt01 = function()
    CH("HIPOPOTASU"):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HASUBURERO"):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("ABAGOORA"):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  TASK:WaitTask()
  WINDOW:DrawFace(324, 20, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), 1603936770)
  WINDOW:Talk(SymAct("HASUBURERO"), 1182864195)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), -1055322228)
  WINDOW:Talk(SymAct("ABAGOORA"), -670941491)
  WINDOW:Talk(SymAct("ABAGOORA"), -467771319)
  subEveCloseMsg()
  CH("HIPOPOTASU"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("HIPOPOTASU")
  })
  WINDOW:DrawFace(72, 16, SymAct("HIPOPOTASU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(25, 0)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -49983224)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -702020917)
  WINDOW:CloseMessage()
  CH("HIPOPOTASU"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("SUBOMII"):SetManpu("MP_QUESTION")
  CH("SUBOMII"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SUBOMII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SUBOMII"), -818728054)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), -2139970227)
  WINDOW:Talk(SymAct("ABAGOORA"), -1721134068)
  WINDOW:Talk(SymAct("ABAGOORA"), -1304115249)
  WINDOW:Talk(SymAct("ABAGOORA"), -1419774322)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(751299137)
  WINDOW:Monologue(903666432)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main05_hachimitsushuukakunojiki01_end()
end
function groundEnd()
end
