dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main06_nyorobonriverboss2nd01_init()
end
function main06_nyorobonriverboss2nd01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  CH("NYOROBON"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFaceF(172, 8, SymAct("NYOROBON"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(50, 0)
  WINDOW:Talk(SymAct("NYOROBON"), 1688906730)
  subEveCloseMsg()
  CH("NYOROBON2"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(20, 20, SymAct("NYOROBON2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYOROBON2"), 2108791467)
  subEveCloseMsg()
  CH("NYOROBON3"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(324, 20, SymAct("NYOROBON3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYOROBON3"), 1453115752)
  subEveCloseMsg()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:DrawFaceOffset(10, 10)
  WINDOW:SwitchTalk({PARTNER_0 = 1334310953, PARTNER_1 = 13004526})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("NYOROMO"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("NYOROMO")
  })
  WINDOW:DrawFace(20, 88, SymAct("NYOROMO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYOROMO"), 433938351)
  WINDOW:CloseMessage()
  CH("NYOROMO"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.3))
  subEveFlash2()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main06_nyorobonriverboss2nd01_end()
end
function groundEnd()
end
