dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main02_nanikanokehai01_init()
end
function main02_nanikanokehai01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("EV02_SHADOW"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_KATAN"), Volume(256))
  SOUND:WaitSe(SymSnd("SE_EVT_KATAN"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1524594911)
  WINDOW:CloseMessage()
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KAGENYU"), Volume(256))
  GM("EV02_SHADOW"):SetVisible(true)
  GM("EV02_SHADOW"):SetMotion(SymMot("START"), LOOP.OFF)
  GM("EV02_SHADOW"):WaitPlayMotion()
  GM("EV02_SHADOW"):SetMotion(SymMot("KEEP"), LOOP.ON)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(3), LINK_DIR.OFF)
  CH("HERO"):WaitMove()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1136937374)
  WINDOW:CloseMessage()
  GM("EV02_SHADOW"):SetMotion(SymMot("FINISH"), LOOP.OFF)
  GM("EV02_SHADOW"):WaitPlayMotion()
  GM("EV02_SHADOW"):SetVisible(false)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  SOUND:PlaySe(SymSnd("SE_EVT_ZAZA"), Volume(256))
  WINDOW:SysMsg(1760107101)
  WINDOW:KeyWait()
  CH("HERO"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  local taskZazaza00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_ZAZAZA"), Volume(256))
    TASK:Sleep(TimeSec(0.7))
    SOUND:PlaySe(SymSnd("SE_EVT_ZAZAZA"), Volume(256))
  end
  TASK:Regist(taskZazaza00)
  WINDOW:SysMsg(1911696156)
  CH("HERO"):WaitRotate()
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1051966939)
  WINDOW:Monologue(665357466)
  WINDOW:Monologue(210100057)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main02_nanikanokehai01_end()
end
function groundEnd()
end
