dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_moguryutankouyarareta01_init()
end
function main03_moguryutankouyarareta01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 85805502, PARTNER_1 = 470186239})
  WINDOW:KeyWait()
  SCREEN_A:FadeOutAll(TimeSec(0.5), true)
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  CH("HERO"):SetDir(RotateTarget(45))
  CH("PARTNER"):SetDir(RotateTarget(-55))
  CH("HERO"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  local taskHeroDownUp = function()
    CH("HERO"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):ResetFacialMotion()
    subEveLookAround(CH("HERO"), Speed(600))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(500), ROT_TYPE.NEAR)
  end
  local taskPartnerDownUp = function()
    CH("PARTNER"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):ResetFacialMotion()
    subEveLookAround02(CH("PARTNER"), Speed(600))
    CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT")
  CH("MOGURYUU3"):SetManpu("MP_FLY_SWEAT")
  CH("MOGURYUU3"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("MOGURYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOGURYUU"), 925575996)
  WINDOW:CloseMessage()
  TASK:Regist(Group("hero"), taskHeroDownUp)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(Group("partner"), taskPartnerDownUp)
  TASK:WaitTask(Group("partner"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 774904445, PARTNER_1 = 1634831546})
  WINDOW:KeyWait()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 2020261371, PARTNER_1 = 1397222968})
  WINDOW:SwitchTalk({PARTNER_0 = 1247600505, PARTNER_1 = -842742858})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU2"):SetManpu("MP_SHOCK_L")
  CH("MOGURYUU3"):SetManpu("MP_SHOCK_L")
  CH("MOGURYUU3"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("MOGURYUU3"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MOGURYUU3"), -723520777)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main03_moguryutankouyarareta01_end()
end
function main03_moguryutankouyarareta02_init()
end
function main03_moguryutankouyarareta02_start()
  SCREEN_A:FadeOut(TimeSec(0), false)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1399143542)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:SysMsg(1249774903)
  SOUND:WaitSe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(1.5))
  local taskNumeShiki01 = function()
    CH("NUMERA"):SetMotion(SymMot("PULL"), LOOP.ON)
    CH("NUMERA"):SetMotionRaito(Raito(2))
    TASK:Sleep(TimeSec(0.5))
    CH("NUMERA"):SetMotion(SymMot("PULL"), LOOP.ON)
    CH("NUMERA"):SetMotionRaito(Raito(2))
    TASK:Sleep(TimeSec(0.5))
    CH("NUMERA"):SetMotionRaito(Raito(1))
    CH("NUMERA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveNod(CH("SHIKIJIKA_SPRING"))
    CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(1.5))
    TASK:Sleep(TimeSec(0.2))
    CH("NUMERA"):WalkTo(SymPos("P00_NUMERA"), Speed(1.5))
  end
  TASK:Regist(Group("grpNumeShiki01"), taskNumeShiki01)
  local taskYanChobo01 = function()
    CH("CHOBOMAKI"):RunTo(SplinePath(SymPos("P00_YANCHOBO"), SymPos("P01_YANCHOBO")), Speed(3))
    TASK:Sleep(TimeSec(0.2))
    CH("YANCHAMU"):RunTo(SplinePath(SymPos("P00_YANCHOBO"), SymPos("P01_YANCHOBO")), Speed(3))
  end
  TASK:Regist(Group("grpYanChobo01"), taskYanChobo01)
  local taskHero01 = function()
    CH("HERO"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.ON)
    TASK:Sleep(TimeSec(0.7))
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.RIGHT)
    CH("HERO"):WaitRotate()
    CH("HERO"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.ON)
    TASK:Sleep(TimeSec(0.5))
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(-125), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  TASK:Regist(taskHero01)
  local taskPartner01 = function()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("NUMERA"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("CHOBOMAKI"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  TASK:Regist(Group("grpPartner01"), taskPartner01)
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask(Group("grpPartner01"))
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1632853748, PARTNER_1 = 2018013109})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 923400562, PARTNER_1 = 772982835})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  SOUND:FadeOutBgm(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main03_moguryutankouyarareta02_end()
end
function groundEnd()
end
