dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function sub01_myuutonoseikatsu2nd01_init()
end
function sub01_myuutonoseikatsu2nd01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P00_HERO"),
    Speed(1.5),
    CH("MYUU")
  })
  CH("MYUU"):WalkTo(SymPos("P00_MYUU"), Speed(1.5))
  CH("KOROBOOSHI"):WalkTo(SymPos("P00_KOROBOOSHI"), Speed(1.2))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("MYUU"):WaitMove()
  CH("MYUU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("MYUU"):WaitRotate()
  CH("MYUU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("MYUU"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("MYUU")
  })
  WINDOW:DrawFace(324, 88, SymAct("MYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MYUU"), -48186602)
  WINDOW:Talk(SymAct("MYUU"), -465860009)
  WINDOW:Talk(SymAct("MYUU"), -820586092)
  WINDOW:Talk(SymAct("MYUU"), -703731499)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("MYUU"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MYUU"):SetManpu("MP_EXCLAMATION")
  CH("MYUU"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("MYUU")
  })
  WINDOW:DrawFace(324, 20, SymAct("MYUU"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MYUU"), -1723040238)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(-2141761709)
  subEveCloseMsg()
  local taskMyuu00 = function()
    CH("MYUU"):SetManpu("MP_SPREE_LP")
    CH("MYUU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
    CH("MYUU"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("MYUU"):WaitPlayMotion()
    CH("MYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskMyuu00)
  WINDOW:DrawFace(324, 88, SymAct("MYUU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("MYUU"), -1418060656)
  TASK:WaitTask()
  subEveCloseMsg()
  CH("MYUU"):ResetManpu()
  CH("MYUU"):ResetFacialMotion()
  TASK:Regist(subEveDoubleJump, {
    CH("MYUU")
  })
  WINDOW:DrawFace(324, 88, SymAct("MYUU"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MYUU"), -1302254127)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("MYUU"):SetMotion(SymMot("SB001_DOYA00"), LOOP.OFF)
  CH("MYUU"):WaitPlayMotion()
  CH("MYUU"):SetMotion(SymMot("SB001_DOYA01"), LOOP.ON)
  WINDOW:DrawFace(324, 20, SymAct("MYUU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("MYUU"), 905523486)
  WINDOW:Talk(SymAct("MYUU"), 753008735)
  WINDOW:CloseMessage()
  SOUND:VolumeBgm(Volume(32), TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(1711825306)
  WINDOW:Monologue(2131972315)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
end
function sub01_myuutonoseikatsu2nd01_end()
end
function sub01_myuutonoseikatsu2nd02_init()
end
function sub01_myuutonoseikatsu2nd02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  local taskPartner00 = function()
    CH("PARTNER"):SetMotion(SymMot("EV026_DOYA00"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("EV026_DOYA01"), LOOP.ON)
  end
  TASK:Regist(taskPartner00)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL04)
  WINDOW:SwitchTalk({PARTNER_0 = 1413350168, PARTNER_1 = 1294283353})
  WINDOW:SwitchTalk({PARTNER_0 = 40150174, PARTNER_1 = 461346271})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("HERO"):WaitManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  EFFECT:DestroyRecollectionFilter()
end
function sub01_myuutonoseikatsu2nd02_end()
end
function sub01_myuutonoseikatsu2nd03_init()
end
function sub01_myuutonoseikatsu2nd03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetDir(CH("MYUU"))
  CH("MYUU"):SetDir(CH("HERO"))
  CH("MYUU"):SetMotion(SymMot("SB001_DOYA01"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(810731036)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("MYUU"):SetMotion(SymMot("SB001_DOYA02"), LOOP.OFF)
  CH("MYUU"):WaitPlayMotion()
  CH("MYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("MYUU"):SetManpu("MP_QUESTION")
  CH("MYUU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("MYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MYUU"), 692713309)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1361974382)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):ResetFacialMotion()
  CH("MYUU"):SetManpu("MP_SPREE_LP")
  CH("MYUU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  TASK:Regist(subEveDoubleJump, {
    CH("MYUU")
  })
  WINDOW:DrawFace(324, 20, SymAct("MYUU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("MYUU"), -1211442477)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_HARAHERI"), Volume(256))
  TASK:Sleep(TimeSec(1.5))
  CH("MYUU"):ResetManpu()
  CH("MYUU"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MYUU"):SetManpu("MP_EXCLAMATION")
  CH("MYUU"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("MYUU"):SetManpu("MP_QUESTION")
  CH("MYUU"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("MYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MYUU"), 1958596212)
  WINDOW:Talk(SymAct("MYUU"), 1839660853)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Regist(subEveNoNoNo, {
    CH("HERO")
  })
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 20, SymAct("MYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MYUU"), 1183558902)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("MYUU")
  })
  WINDOW:Talk(SymAct("MYUU"), 1603313079)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("MYUU"):WalkTo(SymPos("P00_MYUU"), Speed(1.5))
  CH("HERO"):DirTo(SymPos("P00_HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:FadeOutBgm(TimeSec(1.5))
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(-65), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(282135408)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(164248113)
  WINDOW:CloseMessage()
  CH("MYUU"):SetDir(CH("HERO"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  CH("MYUU"):SetManpu("MP_SPREE_LP")
  CH("MYUU"):ResetManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("MYUU")
  })
  WINDOW:DrawFace(324, 20, SymAct("MYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MYUU"), 585591282)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):RunTo(SplinePath(SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(2.5))
  TASK:Sleep(TimeSec(0.5))
  CH("MYUU"):RunTo(SymPos("P01_MYUU"), Speed(2.5))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function sub01_myuutonoseikatsu2nd03_end()
end
function groundEnd()
end
