dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function MIRUHOGGU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1359624902)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SHOUT)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1209076615)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1664899140)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:Talk(SymAct("KAMONEGI"), 2049403141)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), 895942594)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIYAKKII"), 746442371)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function TABUNNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TABUNNE"), 122723648)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  subEveJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.SHOUT)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.TALK)
  WINDOW:Talk(SymAct("TABUNNE"), 508275713)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SHIKIJIKA_SPRING(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1714179890)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -2134343281)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 2106571545)
  WINDOW:Talk(SymAct("NYASUPAA"), 1687456344)
  WINDOW:CloseMessage()
end
function BUBII(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_NOTICE_L")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BUBII"), 1337579931)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("BUBII"), 1453517018)
  WINDOW:Talk(SymAct("BUBII"), 434339357)
  WINDOW:Talk(SymAct("BUBII"), 16273244)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HASUBURERO(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HASUBURERO"), 735386783)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function ABAGOORA(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), 852372958)
  WINDOW:Talk(SymAct("ABAGOORA"), -1252642543)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.SPECIAL01)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("ABAGOORA"), -1404239792)
  WINDOW:Talk(SymAct("ABAGOORA"), 1866077431)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function ROZERIA(chSymb0)
  CH(chSymb0):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("ROZERIA"), 1981883830)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function SUBOMII(chSymb0, chSymb1, chSymb2)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("SUBOMII"), 1561097845)
  subEveCloseMsg()
  CH(chSymb1):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb2):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH(chSymb1):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(20, 88, SymAct("KORATTA"), FACE_TYPE.PAIN)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("KORATTA"), 1142376244)
  subEveDoubleJump(CH(chSymb1))
  subEveCloseMsg()
  CH(chSymb2):SetManpu("MP_UPSET_LP")
  CH(chSymb2):DirTo(CH(chSymb1), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("TOGEPII"), FACE_TYPE.PAIN)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("TOGEPII"), 190239219)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
  CH(chSymb2):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb2):ResetFacialMotion()
end
function KORATTA(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function TOGEPII(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function DENRYUU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_NOTICE_L")
  CH(chSymb0):WaitManpu()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 307093682)
  WINDOW:Talk(SymAct("DENRYUU"), 962638705)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.SURPRISE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("DENRYUU"), 544965168)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.OFF)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  CH(chSymb0):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1478254849)
  WINDOW:Talk(SymAct("DENRYUU"), -1090998338)
  WINDOW:CloseMessage()
end
function KYATAPII(chSymb0, chSymb1, chSymb2)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("KYATAPII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KYATAPII"), -679054446)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  subEveCloseMsg()
  CH(chSymb0):ResetManpu()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("PUPURIN"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("PUPURIN"), -828554541)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  subEveCloseMsg()
  CH(chSymb1):ResetManpu()
  CH(chSymb2):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("UPAA"), FACE_TYPE.HAPPY)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("UPAA"), -441446128)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  WINDOW:CloseMessage()
  CH(chSymb2):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb2):ResetFacialMotion()
end
function PUPURIN(chSymb0, chSymb1, chSymb2)
  KYATAPII(chSymb0, chSymb1, chSymb2)
end
function UPAA(chSymb0, chSymb1, chSymb2)
  KYATAPII(chSymb0, chSymb1, chSymb2)
end
