dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function MYUU(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("MYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MYUU"), -599827232)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MIRUTANKU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MIRUTANKU"), -987468383)
  WINDOW:KeyWait()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):SetManpu("MP_QUESTION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUTANKU"), -301384094)
  WINDOW:CloseMessage()
  CH(chSymb0):WaitManpu()
  CH(chSymb0):ResetFacialMotion()
end
function BURUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURUU"), -149811421)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_QUESTION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURUU"), -1202480668)
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BURUU"), -1589073755)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KOROBOOSHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KOROBOOSHI"), -1973027994)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DOREDYIA(chSymb0)
  CH(chSymb0):SetManpu("MP_QUESTION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOREDYIA"), -1820407257)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOREDYIA"), 350672616)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOODOO"), 234743721)
  WINDOW:KeyWait()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), 444625253)
  WINDOW:CloseMessage()
end
function KOJOFUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), 60506148)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KOJOFUU"), 683021287)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MUKKURU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MUKKURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MUKKURU"), 833430182)
  WINDOW:Talk(SymAct("MUKKURU"), 2129441889)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("MUKKURU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MUKKURU"), 1744274720)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function SUBAME(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SUBAME"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBAME"), 1289410275)
  WINDOW:CloseMessage()
end
function YAYAKOMA(chSymb0)
  TASK:Sleep(TimeSec(0.3))
  CH(chSymb0):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb0):SetManpu("MP_EXCLAMATION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH(chSymb0):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CH(chSymb0):SetManpu("MP_HEART")
  CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("YAYAKOMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("YAYAKOMA"), 1438771106)
  WINDOW:CloseMessage()
  CH(chSymb0):WaitManpu()
end
function NOZUPASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NOZUPASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOZUPASU"), -765854867)
  WINDOW:CloseMessage()
end
function NAZONOKUSA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NAZONOKUSA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NAZONOKUSA"), -884815316)
  WINDOW:Talk(SymAct("NAZONOKUSA"), 137748107)
  WINDOW:CloseMessage()
end
function DENRYUU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 288288714)
  WINDOW:CloseMessage()
end
function DEDENNE(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 973323273)
  CH(chSymb1):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.5))
  CH(chSymb1):WaitRotate()
  WINDOW:KeyWait()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), 588811592)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
  CH(chSymb1):ResetFacialMotion()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), 1817779087)
  WINDOW:Talk(SymAct("KUCHIITO"), 1967270606)
  WINDOW:CloseMessage()
end
function JIRAACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("JIRAACHI"), 1584363789)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("JIRAACHI"), 1198803020)
  WINDOW:CloseMessage()
end
function PEROPPAFU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1058253693)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
  WINDOW:Talk(SymAct("PEROPPAFU"), -638097982)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.CATCHBREATH)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.CATCHBREATH)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1333151250)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH(chSymb0):SetManpu("MP_SWEAT_L")
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SHIKIJIKA_SPRING(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1450014545)
  WINDOW:KeyWait()
  CH(chSymb0):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -2101355668)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  CH(chSymb1):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), -1683690963)
  WINDOW:Talk(SymAct("NUMERA"), -723157782)
  WINDOW:CloseMessage()
end
function NUMERA(chSymb0, chSymb1)
  SHIKIJIKA_SPRING(chSymb0, chSymb1)
end
function JIBAKOIRU(chSymb0, chSymb1, chSymb2)
  WINDOW:DrawFace(20, 88, SymAct("JIBAKOIRU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -838971989)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("KOIRU"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KOIRU"), -422371736)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("REAKOIRU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("REAKOIRU"), -3657943)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb2):ResetFacialMotion()
end
function KOIRU(chSymb0, chSymb1, chSymb2)
  JIBAKOIRU(chSymb0, chSymb1, chSymb2)
end
function REAKOIRU(chSymb0, chSymb1, chSymb2)
  JIBAKOIRU(chSymb0, chSymb1, chSymb2)
end
function UPAA(chSymb0, chSymb1, chSymb2)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH(chSymb0):SetManpu("MP_EXCLAMATION")
  CH(chSymb0):WaitManpu()
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("UPAA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("UPAA"), 2018522086)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("KYATAPII"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KYATAPII"), 1632305831)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
  CH(chSymb2):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb2):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb2):SetManpu("MP_QUESTION")
  CH(chSymb2):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("TOGEPII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TOGEPII"), 761168215)
  TASK:Sleep(TimeSec(0.3))
  CH(chSymb0):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH(chSymb1):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):WaitRotate()
  WINDOW:CloseMessage()
  CH(chSymb2):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("TOGEPII"), FACE_TYPE.HAPPY)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("TOGEPII"), 876982294)
  WINDOW:CloseMessage()
  CH(chSymb2):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb2):ResetFacialMotion()
end
function KYATAPII(chSymb0, chSymb1, chSymb2)
  UPAA(chSymb0, chSymb1, chSymb2)
end
function TOGEPII(chSymb0, chSymb1, chSymb2)
  UPAA(chSymb0, chSymb1, chSymb2)
end
function ROZERIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), 526967765)
  WINDOW:CloseMessage()
end
function BUBII(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BUBII"), 108253844)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function ABAGOORA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), 1228031059)
  subEveCloseMsg()
  CH(chSymb0):DirTo(CH("MYUU"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH(chSymb0):SetManpu("MP_EXCLAMATION")
  subEveJump(CH(chSymb0))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.SURPRISE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("ABAGOORA"), 1344894226)
  subEveCloseMsg()
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  subEveNoNoNo(CH(chSymb0))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("ABAGOORA"), 2063869649)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("ABAGOORA"), 1646204816)
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("ABAGOORA"), -444134561)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KAMONEGI"), -56870370)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("KAMONEGI"), -1780292046)
  WINDOW:CloseMessage()
end
