dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function SHIKIJIKA_SPRING(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1775439701)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1892171286)
  WINDOW:Talk(SymAct("NYASUPAA"), -1541762519)
  WINDOW:CloseMessage()
end
function MIRUHOGGU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.ANGRY)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_ANGRY_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1123966104)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -230672977)
  WINDOW:CloseMessage()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SHOUT)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -346356498)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function CHOBOMAKI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1065986259)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH(chSymb0):SetManpu("MP_SWEAT_R")
  CH(chSymb0):WaitManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -647141780)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1593146019)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("KAMONEGI"), 1206799330)
  WINDOW:Talk(SymAct("KAMONEGI"), -697482629)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -814320838)
  WINDOW:Talk(SymAct("HIYAKKII"), -463789831)
  WINDOW:CloseMessage()
end
function RATTA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -46132808)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("RATTA"), -1308522625)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -1424312770)
  WINDOW:Talk(SymAct("RATTA"), -2143820291)
  WINDOW:Talk(SymAct("RATTA"), -1725115204)
  WINDOW:CloseMessage()
end
function HIPOPOTASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 515164275)
  WINDOW:CloseMessage()
  subEveDoubleJump(CH(chSymb0))
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 128973106)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), -992416363)
  WINDOW:CloseMessage()
end
function ABAGOORA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("ABAGOORA"), -574366508)
  WINDOW:Talk(SymAct("ABAGOORA"), -152137961)
  WINDOW:CloseMessage()
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("ABAGOORA"), -269107626)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KAKUREON(chSymb)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1598805871)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1179706928)
  subEveCloseMsg()
  CH("HERO"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1836955117)
  WINDOW:CloseMessage()
end
