dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 624323558, PARTNER_1 = 1009605287})
  WINDOW:SwitchTalk({PARTNER_0 = 385878372, PARTNER_1 = 236664869})
  WINDOW:CloseMessage()
end
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.CATCHBREATH)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.CATCHBREATH)
  WINDOW:Talk(SymAct("HASUBURERO"), 1096462050)
  WINDOW:Talk(SymAct("HASUBURERO"), 1480695715)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIPOPOTASU(chSymb0, chSymb1, chSymb2)
  CH(chSymb0):SetManpu("MP_SWEAT_R")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 1936510048)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIMANATTSU(chSymb0, chSymb1, chSymb2)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIMANATTSU"), 1786248481)
  WINDOW:CloseMessage()
end
function RATTA(chSymb0, chSymb1, chSymb2)
  CH(chSymb2):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb2):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.THINK)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("RATTA"), -303046162)
  WINDOW:CloseMessage()
end
function KAKUREON(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.SURPRISE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("KAKUREON"), -185282385)
  WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("KAKUREON"), -194540827)
  WINDOW:KeyWait()
  CH(chSymb0):ResetFacialMotion()
end
function GARUURA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("GARUURA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GARUURA"), -310592604)
  WINDOW:DrawFace(20, 88, SymAct("GARUURA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("GARUURA"), -967710617)
  WINDOW:CloseMessage()
end
