dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -2000109385, PARTNER_1 = -1848380938})
  WINDOW:SwitchTalk({PARTNER_0 = -1157717451, PARTNER_1 = -1545235596})
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("NYASUPAA"), -324794957)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SHIKIJIKA_SPRING(chSymb0, chSymb1)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -172018446)
  subEveCloseMsg()
  CH(chSymb0):ResetManpu()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), -560830671)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
end
function NUMERA(chSymb0, chSymb1)
  SHIKIJIKA_SPRING(chSymb0, chSymb1)
end
function ABAGOORA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("ABAGOORA"), -947300752)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  subEveNoNoNo(CH(chSymb0))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:Talk(SymAct("ABAGOORA"), 1074875071)
  WINDOW:CloseMessage()
  CH(chSymb0):WaitManpu()
end
function HIMANATTSU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIMANATTSU"), 1493859326)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("HIMANATTSU"), 381890926)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  subEveJumpSurprise(CH(chSymb0))
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function RATTA(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.SURPRISE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("RATTA"), 265814063)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIPOPOTASU(chSymb0)
  CH(chSymb0):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 620057580)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):SetMotion(SymMot("WAIT02"), LOOP.ON)
end
function HASUBURERO(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("HASUBURERO"), 1039033005)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("HASUBURERO"), 1924133994)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.CATCHBREATH)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("HASUBURERO"), 1807009067)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KONOHANA(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH(chSymb0):SetManpu("MP_EXCLAMATION")
  subEveJump(CH(chSymb0))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 1083807464)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KONOHANA"), 1501734825)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function ROZERIA(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("ROZERIA"), -568673434)
  CH(chSymb0):ResetManpu()
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.SPECIAL02)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("ROZERIA"), -956200409)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
end
function SUBOMII(chSymb0)
  CH(chSymb0):SetManpu("MP_UPSET_LP")
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("SUBOMII"), 74882688)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), 493727681)
  WINDOW:CloseMessage()
end
function TABUNNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TABUNNE"), 910228482)
  WINDOW:Talk(SymAct("TABUNNE"), 794545475)
  WINDOW:CloseMessage()
end
function JIBAKOIRU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 1612340100)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 2030136005)
  WINDOW:CloseMessage()
end
function KOIRU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("KOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOIRU"), 1378629894)
  WINDOW:CloseMessage()
end
function REAKOIRU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  subEveJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("REAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("REAKOIRU"), 1261897799)
  WINDOW:CloseMessage()
end
