dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1714732945, PARTNER_1 = 2133823184})
  WINDOW:SwitchTalk({PARTNER_0 = 1409473811, PARTNER_1 = 1293544530})
  WINDOW:CloseMessage()
end
function RATTA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), 39352981)
  WINDOW:CloseMessage()
end
function SUBOMII(chSymb0, chSymb1, chSymb2)
  CH(chSymb0):DirTo(CH(chSymb2), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb2):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb2):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KYATAPII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KYATAPII"), 457395156)
  subEveCloseMsg()
  subEveNod(CH("SUBOMII"))
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.HAPPY)
  CH("SUBOMII"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SUBOMII"), 812521495)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH("SUBOMII"))
  subEveCloseMsg()
  CH(chSymb0):DirTo(CH(chSymb1), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb1):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("TOGEPII"), FACE_TYPE.HAPPY)
  CH("TOGEPII"):SetFacialMotion(FACIAL_MOTION.EMOTION)
  WINDOW:Talk(SymAct("TOGEPII"), 695544150)
  WINDOW:CloseMessage()
end
function TOGEPII(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function KYATAPII(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function HIMEGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMEGUMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIMEGUMA"), -1360185959)
  WINDOW:Talk(SymAct("HIMEGUMA"), -1208613672)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function RINGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RINGUMA"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("RINGUMA"), 363278363)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), 213647706)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("HASUBURERO"), 663835289)
  WINDOW:CloseMessage()
end
function BUBII(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BUBII"), 1049256920)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function HIMANATTSU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("HIMANATTSU"), 1909191967)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.SPECIAL01)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("HIMANATTSU"), 1758512222)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.GLADNESS)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIMANATTSU"), 1140692893)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIPOPOTASU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 1525065436)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function KAKUREON(chSymb0, bFirst)
end
