dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1998077819, PARTNER_1 = -1845694012})
  WINDOW:CloseMessage()
end
function KUCHIITO(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), -1160666617)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HORUBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HORUBII"), -1547005114)
  WINDOW:Talk(SymAct("HORUBII"), -326433407)
  WINDOW:CloseMessage()
end
function BUIZERU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUIZERU"), -175098688)
  WINDOW:CloseMessage()
end
function AAKEN(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -558012669)
  WINDOW:Talk(SymAct("AAKEN"), -945400254)
  WINDOW:CloseMessage()
end
function YAMIKARASU(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1077824141)
  WINDOW:KeyWait()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1495628748)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BURUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURUU"), -72129232)
  WINDOW:Talk(SymAct("BURUU"), -492284815)
  WINDOW:CloseMessage()
end
function MASSUGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), -914028622)
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MASSUGUMA"), -794937613)
  WINDOW:CloseMessage()
end
function KOROBOOSHI(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KOROBOOSHI"), -1612734412)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MIRUTANKU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUTANKU"), -2033938059)
  WINDOW:CloseMessage()
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), -1377189194)
  WINDOW:CloseMessage()
end
function PURASURU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("PURASURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PURASURU"), -1259146249)
  WINDOW:CloseMessage()
end
function MAINAN(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("MAINAN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MAINAN"), 862646072)
  WINDOW:CloseMessage()
end
function RAPURASU(chSymb0)
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 712105593)
  WINDOW:Talk(SymAct("DENRYUU"), -385430818)
  WINDOW:Talk(SymAct("DENRYUU"), -266470497)
  WINDOW:CloseMessage()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -617568164)
  WINDOW:CloseMessage()
end
function JIRAACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -1037330147)
  WINDOW:Talk(SymAct("JIRAACHI"), -1922428966)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("JIRAACHI"), -1804517733)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function PEROPPAFU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1084461736)
  WINDOW:KeyWait()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1505272807)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:KeyWait()
  WINDOW:Talk(SymAct("PEROPPAFU"), 568279254)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
