dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1295114454, PARTNER_1 = 1412092311})
  WINDOW:SwitchTalk({PARTNER_0 = 2131198548, PARTNER_1 = 1713156885})
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NUMERA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NUMERA"), 693970386)
  subEveJump(CH(chSymb0))
  WINDOW:Talk(SymAct("NUMERA"), 809899155)
  WINDOW:CloseMessage()
end
function SHIKIJIKA_SPRING(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 460015440)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 40924689)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -2048365858)
  WINDOW:CloseMessage()
end
