dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function SHIKIJIKA_SPRING(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -6684906)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NUMERA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("NUMERA"), -427635113)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function CHOBOMAKI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -844128876)
  WINDOW:CloseMessage()
end
function YANCHAMU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -726356779)
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1678427630)
  WINDOW:CloseMessage()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.RELIEF)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("KAMONEGI"), -2098328749)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("KAMONEGI"), -1446815600)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("KAMONEGI"), -1327994415)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HASUBURERO(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HASUBURERO"), 926971166)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function HIPOPOTASU(chSymb0)
  CH(chSymb0):SetManpu("MP_QUESTION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 777733215)
  WINDOW:CloseMessage()
end
function PUPURIN(chSymb0, chSymb1, chSymb2)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("PUPURIN"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("PUPURIN"), 398059178)
  WINDOW:CloseMessage()
  CH(chSymb0):DirTo(CH(chSymb1), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb2):DirTo(CH(chSymb1), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb0):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("UPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("UPAA"), 245553131)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):DirTo(CH(chSymb2), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):DirTo(CH(chSymb2), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):WaitRotate()
  CH(chSymb2):SetManpu("MP_SPREE_LP")
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  WINDOW:DrawFace(20, 88, SymAct("KORATTA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KORATTA"), 630162472)
  WINDOW:CloseMessage()
  CH(chSymb2):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_SHOCK_R")
  CH(chSymb1):SetManpu("MP_SHOCK_R")
  CH(chSymb1):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CH(chSymb2):ResetFacialMotion()
end
function UPAA(chSymb0, chSymb1, chSymb2)
  PUPURIN(chSymb0, chSymb1, chSymb2)
end
function KORATTA(chSymb0, chSymb1, chSymb2)
  PUPURIN(chSymb0, chSymb1, chSymb2)
end
function GARUURA(chSymb0, bFirst)
  if bFirst then
    WINDOW:DrawFace(20, 88, SymAct("GARUURA"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("GARUURA"), 1016378729)
    WINDOW:KeyWait()
  else
  end
end
function HIMEGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMEGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIMEGUMA"), 1943348142)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function RINGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RINGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RINGUMA"), 1791890159)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function ROZERIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), 1105412396)
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("ROZERIA"), 1492676717)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
