dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function KONOHANA(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KONOHANA"), 25787461)
  WINDOW:Talk(SymAct("KONOHANA"), 412241156)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function ABAGOORA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("ABAGOORA"), 868163271)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("ABAGOORA"), 715403142)
  WINDOW:CloseMessage()
end
function HIMANATTSU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIMANATTSU"), 1709553985)
  WINDOW:Talk(SymAct("HIMANATTSU"), 2097055744)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BUBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUBII"), 1473502147)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BUBII"), 1321790082)
  WINDOW:CloseMessage()
end
function RATTA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -917440947)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("RATTA"), -800340212)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
