dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1715881859, PARTNER_1 = -2136831684})
  WINDOW:SwitchTalk({PARTNER_0 = -1416635649, PARTNER_1 = -1298863170})
  WINDOW:CloseMessage()
end
function AAKEN(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -36340359)
  WINDOW:CloseMessage()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -456242120)
  WINDOW:Talk(SymAct("KUCHIITO"), -807198725)
  WINDOW:CloseMessage()
end
function HORUBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HORUBII"), -688378182)
  WINDOW:CloseMessage()
end
function BUIZERU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUIZERU"), 1365258869)
  WINDOW:Talk(SymAct("BUIZERU"), 1216021300)
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("BUIZERU"), 2030626517)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 1611913108)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), 1262388311)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MIRUTANKU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUTANKU"), 1378202902)
  WINDOW:CloseMessage()
end
function YAMIKARASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YAMIKARASU"), 493102033)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("YAMIKARASU"), 75436688)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BURUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURUU"), 793919827)
  WINDOW:CloseMessage()
end
function DOREDYIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOREDYIA"), 910782482)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOREDYIA"), -1311675171)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), -1463132772)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:Talk(SymAct("DOODOO"), 1807567163)
  WINDOW:CloseMessage()
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1923512442)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("DENRYUU"), 1502292921)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), 1083185912)
  WINDOW:Talk(SymAct("JIRAACHI"), 265391167)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("JIRAACHI"), 382385534)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function PEROPPAFU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1038610109)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.GLADNESS)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:Talk(SymAct("PEROPPAFU"), 620552188)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
