dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 93674951, PARTNER_1 = 479095942})
  WINDOW:SwitchTalk({PARTNER_0 = 933445445, PARTNER_1 = 783814148})
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MIRUTANKU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MIRUTANKU"), 1643747523)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KOROBOOSHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOROBOOSHI"), 2028120450)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KOROBOOSHI"), 1406138945)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function YAMIKARASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  CH(chSymb0):SetManpu("MP_SWEAT_R")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  WINDOW:Talk(SymAct("YAMIKARASU"), 1255459584)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DOREDYIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOREDYIA"), -850602033)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MASSUGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), -732436850)
  WINDOW:Talk(SymAct("MASSUGUMA"), -1220400580)
  WINDOW:CloseMessage()
end
function DOODOO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), -1369891971)
  WINDOW:Talk(SymAct("DOODOO"), -2055976770)
  WINDOW:CloseMessage()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOODOO"), -1670415873)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function NOZUPASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NOZUPASU"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("NOZUPASU"), -751898824)
  WINDOW:Talk(SymAct("NOZUPASU"), -902439303)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SHIMAMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SHIMAMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIMAMA"), -518484550)
  WINDOW:CloseMessage()
end
function CHIRAAMII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("CHIRAAMII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHIRAAMII"), -133972741)
  WINDOW:CloseMessage()
end
function SUBAME(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SUBAME"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBAME"), 2140905524)
  WINDOW:CloseMessage()
end
function WARUBIRU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("WARUBIRU"), 1719701877)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function WARUBIARU(chSymb0)
  CH(chSymb0):SetManpu("MP_ANGRY_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("WARUBIARU"), FACE_TYPE.ANGRY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("WARUBIARU"), -1510505006)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:Talk(SymAct("WARUBIARU"), -1125337965)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function TANEBOO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TANEBOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TANEBOO"), -1748900016)
  WINDOW:CloseMessage()
end
function GOOGOOTO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("GOOGOOTO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GOOGOOTO"), -1898260975)
  WINDOW:CloseMessage()
end
function DONFAN(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DONFAN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DONFAN"), -1046789930)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SWEAT_L")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DONFAN"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("DONFAN"), -662670953)
  WINDOW:Talk(SymAct("DONFAN"), -206757292)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function RAPURASU(chSymb0)
end
function DENRYUU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), -357166315)
  WINDOW:Talk(SymAct("DENRYUU"), 1831735258)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function DEDENNE(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), 1949646491)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), 491512503)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("KUCHIITO"), 72406006)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("JIRAACHI"), 796753973)
  WINDOW:Talk(SymAct("JIRAACHI"), 912699764)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function PEROPPAFU(chSymb0)
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.TEARS)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.TEARS)
  WINDOW:Talk(SymAct("PEROPPAFU"), 2032609203)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetManpu()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1614550770)
  WINDOW:CloseMessage()
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.GLADNESS)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1259423025)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
