dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function KONOHANA(chSymb0, bFirst)
  if bFirst then
    WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("KONOHANA"), -161925524)
    WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
    CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
    WINDOW:Talk(SymAct("KONOHANA"), -280885459)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
    CH(chSymb0):SetManpu("MP_SWEAT_R")
    CH(chSymb0):WaitManpu()
    WINDOW:Talk(SymAct("KONOHANA"), -999336722)
    WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
    CH(chSymb0):ResetFacialMotion()
    WINDOW:Talk(SymAct("KONOHANA"), -579574353)
    WINDOW:Talk(SymAct("KONOHANA"), -1841958040)
    WINDOW:Talk(SymAct("KONOHANA"), -1959869911)
    WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
    CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH(chSymb0):SetManpu("MP_LAUGH_LP")
    WINDOW:Talk(SymAct("KONOHANA"), -1610378774)
    WINDOW:CloseMessage()
  else
    WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("KONOHANA"), -1189568341)
    WINDOW:Talk(SymAct("KONOHANA"), 1048624228)
    WINDOW:Talk(SymAct("KONOHANA"), 664505637)
    WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
    CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH(chSymb0):SetManpu("MP_LAUGH_LP")
    WINDOW:Talk(SymAct("KONOHANA"), 550568962)
    WINDOW:CloseMessage()
  end
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
