dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -9985042, PARTNER_1 = -428043601})
  WINDOW:CloseMessage()
end
function MIRUHOGGU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -850280084)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -733286355)
  WINDOW:CloseMessage()
end
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), -1693751574)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HASUBURERO"), -2112858197)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function RATTA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -1455618968)
  WINDOW:CloseMessage()
end
function HIMEGUMA(chSymb0, chSymb1)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("HIMEGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIMEGUMA"), -1339673303)
  WINDOW:CloseMessage()
end
function RINGUMA(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("RINGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RINGUMA"), 935209446)
  WINDOW:DrawFace(20, 88, SymAct("RINGUMA"), FACE_TYPE.PAIN)
  CH(chSymb0):SetManpu("MP_UPSET_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("RINGUMA"), 782571687)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function HIMANATTSU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:Talk(SymAct("HIMANATTSU"), -1459515330)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function BUBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUBII"), -1340432001)
  WINDOW:CloseMessage()
end
function ABAGOORA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), -1690832196)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), -2110995459)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function TABUNNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TABUNNE"), -848472774)
  WINDOW:CloseMessage()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -730438533)
  subEveNodDouble(CH(chSymb0))
  WINDOW:Talk(SymAct("HIYAKKII"), -10799176)
  WINDOW:CloseMessage()
end
function KAKUREON(chSymb0)
end
function RUCHABURU(chSymb0)
end
function GARUURA(chSymb0)
end
