dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 426639007, PARTNER_1 = 7786462})
  WINDOW:CloseMessage()
end
function HIMANATTSU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("HIMANATTSU"), 727424029)
  WINDOW:Talk(SymAct("HIMANATTSU"), 843099484)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.SPECIAL01)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("HIMANATTSU"), 2097232795)
  subEveDoubleJump(CH(chSymb0))
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), 1679428314)
  WINDOW:CloseMessage()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH(chSymb0):SetManpu("MP_SHOCK_L")
  CH(chSymb0):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CH(chSymb0):ResetFacialMotion()
end
function RATTA(chSymb0, chSymb1)
  HIMANATTSU(chSymb0, chSymb1)
end
function TABUNNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TABUNNE"), 1329027353)
  WINDOW:Talk(SymAct("TABUNNE"), 1445750872)
  WINDOW:Talk(SymAct("TABUNNE"), -776702825)
  WINDOW:Talk(SymAct("TABUNNE"), -928037418)
  WINDOW:CloseMessage()
end
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), -1962994742)
  WINDOW:Talk(SymAct("HASUBURERO"), -1813765493)
  WINDOW:CloseMessage()
end
function SUBOMII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH(chSymb0):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:Talk(SymAct("SUBOMII"), -1194757816)
  WINDOW:Talk(SymAct("SUBOMII"), -1580056567)
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.THINK)
  CH(chSymb0):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("SUBOMII"), -292301106)
  WINDOW:Talk(SymAct("SUBOMII"), -142022769)
  WINDOW:Talk(SymAct("SUBOMII"), -593120180)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KORATTA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KORATTA"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("KORATTA"), -977369843)
  WINDOW:Talk(SymAct("KORATTA"), 1109825986)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NUMERA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("NUMERA"), 1530767491)
  subEveNoNoNo(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NUMERA"), -1739932636)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function UPAA(chSymb0)
  subEveNoNoNo(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("UPAA"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("UPAA"), -2125361819)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIPOPOTASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -1434657114)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -1285034009)
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -64587488)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BUBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUBII"), -448968607)
  WINDOW:Talk(SymAct("BUBII"), -837805150)
  WINDOW:CloseMessage()
end
function KONOHANA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), -687133981)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function ABAGOORA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ABAGOORA"), 1351824940)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), 1233651565)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 553048897)
  WINDOW:Talk(SymAct("KAMONEGI"), 971893248)
  WINDOW:CloseMessage()
end
