dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  subUsuComFuncTalkInBasePara2_01(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1834575093, PARTNER_1 = -1950504374})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
end
function AAKEN(chSymb0)
  subUsuComFuncTalkInBasePara2_01(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -1601111671)
  WINDOW:CloseMessage()
end
function SUKANPUU(chSymb0)
  CH(chSymb0):SetManpu("MP_QUESTION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SUKANPUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUKANPUU"), -1182021432)
  WINDOW:Talk(SymAct("SUKANPUU"), -154509809)
  WINDOW:DrawFace(20, 88, SymAct("SUKANPUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SUKANPUU"), -271487154)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), -990102387)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:Talk(SymAct("DOODOO"), -572060212)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NOZUPASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NOZUPASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOZUPASU"), 1518276867)
  WINDOW:Talk(SymAct("NOZUPASU"), 1130635330)
  WINDOW:Talk(SymAct("NOZUPASU"), -1576385848)
  WINDOW:Talk(SymAct("NOZUPASU"), -1156484215)
  WINDOW:CloseMessage()
end
function MIRUTANKU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MIRUTANKU"), -1875107766)
  WINDOW:CloseMessage()
end
function DOREDYIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOREDYIA"), -1993928437)
  WINDOW:CloseMessage()
end
function MASSUGUMA(chSymb0)
  CH(chSymb0):SetManpu("MP_QUESTION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), -966359092)
  WINDOW:CloseMessage()
  CH(chSymb0):DirTo(SymPos("GR_TW01_A_TO_C"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH("HERO"):DirTo(SymPos("GR_TW01_A_TO_C"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), -545409395)
  WINDOW:CloseMessage()
  CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH("HERO"):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), -196025010)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function WARUBIRU(chSymb0)
  CH(chSymb0):SetManpu("MP_SHOCK_R")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.SURPRISE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("WARUBIRU"), -313797617)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  CH(chSymb0):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:Talk(SymAct("WARUBIRU"), 1792264384)
  subEveCloseMsg()
  CH(chSymb0):DirTo(RotateOffs(135), Speed(350))
  CH(chSymb0):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("WARUBIRU"), 1942550913)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DENRYUU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1329599194)
  WINDOW:CloseMessage()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -1448813465)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), -2104914012)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -1684881691)
  WINDOW:Talk(SymAct("KUCHIITO"), -724359134)
  WINDOW:CloseMessage()
end
function PEROPPAFU(chSymb0)
  CH(chSymb0):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH(chSymb0):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("PEROPPAFU"), -842524317)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("PEROPPAFU"), -421180768)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("PEROPPAFU"), -99359)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("AAKEN"):SetManpu("MP_SWEAT_L")
  CH("AAKEN"):WaitManpu()
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
