dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -51080809, PARTNER_1 = -437280554})
  WINDOW:SwitchTalk({PARTNER_0 = -826084587, PARTNER_1 = -673594796})
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function YANCHAMU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), -1734847341)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  subEveJump(CH(chSymb0))
  WINDOW:Talk(SymAct("YANCHAMU"), -2122095150)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function CHOBOMAKI(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1431423471)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIBAKOIRU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -1279981744)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 875371423)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 758524638)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -1624571758)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -2043661869)
  WINDOW:CloseMessage()
end
function ROZERIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), -1390583280)
  WINDOW:CloseMessage()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -1274653871)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIYAKKII"), -79182442)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function ABAGOORA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("ABAGOORA"), -497224489)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("HASUBURERO"), -915298540)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KONOHANA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), -798321067)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), 1475512986)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SUBOMII(chSymb0, chSymb1, chSymb2)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SUBOMII"), 1323940827)
  subEveCloseMsg()
  CH(chSymb0):ResetManpu()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("KYATAPII"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KYATAPII"), -1918980228)
  subEveCloseMsg()
  CH(chSymb1):ResetManpu()
  CH(chSymb2):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  WINDOW:DrawFace(20, 88, SymAct("TOGEPII"), FACE_TYPE.HAPPY)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("TOGEPII"), -1803182531)
  WINDOW:CloseMessage()
  CH(chSymb2):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb2):ResetFacialMotion()
end
function KYATAPII(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function TOGEPII(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function REAKOIRU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  subEveJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("REAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("REAKOIRU"), -1079456258)
  WINDOW:CloseMessage()
end
function HIMANATTSU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIMANATTSU"), -1498153793)
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -369989000)
  WINDOW:CloseMessage()
end
function NUMERA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("NUMERA"), -253142215)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SHIKIJIKA_SPRING(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -607909638)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1025558085)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KOIRU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOIRU"), 1162290548)
  WINDOW:CloseMessage()
end
