dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  subUsuComFuncTalkInBasePara2_01(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 159449834, PARTNER_1 = 278541227})
  WINDOW:CloseMessage()
end
function GOOGOOTO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("GOOGOOTO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GOOGOOTO"), 1001873512)
  WINDOW:CloseMessage()
end
function MEEKURU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MEEKURU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MEEKURU"), 581718313)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SHIMAMA(chSymb0, chSymb1, chSymb2)
  CH(chSymb1):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb2):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("SHIMAMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIMAMA"), 1844299758)
  WINDOW:CloseMessage()
  CH(chSymb0):DirTo(CH(chSymb1), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb2):DirTo(CH(chSymb1), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("KORINKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KORINKU"), 1962342063)
  WINDOW:CloseMessage()
  CH(chSymb0):DirTo(CH(chSymb2), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):DirTo(CH(chSymb2), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  WINDOW:DrawFace(20, 88, SymAct("POCHIENA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("POCHIENA"), 1608230252)
  WINDOW:CloseMessage()
end
function POCHIENA(chSymb0, chSymb1, chSymb2)
  SHIMAMA(chSymb0, chSymb1, chSymb2)
end
function KORINKU(chSymb0, chSymb1, chSymb2)
  SHIMAMA(chSymb0, chSymb1, chSymb2)
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("DOODOO"), 1187025965)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function KOROBOOSHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KOROBOOSHI"), -1051162398)
  WINDOW:Talk(SymAct("KOROBOOSHI"), -666650205)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function YAMIKARASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1824272546)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  CH(chSymb0):SetManpu("MP_SWEAT_R")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  WINDOW:Talk(SymAct("YAMIKARASU"), 1973879267)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function BURUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BURUU"), 1586123296)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NAZONOKUSA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NAZONOKUSA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("NAZONOKUSA"), 1200710497)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function KOFUURAI_HANAZONO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KOFUURAI_HANAZONO"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("KOFUURAI_HANAZONO"), 147912102)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MASSUGUMA(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MASSUGUMA"), 298566887)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MASSUGUMA"), 988190500)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function MUKUBAADO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MUKUBAADO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MUKUBAADO"), 603825765)
  WINDOW:Talk(SymAct("MUKUBAADO"), -1536836950)
  WINDOW:CloseMessage()
end
function MUKKURU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MUKKURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MUKKURU"), -1115780117)
  WINDOW:CloseMessage()
end
function SUBAME(chSymb0)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("SUBAME"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SUBAME"), 2114559820)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function YAYAKOMA(chSymb0)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("YAYAKOMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("YAYAKOMA"), 1729277453)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function RAPURASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RAPURASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAPURASU"), 1279262158)
  WINDOW:DrawFace(20, 88, SymAct("RAPURASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("RAPURASU"), 1428475023)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DENRYUU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), 442849864)
  WINDOW:Talk(SymAct("DENRYUU"), 58616585)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), 676542666)
  WINDOW:Talk(SymAct("DEDENNE"), 826804619)
  WINDOW:CloseMessage()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("KUCHIITO"), -1227877052)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  CH(chSymb0):SetManpu("MP_UPSET_LP")
  WINDOW:Talk(SymAct("KUCHIITO"), -1345641467)
  subEveNo(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  WINDOW:SysMsg(-961152983)
  WINDOW:SysMsg(-542193304)
  WINDOW:SysMsg(-192701781)
  WINDOW:CloseMessage()
end
function PEROPPAFU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.GLADNESS)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:Talk(SymAct("PEROPPAFU"), -308761622)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:Talk(SymAct("PEROPPAFU"), -1562821331)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
  WINDOW:Talk(SymAct("PEROPPAFU"), -1144910740)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1863360593)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
