dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function NUMERA(chSymb0, chSymb1)
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("NUMERA"), -875948864)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
end
function SHIKIJIKA_SPRING(chSymb0, chSymb1)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -758045311)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function HIMEGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMEGUMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIMEGUMA"), -100895166)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function RINGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RINGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RINGUMA"), -521713917)
  WINDOW:CloseMessage()
end
function HIPOPOTASU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -1348021820)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function BUBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUBII"), -1229070203)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  WINDOW:Talk(SymAct("BUBII"), -1651461306)
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("BUBII"), -2071231993)
  WINDOW:Talk(SymAct("BUBII"), 51617480)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_02"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function ROZERIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), 436776841)
  WINDOW:Talk(SymAct("ROZERIA"), -150762608)
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -300369199)
  WINDOW:Talk(SymAct("NYASUPAA"), -986322670)
  WINDOW:CloseMessage()
end
function SUBOMII(chSymb0, chSymb1, chSymb2)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SUBOMII"), -600909741)
  subEveCloseMsg()
  CH(chSymb0):ResetManpu()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("UPAA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("UPAA"), -1821421932)
  subEveCloseMsg()
  CH(chSymb1):ResetManpu()
  CH(chSymb2):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb2))
  WINDOW:DrawFace(20, 88, SymAct("KORATTA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KORATTA"), -1972076587)
  WINDOW:CloseMessage()
  CH(chSymb2):ResetManpu()
  TASK:Sleep(TimeSec(0.25))
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):DirTo(CH("KORATTA"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):DirTo(CH("KORATTA"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_SHOCK_L")
  CH(chSymb1):SetManpu("MP_SHOCK_L")
  CH(chSymb1):WaitManpu()
  CH(chSymb1):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
end
function UPAA(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function KORATTA(chSymb0, chSymb1, chSymb2)
  SUBOMII(chSymb0, chSymb1, chSymb2)
end
function HASUBURERO(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH(chSymb0):SetManpu("MP_NOTICE_L")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HASUBURERO"), -1587991530)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), -1203626665)
  subEveCloseMsg()
  CH(chSymb0):DirTo(RotateTarget(130), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("HASUBURERO"), 1071251864)
  subEveCloseMsg()
  CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("HASUBURERO"), 650195161)
  WINDOW:CloseMessage()
end
function YANCHAMU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -441047938)
  WINDOW:CloseMessage()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  subEveJump(CH(chSymb0))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("YANCHAMU"), -55765697)
  subEveCloseMsg()
  CH(chSymb0):ResetManpu()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -679459076)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
end
function CHOBOMAKI(chSymb0, chSymb1)
  YANCHAMU(chSymb0, chSymb1)
end
function TABUNNE(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("TABUNNE"), -828672067)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -2116361862)
  WINDOW:CloseMessage()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -1732128709)
  WINDOW:CloseMessage()
end
function MIRUHOGGU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH(chSymb0):SetMotion(SymMot("EV005_CONFUSE"), LOOP.ON)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1276345352)
  WINDOW:CloseMessage()
  WINDOW:KeyWait()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1426607431)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  TASK:Sleep(TimeSec(0.3))
  CH(chSymb0):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH(chSymb0):SetMotion(SymMot("EV005_CONFUSE"), LOOP.ON)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("MIRUHOGGU"), 762293878)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):SetMotion(SymMot("WAIT02"), LOOP.ON)
end
