dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  subUsuComFuncTalkInBasePara2_01(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 517982420, PARTNER_1 = 130349461})
  WINDOW:CloseMessage()
end
function BURUU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURUU"), 753510998)
  WINDOW:CloseMessage()
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("YAMIKARASU"), 905091863)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetFacialMotion()
end
function YAMIKARASU(chSymb0, chSymb1)
  BURUU(chSymb0, chSymb1)
end
function MASSUGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), 2058554832)
  WINDOW:CloseMessage()
end
function KOROBOOSHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOROBOOSHI"), 1671969937)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KOROBOOSHI"), 1216704338)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NAZONOKUSA(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NAZONOKUSA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NAZONOKUSA"), 1369333267)
  WINDOW:Talk(SymAct("NAZONOKUSA"), -704232740)
  WINDOW:CloseMessage()
end
function SUKANPUU(chSymb0)
  CH("SUKANPUU"):SetManpu("MP_SHOCK_R")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("SUKANPUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SUKANPUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUKANPUU"), -820153443)
  WINDOW:Talk(SymAct("SUKANPUU"), 1455953711)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DOREDYIA(chSymb0)
  subUsuComFuncTalkInBasePara2_01(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOREDYIA"), 1339237998)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("DOREDYIA"), 1694397869)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("DOREDYIA"), 2112177388)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function PURASURU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("PURASURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PURASURU"), 849662507)
  WINDOW:CloseMessage()
end
function MAINAN(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("MAINAN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MAINAN"), 733995882)
  WINDOW:CloseMessage()
end
function KUREFFI(chSymb0)
end
function DESUKAAN(chSymb0)
end
function NYAASU(chSymb0)
end
function MAJINNOTUBO(chSymb0)
end
