dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1657547811)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), -2077695332)
  WINDOW:CloseMessage()
end
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.CATCHBREATH)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("HASUBURERO"), -1358581409)
  WINDOW:CloseMessage()
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("HASUBURERO"), -1239515106)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function RINGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RINGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RINGUMA"), -111208743)
  WINDOW:CloseMessage()
end
function HIMEGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIMEGUMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIMEGUMA"), -532404328)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BUBII(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  subEveJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("BUBII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BUBII"), -882281381)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function RATTA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -764263142)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.THINK)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH(chSymb0):SetManpu("MP_SWEAT_L")
  WINDOW:Talk(SymAct("RATTA"), 1441421781)
  WINDOW:CloseMessage()
end
function ROZERIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), 1290889364)
  WINDOW:Talk(SymAct("ROZERIA"), 225437286)
  WINDOW:CloseMessage()
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 343201575)
  WINDOW:Talk(SymAct("NYASUPAA"), 1062831332)
  WINDOW:CloseMessage()
end
function HIPOPOTASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 641906085)
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.ANGRY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("HIPOPOTASU"), 1761813346)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function YANCHAMU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1880625699)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function CHOBOMAKI(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1530216928)
  WINDOW:CloseMessage()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1110339745)
  WINDOW:CloseMessage()
end
function MIRUHOGGU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -977900434)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -592618193)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 534399368)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 113342665)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 770452234)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 888609355)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SHOUT)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 2075561100)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1655553485)
  WINDOW:CloseMessage()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1233186318)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), 1352392527)
  WINDOW:Talk(SymAct("HIYAKKII"), -687619200)
  WINDOW:CloseMessage()
end
function TABUNNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("TABUNNE"), -837225791)
  WINDOW:CloseMessage()
  subEveNo(CH("HERO"))
  TASK:Sleep(TimeSec(0.5))
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH(chSymb0):SetManpu("MP_SHOCK_L")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("TABUNNE"), -1486475539)
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("TABUNNE"), -1099096148)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
