dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -715909244, PARTNER_1 = -867227963})
  WINDOW:CloseMessage()
end
function RATTA(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -412977914)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("RATTA"), -25607097)
  WINDOW:CloseMessage()
  CH(chSymb1):DirTo(CH(chSymb0), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("KORATTA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KORATTA"), -1321676160)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("KORATTA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KORATTA"), -1474042943)
  WINDOW:CloseMessage()
end
function KORATTA(chSymb0, chSymb1)
  RATTA(chSymb0, chSymb1)
end
function HIMANATTSU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIMANATTSU"), -2096189438)
  WINDOW:CloseMessage()
end
function HIPOPOTASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -1709866685)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NYASUPAA(chSymb0)
  CH(chSymb0):SetManpu("MP_NOTICE_L")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("NYASUPAA"), 495820172)
  WINDOW:Talk(SymAct("NYASUPAA"), 76983501)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KYATAPII(chSymb0, chSymb1, chSymb2)
  WINDOW:DrawFace(20, 88, SymAct("KYATAPII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KYATAPII"), -98611531)
  subEveDoubleJump(CH(chSymb0))
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("TOGEPII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TOGEPII"), -486244364)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PUPURIN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PUPURIN"), -936825801)
  subEveDoubleJump(CH(chSymb2))
  WINDOW:CloseMessage()
end
function TOGEPII(chSymb0, chSymb1, chSymb2)
  KYATAPII(chSymb0, chSymb1, chSymb2)
end
function PUPURIN(chSymb0, chSymb1, chSymb2)
  KYATAPII(chSymb0, chSymb1, chSymb2)
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -785244810)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("HIYAKKII"), -1636594767)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
