dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
end
function CHOBOMAKI(chSymb0, chSymb1)
  CH(chSymb0):SetMotionRaito(Raito(1))
  CH(chSymb1):SetMotionRaito(Raito(1))
  CH(chSymb0):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb1):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb1):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1709662581)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), -2096910390)
  WINDOW:Talk(SymAct("NUMERA"), -1473315831)
  WINDOW:CloseMessage()
end
function SHIKIJIKA_SPRING(chSymb0, chSymb1)
  CH(chSymb0):SetMotionRaito(Raito(1))
  CH(chSymb1):SetMotionRaito(Raito(1))
  CH(chSymb0):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb1):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb1):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb1):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1321874104)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -25928817)
  WINDOW:Talk(SymAct("YANCHAMU"), -412128562)
  WINDOW:CloseMessage()
end
function YANCHAMU(chSymb0, chSymb1)
  SHIKIJIKA_SPRING(chSymb0, chSymb1)
end
function NUMERA(chSymb0, chSymb1)
  CHOBOMAKI(chSymb0, chSymb1)
end
function NYASUPAA(chSymb)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -868075251)
  WINDOW:CloseMessage()
end
function HIYAKKII(chSymb)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -715585460)
  WINDOW:CloseMessage()
end
function KAKUREON(chSymb)
  WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KAKUREON"), 1388385411)
end
function STONE_WARUBIARU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HERO"), 1272587714)
  WINDOW:CloseMessage()
end
