dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function HASUBURERO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), -671516596)
  WINDOW:CloseMessage()
end
function HIPOPOTASU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("HIPOPOTASU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HIPOPOTASU"), -824030963)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function RATTA(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("RATTA"), -439412018)
  WINDOW:Talk(SymAct("RATTA"), -53204081)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HIMEGUMA(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("HIMEGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIMEGUMA"), -1282032312)
  WINDOW:CloseMessage()
end
function RINGUMA(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("RINGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RINGUMA"), -1433498615)
  WINDOW:Talk(SymAct("RINGUMA"), -2119966774)
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
end
