dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -52719195, PARTNER_1 = -440360732})
  WINDOW:SwitchTalk({PARTNER_0 = -823266521, PARTNER_1 = -671694234})
  WINDOW:SwitchTalk({PARTNER_0 = -1732815711, PARTNER_1 = -2119408160})
  WINDOW:CloseMessage()
end
function YAMIKARASU(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("YAMIKARASU"), -1434372573)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BURUU(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:DrawFace(20, 88, SymAct("BURUU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BURUU"), -1281751198)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MASSUGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), 872553389)
  WINDOW:CloseMessage()
end
function KOROBOOSHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOROBOOSHI"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("KOROBOOSHI"), 756624108)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function NAZONOKUSA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NAZONOKUSA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NAZONOKUSA"), 1918588108)
  WINDOW:Talk(SymAct("NAZONOKUSA"), 1799382413)
  WINDOW:CloseMessage()
end
function DOREDYIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOREDYIA"), 1080899150)
  WINDOW:Talk(SymAct("DOREDYIA"), 1500907279)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("DOREDYIA"), 372740552)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SUBAME(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SUBAME"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBAME"), 254582921)
  WINDOW:CloseMessage()
end
function YAYAKOMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("YAYAKOMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YAYAKOMA"), 604107594)
  WINDOW:CloseMessage()
end
function CHIRAAMII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("CHIRAAMII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHIRAAMII"), 1025163787)
  WINDOW:CloseMessage()
end
function WARUBIRU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("WARUBIRU"), -1165828412)
  WINDOW:Talk(SymAct("WARUBIRU"), -1550192763)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function WARUBIARU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("WARUBIARU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("WARUBIARU"), 1626274594)
  WINDOW:Talk(SymAct("WARUBIARU"), 2046151267)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function OTACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("OTACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OTACHI"), 1389926816)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("OTACHI"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("OTACHI"), 1271113953)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BUIZERU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("BUIZERU"), 75644454)
  WINDOW:Talk(SymAct("BUIZERU"), 496570215)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("BUIZERU"), 917789860)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 800026085)
  WINDOW:Talk(SymAct("DENRYUU"), -1472761558)
  WINDOW:Talk(SymAct("DENRYUU"), -1322499989)
  WINDOW:CloseMessage()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -665674681)
  WINDOW:CloseMessage()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -1052136186)
  WINDOW:KeyWait()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), -362479931)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("JIRAACHI"), -209727612)
  WINDOW:Talk(SymAct("JIRAACHI"), -1136764605)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_NOTICE_L")
  CH(chSymb0):WaitManpu()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("JIRAACHI"), -1524275198)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function PEROPPAFU(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1912063039)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1760359808)
  WINDOW:CloseMessage()
end
