dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1546805264, PARTNER_1 = -1160335695})
  WINDOW:CloseMessage()
end
function HIYAKKII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -1845756558)
  WINDOW:DrawFace(20, 88, SymAct("HIYAKKII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("HIYAKKII"), -1998533581)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function TABUNNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TABUNNE"), FACE_TYPE.NORMAL)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  WINDOW:Talk(SymAct("TABUNNE"), -945726732)
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KAMONEGI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -558208075)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("KAMONEGI"), -174638986)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MIRUHOGGU(chSymb0, bFirst)
  if bFirst then
    WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MIRUHOGGU"), -326366921)
    WINDOW:Talk(SymAct("MIRUHOGGU"), 1796478456)
    WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
    WINDOW:Talk(SymAct("MIRUHOGGU"), 1913595065)
    WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.HAPPY)
    CH(chSymb0):SetManpu("MP_LAUGH_LP")
    WINDOW:Talk(SymAct("MIRUHOGGU"), 1378848716)
    WINDOW:Talk(SymAct("MIRUHOGGU"), 1261747853)
    CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    CH(chSymb0):WaitRotate()
    CH(chSymb0):ResetManpu()
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
    CH(chSymb0):SetManpu("MP_SHOCK_L")
    CH(chSymb0):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
    CH(chSymb0):WaitManpu()
    CH(chSymb0):WaitPlayMotion()
    TASK:Sleep(TimeSec(0.3))
    WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("MIRUHOGGU"), 1612311886)
    WINDOW:Talk(SymAct("MIRUHOGGU"), 2030230543)
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH(chSymb0):SetManpu("MP_FLY_SWEAT")
    CH(chSymb0):WaitManpu()
    TASK:Sleep(TimeSec(0.5))
    WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SPECIAL02)
    CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:Talk(SymAct("MIRUHOGGU"), 910379720)
    WINDOW:CloseMessage()
  else
    CH(chSymb0):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    CH(chSymb0):WaitRotate()
    WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SPECIAL02)
    CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:Talk(SymAct("MIRUHOGGU"), 794327945)
    WINDOW:CloseMessage()
  end
end
function SHIKIJIKA_SPRING(chSymb0, chSymb1)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH(chSymb1):SetManpu("MP_NOTICE_L")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 74786890)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("NUMERA"), 493754635)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetFacialMotion()
end
function NUMERA(chSymb0, chSymb1)
  SHIKIJIKA_SPRING(chSymb0, chSymb1)
end
function RATTA(chSymb0, chSymb1)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("KORATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KORATTA"), -1695152700)
  WINDOW:Talk(SymAct("KORATTA"), -2081606523)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  subEveCloseMsg()
  CH(chSymb0):DirTo(CH(chSymb1), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), 1083842594)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function KORATTA(chSymb0, chSymb1)
  RATTA(chSymb0, chSymb1)
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1501630819)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  subEveJumpSurprise(CH(chSymb0))
  CH(chSymb0):SetManpu("MP_EXCLAMATION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), 1923891872)
  WINDOW:CloseMessage()
  CH(chSymb0):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE01"), LOOP.ON)
  CH("DENRYUU"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), 1807184865)
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetManpu()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.25))
  TASK:Sleep(TimeSec(0.25))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("DENRYUU"), 620160294)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), 1038996583)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function YANCHAMU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("YANCHAMU"), 381716388)
  WINDOW:CloseMessage()
end
function CHOBOMAKI(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 266057445)
  WINDOW:CloseMessage()
end
function KYATAPII(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("KYATAPII"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("KYATAPII"), -2008831446)
  subEveCloseMsg()
  CH(chSymb1):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("UPAA"), FACE_TYPE.PAIN)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("UPAA"), -1856464021)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb1):SetMotion(SymMot("WAIT02"), LOOP.ON)
end
function UPAA(chSymb0, chSymb1)
  KYATAPII(chSymb0, chSymb1)
end
function NYASUPAA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -131709113)
  WINDOW:CloseMessage()
end
function HIMANATTSU(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("HIMANATTSU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HIMANATTSU"), -516065786)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
