dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 814378596, PARTNER_1 = 697392933})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 45878502, PARTNER_1 = 463945127})
  WINDOW:CloseMessage()
end
function WARUBIRU(chSymb0, chSymb1, chSymb2)
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIRU"), 1424403296)
  WINDOW:KeyWait()
  CH(chSymb2):SetManpu("MP_ANGRY_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.ANGRY)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("WARUBIRU"), 1308465697)
  WINDOW:KeyWait()
  CH(chSymb2):ResetManpu()
  CH(chSymb2):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.PAIN)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("WARUBIRU"), 1724959202)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("BUIZERU"), 2144073891)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -128719764)
  WINDOW:CloseMessage()
  CH(chSymb2):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb2):ResetFacialMotion()
end
function BUIZERU(chSymb0, chSymb1, chSymb2)
  WARUBIRU(chSymb0, chSymb1, chSymb2)
end
function AAKEN(chSymb0, chSymb1, chSymb2)
  WARUBIRU(chSymb0, chSymb1, chSymb2)
end
function MASSUGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), -515320531)
  WINDOW:Talk(SymAct("MASSUGUMA"), -1917284065)
  WINDOW:CloseMessage()
end
function DOREDYIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOREDYIA"), -1801215906)
  WINDOW:Talk(SymAct("DOREDYIA"), -1081150563)
  WINDOW:CloseMessage()
end
function KOFUURAI_HANAZONO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOFUURAI_HANAZONO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOFUURAI_HANAZONO"), -1500134692)
  WINDOW:Talk(SymAct("KOFUURAI_HANAZONO"), -371960805)
  WINDOW:CloseMessage()
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), -254843558)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), -605931879)
  WINDOW:CloseMessage()
end
function KOJOFUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), -1023866920)
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("KOJOFUU"), 1163991831)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function POCHIENA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("POCHIENA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("POCHIENA"), 1551510102)
  WINDOW:CloseMessage()
end
function SUBAME(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SUBAME"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBAME"), -1626521871)
  WINDOW:Talk(SymAct("SUBAME"), -2045374544)
  WINDOW:CloseMessage()
end
function KORINKU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KORINKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KORINKU"), -1388618637)
  WINDOW:CloseMessage()
end
function BANEBUU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("BANEBUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BANEBUU"), -1272943310)
  WINDOW:CloseMessage()
end
function NAZONOKUSA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NAZONOKUSA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NAZONOKUSA"), -77464587)
  WINDOW:Talk(SymAct("NAZONOKUSA"), -495269196)
  WINDOW:CloseMessage()
end
function RAPURASU(chSymb0, bFirst)
  if bFirst then
    WINDOW:DrawFace(20, 88, SymAct("RAPURASU"), FACE_TYPE.SAD)
    CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
    WINDOW:Talk(SymAct("RAPURASU"), -917005961)
    WINDOW:Talk(SymAct("RAPURASU"), -800282570)
  else
  end
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1473557753)
  WINDOW:Talk(SymAct("DENRYUU"), 1322223032)
  WINDOW:CloseMessage()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 665934228)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), 1051355349)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("KUCHIITO"), 361184022)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("KUCHIITO"), 211552855)
  CH(chSymb0):SetManpu("MP_UPSET_LP")
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.SAD)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("KUCHIITO"), 1138597008)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), 1522970065)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("JIRAACHI"), 1911291410)
  WINDOW:CloseMessage()
end
function PEROPPAFU(chSymb0)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1760612179)
  WINDOW:Talk(SymAct("PEROPPAFU"), -278342756)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
