dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function MYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MYUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MYUU"), -1095657523)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function WARUBIRU(chSymb0)
  local degree0 = CH(chSymb0):GetDir()
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIRU"), -1481988468)
  WINDOW:Talk(SymAct("WARUBIRU"), -1937246897)
  WINDOW:CloseMessage()
end
function DOREDYIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOREDYIA"), -1784888306)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("DOREDYIA"), -623029559)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function KOFUURAI_HANAZONO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KOFUURAI_MIYABI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOFUURAI_MIYABI"), -1010408568)
  WINDOW:Talk(SymAct("KOFUURAI_MIYABI"), -387239861)
  WINDOW:CloseMessage()
end
function OTACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("OTACHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("OTACHI"), -235929334)
  WINDOW:CloseMessage()
end
function PURASURU(chSymb0, chSymb1)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("PURASURU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("PURASURU"), 1986534853)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function MAINAN(chSymb0, chSymb1)
  CH(chSymb1):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("MAINAN"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MAINAN"), 1869819012)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
  CH(chSymb1):ResetFacialMotion()
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), 907825724)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SUBAME(chSymb0)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("SUBAME"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SUBAME"), 789013373)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function YAYAKOMA(chSymb0)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("YAYAKOMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("YAYAKOMA"), 69873854)
  WINDOW:Talk(SymAct("YAYAKOMA"), 489751039)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function MUKKURU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MUKKURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MUKKURU"), 1383110456)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("MUKKURU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MUKKURU"), 1265346169)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function MEEKURU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MEEKURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEEKURU"), 1615263162)
  WINDOW:Talk(SymAct("MEEKURU"), 2036188411)
  WINDOW:CloseMessage()
end
function GOMAZOU(chSymb0)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("GOMAZOU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("GOMAZOU"), -20588492)
  WINDOW:Talk(SymAct("GOMAZOU"), -404821643)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function BANEBUU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("BANEBUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BANEBUU"), 615120338)
  WINDOW:CloseMessage()
end
function TANEBOO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TANEBOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TANEBOO"), 1035127955)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("TANEBOO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("TANEBOO"), 379559760)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function MUKUBAADO(chSymb0, chSymb1, chSymb2)
  WINDOW:DrawFace(20, 88, SymAct("MUKUBAADO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MUKUBAADO"), 260353553)
  WINDOW:Talk(SymAct("MUKUBAADO"), 1086666966)
  subEveCloseMsg()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("GOOGOOTO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("GOOGOOTO"), 1507723671)
  WINDOW:Talk(SymAct("GOOGOOTO"), 1928550996)
  subEveCloseMsg()
  CH(chSymb1):ResetManpu()
  CH(chSymb1):ResetFacialMotion()
  CH(chSymb2):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("DONFAN"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DONFAN"), 1810393877)
  WINDOW:CloseMessage()
  CH(chSymb2):ResetManpu()
  CH(chSymb2):ResetFacialMotion()
end
function GOOGOOTO(chSymb0, chSymb1, chSymb2)
  MUKUBAADO(chSymb0, chSymb1, chSymb2)
end
function DONFAN(chSymb0, chSymb1, chSymb2)
  MUKUBAADO(chSymb0, chSymb1, chSymb2)
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), -328173606)
  WINDOW:Talk(SymAct("DENRYUU"), -177518949)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), -1676305737)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -2062636042)
  WINDOW:CloseMessage()
end
function PEROPPAFU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1373374411)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1221015180)
  WINDOW:CloseMessage()
end
