dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -618207051, PARTNER_1 = -1036133900})
  WINDOW:CloseMessage()
end
function MIRUTANKU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUTANKU"), -384792009)
  WINDOW:Talk(SymAct("MIRUTANKU"), -267666570)
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("MIRUTANKU"), -1085657679)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function MUKUBAADO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MUKUBAADO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MUKUBAADO"), -1504633616)
  WINDOW:CloseMessage()
end
function MUKKURU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MUKKURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MUKKURU"), -1921233101)
  WINDOW:CloseMessage()
end
function DOODOO(chSymb0)
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("DOODOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOODOO"), -1805156750)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:Talk(SymAct("DOODOO"), 335504061)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function DOREDYIA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DOREDYIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("DOREDYIA"), 182735868)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function PURASURU(chSymb0, chSymb1)
  CH(chSymb0):SetManpu("MP_EXCLAMATION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PURASURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PURASURU"), 289450232)
  WINDOW:CloseMessage()
end
function MAINAN(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("MAINAN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MAINAN"), 140220857)
  WINDOW:CloseMessage()
end
function YAYAKOMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("YAYAKOMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YAYAKOMA"), 594987642)
  WINDOW:CloseMessage()
end
function CHIRAAMII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("CHIRAAMII"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("CHIRAAMII"), 980286267)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function KORINKU(chSymb0)
  CH(chSymb0):SetManpu("MP_QUESTION")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KORINKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KORINKU"), 1965846012)
  WINDOW:Talk(SymAct("KORINKU"), 1815567549)
  WINDOW:Talk(SymAct("KORINKU"), 1192890238)
  WINDOW:CloseMessage()
end
function OTACHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("OTACHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("OTACHI"), 1577139775)
  WINDOW:CloseMessage()
end
function NOZUPASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("NOZUPASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOZUPASU"), -644275472)
  WINDOW:Talk(SymAct("NOZUPASU"), -1065217103)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("NOZUPASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("NOZUPASU"), 66389782)
  WINDOW:CloseMessage()
end
function DENRYUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 451819095)
  WINDOW:CloseMessage()
end
function DEDENNE(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 834889108)
  WINDOW:CloseMessage()
end
function POKEMON_ATLAS(chSymb0)
end
function POKEMON_ATLAS_D(chSymb0)
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), 685266133)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), 1738129938)
  WINDOW:CloseMessage()
end
function JIRAACHI(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH(chSymb0):SetManpu("MP_QUESTION")
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.THINK)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:Talk(SymAct("JIRAACHI"), 2122511187)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("JIRAACHI"), 1437573264)
  WINDOW:Talk(SymAct("JIRAACHI"), 1286902225)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("JIRAACHI"), -886272738)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function PEROPPAFU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:Talk(SymAct("PEROPPAFU"), -768099233)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1152819085)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.CATCHBREATH)
  CH(chSymb0):ResetManpu()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.CATCHBREATH)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1571663566)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
