dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1028417622, PARTNER_1 = -609704213})
  WINDOW:CloseMessage()
end
function BUIZERU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUIZERU"), -259656408)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.DECIDE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:Talk(SymAct("BUIZERU"), -375470999)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SUKANPUU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SUKANPUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUKANPUU"), -1495313746)
  WINDOW:DrawFace(20, 88, SymAct("SUKANPUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("SUKANPUU"), -1077648401)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function BANEBUU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("BANEBUU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("BANEBUU"), -1796657108)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("BANEBUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BANEBUU"), -1913519763)
  WINDOW:CloseMessage()
  WINDOW:DrawFace(20, 88, SymAct("BANEBUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BANEBUU"), 174726562)
  WINDOW:CloseMessage()
end
function TANEBOO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("TANEBOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TANEBOO"), 326184163)
  WINDOW:CloseMessage()
end
function PURASURU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("PURASURU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("PURASURU"), 480301918)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function MAINAN(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("MAINAN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MAINAN"), 96199199)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("MAINAN"), FACE_TYPE.HAPPY)
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb1):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("MAINAN"), 781627868)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
  CH(chSymb1):ResetFacialMotion()
end
function MEEKURU(chSymb0, chSymb1, chSymb2, chSymb3)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("MEEKURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEEKURU"), 932020381)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):DirTo(CH(chSymb1), Speed(500), ROT_TYPE.NEAR)
  CH(chSymb2):DirTo(CH(chSymb1), Speed(500), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb1))
  WINDOW:DrawFace(20, 88, SymAct("POCHIENA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("POCHIENA"), 2026640986)
  WINDOW:Talk(SymAct("POCHIENA"), 1641490203)
  CH(chSymb1):SetMotion(SymMot("ATTACK"), LOOP.OFF)
  CH(chSymb1):WaitPlayMotion()
  CH(chSymb1):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH(chSymb1):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH(chSymb2):SetManpu("MP_EXCLAMATION")
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("GOMAZOU"), FACE_TYPE.PAIN)
  CH(chSymb2):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("GOMAZOU"), 1257927896)
  subEveCloseMsg()
  CH(chSymb2):ResetFacialMotion()
  CH(chSymb2):ResetManpu()
  CH(chSymb3):SetManpu("MP_LAUGH_LP")
  CH(chSymb3):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:CloseMessage()
  CH(chSymb0):DirTo(CH(chSymb3), Speed(500), ROT_TYPE.NEAR)
  CH(chSymb1):DirTo(CH(chSymb3), Speed(500), ROT_TYPE.NEAR)
  CH(chSymb2):DirTo(CH(chSymb3), Speed(500), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  CH(chSymb1):WaitRotate()
  CH(chSymb2):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb3))
  WINDOW:DrawFace(20, 88, SymAct("SHIMAMA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SHIMAMA"), 1407272345)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH(chSymb2):SetManpu("MP_SHOCK_L")
  WINDOW:CloseMessage()
  CH(chSymb3):ResetManpu()
  CH(chSymb3):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.3))
  CH(chSymb2):ResetManpu()
end
function POCHIENA(chSymb0, chSymb1, chSymb2, chSymb3)
  MEEKURU(chSymb0, chSymb1, chSymb2, chSymb3)
end
function GOMAZOU(chSymb0, chSymb1, chSymb2, chSymb3)
  MEEKURU(chSymb0, chSymb1, chSymb2, chSymb3)
end
function SHIMAMA(chSymb0, chSymb1, chSymb2, chSymb3)
  MEEKURU(chSymb0, chSymb1, chSymb2, chSymb3)
end
function WARUBIARU(chSymb0)
  CH(chSymb0):SetManpu("MP_ANGRY_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("WARUBIARU"), FACE_TYPE.ANGRY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("WARUBIARU"), -730244778)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:Talk(SymAct("WARUBIARU"), -849188841)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:Talk(SymAct("WARUBIARU"), 236289200)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function WARUBIRU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIRU"), 386813425)
  WINDOW:KeyWait()
  CH(chSymb0):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:DrawFace(20, 88, SymAct("WARUBIRU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("WARUBIRU"), 1008934450)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetShake()
  CH(chSymb0):ResetFacialMotion()
end
function MASSUGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MASSUGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MASSUGUMA"), 624439155)
  WINDOW:Talk(SymAct("MASSUGUMA"), 1786362292)
  WINDOW:CloseMessage()
end
function AAKEN(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.CATCHBREATH)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.CATCHBREATH)
  WINDOW:Talk(SymAct("AAKEN"), 1935837429)
  WINDOW:Talk(SymAct("AAKEN"), 1481628470)
  WINDOW:Talk(SymAct("AAKEN"), 1096084087)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function HORUBII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HORUBII"), -959646024)
  WINDOW:KeyWait()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("HORUBII"), -539506695)
  WINDOW:KeyWait()
  CH(chSymb0):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HORUBII"), -1230431275)
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_SPREE_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HORUBII"), -1347278188)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function DENRYUU(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -2069923497)
  WINDOW:Talk(SymAct("DENRYUU"), -1652275178)
  WINDOW:Talk(SymAct("DENRYUU"), -758784303)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE01"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_SHOCK_L")
  TASK:Sleep(TimeSec(0.8))
  CH(chSymb0):WaitManpu()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DENRYUU"), -874582128)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.25))
end
function DEDENNE(chSymb0, chSymb1)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -520897453)
  WINDOW:Talk(SymAct("DEDENNE"), -102200046)
  WINDOW:Talk(SymAct("DEDENNE"), 2121306589)
  WINDOW:KeyWait()
  CH(chSymb1):SetManpu("MP_LAUGH_LP")
  CH(chSymb1):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), 1735106716)
  WINDOW:CloseMessage()
  CH(chSymb1):ResetManpu()
  CH(chSymb1):ResetFacialMotion()
end
function KUCHIITO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), 729686892)
  WINDOW:Talk(SymAct("KUCHIITO"), 845484589)
  WINDOW:KeyWait()
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KUCHIITO"), 424165870)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIRAACHI(chSymb0)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("JIRAACHI"), 5468335)
  WINDOW:Talk(SymAct("JIRAACHI"), 1326638696)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
  CH(chSymb0):ResetFacialMotion()
end
function PEROPPAFU(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.CATCHBREATH)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.CATCHBREATH)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1443485481)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.SURPRISE)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:Talk(SymAct("PEROPPAFU"), 2099545322)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  CH(chSymb0):WaitManpu()
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
