dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function ROZERIA(chSymb0)
  CH(chSymb0):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
  CH(chSymb0):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("ROZERIA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("ROZERIA"), -1242249665)
  WINDOW:Talk(SymAct("ROZERIA"), -1393559682)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SUBOMII(chSymb0)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("SUBOMII"), -2017286979)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  subEveDoubleJump(CH(chSymb0))
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.WEEP)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:Talk(SymAct("SUBOMII"), -1629907460)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
