dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function RAPURASU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RAPURASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAPURASU"), 1587507728)
  WINDOW:Talk(SymAct("RAPURASU"), 1199850321)
  WINDOW:KeyWait()
  WINDOW:DrawFace(20, 88, SymAct("RAPURASU"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("RAPURASU"), 1823019154)
  WINDOW:CloseMessage()
end
function PARTNER(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:SwitchTalk({PARTNER_0 = 1974608339, PARTNER_1 = 989050644})
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function AAKEN(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("AAKEN"), 602441301)
  WINDOW:Talk(SymAct("AAKEN"), 147182998)
  WINDOW:CloseMessage()
end
function GAMAGARU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("GAMAGARU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GAMAGARU"), 299820247)
  WINDOW:CloseMessage()
end
function ODOSHISHI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("ODOSHISHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ODOSHISHI"), -1773733864)
  WINDOW:CloseMessage()
end
function KINOGASSA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KINOGASSA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("KINOGASSA"), -1889679015)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function PARASEKUTO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("PARASEKUTO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PARASEKUTO"), -756408393)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("PARASEKUTO"), -873386250)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function GONYONYO(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("GONYONYO"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("GONYONYO"), -522420939)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("GONYONYO"), -104379276)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH(chSymb0))
  WINDOW:CloseMessage()
end
function GOKURIN(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("GOKURIN"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:Talk(SymAct("GOKURIN"), -1232676173)
  WINDOW:DrawFace(20, 88, SymAct("GOKURIN"), FACE_TYPE.NORMAL)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:Talk(SymAct("GOKURIN"), -1348604942)
  WINDOW:DrawFace(20, 88, SymAct("GOKURIN"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("GOKURIN"), -2068793295)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH(chSymb0):SetManpu("MP_FLY_SWEAT")
  WINDOW:CloseMessage()
  CH(chSymb0):WaitManpu()
  CH(chSymb0):ResetFacialMotion()
end
function CHORONEKO(chSymb0)
  CH(chSymb0):SetManpu("MP_NOTICE_L")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("CHORONEKO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("CHORONEKO"), -1649702544)
  CH(chSymb0):ResetFacialMotion()
  WINDOW:KeyWait()
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:Talk(SymAct("CHORONEKO"), 439588287)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetManpu()
end
function MOROBARERU(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("MOROBARERU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOROBARERU"), 52995326)
  WINDOW:CloseMessage()
end
function RAKURAI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("RAKURAI"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("RAKURAI"), -1067470759)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function SUKORUPI(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("SUKORUPI"), FACE_TYPE.PAIN)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:Talk(SymAct("SUKORUPI"), -649821928)
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
end
function JIGUZAGUMA(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("JIGUZAGUMA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIGUZAGUMA"), -227945765)
  WINDOW:DrawFace(20, 88, SymAct("JIGUZAGUMA"), FACE_TYPE.HAPPY)
  CH(chSymb0):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH(chSymb0):SetManpu("MP_LAUGH_LP")
  WINDOW:Talk(SymAct("JIGUZAGUMA"), -344792166)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  subEveJump(CH(chSymb0))
  WINDOW:CloseMessage()
  CH(chSymb0):ResetFacialMotion()
  CH(chSymb0):ResetManpu()
end
function KEESHII(chSymb0)
  WINDOW:DrawFace(20, 88, SymAct("KEESHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KEESHII"), -1540131491)
  WINDOW:Talk(SymAct("KEESHII"), -1121434596)
  WINDOW:CloseMessage()
end
