dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main21_chitenbosswin01_init()
end
function main21_chitenbosswin01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  MAP:SetVisibleMaterial("uzu", false)
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("KUCHIITO"):SetMotion(SymMot("EV015_BATTLE00"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  local taskEffAway01 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_OUT"), Volume(256))
    EFFECT:Create("effectSmokeupBlack01", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack01", SymPos("P_EFF_EV_SMOKEUP_BLACK_01"))
    EFFECT:Play("effectSmokeupBlack01")
    CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("SHADOW_OF_NIHIL"):SetVisible(false)
  end
  TASK:Regist(taskEffAway01)
  TASK:Sleep(TimeSec(0.2))
  local taskEffAway02 = function()
    EFFECT:Create("effectSmokeupBlack02", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack02", SymPos("P_EFF_EV_SMOKEUP_BLACK_02"))
    EFFECT:Play("effectSmokeupBlack02")
    CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  end
  TASK:Regist(taskEffAway02)
  local taskEffAway03 = function()
    EFFECT:Create("effectSmokeupBlack03", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack03", SymPos("P_EFF_EV_SMOKEUP_BLACK_03"))
    EFFECT:Play("effectSmokeupBlack03")
    CH("BANGIRASU_MEGA"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("BANGIRASU_MEGA"):SetVisible(false)
  end
  TASK:Regist(taskEffAway03)
  TASK:Sleep(TimeSec(0.2))
  local taskEffAway04 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_OUT"), Volume(256))
    EFFECT:Create("effectSmokeupBlack04", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack04", SymPos("P_EFF_EV_SMOKEUP_BLACK_04"))
    EFFECT:Play("effectSmokeupBlack04")
    CH("GENGAA_MEGA2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("GENGAA_MEGA2"):SetVisible(false)
  end
  TASK:Regist(taskEffAway04)
  TASK:Sleep(TimeSec(0.1))
  local taskEffAway05 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_OUT"), Volume(256))
    EFFECT:Create("effectSmokeupBlack05", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack05", SymPos("P_EFF_EV_SMOKEUP_BLACK_05"))
    EFFECT:Play("effectSmokeupBlack05")
    CH("GENGAA_MEGA"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(1))
    CH("GENGAA_MEGA"):SetVisible(false)
  end
  TASK:Regist(taskEffAway05)
  TASK:Sleep(TimeSec(1))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("PARTNER"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 800783033, PARTNER_1 = 916573176})
  WINDOW:SwitchTalk({PARTNER_0 = 495753275, PARTNER_1 = 77048186})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenbosswin01_end()
end
function main21_chitenbosswin02_init()
end
function main21_chitenbosswin02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  EFFECT:Create("effectLightlineStartLp", SymEff("EV_LIGHTLINE_START_LP"))
  EFFECT:SetPosition("effectLightlineStartLp", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineStartLp")
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_02"))
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_03_LP"))
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenbosswin02_end()
end
function main21_chitenbosswin03_init()
end
function main21_chitenbosswin03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:Create("effectLightDoorXlStartLp", SymEff("EV_LIGHTDOOR_XL_START_LP"))
  EFFECT:SetPosition("effectLightDoorXlStartLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
  EFFECT:Play("effectLightDoorXlStartLp")
  GM("EV21_DOOR"):SetVisible(false)
  CH("KUCHIITO"):SetMotion(SymMot("EV015_BATTLE00"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  GM("EV21_DOOR"):SetVisible(true)
  GM("EV21_DOOR"):SetMotion(SymMot("OPEN"), LOOP.OFF)
  SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_OPEN"), Volume(256))
  TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
  GM("EV21_DOOR"):SetMotion(SymMot("LOOP"), LOOP.ON)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 1272332221)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("RAIKOU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("RAIKOU"), 1389170428)
  WINDOW:CloseMessage()
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("KUCHIITO"):RunTo(SymPos("P00_KUCHIITO"), Speed(3))
  CH("ENTEI"):RunTo(SymPos("P00_ENTEI"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("RAIKOU"):RunTo(SymPos("P00_RAIKOU"), Speed(3))
  CH("SUIKUN"):RunTo(SymPos("P00_SUIKUN"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectLightDoorXlStartLp")
end
function main21_chitenbosswin03_end()
end
function main21_chitenbosswin04_init()
end
function main21_chitenbosswin04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:Create("effectLightlineLp", SymEff("EV_LIGHTLINE_LP"))
  EFFECT:SetPosition("effectLightlineLp", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineLp")
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_03"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:FadeOutSe(SymSnd("SE_EVT_TENNOHIKARI_02"), TimeSec(2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_TENNOHIKARI_03_LP"), TimeSec(2))
  EFFECT:Create("effectDropBlack01", SymEff("EV_DROP_BLACK"))
  EFFECT:SetPosition("effectDropBlack01", SymPos("P_EFF_EV_DROP_BLACK_01"))
  EFFECT:Play("effectDropBlack01")
  SOUND:PlaySe(SymSnd("SE_EVT_KK_AMEBA_APPEAR"), Volume(256))
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenbosswin04_end()
end
function main21_chitenbosswin05_init()
end
function main21_chitenbosswin05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SHADOW_OF_NIHIL6"):SetVisible(false)
  CH("SHADOW_OF_NIHIL"):SetVisible(false)
  CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  CH("SHADOW_OF_NIHIL4"):SetVisible(false)
  CH("SHADOW_OF_NIHIL5"):SetVisible(false)
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):SetMotionRaito(Raito(1.2))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):SetMotionRaito(Raito(0.9))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):SetMotionRaito(Raito(0.7))
  CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL6"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  EFFECT:Create("effectLightDoorXlKeepLp", SymEff("EV_LIGHTDOOR_XL_KEEP_LP"))
  EFFECT:SetPosition("effectLightDoorXlKeepLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
  EFFECT:Play("effectLightDoorXlKeepLp")
  GM("EV21_DOOR"):SetMotion(SymMot("LOOP"), LOOP.ON)
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0))
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SUIKUN"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  local taskEffBota01 = function()
    EFFECT:Create("effectDropFloorBlack01", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack01", SymPos("P_EFF_DROP_FLOOR_BLACK_01"))
    EFFECT:Play("effectDropFloorBlack01")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL"):SetVisible(true)
    CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota01)
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota02 = function()
    EFFECT:Create("effectDropFloorBlack02", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack02", SymPos("P_EFF_DROP_FLOOR_BLACK_02"))
    EFFECT:Play("effectDropFloorBlack02")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL2"):SetVisible(true)
    CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL2"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota02)
  local taskEffBota03 = function()
    EFFECT:Create("effectDropFloorBlack03", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack03", SymPos("P_EFF_DROP_FLOOR_BLACK_03"))
    EFFECT:Play("effectDropFloorBlack03")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL3"):SetVisible(true)
    CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL3"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota03)
  TASK:Sleep(TimeSec(0.1))
  local taskEffBota04 = function()
    EFFECT:Create("effectDropFloorBlack04", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack04", SymPos("P_EFF_DROP_FLOOR_BLACK_04"))
    EFFECT:Play("effectDropFloorBlack04")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL4"):SetVisible(true)
    CH("SHADOW_OF_NIHIL4"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL4"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota04)
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota05 = function()
    EFFECT:Create("effectDropFloorBlack05", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack05", SymPos("P_EFF_DROP_FLOOR_BLACK_05"))
    EFFECT:Play("effectDropFloorBlack05")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL5"):SetVisible(true)
    CH("SHADOW_OF_NIHIL5"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL5"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL5"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL5"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota05)
  TASK:Sleep(TimeSec(2.5))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  MAP:SetVisibleMaterial("uzu", false)
  CH("SUIKUN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("SUIKUN"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("RAIKOU"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2044747071, PARTNER_1 = 1627090046})
  WINDOW:CloseMessage()
  CH("SHADOW_OF_NIHIL5"):SetVisible(false)
  CH("ENTEI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("RAIKOU"):SetMotion(SymMot("EV020_BARK00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_ROAR"))
  EFFECT:Create("effectBodyElectric", SymEff("EV_BODY_ELECTRIC"))
  EFFECT:SetPosition("effectBodyElectric", SymPos("P_EFF_BODY_ELECTRIC"))
  EFFECT:Play("effectBodyElectric")
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_DENGEKI_01"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-412913487)
  CH("RAIKOU"):WaitPlayMotion()
  CH("RAIKOU"):SetMotion(SymMot("EV020_BARK01"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:ForceCloseMessage()
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CAMERA:SetRotateZ(Degree(0))
  CH("ENTEI"):SetVisible(true)
  CH("SHADOW_OF_NIHIL5"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_DENGEKI_02"))
  EFFECT:Create("effectLightningWarp01", SymEff("EV_LIGHTNING"))
  EFFECT:SetPosition("effectLightningWarp01", SymPos("P_EFF_LIGHTNING_WARP_01"))
  EFFECT:Play("effectLightningWarp01")
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  local taskEffAway01 = function()
    EFFECT:Create("effectSmokeupBlack01", SymEff("EV_SMOKEUP_BLACK"))
    EFFECT:SetPosition("effectSmokeupBlack01", SymPos("P_EFF_EV_SMOKEUP_BLACK_01"))
    EFFECT:Play("effectSmokeupBlack01")
    SOUND:PlaySe(SymSnd("SE_EVT_KK_OUT"), Volume(256))
    CH("SHADOW_OF_NIHIL5"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL5"):SetPosition(Vector(-68, 0, 78))
    TASK:Sleep(TimeSec(1))
    CH("SHADOW_OF_NIHIL5"):SetVisible(false)
  end
  TASK:Regist(taskEffAway01)
  TASK:Sleep(TimeSec(1))
  local taskEffBota06 = function()
    EFFECT:Create("effectDropFloorBlack06", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack06", SymPos("P_EFF_DROP_FLOOR_BLACK_06"))
    EFFECT:Play("effectDropFloorBlack06")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL6"):SetVisible(true)
    CH("SHADOW_OF_NIHIL6"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL6"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL6"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL6"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota06)
  TASK:Sleep(TimeSec(3))
  EFFECT:Remove("effectLightDoorXlKeepLp")
  MAP:SetVisibleMaterial("rock0", true)
  MAP:SetVisibleMaterial("rock1", true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  EFFECT:Create("effectLightDoorXlEnd", SymEff("EV_LIGHTDOOR_XL_END"))
  EFFECT:SetPosition("effectLightDoorXlEnd", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
  EFFECT:Play("effectLightDoorXlEnd")
  TASK:Sleep(TimeSec(0.9))
  local taskDoorBack00 = function()
    GM("EV21_DOOR"):SetMotion(SymMot("CLOSE"), LOOP.OFF)
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_CLOSE_01"), Volume(256))
    TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
    GM("EV21_DOOR"):SetVisible(false)
  end
  TASK:Regist(taskDoorBack00)
  TASK:Sleep(TimeSec(2))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -25673232, PARTNER_1 = 1313628704})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectLightDoorXlKeepLp")
end
function main21_chitenbosswin05_end()
end
function main21_chitenbosswin06_init()
end
function main21_chitenbosswin06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:Create("effectLightlineEnd", SymEff("EV_LIGHTLINE_END"))
  EFFECT:SetPosition("effectLightlineEnd", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineEnd")
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_CLOSE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenbosswin06_end()
end
function main21_chitenbosswin07_init()
end
function main21_chitenbosswin07_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("KUCHIITO"):SetMotion(SymMot("EV015_BATTLE00"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):SetMotionRaito(Raito(1.2))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):SetMotionRaito(Raito(0.9))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL6"):SetMotionRaito(Raito(0.7))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL8"):SetMotionRaito(Raito(0.7))
  CH("SHADOW_OF_NIHIL8"):SetVisible(false)
  CH("SHADOW_OF_NIHIL7"):SetVisible(false)
  CH("SHADOW_OF_NIHIL8"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL7"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("RAIKOU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("RAIKOU"), 1465340769)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SUIKUN"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SUIKUN"), 2088370338)
  WINDOW:CloseMessage()
  CH("SUIKUN"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 1700868579, PARTNER_1 = 706783012})
  WINDOW:CloseMessage()
  CH("SUIKUN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KUCHIITO"), 859543141)
  WINDOW:CloseMessage()
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskEffBota01 = function()
    EFFECT:Create("effectDropFloorBlack01", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack01", SymPos("P_EFF_DROP_FLOOR_BLACK_01"))
    EFFECT:Play("effectDropFloorBlack01")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL7"):SetVisible(true)
    CH("SHADOW_OF_NIHIL7"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL7"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL7"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL7"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota01)
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota02 = function()
    EFFECT:Create("effectDropFloorBlack02", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack02", SymPos("P_EFF_DROP_FLOOR_BLACK_02"))
    EFFECT:Play("effectDropFloorBlack02")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL8"):SetVisible(true)
    CH("SHADOW_OF_NIHIL8"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL8"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL8"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL8"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota02)
  TASK:Sleep(TimeSec(1.5))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("SHADOW_OF_NIHIL8"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("SHADOW_OF_NIHIL7"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("ENTEI"):DirTo(CH("SHADOW_OF_NIHIL8"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KUCHIITO"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
  CH("ENTEI"):WaitRotate()
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):WaitRotate()
  CH("KUCHIITO"):SetMotion(SymMot("EV015_BATTLE00"), LOOP.ON)
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 404145574, PARTNER_1 = 17691879})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05_6"))
  CAMERA:SetTgt(SymCam("CAMERA_05_6"))
  CAMERA:SetFovy(SymCam("CAMERA_05_6"))
  CAMERA:SetRotateZ(SymCam("CAMERA_05_6"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_7"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("RAIKOU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("RAIKOU"), -2036996056)
  WINDOW:CloseMessage()
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):DirTo(RotateTarget(170), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("SUIKUN"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SUIKUN"), -1618028183)
  WINDOW:CloseMessage()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.PAIN)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(1559875022)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), Volume(256))
  CH("SHADOW_OF_NIHIL"):SetManpu("EV_NIHIL_MOVE")
  CH("SHADOW_OF_NIHIL2"):SetManpu("EV_NIHIL_MOVE")
  CH("SHADOW_OF_NIHIL3"):SetManpu("EV_NIHIL_MOVE")
  CH("SHADOW_OF_NIHIL4"):SetManpu("EV_NIHIL_MOVE")
  CH("SHADOW_OF_NIHIL6"):SetManpu("EV_NIHIL_MOVE")
  CH("SHADOW_OF_NIHIL8"):SetManpu("EV_NIHIL_MOVE")
  CH("SHADOW_OF_NIHIL7"):SetManpu("EV_NIHIL_MOVE")
  CH("SHADOW_OF_NIHIL"):WalkTo(SymPos("P00_KAGE01"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("SHADOW_OF_NIHIL2"):WalkTo(SymPos("P00_KAGE02"), Speed(1.5))
  CH("SHADOW_OF_NIHIL3"):WalkTo(SymPos("P00_KAGE03"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("SHADOW_OF_NIHIL4"):WalkTo(SymPos("P00_KAGE04"), Speed(1.5))
  CH("SHADOW_OF_NIHIL6"):WalkTo(SymPos("P00_KAGE05"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("SHADOW_OF_NIHIL8"):WalkTo(SymPos("P00_KAGE06"), Speed(1.5))
  CH("SHADOW_OF_NIHIL7"):WalkTo(SymPos("P00_KAGE07"), Speed(1.5))
  CH("RAIKOU"):WalkTo(SymPos("P00_RAIKOU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1), LINK_DIR.OFF)
  CH("RAIKOU"):WaitMove()
  CH("RAIKOU"):DirTo(RotateTarget(170), Speed(350), ROT_TYPE.NEAR)
  CH("RAIKOU"):WaitRotate()
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("HERO"):WaitMove()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutSe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), TimeSec(0.5))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:SetRotateZ(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("RAIKOU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("RAIKOU"), 1172503695)
  WINDOW:CloseMessage()
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CH("KUCHIITO"):SetPosition(SymPos("P00_KUCHIITO"))
  CH("ENTEI"):SetPosition(SymPos("P00_ENTEI"))
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  CH("ENTEI"):SetNeckRot(RotateTarget(40), RotateTarget(-20), RotateTarget(0), TimeSec(0.15))
  CH("ENTEI"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ENTEI"), 1859104588)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):WaitManpu()
  CH("KUCHIITO"):SetNeckRot(RotateTarget(-40), RotateTarget(0), RotateTarget(0), TimeSec(0.15))
  CH("KUCHIITO"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ENTEI"), 2010422797)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CH("KUCHIITO"):SetVisible(false)
  CH("ENTEI"):SetVisible(false)
  CH("SUIKUN"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON, TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(949291210)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 562968971, PARTNER_1 = 178481736})
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(2))
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 330849033, PARTNER_1 = -1809823802})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(-1925482873)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("KUCHIITO"):SetVisible(true)
  CH("ENTEI"):SetVisible(true)
  CH("SUIKUN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -465196373, PARTNER_1 = -44131350})
  WINDOW:SwitchTalk({PARTNER_0 = -697055191, PARTNER_1 = -815203992})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):WaitManpu()
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KUCHIITO"), -2144768081)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), -1724752146)
  subEveCloseMsg()
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), -1306587859)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("SUIKUN"):SetVisible(false)
  SOUND:FadeOutBgm(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_09_5"))
  CAMERA:SetTgt(SymCam("CAMERA_09_5"))
  CAMERA:SetFovy(SymCam("CAMERA_09_5"))
  CH("KUCHIITO"):ResetNeckRot(TimeSec(0.2))
  CH("KUCHIITO"):WaitNeckRot()
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), -1425785748)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CH("SUIKUN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  CAMERA:MoveFollow2(SymCam("CAMERA_11_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KIBOUNOTOBIRA_INTRO"), Volume(256))
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("KUCHIITO"):DirTo(SymPos("P01_KUCHIITO"), Speed(200), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  CH("KUCHIITO"):SetEyeMotion(EYE_MOTION.CLOSE)
  CH("KUCHIITO"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("ENTEI"):SetNeckRot(RotateTarget(-40), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  CH("ENTEI"):WaitNeckRot()
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ENTEI"), 748429475)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  CAMERA:SetRotateZ(SymCam("CAMERA_12"))
  CAMERA:MoveFollow2(SymCam("CAMERA_12_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("SUIKUN"):SetNeckRot(RotateTarget(40), RotateTarget(0), RotateTarget(0), TimeSec(0.15))
  CH("SUIKUN"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 898044386)
  WINDOW:CloseMessage()
  CH("SUIKUN"):ResetNeckRot(TimeSec(0.15))
  CH("SUIKUN"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 2039648786)
  WINDOW:CloseMessage()
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CAMERA:SetFovy(SymCam("CAMERA_13"))
  CAMERA:MoveFollow2(SymCam("CAMERA_13_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("RAIKOU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("RAIKOU"), 1619632979)
  WINDOW:CloseMessage()
  CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  CH("ENTEI"):SetVisible(false)
  CH("SUIKUN"):SetVisible(false)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  CAMERA:SetFovy(SymCam("CAMERA_14"))
  CH("KUCHIITO"):WalkTo(SymPos("P01_KUCHIITO"), Speed(1))
  CH("KUCHIITO"):WaitMove()
  CH("KUCHIITO"):ResetFacialMotion()
  CH("KUCHIITO"):ResetNeckRot(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("PARTNER"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.PAIN)
  CH("HERO"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1269100688, PARTNER_1 = 1388298705})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_15"))
  CAMERA:SetTgt(SymCam("CAMERA_15"))
  CAMERA:SetFovy(SymCam("CAMERA_15"))
  CAMERA:MoveFollow2(SymCam("CAMERA_15_5"), Speed(0.05, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), 503207702)
  WINDOW:KeyWait()
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KUCHIITO"), 82142807)
  CH("HERO"):ResetFacialMotion()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:CloseMessage()
  CH("KUCHIITO"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_16"))
  CAMERA:SetTgt(SymCam("CAMERA_16"))
  CAMERA:SetFovy(SymCam("CAMERA_16"))
  CAMERA:MoveFollow2(SymCam("CAMERA_16_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("KUCHIITO"):SetMotion(SymMot("THROW"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), false)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
  CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("PARTNER"):MoveTo(SymPos("P02_PARTNER"), Speed(2.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), false)
  CH("HERO"):WaitMove()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("KUCHIITO"):WaitPlayMotion()
  CH("KUCHIITO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 801650068, PARTNER_1 = 919798997})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenbosswin07_end()
end
function main21_chitenbosswin09_init()
end
function main21_chitenbosswin09_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  SOUND:FadeOutBgm(TimeSec(3))
  CUT:Load(SymCut("m21_090_09"))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  MAP:SetVisibleMaterial("uzu", false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main21_chitenbosswin09_cut_script_08()
end
function main21_chitenbosswin09_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("ENTEI"), -1320478694)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main21_chitenbosswin09_cut_talk_02()
  SOUND:PlaySe(SymSnd("SE_EVT_SANSEIJUU"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_SANSEIJUU_ATTACK_02"), Volume(256))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SysMsg(-1471141541)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main21_chitenbosswin09_cut_talk_03()
  local taskKageKieru05 = function()
    TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_SPLASH"), Volume(128))
  end
  TASK:Regist(taskKageKieru05)
  local taskKageKieru06 = function()
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_SPLASH"), Volume(128))
  end
  TASK:Regist(taskKageKieru06)
  local taskKageKieru01 = function()
    TASK:Sleep(TimeSec(75, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_SPLASH"), Volume(128))
  end
  TASK:Regist(taskKageKieru01)
  CH("HERO"):SetShadow(false)
  CH("PARTNER"):SetShadow(false)
  CH("KUCHIITO"):SetShadow(false)
  local taskIkkeeSe = function()
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KUCHIITO_ATTACK"), Volume(128))
  end
  TASK:Regist(taskIkkeeSe)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("KUCHIITO"), -1053887113)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main21_chitenbosswin09_cut_talk_04()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = -667565002, PARTNER_1 = -216492043})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main21_chitenbosswin09_cut_script_01()
  local taskKageKieru07 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_SPLASH"), Volume(256))
  end
  TASK:Regist(taskKageKieru07)
  local taskKageKieru03 = function()
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_SPLASH"), Volume(256))
  end
  TASK:Regist(taskKageKieru03)
  local taskKageKieru02 = function()
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_SPLASH"), Volume(256))
  end
  TASK:Regist(taskKageKieru02)
  local taskKageKieru06 = function()
    TASK:Sleep(TimeSec(40, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_SPLASH"), Volume(256))
  end
  TASK:Regist(taskKageKieru06)
end
function main21_chitenbosswin09_cut_script_02()
end
function main21_chitenbosswin09_cut_script_03()
end
function main21_chitenbosswin09_cut_script_04()
end
function main21_chitenbosswin09_cut_script_05()
end
function main21_chitenbosswin09_cut_script_06()
end
function main21_chitenbosswin09_cut_script_07()
end
function main21_chitenbosswin09_end()
end
function main21_chitenbosswin10_init()
end
function main21_chitenbosswin10_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KIBOUNOTOBIRA"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  EFFECT:Create("effectLightlineStartLp", SymEff("EV_LIGHTLINE_START_LP"))
  EFFECT:SetPosition("effectLightlineStartLp", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineStartLp")
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_02"), Volume(32))
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_03_LP"), Volume(32))
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenbosswin10_end()
end
function main21_chitenbosswin11_init()
end
function main21_chitenbosswin11_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KIBOUNOTOBIRA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  MAP:SetVisibleMaterial("uzu", false)
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):SetMotionRaito(Raito(1.2))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):SetMotionRaito(Raito(0.9))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL6"):SetMotionRaito(Raito(0.7))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):SetMotionRaito(Raito(0.7))
  EFFECT:Create("effectLightDoorXlStartLp", SymEff("EV_LIGHTDOOR_XL_START_LP"))
  EFFECT:SetPosition("effectLightDoorXlStartLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
  EFFECT:Play("effectLightDoorXlStartLp")
  GM("EV21_DOOR"):SetVisible(false)
  GM("EV21_DOOR_5"):SetVisible(false)
  GM("EV21_DOOR_4"):SetVisible(false)
  GM("EV21_DOOR_3"):SetVisible(false)
  CH("SHADOW_OF_NIHIL"):SetVisible(false)
  CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  CH("SHADOW_OF_NIHIL4"):SetVisible(false)
  CH("SHADOW_OF_NIHIL5"):SetVisible(false)
  CH("SHADOW_OF_NIHIL6"):SetVisible(false)
  CH("SHADOW_OF_NIHIL7"):SetVisible(false)
  CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL6"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL7"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  local taskHero00 = function()
    CH("HERO"):SetMotion(SymMot("EV013_AVOID03"), LOOP.OFF)
    CH("HERO"):MoveTo(SymPos("P00_HERO"), Speed(1.5), LINK_DIR.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    CH("HERO"):SetMotion(SymMot("EV013_AVOID04"), LOOP.ON)
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.2))
  local taskPartner00 = function()
    CH("PARTNER"):SetMotion(SymMot("EV013_AVOID03"), LOOP.OFF)
    CH("PARTNER"):MoveTo(SymPos("P00_PARTNER"), Speed(1.5), LINK_DIR.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    CH("PARTNER"):SetMotion(SymMot("EV013_AVOID04"), LOOP.ON)
  end
  TASK:Regist(taskPartner00)
  SOUND:FadeOutSe(SymSnd("SE_EVT_TENNOHIKARI_02"), TimeSec(1.5))
  SOUND:FadeOutSe(SymSnd("SE_EVT_TENNOHIKARI_03_LP"), TimeSec(1.5))
  local taskDoorOpen00 = function()
    GM("EV21_DOOR"):SetVisible(true)
    GM("EV21_DOOR"):SetMotion(SymMot("OPEN"), LOOP.OFF)
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_OPEN"), Volume(256))
    TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
    GM("EV21_DOOR"):SetMotion(SymMot("LOOP"), LOOP.ON)
  end
  TASK:Regist(taskDoorOpen00)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:WaitTask()
  local taskHero01 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(128))
    CH("HERO"):SetManpu("MP_NOTICE_R")
    CH("HERO"):WaitManpu()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetMotion(SymMot("EV015_WAKEUP00"), LOOP.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):ResetFacialMotion()
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.OFF)
    CH("HERO"):DirTo(RotateTarget(-160), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(190))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskHero01)
  TASK:Sleep(TimeSec(0.1))
  local taskPartner01 = function()
    CH("PARTNER"):SetManpu("MP_NOTICE_L")
    CH("PARTNER"):WaitManpu()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):SetMotion(SymMot("EV015_WAKEUP00"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):ResetFacialMotion()
    CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.OFF)
    CH("PARTNER"):DirTo(RotateTarget(160), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):WaitManpu()
  end
  TASK:Regist(taskPartner01)
  TASK:WaitTask()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -368859468, PARTNER_1 = -1522388877})
  WINDOW:CloseMessage()
  CH("KUCHIITO"):SetVisible(false)
  CH("ENTEI"):SetVisible(false)
  CH("SUIKUN"):SetVisible(false)
  CH("RAIKOU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota01 = function()
    EFFECT:Create("effectDropFloorBlack01", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack01", SymPos("P_EFF_DROP_FLOOR_BLACK_01"))
    EFFECT:Play("effectDropFloorBlack01")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(190))
    CH("SHADOW_OF_NIHIL"):SetVisible(true)
    CH("SHADOW_OF_NIHIL"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota01)
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota02 = function()
    EFFECT:Create("effectDropFloorBlack02", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack02", SymPos("P_EFF_DROP_FLOOR_BLACK_02"))
    EFFECT:Play("effectDropFloorBlack02")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL2"):SetVisible(true)
    CH("SHADOW_OF_NIHIL2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL2"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota02)
  TASK:Sleep(TimeSec(0.1))
  local taskEffBota03 = function()
    EFFECT:Create("effectDropFloorBlack03", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack03", SymPos("P_EFF_DROP_FLOOR_BLACK_03"))
    EFFECT:Play("effectDropFloorBlack03")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(190))
    CH("SHADOW_OF_NIHIL3"):SetVisible(true)
    CH("SHADOW_OF_NIHIL3"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL3"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota03)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(128))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("KUCHIITO"):SetMotion(SymMot("EV015_BATTLE00"), LOOP.ON)
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.7))
  CH("KUCHIITO"):SetVisible(true)
  CH("ENTEI"):SetVisible(true)
  CH("SUIKUN"):SetVisible(true)
  CH("RAIKOU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetRotateZ(SymCam("CAMERA_03"))
  local taskEffBota06 = function()
    EFFECT:Create("effectDropFloorBlack06", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack06", SymPos("P_EFF_DROP_FLOOR_BLACK_06"))
    EFFECT:Play("effectDropFloorBlack06")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL6"):SetVisible(true)
    CH("SHADOW_OF_NIHIL6"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL6"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL6"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL6"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota06)
  TASK:Sleep(TimeSec(0.2))
  local taskEffBota07 = function()
    EFFECT:Create("effectDropFloorBlack07", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack07", SymPos("P_EFF_DROP_FLOOR_BLACK_07"))
    EFFECT:Play("effectDropFloorBlack07")
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_BICHA"))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL7"):SetVisible(true)
    CH("SHADOW_OF_NIHIL7"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL7"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL7"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL7"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota07)
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), -1135017678)
  WINDOW:Talk(SymAct("KUCHIITO"), -1753984271)
  WINDOW:CloseMessage()
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:MoveFollow2(SymCam("CAMERA_04_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(190))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1905302608, PARTNER_1 = 167214975})
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CH("PARTNER"):ResetFacialMotion()
  CH("SHADOW_OF_NIHIL4"):SetVisible(true)
  CH("SHADOW_OF_NIHIL5"):SetVisible(true)
  MAP:SetVisibleMaterial("rock0", true)
  MAP:SetVisibleMaterial("rock1", true)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  local taskDoorBack05 = function()
    EFFECT:ChangeColor("effectLightDoorXlStartLp", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectLightDoorLLp", SymEff("EV_LIGHTDOOR_L_LP"))
    EFFECT:SetPosition("effectLightDoorLLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
    EFFECT:Play("effectLightDoorLLp")
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_CLOSE_02"), Volume(190))
    GM("EV21_DOOR"):SetVisible(false)
    GM("EV21_DOOR_5"):SetVisible(true)
    GM("EV21_DOOR_5"):SetMotion(SymMot("SMALL"), LOOP.OFF)
    GM("EV21_DOOR_5"):SetNextMotion(SymMot("LOOP"), LOOP.ON, TimeSec(0, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(45, TIME_TYPE.FRAME))
    GM("EV21_DOOR"):SetVisible(false)
    EFFECT:Remove("effectLightDoorXlStartLp")
  end
  TASK:Regist(taskDoorBack05)
  TASK:Sleep(TimeSec(2))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:SetRotateZ(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(0.7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("SUIKUN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("SUIKUN"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(20, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 283921982)
  WINDOW:Talk(SymAct("SUIKUN"), -744793447)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:SetRotateZ(SymCam("CAMERA_07"))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(0.7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(128))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -897553448, PARTNER_1 = -508741605})
  WINDOW:CloseMessage()
  MAP:SetVisibleMaterial("rock0", true)
  MAP:SetVisibleMaterial("rock1", true)
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  local taskDoorBack04 = function()
    EFFECT:ChangeColor("effectLightDoorLLp", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectLightDoorMLp", SymEff("EV_LIGHTDOOR_M_LP"))
    EFFECT:SetPosition("effectLightDoorMLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
    EFFECT:Play("effectLightDoorMLp")
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_CLOSE_02"), Volume(190))
    GM("EV21_DOOR_5"):SetVisible(false)
    GM("EV21_DOOR_4"):SetVisible(true)
    GM("EV21_DOOR_4"):SetMotion(SymMot("SMALL"), LOOP.OFF)
    GM("EV21_DOOR_4"):SetNextMotion(SymMot("LOOP"), LOOP.ON, TimeSec(0, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(45, TIME_TYPE.FRAME))
    GM("EV21_DOOR_5"):SetVisible(false)
    EFFECT:Remove("effectLightDoorLLp")
  end
  TASK:Regist(taskDoorBack04)
  TASK:Sleep(TimeSec(2))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:SetRotateZ(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("ENTEI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("ENTEI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:Talk(SymAct("ENTEI"), -122287782)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  CAMERA:SetRotateZ(SymCam("CAMERA_09"))
  CAMERA:MoveFollow2(SymCam("CAMERA_09_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), -1208508515)
  WINDOW:Talk(SymAct("ENTEI"), -1360220452)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  CAMERA:SetRotateZ(SymCam("CAMERA_10"))
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), -2050884321)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(128))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -1663382434, PARTNER_1 = 457363601})
  WINDOW:CloseMessage()
  MAP:SetVisibleMaterial("rock0", true)
  MAP:SetVisibleMaterial("rock1", true)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  local taskDoorBack03 = function()
    EFFECT:ChangeColor("effectLightDoorMLp", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectLightDoorSLp", SymEff("EV_LIGHTDOOR_S_LP"))
    EFFECT:SetPosition("effectLightDoorSLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
    EFFECT:Play("effectLightDoorSLp")
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_CLOSE_02"), Volume(190))
    GM("EV21_DOOR_4"):SetVisible(false)
    GM("EV21_DOOR_3"):SetVisible(true)
    GM("EV21_DOOR_3"):SetMotion(SymMot("SMALL"), LOOP.OFF)
    GM("EV21_DOOR_3"):SetNextMotion(SymMot("LOOP"), LOOP.ON, TimeSec(0, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(45, TIME_TYPE.FRAME))
    GM("EV21_DOOR_4"):SetVisible(false)
    EFFECT:Remove("effectLightDoorMLp")
  end
  TASK:Regist(taskDoorBack03)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectLightDoorSLp")
end
function main21_chitenbosswin11_end()
end
function main21_chitenbosswin12_init()
end
function main21_chitenbosswin12_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KIBOUNOTOBIRA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:Create("effectLightlineSLp", SymEff("EV_LIGHTLINE_S_LP"))
  EFFECT:SetPosition("effectLightlineSLp", SymPos("P_EFF_EV_LIGHTLINE_START_LP"))
  EFFECT:Play("effectLightlineSLp")
  SOUND:PlaySe(SymSnd("SE_EVT_TENNOHIKARI_CLOSE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectLightlineSLp")
end
function main21_chitenbosswin12_end()
end
function main21_chitenbosswin13_init()
end
function main21_chitenbosswin13_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KIBOUNOTOBIRA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  MAP:SetVisibleMaterial("rock0", false)
  MAP:SetVisibleMaterial("rock1", false)
  MAP:SetVisibleMaterial("uzu", false)
  GM("EV21_DOOR_2"):SetVisible(false)
  GM("EV21_DOOR_3"):SetMotion(SymMot("LOOP"), LOOP.ON)
  EFFECT:Create("effectLightDoorSLp", SymEff("EV_LIGHTDOOR_S_LP"))
  EFFECT:SetPosition("effectLightDoorSLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
  EFFECT:Play("effectLightDoorSLp")
  CH("SHADOW_OF_NIHIL"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL2"):SetMotionRaito(Raito(0.8))
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL3"):SetMotionRaito(Raito(1.2))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):SetMotionRaito(Raito(0.9))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL6"):SetMotionRaito(Raito(0.7))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL5"):SetMotionRaito(Raito(0.7))
  CH("SHADOW_OF_NIHIL8"):SetVisible(false)
  CH("SHADOW_OF_NIHIL4"):SetVisible(false)
  CH("SHADOW_OF_NIHIL8"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("SHADOW_OF_NIHIL4"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  local taskDoorBack03 = function()
    EFFECT:ChangeColor("effectLightDoorSLp", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectLightDoorXSLp", SymEff("EV_LIGHTDOOR_XS_LP"))
    EFFECT:SetPosition("effectLightDoorXSLp", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
    EFFECT:Play("effectLightDoorXSLp")
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_CLOSE_05"), Volume(190))
    GM("EV21_DOOR_3"):SetVisible(false)
    GM("EV21_DOOR_2"):SetVisible(true)
    GM("EV21_DOOR_2"):SetMotion(SymMot("SMALL"), LOOP.OFF)
    TASK:Sleep(TimeSec(45, TIME_TYPE.FRAME))
    EFFECT:Remove("effectLightDoorSLp")
    GM("EV21_DOOR_2"):SetVisible(false)
  end
  TASK:Regist(taskDoorBack03)
  CH("HERO"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(2))
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetRotateZ(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("RAIKOU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("RAIKOU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 88, SymAct("RAIKOU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("RAIKOU"), 39444944)
  WINDOW:Talk(SymAct("RAIKOU"), 1797733884)
  WINDOW:CloseMessage()
  CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:SetRotateZ(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1916538045, PARTNER_1 = 1494310782})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 1074425407, PARTNER_1 = 256637176})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", SymPos("P_EFF_BG_CONCENTRATION_LP"))
  EFFECT:Play("effectBgConLp")
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = 374393273, PARTNER_1 = 1031641722})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CH("SHADOW_OF_NIHIL3"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 610708283, PARTNER_1 = -1543587852})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetRotateZ(SymCam("CAMERA_05"))
  local taskHero00 = function()
    CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
    CH("HERO"):WaitMove()
    CH("HERO"):SetMotion(SymMot("JUMP"), LOOP.ON)
    CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(3))
    CH("HERO"):WaitMove()
    EFFECT:Create("effectLightDoorIn", SymEff("EV_LIGHTDOOR_IN"))
    EFFECT:SetPosition("effectLightDoorIn", SymPos("P_EFF_EV_LIGHTDOOR_IN"))
    EFFECT:Play("effectLightDoorIn")
    SOUND:PlaySe(SymSnd("SE_EVT_WARP"), Volume(256))
    CH("HERO"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
    CH("HERO"):SetVisible(false)
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.3))
  local taskPartner00 = function()
    CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):SetMotion(SymMot("JUMP"), LOOP.ON)
    CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(3))
    CH("PARTNER"):WaitMove()
    EFFECT:Create("effectLightDoorIn02", SymEff("EV_LIGHTDOOR_IN"))
    EFFECT:SetPosition("effectLightDoorIn02", SymPos("P_EFF_EV_LIGHTDOOR_IN"))
    EFFECT:Play("effectLightDoorIn02")
    SOUND:PlaySe(SymSnd("SE_EVT_WARP"), Volume(256))
    CH("PARTNER"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
    CH("PARTNER"):SetVisible(false)
  end
  TASK:Regist(taskPartner00)
  TASK:WaitTask()
  TASK:Sleep(TimeSec(1.5))
  local taskDoorBack02 = function()
    EFFECT:ChangeColor("effectLightDoorXSLp", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectLightDoorsEnd", SymEff("EV_LIGHTDOOR_END"))
    EFFECT:SetPosition("effectLightDoorsEnd", SymPos("P_EFF_EV_LIGHTDOOR_L_LP"))
    EFFECT:Play("effectLightDoorsEnd")
    SOUND:PlaySe(SymSnd("SE_EVT_KIBOUNOTOBIRA_CLOSE_06"), Volume(128))
    TASK:Sleep(TimeSec(3))
    EFFECT:Remove("effectLightDoorXSLp")
  end
  TASK:Regist(taskDoorBack02)
  TASK:Sleep(TimeSec(3))
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  WINDOW:DrawFaceF(324, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), -1159362891)
  WINDOW:Talk(SymAct("KUCHIITO"), 860106154)
  WINDOW:CloseMessage()
  MAP:SetVisibleMaterial("rock0", true)
  MAP:SetVisibleMaterial("rock1", true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(35, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskEffBota04 = function()
    EFFECT:Create("effectDropFloorBlack04", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack04", SymPos("P_EFF_DROP_FLOOR_BLACK_04"))
    EFFECT:Play("effectDropFloorBlack04")
    TASK:Sleep(TimeSec(0.3))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL4"):SetVisible(true)
    CH("SHADOW_OF_NIHIL4"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL4"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota04)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), 710876395)
  local taskEffBota08 = function()
    EFFECT:Create("effectDropFloorBlack08", SymEff("EV_DROP_FLOOR_BLACK"))
    EFFECT:SetPosition("effectDropFloorBlack08", SymPos("P_EFF_DROP_FLOOR_BLACK_08"))
    EFFECT:Play("effectDropFloorBlack08")
    TASK:Sleep(TimeSec(0.3))
    TASK:Sleep(TimeSec(0.3))
    CH("SHADOW_OF_NIHIL8"):SetVisible(true)
    CH("SHADOW_OF_NIHIL8"):ChangeColor(Color(1, 1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL8"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL8"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL8"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskEffBota08)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main21_chitenbosswin13_end()
end
function main21_chitenbosswin14_init()
end
function main21_chitenbosswin14_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KIBOUNOTOBIRA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(6))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:Create("effectLuminousWarpallLp", SymEff("EV_LUMINOUS_WARPALL_LP"))
  EFFECT:SetPosition("effectLuminousWarpallLp", SymPos("P_EFF_EV_LUMINOUS_WARPALL_LP"))
  EFFECT:Play("effectLuminousWarpallLp")
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_WARP_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = 24268584, PARTNER_1 = 409566825})
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutBgm(TimeSec(3.5))
  SCREEN_A:WhiteOutAll(TimeSec(0.5), true)
  WINDOW:ForceCloseMessage()
  EFFECT:Remove("effectLuminousWarpallLp")
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0), true)
  SCREEN_A:WhiteInAll(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main21_chitenbosswin14_end()
end
function groundEnd()
end
