dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main06_fuanwokakaetegakkouhe01_init()
end
function main06_fuanwokakaetegakkouhe01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_04"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -794929207, PARTNER_1 = -914004344})
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -492292789, PARTNER_1 = -72154102})
  WINDOW:SwitchTalk({PARTNER_0 = -1259171123, PARTNER_1 = -1377197172})
  CH("KAKUREON"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -2033913777, PARTNER_1 = -1612726002})
  WINDOW:SwitchTalk({PARTNER_0 = 407363009, PARTNER_1 = 22867072})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -921420889, PARTNER_1 = -804320538})
  WINDOW:SwitchTalk({PARTNER_0 = -81635035, PARTNER_1 = -499554204})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1384579421, PARTNER_1 = -1268527134})
  WINDOW:CloseMessage()
  CH("KAKUREON"):DirTo(RotateTarget(-25), Speed(200), ROT_TYPE.NEAR)
  CH("KAKUREON"):WaitRotate()
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  subEveNod(CH("KAKUREON"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1622238175, PARTNER_1 = -2041205408})
  WINDOW:SwitchTalk({PARTNER_0 = 30257583, PARTNER_1 = 416710894})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetNeckRot(TimeSec(0.3))
  CH("PARTNER"):WaitNeckRot()
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.2))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.2))
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main06_fuanwokakaetegakkouhe01_end()
end
function main06_fuanwokakaetegakkouhe02_init()
end
function main06_fuanwokakaetegakkouhe02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NUMERA"), -610167735)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1027955448)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -375916853)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -259209334)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1077063347)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1495900148)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_00"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("MIRUHOGGU"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1912917041)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1797258610)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 326639169)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 174272256)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1662907180)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 2047263341)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1361809838)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1211146479)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("MIRUHOGGU"):ResetManpu()
end
function main06_fuanwokakaetegakkouhe02_end()
end
function main06_fuanwokakaetegakkouhe03_init()
end
function main06_fuanwokakaetegakkouhe03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.PAIN)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(72, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:DrawFaceOffset(50, 0)
  WINDOW:Monologue(124859944)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 510265193, PARTNER_1 = 893867178})
  WINDOW:SwitchTalk({PARTNER_0 = 744252907, PARTNER_1 = -1413187292})
  WINDOW:SwitchTalk({PARTNER_0 = -1293989787, PARTNER_1 = -20264043})
  subEveCloseMsg()
  WINDOW:DrawFaceF(72, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:DrawFaceOffset(50, 0)
  WINDOW:Monologue(-405669164)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -855856873, PARTNER_1 = -706242474})
  WINDOW:SwitchTalk({PARTNER_0 = -1700393327, PARTNER_1 = -2084749360})
  subEveCloseMsg()
  WINDOW:DrawFace(72, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:DrawFaceOffset(40, 0)
  WINDOW:Monologue(-1466930157)
  WINDOW:CloseMessage()
  WINDOW:SysMsg(-1316266670)
  WINDOW:SelectStart()
  WINDOW:SelectChain(907231645, 1)
  WINDOW:SelectChain(789082332, 0)
  WINDOW:DefaultCursor(1)
  local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
  if id == 1 then
    WINDOW:CloseMessage()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
    WINDOW:SwitchTalk({PARTNER_0 = 1182182640, PARTNER_1 = 1601019313})
    WINDOW:SwitchTalk({PARTNER_0 = 1950404210, PARTNER_1 = 1834745651})
    WINDOW:SwitchTalk({PARTNER_0 = 572156404, PARTNER_1 = 989943989})
    WINDOW:SwitchTalk({PARTNER_0 = 271321974, PARTNER_1 = 154614327})
    WINDOW:SwitchTalk({PARTNER_0 = -1901123848, PARTNER_1 = -1749805127})
    WINDOW:SwitchTalk({PARTNER_0 = 1422066462, PARTNER_1 = 1306014303})
    WINDOW:CloseMessage()
    SOUND:FadeOutBgm(TimeSec(1))
    TASK:Regist(subEveMoveDir2, {
      CH("HERO"),
      SymPos("P00_HERO"),
      Speed(1.5),
      SymPos("P00_HERO")
    })
    TASK:Sleep(TimeSec(0.5))
    TASK:Regist(subEveMoveDir2, {
      CH("PARTNER"),
      SymPos("P00_PARTNER"),
      Speed(1.5),
      SymPos("P00_PARTNER")
    })
    SOUND:PlaySe(SymSnd("SE_EVT_NYASUPAA_ALERT"), Volume(190))
    WINDOW:SysMsg(1727357340)
    CH("HERO"):ResetFacialMotion()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
    CH("HERO"):SetManpu("MP_NOTICE_L")
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):WaitManpu()
    TASK:WaitTask()
    subEveCloseMsg()
    WINDOW:SysMsg(2146324701)
    CH("PARTNER"):WaitManpu()
    subEveCloseMsg()
    WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
    WINDOW:SwitchTalk({PARTNER_0 = 816825882, PARTNER_1 = 699725659})
    subEveCloseMsg()
    WINDOW:DrawFaceF(72, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
    WINDOW:Monologue(43623576)
    subEveCloseMsg()
    WINDOW:SysMsg(461542873)
    WINDOW:SysMsg(-1675982570)
    WINDOW:CloseMessage()
  else
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
    CH("PARTNER"):SetManpu("MP_SHOCK_L")
    CH("PARTNER"):WaitManpu()
    WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
    WINDOW:SwitchTalk({PARTNER_0 = -2063484841, PARTNER_1 = -327195525})
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
    CH("PARTNER"):WaitManpu()
    WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
    WINDOW:SwitchTalk({PARTNER_0 = -177973958, PARTNER_1 = -565639431})
    WINDOW:SwitchTalk({PARTNER_0 = -950913096, PARTNER_1 = -2011979393})
    WINDOW:KeyWait()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
    WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
    WINDOW:SwitchTalk({PARTNER_0 = -1861709762, PARTNER_1 = -1171930115})
    subEveCloseMsg()
    SOUND:FadeOutBgm(TimeSec(0.5))
    SOUND:PlaySe(SymSnd("SE_EVT_NYASUPAA_ALERT"), Volume(190))
    WINDOW:SysMsg(-1556155716)
    CH("HERO"):ResetFacialMotion()
    CH("PARTNER"):ResetFacialMotion()
    CH("HERO"):SetManpu("MP_NOTICE_R")
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):WaitManpu()
    subEveCloseMsg()
    WINDOW:SysMsg(614919795)
    subEveCloseMsg()
    WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
    WINDOW:SwitchTalk({PARTNER_0 = 1035853618, PARTNER_1 = -1273203667})
    subEveCloseMsg()
    WINDOW:DrawFace(72, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
    WINDOW:Monologue(-1392032404)
    subEveCloseMsg()
    WINDOW:SysMsg(-2044062033)
    WINDOW:SysMsg(-1624168466)
    WINDOW:CloseMessage()
  end
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main06_fuanwokakaetegakkouhe03_end()
end
function main06_fuanwokakaetegakkouhe04_init()
end
function main06_fuanwokakaetegakkouhe04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SysMsg(-797920983)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  subEveCloseMsg()
  CH("MIRUHOGGU"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_QUESTION")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -915701656)
  subEveCloseMsg()
  WINDOW:SysMsg(-498674773)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -77733142)
  subEveCloseMsg()
  WINDOW:SysMsg(2093350437)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1709100900)
  WINDOW:KeyWait()
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT")
  subEveLookAround(CH("MIRUHOGGU"), Speed(1000))
  WINDOW:Talk(SymAct("MIRUHOGGU"), 211817288)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 364585481)
  CH("MIRUHOGGU"):WaitManpu()
  subEveCloseMsg()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_03"), Volume(256))
  WINDOW:SysMsg(1050046922)
  WINDOW:SysMsg(663568523)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):WaitManpu()
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("MIRUHOGGU"):SetMotion(SymMot("EV005_SHY"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1758254668)
  subEveCloseMsg()
  WINDOW:SysMsg(1909974797)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  TASK:Regist(subEveJumpSurprise, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1526379726)
  subEveCloseMsg()
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("MIRUHOGGU"):SetMotion(SymMot("EV005_SHY"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1138853263)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main06_fuanwokakaetegakkouhe04_end()
end
function main06_fuanwokakaetegakkouhe05_init()
end
function main06_fuanwokakaetegakkouhe05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MIRUHOGGU"):SetMotion(SymMot("EV005_SHY"), LOOP.ON, TimeSec(0))
  CH("HIYAKKII"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):SetManpu("MP_SWEAT_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  WINDOW:SwitchTalk({PARTNER_0 = -998663872, PARTNER_1 = -580737023})
  subEveCloseMsg()
  WINDOW:SysMsg(-825086446)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -674685101, PARTNER_1 = -52147056})
  subEveCloseMsg()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:SysMsg(-436240943)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):RunTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(4))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):RunTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(4))
  TASK:Sleep(TimeSec(1.5))
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:SysMsg(-1430328554)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
  CH("MIRUHOGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("MIRUHOGGU"):WaitManpu()
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetPosition(SymPos("P02_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("HERO"):SetDir(RotateTarget(-100))
  CH("PARTNER"):SetDir(RotateTarget(-125))
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1280976297)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1735882348)
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir2, {
    CH("MIRUHOGGU"),
    SymPos("P00_MIRUHOGGU"),
    Speed(2),
    SymPos("P00_MIRUHOGGU")
  })
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("MIRUHOGGU"):SetPosition(SymPos("P01_MIRUHOGGU"))
  TASK:Regist(subEveMoveDir, {
    CH("MIRUHOGGU"),
    SymPos("P02_MIRUHOGGU"),
    Speed(2),
    CH("PARTNER")
  })
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:WaitTask()
  CH("MIRUHOGGU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  CH("MIRUHOGGU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("MIRUHOGGU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -2121025323)
  WINDOW:KeyWait()
  CH("MIRUHOGGU"):ResetManpu()
  WINDOW:Talk(SymAct("MIRUHOGGU"), 101426202)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):ResetFacialMotion()
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 521180507)
  CAMERA:WaitMove()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_01"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1986939255)
  TASK:WaitTask()
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1869969462)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("MIRUHOGGU"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1146629109)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1564678836)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:Talk(SymAct("MIRUHOGGU"), 302156915)
  WINDOW:CloseMessage()
  CH("MIRUHOGGU"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("MIRUHOGGU"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 186236210)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 540339953, PARTNER_1 = 959438768})
  subEveCloseMsg()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.1))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.1))
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1095253121)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -1481838018, PARTNER_1 = 1692133017})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("MIRUHOGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 2109790168)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1458406427)
  subEveCloseMsg()
  SOUND:FadeOutBgm(TimeSec(1))
  CH("HIYAKKII"):SetVisible(true)
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("MIRUHOGGU"):ResetManpu()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("MIRUHOGGU"):SetManpu("MP_EXCLAMATION")
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):ResetFacialMotion()
    CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
    CH("PARTNER"):SetManpu("MP_NOTICE_L")
    CH("NUMERA"):SetManpu("MP_NOTICE_L")
    CH("HERO"):ResetFacialMotion()
    CH("HERO"):ResetNeckRot(TimeSec(0.1))
  end
  TASK:Regist(taskLookAt01)
  WINDOW:Talk(SymAct("HIYAKKII"), 1341568346)
  WINDOW:Talk(SymAct("HIYAKKII"), 12002205)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("MIRUHOGGU"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(CH("HIYAKKII"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct("MIRUHOGGU"), 430707420)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir, {
    CH("HIYAKKII"),
    SymPos("P00_HIYAKKII"),
    Speed(1.5),
    CH("PARTNER")
  })
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.6))
    CH("HERO"):DirTo(SymPos("P00_HIYAKKII"), Speed(60), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(SymPos("P00_HIYAKKII"), Speed(60), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):DirTo(SymPos("P00_HIYAKKII"), Speed(60), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(SymPos("P00_HIYAKKII"), Speed(60), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("NUMERA"):DirTo(SymPos("P00_HIYAKKII"), Speed(60), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P00_HIYAKKII"), Speed(60), ROT_TYPE.NEAR)
    CH("YANCHAMU"):DirTo(SymPos("P00_HIYAKKII"), Speed(60), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  TASK:WaitTask()
  WINDOW:DrawFace(72, 16, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), 847331615)
  WINDOW:Talk(SymAct("HIYAKKII"), 731541598)
  WINDOW:Talk(SymAct("HIYAKKII"), -1409127279)
  WINDOW:Talk(SymAct("HIYAKKII"), -1256628784)
  WINDOW:Talk(SymAct("HIYAKKII"), -597196292)
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -981684035, PARTNER_1 = -296623234})
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAKKII"), -146091457)
  WINDOW:CloseMessage()
  CH("HIYAKKII"):DirTo(CH("MIRUHOGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("HIYAKKII"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("HIYAKKII"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-15, 0)
  WINDOW:Talk(SymAct("HIYAKKII"), -1207221000)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHILDREN_01"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:MoveFollow2(SymCam("CAMERA_08"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
  CH("NUMERA"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  CH("MIRUHOGGU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  CH("HIYAKKII"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymWord(2093398760), -1592756807)
  CAMERA:WaitMove()
  subEveCloseMsg()
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1975703942, PARTNER_1 = -1826220229})
  WINDOW:CloseMessage()
  CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(272, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 347999220)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NYASUPAA"), 228932277)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NUMERA"), 1102100805)
  WINDOW:Talk(SymAct("NUMERA"), 1487636484)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.EMOTION)
  WINDOW:Monologue(1938217927)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_09"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1788734086)
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(0.5))
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):ResetManpu()
  CH("NYASUPAA"):ResetManpu()
  CH("HERO"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 635206721)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):SetManpu("MP_NOTICE_R")
  CH("NUMERA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.SAD)
  WINDOW:DrawFaceOffset(8, -8)
  WINDOW:Talk(SymAct("YANCHAMU"), 1019694336)
  WINDOW:Talk(SymAct("YANCHAMU"), 401219267)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 250687362)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.SAD)
  WINDOW:DrawFaceOffset(8, -8)
  WINDOW:Talk(SymAct("YANCHAMU"), -1989594291)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:MoveFollow2(SymCam("CAMERA_11"), Speed(12, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
  CH("NUMERA"):SetManpu("MP_SPREE_LP")
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.5))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1871576564, PARTNER_1 = -116597216})
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(0.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_12"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P03_PARTNER"),
    Speed(2),
    CH("YANCHAMU")
  })
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):ResetManpu()
  CH("NYASUPAA"):ResetManpu()
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), -535302303)
  subEveCloseMsg()
  CH("YANCHAMU"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-35, 0)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -885343070)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), -769552925)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1654645980, PARTNER_1 = -2072303003})
  WINDOW:SwitchTalk({PARTNER_0 = -1353287258, PARTNER_1 = -1236449049})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), 836064296)
  WINDOW:CloseMessage()
  local taskYanchobo00 = function()
    CH("YANCHAMU"):ResetManpu()
    function TaskL.Loop()
      CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
      TASK:Sleep(TimeSec(0.5))
      CH("YANCHAMU"):SetManpu("MP_ANGRY_LP")
      TASK:Regist(subEveDoubleJump, {
        CH("YANCHAMU")
      })
      TASK:Sleep(TimeSec(1.5))
      TASK:Regist(subEveDoubleJump, {
        CH("YANCHAMU")
      })
      TASK:Sleep(TimeSec(1))
      CH("YANCHAMU"):ResetManpu()
      CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
      TASK:Sleep(TimeSec(1.5))
    end
    function TaskL.Finish()
      return
    end
  end
  local taskHeroPa00 = function()
    function TaskL.Loop()
      CH("PARTNER"):SetManpu("MP_LAUGH_LP")
      TASK:Regist(subEveDoubleJump, {
        CH("PARTNER")
      })
      TASK:Sleep(TimeSec(0.2))
      CH("HERO"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(1.5))
      CH("PARTNER"):ResetManpu()
      TASK:Regist(subEveDoubleJump, {
        CH("PARTNER")
      })
      TASK:Sleep(TimeSec(1))
      CH("HERO"):ResetManpu()
      TASK:Sleep(TimeSec(1.5))
    end
    function TaskL.Finish()
      return
    end
  end
  local taskNume00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NUMERA"):SetManpu("MP_SPREE_LP")
      CH("NUMERA"):SetMotion(SymMot("WALK"), LOOP.ON)
      TASK:Regist(subEveDoubleJump, {
        CH("NUMERA")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Regist(subEveDoubleJump, {
        CH("NUMERA")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NUMERA"):ResetManpu()
    end
    function TaskL.Finish()
      CH("NUMERA"):ResetManpu()
      CH("NUMERA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      return
    end
  end
  local taskShikiNya00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SHIKIJIKA_SPRING"):SetManpu("MP_SPREE_LP")
      TASK:Regist(subEveDoubleJump, {
        CH("SHIKIJIKA_SPRING")
      })
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("NYASUPAA"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SHIKIJIKA_SPRING"):ResetManpu()
    end
    function TaskL.Finish()
      CH("NYASUPAA"):ResetManpu()
      CH("SHIKIJIKA_SPRING"):ResetManpu()
      return
    end
  end
  SOUND:PlaySe(SymSnd("SE_EVT_WAIWAI_LP"), Volume(256))
  TASK:Regist(Group("taskHeroPa00"), taskHeroPa00)
  TASK:Regist(Group("grpYanchobo"), taskYanchobo00)
  TASK:Regist(Group("grpNume"), taskNume00)
  TASK:Regist(Group("grpShikiNya"), taskShikiNya00)
  TASK:Sleep(TimeSec(2))
  CAMERA:MoveFollow2(SymCam("CAMERA_13"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(72, 16, SymAct("HIYAKKII"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HIYAKKII"), 684615017)
  WINDOW:Talk(SymAct("HIYAKKII"), -340168242)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MIRUHOGGU"):SetManpu("MP_FLY_SWEAT")
  CH("MIRUHOGGU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("MIRUHOGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -224247665)
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_WAIWAI_LP"), TimeSec(1.5))
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):ResetManpu()
  CH("PARTNER"):ResetManpu()
  CH("NUMERA"):ResetManpu()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  CH("NYASUPAA"):ResetManpu()
  CH("CHOBOMAKI"):ResetManpu()
  CH("YANCHAMU"):ResetManpu()
end
function main06_fuanwokakaetegakkouhe05_end()
end
function main06_fuanwokakaetegakkouhe06_init()
end
function main06_fuanwokakaetegakkouhe06_start()
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -644934836)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:SysMsg(-1064033779)
  SOUND:WaitSe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(1.5))
  local taskNumeShiki01 = function()
    CH("NUMERA"):SetMotion(SymMot("PULL"), LOOP.ON)
    CH("NUMERA"):SetMotionRaito(Raito(2))
    TASK:Sleep(TimeSec(0.5))
    CH("NUMERA"):SetMotion(SymMot("PULL"), LOOP.ON)
    CH("NUMERA"):SetMotionRaito(Raito(2))
    TASK:Sleep(TimeSec(0.5))
    CH("NUMERA"):SetMotionRaito(Raito(1))
    CH("NUMERA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveNod(CH("SHIKIJIKA_SPRING"))
    CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(1.5))
    TASK:Sleep(TimeSec(0.2))
    CH("NUMERA"):WalkTo(SymPos("P00_NUMERA"), Speed(1.5))
  end
  TASK:Regist(Group("grpNumeShiki01"), taskNumeShiki01)
  local taskYanChobo01 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.1))
      CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(1))
      CH("CHOBOMAKI"):ResetManpu()
      TASK:Sleep(TimeSec(0.2))
      CH("YANCHAMU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
      TASK:Sleep(TimeSec(2))
      CH("YANCHAMU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.5))
    end
  end
  TASK:Regist(Group("grpYanChobo01"), taskYanChobo01)
  local taskHero01 = function()
    CH("HERO"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.ON)
    TASK:Sleep(TimeSec(0.7))
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.RIGHT)
    CH("HERO"):WaitRotate()
    CH("HERO"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.ON)
    TASK:Sleep(TimeSec(0.5))
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(-125), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  TASK:Regist(taskHero01)
  local taskPartner01 = function()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("NUMERA"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("CHOBOMAKI"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  TASK:Regist(Group("grpPartner01"), taskPartner01)
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask(Group("grpPartner01"))
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1881819958, PARTNER_1 = -1764850293})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1109141944, PARTNER_1 = -1527191799})
  WINDOW:SwitchTalk({PARTNER_0 = 593558470, PARTNER_1 = 981191303})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  CAMERA:MoveToHero(Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
end
function main06_fuanwokakaetegakkouhe06_end()
end
function groundEnd()
end
