dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main15_enteishujinkoushinkaboss1st01_init()
end
function main15_enteishujinkoushinkaboss1st01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CH("HERO"):SetVisibleScarf(true)
  CH("PARTNER"):SetVisibleScarf(true)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("BUIZERU"):SetMotion(SymMot("EV020_DOWN00"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetMotion(SymMot("EV021_DEPRESS01"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("EV021_DEPRESS01"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  local taskEntei00 = function()
    CH("ENTEI"):SetMotion(SymMot("EV015_BARK00"), LOOP.OFF)
    CH("ENTEI"):WaitPlayMotion()
    CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  end
  TASK:Regist(taskEntei00)
  TASK:Sleep(TimeSec(0.7))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_IMPACT"))
  local taskScreenEffect00 = function()
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
    TASK:Sleep(TimeSec(0.1))
    SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
    TASK:Sleep(TimeSec(0.2))
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  end
  TASK:Regist(taskScreenEffect00)
  local taskHero00 = function()
    CH("HERO"):SetManpu("MP_SHOCK_L")
    CH("HERO"):SetMotion(SymMot("EV013_AVOID00"), LOOP.OFF)
    CH("HERO"):MoveTo(SymPos("P10_HERO"), Speed(3), LINK_DIR.OFF)
    CH("HERO"):WaitMove()
    CH("HERO"):SetMotion(SymMot("EV013_AVOID03"), LOOP.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON)
  end
  TASK:Regist(taskHero00)
  local taskPartner00 = function()
    CH("PARTNER"):SetManpu("MP_SHOCK_R")
    CH("PARTNER"):SetMotion(SymMot("EV013_AVOID00"), LOOP.OFF)
    CH("PARTNER"):MoveTo(SymPos("P10_PARTNER"), Speed(3), LINK_DIR.OFF)
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):SetMotion(SymMot("EV013_AVOID03"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON)
  end
  TASK:Regist(taskPartner00)
  TASK:WaitTask()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_03"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), 1269160972)
  WINDOW:CloseMessage()
  CH("ENTEI"):SetScale(Scale(1.3))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P00_PARTNER"))
  CH("HERO"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 1388244301, PARTNER_1 = 2039725710})
  CH("PARTNER"):ResetShake()
  WINDOW:CloseMessage()
  CH("BUIZERU"):SetVisible(true)
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("BUIZERU"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):ResetShake()
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BUIZERU"), 1619562447)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("BUIZERU"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CH("HERO"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):ResetShake()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(801708296)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("ENTEI"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ENTEI"), 919742537)
  WINDOW:CloseMessage()
  CH("ENTEI"):DirTo(CH("HERO"), Speed(60), ROT_TYPE.NEAR)
  CH("ENTEI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), 503282570)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_04_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CAMERA:WaitMove()
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:Talk(SymAct("ENTEI"), 82070219)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CH("ENTEI"):WalkTo(SymPos("P00_ENTEI"), Speed(1))
  CH("ENTEI"):WaitMove()
  CH("ENTEI"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.2))
  CH("ENTEI"):WaitNeckRot()
  WINDOW:DrawFace(20, 20, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), -2089003516)
  WINDOW:CloseMessage()
  CH("ENTEI"):SetScale(Scale(1))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(true)
  CH("BUIZERU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BUIZERU"), -1704499387)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 99866943, PARTNER_1 = 485025918})
  WINDOW:CloseMessage()
  CH("ENTEI"):SetScale(Scale(1.2))
  CH("PARTNER"):SetVisible(false)
  CH("BUIZERU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:MoveFollow2(SymCam("CAMERA_08_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct("ENTEI"), 935705533)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CH("ENTEI"):SetVisible(false)
  CH("BUIZERU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_BEAT"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(0.5), TimeSec(0.05), true)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:SetEye(SymCam("CAMERA_03_5"))
  CAMERA:SetTgt(SymCam("CAMERA_03_5"))
  EFFECT:StartMotionBlur(0.04, 0.9, 0)
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.25))
  TASK:Sleep(TimeSec(0.4))
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(50, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  CAMERA:WaitMove()
  SCREEN_A:FadeOut(TimeSec(0.1), true)
  EFFECT:EndMotionBlur()
  CAMERA:SetDefaultGroundFovy()
end
function main15_enteishujinkoushinkaboss1st01_end()
end
function main15_enteishujinkoushinkaboss1st02_init()
end
function main15_enteishujinkoushinkaboss1st02_start()
  SAJI:CreateSajiPlayer("seimeinoki", "EV15_120_02_1")
  SJ("seimeinoki"):SetPosition(Vector2(200, 120))
  SJ("seimeinoki"):SetDrawPriority(1024)
  SJ("seimeinoki"):Play(LOOP.OFF)
  SOUND:PlaySe(SymSnd("SE_EVT_BEAT"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0), true)
  TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  SCREEN_A:FadeOut(TimeSec(0), true)
  SAJI:DestroySajiPlayer("seimeinoki")
end
function main15_enteishujinkoushinkaboss1st02_end()
end
function main15_enteishujinkoushinkaboss1st03_init()
end
function main15_enteishujinkoushinkaboss1st03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CH("HERO"):SetVisibleScarf(true)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetScale(Scale(1.3))
  SCREEN_A:FadeIn(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.4))
  CH("ENTEI"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.3))
  CH("ENTEI"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.3))
  CH("ENTEI"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ENTEI"), 786336508)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOutAll(TimeSec(0.3), true)
end
function main15_enteishujinkoushinkaboss1st03_end()
end
function main15_enteishujinkoushinkaboss1st04_init()
end
function main15_enteishujinkoushinkaboss1st04_start()
  SAJI:CreateSajiPlayer("seimeinoki_02", "EV15_120_02_2")
  SJ("seimeinoki_02"):SetPosition(Vector2(200, 120))
  SJ("seimeinoki_02"):SetDrawPriority(1024)
  SJ("seimeinoki_02"):Play(LOOP.ON)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SEIMEINOKI_LIGHT_01"), Volume(256))
  TASK:Sleep(TimeSec(150, TIME_TYPE.FRAME))
  SCREEN_A:WhiteOut(TimeSec(0.5), true)
  SAJI:DestroySajiPlayer("seimeinoki_02")
  TASK:Sleep(TimeSec(0.5))
end
function main15_enteishujinkoushinkaboss1st04_end()
end
function main15_enteishujinkoushinkaboss1st05_init()
end
function main15_enteishujinkoushinkaboss1st05_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CH("HERO"):SetVisibleScarf(true)
  CH("PARTNER"):SetVisibleScarf(true)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("BUIZERU"):SetMotion(SymMot("EV020_DOWN00"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("ENTEI"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0))
  CH("ENTEI"):SetVisible(false)
  CH("BUIZERU"):SetVisible(false)
  CH("ENTEI"):SetScale(Scale(1.1))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  local taskSoundHeroScarf = function()
    SOUND:PlaySe(SymSnd("SE_EVT_HERO_SCARF_LIGHT_01"), Volume(256))
    TASK:Sleep(TimeSec(1.5))
    SOUND:FadeInEnv(SymSnd("SE_EVT_HERO_SCARF_LIGHT_02_LP"), TimeSec(0.5), Volume(190))
  end
  TASK:Regist(taskSoundHeroScarf)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 30 then
    EFFECT:Create("effectLuminousScarfLp", SymEff("EV_LUMINOUS_SCARF_LP"))
    EFFECT:SetPosition("effectLuminousScarfLp", CH("HERO"), BODY_POINT.CENTER)
    EFFECT:Play("effectLuminousScarfLp")
  elseif pokemonIndexHero == 5 then
    EFFECT:Create("effectLuminousScarfLp", SymEff("EV_LUMINOUS_SCARF_LP"))
    EFFECT:SetPosition("effectLuminousScarfLp", CH("HERO"), BODY_POINT.CENTER)
    EFFECT:Play("effectLuminousScarfLp")
  elseif pokemonIndexHero == 10 then
    EFFECT:Create("effectLuminousScarfLp", SymEff("EV_LUMINOUS_SCARF_LP"))
    EFFECT:SetPosition("effectLuminousScarfLp", SymPos("P_EFF_EV_LUMINOUS_SCARF_LP"))
    EFFECT:Play("effectLuminousScarfLp")
  else
    EFFECT:Create("effectLuminousScarfLp", SymEff("EV_LUMINOUS_SCARF_LP"))
    EFFECT:SetPosition("effectLuminousScarfLp", CH("HERO"), BODY_POINT.SCARF)
    EFFECT:Play("effectLuminousScarfLp")
  end
  TASK:Sleep(TimeSec(1.8))
  CH("ENTEI"):SetVisible(true)
  CH("BUIZERU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("ENTEI"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.3))
  CH("ENTEI"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("ENTEI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.4, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):ResetShake()
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF, TimeSec(0.5))
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 1637817403, PARTNER_1 = 2021928314})
  WINDOW:CloseMessage()
  local taskSoundPartnerScarf = function()
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_SCARF_LIGHT_01"), Volume(256))
    TASK:Sleep(TimeSec(1.5))
    SOUND:FadeInEnv(SymSnd("SE_EVT_PARTNER_SCARF_LIGHT_02_LP"), TimeSec(0.5), Volume(190))
  end
  TASK:Regist(taskSoundPartnerScarf)
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  EFFECT:Create("effectLuminousScarfLp02", SymEff("EV_LUMINOUS_SCARF_LP"))
  EFFECT:SetPosition("effectLuminousScarfLp02", CH("PARTNER"), BODY_POINT.SCARF)
  EFFECT:Play("effectLuminousScarfLp02")
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("ENTEI"):ResetNeckRot(TimeSec(0.15))
  CH("ENTEI"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("ENTEI"):WaitRotate()
  CH("ENTEI"):SetManpu("MP_EXCLAMATION")
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 1 then
    EFFECT:MoveTo("effectLuminousScarfLp", PosOffs(-0.3, 0), Speed(0.5))
  elseif pokemonIndexHero == 325 then
  elseif pokemonIndexHero == 197 then
    EFFECT:MoveTo("effectLuminousScarfLp", PosOffs(-0.2, 0), Speed(0.5))
  elseif pokemonIndexHero == 329 then
    EFFECT:MoveTo("effectLuminousScarfLp", PosOffs(-0.2, 0), Speed(0.5))
  elseif pokemonIndexHero == 479 then
    EFFECT:MoveTo("effectLuminousScarfLp", PosOffs(-0.3, 0), Speed(0.5))
  elseif pokemonIndexHero == 485 then
  elseif pokemonIndexHero == 595 then
    EFFECT:MoveTo("effectLuminousScarfLp", PosOffs(-0.3, 0), Speed(0.5))
  elseif pokemonIndexHero == 598 then
    EFFECT:MoveHeightTo("effectLuminousScarfLp", Height(0.15), Speed(0.25))
  elseif pokemonIndexHero == 766 then
    EFFECT:MoveHeightTo("effectLuminousScarfLp", Height(0.1), Speed(0.25))
  elseif pokemonIndexHero == 769 then
    EFFECT:MoveTo("effectLuminousScarfLp", PosOffs(-0.2, 0), Speed(0.5))
  elseif pokemonIndexHero == 772 then
    EFFECT:MoveHeightTo("effectLuminousScarfLp", Height(0.15), Speed(0.25))
    EFFECT:MoveTo("effectLuminousScarfLp", PosOffs(-0.05, 0), Speed(0.25))
  else
    EFFECT:MoveHeightTo("effectLuminousScarfLp", Height(0.2), Speed(0.25))
  end
  CH("HERO"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF, TimeSec(0.5))
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1403616953)
  WINDOW:CloseMessage()
  EFFECT:Remove("effectLuminousScarfLp")
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:Create("effectLuminousScarfLp", SymEff("EV_LUMINOUS_SCARF_LP"))
  EFFECT:SetPosition("effectLuminousScarfLp", CH("HERO"), BODY_POINT.CENTER)
  EFFECT:Play("effectLuminousScarfLp")
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(0.3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:FadeOutEnv(TimeSec(1.5))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_WHITEOUT"))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:WhiteOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
  EFFECT:Remove("effectLuminousScarfLp")
  EFFECT:Remove("effectLuminousScarfLp02")
end
function main15_enteishujinkoushinkaboss1st05_end()
end
function main15_enteishujinkoushinkaboss1st06_init()
end
function main15_enteishujinkoushinkaboss1st06_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CH("HERO"):SetVisibleScarf(true)
  CH("PARTNER"):SetVisibleScarf(true)
  CH("HERO"):SetShadow(false)
  CH("PARTNER"):SetShadow(false)
  CHARA:PreLoadHeroPartnerFinalEvlolution()
  CUT:Load(SymCut("m15_120_06"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_HENSHIN"), Volume(256))
  SOUND:FadeInEnv(SymSnd("SE_EVT_FINAL_EV_BACK_LP"), TimeSec(0.5), Volume(128))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main15_enteishujinkoushinkaboss1st06_end()
end
function main15_enteishujinkoushinkaboss1st07_init()
end
function main15_enteishujinkoushinkaboss1st07_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("BUIZERU"):SetMotion(SymMot("EV020_DOWN00"), LOOP.ON, TimeSec(0))
  SOUND:PlayBgm(SymSnd("BGM_EVE_HENSHIN_AFTER"), Volume(256))
  SCREEN_A:WhiteIn(TimeSec(0.5), false)
  CH("ENTEI"):WalkTo(SymPos("P00_ENTEI"), Speed(1), LINK_DIR.OFF)
  CH("ENTEI"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ENTEI"), 1253199864)
  WINDOW:CloseMessage()
  SOUND:FadeInEnv(SymSnd("SE_EVT_HERO_LIGHT_LP"), TimeSec(0.2), Volume(256))
  CH("ENTEI"):SetVisible(false)
  CH("BUIZERU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CAMERA:SetFovy(SymCam("CAMERA_00_5"))
  EFFECT:Create("effectShinkaEndGlitter01", SymEff("EV_SHINKA_END_GLITTER"))
  EFFECT:Create("effectShinkaEndGlitter02", SymEff("EV_SHINKA_END_GLITTER"))
  EFFECT:SetPosition("effectShinkaEndGlitter01", CH("HERO"), BODY_POINT.HEAD)
  EFFECT:SetPosition("effectShinkaEndGlitter02", CH("PARTNER"), BODY_POINT.HEAD)
  EFFECT:Play("effectShinkaEndGlitter01")
  EFFECT:Play("effectShinkaEndGlitter02")
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutEnv(TimeSec(1.5))
  TASK:Sleep(TimeSec(1))
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -852864201, PARTNER_1 = -734961034})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.6))
  CH("PARTNER"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.4))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CH("ENTEI"):SetScale(Scale(1.3))
  CH("HERO"):SetVisible(true)
  CH("ENTEI"):SetVisible(true)
  CH("BUIZERU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  local taskHero00 = function()
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskHero00)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 390493905, PARTNER_1 = 240994192})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 628102227, PARTNER_1 = 1013654802})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CH("ENTEI"):SetScale(Scale(1.4))
  CH("ENTEI"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  CH("ENTEI"):WalkTo(SymPos("P01_ENTEI"), Speed(1))
  WINDOW:DrawFace(72, 16, SymAct("ENTEI"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:Talk(SymAct("ENTEI"), 1932178389)
  CH("ENTEI"):WaitMove()
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("ENTEI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("ENTEI"), Speed(350), ROT_TYPE.NEAR)
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(72, 16, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:Talk(SymAct("ENTEI"), 1781629588)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_ENTEI_ANGRY"))
  EFFECT:Create("effectFireAngry", SymEff("EV_FIRE_ANGRY"))
  EFFECT:SetPosition("effectFireAngry", SymPos("P_EFF_EV_FIRE_APPEAR"))
  EFFECT:SetScale("effectFireAngry", Scale(1.5))
  EFFECT:Play("effectFireAngry")
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct("ENTEI"), 1092407639)
  WINDOW:CloseMessage()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("BUIZERU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetRotateZ(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(1476911126)
  WINDOW:Monologue(-543163175)
  WINDOW:CloseMessage()
  CH("ENTEI"):SetScale(Scale(1.2))
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), -964375144)
  SOUND:FadeOutBgm(TimeSec(2))
  WINDOW:Talk(SymAct("ENTEI"), -1342565964)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CH("ENTEI"):SetScale(Scale(1.3))
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("ENTEI"), -1226759947)
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.2))
  CH("ENTEI"):SetMotion(SymMot("EV015_BARK00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_ROAR"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-1647545546)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main15_enteishujinkoushinkaboss1st07_end()
end
function groundEnd()
end
