dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main22_oobemunohanashi01_init()
end
function main22_oobemunohanashi01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteIn(TimeSec(0.1), false)
  TASK:Sleep(TimeSec(0.1))
  CH("OOBEMU"):SetManpu("MP_SHOCK_R")
  CH("OOBEMU"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
  CH("OOBEMU"):WaitPlayMotion()
  CH("OOBEMU"):SetMotion(SymMot("FALL"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(256))
  CH("OOBEMU"):WaitPlayMotion()
  CH("OOBEMU"):SetMotion(SymMot("EV022_DOWN00"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(1.2))
  CH("OOBEMU"):SetShake(Vector(0.01, 0, 0), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU"):ResetShake()
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_FLASH_OUT"), Volume(190))
  CH("OOBEMU"):SetMotion(SymMot("EV022_DOWN01"), LOOP.OFF)
  CH("OOBEMU"):SetMotionRaito(Raito(0.8))
  CH("OOBEMU"):WaitPlayMotion()
  CH("OOBEMU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("OOBEMU"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  WINDOW:Monologue(-297941465)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NYASUPAA"):SetManpu("MP_FLY_SWEAT")
  CH("NYASUPAA"):WaitManpu()
  WINDOW:DrawFace(272, 88, SymAct("NYASUPAA"), FACE_TYPE.SPECIAL03)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Talk(SymAct("NYASUPAA"), -148441242)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  TASK:Sleep(TimeSec(0.2))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("OOBEMU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  local taskOobemu00 = function()
    CH("OOBEMU"):SetMotion(SymMot("CHARGE"), LOOP.OFF)
    CH("OOBEMU"):WaitPlayMotion()
    CH("OOBEMU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  end
  TASK:Regist(taskOobemu00)
  WINDOW:Talk(SymAct("OOBEMU"), -603216731)
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("OOBEMU"):RunTo(SymPos("P00_OOBEMU"), Speed(2.5))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("OOBEMU"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskLookAt00)
  WINDOW:SwitchTalk({PARTNER_0 = -988768796, PARTNER_1 = -1974402269})
  TASK:Sleep(TimeSec(0.25))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(4))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  local taskOobemu01 = function()
    CH("OOBEMU"):SetManpu("MP_SHOCK_R")
    CH("OOBEMU"):SetMotion(SymMot("EV022_BLOWN00"), LOOP.OFF)
    CH("OOBEMU"):MoveTo(SymPos("P01_OOBEMU"), Speed(5), LINK_DIR.OFF)
    CH("OOBEMU"):WaitPlayMotion()
    CH("OOBEMU"):SetMotion(SymMot("EV022_BLOWN01"), LOOP.ON)
    CH("OOBEMU"):WaitPlayMotion()
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    CH("OOBEMU"):SetMotion(SymMot("EV022_BLOWN03"), LOOP.ON)
    CH("OOBEMU"):MoveHeightTo(Height(0.1), Speed(1.5))
    CH("OOBEMU"):WaitMoveHeight()
    CH("OOBEMU"):MoveHeightTo(Height(0), Speed(1.5))
    CH("OOBEMU"):WaitMoveHeight()
    CH("OOBEMU"):MoveHeightTo(Height(0.1), Speed(1.5))
    CH("OOBEMU"):WaitMoveHeight()
    CH("OOBEMU"):MoveHeightTo(Height(0), Speed(1.5))
    CH("OOBEMU"):WaitMoveHeight()
    TASK:Sleep(TimeSec(0.2))
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  end
  CH("PARTNER"):WaitMove()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("NYASUPAA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_DOSHU"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("PARTNER"):SetMotion(SymMot("ATTACK"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Regist(taskOobemu01)
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(2.3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):WaitPlayMotion()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("OOBEMU"), -1823853982)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(3))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = -1201184351, PARTNER_1 = -1585688352})
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  WINDOW:SwitchTalk({PARTNER_0 = 652495919, PARTNER_1 = 1073708398})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -1897826124, PARTNER_1 = -1745204747})
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -1126753738, PARTNER_1 = -1513346185})
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -359809616, PARTNER_1 = -208237327})
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("NYASUPAA"):SetPosition(SymPos("P00_NYASUPAA"))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CH("NYASUPAA"):SetDir(RotateTarget(0))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("NYASUPAA"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  TASK:Regist(subEveDoubleJump, {
    CH("NYASUPAA")
  })
  CH("NYASUPAA"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(72, 16, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("NYASUPAA"), -658776270)
  WINDOW:KeyWait()
  CH("NYASUPAA"):ResetManpu()
  WINDOW:Talk(SymAct("NYASUPAA"), -1046417805)
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_06_5"))
  CAMERA:SetTgt(SymCam("CAMERA_06_5"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WalkTo(SymPos("P03_PARTNER"), Speed(0.8), LINK_DIR.OFF)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = 1178137276, PARTNER_1 = 1596179453})
  CH("PARTNER"):WaitMove()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("NYASUPAA"):DirTo(CH("OOBEMU"), Speed(500), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("NYASUPAA")
  })
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("NYASUPAA"), -1672161446)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_FLY_SWEAT")
  CH("OOBEMU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), -2058361317)
  WINDOW:Talk(SymAct("OOBEMU"), -1369262632)
  WINDOW:Talk(SymAct("OOBEMU"), -1216772967)
  WINDOW:Talk(SymAct("OOBEMU"), -130543010)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-517790945)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -905023268, PARTNER_1 = -753581667})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), 1418550610)
  WINDOW:Talk(SymAct("OOBEMU"), 1301703699)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_04"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 619229247, PARTNER_1 = 1039368574})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("OOBEMU"):SetMotion(SymMot("EV022_BLOWN04"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.3))
  CH("NYASUPAA"):WalkTo(SymPos("P01_NYASUPAA"), Speed(1), LINK_DIR.OFF)
  CH("OOBEMU"):WaitPlayMotion()
  CH("OOBEMU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:DrawFace(72, 16, SymAct("OOBEMU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("OOBEMU"), 383701693)
  WINDOW:Talk(SymAct("OOBEMU"), 264627196)
  WINDOW:Talk(SymAct("OOBEMU"), 1082422587)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("OOBEMU"), 1503609978)
  WINDOW:Talk(SymAct("OOBEMU"), 1924274105)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = 1806247672, PARTNER_1 = -332318153})
  WINDOW:SwitchTalk({PARTNER_0 = -181793930, PARTNER_1 = -1187018618})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1608205881)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1962284540, PARTNER_1 = -1844257979})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -581743230)
  WINDOW:Talk(SymAct("NYASUPAA"), -1001882429)
  WINDOW:Talk(SymAct("NYASUPAA"), -278581504)
  WINDOW:Talk(SymAct("NYASUPAA"), -159506879)
  WINDOW:Talk(SymAct("NYASUPAA"), 1910899342)
  WINDOW:Talk(SymAct("NYASUPAA"), 1761424335)
  WINDOW:Talk(SymAct("NYASUPAA"), 25423843)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_FLY_SWEAT")
  CH("OOBEMU"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("OOBEMU")
  })
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("OOBEMU"), 412671650)
  WINDOW:Talk(SymAct("OOBEMU"), 867536225)
  WINDOW:Talk(SymAct("OOBEMU"), 716094496)
  WINDOW:Talk(SymAct("OOBEMU"), 1710172903)
  WINDOW:Talk(SymAct("OOBEMU"), 2096372646)
  WINDOW:Talk(SymAct("OOBEMU"), 1473857637)
  WINDOW:CloseMessage()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CAMERA:SetEye(SymCam("CAMERA_09_5"))
  CAMERA:SetTgt(SymCam("CAMERA_09_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1321367844, PARTNER_1 = -916822549})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-801024854)
  WINDOW:Monologue(322322445)
  WINDOW:Monologue(170750284)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 553656975, PARTNER_1 = 941298638})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), 2002421001)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("NYASUPAA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NYASUPAA"), 1849799752)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1164765067, PARTNER_1 = 1551357642})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -605042171)
  WINDOW:Talk(SymAct("OOBEMU"), -1024132284)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1417009304)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -1299114455)
  WINDOW:Talk(SymAct("OOBEMU"), -1715714582)
  WINDOW:Talk(SymAct("OOBEMU"), -2136509269)
  WINDOW:Talk(SymAct("OOBEMU"), -806952340)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(-688008403)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("OOBEMU"), -36667154)
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), -456412753)
  WINDOW:Talk(SymAct("OOBEMU"), 1666428256)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("OOBEMU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("OOBEMU"), 2051578913)
  WINDOW:Talk(SymAct("OOBEMU"), -202819778)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CH("OOBEMU"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.3))
  CH("OOBEMU"):WaitNeckRot()
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_15"))
  CAMERA:SetTgt(SymCam("CAMERA_15"))
  CH("NYASUPAA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("NYASUPAA"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -353237377)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1042328132)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -658217731, PARTNER_1 = -1752829382})
  WINDOW:SwitchTalk({PARTNER_0 = -1902197893, PARTNER_1 = -1514958664})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  subEveNod(CH("NYASUPAA"))
  WINDOW:DrawFace(20, 20, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1129799175)
  WINDOW:CloseMessage()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(SymPos("P02_NYASUPAA"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(SymPos("P02_NYASUPAA"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.5))
    CH("OOBEMU"):ResetNeckRot(TimeSec(0.15))
    CH("OOBEMU"):DirTo(SymPos("P02_NYASUPAA"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  CH("NYASUPAA"):WalkTo(SymPos("P02_NYASUPAA"), Speed(1))
  CH("NYASUPAA"):WaitMove()
  CAMERA:SetEye(SymCam("CAMERA_16"))
  CAMERA:SetTgt(SymCam("CAMERA_16"))
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):SetEyeMotion(EYE_MOTION.CLOSE)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_NYASUPAA_ALERT"), Volume(190))
  WINDOW:SysMsg(993049910)
  TASK:Sleep(TimeSec(1))
  subEveCloseMsg()
  WINDOW:Talk(SymAct("NYASUPAA"), 573279351)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1263882331, PARTNER_1 = 1380868378})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_16"))
  CAMERA:SetTgt(SymCam("CAMERA_16"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("NYASUPAA"), 2036544217)
  subEveCloseMsg()
  CH("NYASUPAA"):ResetFacialMotion()
  WINDOW:DrawFace(272, 16, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1618477976)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("NYASUPAA"), 792302943)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  CAMERA:SetEye(SymCam("CAMERA_19"))
  CAMERA:SetTgt(SymCam("CAMERA_19"))
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 908239902, PARTNER_1 = 487585757})
  WINDOW:SwitchTalk({PARTNER_0 = 68470428, PARTNER_1 = -2087921069})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1701319918, PARTNER_1 = 1088960607})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1509099806, PARTNER_1 = 1927174877})
  WINDOW:SwitchTalk({PARTNER_0 = 1808100252, PARTNER_1 = 612695387})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1033882650)
  WINDOW:Talk(SymAct("NYASUPAA"), 380805081)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(262778520)
  WINDOW:Monologue(-2010009001)
  WINDOW:Monologue(-1859484906)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_19"))
  CAMERA:SetTgt(SymCam("CAMERA_19"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -128688326, PARTNER_1 = -514888069})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -899531336)
  WINDOW:Talk(SymAct("NYASUPAA"), -747041543)
  WINDOW:Talk(SymAct("NYASUPAA"), -1674012098)
  WINDOW:Talk(SymAct("NYASUPAA"), -2061259905)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):RunTo(SplinePath(SymSpl("S00_NYASUPAA")), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.7))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1374750532, PARTNER_1 = -1223308803})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_17"))
  CAMERA:SetTgt(SymCam("CAMERA_17"))
  CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 814601522, PARTNER_1 = 697754739})
  WINDOW:SwitchTalk({PARTNER_0 = -354291500, PARTNER_1 = -201670251})
  WINDOW:KeyWait()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -656960938, PARTNER_1 = -1043553513})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -1903348272)
  WINDOW:Talk(SymAct("OOBEMU"), -1751776111)
  WINDOW:Talk(SymAct("OOBEMU"), -1128573102)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_18"))
  CAMERA:SetTgt(SymCam("CAMERA_18"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1516214765, PARTNER_1 = 574126812})
  WINDOW:SwitchTalk({PARTNER_0 = 992168861, PARTNER_1 = 1381865393})
  WINDOW:SwitchTalk({PARTNER_0 = 1262921456, PARTNER_1 = 1617687859})
  WINDOW:SwitchTalk({PARTNER_0 = 2037433458, PARTNER_1 = 909202101})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main22_oobemunohanashi01_end()
end
function groundEnd()
end
