dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main10_tenkeisanninosekiclear1st01_init()
end
function main10_tenkeisanninosekiclear1st01_start()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), -497913622)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -79085141, PARTNER_1 = -798748056})
  WINDOW:SwitchTalk({PARTNER_0 = -914414807, PARTNER_1 = -2042710546})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -1624931153)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskNyorobon00 = function()
    function TaskL.Loop()
      CH("NYOROBON"):DirTo(RotateOffs(-45), Speed(200))
      CH("NYOROBON"):WaitRotate()
      TASK:Sleep(TimeSec(2))
      CH("NYOROBON"):DirTo(RotateOffs(90), Speed(300))
      CH("NYOROBON"):WaitRotate()
      TASK:Sleep(TimeSec(5))
      CH("NYOROBON"):DirTo(RotateOffs(-45), Speed(200))
      CH("NYOROBON"):WaitRotate()
      TASK:Sleep(TimeSec(5))
    end
    function TaskL.Finish()
      return
    end
  end
  local taskSupiaa00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.3))
      CH("SUPIAA"):DirTo(RotateOffs(-45), Speed(600))
      CH("SUPIAA"):WaitRotate()
      TASK:Sleep(TimeSec(1.5))
      CH("SUPIAA"):DirTo(RotateOffs(90), Speed(600))
      CH("SUPIAA"):WaitRotate()
      TASK:Sleep(TimeSec(1))
      CH("SUPIAA"):DirTo(RotateOffs(-45), Speed(600))
      CH("SUPIAA"):WaitRotate()
      TASK:Sleep(TimeSec(3))
    end
    function TaskL.Finish()
      return
    end
  end
  local taskJibakoiru00 = function()
    function TaskL.Loop()
      CH("JIBAKOIRU"):DirTo(RotateOffs(-45), Speed(100))
      CH("JIBAKOIRU"):WaitRotate()
      TASK:Sleep(TimeSec(1.5))
      CH("JIBAKOIRU"):DirTo(RotateOffs(90), Speed(200))
      CH("JIBAKOIRU"):WaitRotate()
      TASK:Sleep(TimeSec(1.5))
      CH("JIBAKOIRU"):DirTo(RotateOffs(-45), Speed(100))
      CH("JIBAKOIRU"):WaitRotate()
      TASK:Sleep(TimeSec(5))
    end
    function TaskL.Finish()
      return
    end
  end
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHUKEI"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  TASK:Sleep(TimeSec(1))
  TASK:Regist(taskJibakoiru00)
  TASK:Sleep(TimeSec(3))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Regist(taskNyorobon00)
  TASK:Regist(taskSupiaa00)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -1274488980)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1391204819, PARTNER_1 = 713816802})
  WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), 865127331)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -759706783, PARTNER_1 = -877856224})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), -528373277)
  WINDOW:Talk(SymAct("KONOHANA"), -107308894)
  WINDOW:CloseMessage()
  local taskUnazuku00 = function()
    subEveNod(CH("HERO"))
  end
  local taskUnazuku01 = function()
    subEveNod(CH("PARTNER"))
  end
  TASK:Regist(taskUnazuku00)
  TASK:Regist(taskUnazuku01)
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutBgm(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function main10_tenkeisanninosekiclear1st01_end()
end
function main10_tenkeisanninosekiclear1st02_init()
end
function main10_tenkeisanninosekiclear1st02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:FadeInEnv(SymSnd("SE_MAP_HILLSWIND_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), -1227157915)
  WINDOW:Talk(SymAct("KONOHANA"), -1346355420)
  WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), -2064814873)
  WINDOW:Talk(SymAct("KONOHANA"), -1644798554)
  WINDOW:Talk(SymAct("KONOHANA"), 443433321)
  subEveCloseMsg()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("KONOHANA"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 58028072, PARTNER_1 = -1073585009})
  WINDOW:SwitchTalk({PARTNER_0 = -652651058, PARTNER_1 = -231471603})
  WINDOW:SwitchTalk({PARTNER_0 = -349227188, PARTNER_1 = -1536253557})
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), -1116368694)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  CH("KONOHANA"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  TASK:Sleep(TimeSec(0.8))
  CH("KONOHANA"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -1772567799)
  WINDOW:Talk(SymAct("KONOHANA"), -1891372472)
  WINDOW:Talk(SymAct("KONOHANA"), 148631175)
  WINDOW:Talk(SymAct("KONOHANA"), 297852870)
  WINDOW:CloseMessage()
  CH("KONOHANA"):WalkTo(SplinePath(SymPos("P00_KONOHANA"), SymPos("P01_KONOHANA"), SymPos("P02_KONOHANA")), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P02_KONOHANA"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(SymPos("P02_KONOHANA"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(2.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 2025718762, PARTNER_1 = 1638216363})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main10_tenkeisanninosekiclear1st02_end()
end
function groundEnd()
end
