dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main20_shizukanaiwabano2yarare01_init()
end
function main20_shizukanaiwabano2yarare01_start()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 1125835963, PARTNER_1 = 1510069754})
  WINDOW:KeyWait()
  SCREEN_A:FadeOutAll(TimeSec(0.5), true)
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("SE_ENV_FOREST_NIGHT_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("AAKEN"), 1898743353)
  subEveCloseMsg()
  CH("AAKEN"):ResetFacialMotion()
  WINDOW:DrawFace(324, 20, SymAct("DEDENNE"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DEDENNE"), 1748481912)
  WINDOW:CloseMessage()
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), 662053311)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1047335166, PARTNER_1 = 356533053})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  local taskUnun00 = function()
    subEveNod(CH("HERO"))
  end
  local taskUnun01 = function()
    subEveNod(CH("PARTNER"))
  end
  local taskUnun02 = function()
    subEveNod(CH("DEDENNE"))
  end
  local taskUnun03 = function()
    subEveNod(CH("KUCHIITO"))
  end
  local taskUnun05 = function()
    subEveNod(CH("AAKEN"))
  end
  TASK:Regist(taskUnun00)
  TASK:Regist(taskUnun01)
  TASK:Regist(taskUnun02)
  TASK:Regist(taskUnun03)
  TASK:Regist(taskUnun05)
  TASK:Sleep(TimeSec(0.7))
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:MoveToHero(Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
end
function main20_shizukanaiwabano2yarare01_end()
end
function groundEnd()
end
