dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main05_konohanakaettekiteta01_init()
end
function main05_konohanakaettekiteta01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_NOTICE_R")
  CH("KONOHANA"):WaitManpu()
  CH("KONOHANA"):DirTo(SymPos("P00_HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1702464079)
  WINDOW:Talk(SymAct("KONOHANA"), 2086845198)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_HAPPY"), Volume(256))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  CH("HERO"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(1464854733)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1314183564)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_QUESTION")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 18173771)
  WINDOW:Talk(SymAct("KONOHANA"), 403602954)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("KONOHANA"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("KONOHANA"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  CH("KONOHANA"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), 857943497)
  WINDOW:CloseMessage()
  CH("KONOHANA"):ResetNeckRot(TimeSec(0.15))
  CH("KONOHANA"):WaitNeckRot()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 708320392)
  WINDOW:Talk(SymAct("KONOHANA"), -1382023097)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  subEveNo(CH("HERO"))
  TASK:Sleep(TimeSec(0.6))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -1262800634)
  WINDOW:Talk(SymAct("KONOHANA"), 1554980836)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), 1169436325)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  subEveNo(CH("HERO"))
  TASK:Sleep(TimeSec(0.6))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1855552870)
  WINDOW:Talk(SymAct("KONOHANA"), 2005027879)
  WINDOW:Talk(SymAct("KONOHANA"), 952359648)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutBgm(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
end
function main05_konohanakaettekiteta01_end()
end
function groundEnd()
end
