dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_inisienohoneatobosswin01_init()
end
function main09_inisienohoneatobosswin01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("GIRATYINA_A"):SetMotion(SymMot("EV009_DOWN00"), LOOP.OFF)
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SHIKIJIKA_SPRING"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("NUMERA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_GIRATYINA_DEATHCRY"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:Talk(SymAct("GIRATYINA_A"), -988927670)
  TASK:Sleep(TimeSec(0.9))
  SOUND:PlaySe(SymSnd("SE_EVT_GIRATYINA_DOWN"))
  TASK:Sleep(TimeSec(0.6))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("GIRATYINA_A"):WaitPlayMotion()
  CH("GIRATYINA_A"):SetMotion(SymMot("EV009_DOWN01"), LOOP.ON)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(0.3))
  local taskAll00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("SHIKIJIKA_SPRING"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("NYASUPAA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskAll00)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("HITOMOSHI")
  })
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveJumpSurprise, {
    CH("HITOMOSHI3")
  })
  CH("HITOMOSHI"):WaitManpu()
  CH("NUMERA"):DirTo(SymPos("P00_HITOMOSHI3"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(SymPos("P00_HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("HITOMOSHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HITOMOSHI"), -602597365)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  CH("HITOMOSHI2"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("HITOMOSHI2")
  })
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveJumpSurprise, {
    CH("HITOMOSHI4")
  })
  CH("HITOMOSHI"):WaitManpu()
  CH("HERO"):DirTo(SymPos("P00_HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(SymPos("P00_HITOMOSHI4"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P00_HITOMOSHI4"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(272, 16, SymAct("HITOMOSHI2"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HITOMOSHI"), -147305528)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_RUN_ESCAPE"))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT_LP")
  CH("HITOMOSHI"):WalkTo(SymPos("P00_HITOMOSHI"), Speed(4))
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT_LP")
  CH("HITOMOSHI2"):WalkTo(SymPos("P00_HITOMOSHI2"), Speed(4))
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT_LP")
  CH("HITOMOSHI3"):WalkTo(SymPos("P00_HITOMOSHI3"), Speed(4))
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT_LP")
  CH("HITOMOSHI4"):WalkTo(SymPos("P00_HITOMOSHI4"), Speed(4))
  TASK:Sleep(TimeSec(1))
  CH("HITOMOSHI"):SetVisible(false)
  CH("HITOMOSHI2"):SetVisible(false)
  CH("HITOMOSHI3"):SetVisible(false)
  CH("HITOMOSHI4"):SetVisible(false)
  CH("HITOMOSHI"):ResetManpu()
  CH("HITOMOSHI2"):ResetManpu()
  CH("HITOMOSHI3"):ResetManpu()
  CH("HITOMOSHI4"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -299664759, PARTNER_1 = -1587352498})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1199973105)
  WINDOW:CloseMessage()
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -1823174964)
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir2, {
    CH("HERO"),
    SymPos("P00_HERO"),
    Speed(1.5),
    SymPos("P00_HERO")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveMoveDir2, {
    CH("PARTNER"),
    SymPos("P00_PARTNER"),
    Speed(1.5),
    SymPos("P00_PARTNER")
  })
  TASK:Regist(subEveMoveDir2, {
    CH("SHIKIJIKA_SPRING"),
    SymPos("P00_SHIKIJIKA"),
    Speed(1.5),
    SymPos("P00_SHIKIJIKA")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir2, {
    CH("NUMERA"),
    SymPos("P00_NUMERA"),
    Speed(1.5),
    SymPos("P00_NUMERA")
  })
  TASK:Regist(subEveMoveDir2, {
    CH("NYASUPAA"),
    SymPos("P00_NYASUPAA"),
    Speed(1.5),
    SymPos("P00_NYASUPAA")
  })
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:WaitTask()
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("GIRATYINA_A"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("GIRATYINA_A"):ResetShake()
  WINDOW:DrawFace(324, 20, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), -1974485107)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 232235842, PARTNER_1 = 348951043})
  WINDOW:SwitchTalk({PARTNER_0 = 1846000004, PARTNER_1 = 1998358725})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("GIRATYINA_A"), 1546771206)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 1160440391)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 174816384)
  WINDOW:Talk(SymAct("NYASUPAA"), 326127041)
  WINDOW:Talk(SymAct("NYASUPAA"), 945626626)
  WINDOW:Talk(SymAct("NYASUPAA"), 558247747)
  WINDOW:Talk(SymAct("NYASUPAA"), -1495387252)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GIRATYINA_A"):SetManpu("MP_FLY_SWEAT")
  CH("GIRATYINA_A"):WaitManpu()
  WINDOW:Talk(SymAct("GIRATYINA_A"), -1077607731)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 2092045930)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 1705584427)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1317303528)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GIRATYINA_A"):SetManpu("MP_FLY_SWEAT")
  CH("GIRATYINA_A"):WaitManpu()
  WINDOW:Talk(SymAct("GIRATYINA_A"), 1470055849)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  CH("HITOMOSHI"):SetVisible(true)
  CH("HITOMOSHI2"):SetVisible(true)
  CH("HITOMOSHI3"):SetVisible(true)
  CH("HITOMOSHI4"):SetVisible(true)
  CH("HITOMOSHI"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI4"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI"):SetShadow(false)
  CH("HITOMOSHI2"):SetShadow(false)
  CH("HITOMOSHI3"):SetShadow(false)
  CH("HITOMOSHI4"):SetShadow(false)
  CH("HITOMOSHI"):SetPosition(SymPos("P01_HITOMOSHI"))
  CH("HITOMOSHI2"):SetPosition(SymPos("P01_HITOMOSHI2"))
  CH("HITOMOSHI3"):SetPosition(SymPos("P01_HITOMOSHI3"))
  CH("HITOMOSHI4"):SetPosition(SymPos("P01_HITOMOSHI4"))
  CH("HITOMOSHI"):SetDir(CH("GIRATYINA_A"))
  CH("HITOMOSHI2"):SetDir(CH("GIRATYINA_A"))
  CH("HITOMOSHI3"):SetDir(CH("GIRATYINA_A"))
  CH("HITOMOSHI4"):SetDir(CH("GIRATYINA_A"))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_BLACK_KYUREMU_COME_01"), Volume(256))
  CH("GIRATYINA_A"):SetMotion(SymMot("EV009_DOWN02"), LOOP.OFF)
  local taskAll01 = function()
    TASK:Sleep(TimeSec(0.2))
    TASK:Regist(subEveRunDir, {
      CH("NYASUPAA"),
      SymPos("P01_NYASUPAA"),
      Speed(2),
      CH("GIRATYINA_A")
    })
    TASK:Regist(subEveRunDir, {
      CH("SHIKIJIKA_SPRING"),
      SymPos("P01_SHIKIJIKA"),
      Speed(2),
      CH("GIRATYINA_A")
    })
    TASK:Sleep(TimeSec(0.1))
    TASK:Regist(subEveRunDir, {
      CH("NUMERA"),
      SymPos("P01_NUMERA"),
      Speed(2),
      CH("GIRATYINA_A")
    })
    TASK:Sleep(TimeSec(0.2))
    TASK:Regist(subEveRunDir, {
      CH("HERO"),
      SymPos("P01_HERO"),
      Speed(2),
      CH("GIRATYINA_A")
    })
    TASK:Sleep(TimeSec(0.1))
    TASK:Regist(subEveRunDir, {
      CH("PARTNER"),
      SymPos("P01_PARTNER"),
      Speed(2),
      CH("GIRATYINA_A")
    })
  end
  TASK:Regist(taskAll01)
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.5))
  CH("SHIKIJIKA_SPRING"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("NUMERA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("GIRATYINA_A"):WaitPlayMotion()
  CH("GIRATYINA_A"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  WINDOW:Talk(SymAct("GIRATYINA_A"), 417256302)
  WINDOW:KeyWait()
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("GIRATYINA_A"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 29745711)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("GIRATYINA_A"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  WINDOW:Talk(SymAct("HITOMOSHI"), 719892972)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("GIRATYINA_A"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  local taskGiratyina00 = function()
    CH("GIRATYINA_A"):DirTo(CH("HITOMOSHI"), Speed(200), ROT_TYPE.NEAR)
    CH("GIRATYINA_A"):WaitRotate()
    CH("GIRATYINA_A"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.3))
    CH("GIRATYINA_A"):WaitNeckRot()
  end
  EFFECT:Create("effectFire01", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire01", SymPos("P_EFF_FIRE_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_HONOO_ENTRY"), Volume(256))
  EFFECT:Play("effectFire01")
  TASK:Sleep(TimeSec(0.1))
  EFFECT:Create("effectFire04", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire04", SymPos("P_EFF_FIRE_04"))
  EFFECT:Play("effectFire04")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P_EFF_FIRE_02"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(SymPos("P_EFF_FIRE_01"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P_EFF_FIRE_04"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(taskGiratyina00)
  EFFECT:Create("effectFire02", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire02", SymPos("P_EFF_FIRE_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_HONOO_ENTRY"), Volume(256))
  EFFECT:Play("effectFire02")
  TASK:Sleep(TimeSec(0.1))
  EFFECT:Create("effectFire03", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire03", SymPos("P_EFF_FIRE_03"))
  EFFECT:Play("effectFire03")
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):DirTo(SymPos("P_EFF_FIRE_04"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(SymPos("P_EFF_FIRE_03"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.8))
  SOUND:PlaySe(SymSnd("SE_EVT_HITOMOSHI_ENTRY"), Volume(256))
  EFFECT:ChangeColor("effectFire01", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectFire02", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectFire03", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectFire04", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.25))
  CH("HITOMOSHI"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI3"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI4"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI"):SetShadow(true)
  CH("HITOMOSHI2"):SetShadow(true)
  CH("HITOMOSHI3"):SetShadow(true)
  CH("HITOMOSHI4"):SetShadow(true)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(272, 16, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), 871596205)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("HITOMOSHI"), -1268016030)
  WINDOW:CloseMessage()
  local taskAll02 = function()
    CH("PARTNER"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("NUMERA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll02)
  WINDOW:DrawFace(324, 20, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), -1385124573)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HITOMOSHI"), -1005686513)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GIRATYINA_A"):SetManpu("MP_FLY_SWEAT")
  CH("GIRATYINA_A"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), -585809842)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HITOMOSHI"), -164097139)
  WINDOW:Talk(SymAct("HITOMOSHI"), -282910004)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(-150), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(-150), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  CH("GIRATYINA_A"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GIRATYINA_A"):SetManpu("MP_FLY_SWEAT")
  CH("GIRATYINA_A"):WaitManpu()
  CH("GIRATYINA_A"):ResetShake()
  WINDOW:DrawFace(324, 20, SymAct("GIRATYINA_A"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GIRATYINA_A"), -1604144117)
  CH("GIRATYINA_A"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("GIRATYINA_A"):ResetShake()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_HENSHIN"))
  EFFECT:Create("effectWhiteOut", SymEff("EV_BREAK_BOSS_SKY"))
  EFFECT:SetPosition("effectWhiteOut", SymPos("P_EFF_WHITE"))
  EFFECT:Play("effectWhiteOut")
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteOut(TimeSec(0.3), true)
end
function main09_inisienohoneatobosswin01_end()
end
function main09_inisienohoneatobosswin01_5_init()
end
function main09_inisienohoneatobosswin01_5_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YUNIRAN"):SetFacialMotion(FACIAL_MOTION.WEEP)
  CH("YUNIRAN"):SetManpu("MP_FLY_SWEAT_LP")
  WINDOW:DrawFace(272, 16, SymAct("YUNIRAN"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("YUNIRAN"), -1183218358)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("YUNIRAN")
  })
  WINDOW:Talk(SymAct("YUNIRAN"), -1839933815)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("NUMERA"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("NUMERA")
  })
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -1957697592)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HITOMOSHI"), 215481095)
  WINDOW:Talk(SymAct("HITOMOSHI"), 365742662)
  subEveCloseMsg()
  CH("YUNIRAN"):ResetManpu()
  TASK:Regist(subEveJump, {
    CH("YUNIRAN")
  })
  WINDOW:DrawFace(324, 20, SymAct("YUNIRAN"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("YUNIRAN"), 1507412406)
  CH("YUNIRAN"):SetManpu("MP_FLY_SWEAT")
  CH("YUNIRAN"):WaitManpu()
  TASK:Regist(subEveJump, {
    CH("YUNIRAN")
  })
  WINDOW:CloseMessage()
  CH("YUNIRAN"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.5))
  CH("YUNIRAN"):SetEyeMotion(EYE_MOTION.PAIN)
  TASK:Sleep(TimeSec(0.1))
  CH("YUNIRAN"):SetEyeMotion(EYE_MOTION.NORMAL)
  TASK:Sleep(TimeSec(0.2))
  CH("YUNIRAN"):SetEyeMotion(EYE_MOTION.PAIN)
  TASK:Sleep(TimeSec(0.1))
  CH("YUNIRAN"):SetEyeMotion(EYE_MOTION.NORMAL)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  local taskAll00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll00)
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1086486775)
  WINDOW:CloseMessage()
  CH("HITOMOSHI"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI2"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI3"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI4"):WaitRotate()
  CH("YUNIRAN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 20, SymAct("HITOMOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI"), 1810836276)
  WINDOW:Talk(SymAct("HITOMOSHI"), 1928600181)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1035308210, PARTNER_1 = 615431667})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI4"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("HITOMOSHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HITOMOSHI"), 260304432)
  WINDOW:KeyWait()
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI3"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI3"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  WINDOW:Talk(SymAct("HITOMOSHI"), 379117425)
  CH("HITOMOSHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HITOMOSHI3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  local taskAll01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll01)
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI2"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("HITOMOSHI2"), -1862220866)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI2"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI2"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI4"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI4"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  WINDOW:Talk(SymAct("HITOMOSHI2"), -2011434241)
  CH("HITOMOSHI2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HITOMOSHI4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -513462573)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_QUESTION")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -125952110)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI"):ResetFacialMotion()
  CH("HITOMOSHI2"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):ResetFacialMotion()
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI2"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HITOMOSHI2"), -749515695)
  WINDOW:Talk(SymAct("HITOMOSHI2"), -901219056)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HITOMOSHI4"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HITOMOSHI4"), -2062947369)
  WINDOW:Talk(SymAct("HITOMOSHI4"), -1676485994)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1220572843, PARTNER_1 = -1373325292})
  subEveCloseMsg()
  local taskAll02 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("HERO"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll02)
  WINDOW:DrawFace(20, 20, SymAct("HITOMOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI"), 700228827)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  local taskNumera00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("NUMERA"):DirTo(CH("HITOMOSHI3"), Speed(500), ROT_TYPE.NEAR)
    CH("NUMERA"):WaitRotate()
    CH("PARTNER"):DirTo(CH("HITOMOSHI3"), Speed(500), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("HITOMOSHI3"), Speed(500), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI3"), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("HITOMOSHI3"), Speed(500), ROT_TYPE.NEAR)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("NUMERA"):SetManpu("MP_SHOCK_L")
    TASK:Regist(subEveJumpSurprise, {
      CH("NUMERA")
    })
  end
  CH("HITOMOSHI3"):WalkTo(SymPos("P00_HITOMOSHI3"), Speed(2))
  CH("HITOMOSHI3"):WaitMove()
  CH("HITOMOSHI"):DirTo(CH("NUMERA"), Speed(500), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_HITOMOSHI_ODOSU"))
  CH("HITOMOSHI3"):SetMotion(SymMot("DOUBLE"), LOOP.OFF)
  TASK:Regist(taskNumera00)
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI3"), 816289178)
  CH("HITOMOSHI3"):WaitPlayMotion()
  CH("HITOMOSHI3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -204439235)
  WINDOW:CloseMessage()
  CH("HITOMOSHI3"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI3"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("HITOMOSHI3")
  })
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI3"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("HITOMOSHI3"), -355749764)
  subEveCloseMsg()
  local taskBobobob00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_HITOMOSHI_HONOO_STRONG"))
    CH("HITOMOSHI3"):SetMotion(SymMot("EV009_FIRE00"), LOOP.OFF)
    CH("HITOMOSHI3"):WaitPlayMotion()
    CH("HITOMOSHI3"):SetMotion(SymMot("EV009_FIRE"), LOOP.ON)
  end
  TASK:Regist(taskBobobob00)
  WINDOW:SysMsg(-1041833025)
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.5))
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SWEAT_L")
  CH("HERO"):SetManpu("MP_SWEAT_L")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SWEAT_L")
  CH("NUMERA"):SetManpu("MP_SWEAT_L")
  CH("NYASUPAA"):SetManpu("MP_SWEAT_L")
  CH("NYASUPAA"):WaitManpu()
  TASK:Sleep(TimeSec(0.7))
  CH("HITOMOSHI3"):SetMotion(SymMot("EV009_FIRE02"), LOOP.OFF)
  CH("HITOMOSHI3"):WaitPlayMotion()
  CH("HITOMOSHI3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("HITOMOSHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI"):WaitRotate()
  local taskAll03 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll03)
  WINDOW:DrawFace(72, 16, SymAct("HITOMOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI"), -654454018)
  WINDOW:Talk(SymAct("HITOMOSHI"), -1749269447)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_FLY_SWEAT")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1901628040)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("HITOMOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI"), -1517672773)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("HITOMOSHI3"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(0, 15)
  WINDOW:Talk(SymAct("HITOMOSHI3"), -1131341830)
  subEveCloseMsg()
  TASK:Regist(taskAll01)
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI2"), 990448437)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI4"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI4"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(0, 10)
  WINDOW:Talk(SymAct("HITOMOSHI4"), 571619956)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HITOMOSHI"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI"):WaitRotate()
  CH("YUNIRAN"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(taskAll03)
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI"), 1265428056)
  WINDOW:Talk(SymAct("HITOMOSHI"), 1383585561)
  WINDOW:Talk(SymAct("HITOMOSHI"), 2035975386)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_08"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  local taskAll04 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):DirTo(CH("HITOMOSHI3"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("HITOMOSHI3"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("HITOMOSHI3"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("HITOMOSHI3"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI3"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll04)
  CH("HITOMOSHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("YUNIRAN"):DirTo(CH("HITOMOSHI3"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI3"), 1614919067)
  WINDOW:Talk(SymAct("HITOMOSHI3"), 788538204)
  subEveCloseMsg()
  CH("HITOMOSHI"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI")
  })
  WINDOW:DrawFace(72, 16, SymAct("HITOMOSHI"), FACE_TYPE.GLADNESS)
  WINDOW:DrawFaceOffset(-25, 0)
  WINDOW:Talk(SymAct("HITOMOSHI"), 907743773)
  WINDOW:CloseMessage()
  CH("HITOMOSHI"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI3")
  })
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI3"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("HITOMOSHI3"), 490095070)
  WINDOW:Talk(SymAct("HITOMOSHI3"), 70086815)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"))
  CH("HITOMOSHI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("HITOMOSHI2"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("HITOMOSHI"):SetManpu("MP_SPREE_LP")
  CH("HITOMOSHI2"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI4")
  })
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SWEAT_L")
  CH("HERO"):SetManpu("MP_SWEAT_L")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SWEAT_L")
  CH("NUMERA"):SetManpu("MP_SWEAT_L")
  CH("NYASUPAA"):SetManpu("MP_SWEAT_L")
  CH("NYASUPAA"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI2")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI3")
  })
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -2085262256)
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(0.5))
  CH("HITOMOSHI"):ResetManpu()
  CH("HITOMOSHI"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI2"):ResetFacialMotion()
  CH("HITOMOSHI2"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI3"):ResetFacialMotion()
  CH("HITOMOSHI3"):ResetManpu()
  CH("HITOMOSHI4"):ResetFacialMotion()
  CH("HITOMOSHI4"):ResetManpu()
  CH("YUNIRAN"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1699848943)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Talk(SymAct("NYASUPAA"), 319813134)
  WINDOW:Talk(SymAct("NYASUPAA"), 169133903)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI3"):WaitManpu()
  TASK:Regist(taskAll03)
  CH("YUNIRAN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 20, SymAct("HITOMOSHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HITOMOSHI"), 557421708)
  SOUND:FadeOutBgm(TimeSec(1.5))
  WINDOW:Talk(SymAct("HITOMOSHI"), 941794765)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI3"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI3"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HITOMOSHI3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:DrawFace(20, 20, SymAct("HITOMOSHI"), FACE_TYPE.PAIN)
  WINDOW:DrawFaceOffset(50, 0)
  WINDOW:Talk(SymAct("HITOMOSHI"), 2002989834)
  WINDOW:Talk(SymAct("HITOMOSHI"), 1853358667)
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1163219336, PARTNER_1 = 1548640457})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI2"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI2"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI4"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI4"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HITOMOSHI4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Regist(taskAll01)
  CH("YUNIRAN"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI2"), FACE_TYPE.PAIN)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Talk(SymAct("HITOMOSHI2"), -606700538)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI4")
  })
  WINDOW:DrawFace(324, 88, SymAct("HITOMOSHI4"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("HITOMOSHI4"), -1026732729)
  WINDOW:Talk(SymAct("HITOMOSHI4"), -1414295189)
  WINDOW:Talk(SymAct("HITOMOSHI4"), -1297571798)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1719274519, PARTNER_1 = -2137079128})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HITOMOSHI"):ResetFacialMotion()
  CH("HITOMOSHI2"):ResetFacialMotion()
  CH("HITOMOSHI3"):ResetFacialMotion()
  CH("HITOMOSHI4"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_EXCLAMATION")
  CH("HITOMOSHI2"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI3"):SetManpu("MP_EXCLAMATION")
  CH("HITOMOSHI4"):SetManpu("MP_EXCLAMATION")
  local taskAll05 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll05)
  CH("YUNIRAN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -807447441)
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -691772114)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_03"), Volume(256))
  CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -35047699, PARTNER_1 = -453900372})
  WINDOW:SwitchTalk({PARTNER_0 = 1667898211, PARTNER_1 = 2054236706})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1942821996, PARTNER_1 = 1792421165})
  WINDOW:SwitchTalk({PARTNER_0 = 1107001070, PARTNER_1 = 1491095471})
  WINDOW:SwitchTalk({PARTNER_0 = 396482920, PARTNER_1 = 247130153})
  WINDOW:SwitchTalk({PARTNER_0 = 630701034, PARTNER_1 = 1015843499})
  WINDOW:SwitchTalk({PARTNER_0 = -1156278684, PARTNER_1 = -1576032475})
  subEveCloseMsg()
  local taskAll06 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll06)
  CH("YUNIRAN"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -881755383)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -764786104)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  local taskAll07 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("SHIKIJIKA_SPRING"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll07)
  CH("YUNIRAN"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -112780917)
  WINDOW:Talk(SymAct("NYASUPAA"), -530831158)
  WINDOW:Talk(SymAct("NYASUPAA"), -1357005299)
  WINDOW:Talk(SymAct("NYASUPAA"), -1241084084)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1658069873, PARTNER_1 = -2077168178})
  subEveCloseMsg()
  local taskAll08 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll08)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), 61403393)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NUMERA"), 447987776)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -641411865, PARTNER_1 = -1059068506})
  WINDOW:CloseMessage()
  CH("NUMERA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):WaitRotate()
  local taskAll09 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskAll09)
  CH("YUNIRAN"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), -336415131)
  WINDOW:Talk(SymAct("NUMERA"), -219576540)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(-1113058845)
  WINDOW:Monologue(-1531764574)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1885441183, PARTNER_1 = -1769651680})
  subEveCloseMsg()
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  TASK:Regist(taskAll06)
  CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.RELIEF)
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.RELIEF)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 287137519)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 134639534)
  WINDOW:KeyWait()
  CH("SHIKIJIKA_SPRING"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1635300226)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 2019787459, PARTNER_1 = 1397674240})
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = 1247141953, PARTNER_1 = 85227142})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(72, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 470763463)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI2"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 924980228)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI3"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI3"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI2"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI2"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI4"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  CH("HITOMOSHI4"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HITOMOSHI3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HITOMOSHI2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HITOMOSHI4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI2"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("HITOMOSHI2"), 775497029)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI4")
  })
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI4"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(0, 15)
  WINDOW:Talk(SymAct("HITOMOSHI4"), -1449051766)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), -1329985333)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI2"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI2"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("HITOMOSHI2"), -55604421)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("HITOMOSHI4")
  })
  WINDOW:DrawFace(324, 20, SymAct("HITOMOSHI4"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(0, 15)
  WINDOW:Talk(SymAct("HITOMOSHI4"), -441140614)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -828773959)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -679290632)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):WaitManpu()
  WINDOW:DrawFace(72, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1732030913)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -2116518018)
  WINDOW:Talk(SymAct("NUMERA"), -1426772803)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI"):ResetFacialMotion()
  CH("HITOMOSHI2"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI3"):ResetFacialMotion()
  CH("HITOMOSHI4"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HITOMOSHI"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI2"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI3"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):SetManpu("MP_FLY_SWEAT")
  CH("HITOMOSHI"):WaitManpu()
  TASK:Regist(taskAll00)
  WINDOW:DrawFace(20, 20, SymAct("HITOMOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI"), -1276240388)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  CH("YUNIRAN"):DirTo(CH("HITOMOSHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HITOMOSHI"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HITOMOSHI2"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI3"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI4"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  CH("HITOMOSHI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HITOMOSHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HITOMOSHI"), 880148787)
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("YUNIRAN")
  })
  WINDOW:DrawFace(324, 20, SymAct("YUNIRAN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YUNIRAN"), 762130546)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_11"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("YUNIRAN"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("YUNIRAN"), Speed(350), ROT_TYPE.NEAR)
  CH("YUNIRAN"):WaitRotate()
  CAMERA:WaitMove()
  EFFECT:Create("effectWhiteOut", SymEff("EV_LUMINOUS_PINK"))
  EFFECT:SetPosition("effectWhiteOut", SymPos("P_EFF_WHITE"))
  EFFECT:Play("effectWhiteOut")
  SOUND:PlaySe(SymSnd("SE_EVT_PHYCHO_POWER"))
  TASK:Sleep(TimeSec(2))
  SOUND:PlaySe(SymSnd("SE_EVT_CHANGE"))
  SCREEN_A:WhiteOut(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.5))
end
function main09_inisienohoneatobosswin01_5_end()
end
function main09_inisienohoneatobosswin02_init()
end
function main09_inisienohoneatobosswin02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("YANCHAMU"):SetScale(Scale(0, 4, 0))
  CH("CHOBOMAKI"):SetScale(Scale(0, 4, 0))
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.SLEEP)
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.SLEEP)
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:Create("effectBarrier01", SymEff("EV_BARRIER_LP"))
  EFFECT:SetPosition("effectBarrier01", SymPos("P_EFF_BARRIER01"))
  EFFECT:Create("effectBarrier02", SymEff("EV_BARRIER_LP"))
  EFFECT:SetPosition("effectBarrier02", SymPos("P_EFF_BARRIER02"))
  SOUND:PlaySe(SymSnd("SE_EVT_RELEASE"))
  EFFECT:Play("effectBarrier01")
  EFFECT:Play("effectBarrier02")
  CH("YANCHAMU"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  CH("CHOBOMAKI"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1.5))
  EFFECT:ChangeColor("effectBarrier01", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectBarrier02", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  EFFECT:Create("effectBarrierEnd01", SymEff("EV_BARRIER_END"))
  EFFECT:SetPosition("effectBarrierEnd01", SymPos("P_EFF_BARRIER01"))
  EFFECT:Create("effectBarrierEnd02", SymEff("EV_BARRIER_END"))
  EFFECT:SetPosition("effectBarrierEnd02", SymPos("P_EFF_BARRIER02"))
  EFFECT:Play("effectBarrierEnd01")
  EFFECT:Play("effectBarrierEnd02")
  TASK:Sleep(TimeSec(1.2))
  CH("YANCHAMU"):MoveHeightTo(Height(0), Speed(0.5))
  CH("CHOBOMAKI"):MoveHeightTo(Height(0), Speed(0.5))
  TASK:Sleep(TimeSec(2))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ODAYAKA_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("YANCHAMU"):WaitMoveHeight()
  TASK:Sleep(TimeSec(0.2))
  CH("YANCHAMU"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_EXCLAMATION")
  CH("CHOBOMAKI"):SetManpu("MP_EXCLAMATION")
  CH("CHOBOMAKI"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  local taskYanchamu00 = function()
    CH("YANCHAMU"):RunTo(SymPos("P01_YANCHAMU"), Speed(3))
    CH("YANCHAMU"):WaitMove()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT_LP")
    CH("YANCHAMU"):SetMotion(SymMot("EV009_CRY00"), LOOP.OFF)
    CH("YANCHAMU"):WaitPlayMotion()
    CH("YANCHAMU"):SetMotion(SymMot("EV009_CRY01"), LOOP.ON)
  end
  local taskChobomaki00 = function()
    CH("CHOBOMAKI"):RunTo(SymPos("P01_CHOBOMAKI"), Speed(3))
    CH("CHOBOMAKI"):WaitMove()
    CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT_LP")
    CH("CHOBOMAKI"):SetMotion(SymMot("EV009_CRY00"), LOOP.OFF)
    CH("CHOBOMAKI"):WaitPlayMotion()
    CH("CHOBOMAKI"):SetMotion(SymMot("EV009_CRY01"), LOOP.ON)
  end
  TASK:Regist(taskYanchamu00)
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(taskChobomaki00)
  TASK:Sleep(TimeSec(0.1))
  CH("HITOMOSHI"):DirTo(SymPos("P01_YANCHAMU"), Speed(200), ROT_TYPE.NEAR)
  CH("HITOMOSHI2"):DirTo(SymPos("P01_CHOBOMAKI"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
  CH("NUMERA"):WalkTo(SymPos("P00_NUMERA"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(2))
  CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(2))
  TASK:WaitTask()
  WINDOW:DrawFace(72, 16, SymAct("YANCHAMU"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("YANCHAMU"), 1142156382)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("CHOBOMAKI"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1560861983)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1982172892, PARTNER_1 = 1866383261})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 545204570)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
end
function main09_inisienohoneatobosswin02_end()
end
function main09_inisienohoneatobosswin03_init()
end
function main09_inisienohoneatobosswin03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ODAYAKA_02"), Volume(256))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 962861083)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 306793432)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 189954713)
  WINDOW:KeyWait()
  SOUND:FadeOutBgm(TimeSec(2))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1932892586)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_DOTEKKOTSU"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), -1781442793)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main09_inisienohoneatobosswin03_end()
end
function main09_inisienohoneatobosswin04_init()
end
function main09_inisienohoneatobosswin04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisibleMaterial("s_shadow_mat", false)
  MAP:SetVisibleMaterial("saucer00_mat", false)
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CH("ABAGOORA"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(272, 16, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), 1453736880)
  WINDOW:Talk(SymAct("ABAGOORA"), 1337815793)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  CH("KONOHANA"):DirTo(CH("ABAGOORA"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("KONOHANA"), 1687167282)
  WINDOW:CloseMessage()
  CH("ABAGOORA"):ResetManpu()
  CH("KONOHANA"):ResetFacialMotion()
  CH("ABAGOORA"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("ABAGOORA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("ABAGOORA")
  })
  WINDOW:DrawFace(272, 16, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), 2106265715)
  WINDOW:KeyWait()
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:Talk(SymAct("ABAGOORA"), 852133556)
  WINDOW:Talk(SymAct("ABAGOORA"), 735164405)
  WINDOW:CloseMessage()
  CH("ABAGOORA"):ResetManpu()
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 16573494, PARTNER_1 = 434623863})
  WINDOW:CloseMessage()
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("HERO"):WaitNeckRot()
  CH("ABAGOORA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("ABAGOORA"):WaitRotate()
  CH("KONOHANA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1635792456, PARTNER_1 = -2023425799})
  WINDOW:SwitchTalk({PARTNER_0 = -300276523, PARTNER_1 = -150923884})
  WINDOW:SwitchTalk({PARTNER_0 = -601078185, PARTNER_1 = -986220778})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP00"), LOOP.OFF)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON)
  CH("PARTNER"):SetManpu("MP_SLEEP_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("ABAGOORA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(272, 16, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), -1971920431)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_ANGRY_LP")
  CH("ABAGOORA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  TASK:Regist(subEveDoubleJump, {
    CH("ABAGOORA")
  })
  WINDOW:Talk(SymAct("ABAGOORA"), -1821519728)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("ABAGOORA"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SwitchTalk({PARTNER_0 = -1203731629, PARTNER_1 = -1587826158})
  WINDOW:CloseMessage()
  CH("KONOHANA"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(272, 16, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), 650358493)
  WINDOW:Talk(SymAct("ABAGOORA"), 1071161244)
  WINDOW:CloseMessage()
  CH("ABAGOORA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("ABAGOORA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("ABAGOORA"):SetManpu("MP_ANGRY_LP")
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("ABAGOORA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(72, 16, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(25, 0)
  WINDOW:Talk(SymAct("ABAGOORA"), -1233570685)
  WINDOW:CloseMessage()
  CH("ABAGOORA"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1352530494)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("ABAGOORA")
  })
  WINDOW:DrawFace(72, 16, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(25, 0)
  WINDOW:Talk(SymAct("ABAGOORA"), -2075175423)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.1))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(-1655412928)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.1))
  CH("ABAGOORA"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(72, 16, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(25, 0)
  WINDOW:Talk(SymAct("ABAGOORA"), -770313849)
  WINDOW:Talk(SymAct("ABAGOORA"), -888225594)
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main09_inisienohoneatobosswin04_end()
end
function main09_inisienohoneatobosswin05_init()
end
function main09_inisienohoneatobosswin05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:DrawFace(20, 88, SymAct("ABAGOORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("ABAGOORA"), -534539515)
  WINDOW:Talk(SymAct("ABAGOORA"), -113728956)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 2124463755)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1740345290)
  SOUND:FadeOutBgm(TimeSec(1.5))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 247813094)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(1.5))
end
function main09_inisienohoneatobosswin05_end()
end
function groundEnd()
end
