dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_kimodameshi01_init()
end
function main09_kimodameshi01_start()
end
function main09_kimodameshi01_end()
end
function main09_kimodameshi02_init()
end
function main09_kimodameshi02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(2.5))
  CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("PARTNER"):SetEyeMotion(EYE_MOTION.SAD)
  CH("PARTNER"):SetMouthMotion(MOUTH_MOTION.ANGRY)
  MAP:SetVisibleMaterial("m_tw00_all_night_light0", false)
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.7))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(SymPos("P00_IE"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-108229355)
  subEveCloseMsg()
  WINDOW:SwitchTalk({PARTNER_0 = -526926764, PARTNER_1 = -876941417})
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:CloseMessage()
  CH("HERO"):RunTo(SymPos("P03_HERO"), Speed(2.5))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-761143594)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1646245871, PARTNER_1 = -2063894192})
  WINDOW:SwitchTalk({PARTNER_0 = -1344918893, PARTNER_1 = -1228071982})
  WINDOW:SwitchTalk({PARTNER_0 = 827655965, PARTNER_1 = 676214364})
  WINDOW:SwitchTalk({PARTNER_0 = -2103467156, PARTNER_1 = -1685810643})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir2, {
    CH("HERO"),
    SymPos("P04_HERO"),
    Speed(1.5),
    SymPos("P04_HERO")
  })
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:WaitTask()
  local taskHero00 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("HERO"):SetManpu("MP_NOTICE_L")
    CH("HERO"):WaitManpu()
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  TASK:Regist(taskHero00)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetEyeMotion(EYE_MOTION.NORMAL)
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1331052050, PARTNER_1 = -1447890769})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir2, {
    CH("HERO"),
    SymPos("P05_HERO"),
    Speed(1.2),
    SymPos("P05_HERO")
  })
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):SetEyeMotion(EYE_MOTION.SAD)
  CH("PARTNER"):SetMouthMotion(MOUTH_MOTION.ANGRY)
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.2))
  TASK:Sleep(TimeSec(1.5))
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main09_kimodameshi02_end()
end
function main09_kimodameshi03_init()
end
function main09_kimodameshi03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  elseif pokemonIndexHero == 5 then
    CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  elseif pokemonIndexHero == 322 then
    CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  elseif pokemonIndexHero == 10 then
    CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  else
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  end
  local taskPartner00 = function()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  end
  TASK:Regist(taskPartner00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):SetManpu("MP_NOTICE_L")
  CH("NUMERA"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  CH("HERO"):WaitMove()
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("YANCHAMU"), -420256152)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_NOTICE_R")
  WINDOW:Talk(SymAct("YANCHAMU"), -1550551)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:Talk(SymAct("YANCHAMU"), -725285654)
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.5))
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -841075285, PARTNER_1 = 1246112100})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("YANCHAMU"), 1398609957)
  WINDOW:Talk(SymAct("YANCHAMU"), -1876292478)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main09_kimodameshi03_end()
end
function main09_kimodameshi04_init()
end
function main09_kimodameshi04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SAJI:CreateSajiPlayer("kage_01", "EV09_050_04_01")
  SAJI:CreateSajiPlayer("kage_02", "EV09_050_04_02")
  SAJI:CreateSajiPlayer("kage_03", "EV09_050_04_03")
  SJ("kage_01"):ChangeAlpha(0, TimeSec(0))
  SJ("kage_02"):SetVisible(false)
  SJ("kage_03"):SetVisible(false)
  SJ("kage_01"):SetPosition(Vector2(200, 120))
  SJ("kage_02"):SetPosition(Vector2(200, 120))
  SJ("kage_03"):SetPosition(Vector2(200, 120))
  SJ("kage_01"):SetDrawPriority(1024)
  SJ("kage_02"):SetDrawPriority(1024)
  SJ("kage_03"):SetDrawPriority(1024)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1993261629)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1575195136)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("YANCHAMU"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CAMERA:WaitMove()
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("SHIKIJIKA_SPRING"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -1157144767)
  WINDOW:Talk(SymAct("YANCHAMU"), -196687482)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("CHOBOMAKI")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -312608569)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -965694716, PARTNER_1 = -546596283})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 1492354698)
  WINDOW:Talk(SymAct("YANCHAMU"), 1105770443)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("CHOBOMAKI")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 680946663, PARTNER_1 = 831347366})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("YANCHAMU"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(172, 8, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 446695781)
  WINDOW:Talk(SymAct("YANCHAMU"), 62601252)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1291497187)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 1440849826, PARTNER_1 = 2127350881})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("YANCHAMU"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("YANCHAMU"):SetManpu("MP_SPREE_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(10, 0)
  WINDOW:Talk(SymAct("YANCHAMU"), 1742208288)
  WINDOW:Talk(SymAct("YANCHAMU"), -531635729)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CH("YANCHAMU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  if pokemonIndexPartner == 10 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 30 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 203 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 322 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 485 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 537 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 592 then
    CH("PARTNER"):SetPosition(SymPos("SP01_PARTNER"))
  elseif pokemonIndexPartner == 598 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 766 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  end
  local taskPartner00 = function()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    CH("PARTNER"):SetManpu("MP_SHOCK_R")
    CH("PARTNER"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("EV001_DOWN00"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON)
  end
  TASK:Regist(taskPartner00)
  local taskOdoroku = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("NUMERA"):SetManpu("MP_SHOCK_R")
    CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
    CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskOdoroku)
  SOUND:PlaySe(SymSnd("SE_EVT_GYAAAA"))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -111882066, PARTNER_1 = -1254010018})
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), -1403362785)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SWEAT_L")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFaceF(172, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -2022231588)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("CHOBOMAKI"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1637089123)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("NYASUPAA"), FACE_TYPE.SAD)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:Talk(SymAct("NYASUPAA"), -785541542)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -935942373)
  WINDOW:Talk(SymAct("YANCHAMU"), -484707112)
  subEveCloseMsg()
  SOUND:FadeOutBgm(TimeSec(0.5))
  local taskNotice00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("CHOBOMAKI"):SetManpu("MP_NOTICE_L")
    TASK:Sleep(TimeSec(0.1))
    CH("YANCHAMU"):SetManpu("MP_NOTICE_L")
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
    CH("NYASUPAA"):SetManpu("MP_NOTICE_L")
    CH("HERO"):ResetFacialMotion()
    CH("HERO"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskNotice00)
  local taskObake00 = function()
    EFFECT:StartMotionBlur(0, 0, 0)
    EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.4))
    EFFECT:ChangeMotionBlurAlpha(0.5, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.5))
    EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.4))
    EFFECT:EndMotionBlur()
  end
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(-100612711)
  TASK:WaitTask()
  subEveCloseMsg()
  CH("YANCHAMU"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 2107169110)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("YANCHAMU"), 1686366231)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  WINDOW:DrawFace(72, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 234697787)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 350619002)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(1070290617)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  local taskSurprise00 = function()
    CH("CHOBOMAKI"):SetManpu("MP_SHOCK_R")
    CH("YANCHAMU"):SetManpu("MP_EXCLAMATION")
    TASK:Regist(subEveJumpSurprise, {
      CH("CHOBOMAKI")
    })
    TASK:Sleep(TimeSec(0.2))
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_R")
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):SetManpu("MP_SHOCK_R")
    CH("NUMERA"):WaitManpu()
    CH("HERO"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("CHOBOMAKI"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    CH("YANCHAMU"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  end
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  TASK:Regist(taskSurprise00)
  TASK:Sleep(TimeSec(0.7))
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 651192312)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_02"), Volume(256))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1771172159)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:Talk(SymAct("NYASUPAA"), 1888141438)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("CHOBOMAKI"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NUMERA"), 1537708989)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  CH("NYASUPAA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1119658748)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(-987447757)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  local taskShikijika00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
    subEveLookAround(CH("SHIKIJIKA_SPRING"), Speed(600))
  end
  local taskNyasupaa00 = function()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("NYASUPAA"), Speed(600))
  end
  local taskHero00 = function()
    TASK:Sleep(TimeSec(0.4))
    subEveLookAround(CH("HERO"), Speed(600))
  end
  TASK:Regist(taskShikijika00)
  TASK:Regist(taskNyasupaa00)
  TASK:Regist(taskHero00)
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -599814286)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_HONOO_ENTRY"))
  EFFECT:Create("effectFire01", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire01", SymPos("P_EFF_FIRE_01"))
  EFFECT:Play("effectFire01")
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("YANCHAMU"):SetManpu("MP_SHOCK_L")
  CAMERA:MoveFollow2(SymCam("CAMERA_10"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P_EFF_FIRE_01"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(SymPos("P_EFF_FIRE_01"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P_EFF_FIRE_01"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("NYASUPAA"):DirTo(SymPos("P_EFF_FIRE_01"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), 524852181)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 106146452)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_HONOO_ENTRY"))
  EFFECT:Create("effectFire02", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire02", SymPos("P_EFF_FIRE_02"))
  EFFECT:Play("effectFire02")
  TASK:Sleep(TimeSec(0.3))
  CH("YANCHAMU"):SetManpu("MP_EXCLAMATION")
  CH("YANCHAMU"):DirTo(SymPos("P_EFF_FIRE_02"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskNyasupaa00)
  SOUND:PlaySe(SymSnd("SE_EVT_HONOO_ENTRY"))
  EFFECT:Create("effectFire03", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire03", SymPos("P_EFF_FIRE_03"))
  EFFECT:Play("effectFire03")
  TASK:Sleep(TimeSec(0.3))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_R")
  CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P_EFF_FIRE_03"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskShikijika00)
  SOUND:PlaySe(SymSnd("SE_EVT_HONOO_ENTRY"))
  EFFECT:Create("effectFire04", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire04", SymPos("P_EFF_FIRE_04"))
  EFFECT:Play("effectFire04")
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):DirTo(SymPos("P_EFF_FIRE_04"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.1))
  local taskNumera00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("NUMERA"):SetManpu("MP_SHOCK_R")
    CH("NUMERA"):SetMotionRaito(Raito(2))
    CH("NUMERA"):SetMotion(SymMot("EV002_CRY"), LOOP.OFF)
    CH("NUMERA"):WaitPlayMotion()
    CH("NUMERA"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
    CH("NUMERA"):WaitPlayMotion()
    CH("NUMERA"):SetMotionRaito(Raito(1))
    CH("NUMERA"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  end
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NUMERA"), 763296087)
  WINDOW:KeyWait()
  TASK:Regist(taskNumera00)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("NUMERA"), 879085590)
  CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:CloseMessage()
  local taskSurprise01 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_L")
    CH("YANCHAMU"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.2))
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):SetManpu("MP_SHOCK_R")
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("YANCHAMU"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskSurprise01)
  WINDOW:DrawFace(324, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(0, -8)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 2065981137)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  local taskChobomaki00 = function()
    CH("CHOBOMAKI"):SetManpu("MP_SHOCK_L")
    CH("CHOBOMAKI"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    CH("CHOBOMAKI"):WaitPlayMotion()
    CH("CHOBOMAKI"):SetMotionRaito(Raito(2))
    CH("CHOBOMAKI"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
    CH("CHOBOMAKI"):WaitPlayMotion()
    CH("CHOBOMAKI"):SetMotionRaito(Raito(1))
    CH("CHOBOMAKI"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  end
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1648324496)
  WINDOW:KeyWait()
  TASK:Regist(taskChobomaki00)
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1225931859)
  local taskSurprise02 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("YANCHAMU"):SetManpu("MP_SHOCK_L")
    TASK:Sleep(TimeSec(0.1))
    CH("YANCHAMU"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    CH("NYASUPAA"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskSurprise02)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), 1342770450)
  WINDOW:Talk(SymAct("YANCHAMU"), -678358563)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:Talk(SymAct("YANCHAMU"), -829808484)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_11"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  subEveLookAround(CH("YANCHAMU"), Speed(600))
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):WaitManpu()
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("YANCHAMU"), -1477116752)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("YANCHAMU"), -1091580431)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"), Volume(256))
  MAP:ChangeLightColor(Color(0.5, 0.5, 0.5, 1), TimeSec(0.5))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("YANCHAMU"):SetManpu("MP_EXCLAMATION")
  CH("YANCHAMU"):WaitManpu()
  subEveLookAround02(CH("YANCHAMU"), Speed(600))
  WINDOW:SysMsg(-1782407630)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_SHOCK_R")
  CH("YANCHAMU"):WaitManpu()
  TASK:Regist(taskShikijika00)
  TASK:Regist(taskNyasupaa00)
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.1))
  subEveLookAround(CH("YANCHAMU"), Speed(600))
  TASK:Sleep(TimeSec(0.4))
  WINDOW:SysMsg(-1931890829)
  WINDOW:SysMsg(-1013433932)
  WINDOW:CloseMessage()
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(taskShikijika00)
  TASK:Regist(taskNyasupaa00)
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.1))
  CH("YANCHAMU"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CH("YANCHAMU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("YANCHAMU"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("YANCHAMU"):SetManpu("MP_SHOCK_L")
  CH("YANCHAMU"):DirTo(SymPos("P02_SHADOW"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CH("NYASUPAA"):DirTo(SymPos("P02_SHADOW"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), -628946699)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CAMERA:SetFovy(SymCam("CAMERA_13"))
  CAMERA:MoveFollow2(SymCam("CAMERA_13_5"), Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SJ("kage_01"):Play(LOOP.ON)
  SJ("kage_01"):ChangeAlpha(1, TimeSec(0.5))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P02_SHADOW"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P02_SHADOW"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-240231626)
  TASK:WaitTask()
  WINDOW:SysMsg(-390763913)
  WINDOW:SysMsg(1865250488)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"), Volume(256))
  SJ("kage_02"):SetVisible(true)
  SJ("kage_02"):Play(LOOP.OFF)
  SAJI:DestroySajiPlayer("kage_01")
  SJ("kage_02"):WaitEnd()
  SJ("kage_03"):SetVisible(true)
  SJ("kage_03"):Play(LOOP.ON)
  SAJI:DestroySajiPlayer("kage_02")
  subEveFlash2()
  SOUND:FadeOutEnv(TimeSec(0.5))
  SCREEN_A:FadeOutAll(TimeSec(0.1), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  SCREEN_A:FadeOut(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(0), true)
  SOUND:PlaySe(SymSnd("SE_EVT_GYAAAA"))
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), 1983268857)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  SAJI:DestroySajiPlayer("kage_03")
  MAP:ReturnLightColor(TimeSec(0, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(4))
end
function main09_kimodameshi04_end()
end
function groundEnd()
end
