dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main24_hajimarinomoriboss2nd01_init()
end
function main24_hajimarinomoriboss2nd01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  CH("OOBEMU"):SetShadowOnlyMode(true)
  CH("KONOHANA"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CH("IBERUTARU"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CH("OOBEMU2"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CH("OOBEMU3"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CH("OOBEMU"):SetMotion(SymMot("EV022_DOWN00"), LOOP.ON, TimeSec(0))
  CH("IBERUTARU"):SetScale(Scale(1.2))
  EFFECT:Create("effectNihilAuraLPIberutaru", SymEff("EV_NIHIL_AURA_LP"))
  EFFECT:SetPosition("effectNihilAuraLPIberutaru", SymPos("P_EFF_IBERUTARU"))
  EFFECT:SetScale("effectNihilAuraLPIberutaru", Scale(3))
  EFFECT:Play("effectNihilAuraLPIberutaru")
  EFFECT:Create("effectNihilAuraLPIKonohana", SymEff("EV_NIHIL_AURA_LP"))
  EFFECT:SetPosition("effectNihilAuraLPIKonohana", SymPos("P_EFF_KONOHANA"))
  EFFECT:Play("effectNihilAuraLPIKonohana")
  EFFECT:Create("effectNihilAuraLPIOobemu02", SymEff("EV_NIHIL_AURA_LP"))
  EFFECT:SetPosition("effectNihilAuraLPIOobemu02", SymPos("P_EFF_OOBEMU02"))
  EFFECT:Play("effectNihilAuraLPIOobemu02")
  EFFECT:Create("effectNihilAuraLPIOobemu03", SymEff("EV_NIHIL_AURA_LP"))
  EFFECT:SetPosition("effectNihilAuraLPIOobemu03", SymPos("P_EFF_OOBEMU03"))
  EFFECT:Play("effectNihilAuraLPIOobemu03")
  SOUND:FadeInEnv(SymSnd("SE_EVT_SHADOW_BIND_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("KONOHANA"), -1352767321)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07_5"))
  CAMERA:SetTgt(SymCam("CAMERA_07_5"))
  CAMERA:SetFovy(SymCam("CAMERA_07_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("IBERUTARU"), -1236968986)
  WINDOW:CloseMessage()
  SOUND:VolumeEnv(Volume(190), TimeSec(0.5))
  GM("STONE_OOBEMU"):SetScale(Scale(0.7))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:SetRotateZ(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("JIRAACHI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("DENRYUU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("SEREBII"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), -1654126043)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), -2072822940)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_IBERUTARU"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:SetRotateZ(SymCam("CAMERA_07"))
  local taskIberutaru00 = function()
    CH("IBERUTARU"):SetMotion(SymMot("EV024_ROAR00"), LOOP.OFF)
    CH("IBERUTARU"):WaitPlayMotion()
    CH("IBERUTARU"):SetMotion(SymMot("EV024_ROAR01"), LOOP.ON)
  end
  TASK:Regist(taskIberutaru00)
  EFFECT:ChangeColor("effectNihilAuraLPIberutaru", Color(1, 1, 1, 0), TimeSec(20, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectNihilAuraLPIKonohana", Color(1, 1, 1, 0), TimeSec(20, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectNihilAuraLPIOobemu02", Color(1, 1, 1, 0), TimeSec(20, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectNihilAuraLPIOobemu03", Color(1, 1, 1, 0), TimeSec(20, TIME_TYPE.FRAME))
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_GIRATYINA_DEATHCRY"), Volume(256))
  WINDOW:SysMsg(-885871197)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
  EFFECT:EndMotionBlur()
  EFFECT:Remove("effectNihilAuraLPIberutaru")
  EFFECT:Remove("effectNihilAuraLPIKonohana")
  EFFECT:Remove("effectNihilAuraLPIOobemu02")
  EFFECT:Remove("effectNihilAuraLPIOobemu03")
  CH("IBERUTARU"):SetMotion(SymMot("EV000_WAIT02"), LOOP.ON, TimeSec(0.5))
  CH("KONOHANA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  CH("OOBEMU2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  CH("OOBEMU3"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("JIRAACHI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("DENRYUU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("SEREBII"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), -769024798)
  WINDOW:CloseMessage()
  subEveFlash2()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  MAP:ReturnLightColor(TimeSec(0, TIME_TYPE.FRAME))
  SYSTEM:SetNextDungeonBanner(false)
end
function main24_hajimarinomoriboss2nd01_end()
end
function groundEnd()
end
