dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main19_iberutarunokeikoku01_init()
end
function main19_iberutarunokeikoku01_start()
  CUT:Load(SymCut("m19_010_01"))
  local taskSe00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_BLACK_SPREAD_LP"), Volume(256))
    TASK:Sleep(TimeSec(1))
    SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_JUUDEN_02_LP"), Volume(128))
  end
  TASK:Regist(taskSe00)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main19_iberutarunokeikoku01_cut_script_01()
  SOUND:FadeOutSe(SymSnd("SE_EVT_BLACK_SPREAD_LP"), TimeSec(1))
  SOUND:FadeOutSe(SymSnd("SE_EVT_DEDENNE_JUUDEN_02_LP"), TimeSec(1))
end
function main19_iberutarunokeikoku01_end()
end
function main19_iberutarunokeikoku02_init()
end
function main19_iberutarunokeikoku02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("YAMIKARASU_TOWN"):SetManpu("MP_SPREE_LP")
  CH("YAMIKARASU_TOWN"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("NOZUPASU"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("BURUU"):SetManpu("MP_LAUGH_LP")
  CH("KOROBOOSHI"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("MASSUGUMA")
  })
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"), Volume(256))
  SCREEN_A:FadeChange(Level(0), Level(0.6), TimeSec(0.7), true)
  TASK:Sleep(TimeSec(0.2))
  CH("KOROBOOSHI"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("YAMIKARASU_TOWN"):ResetManpu()
  CH("YAMIKARASU_TOWN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("NOZUPASU"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("BURUU"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("KAKUREON"):SetManpu("MP_EXCLAMATION")
  CH("YAMIKARASU_TOWN"):SetManpu("MP_EXCLAMATION")
  CH("NOZUPASU"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.2))
  CH("BURUU"):SetManpu("MP_EXCLAMATION")
  CH("KOROBOOSHI"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("MASSUGUMA"):SetManpu("MP_EXCLAMATION")
  CH("BURUU"):WaitManpu()
  CH("YAMIKARASU_TOWN"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("BURUU"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("MASSUGUMA"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOZUPASU"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("KOROBOOSHI"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("NOZUPASU"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CH("DESUKAAN"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KAKUREON"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("YAMIKARASU_TOWN"):SetManpu("MP_QUESTION")
  CH("YAMIKARASU_TOWN"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("YAMIKARASU"), -1827039860)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.5), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku02_end()
end
function main19_iberutarunokeikoku03_init()
end
function main19_iberutarunokeikoku03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HASUBURERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("HIPOPOTASU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KAMONEGI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("RATTA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("ROZERIA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KAKUREON"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HASUBURERO"):SetManpu("MP_QUESTION")
  CH("HASUBURERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HASUBURERO"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("HASUBURERO"), -1979538227)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.5), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku03_end()
end
function main19_iberutarunokeikoku04_init()
end
function main19_iberutarunokeikoku04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("MOROBARERU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("RAKURAI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SUKORUPI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("SUKORUPI"):SetManpu("MP_SHOCK_R")
  CH("RAKURAI"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("MOROBARERU"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("SUKORUPI")
  })
  CH("SUKORUPI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SUKORUPI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SUKORUPI"), -1590692082)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.1), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  WINDOW:Narration(TimeSec(0), TimeSec(0), -1204500913)
  WINDOW:CloseMessage()
end
function main19_iberutarunokeikoku04_end()
end
function main19_iberutarunokeikoku04_5_init()
end
function main19_iberutarunokeikoku04_5_start()
  GM("IBERUTARU_SHADOW"):SetScale(Scale(7.5))
  GM("EFFECT_FREE01"):SetScale(Scale(7.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.05, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SysMsg(-143306616)
  WINDOW:SysMsg(-294755895)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetDefaultGroundFovy()
  EFFECT:EndMotionBlur()
end
function main19_iberutarunokeikoku04_5_end()
end
function main19_iberutarunokeikoku05_init()
end
function main19_iberutarunokeikoku05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("ZEKUROMU"), -985452022)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetDefaultGroundFovy()
end
function main19_iberutarunokeikoku05_end()
end
function main19_iberutarunokeikoku06_init()
end
function main19_iberutarunokeikoku06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:Create("effectBgFireLp", SymEff("EV_16_BG_FIRE_LP"))
  EFFECT:SetPosition("effectBgFireLp", SymPos("P_EFF_EV_16_BG_FIRE_LP"))
  EFFECT:Play("effectBgFireLp")
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("RESHIRAMU"), -598211765)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectBgFireLp")
end
function main19_iberutarunokeikoku06_end()
end
function main19_iberutarunokeikoku07_init()
end
function main19_iberutarunokeikoku07_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("MOROBARERU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("RAKURAI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SUKORUPI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:SysMsg(1539317636)
  WINDOW:SysMsg(1121660613)
  WINDOW:SysMsg(829448444)
  WINDOW:SysMsg(678121917)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("MOROBARERU"):SetManpu("MP_SHOCK_R")
  CH("MOROBARERU"):WaitManpu()
  WINDOW:Talk(SymAct("MOROBARERU"), 54919806)
  TASK:Sleep(TimeSec(0.8))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("SUKORUPI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("SUKORUPI")
  })
  CH("SUKORUPI"):WaitManpu()
  WINDOW:Talk(SymAct("SUKORUPI"), 442315583)
  TASK:Sleep(TimeSec(0.8))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(50, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 88, SymAct("RAKURAI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("RAKURAI"), 1427940856)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku07_end()
end
function main19_iberutarunokeikoku08_init()
end
function main19_iberutarunokeikoku08_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("YAMIKARASU_TOWN"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NOZUPASU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("BURUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KOROBOOSHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("MASSUGUMA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KAKUREON"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DESUKAAN"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KAKUREON"):SetDir(RotateTarget(90))
  CH("DESUKAAN"):SetDir(RotateTarget(90))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:SysMsg(1275565241)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku08_end()
end
function main19_iberutarunokeikoku09_init()
end
function main19_iberutarunokeikoku09_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SAIDON"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("SAIDON2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("SAIDON4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("SAIDON5"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("SAIDON6"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("SAIDON"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SAIDON2"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SAIDON4"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SAIDON6"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  local taskSaidon03 = function()
    CH("SAIDON3"):WalkTo(SymPos("P00_SAIDON3"), Speed(1.5))
    CH("SAIDON3"):WaitMove()
    CH("SAIDON3"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  end
  TASK:Regist(taskSaidon03)
  local taskSaidon05 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("SAIDON5"):DirTo(RotateTarget(-145), Speed(200), ROT_TYPE.NEAR)
    CH("SAIDON5"):WaitRotate()
    CH("SAIDON5"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  end
  TASK:Regist(taskSaidon05)
  local taskSaidon02 = function()
    CH("SAIDON2"):DirTo(RotateTarget(-145), Speed(200), ROT_TYPE.NEAR)
    CH("SAIDON2"):WaitRotate()
    CH("SAIDON2"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  end
  TASK:Regist(taskSaidon02)
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1730856826)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku09_end()
end
function main19_iberutarunokeikoku10_init()
end
function main19_iberutarunokeikoku10_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KINOGASSA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KURUMIRU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("PARASU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("BATAFURII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:SysMsg(2117203515)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku10_end()
end
function main19_iberutarunokeikoku11_init()
end
function main19_iberutarunokeikoku11_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PAUWAU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KUMASHUN"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DERIBAADO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("TSUNBEAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:SysMsg(-106304780)
  WINDOW:SysMsg(-525149259)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku11_end()
end
function main19_iberutarunokeikoku12_init()
end
function main19_iberutarunokeikoku12_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:SysMsg(600166162)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main19_iberutarunokeikoku12_end()
end
function main19_iberutarunokeikoku13_init()
end
function main19_iberutarunokeikoku13_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:SysMsg(987692627)
  WINDOW:CloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  CAMERA:SetDefaultGroundFovy()
end
function main19_iberutarunokeikoku13_end()
end
function main19_iberutarunokeikoku14_init()
end
function main19_iberutarunokeikoku14_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CUT:Load(SymCut("m19_010_14"))
  SOUND:PlaySe(SymSnd("SE_EVT_BLACK_END"), Volume(256))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  TASK:Sleep(TimeSec(0.5))
end
function main19_iberutarunokeikoku14_end()
end
function main19_iberutarunokeikoku15_init()
end
function main19_iberutarunokeikoku15_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 301182352)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 149462225)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1202260502)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1588738903)
  WINDOW:KeyWait()
  SOUND:FadeOutBgm(TimeSec(2.5))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1973381268)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1820613077)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  GM("STONE_PIKACHUU"):SetScale(Scale(1.1))
  GM("STONE_POKABU"):SetScale(Scale(1.1))
  GM("STONE_MIJUMARU"):SetScale(Scale(1.1))
  GM("STONE_TSUTAAJA"):SetScale(Scale(1.1))
  GM("STONE_FUSHIGIDANE"):SetScale(Scale(1.1))
  GM("STONE_HITOKAGE"):SetScale(Scale(1.1))
  GM("STONE_ZENIGAME"):SetScale(Scale(1.1))
  GM("STONE_CHIKORIITA"):SetScale(Scale(1.1))
  GM("STONE_HINOARASHI"):SetScale(Scale(1.1))
  GM("STONE_WANINOKO"):SetScale(Scale(1.1))
  GM("STONE_KIMORI"):SetScale(Scale(1.1))
  GM("STONE_ACHAMO"):SetScale(Scale(1.1))
  GM("STONE_MIZUGOROU"):SetScale(Scale(1.1))
  GM("STONE_NAETORU"):SetScale(Scale(1.1))
  GM("STONE_HIKOZARU"):SetScale(Scale(1.1))
  GM("STONE_POTCHAMA"):SetScale(Scale(1.1))
  GM("STONE_RIORU"):SetScale(Scale(1.1))
  GM("STONE_HARIMARON"):SetScale(Scale(1.1))
  GM("STONE_FOKKO"):SetScale(Scale(1.1))
  GM("STONE_KEROMATSU"):SetScale(Scale(1.1))
  GM("STONE_PIKACHUU_2"):SetScale(Scale(1.1))
  GM("STONE_POKABU_2"):SetScale(Scale(1.1))
  GM("STONE_MIJUMARU_2"):SetScale(Scale(1.1))
  GM("STONE_TSUTAAJA_2"):SetScale(Scale(1.1))
  GM("STONE_FUSHIGIDANE_2"):SetScale(Scale(1.1))
  GM("STONE_HITOKAGE_2"):SetScale(Scale(1.1))
  GM("STONE_ZENIGAME_2"):SetScale(Scale(1.1))
  GM("STONE_CHIKORIITA_2"):SetScale(Scale(1.1))
  GM("STONE_HINOARASHI_2"):SetScale(Scale(1.1))
  GM("STONE_WANINOKO_2"):SetScale(Scale(1.1))
  GM("STONE_KIMORI_2"):SetScale(Scale(1.1))
  GM("STONE_ACHAMO_2"):SetScale(Scale(1.1))
  GM("STONE_MIZUGOROU_2"):SetScale(Scale(1.1))
  GM("STONE_NAETORU_2"):SetScale(Scale(1.1))
  GM("STONE_HIKOZARU_2"):SetScale(Scale(1.1))
  GM("STONE_POTCHAMA_2"):SetScale(Scale(1.1))
  GM("STONE_RIORU_2"):SetScale(Scale(1.1))
  GM("STONE_HARIMARON_2"):SetScale(Scale(1.1))
  GM("STONE_FOKKO_2"):SetScale(Scale(1.1))
  GM("STONE_KEROMATSU_2"):SetScale(Scale(1.1))
  GM("STONE_PIKACHUU"):SetVisible(false)
  GM("STONE_POKABU"):SetVisible(false)
  GM("STONE_MIJUMARU"):SetVisible(false)
  GM("STONE_TSUTAAJA"):SetVisible(false)
  GM("STONE_FUSHIGIDANE"):SetVisible(false)
  GM("STONE_HITOKAGE"):SetVisible(false)
  GM("STONE_ZENIGAME"):SetVisible(false)
  GM("STONE_CHIKORIITA"):SetVisible(false)
  GM("STONE_HINOARASHI"):SetVisible(false)
  GM("STONE_WANINOKO"):SetVisible(false)
  GM("STONE_KIMORI"):SetVisible(false)
  GM("STONE_ACHAMO"):SetVisible(false)
  GM("STONE_MIZUGOROU"):SetVisible(false)
  GM("STONE_NAETORU"):SetVisible(false)
  GM("STONE_HIKOZARU"):SetVisible(false)
  GM("STONE_POTCHAMA"):SetVisible(false)
  GM("STONE_RIORU"):SetVisible(false)
  GM("STONE_HARIMARON"):SetVisible(false)
  GM("STONE_FOKKO"):SetVisible(false)
  GM("STONE_KEROMATSU"):SetVisible(false)
  GM("STONE_PIKACHUU_2"):SetVisible(false)
  GM("STONE_POKABU_2"):SetVisible(false)
  GM("STONE_MIJUMARU_2"):SetVisible(false)
  GM("STONE_TSUTAAJA_2"):SetVisible(false)
  GM("STONE_FUSHIGIDANE_2"):SetVisible(false)
  GM("STONE_HITOKAGE_2"):SetVisible(false)
  GM("STONE_ZENIGAME_2"):SetVisible(false)
  GM("STONE_CHIKORIITA_2"):SetVisible(false)
  GM("STONE_HINOARASHI_2"):SetVisible(false)
  GM("STONE_WANINOKO_2"):SetVisible(false)
  GM("STONE_KIMORI_2"):SetVisible(false)
  GM("STONE_ACHAMO_2"):SetVisible(false)
  GM("STONE_MIZUGOROU_2"):SetVisible(false)
  GM("STONE_NAETORU_2"):SetVisible(false)
  GM("STONE_HIKOZARU_2"):SetVisible(false)
  GM("STONE_POTCHAMA_2"):SetVisible(false)
  GM("STONE_RIORU_2"):SetVisible(false)
  GM("STONE_HARIMARON_2"):SetVisible(false)
  GM("STONE_FOKKO_2"):SetVisible(false)
  GM("STONE_KEROMATSU_2"):SetVisible(false)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 30 then
    GM("STONE_PIKACHUU"):SetVisible(true)
  elseif pokemonIndexHero == 595 then
    GM("STONE_POKABU"):SetVisible(true)
  elseif pokemonIndexHero == 598 then
    GM("STONE_MIJUMARU"):SetVisible(true)
  elseif pokemonIndexHero == 592 then
    GM("STONE_TSUTAAJA"):SetVisible(true)
  elseif pokemonIndexHero == 1 then
    GM("STONE_FUSHIGIDANE"):SetVisible(true)
  elseif pokemonIndexHero == 5 then
    GM("STONE_HITOKAGE"):SetVisible(true)
  elseif pokemonIndexHero == 10 then
    GM("STONE_ZENIGAME"):SetVisible(true)
  elseif pokemonIndexHero == 197 then
    GM("STONE_CHIKORIITA"):SetVisible(true)
  elseif pokemonIndexHero == 200 then
    GM("STONE_HINOARASHI"):SetVisible(true)
  elseif pokemonIndexHero == 203 then
    GM("STONE_WANINOKO"):SetVisible(true)
  elseif pokemonIndexHero == 322 then
    GM("STONE_KIMORI"):SetVisible(true)
  elseif pokemonIndexHero == 325 then
    GM("STONE_ACHAMO"):SetVisible(true)
  elseif pokemonIndexHero == 329 then
    GM("STONE_MIZUGOROU"):SetVisible(true)
  elseif pokemonIndexHero == 479 then
    GM("STONE_NAETORU"):SetVisible(true)
  elseif pokemonIndexHero == 482 then
    GM("STONE_HIKOZARU"):SetVisible(true)
  elseif pokemonIndexHero == 485 then
    GM("STONE_POTCHAMA"):SetVisible(true)
  elseif pokemonIndexHero == 537 then
    GM("STONE_RIORU"):SetVisible(true)
  elseif pokemonIndexHero == 766 then
    GM("STONE_HARIMARON"):SetVisible(true)
  elseif pokemonIndexHero == 769 then
    GM("STONE_FOKKO"):SetVisible(true)
  elseif pokemonIndexHero == 772 then
    GM("STONE_KEROMATSU"):SetVisible(true)
  end
  local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  if pokemonIndexPartner == 30 then
    GM("STONE_PIKACHUU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 595 then
    GM("STONE_POKABU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 598 then
    GM("STONE_MIJUMARU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 592 then
    GM("STONE_TSUTAAJA_2"):SetVisible(true)
  elseif pokemonIndexPartner == 1 then
    GM("STONE_FUSHIGIDANE_2"):SetVisible(true)
  elseif pokemonIndexPartner == 5 then
    GM("STONE_HITOKAGE_2"):SetVisible(true)
  elseif pokemonIndexPartner == 10 then
    GM("STONE_ZENIGAME_2"):SetVisible(true)
  elseif pokemonIndexPartner == 197 then
    GM("STONE_CHIKORIITA_2"):SetVisible(true)
  elseif pokemonIndexPartner == 200 then
    GM("STONE_HINOARASHI_2"):SetVisible(true)
  elseif pokemonIndexPartner == 203 then
    GM("STONE_WANINOKO_2"):SetVisible(true)
  elseif pokemonIndexPartner == 322 then
    GM("STONE_KIMORI_2"):SetVisible(true)
  elseif pokemonIndexPartner == 325 then
    GM("STONE_ACHAMO_2"):SetVisible(true)
  elseif pokemonIndexPartner == 329 then
    GM("STONE_MIZUGOROU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 479 then
    GM("STONE_NAETORU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 482 then
    GM("STONE_HIKOZARU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 485 then
    GM("STONE_POTCHAMA_2"):SetVisible(true)
  elseif pokemonIndexPartner == 537 then
    GM("STONE_RIORU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 766 then
    GM("STONE_HARIMARON_2"):SetVisible(true)
  elseif pokemonIndexPartner == 769 then
    GM("STONE_FOKKO_2"):SetVisible(true)
  elseif pokemonIndexPartner == 772 then
    GM("STONE_KEROMATSU_2"):SetVisible(true)
  end
  CH("NYASUPAA"):SetVisible(false)
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -350468838)
  WINDOW:Talk(SymAct("JIRAACHI"), -234392485)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1686525833)
  WINDOW:Talk(SymAct("DENRYUU"), -2107467466)
  WINDOW:Talk(SymAct("DENRYUU"), -1454388491)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -1336607820)
  WINDOW:Talk(SymAct("JIRAACHI"), -15372941)
  WINDOW:Talk(SymAct("JIRAACHI"), -435266510)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetDir(RotateTarget(0))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(0.3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -853340175)
  WINDOW:Talk(SymAct("JIRAACHI"), -734511440)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(CH("JIRAACHI"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), 1403003519)
  WINDOW:Talk(SymAct("JIRAACHI"), 1253774142)
  subEveCloseMsg()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
    CH("DENRYUU"):SetManpu("MP_NOTICE_L")
  end
  TASK:Regist(taskLookAt00)
  SOUND:PlaySe(SymSnd("SE_EVT_GASAGASA"))
  WINDOW:SysMsg(112103630)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):DirTo(SymPos("P00_NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(SymPos("P00_NYASUPAA"), Speed(60), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("NYASUPAA"):SetVisible(true)
  CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(2))
  TASK:Sleep(TimeSec(0.7))
  CAMERA:MoveFollow(SymCam("CAMERA_06"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:Talk(SymAct("JIRAACHI"), 531997071)
  WINDOW:Talk(SymAct("JIRAACHI"), 882438732)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):WaitMove()
  CH("NYASUPAA"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.2))
  CH("NYASUPAA"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NYASUPAA"), 763609869)
  WINDOW:Talk(SymAct("NYASUPAA"), 1656903114)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CH("NYASUPAA"):SetShake(Vector(0.005, 0, 0), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NYASUPAA"), 2077844619)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:Talk(SymAct("JIRAACHI"), 1358182216)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1240401417)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):ResetFacialMotion()
  CH("NYASUPAA"):ResetShake()
  CH("NYASUPAA"):ResetNeckRot(TimeSec(0.2))
  CH("NYASUPAA"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -831055162)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  subEveNod(CH("JIRAACHI"))
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:Talk(SymAct("JIRAACHI"), -680776825)
  WINDOW:Talk(SymAct("JIRAACHI"), -1106053205)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1492531478)
  WINDOW:Talk(SymAct("DENRYUU"), -1943759575)
  WINDOW:Talk(SymAct("DENRYUU"), -1790991256)
  WINDOW:Talk(SymAct("DENRYUU"), -629263697)
  WINDOW:Talk(SymAct("DENRYUU"), -1016790034)
  WINDOW:CloseMessage()
  CH("DENRYUU"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("JIRAACHI"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:MoveFollow(SymCam("CAMERA_05_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -397914067)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CH("DENRYUU"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("JIRAACHI"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -246193812)
  WINDOW:CloseMessage()
  subEveNod(CH("NYASUPAA"))
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1993047459)
  WINDOW:Talk(SymAct("NYASUPAA"), 1875922146)
  WINDOW:Talk(SymAct("NYASUPAA"), -1398319035)
  WINDOW:Talk(SymAct("NYASUPAA"), -1245943548)
  subEveCloseMsg()
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), -1634649401)
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CH("DENRYUU"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("JIRAACHI"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WalkTo(SymPos("P01_NYASUPAA"), Speed(1.5))
  CH("NYASUPAA"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -2020996218)
  WINDOW:Talk(SymAct("JIRAACHI"), -926180031)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -774853632)
  WINDOW:Talk(SymAct("DENRYUU"), -84017213)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(60), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  local taskDenryuu00 = function()
    subEveNod(CH("DENRYUU"))
  end
  TASK:Regist(taskDenryuu00)
  local taskJiraachi00 = function()
    subEveNod(CH("JIRAACHI"))
  end
  TASK:Regist(taskJiraachi00)
  local taskNyasupaa00 = function()
    subEveNod(CH("NYASUPAA"))
  end
  TASK:Regist(taskNyasupaa00)
  TASK:Sleep(TimeSec(0.7))
  SOUND:FadeOutEnv(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(1), true)
end
function main19_iberutarunokeikoku15_end()
end
function groundEnd()
end
