dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main18_nidometenkeininoseki01_init()
end
function main18_nidometenkeininoseki01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PURIN"):SetShadowOnlyMode(true)
  CH("REAKOIRU"):SetShadow(false)
  CH("NYOROBON"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("JIBAKOIRU"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("NYOROBON"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
  CH("JIBAKOIRU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
  CH("KOIRU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
  CH("REAKOIRU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
  CH("SUPIAA"):SetMotion(SymMot("EV005_DOWN"), LOOP.ON, TimeSec(0))
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
  CH("KONOHANA"):RunTo(SymPos("P00_KONOHANA"), Speed(3))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("AAKEN"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("KONOHANA"):SetManpu("MP_SHOCK_L")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1305787401, PARTNER_1 = 1422888264})
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_TENSION_02"), Volume(256))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 2145574539)
  WINDOW:CloseMessage()
  CH("HERO"):SetPosition(SymPos("P02_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("AAKEN"):SetPosition(SymPos("P02_AAKEN"))
  CH("KONOHANA"):SetPosition(SymPos("P02_KONOHANA"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Regist(subEveRunDir, {
    CH("AAKEN"),
    SymPos("P01_AAKEN"),
    Speed(3),
    CH("SUPIAA")
  })
  TASK:Regist(subEveRunDir, {
    CH("KONOHANA"),
    SymPos("P01_KONOHANA"),
    Speed(3),
    CH("NYOROBON")
  })
  TASK:Regist(Group("grpPartner"), subEveRunDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(3),
    CH("JIBAKOIRU")
  })
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(3),
    CH("JIBAKOIRU")
  })
  TASK:WaitTask(Group("grpPartner"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1727655882, PARTNER_1 = 699955469})
  subEveCloseMsg()
  local taskJibakoiru00 = function()
    CH("JIBAKOIRU"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(0.3))
    CH("JIBAKOIRU"):ResetShake()
  end
  TASK:Regist(taskJibakoiru00)
  WINDOW:DrawFace(324, 20, SymAct("JIBAKOIRU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 816007244)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 462297999)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("AAKEN")
  })
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 43330254)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SUPIAA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SUPIAA"), -2062731775)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NYOROBON"):SetManpu("MP_FLY_SWEAT")
  CH("NYOROBON"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("NYOROBON"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NYOROBON"), -1676277952)
  WINDOW:Talk(SymAct("NYOROBON"), 892750419)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 741178130)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SUPIAA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SUPIAA"), 117450961)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 505092496, PARTNER_1 = 1364889431})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("AAKEN"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("KONOHANA"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 20, SymAct("JIBAKOIRU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 1212268054)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 1668083157)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 2054675604)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -34619301)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -453709542)
  WINDOW:CloseMessage()
  CH("AAKEN"):RunTo(SplinePath(SymSpl("S00_AAKEN")), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):RunTo(SplinePath(SymSpl("S00_KONOHANA")), Speed(3))
  TASK:Sleep(TimeSec(0.4))
  CH("PARTNER"):RunTo(SplinePath(SymSpl("S00_PARTNER")), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):RunTo(SplinePath(SymSpl("S00_HERO")), Speed(3))
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main18_nidometenkeininoseki01_end()
end
function groundEnd()
end
