dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main20_shizukanaiwababoss1st01_init()
end
function main20_shizukanaiwababoss1st01_start()
  TASK:Sleep(TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1249079811, PARTNER_1 = 1399341890})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 2017792129)
  WINDOW:Talk(SymAct("AAKEN"), 1633558976)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 773830407)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 923043398, PARTNER_1 = 472503685})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), 87221444)
  WINDOW:Talk(SymAct("KUCHIITO"), -2102724597)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FOOT_STEP_01_LP"), Volume(256))
  TASK:Sleep(TimeSec(0.1))
end
function main20_shizukanaiwababoss1st01_end()
end
function main20_shizukanaiwababoss1st02_init()
end
function main20_shizukanaiwababoss1st02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SHADOW_OF_NIHIL"):SetVisible(false)
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("DEDENNE"):RunTo(SymPos("P00_DEDENNE"), Speed(3))
  CH("KUCHIITO"):RunTo(SymPos("P00_KUCHIITO"), Speed(3))
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
  CH("BUIZERU"):RunTo(SymPos("P00_BUIZERU"), Speed(3))
  CH("HORUBII"):RunTo(SymPos("P00_HORUBII"), Speed(3))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  SOUND:FadeOutSe(SymSnd("SE_EVT_FOOT_STEP_01_LP"), TimeSec(1))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), -1682847414)
  WINDOW:CloseMessage()
  CH("AAKEN"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("KUCHIITO"):DirTo(SymPos("P_SEKIHI"), Speed(200), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(SymPos("P_SEKIHI"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("DEDENNE"):DirTo(SymPos("P_SEKIHI"), Speed(200), ROT_TYPE.NEAR)
    CH("HORUBII"):DirTo(SymPos("P_SEKIHI"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(SymPos("P_SEKIHI"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BUIZERU"):DirTo(SymPos("P_SEKIHI"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -1291498807)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -1440842872)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(3),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(3),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("DEDENNE"),
    SymPos("P01_DEDENNE"),
    Speed(3),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("KUCHIITO"),
    SymPos("P01_KUCHIITO"),
    Speed(3),
    RotateTarget(180)
  })
  TASK:Regist(subEveRunDir, {
    CH("AAKEN"),
    SymPos("P01_AAKEN"),
    Speed(3),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.4))
  TASK:Regist(subEveRunDir, {
    CH("HORUBII"),
    SymPos("P01_HORUBII"),
    Speed(2.5),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("BUIZERU"),
    SymPos("P01_BUIZERU"),
    Speed(2.5),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_KK_AMEBA_APPEAR"), Volume(190))
  CH("SHADOW_OF_NIHIL"):SetVisible(true)
  CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_AP00"), LOOP.OFF, TimeSec(0))
  CH("SHADOW_OF_NIHIL"):WaitPlayMotion()
  CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_WT00"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), Volume(256))
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main20_shizukanaiwababoss1st02_end()
end
function main20_shizukanaiwababoss1st03_init()
end
function main20_shizukanaiwababoss1st03_start()
end
function main20_shizukanaiwababoss1st03_end()
end
function main20_shizukanaiwababoss1st04_init()
end
function main20_shizukanaiwababoss1st04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -2127353781)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1742202614, PARTNER_1 = -680947763})
  WINDOW:KeyWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KODAIMOJI"), Volume(256))
  WINDOW:SwitchTalk({PARTNER_0 = -831340916, PARTNER_1 = -446698161})
  WINDOW:SwitchTalk({PARTNER_0 = -62596082, PARTNER_1 = 2078064833})
  WINDOW:SwitchTalk({PARTNER_0 = 1657270656, PARTNER_1 = -1582242521})
  WINDOW:SwitchTalk({PARTNER_0 = -1196698522, PARTNER_1 = -1819899995})
  WINDOW:SwitchTalk({PARTNER_0 = -1969375516, PARTNER_1 = -975429597})
  WINDOW:SwitchTalk({PARTNER_0 = -590933662, PARTNER_1 = -135642463})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("PARTNER"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_QUESTION")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -286166048)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), 1768517423)
  WINDOW:Talk(SymAct("KUCHIITO"), 1886543470)
  WINDOW:Talk(SymAct("KUCHIITO"), 420250178)
  WINDOW:Talk(SymAct("KUCHIITO"), 1553155)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("DEDENNE"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  CH("KUCHIITO"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DEDENNE"), 725278912)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 841077121)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), 2103461702)
  WINDOW:Talk(SymAct("KUCHIITO"), 1685812743)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("KUCHIITO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("DEDENNE"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1331045828, PARTNER_1 = 1447892101})
  WINDOW:SwitchTalk({PARTNER_0 = -774567862, PARTNER_1 = -926009077})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_QUESTION")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -2065974533)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1648325702, PARTNER_1 = -1225926535})
  WINDOW:SwitchTalk({PARTNER_0 = -1342772936, PARTNER_1 = -524845057})
  subEveCloseMsg()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("DEDENNE"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), -106148162)
  WINDOW:Talk(SymAct("KUCHIITO"), -763290243)
  WINDOW:Talk(SymAct("KUCHIITO"), -879088580)
  WINDOW:Talk(SymAct("KUCHIITO"), 1275212019)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1427702194, PARTNER_1 = 1013439902})
  WINDOW:SwitchTalk({PARTNER_0 = 628944095, PARTNER_1 = 240238364})
  WINDOW:SwitchTalk({PARTNER_0 = 390762077, PARTNER_1 = 1477122202})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), 1091578331)
  WINDOW:Talk(SymAct("KUCHIITO"), 1782413848)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("AAKEN"), 1931889497)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_NOTICE_R")
  CH("DEDENNE"):WaitManpu()
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("KUCHIITO"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
    CH("AAKEN"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), -188852330)
  WINDOW:Talk(SymAct("DEDENNE"), -307927337)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("PARTNER"):DirTo(RotateTarget(20), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):DirTo(RotateTarget(70), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(RotateTarget(10), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(RotateTarget(35), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFaceF(72, 16, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 785543792)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(50, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 935936817, PARTNER_1 = 484708594})
  WINDOW:SwitchTalk({PARTNER_0 = 100606387, PARTNER_1 = 1254012788})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetDefaultGroundFovy()
end
function main20_shizukanaiwababoss1st04_end()
end
function main20_shizukanaiwababoss1st05_init()
end
function main20_shizukanaiwababoss1st05_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("BUIZERU"):SetVisible(false)
  CH("HORUBII"):SetVisible(false)
  CH("SHADOW_OF_NIHIL3"):SetVisible(false)
  CH("SHADOW_OF_NIHIL4"):SetVisible(false)
  CH("SHADOW_OF_NIHIL"):SetVisible(false)
  CH("SHADOW_OF_NIHIL2"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  local taskHero00 = function()
    CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
    CH("HERO"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("HERO"), Speed(600))
  end
  TASK:Regist(taskHero00)
  local taskPartner00 = function()
    CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
    CH("PARTNER"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  TASK:Regist(taskPartner00)
  local taskDedenne00 = function()
    CH("DEDENNE"):WalkTo(SymPos("P00_DEDENNE"), Speed(1.5))
    CH("DEDENNE"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("DEDENNE"), Speed(600))
  end
  TASK:Regist(taskDedenne00)
  local taskKuchiito00 = function()
    CH("KUCHIITO"):WalkTo(SymPos("P00_KUCHIITO"), Speed(1.5))
    CH("KUCHIITO"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("KUCHIITO"), Speed(600))
  end
  TASK:Regist(taskKuchiito00)
  local taskAaken00 = function()
    CH("AAKEN"):WalkTo(SymPos("P00_AAKEN"), Speed(1.5))
    CH("AAKEN"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("AAKEN"), Speed(600))
  end
  TASK:Regist(taskAaken00)
  TASK:Sleep(TimeSec(1.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_02"), Volume(256))
  TASK:WaitTask()
  CH("DEDENNE"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(172, 8, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:Talk(SymAct("DEDENNE"), 1403356725)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):WaitRotate()
  CH("BUIZERU"):SetVisible(true)
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DEDENNE"), 2022233590)
  WINDOW:CloseMessage()
  CH("BUIZERU"):SetPosition(SymPos("P00_BUIZERU"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Regist(subEveMoveDir, {
    CH("DEDENNE"),
    SymPos("P01_DEDENNE"),
    Speed(2),
    CH("BUIZERU")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(2),
    CH("BUIZERU")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("KUCHIITO"),
    SymPos("P01_KUCHIITO"),
    Speed(2),
    CH("BUIZERU")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(2),
    CH("BUIZERU")
  })
  TASK:Regist(subEveMoveDir, {
    CH("AAKEN"),
    SymPos("P01_AAKEN"),
    Speed(2),
    CH("BUIZERU")
  })
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 1637082295)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -435423112, PARTNER_1 = -15677127})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1771170539, PARTNER_1 = -1888148396})
  WINDOW:SwitchTalk({PARTNER_0 = -1537706089, PARTNER_1 = -1119664426})
  WINDOW:CloseMessage()
  CH("BUIZERU"):WalkTo(SymPos("P01_BUIZERU"), Speed(0.5))
  TASK:Sleep(TimeSec(0.3))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):SetManpu("MP_NOTICE_R")
    TASK:Sleep(TimeSec(0.1))
    CH("DEDENNE"):SetManpu("MP_NOTICE_R")
    CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
    CH("AAKEN"):SetManpu("MP_NOTICE_R")
  end
  TASK:Regist(taskLookAt00)
  CH("HORUBII"):SetVisible(true)
  WINDOW:Talk(SymAct("HORUBII"), -234696687)
  WINDOW:Talk(SymAct("HORUBII"), -350625456)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1070288237, PARTNER_1 = -651197486})
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("AAKEN"):RunTo(SymPos("P02_AAKEN"), Speed(4), LINK_DIR.OFF)
  CH("HERO"):RunTo(SymPos("P02_HERO"), Speed(4), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):RunTo(SymPos("P02_PARTNER"), Speed(4), LINK_DIR.OFF)
  CH("DEDENNE"):RunTo(SymPos("P02_DEDENNE"), Speed(4), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("KUCHIITO"):RunTo(SymPos("P02_KUCHIITO"), Speed(4), LINK_DIR.OFF)
  CH("KUCHIITO"):WaitMove()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_TENSION_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("HERO"):SetDir(CH("HORUBII"))
  CH("PARTNER"):SetDir(CH("HORUBII"))
  CH("DEDENNE"):SetDir(CH("HORUBII"))
  CH("KUCHIITO"):SetDir(CH("HORUBII"))
  CH("AAKEN"):SetDir(CH("HORUBII"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DEDENNE"), 1589092125)
  WINDOW:CloseMessage()
  CH("HORUBII"):RunTo(SymPos("P00_HORUBII"), Speed(3))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("HORUBII"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HORUBII"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("HORUBII")
  })
  WINDOW:DrawFace(324, 20, SymAct("HORUBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HORUBII"), 1202499164)
  WINDOW:Talk(SymAct("HORUBII"), -838007485)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  CH("KUCHIITO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -686410750, PARTNER_1 = -63215679})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("HORUBII"):DirTo(CH("BUIZERU"), Speed(500), ROT_TYPE.NEAR)
  CH("HORUBII"):WaitRotate()
  CH("HORUBII"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("HORUBII")
  })
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("HORUBII"), -450865536)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("HORUBII"):DirTo(SymPos("P01_HORUBII"), Speed(500), ROT_TYPE.NEAR)
  CH("HORUBII"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):WalkTo(SymPos("P01_HORUBII"), Speed(1))
  WINDOW:DrawFace(72, 16, SymAct("HORUBII"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("HORUBII"), -1436434361)
  CH("HORUBII"):WaitMove()
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CH("KUCHIITO"):RunTo(SymPos("P03_KUCHIITO"), Speed(8))
  CH("KUCHIITO"):WaitMove()
  CH("KUCHIITO"):SetMotion(SymMot("ATTACK_ROUND"), LOOP.OFF)
  CH("HORUBII"):DirTo(CH("KUCHIITO"), Speed(600), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):ResetFacialMotion()
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  local taskHorubii00 = function()
    CH("HORUBII"):SetManpu("MP_SHOCK_L")
    CH("HORUBII"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    CH("HORUBII"):MoveTo(SymPos("P02_HORUBII"), Speed(8))
    CH("HORUBII"):WaitMove()
    SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(256))
    CH("HORUBII"):SetMotion(SymMot("FALL"), LOOP.OFF)
    CH("HORUBII"):WaitPlayMotion()
    CH("HORUBII"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  end
  TASK:Regist(taskHorubii00)
  CH("KUCHIITO"):WaitPlayMotion()
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  CH("KUCHIITO"):WaitManpu()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  CH("HERO"):DirTo(SymPos("P02_HORUBII"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(SymPos("P02_HORUBII"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(SymPos("P02_HORUBII"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(SymPos("P02_HORUBII"), Speed(350), ROT_TYPE.NEAR)
  TASK:WaitTask()
  WINDOW:DrawFace(172, 8, SymAct("HORUBII"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("HORUBII"), -1283788538)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1739087163, PARTNER_1 = -2125687932})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(272, 16, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KUCHIITO"), 114593611)
  WINDOW:Talk(SymAct("KUCHIITO"), 533708298)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CH("KUCHIITO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_10_5"))
  CAMERA:SetTgt(SymCam("CAMERA_10_5"))
  CAMERA:SetFovy(SymCam("CAMERA_10_5"))
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  TASK:Sleep(TimeSec(1.5))
  CH("BUIZERU"):SetManpu("MP_SHOCK_L")
  CH("BUIZERU"):SetMotion(SymMot("FALL"), LOOP.OFF)
  CH("BUIZERU"):WaitPlayMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(190))
  CH("BUIZERU"):SetMotion(SymMot("EV020_DOWN00"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CH("KUCHIITO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  CH("DEDENNE"):WaitManpu()
  CH("HERO"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("KUCHIITO"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 20, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DEDENNE"), 1991336486)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  local taskHorubii00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_NOMIKOMU_01"), Volume(256))
    CH("SHADOW_OF_NIHIL"):SetVisible(true)
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_AP00"), LOOP.OFF, TimeSec(0))
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    CH("HORUBII"):ChangeColor(Color(0, 0, 0, 1), TimeSec(20, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
    CH("HORUBII"):MoveHeightTo(Height(-5), Speed(0.2))
    TASK:Sleep(TimeSec(0.4))
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF)
    TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
    CH("SHADOW_OF_NIHIL"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL"):SetMotion(SymMot("EV020_WT01"), LOOP.ON)
    SOUND:PlaySe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), Volume(256))
  end
  TASK:Regist(taskHorubii00)
  TASK:Sleep(TimeSec(1))
  CH("HERO"):SetDir(CH("SHADOW_OF_NIHIL"))
  CH("PARTNER"):SetDir(CH("SHADOW_OF_NIHIL"))
  CH("AAKEN"):SetDir(CH("SHADOW_OF_NIHIL"))
  CH("DEDENNE"):SetDir(CH("SHADOW_OF_NIHIL"))
  CH("KUCHIITO"):SetDir(CH("SHADOW_OF_NIHIL"))
  TASK:Sleep(TimeSec(2))
  CH("HORUBII"):SetVisible(false)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1873433447, PARTNER_1 = 1149698212})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 1570517477)
  WINDOW:CloseMessage()
  CH("DEDENNE"):SetPosition(SymPos("P03_DEDENNE"))
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CAMERA:SetFovy(SymCam("CAMERA_13"))
  CAMERA:SetRotateZ(SymCam("CAMERA_13"))
  local taskShadow03 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_AMEBA_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL3"):SetVisible(true)
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("EV020_AP00"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL3"):WaitPlayMotion()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF)
    CH("SHADOW_OF_NIHIL3"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL3"):SetMotion(SymMot("EV020_WT01"), LOOP.ON)
    SOUND:PlaySe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), Volume(256))
  end
  TASK:Regist(taskShadow03)
  TASK:Sleep(TimeSec(0.2))
  local taskShadow04 = function()
    CH("SHADOW_OF_NIHIL4"):SetVisible(true)
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("EV020_AP00"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL4"):WaitPlayMotion()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF)
    CH("SHADOW_OF_NIHIL4"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL4"):SetMotion(SymMot("EV020_WT01"), LOOP.ON)
  end
  TASK:Regist(taskShadow04)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("DEDENNE"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):DirTo(CH("SHADOW_OF_NIHIL4"), Speed(500), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("SHADOW_OF_NIHIL3"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):DirTo(CH("SHADOW_OF_NIHIL4"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("SHADOW_OF_NIHIL4"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("SHADOW_OF_NIHIL4"), Speed(500), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("AAKEN"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("DEDENNE"):WaitRotate()
  CH("DEDENNE"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(2))
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  CAMERA:SetFovy(SymCam("CAMERA_14"))
  TASK:Sleep(TimeSec(0.2))
  local taskShadow02 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_AMEBA_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL2"):SetVisible(true)
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("EV020_AP00"), LOOP.OFF, TimeSec(0))
    CH("SHADOW_OF_NIHIL2"):WaitPlayMotion()
    SOUND:PlaySe(SymSnd("SE_EVT_KK_APPEAR"), Volume(256))
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("EV020_AP01"), LOOP.OFF)
    CH("SHADOW_OF_NIHIL2"):WaitPlayMotion()
    CH("SHADOW_OF_NIHIL2"):SetMotion(SymMot("EV020_WT01"), LOOP.ON)
    SOUND:PlaySe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), Volume(256))
  end
  TASK:Regist(taskShadow02)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_SHOCK_L")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("SHADOW_OF_NIHIL2"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("SHADOW_OF_NIHIL2"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_15"))
  CAMERA:SetTgt(SymCam("CAMERA_15"))
  CAMERA:SetFovy(SymCam("CAMERA_15"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 316516130, PARTNER_1 = 197564003})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("SHADOW_OF_NIHIL"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(172, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 552322464, PARTNER_1 = 972092641})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_16"))
  CAMERA:SetTgt(SymCam("CAMERA_16"))
  CAMERA:SetFovy(SymCam("CAMERA_16"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(172, 8, SymAct("KUCHIITO"), FACE_TYPE.DECIDE)
  WINDOW:DrawFaceOffset(-40, 0)
  WINDOW:Talk(SymAct("KUCHIITO"), -1100421074)
  WINDOW:Talk(SymAct("KUCHIITO"), -1485579921)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_SHOCK_R")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DEDENNE"), 313414528)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_17"))
  CAMERA:SetTgt(SymCam("CAMERA_17"))
  CAMERA:SetFovy(SymCam("CAMERA_17"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 196436673)
  WINDOW:Talk(SymAct("AAKEN"), 546844930)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_18"))
  CAMERA:SetTgt(SymCam("CAMERA_18"))
  CAMERA:SetFovy(SymCam("CAMERA_18"))
  CAMERA:MoveFollow2(SymCam("CAMERA_18_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:FadeOutSe(SymSnd("SE_EVT_KK_UGOMEKU_LP"), TimeSec(0.5))
  subEveFlash2()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main20_shizukanaiwababoss1st05_end()
end
function groundEnd()
end
