function Island_first_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  TASK:Regist(Perippaa_op_camera)
  local taskPlayerRun = function()
    CH("PLAYER"):RunTo(SplinePath(SymPos("POINT00_PLAYER"), SymPos("POINT01_PLAYER"), SymPos("POINT02_PLAYER")), Speed(3))
    CH("PLAYER"):WaitMove()
    CH("PLAYER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    CH("PLAYER"):WaitRotate()
  end
  TASK:Regist(taskPlayerRun)
  SCREEN_A:FadeInAll(TimeSec(1), false)
  SCREEN_B:FadeInAll(TimeSec(1), true)
  TASK:Sleep(TimeSec(3))
  SCREEN_A:FadeOutAll(TimeSec(1), false)
  SCREEN_B:FadeOutAll(TimeSec(1), true)
  CAMERA:SetEye(SymCam("CAMERA_PERI_CENTER"))
  CAMERA:SetTgt(SymCam("CAMERA_PERI_CENTER"))
  CH("PERIPPAA"):SetVisible(true)
  CH("PERIPPAA2"):SetVisible(true)
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeInAll(TimeSec(0.5), false)
  SCREEN_B:FadeInAll(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  local taskAisatsu00 = function()
    CH("PERIPPAA2"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("PERIPPAA2"):WaitPlayMotion()
    CH("PERIPPAA2"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  end
  TASK:Regist(taskAisatsu00)
  CH("PERIPPAA2"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 1237093977)
  subEveCloseMsg()
  CH("PERIPPAA2"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  local taskAisatsu01 = function()
    CH("PERIPPAA"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("PERIPPAA"):WaitPlayMotion()
    CH("PERIPPAA"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  end
  TASK:Regist(taskAisatsu01)
  CH("PERIPPAA"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(324, 88, SymAct("PERIPPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA"), 1353170712)
  WINDOW:CloseMessage()
  CH("PERIPPAA"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PERIPPAA2"):SetManpu("MP_NOTICE_L")
  CH("PERIPPAA2"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 2072702171)
  WINDOW:Talk(SymAct("PERIPPAA2"), 1653726618)
  WINDOW:Talk(SymAct("PERIPPAA2"), 768625501)
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.5))
  local taskGourei00 = function()
    CH("PERIPPAA2"):SetManpu("MP_SPREE_LP")
    CH("PERIPPAA2"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("PERIPPAA2"):WaitPlayMotion()
    CH("PERIPPAA2"):SetMotion(SymMot("WAIT00"), LOOP.ON)
    CH("PERIPPAA2"):ResetManpu()
  end
  TASK:Regist(taskGourei00)
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 885750300)
  WINDOW:Talk(SymAct("PERIPPAA2"), 535177695)
  WINDOW:Talk(SymAct("PERIPPAA2"), 117250206)
  WINDOW:CloseMessage()
  TASK:Regist(taskGourei00)
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), -2124086191)
  WINDOW:Talk(SymAct("PERIPPAA2"), -1736559344)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_WEST"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PERIPPAA2"):DirTo(RotateTarget(-130), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 1197097711)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("PERIPPAA2"):DirTo(RotateTarget(5), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_PERI_CENTER"))
  CAMERA:SetTgt(SymCam("CAMERA_PERI_CENTER"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(taskGourei00)
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 1581347758)
  WINDOW:Talk(SymAct("PERIPPAA2"), 1970020461)
  WINDOW:Talk(SymAct("PERIPPAA2"), 1819742508)
  subEveCloseMsg()
  TASK:Sleep(TimeSec(0.3))
  CH("PERIPPAA"):DirTo(CH("PERIPPAA2"), Speed(350), ROT_TYPE.NEAR)
  CH("PERIPPAA"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("PERIPPAA"):DirTo(RotateTarget(-5), Speed(500), ROT_TYPE.NEAR)
  CH("PERIPPAA"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  local taskPeri00 = function()
    CH("PERIPPAA"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.2))
    CH("PERIPPAA"):SetMotion(SymMot("WAIT00"), LOOP.ON)
    TASK:Sleep(TimeSec(0.2))
    CH("PERIPPAA"):DirTo(CH("PERIPPAA2"), Speed(500), ROT_TYPE.NEAR)
    CH("PERIPPAA"):WaitRotate()
    CH("PERIPPAA"):SetManpu("MP_FLY_SWEAT")
    CH("PERIPPAA"):WaitManpu()
  end
  TASK:Regist(taskPeri00)
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(taskGourei00)
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 590776299)
  WINDOW:KeyWait()
  WINDOW:Talk(SymAct("PERIPPAA2"), 976074410)
  WINDOW:CloseMessage()
  CH("PERIPPAA"):DirTo(RotateTarget(-5), Speed(350), ROT_TYPE.NEAR)
  SCREEN_A:FadeOutAll(TimeSec(0.5), false)
  SCREEN_B:FadeOutAll(TimeSec(0.5), true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(Perippaa_view_gate)
  SCREEN_A:FadeInAll(TimeSec(0.5), false)
  SCREEN_B:FadeInAll(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 285271401)
  WINDOW:Talk(SymAct("PERIPPAA2"), 136041512)
  WINDOW:Talk(SymAct("PERIPPAA2"), -1887188761)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOutAll(TimeSec(0.5), false)
  SCREEN_B:FadeOutAll(TimeSec(0.5), true)
  CAMERA:SetEye(SymCam("CAMERA_PERI_CENTER"))
  CAMERA:SetTgt(SymCam("CAMERA_PERI_CENTER"))
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeInAll(TimeSec(0.5), false)
  SCREEN_B:FadeInAll(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), -1768359514)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PERIPPAA"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PERIPPAA")
  })
  CH("PERIPPAA"):WaitManpu()
  CH("PERIPPAA"):DirTo(CH("PERIPPAA"), Speed(500), ROT_TYPE.NEAR)
  CH("PERIPPAA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PERIPPAA"):SetManpu("MP_FLY_SWEAT_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("PERIPPAA")
  })
  CH("PERIPPAA2"):DirTo(CH("PERIPPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("PERIPPAA"):SetFacialMotion(FACIAL_MOTION.PAIN)
  WINDOW:DrawFace(324, 88, SymAct("PERIPPAA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("PERIPPAA"), 1441787137)
  WINDOW:CloseMessage()
  CH("PERIPPAA"):ResetFacialMotion()
  CH("PERIPPAA"):ResetManpu()
  CH("PERIPPAA"):SetMotion(SymMot("WAIT00"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PERIPPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA"), 1291115584)
  WINDOW:Talk(SymAct("PERIPPAA"), 1742311299)
  WINDOW:Talk(SymAct("PERIPPAA"), 2126692034)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_EAST"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PERIPPAA"):DirTo(RotateTarget(130), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("PERIPPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA"), 830679045)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("PERIPPAA"):DirTo(RotateTarget(-5), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_PERI_CENTER"))
  CAMERA:SetTgt(SymCam("CAMERA_PERI_CENTER"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.3))
  CH("PERIPPAA2"):DirTo(RotateTarget(5), Speed(350), ROT_TYPE.NEAR)
  CH("PERIPPAA2"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PERIPPAA2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PERIPPAA2"), 681056580)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOutAll(TimeSec(1), false)
  SCREEN_B:FadeOutAll(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function Perippaa_op_camera()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
end
function Perippaa_view_gate()
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
end
function Perippaa_action_odoroku()
  CH("PERIPPAA2"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
  TASK:Sleep(TimeSec(1))
  CH("PERIPPAA2"):WaitPlayMotion()
  CH("PERIPPAA2"):SetMotion(SymMot("WAIT00"), LOOP.ON)
end
function Island_second()
  TASK:Regist(Group("main"), Island_second_task)
  while TASK:IsEndTasks(Group("main")) == false do
    TASK:Sleep(TimeSec(0))
  end
end
function Island_second_task()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PLAYER"):SetPosition(SymPos("WALK_POINT_00"))
  CH("PLAYER"):SetDir(RotateTarget(180))
  SOUND:PlayBgm(SymSnd("BGM_MAP_PERIPPAATOU"), Volume(256))
  SCREEN_A:FadeInAll(TimeSec(1), false)
  SCREEN_B:FadeInAll(TimeSec(1), true)
  TASK:Sleep(TimeSec(1.3), TASK_EXIT.QUICK)
  SCREEN_A:FadeOutAll(TimeSec(1), false)
  SCREEN_B:FadeOutAll(TimeSec(1), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SCREEN_A:FadeInAll(TimeSec(1), false)
  SCREEN_B:FadeInAll(TimeSec(1), true)
  EFFECT:Create("warp", SymEff("CH_WARPCYLINDER_BLUE"))
  EFFECT:SetPosition("warp", SymPos("WALK_POINT_00"))
  EFFECT:Play("warp")
  SOUND:PlaySe(SymSnd("SE_TAMA_WARP"), Volume(256))
  CH("PLAYER"):SetVisible(true)
  EFFECT:Wait("warp")
  TASK:Sleep(TimeSec(0.5), TASK_EXIT.QUICK)
  CH("PLAYER"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate(TASK_EXIT.QUICK)
  TASK:Sleep(TimeSec(0.5), TASK_EXIT.QUICK)
  CH("PLAYER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate(TASK_EXIT.QUICK)
  TASK:Sleep(TimeSec(0.5), TASK_EXIT.QUICK)
  CH("PLAYER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate(TASK_EXIT.QUICK)
  TASK:Sleep(TimeSec(0.5), TASK_EXIT.QUICK)
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PLAYER"):RunTo(SymPos("WALK_POINT_01"), Speed(3))
  TASK:Sleep(TimeSec(1.5), TASK_EXIT.QUICK)
  SCREEN_A:FadeOutAll(TimeSec(1), false)
  SCREEN_B:FadeOutAll(TimeSec(1), true)
end
