dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_jugyouchuuni01_init()
end
function main03_jugyouchuuni01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetVisible(false)
  CH("KAMONEGI"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0))
  CH("YANCHAMU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
  CH("CHOBOMAKI"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
  local taskutoutoPartner00 = function()
    function TaskL.Loop()
      CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.5))
      CH("PARTNER"):WaitNeckRot()
      CH("PARTNER"):ResetFacialMotion()
      CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
      CH("PARTNER"):WaitNeckRot()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.3))
      CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0.1))
      CH("PARTNER"):ResetFacialMotion()
      TASK:Sleep(TimeSec(0.1))
      CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0.1))
      CH("PARTNER"):ResetFacialMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0.1))
      CH("PARTNER"):ResetFacialMotion()
      TASK:Sleep(TimeSec(0.1))
      CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("PARTNER"):ResetFacialMotion()
      CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
      CH("PARTNER"):WaitNeckRot()
      return
    end
  end
  local taskutoutoShikijika00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      CH("SHIKIJIKA_SPRING"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.5))
      CH("SHIKIJIKA_SPRING"):WaitNeckRot()
      CH("SHIKIJIKA_SPRING"):ResetFacialMotion()
      CH("SHIKIJIKA_SPRING"):ResetNeckRot(TimeSec(0.2))
      CH("SHIKIJIKA_SPRING"):WaitNeckRot()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.3))
      CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0.1))
      CH("SHIKIJIKA_SPRING"):ResetFacialMotion()
      TASK:Sleep(TimeSec(0.1))
      CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0.1))
      CH("SHIKIJIKA_SPRING"):ResetFacialMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0.1))
      CH("SHIKIJIKA_SPRING"):ResetFacialMotion()
      TASK:Sleep(TimeSec(0.1))
      CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.SLEEP)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
    end
    function TaskL.Finish()
      CH("SHIKIJIKA_SPRING"):ResetFacialMotion()
      CH("SHIKIJIKA_SPRING"):ResetNeckRot(TimeSec(0.2))
      CH("SHIKIJIKA_SPRING"):WaitNeckRot()
      return
    end
  end
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -518378072)
  WINDOW:Talk(SymAct("KAMONEGI"), -134144791)
  WINDOW:Talk(SymAct("KAMONEGI"), -752070870)
  WINDOW:CloseMessage()
  TASK:Regist(Group("grpPartner"), taskutoutoPartner00)
  TASK:Regist(Group("grpShikijika"), taskutoutoShikijika00)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -902332821)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):SetManpu("MP_SLEEP_LP")
  CH("CHOBOMAKI"):SetManpu("MP_SLEEP_LP")
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_ZZZ"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -2055804756)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SHU"), Volume(256))
  CH("HERO"):WaitMove()
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:ExitNotifyTasks(Group("grpPartner"))
  TASK:ExitNotifyTasks(Group("grpShikijika"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("NYASUPAA"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_NOTICE_L")
  CH("YANCHAMU"):ResetManpu()
  CH("CHOBOMAKI"):ResetManpu()
  CH("YANCHAMU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("CHOBOMAKI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("KAMONEGI"):ResetNeckRot(TimeSec(0.2))
  CH("KAMONEGI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:WaitTask(Group("grpPartner"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:WaitTask(Group("grpShikijika"))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("YANCHAMU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1670522387)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(324, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1220507090)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("PARTNER"):SetPosition(SymPos("P00_PARTNER"))
  CH("SHIKIJIKA_SPRING"):SetPosition(SymPos("P00_SHIKIJIKA"))
  CH("NUMERA"):SetPosition(SymPos("P00_NUMERA"))
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(2),
    CH("HERO")
  })
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveMoveDir, {
    CH("SHIKIJIKA_SPRING"),
    SymPos("P01_SHIKIJIKA"),
    Speed(2),
    CH("HERO")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveMoveDir, {
    CH("NUMERA"),
    SymPos("P01_NUMERA"),
    Speed(2),
    CH("HERO")
  })
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P01_PARTNER"), Speed(60), ROT_TYPE.NEAR)
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1369719953, PARTNER_1 = 700688288})
  WINDOW:SwitchTalk({PARTNER_0 = 819500769, PARTNER_1 = 86165735})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH("KAMONEGI"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("KAMONEGI")
  })
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KAMONEGI"), 473561510)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KAMONEGI"), 924101221)
  WINDOW:CloseMessage()
  CH("KAMONEGI"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_FLY_SWEAT")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 772774692)
  WINDOW:CloseMessage()
  CH("NUMERA"):WalkTo(SymPos("P00_NUMERA"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(1.5))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(2))
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("SHIKIJIKA_SPRING"):SetPosition(SymPos("P02_SHIKIJIKA"))
  CH("NUMERA"):SetPosition(SymPos("P02_NUMERA"))
  CH("PARTNER"):SetDir(SymPos("P03_PARTNER"))
  CH("SHIKIJIKA_SPRING"):SetDir(SymPos("P03_SHIKIJIKA"))
  CH("NUMERA"):SetDir(SymPos("P03_NUMERA"))
  local taskPartner00 = function()
    CH("PARTNER"):WalkTo(SplinePath(SymPos("P02_PARTNER"), SymPos("P03_PARTNER")), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(RotateTarget(-125), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  local taskShikijika00 = function()
    CH("SHIKIJIKA_SPRING"):WalkTo(SplinePath(SymPos("P02_SHIKIJIKA"), SymPos("P03_SHIKIJIKA")), Speed(1.5))
    CH("SHIKIJIKA_SPRING"):WaitMove()
    CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):WaitRotate()
  end
  local taskNumera00 = function()
    CH("NUMERA"):WalkTo(SplinePath(SymPos("P02_NUMERA"), SymPos("P03_NUMERA")), Speed(1.5))
    CH("NUMERA"):WaitMove()
    CH("NUMERA"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):WaitRotate()
  end
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(taskPartner00)
  TASK:Regist(taskShikijika00)
  TASK:Regist(taskNumera00)
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1632505315)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 2018852002)
  WINDOW:Talk(SymAct("KAMONEGI"), 1400401761)
  WINDOW:CloseMessage()
  local taskHero00 = function()
    CH("HERO"):WalkTo(SplinePath(SymSpl("S00_HERO")), Speed(1.5))
    CH("HERO"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.1))
  CH("KAMONEGI"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):DirTo(SymPos("P03_HERO"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1248026144, PARTNER_1 = -839171345})
  WINDOW:CloseMessage()
  TASK:WaitTask()
  CH("NYASUPAA"):DirTo(RotateTarget(-115), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):DirTo(RotateTarget(-115), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):DirTo(RotateTarget(-100), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("KAMONEGI"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("KAMONEGI")
  })
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KAMONEGI"), -723487826)
  WINDOW:CloseMessage()
  CH("KAMONEGI"):ResetManpu()
  CH("PARTNER"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 395798281, PARTNER_1 = 244078152})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 631309707)
  WINDOW:CloseMessage()
  CH("KAMONEGI"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.3))
  CH("KAMONEGI"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("KAMONEGI"):SetManpu("MP_QUESTION")
  CH("KAMONEGI"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KAMONEGI"), 1018836170)
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1945870861)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Regist(Group("grpPartner"), taskutoutoPartner00)
  TASK:Regist(Group("grpShikijika"), taskutoutoShikijika00)
  local taskYanChobo01 = function()
    CH("YANCHAMU"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
    CH("YANCHAMU"):WaitPlayMotion()
    CH("YANCHAMU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
    CH("CHOBOMAKI"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
    CH("CHOBOMAKI"):WaitPlayMotion()
    CH("CHOBOMAKI"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  end
  TASK:Regist(taskYanChobo01)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_ZZZ"), Volume(256))
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1793102668)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function main03_jugyouchuuni01_end()
end
function main03_jugyouchuuni02_init()
end
function main03_jugyouchuuni02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1104003215)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHILDREN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NUMERA"), 1490481614)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -548475647)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -967451584, PARTNER_1 = -1356136340})
  WINDOW:SwitchTalk({PARTNER_0 = -1238355667, PARTNER_1 = -1659018514})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  local taskShikijika01 = function()
    function TaskL.Loop()
      CH("SHIKIJIKA_SPRING"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(3))
      CH("SHIKIJIKA_SPRING"):ResetManpu()
      TASK:Sleep(TimeSec(1.5))
    end
  end
  local taskNumera01 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.3))
      TASK:Regist(subEveDoubleJump, {
        CH("NUMERA")
      })
      TASK:Sleep(TimeSec(0.3))
      CH("NUMERA"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(2))
      CH("NUMERA"):ResetManpu()
      TASK:Sleep(TimeSec(1.5))
    end
  end
  local taskPartner01 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.5))
      CH("PARTNER"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
      CH("PARTNER"):WaitRotate()
      TASK:Sleep(TimeSec(0.2))
      CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
      CH("PARTNER"):WaitRotate()
      TASK:Sleep(TimeSec(0.2))
      CH("PARTNER"):DirTo(RotateTarget(170), Speed(350), ROT_TYPE.NEAR)
      CH("PARTNER"):WaitRotate()
      TASK:Sleep(TimeSec(0.2))
      CH("PARTNER"):SetManpu("MP_SPREE_LP")
      TASK:Regist(subEveDoubleJump, {
        CH("PARTNER")
      })
      TASK:Sleep(TimeSec(1.5))
      CH("PARTNER"):ResetManpu()
    end
  end
  SOUND:PlayEnv(SymSnd("SE_EVT_GAYA_LP"), Volume(256))
  TASK:Regist(Group("grpShikijika"), taskShikijika01)
  TASK:Regist(Group("grpNumera"), taskNumera01)
  TASK:Regist(Group("grpPartner"), taskPartner01)
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):DirTo(RotateTarget(-120), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(4.5))
  SOUND:VolumeEnv(Volume(64), TimeSec(1))
  SOUND:VolumeBgm(Volume(64), TimeSec(2))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("YANCHAMU"), -2079960145)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):WaitRotate()
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -884488856)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_QUESTION")
  CH("YANCHAMU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -765660119)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  SOUND:FadeOutEnv(TimeSec(1))
  CH("CHOBOMAKI"):WalkTo(SymPos("P00_CHOBOMAKI"), Speed(1.5))
  CH("CHOBOMAKI"):WaitMove()
  CH("YANCHAMU"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.35))
  CH("YANCHAMU"):WaitNeckRot()
  CH("CHOBOMAKI"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -109991958)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -529885525)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):ResetManpu()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  CH("NUMERA"):ResetManpu()
  CH("CHOBOMAKI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:SysMsg(1743948388)
  SOUND:WaitSe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 2129247013)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.1))
end
function main03_jugyouchuuni02_end()
end
function main03_jugyouchuuni03_init()
end
function main03_jugyouchuuni03_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(1.5))
  TASK:Regist(subEveMoveDir, {
    CH("SHIKIJIKA_SPRING"),
    SymPos("P00_SHIKIJIKA"),
    Speed(1.5),
    CH("KAMONEGI")
  })
  TASK:Regist(subEveMoveDir, {
    CH("NUMERA"),
    SymPos("P00_NUMERA"),
    Speed(1.5),
    CH("KAMONEGI")
  })
  CH("YANCHAMU"):SetManpu("MP_SPREE_LP")
  CH("YANCHAMU"):RunTo(SplinePath(SymPos("P00_YANCHAMU"), SymPos("P01_YANCHAMU")), Speed(3))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT_LP")
  CH("CHOBOMAKI"):RunTo(SplinePath(SymPos("P00_CHOBOMAKI"), SymPos("P01_CHOBOMAKI")), Speed(3))
  SOUND:PlayBgm(SymSnd("BGM_EVE_GAKKOU_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask()
  CH("KAMONEGI"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 855390421)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 736561556)
  subEveCloseMsg()
  CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P01_SHIKIJIKA"), Speed(1.5))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), 13261399)
  subEveCloseMsg()
  CH("NUMERA"):WalkTo(SymPos("P01_NUMERA"), Speed(1.5))
  CH("KAMONEGI"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 433154838)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main03_jugyouchuuni03_end()
end
function groundEnd()
end
