dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main22_kodaiisekitry1st01_init()
end
function main22_kodaiisekitry1st01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("RAPURASU"):SetShadow(false)
  CH("RAPURASU"):SetNeckRot(RotateTarget(-30), RotateTarget(0), RotateTarget(0), TimeSec(0))
  SOUND:FadeInEnv(SymSnd("SE_ENV_SEA_02_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(324, 88, SymAct("RAPURASU2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAPURASU2"), -864442871)
  WINDOW:Talk(SymAct("RAPURASU2"), -714959032)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -28326773, PARTNER_1 = -413862454})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("RAPURASU2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAPURASU2"), -1474993395)
  subEveCloseMsg()
  WINDOW:Talk(SymAct("RAPURASU2"), -1324461492)
  WINDOW:SelectStart()
  WINDOW:SelectChain(-1708981873, 1)
  WINDOW:SelectChain(-2093469490, 0)
  WINDOW:DefaultCursor(0)
  local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
  if id == 1 then
    subEveCloseMsg()
    CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("OOBEMU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    CH("OOBEMU"):WaitRotate()
    WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
    WINDOW:SwitchTalk({PARTNER_0 = 77605889, PARTNER_1 = 498801984})
    WINDOW:CloseMessage()
    subEveNod(CH("HERO"))
    SOUND:FadeOutEnv(TimeSec(0.8))
    SCREEN_A:FadeOut(TimeSec(1), true)
    TASK:Sleep(TimeSec(2))
    return "select1"
  else
    WINDOW:CloseMessage()
    SOUND:FadeOutEnv(TimeSec(0.5))
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    return "select2"
  end
end
function main22_kodaiisekitry1st01_end()
end
function groundEnd()
end
