dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main05_kaiyoude01_init()
end
function main05_kaiyoude01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m05_200_01"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main05_kaiyoude01_cut_script_01()
  SOUND:PlaySe(SymSnd("SE_EVT_DIVING"), Volume(256))
end
function main05_kaiyoude01_end()
end
function main05_kaiyoude02_init()
end
function main05_kaiyoude02_start()
  SOUND:FadeInEnv(SymSnd("SE_ENV_SEA_LP"), TimeSec(0.5), Volume(128))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m05_200_02"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main05_kaiyoude02_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("JUGON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JUGON"), 659805467)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude02_cut_talk_02()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(272, 16, SymAct("RANTAAN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RANTAAN"), 1044964442)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude02_cut_talk_03()
  WINDOW:SetWaitMode(TimeSec(2.5), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("RANTAAN2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RANTAAN2"), 358987673)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude02_cut_talk_04()
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  WINDOW:DrawFace(324, 20, SymAct("RANTAAN3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RANTAAN3"), 209618648)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude02_cut_talk_05()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("JUGON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JUGON"), 1128206367)
  WINDOW:Talk(SymAct("JUGON"), 1512317278)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude02_cut_talk_06()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("JUGON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JUGON"), 1896444573)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude02_end()
end
function main05_kaiyoude03_init()
end
function main05_kaiyoude03_start()
  SOUND:PlayEnv(SymSnd("SE_ENV_SEA_LP"), Volume(128))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m05_200_03"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main05_kaiyoude03_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("RANTAAN3"), 1746027484)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude03_cut_talk_02()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("RANTAAN"), -276144365)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude03_cut_talk_03()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("RANTAAN2"), -158241198)
  WINDOW:Talk(SymAct("RANTAAN2"), 2041350651)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("RANTAAN"), 1622653114)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude03_cut_talk_04()
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  WINDOW:Talk(SymAct("RANTAAN"), 1268444025)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude03_cut_talk_05()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("RANTAAN2"), 1384241720)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude03_cut_talk_06()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("RANTAAN3"), 499141887)
  WINDOW:Talk(SymAct("RANTAAN3"), 81493438)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude03_end()
end
function main05_kaiyoude04_init()
end
function main05_kaiyoude04_start()
  SOUND:PlayEnv(SymSnd("SE_ENV_SEA_LP"), Volume(128))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m05_200_04"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  TASK:Sleep(TimeSec(0.5))
end
function main05_kaiyoude04_end()
end
function main05_kaiyoude04_cut_talk_01()
  SOUND:PlaySe(SymSnd("SE_EVT_DOON_01"), Volume(128))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("RANTAAN3"), 804662909)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main05_kaiyoude04_cut_script_01()
  SOUND:FadeOutEnv(TimeSec(1.5))
end
function groundEnd()
end
