dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main13_jiraachimezameru01_init()
end
function main13_jiraachimezameru01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("JIRAACHI"):SetMotion(SymMot("EV013_SLEEP00"), LOOP.ON, TimeSec(0))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 517150991, PARTNER_1 = 130558030})
  WINDOW:CloseMessage()
  local taskHeroAround = function()
    CH("HERO"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(RotateTarget(170), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(RotateTarget(80), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  local taskPartnerLookAround = function()
    CH("PARTNER"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):DirTo(RotateTarget(-120), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(RotateTarget(-45), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  TASK:Regist(Group("hero"), taskHeroAround)
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(Group("partner"), taskPartnerLookAround)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 753236877, PARTNER_1 = 905857740})
  TASK:WaitTask(Group("partner"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(4))
  EFFECT:Create("effectStarAbsorb", SymEff("EV_STAR_ABSORB"))
  EFFECT:SetPosition("effectStarAbsorb", SymPos("P_EFF_STAR_ABSORB"))
  SOUND:PlaySe(SymSnd("SE_EVT_JIRAACHI_OMEZAME_01"))
  EFFECT:Play("effectStarAbsorb")
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("JIRAACHI"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("JIRAACHI"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(1.1))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  SOUND:FadeOutEnv(TimeSec(0.5))
  SCREEN_A:WhiteOut(TimeSec(0.3), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = 2059394059, PARTNER_1 = 1671753034})
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(1))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  EFFECT:Create("effectStar", SymEff("EV_STAR"))
  EFFECT:SetPosition("effectStar", SymPos("P_EFF_STAR_ABSORB"))
  EFFECT:Play("effectStar")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.1))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_JIRAACHI_OMEZAME_02"))
  EFFECT:Wait("effectStar")
  CH("JIRAACHI"):SetMotion(SymMot("EV013_SLEEP01"), LOOP.OFF)
  CH("JIRAACHI"):WaitPlayMotion()
  CH("JIRAACHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  local taskJiraachi00 = function()
    CH("JIRAACHI"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("JIRAACHI"):WaitPlayMotion()
    CH("JIRAACHI"):SetManpu("MP_SPREE_LP")
    CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("JIRAACHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskJiraachi00)
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("JIRAACHI"), 1216986761)
  WINDOW:Talk(SymAct("JIRAACHI"), 1368559560)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CH("JIRAACHI"):ResetManpu()
  CH("JIRAACHI"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("JIRAACHI"):SetManpu("MP_NOTICE_L")
  CH("JIRAACHI"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -703950073)
  WINDOW:Talk(SymAct("JIRAACHI"), -820927930)
  WINDOW:Talk(SymAct("JIRAACHI"), -976164427)
  WINDOW:Talk(SymAct("JIRAACHI"), -590620428)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SWEAT_R_AL")
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -135886025)
  WINDOW:Talk(SymAct("JIRAACHI"), -285361546)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("JIRAACHI"):SetManpu("MP_QUESTION")
  WINDOW:Talk(SymAct("JIRAACHI"), -1581503311)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1197007376, PARTNER_1 = -1819652557})
  WINDOW:SwitchTalk({PARTNER_0 = -1970176142, PARTNER_1 = 218719165})
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 336745212, PARTNER_1 = -681228709})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("JIRAACHI"):SetManpu("MP_QUESTION")
  CH("JIRAACHI"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("JIRAACHI"), -830572774)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  CH("JIRAACHI"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -447535911)
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -62384744, PARTNER_1 = -1291222177})
  subEveCloseMsg()
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("JIRAACHI"), -1441615330)
  WINDOW:Talk(SymAct("JIRAACHI"), -2126519843)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("JIRAACHI"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):SetManpu("MP_SWEAT_R_AL")
  TASK:Sleep(TimeSec(1.5))
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  CH("JIRAACHI"):ResetManpu()
  CH("JIRAACHI"):ResetFacialMotion()
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -1742417764)
  WINDOW:KeyWait()
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("JIRAACHI"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("JIRAACHI"), 532466771)
  CH("JIRAACHI"):WaitPlayMotion()
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main13_jiraachimezameru01_end()
end
function main13_jiraachimezameru02_init()
end
function main13_jiraachimezameru02_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1301"))
  MAP:SetVisibleBG(true)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("JIRAACHI"), 111672594)
  WINDOW:Talk(SymAct("JIRAACHI"), 1876500798)
  WINDOW:Talk(SymAct("JIRAACHI"), 1992429695)
  WINDOW:Talk(SymAct("JIRAACHI"), 1575961532)
  WINDOW:Talk(SymAct("JIRAACHI"), 1156870909)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main13_jiraachimezameru02_end()
end
function main13_jiraachimezameru03_init()
end
function main13_jiraachimezameru03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("JIRAACHI"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("JIRAACHI"), 196469818)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):SetManpu("MP_SWEAT_R_AL")
  TASK:Sleep(TimeSec(1))
  CH("JIRAACHI"):ResetManpu()
  CH("JIRAACHI"):ResetFacialMotion()
  WINDOW:DrawFace(272, 16, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), 313447803)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetMotion(SymMot("EV013_SLEEP00"), LOOP.ON, TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 964921016, PARTNER_1 = 546879481})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT_LP")
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT_LP")
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function main13_jiraachimezameru03_end()
end
function main13_jiraachimezameru04_init()
end
function main13_jiraachimezameru04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_03"), Volume(128))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 20, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -1493128394)
  WINDOW:Talk(SymAct("JIRAACHI"), -1105487241)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  CH("DENRYUU"):DirTo(CH("JIRAACHI"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFaceF(172, 8, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -233956985)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -350934842)
  WINDOW:CloseMessage()
  CH("DENRYUU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1070040315)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_QUESTION")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DENRYUU"), -651998652)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1771905917)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("JIRAACHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("JIRAACHI"), -1887834686)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  WINDOW:SwitchTalk({PARTNER_0 = -1537950207, PARTNER_1 = -1118859456})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.CATCHBREATH)
  WINDOW:Monologue(987206543)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 600613582)
  WINDOW:Talk(SymAct("DENRYUU"), 1253211874)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1403604899, PARTNER_1 = 2021923936})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1637821729)
  WINDOW:Talk(SymAct("DENRYUU"), 786349030)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 935692967, PARTNER_1 = 485022052})
  WINDOW:SwitchTalk({PARTNER_0 = 99870757, PARTNER_1 = -2106854166})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1687108181)
  WINDOW:Talk(SymAct("DENRYUU"), 1476907276)
  WINDOW:Talk(SymAct("DENRYUU"), 1092411469)
  WINDOW:Talk(SymAct("DENRYUU"), 1781642126)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1932165839, PARTNER_1 = 1013650440})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 628106569, PARTNER_1 = 241006218})
  WINDOW:SwitchTalk({PARTNER_0 = 390481867, PARTNER_1 = -1864475900})
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -1983550907, PARTNER_1 = -524568983})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main13_jiraachimezameru04_end()
end
function groundEnd()
end
