dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main05_kizunasukaafu01_init()
end
function main05_kizunasukaafu01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(190))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(3))
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.5))
  CH("ROZERIA"):SetFacialMotion(FACIAL_MOTION.SLEEP)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ROZERIA"):SetManpu("MP_FLY_SWEAT")
  CH("ROZERIA"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("ROZERIA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("ROZERIA"), -38465398)
  WINDOW:Talk(SymAct("ROZERIA"), -458350133)
  subEveCloseMsg()
  CH("ROZERIA"):ResetFacialMotion()
  TASK:Regist(subEveDoubleJump, {
    CH("SUBOMII")
  })
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBOMII"), -813469176)
  WINDOW:Talk(SymAct("SUBOMII"), -694664375)
  subEveCloseMsg()
  CH("ROZERIA"):SetFacialMotion(FACIAL_MOTION.SLEEP)
  WINDOW:DrawFace(272, 16, SymAct("ROZERIA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("ROZERIA"), -1713777266)
  WINDOW:Talk(SymAct("ROZERIA"), -2134711089)
  subEveCloseMsg()
  CH("ROZERIA"):ResetFacialMotion()
  TASK:Regist(subEveJump, {
    CH("SUBOMII")
  })
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBOMII"), -1410353396)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("ROZERIA"):WalkTo(SymPos("P00_ROZERIA"), Speed(1.5))
  CH("SUBOMII"):WalkTo(SymPos("P00_SUBOMII"), Speed(1.5))
  CH("SUBOMII"):WaitMove()
  CH("ROZERIA"):WaitMove()
  CH("ROZERIA"):SetMotion(SymMot("EV005_HUG00"), LOOP.OFF)
  CH("SUBOMII"):SetMotion(SymMot("EV005_HUG00"), LOOP.OFF)
  CH("SUBOMII"):WaitPlayMotion()
  CH("ROZERIA"):SetMotion(SymMot("EV005_HUG01"), LOOP.ON)
  CH("SUBOMII"):SetMotion(SymMot("EV005_HUG01"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("ROZERIA"):SetPosition(SymPos("P01_ROZERIA"))
  CH("SUBOMII"):SetPosition(SymPos("P01_SUBOMII"))
  CH("ROZERIA"):SetDir(RotateTarget(0))
  CH("SUBOMII"):SetDir(RotateTarget(0))
  CH("ROZERIA"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
  CH("SUBOMII"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(272, 16, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), -1292597683)
  WINDOW:Talk(SymAct("ROZERIA"), 896309890)
  WINDOW:Talk(SymAct("ROZERIA"), 746040259)
  WINDOW:CloseMessage()
  CH("ROZERIA"):WalkTo(SymPos("P02_ROZERIA"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(SymPos("P02_ROZERIA"), Speed(200), ROT_TYPE.NEAR)
  CH("ROZERIA"):WaitMove()
  SOUND:PlayMe(SymSnd("ME_REWARD"), Volume(256))
  OverFlow_AddOverflowCheckItem(108, 1, true)
  SOUND:WaitMe()
  WINDOW:KeyWait()
  SOUND:PlayMe(SymSnd("ME_REWARD"), Volume(256))
  OverFlow_AddOverflowCheckItem(73, 1, true)
  SOUND:WaitMe()
  WINDOW:KeyWait()
  SOUND:PlayMe(SymSnd("ME_REWARD"), Volume(256))
  OverFlow_AddOverflowCheckItem(305, 5, true)
  SOUND:WaitMe()
  WINDOW:KeyWait()
  SOUND:PlayMe(SymSnd("ME_REWARD"), Volume(256))
  OverFlow_AddOverflowCheckItem(132, 1, true)
  SOUND:WaitMe()
  WINDOW:CloseMessage()
  CH("ROZERIA"):DirTo(SymPos("P01_ROZERIA"), Speed(350), ROT_TYPE.LEFT)
  CH("ROZERIA"):WaitRotate()
  CH("ROZERIA"):WalkTo(SymPos("P01_ROZERIA"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(SymPos("P01_ROZERIA"), Speed(60), ROT_TYPE.NEAR)
  CH("ROZERIA"):WaitMove()
  CH("ROZERIA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("ROZERIA"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), -84353415)
  WINDOW:Talk(SymAct("ROZERIA"), -471601352)
  WINDOW:Talk(SymAct("ROZERIA"), -925975301)
  subEveCloseMsg()
  CH("SUBOMII"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("SUBOMII")
  })
  WINDOW:DrawFace(72, 16, SymAct("SUBOMII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUBOMII"), -774533702)
  WINDOW:CloseMessage()
  CH("SUBOMII"):ResetManpu()
  CH("SUBOMII"):WalkTo(SplinePath(SymPos("P03_SUBOMII"), SymPos("P04_SUBOMII")), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("ROZERIA"):DirTo(SymPos("P03_SUBOMII"), Speed(200), ROT_TYPE.NEAR)
  CH("ROZERIA"):WaitRotate()
  CH("ROZERIA"):WalkTo(SplinePath(SymPos("P03_SUBOMII"), SymPos("P04_SUBOMII")), Speed(1.5))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(60), ROT_TYPE.LEFT)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(0), Speed(60), ROT_TYPE.LEFT)
  TASK:Sleep(TimeSec(0.7))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("ROZERIA"):WaitMove()
  CH("SUBOMII"):SetVisible(false)
  CH("ROZERIA"):SetVisible(false)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1634460803, PARTNER_1 = -2020660676})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1398638081, PARTNER_1 = -1246148418})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 841045105, PARTNER_1 = 725247280})
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(-397577833)
  WINDOW:Monologue(-246005546)
  WINDOW:CloseMessage()
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(1), Volume(256))
  SOUND:FadeOutBgm(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.2))
  CH("PARTNER"):WaitRotate()
  CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(SymPos("P00_HERO"), Speed(60), ROT_TYPE.NEAR)
  CH("HERO"):WaitMove()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -629468395, PARTNER_1 = -1017109932})
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1943948141, PARTNER_1 = -1791326766})
  WINDOW:SwitchTalk({PARTNER_0 = -1105734127, PARTNER_1 = -1492326576})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(546634655)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  subEveNod(CH("PARTNER"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 965724894, PARTNER_1 = 1357977330})
  WINDOW:SwitchTalk({PARTNER_0 = 1240082355, PARTNER_1 = 1657238640})
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  CH("HERO"):SetVisible(true)
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 2078033201, PARTNER_1 = 882758646})
  WINDOW:SwitchTalk({PARTNER_0 = 763814583, PARTNER_1 = 111915380})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(531660853)
  WINDOW:Monologue(-1742168838)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -2127319621, PARTNER_1 = -853135797})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.CATCHBREATH)
  WINDOW:Monologue(-734191862)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.3))
  CH("PARTNER"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -15708983, PARTNER_1 = -435454584})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1454707889, PARTNER_1 = -1336813042})
  WINDOW:SwitchTalk({PARTNER_0 = -1686337075, PARTNER_1 = -2107131764})
  WINDOW:SwitchTalk({PARTNER_0 = 100639811, PARTNER_1 = 484742402})
  WINDOW:SwitchTalk({PARTNER_0 = 1973045550, PARTNER_1 = 1820424303})
  WINDOW:SwitchTalk({PARTNER_0 = 1202465708, PARTNER_1 = 1589058285})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 301370410, PARTNER_1 = 149798251})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  CH("HERO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("HERO"):WaitNeckRot()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main05_kizunasukaafu01_end()
end
function main05_kizunasukaafu02_init()
end
function main05_kizunasukaafu02_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = 599846568, PARTNER_1 = 987488233})
  WINDOW:SwitchTalk({PARTNER_0 = -1119632602, PARTNER_1 = -1537674649})
  WINDOW:SwitchTalk({PARTNER_0 = 1731192512, PARTNER_1 = 2117392257})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetDefaultGroundFovy()
end
function main05_kizunasukaafu02_end()
end
function main05_kizunasukaafu03_init()
end
function main05_kizunasukaafu03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  GM("SCARF01"):SetVisible(false)
  GM("SCARF01"):SetScale(Scale(0.7))
  GM("SCARF01_2"):SetVisible(false)
  GM("SCARF01_2"):SetScale(Scale(0.7))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1427735618, PARTNER_1 = 1275245827})
  WINDOW:KeyWait()
  TASK:Regist(subEveNoNoNo, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 54731716, PARTNER_1 = 441979525})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 829768006, PARTNER_1 = 678326279})
  WINDOW:CloseMessage()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:WaitTask()
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
  CH("PARTNER"):WaitMove()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SLEEP)
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-40), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  WINDOW:SwitchTalk({PARTNER_0 = -1342804792, PARTNER_1 = -1225958007})
  WINDOW:CloseMessage()
  while true do
    WINDOW:SysMsg(-543981147)
    WINDOW:SelectStart()
    WINDOW:SelectChain(-964120348, 1)
    WINDOW:SelectChain(-307895513, 0)
    WINDOW:DefaultCursor(0)
    local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
    if id == 0 then
      CAMERA:SetEye(SymCam("CAMERA_03"))
      CAMERA:SetTgt(SymCam("CAMERA_03"))
      TASK:Sleep(TimeSec(0.2))
      WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
      WINDOW:Monologue(-188820890)
      WINDOW:Monologue(-1140898655)
      WINDOW:Monologue(-1562085920)
      WINDOW:CloseMessage()
      CAMERA:SetEye(SymCam("CAMERA_02"))
      CAMERA:SetTgt(SymCam("CAMERA_02"))
      TASK:Sleep(TimeSec(0.2))
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
      CH("PARTNER"):WaitManpu()
      WINDOW:SwitchTalk({PARTNER_0 = -1983306205, PARTNER_1 = -1865279646})
      WINDOW:CloseMessage()
    else
      break
    end
  end
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.EMOTION)
  CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
  CH("PARTNER"):WaitNeckRot()
  WINDOW:SwitchTalk({PARTNER_0 = 390728621, PARTNER_1 = 240204524})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -2014277133, PARTNER_1 = -1628725070})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.GLADNESS)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1245252751, PARTNER_1 = -1394752976})
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(2))
  WINDOW:SwitchTalk({PARTNER_0 = -476293897, PARTNER_1 = -91789898})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -777374091, PARTNER_1 = -927922380})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:SwitchTalk({PARTNER_0 = 1328094203, PARTNER_1 = 1446128314})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  GM("SCARF01"):SetVisible(true)
  TASK:Sleep(TimeSec(0.1))
  GM("SCARF01_2"):SetVisible(true)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1062008470, PARTNER_1 = 643286999})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(226137108)
  subEveCloseMsg()
  subEveNod(CH("PARTNER"))
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 341943637, PARTNER_1 = 1528837010})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main05_kizunasukaafu03_end()
end
function main05_kizunasukaafu04_init()
end
function main05_kizunasukaafu04_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV0502"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1111163603, PARTNER_1 = 1763070224})
  WINDOW:SwitchTalk({PARTNER_0 = 1879924817, PARTNER_1 = -141198178})
  WINDOW:SwitchTalk({PARTNER_0 = -292663841, PARTNER_1 = 17425304})
  WINDOW:SwitchTalk({PARTNER_0 = 403886809, PARTNER_1 = 859799834})
  WINDOW:SwitchTalk({PARTNER_0 = 707047515, PARTNER_1 = 1701127836})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(2088638429)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
  SOUND:PlaySe(SymSnd("SE_EVT_SCARF_WEAR"))
  SOUND:WaitSe(SymSnd("SE_EVT_SCARF_WEAR"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1465074718, PARTNER_1 = 1313371487})
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -909088368, PARTNER_1 = -791979823})
  WINDOW:CloseMessage()
end
function main05_kizunasukaafu04_end()
end
function main05_kizunasukaafu05_init()
end
function main05_kizunasukaafu05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetVisibleScarf(true)
  CH("PARTNER"):SetVisibleScarf(true)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):SetManpu("MP_LAUGH_LP")
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1179286275, PARTNER_1 = -1599162948})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:SwitchTalk({PARTNER_0 = -1954290049, PARTNER_1 = -1835477186})
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SwitchTalk({PARTNER_0 = -572964359, PARTNER_1 = -993890120})
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SwitchTalk({PARTNER_0 = -269540485, PARTNER_1 = -151776710})
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("HERO"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("HERO"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("HERO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CH("HERO"):ResetManpu()
  CH("PARTNER"):ResetManpu()
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1902907125, PARTNER_1 = 1752645556})
  WINDOW:SwitchTalk({PARTNER_0 = -1426052333, PARTNER_1 = -1306846638})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1724495471, PARTNER_1 = -2144503600})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(2))
end
function main05_kizunasukaafu05_end()
end
function groundEnd()
end
