dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main15_enteishujinkoushinkaboss2nd01_init()
end
function main15_enteishujinkoushinkaboss2nd01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CH("BUIZERU"):SetMotion(SymMot("EV020_DOWN00"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetScale(Scale(1.4))
  SOUND:PlayBgm(SymSnd("BGM_EVE_HENSHIN_AFTER"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(72, 16, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:Talk(SymAct("ENTEI"), 1121037239)
  WINDOW:Talk(SymAct("ENTEI"), 1540004598)
  WINDOW:CloseMessage()
  CH("ENTEI"):SetScale(Scale(1.2))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("ENTEI"), 1894238517)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CH("ENTEI"):SetScale(Scale(1.3))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("ENTEI"), 1778186356)
  WINDOW:Talk(SymAct("ENTEI"), 649948851)
  WINDOW:Talk(SymAct("ENTEI"), 1067868146)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  subEveFlash2()
  TASK:Sleep(TimeSec(0.2))
  CH("ENTEI"):SetMotion(SymMot("EV015_BARK00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_ROAR"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(344656945)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main15_enteishujinkoushinkaboss2nd01_end()
end
function groundEnd()
end
