dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main12_chousadanninyuudan02_init()
end
function main12_chousadanninyuudan02_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main12_chousadanninyuudan02_end()
end
function main12_chousadanninyuudan03_init()
end
function main12_chousadanninyuudan03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("DENRYUU"):SetVisible(false)
  CH("KUCHIITO"):SetVisible(false)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  elseif pokemonIndexHero == 5 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  end
  local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  if pokemonIndexPartner == 592 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 5 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  end
  CH("AAKEN"):SetManpu("EV_EAT_LP")
  CH("AAKEN"):SetMotionRaito(Raito(2))
  CH("AAKEN"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("HORUBII"):SetManpu("EV_EAT_LP")
  CH("HORUBII"):SetMotionRaito(Raito(2))
  CH("HORUBII"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("EV_EAT_LP")
  CH("DEDENNE"):SetMotionRaito(Raito(2))
  CH("DEDENNE"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("PEROPPAFU"):SetManpu("EV_EAT_LP")
  CH("PEROPPAFU"):SetMotionRaito(Raito(2))
  CH("PEROPPAFU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):SetManpu("EV_EAT_LP")
  CH("BUIZERU"):SetMotionRaito(Raito(2))
  CH("BUIZERU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_03"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_GATSUGATSU_02_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  WINDOW:SysMsg(-1821699104)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1972362591)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1587711646)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1203355613)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-150481180)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-300095579)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-986598298)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-601193177)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(1538431464)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(1118415017)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-52207056)
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_GATSUGATSU_02_LP"), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  local taskBuizeru00 = function()
    CH("BUIZERU"):ResetManpu()
    CH("BUIZERU"):SetMotionRaito(Raito(1))
    CH("BUIZERU"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("BUIZERU"):WaitPlayMotion()
    CH("BUIZERU"):SetManpu("MP_SPREE_LP")
    CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("BUIZERU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local taskAaken00 = function()
    CH("AAKEN"):ResetManpu()
    CH("AAKEN"):SetMotionRaito(Raito(1))
    CH("AAKEN"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("AAKEN"):WaitPlayMotion()
    CH("AAKEN"):SetManpu("MP_LAUGH_LP")
    CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Regist(subEveDoubleJump, {
      CH("AAKEN")
    })
  end
  local taskDedenne00 = function()
    CH("DEDENNE"):ResetManpu()
    CH("DEDENNE"):SetMotionRaito(Raito(1))
    CH("DEDENNE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("DEDENNE"):WaitPlayMotion()
    CH("DEDENNE"):SetManpu("MP_SPREE_LP")
    CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("DEDENNE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Regist(subEveDoubleJump, {
      CH("DEDENNE")
    })
  end
  local taskHorubii00 = function()
    CH("HORUBII"):ResetManpu()
    CH("HORUBII"):SetMotionRaito(Raito(1))
    CH("HORUBII"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("HORUBII"):WaitPlayMotion()
    CH("HORUBII"):SetManpu("MP_SPREE_LP")
    CH("HORUBII"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("HORUBII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Regist(subEveDoubleJump, {
      CH("HORUBII")
    })
  end
  local taskPeropaffu00 = function()
  end
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"), Volume(256))
  TASK:Regist(taskBuizeru00)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskAaken00)
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(taskDedenne00)
  TASK:Regist(taskHorubii00)
  WINDOW:SysMsg(-436710543)
  WINDOW:CloseMessage()
  CH("BUIZERU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.HAPPY)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Talk(SymAct("BUIZERU"), -824901454)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("AAKEN"), -674352653)
  WINDOW:Talk(SymAct("AAKEN"), -1735416012)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("PEROPPAFU"):ResetManpu()
  CH("PEROPPAFU"):SetMotionRaito(Raito(1))
  CH("PEROPPAFU"):SetManpu("MP_LAUGH_LP")
  CH("PEROPPAFU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("PEROPPAFU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(324, 20, SymAct("PEROPPAFU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("PEROPPAFU"), -2120968587)
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(0.5))
  CH("AAKEN"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  WINDOW:CloseMessage()
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("HORUBII"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("AAKEN"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_ANGRY_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):SetManpu("MP_ANGRY_LP")
  CH("DEDENNE"):SetManpu("MP_ANGRY_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("HORUBII"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("BUIZERU")
  })
  WINDOW:DrawFace(20, 20, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("BUIZERU"), -1430665802)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):ResetManpu()
  CH("DEDENNE"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("PEROPPAFU"):ResetManpu()
  TASK:Sleep(TimeSec(0.3))
  CH("AAKEN"):ResetFacialMotion()
  CH("DEDENNE"):ResetFacialMotion()
  CH("BUIZERU"):ResetFacialMotion()
  CH("HORUBII"):ResetFacialMotion()
  CH("PEROPPAFU"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  local taskLookAt00 = function()
    CH("DEDENNE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("BUIZERU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HORUBII"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("DEDENNE"), -1281166089)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 876275768, PARTNER_1 = 757193081})
  WINDOW:SwitchTalk({PARTNER_0 = -296301090, PARTNER_1 = -145884001})
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("BUIZERU")
  })
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-15, 0)
  WINDOW:Talk(SymAct("BUIZERU"), -597643428)
  WINDOW:Talk(SymAct("BUIZERU"), -981754339)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("HORUBII"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(10, 0)
  WINDOW:Talk(SymAct(""), -1975908134)
  WINDOW:Talk(SymAct("HORUBII"), -1826539109)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1207145896, PARTNER_1 = -1592304871})
  WINDOW:SwitchTalk({PARTNER_0 = 646924246, PARTNER_1 = 1066694295})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = 1458219707, PARTNER_1 = 1341234170})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  local taskSurprise00 = function()
    CH("AAKEN"):SetManpu("MP_EXCLAMATION")
    TASK:Regist(subEveJumpSurprise, {
      CH("AAKEN")
    })
    TASK:Sleep(TimeSec(0.1))
    CH("BUIZERU"):SetManpu("MP_SHOCK_L")
    CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
    CH("HORUBII"):SetManpu("MP_EXCLAMATION")
    TASK:Regist(subEveJumpSurprise, {
      CH("PEROPPAFU")
    })
    CH("PEROPPAFU"):SetManpu("MP_SHOCK_L")
    CH("PEROPPAFU"):WaitManpu()
  end
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  TASK:Regist(taskSurprise00)
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-10, -5)
  WINDOW:Talk(SymAct("AAKEN"), 1692190777)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_FLY_SWEAT")
  CH("BUIZERU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.SAD)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Talk(SymAct("BUIZERU"), 2110257528)
  WINDOW:Talk(SymAct("BUIZERU"), 847671231)
  WINDOW:Talk(SymAct("BUIZERU"), 731733758)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_FLY_SWEAT")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("DEDENNE"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DEDENNE"), 11537725)
  WINDOW:Talk(SymAct("DEDENNE"), 430652540)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1640816461, PARTNER_1 = -2027417102})
  WINDOW:SwitchTalk({PARTNER_0 = -885157374, PARTNER_1 = -769219773})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveDoubleJump, {
    CH("HERO")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -116658048, PARTNER_1 = -535772735})
  TASK:WaitTask()
  WINDOW:KeyWait()
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  WINDOW:SwitchTalk({PARTNER_0 = -1353623802, PARTNER_1 = -1236638137})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveJump, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(324, 20, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1654180476)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("BUIZERU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  WINDOW:CloseMessage()
  CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("AAKEN"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("BUIZERU")
  })
  WINDOW:DrawFace(20, 20, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("BUIZERU"), -2072247099)
  WINDOW:CloseMessage()
  CH("BUIZERU"):ResetManpu()
  CH("BUIZERU"):ResetFacialMotion()
  CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("HORUBII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("HORUBII"), 65280010)
  WINDOW:Talk(SymAct("HORUBII"), 452929867)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT")
  CH("PEROPPAFU"):WaitManpu()
  WINDOW:DrawFace(172, 8, SymAct("PEROPPAFU"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1937896807)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(3.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("AAKEN")
  })
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("AAKEN"), 1788527654)
  WINDOW:KeyWait()
  CH("AAKEN"):ResetManpu()
  WINDOW:Talk(SymAct("AAKEN"), 1102551013)
  subEveCloseMsg()
  local taskSurprise01 = function()
    CH("AAKEN"):ResetFacialMotion()
    CH("AAKEN"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("BUIZERU"):SetManpu("MP_NOTICE_R")
    CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("HORUBII"):SetManpu("MP_EXCLAMATION")
    CH("PEROPPAFU"):SetManpu("MP_NOTICE_R")
    CH("PEROPPAFU"):WaitManpu()
  end
  CH("DENRYUU"):SetVisible(true)
  CH("KUCHIITO"):SetVisible(true)
  WINDOW:Talk(SymAct("DENRYUU"), 1487709860)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  TASK:Regist(taskSurprise01)
  WINDOW:CloseMessage()
  TASK:WaitTask()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("AAKEN"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(324, 20, SymAct("BUIZERU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BUIZERU"), 401420387)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 251003170)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), 635130593)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1019241376, PARTNER_1 = -1151828113})
  WINDOW:SwitchTalk({PARTNER_0 = -1572647378, PARTNER_1 = 1630821001})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_08"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DENRYUU"):WalkTo(SymPos("P00_DENRYUU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):WalkTo(SymPos("P00_KUCHIITO"), Speed(1.5))
  CH("DENRYUU"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), 2016373704)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  TASK:Regist(taskSurprise01)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 20, SymAct("HORUBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HORUBII"), 1392654347)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1243154762)
  WINDOW:Talk(SymAct("DENRYUU"), 89694093)
  WINDOW:CloseMessage()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("DENRYUU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(9, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE01"), LOOP.ON)
  CH("DENRYUU"):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("DENRYUU"), 474197708)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  TASK:Regist(taskSurprise00)
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("AAKEN"), 930020623)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_FLY_SWEAT")
  CH("BUIZERU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-15, 0)
  WINDOW:Talk(SymAct("BUIZERU"), 779471950)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("DENRYUU"):ResetManpu()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.25))
  TASK:Sleep(TimeSec(0.25))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1444032383)
  WINDOW:Talk(SymAct("DENRYUU"), -1325997632)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("AAKEN"):SetManpu("MP_SWEAT_R")
  CH("BUIZERU"):SetManpu("MP_SWEAT_L")
  CH("DEDENNE"):SetManpu("MP_SWEAT_L")
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_NOTICE_R")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -645382676)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DEDENNE"), -1064104787)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DENRYUU"), -339845266)
  WINDOW:Talk(SymAct("DENRYUU"), -224039377)
  WINDOW:CloseMessage()
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("DENRYUU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(9, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("EV006_POSE01"), LOOP.ON)
  CH("DENRYUU"):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("DENRYUU"), -1109067544)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  TASK:Regist(taskSurprise00)
  WINDOW:DrawFace(324, 20, SymAct("HORUBII"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(10, 0)
  WINDOW:Talk(SymAct("HORUBII"), -1526740567)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("DENRYUU"):ResetManpu()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.25))
  TASK:Sleep(TimeSec(0.25))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1882023318)
  WINDOW:Talk(SymAct("DENRYUU"), -1765168341)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("AAKEN"):SetManpu("MP_SWEAT_R")
  CH("BUIZERU"):SetManpu("MP_SWEAT_L")
  CH("DEDENNE"):SetManpu("MP_SWEAT_L")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:Talk(SymAct("BUIZERU"), 290568164)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("HORUBII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("HORUBII"), 139101861)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -2115293766)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  local taskBuizeru01 = function()
    subEveNod(CH("BUIZERU"))
  end
  local taskAaken01 = function()
    subEveNod(CH("AAKEN"))
  end
  local taskHorubii01 = function()
    subEveNod(CH("HORUBII"))
  end
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  TASK:Regist(taskBuizeru01)
  TASK:Regist(taskAaken01)
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(taskHorubii01)
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1729094405)
  WINDOW:Talk(SymAct("DENRYUU"), -1277341896)
  WINDOW:Talk(SymAct("DENRYUU"), -1429832071)
  WINDOW:Talk(SymAct("DENRYUU"), -444077890)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveJump, {
    CH("HERO")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -56829441, PARTNER_1 = -676230596})
  WINDOW:SwitchTalk({PARTNER_0 = -827671683, PARTNER_1 = 1228056498})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_LAUGH_LP")
  CH("DEDENNE"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):SetManpu("MP_SPREE_LP")
  CH("PEROPPAFU"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("HORUBII"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(1))
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("DEDENNE"), 1344902899)
  subEveCloseMsg()
  CH("DEDENNE"):ResetFacialMotion()
  CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.HAPPY)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Talk(SymAct("BUIZERU"), 962022111)
  WINDOW:CloseMessage()
  CH("BUIZERU"):ResetFacialMotion()
  SOUND:FadeOutBgm(TimeSec(1))
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(0.5))
  CH("BUIZERU"):ResetManpu()
  CH("PEROPPAFU"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Regist(subEveDoubleJump, {
    CH("BUIZERU")
  })
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Talk(SymAct("BUIZERU"), 541883294)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main12_chousadanninyuudan03_end()
end
function main12_chousadanninyuudan04_init()
end
function main12_chousadanninyuudan04_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1203"))
  MAP:SetVisibleBG(true)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("BUIZERU"), 190916701)
  WINDOW:Talk(SymAct("BUIZERU"), 309991708)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_chousadanninyuudan04_end()
end
function main12_chousadanninyuudan05_init()
end
function main12_chousadanninyuudan05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Regist(subEveDoubleJump, {
    CH("AAKEN")
  })
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("AAKEN"), 1564184539)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main12_chousadanninyuudan05_end()
end
function main12_chousadanninyuudan06_init()
end
function main12_chousadanninyuudan06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1204"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("AAKEN"), 1142996634)
  WINDOW:Talk(SymAct("AAKEN"), 1863183705)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_chousadanninyuudan06_end()
end
function main12_chousadanninyuudan07_init()
end
function main12_chousadanninyuudan07_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1205"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("DEDENNE"), 1981209624)
  WINDOW:Talk(SymAct("DEDENNE"), -242302761)
  WINDOW:Talk(SymAct("DEDENNE"), -392826474)
  WINDOW:Talk(SymAct("DEDENNE"), -496636312)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_chousadanninyuudan07_end()
end
function main12_chousadanninyuudan08_init()
end
function main12_chousadanninyuudan08_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1206"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("HORUBII"), -75571415)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_chousadanninyuudan08_end()
end
function main12_chousadanninyuudan09_init()
end
function main12_chousadanninyuudan09_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1207"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("PEROPPAFU"), -799830806)
  WINDOW:Talk(SymAct("PEROPPAFU"), -917979733)
  WINDOW:Talk(SymAct("PEROPPAFU"), -2046219412)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("BUIZERU"), -1626203603)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_chousadanninyuudan09_end()
end
function main12_chousadanninyuudan10_init()
end
function main12_chousadanninyuudan10_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1208"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("KUCHIITO"), -1270920722)
  WINDOW:Talk(SymAct("KUCHIITO"), -1390118737)
  WINDOW:Talk(SymAct("KUCHIITO"), 716989536)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_chousadanninyuudan10_end()
end
function main12_chousadanninyuudan11_init()
end
function main12_chousadanninyuudan11_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("IMEV1209"))
  MAP:SetVisibleBG(true)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:Talk(SymAct("DENRYUU"), 866604321)
  WINDOW:Talk(SymAct("DENRYUU"), 1524205837)
  WINDOW:Talk(SymAct("DENRYUU"), 1136834636)
  WINDOW:Talk(SymAct("DENRYUU"), 1760553871)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_chousadanninyuudan11_end()
end
function main12_chousadanninyuudan12_init()
end
function main12_chousadanninyuudan12_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  elseif pokemonIndexHero == 5 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  end
  local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  if pokemonIndexPartner == 592 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 5 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  end
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Talk(SymAct("DEDENNE"), 1911872206)
  WINDOW:Talk(SymAct("DEDENNE"), 1052068873)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.1))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 665746760)
  WINDOW:Talk(SymAct("DENRYUU"), 209923723)
  WINDOW:Talk(SymAct("DENRYUU"), 362291146)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.LEFT)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1845492987, PARTNER_1 = -1961151932})
  WINDOW:SwitchTalk({PARTNER_0 = 1215047395, PARTNER_1 = 1366759330})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main12_chousadanninyuudan12_end()
end
function main12_chousadanninyuudan13_init()
end
function main12_chousadanninyuudan13_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 2052736097, PARTNER_1 = 1665234208})
  WINDOW:SwitchTalk({PARTNER_0 = 738255847, PARTNER_1 = 891015846})
  subEveCloseMsg()
  CH("DENRYUU"):ResetNeckRot(TimeSec(0.1))
  CH("DENRYUU"):WaitNeckRot()
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(60), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 506888549)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 120434724, PARTNER_1 = -2135577365})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
end
function main12_chousadanninyuudan13_end()
end
function main12_chousadanninyuudan14_init()
end
function main12_chousadanninyuudan14_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  elseif pokemonIndexHero == 5 then
    CH("HERO"):SetPosition(SymPos("SP00_HERO"))
  end
  local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  if pokemonIndexPartner == 592 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  elseif pokemonIndexPartner == 5 then
    CH("PARTNER"):SetPosition(SymPos("SP00_PARTNER"))
  end
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1716609622, PARTNER_1 = -254787194})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00_2"))
  CAMERA:SetTgt(SymCam("CAMERA_00_2"))
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -372543289)
  WINDOW:KeyWait()
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), -1025105148)
  WINDOW:Talk(SymAct("DENRYUU"), -604171707)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("HERO"):SetMotionRaito(Raito(2))
  CH("DENRYUU"):SetMotion(SymMot("EV012_POINT00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("HERO"):SetMotionRaito(Raito(1))
  CH("DENRYUU"):SetMotion(SymMot("EV012_POINT01"), LOOP.ON)
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("DENRYUU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), -1799584638)
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("AAKEN")
  })
  CH("BUIZERU"):SetManpu("MP_SHOCK_L")
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("PEROPPAFU")
  })
  CH("PEROPPAFU"):SetManpu("MP_SHOCK_L")
  CH("PEROPPAFU"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DENRYUU"):ResetFacialMotion()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(-40, 0)
  WINDOW:Talk(SymAct("DEDENNE"), -1918388797)
  WINDOW:CloseMessage()
  CH("DEDENNE"):ResetManpu()
  CH("DEDENNE"):ResetFacialMotion()
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir, {
    CH("DEDENNE"),
    SymPos("P00_DEDENNE"),
    Speed(1.5),
    CH("PEROPPAFU")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("PEROPPAFU"),
    SymPos("P00_PEROPPAFU"),
    Speed(2),
    SymPos("P00_DEDENNE")
  })
  TASK:Regist(subEveMoveDir, {
    CH("BUIZERU"),
    SymPos("P00_BUIZERU"),
    Speed(2),
    CH("HORUBII")
  })
  CH("HORUBII"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("AAKEN"),
    SymPos("P00_AAKEN"),
    Speed(2),
    RotateTarget(90)
  })
  TASK:WaitTask()
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_WAIWAI_LP"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("AAKEN"), -1500846592)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUIZERU"), -1080961215)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 940166030)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetDir(CH("PEROPPAFU"))
  CH("KUCHIITO"):SetDir(CH("PEROPPAFU"))
  CH("HERO"):SetDir(CH("PEROPPAFU"))
  CH("PARTNER"):SetDir(CH("PEROPPAFU"))
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_SHOCK_R")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DENRYUU"), 554891983)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_FLY_SWEAT")
  CH("DENRYUU"):WaitManpu()
  SOUND:FadeOutSe(SymSnd("SE_EVT_WAIWAI_LP"), TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("AAKEN"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PEROPPAFU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PEROPPAFU"):WaitRotate()
  CH("AAKEN"):SetManpu("MP_SPREE_LP")
  CH("DEDENNE"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):SetManpu("MP_LAUGH_LP")
  CH("HORUBII"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("PEROPPAFU"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_FLY_SWEAT")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DENRYUU"), 1829206335)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("AAKEN"):ResetManpu()
  CH("DEDENNE"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("PEROPPAFU"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 1948010622)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):DirLockToChara(CH("DEDENNE"))
  CH("PARTNER"):DirLockToChara(CH("DEDENNE"))
  CH("HORUBII"):DirLockToChara(CH("DEDENNE"))
  CH("BUIZERU"):DirLockToChara(CH("DEDENNE"))
  CH("AAKEN"):DirLockToChara(CH("DEDENNE"))
  CH("PEROPPAFU"):DirLockToChara(CH("DEDENNE"))
  CH("DENRYUU"):DirLockToChara(CH("DEDENNE"))
  CH("KUCHIITO"):DirLockToChara(CH("DEDENNE"))
  CH("DEDENNE"):RunTo(SplinePath(SymPos("P01_DEDENNE"), SymPos("P02_DEDENNE")), Speed(3))
  CH("DEDENNE"):WaitMove()
  CH("DEDENNE"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirLockOff()
  CH("PARTNER"):DirLockOff()
  CH("HORUBII"):DirLockOff()
  CH("BUIZERU"):DirLockOff()
  CH("AAKEN"):DirLockOff()
  CH("PEROPPAFU"):DirLockOff()
  CH("DENRYUU"):DirLockOff()
  CH("KUCHIITO"):DirLockOff()
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 1597053885)
  WINDOW:Talk(SymAct("DEDENNE"), 1177168636)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  WINDOW:SwitchTalk({PARTNER_0 = 158055483, PARTNER_1 = 275811706})
  WINDOW:CloseMessage()
  CH("DEDENNE"):WalkTo(SymPos("P03_DEDENNE"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(SymPos("P03_DEDENNE"), Speed(60), ROT_TYPE.NEAR)
  CH("KUCHIITO"):DirTo(SymPos("P03_DEDENNE"), Speed(60), ROT_TYPE.NEAR)
  CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(1.5))
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFaceF(172, 8, SymAct("DENRYUU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DENRYUU"), 996007609)
  TASK:Sleep(TimeSec(2))
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("DEDENNE"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("BUIZERU"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("PEROPPAFU"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUIZERU"), 575074296)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetDir(CH("PEROPPAFU"))
  CH("KUCHIITO"):SetDir(CH("PEROPPAFU"))
  local taskBuizeru01 = function()
    subEveNod(CH("BUIZERU"))
  end
  local taskAaken01 = function()
    subEveNod(CH("AAKEN"))
  end
  local taskHorubii01 = function()
    subEveNod(CH("HORUBII"))
  end
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  TASK:Regist(taskBuizeru01)
  TASK:Regist(taskAaken01)
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(taskHorubii01)
  TASK:Sleep(TimeSec(1))
  CH("DENRYUU"):DirLockToChara(CH("PEROPPAFU"))
  CH("KUCHIITO"):DirLockToChara(CH("PEROPPAFU"))
  CH("HORUBII"):WalkTo(SplinePath(SymPos("P01_HORUBII"), SymPos("P02_HORUBII"), SymPos("P03_HORUBII")), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("PEROPPAFU"):WalkTo(SplinePath(SymPos("P01_PEROPPAFU"), SymPos("P02_PEROPPAFU"), SymPos("P03_PEROPPAFU"), SymPos("P04_PEROPPAFU")), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):WalkTo(SplinePath(SymPos("P01_BUIZERU"), SymPos("P02_BUIZERU"), SymPos("P03_BUIZERU"), SymPos("P04_BUIZERU")), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):WalkTo(SplinePath(SymPos("P01_AAKEN"), SymPos("P02_AAKEN"), SymPos("P03_AAKEN"), SymPos("P04_AAKEN")), Speed(2))
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(1.5))
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -1512115401)
  TASK:Sleep(TimeSec(1.5))
  CH("DENRYUU"):DirLockOff()
  CH("KUCHIITO"):DirLockOff()
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("DENRYUU"):SetMotion(SymMot("EV012_DEPRESS00"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("EV012_DEPRESS01"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DENRYUU"), -1127890314)
  WINDOW:CloseMessage()
  CH("KUCHIITO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -709157286)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DENRYUU"), -861917413)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KUCHIITO"):SetManpu("MP_FLY_SWEAT")
  CH("KUCHIITO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -410157864)
  WINDOW:KeyWait()
  WINDOW:Talk(SymAct("KUCHIITO"), -23704167)
  WINDOW:Talk(SymAct("KUCHIITO"), -1311253666)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetMotion(SymMot("EV012_DEPRESS02"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1462965729)
  WINDOW:Talk(SymAct("DENRYUU"), -2082358820)
  WINDOW:Talk(SymAct("DENRYUU"), -1694857059)
  WINDOW:Talk(SymAct("DENRYUU"), 492999762)
  WINDOW:Talk(SymAct("DENRYUU"), 75080979)
  WINDOW:Talk(SymAct("DENRYUU"), -955338316)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
end
function main12_chousadanninyuudan14_end()
end
function main12_chousadanninyuudan15_init()
end
function main12_chousadanninyuudan15_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Regist(subEveMoveDir, {
    CH("DEDENNE"),
    SymPos("P00_DEDENNE"),
    Speed(1.5),
    RotateTarget(0)
  })
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  local taskPartner00 = function()
    CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(1.5))
    CH("PARTNER"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):SetManpu("MP_SPREE_LP")
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  TASK:Regist(taskPartner00)
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_04"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1.5))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -569016075)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -180825290, PARTNER_1 = -333192585})
  TASK:WaitTask()
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -1553828688)
  WINDOW:Talk(SymAct("DEDENNE"), -1166457359)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1856760270, PARTNER_1 = -2008078477})
  WINDOW:SwitchTalk({PARTNER_0 = 265763772, PARTNER_1 = 382470909})
  subEveCloseMsg()
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("DEDENNE"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), 2142426833)
  WINDOW:Talk(SymAct("DEDENNE"), 1722410896)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.RELIEF)
  WINDOW:SwitchTalk({PARTNER_0 = 1300542547, PARTNER_1 = 1419740434})
  subEveCloseMsg()
  CH("DEDENNE"):ResetFacialMotion()
  CH("DEDENNE"):ResetManpu()
  WINDOW:DrawFace(272, 16, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), 467538901)
  WINDOW:Talk(SymAct("DEDENNE"), 46473876)
  WINDOW:Talk(SymAct("DEDENNE"), 703099223)
  WINDOW:Talk(SymAct("DEDENNE"), 821248022)
  WINDOW:CloseMessage()
  CH("DEDENNE"):WalkTo(SymPos("P01_DEDENNE"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.LEFT)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1217700647, PARTNER_1 = -1368363624})
  TASK:Sleep(TimeSec(1))
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 668059271, PARTNER_1 = 1053489094})
  TASK:WaitTask()
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("HERO")
  })
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.EMOTION)
  WINDOW:Monologue(367502341)
  TASK:WaitTask()
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 217879876, PARTNER_1 = 1136460675})
  WINDOW:SwitchTalk({PARTNER_0 = 1520841410, PARTNER_1 = 1904959745})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"), Volume(256))
  local taskPartner01 = function()
    CH("PARTNER"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetManpu("MP_SPREE_LP")
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
    CH("PARTNER"):SetMotionRaito(Raito(2))
  end
  TASK:Regist(taskPartner01)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.GLADNESS)
  WINDOW:SwitchTalk({PARTNER_0 = 1754288192, PARTNER_1 = -284668785})
  CH("HERO"):SetManpu("MP_LAUGH_LP")
  TASK:WaitTask()
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(2))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("HERO"):DirTo(SymPos("P02_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  TASK:Regist(subEveDoubleJump, {
    CH("HERO")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(1))
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):WalkTo(SymPos("P03_PARTNER"), Speed(2))
  CH("HERO"):DirTo(SymPos("P03_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  TASK:Regist(taskPartner01)
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("HERO")
  })
  TASK:Sleep(TimeSec(1.5))
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(0.5))
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):ResetFacialMotion()
  CH("HERO"):ResetManpu()
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -166494770, PARTNER_1 = -1620205086})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -2039050077, PARTNER_1 = -1386495136})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1270812127, PARTNER_1 = -83794714})
  WINDOW:SwitchTalk({PARTNER_0 = -501590617, PARTNER_1 = -919140764})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function main12_chousadanninyuudan15_end()
end
function groundEnd()
end
