dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main05_kannrosougenboss2nd01_init()
end
function main05_kannrosougenboss2nd01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SUBOMII"):SetManpu("MP_FLY_SWEAT_LP")
  CH("SUBOMII"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  SOUND:PlayBgm(SymSnd("BGM_EVE_TENSION_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("SUBOMII"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("SUBOMII"), -461388066)
  WINDOW:CloseMessage()
  CH("SUBOMII"):ResetManpu()
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(4))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(4))
  CH("PARTNER"):WaitMove()
  CH("SUBOMII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("SUBOMII"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -43714657, PARTNER_1 = -699816868})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("MITSUHANII4"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("MITSUHANII4"), Speed(350), ROT_TYPE.NEAR)
    CH("SUBOMII"):DirTo(CH("MITSUHANII4"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SUPIAA3"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 20, SymAct("SUPIAA3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUPIAA"), -816671459)
  subEveCloseMsg()
  CH("MITSUHANII4"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(72, 16, SymAct("MITSUHANII4"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MITSUHANII4"), -2146237478)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1727516005, PARTNER_1 = -1306173096})
  WINDOW:CloseMessage()
  CH("SUBOMII"):SetManpu("MP_FLY_SWEAT")
  CH("SUBOMII"):RunTo(SymPos("P02_SUBOMII"), Speed(4))
  TASK:Sleep(TimeSec(0.7))
  CH("SUPIAA3"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 20, SymAct("SUPIAA3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUPIAA"), -1421979623)
  WINDOW:CloseMessage()
  CH("SUPIAA2"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("SUPIAA3"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  subEveFlash2()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main05_kannrosougenboss2nd01_end()
end
function groundEnd()
end
