dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main01_jyobantougetry1st01_init()
end
function main01_jyobantougetry1st01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  SOUND:PlayBgm(SymSnd("BGM_EVE_TENSION_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KONOHANA"):RunTo(SymPos("P00_KONOHANA"), Speed(4))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(4))
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("KONOHANA"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 2001230648)
  subEveCloseMsg()
  WINDOW:Talk(SymAct(""), 1850960505)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(-90), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):DirTo(RotateTarget(-90), Speed(500), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("KONOHANA"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(272, 16, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 1165900218)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  SOUND:PlaySe(SymSnd("SE_EVT_FOOT_STEP_01_LP"))
  CH("KONOHANA"):RunTo(SymPos("P01_KONOHANA"), Speed(4))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(4))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_FOOT_STEP_01_LP"), TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main01_jyobantougetry1st01_end()
end
function groundEnd()
end
