dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main11_obemunouwasa01_init()
end
function main11_obemunouwasa01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SplinePath(SymPos("P00_HERO"), SymPos("P00_5_HERO")), Speed(1.5))
  CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P00_5_PARTNER")), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("ROZERIA"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CH("ROZERIA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  subEveNodDouble(CH("RATTA"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("ROZERIA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("ROZERIA"), -269209908)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("RATTA"), -152100979)
  CH("HERO"):WalkTo(SplinePath(SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SplinePath(SymPos("P01_PARTNER"), SymPos("P02_PARTNER")), Speed(2))
  subEveCloseMsg()
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -574469042, PARTNER_1 = -992379633})
  WINDOW:CloseMessage()
  CH("RATTA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("ROZERIA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("RATTA"):WaitRotate()
  CH("HERO"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -1952912440)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1836852599, PARTNER_1 = -1179743926})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -1598703605)
  WINDOW:Talk(SymAct("RATTA"), 657302724)
  WINDOW:Talk(SymAct("RATTA"), 1043764613)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1648740080)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("ROZERIA"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("ROZERIA"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("RATTA"):DirTo(CH("ROZERIA"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), -2069821359)
  WINDOW:Talk(SymAct("ROZERIA"), -1349756014)
  WINDOW:Talk(SymAct("ROZERIA"), -1231590701)
  subEveCloseMsg()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.1))
    CH("ROZERIA"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  TASK:Regist(subEveDoubleJump, {
    CH("RATTA")
  })
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("RATTA"), -103351276)
  WINDOW:Talk(SymAct("RATTA"), -523383467)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-874471786)
  WINDOW:Monologue(-755257385)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), 1432597272)
  WINDOW:CloseMessage()
  CH("ROZERIA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("ROZERIA"):WaitRotate()
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.1))
    CH("RATTA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("ROZERIA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("ROZERIA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  WINDOW:DrawFace(324, 88, SymAct("ROZERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ROZERIA"), 1282966105)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.7))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
end
function main11_obemunouwasa01_end()
end
function groundEnd()
end
