dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main12_yamawokoete01_init()
end
function main12_yamawokoete01_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_TABIDACHI_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -252212696)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -370361495)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1027479382)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -606414357)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1801760980)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(3))
  TASK:Sleep(TimeSec(3.5))
end
function main12_yamawokoete01_end()
end
function main12_yamawokoete02_init()
end
function main12_yamawokoete02_start()
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("WALLPAPER_MAIN_CAPTURE_BG01"))
  MAP:SetVisibleBG(true)
  WINDOW:BeginChapter()
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  SCREEN_A:FadeIn(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(1), false)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Chapter(TimeSec(1.5), TimeSec(1.5), -1920958867)
  TASK:Sleep(TimeSec(3))
  SCREEN_A:FadeOutAll(TimeSec(1), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  WINDOW:EndChapter()
  WINDOW:ForceCloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main12_yamawokoete02_end()
end
function main12_yamawokoete03_init()
end
function main12_yamawokoete03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskHero00 = function()
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2))
    CH("HERO"):WaitMove()
    CH("HERO"):DirTo(RotateTarget(160), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.8))
    CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(2.5))
    CH("HERO"):WaitMove()
  end
  local taskPartner00 = function()
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(RotateTarget(160), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):WaitManpu()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(2.5))
    CH("PARTNER"):WaitMove()
  end
  TASK:Regist(Group("grpHero"), taskHero00)
  TASK:Regist(Group("grpPartner"), taskPartner00)
  SOUND:FadeInEnv(SymSnd("SE_ENV_CLIFF_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:WaitTask(Group("grpPartner"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1498600018, PARTNER_1 = -1078584081})
  WINDOW:SwitchTalk({PARTNER_0 = 942538784, PARTNER_1 = 557134177})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1980987146, PARTNER_1 = 1862813259})
  WINDOW:SwitchTalk({PARTNER_0 = 1143281032, PARTNER_1 = 1564353737})
  WINDOW:SwitchTalk({PARTNER_0 = 310358542, PARTNER_1 = 191136591})
  WINDOW:SwitchTalk({PARTNER_0 = 541708428, PARTNER_1 = 961733069})
  WINDOW:SwitchTalk({PARTNER_0 = -1093993214, PARTNER_1 = -1479422909})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main12_yamawokoete03_end()
end
function groundEnd()
end
