dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main06_kakureonnotokoroheikou01_init()
end
function main06_kakureonnotokoroheikou01_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("TSUNAGARI_OVUM"):SetVisible(false)
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(SymPos("P00_HERO"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 350611178, PARTNER_1 = 234805163})
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(SymPos("P00_PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  CH("HERO"):DirTo(GM("TSUNAGARI_OVUM"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  GM("TSUNAGARI_OVUM"):SetVisible(true)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 651396200, PARTNER_1 = 1070118185})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1888035822, PARTNER_1 = 1771180719})
  WINDOW:SwitchTalk({PARTNER_0 = 1119830380, PARTNER_1 = 1537503277})
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  GM("TSUNAGARI_OVUM"):SetVisible(false)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main06_kakureonnotokoroheikou01_end()
end
function groundEnd()
end
