dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_inisienohoneatoboss1st01_init()
end
function main09_inisienohoneatoboss1st01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 758124192, PARTNER_1 = 875249633})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("NYASUPAA"), 520514594)
  WINDOW:Talk(SymAct("NYASUPAA"), 102587747)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1230818212, PARTNER_1 = 1346894565})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskNyasupaa00 = function()
    CH("NYASUPAA"):RunTo(SymPos("P00_NYASUPAA"), Speed(3))
    CH("NYASUPAA"):WaitMove()
    CH("NYASUPAA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("NYASUPAA"), Speed(600))
  end
  local taskShikijika00 = function()
    CH("SHIKIJIKA_SPRING"):RunTo(SymPos("P00_SHIKIJIKA"), Speed(3))
    CH("SHIKIJIKA_SPRING"):WaitMove()
    CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("SHIKIJIKA_SPRING"), Speed(600))
  end
  local taskHero00 = function()
    CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
    CH("HERO"):WaitMove()
    subEveLookAround(CH("HERO"), Speed(600))
  end
  local taskPartner00 = function()
    CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  local taskNumera00 = function()
    CH("NUMERA"):RunTo(SymPos("P00_NUMERA"), Speed(3))
    CH("NUMERA"):WaitMove()
    TASK:Sleep(TimeSec(0.2))
    CH("NUMERA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
    CH("NUMERA"):WaitRotate()
  end
  TASK:Regist(Group("grpNyasupaa"), taskNyasupaa00)
  TASK:Regist(Group("grpShikijika"), taskShikijika00)
  TASK:Regist(Group("grpHero"), taskHero00)
  TASK:Regist(Group("grpPartner"), taskPartner00)
  TASK:Regist(Group("grpNumera"), taskNumera00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:WaitTask()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2070587686, PARTNER_1 = 1651611751})
  WINDOW:SwitchTalk({PARTNER_0 = -437680984, PARTNER_1 = -51202583})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  local taskNyasupaa01 = function()
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    CH("NYASUPAA"):WaitManpu()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("NYASUPAA"), Speed(600))
  end
  local taskShikijika01 = function()
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
    CH("SHIKIJIKA_SPRING"):WaitManpu()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("SHIKIJIKA_SPRING"), Speed(600))
  end
  local taskHero01 = function()
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):WaitManpu()
    subEveLookAround(CH("HERO"), Speed(600))
  end
  local taskPartner01 = function()
    CH("PARTNER"):SetManpu("MP_SHOCK_R")
    CH("PARTNER"):WaitManpu()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  local taskNumera01 = function()
    CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
    CH("NUMERA"):WaitManpu()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("NUMERA"), Speed(600))
  end
  TASK:Regist(Group("grpNyasupaa"), taskNyasupaa01)
  TASK:Regist(Group("grpShikijika"), taskShikijika01)
  TASK:Regist(Group("grpHero"), taskHero01)
  TASK:Regist(Group("grpPartner"), taskPartner01)
  TASK:Regist(Group("grpNumera"), taskNumera01)
  local taskObake00 = function()
    EFFECT:StartMotionBlur(0, 0, 0)
    EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.4))
    EFFECT:ChangeMotionBlurAlpha(0.5, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.5))
    EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.4))
    TASK:Sleep(TimeSec(0.4))
    EFFECT:EndMotionBlur()
  end
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(1872560055)
  WINDOW:SysMsg(1988611830)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  CH("NUMERA"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), 1571462453)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1152494708)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  local taskOdoroku00 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    TASK:Regist(subEveJump, {
      CH("PARTNER")
    })
    CH("NUMERA"):SetManpu("MP_SHOCK_R")
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskOdoroku00)
  SOUND:PlaySe(SymSnd("SE_EVT_OBAKE"))
  TASK:Regist(taskObake00)
  WINDOW:SysMsg(200293043)
  WINDOW:SysMsg(317393906)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  WINDOW:DrawFaceF(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 969300017)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  WINDOW:DrawFaceF(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 551381360)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1488620097)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1101118210)
  WINDOW:SysMsg(2099859545)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFaceF(20, 20, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1681023256, PARTNER_1 = 1327444699})
  WINDOW:SwitchTalk({PARTNER_0 = 1443103642, PARTNER_1 = 423990621})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  WINDOW:SysMsg(6202396)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.1))
end
function main09_inisienohoneatoboss1st01_end()
end
function main09_inisienohoneatoboss1st02_init()
end
function main09_inisienohoneatoboss1st02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SAJI:CreateSajiPlayer("kage_03", "EV09_050_04_03")
  SJ("kage_03"):Play(LOOP.ON)
  SJ("kage_03"):SetVisible(false)
  SJ("kage_03"):ChangeAlpha(0, TimeSec(0))
  SJ("kage_03"):SetPosition(Vector2(200, 120))
  SJ("kage_03"):SetDrawPriority(1024)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("YANCHAMU"):SetScale(Scale(0, 4, 0))
  CH("CHOBOMAKI"):SetScale(Scale(0, 4, 0))
  CH("YANCHAMU"):SetShadow(false)
  CH("CHOBOMAKI"):SetShadow(false)
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("YANCHAMU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("CHOBOMAKI"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFaceF(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 729020383, PARTNER_1 = 845727390})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.1))
  WINDOW:SysMsg(-1242506671)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1393825008, PARTNER_1 = -980076740})
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_03"), Volume(256))
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(1.5))
  SJ("kage_03"):SetVisible(true)
  SJ("kage_03"):ChangeAlpha(1, TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:MoveFollow2(SymCam("CAMERA_08_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  local taskFlash = function()
    subEveFlash2()
  end
  TASK:Regist(taskFlash)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_R")
  CH("NUMERA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("NUMERA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(2))
  SOUND:FadeOutEnv(TimeSec(0.5))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -594672003, PARTNER_1 = -140290626})
  CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  subEveCloseMsg()
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:DrawFace(72, 16, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -289905409)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1577455048)
  WINDOW:SysMsg(-1193098375)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_R")
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1815113542, PARTNER_1 = -1965776389})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  SJ("kage_03"):SetVisible(false)
  CAMERA:SetDefaultGroundFovy()
  SCREEN_A:FadeChange(Level(0), Level(0.5), TimeSec(0), false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.FAINT)
  CH("PARTNER"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  TASK:Sleep(TimeSec(1))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("SHIKIJIKA_SPRING"):ResetNeckRot(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 223132980)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 341281909)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(1))
  SJ("kage_03"):SetVisible(true)
  SCREEN_A:FadeChange(Level(0), Level(0), TimeSec(0), false)
  CAMERA:SetEye(SymCam("CAMERA_08_5"))
  CAMERA:SetTgt(SymCam("CAMERA_08_5"))
  CAMERA:SetFovy(SymCam("CAMERA_08_5"))
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  WINDOW:SysMsg(1480724357)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("NYASUPAA"):SetManpu("MP_QUESTION")
  CH("NYASUPAA"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1096367812)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"))
  SJ("kage_03"):ChangeAlpha(0, TimeSec(1.5))
  TASK:Sleep(TimeSec(2.5))
  SAJI:DestroySajiPlayer("kage_03")
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_BUWAN"))
  EFFECT:Create("effectBarrier01", SymEff("EV_BARRIER_LP"))
  EFFECT:SetPosition("effectBarrier01", SymPos("P_EFF_BARRIER01"))
  EFFECT:Create("effectBarrier02", SymEff("EV_BARRIER_LP"))
  EFFECT:SetPosition("effectBarrier02", SymPos("P_EFF_BARRIER02"))
  EFFECT:Play("effectBarrier01")
  EFFECT:Play("effectBarrier02")
  CH("YANCHAMU"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  CH("CHOBOMAKI"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1.5))
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1786014983)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("YANCHAMU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("YANCHAMU"), 1936677958)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("CHOBOMAKI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1009699457)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  EFFECT:SetPosition("effectBarrier01", SymPos("P_EFF_BARRIER01_2"))
  EFFECT:SetPosition("effectBarrier02", SymPos("P_EFF_BARRIER02_2"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(624294848)
  WINDOW:SysMsg(236496899)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 386111810)
  subEveCloseMsg()
  WINDOW:SysMsg(-1868855923)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -1988053812)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05_5"))
  CAMERA:SetTgt(SymCam("CAMERA_05_5"))
  CAMERA:SetFovy(SymCam("CAMERA_05_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-520197920)
  WINDOW:SysMsg(-102409823)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -758642078, PARTNER_1 = -875349213})
  WINDOW:CloseMessage()
  CH("HERO"):ResetNeckRot(TimeSec(0.1))
  CH("NYASUPAA"):ResetNeckRot(TimeSec(0.1))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_SHOCK_R")
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -2070762012)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05_5"))
  CAMERA:SetTgt(SymCam("CAMERA_05_5"))
  CAMERA:SetFovy(SymCam("CAMERA_05_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1651925851)
  WINDOW:SysMsg(-1230712986)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.PAIN)
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("HERO"):DirTo(SymPos("P00_PARTNER"), Speed(60), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -1346372057, PARTNER_1 = 673702632})
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  WINDOW:SwitchTalk({PARTNER_0 = 826069929, PARTNER_1 = -229914866})
  WINDOW:SwitchTalk({PARTNER_0 = -347015601, PARTNER_1 = -1065507444})
  WINDOW:KeyWait()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -647588659, PARTNER_1 = -1775828470})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_06_5"))
  CAMERA:SetTgt(SymCam("CAMERA_06_5"))
  CAMERA:SetFovy(SymCam("CAMERA_06_5"))
  EFFECT:SetPosition("effectBarrier01", SymPos("P_EFF_BARRIER01"))
  EFFECT:SetPosition("effectBarrier02", SymPos("P_EFF_BARRIER02"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  SCREEN_A:FadeChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("YANCHAMU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("YANCHAMU"), -1891880117)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("CHOBOMAKI"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("CHOBOMAKI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1542365048)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.1), true)
end
function main09_inisienohoneatoboss1st02_end()
end
function main09_inisienohoneatoboss1st03_init()
end
function main09_inisienohoneatoboss1st03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_05_5"))
  CAMERA:SetTgt(SymCam("CAMERA_05_5"))
  CAMERA:SetFovy(SymCam("CAMERA_05_5"))
  CH("YANCHAMU"):SetShadow(false)
  CH("CHOBOMAKI"):SetShadow(false)
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("YANCHAMU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("CHOBOMAKI"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  EFFECT:Create("effectBarrier01", SymEff("EV_BARRIER_LP"))
  EFFECT:SetPosition("effectBarrier01", SymPos("P_EFF_BARRIER01_2"))
  EFFECT:Create("effectBarrier02", SymEff("EV_BARRIER_LP"))
  EFFECT:SetPosition("effectBarrier02", SymPos("P_EFF_BARRIER02_2"))
  EFFECT:Play("effectBarrier01")
  EFFECT:Play("effectBarrier02")
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SHIKIJIKA_SPRING"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("HITOMOSHI"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI4"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HITOMOSHI"):SetShadow(false)
  CH("HITOMOSHI2"):SetShadow(false)
  CH("HITOMOSHI3"):SetShadow(false)
  CH("HITOMOSHI4"):SetShadow(false)
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  WINDOW:SysMsg(-1123397175)
  WINDOW:SysMsg(982666502)
  WINDOW:CloseMessage()
  EFFECT:ChangeColor("effectBarrier01", Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectBarrier02", Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
  CH("YANCHAMU"):SetVisible(true)
  CH("CHOBOMAKI"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_06_5"))
  CAMERA:SetTgt(SymCam("CAMERA_06_5"))
  CAMERA:SetFovy(SymCam("CAMERA_06_5"))
  EFFECT:SetPosition("effectBarrier01", SymPos("P_EFF_BARRIER01"))
  EFFECT:SetPosition("effectBarrier02", SymPos("P_EFF_BARRIER02"))
  TASK:Sleep(TimeSec(0.2))
  EFFECT:ChangeColor("effectBarrier01", Color(1, 1, 1, 0), TimeSec(5, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectBarrier02", Color(1, 1, 1, 0), TimeSec(5, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_SHOWAN"))
  EFFECT:Create("effectBarrierEnd01", SymEff("EV_BARRIER_END"))
  EFFECT:SetPosition("effectBarrierEnd01", SymPos("P_EFF_BARRIER01"))
  EFFECT:Create("effectBarrierEnd02", SymEff("EV_BARRIER_END"))
  EFFECT:SetPosition("effectBarrierEnd02", SymPos("P_EFF_BARRIER02"))
  EFFECT:Play("effectBarrierEnd01")
  EFFECT:Play("effectBarrierEnd02")
  TASK:Sleep(TimeSec(0.4))
  CH("YANCHAMU"):ChangeScale(Scale(0, 4, 0), TimeSec(3, TIME_TYPE.FRAME))
  CH("CHOBOMAKI"):ChangeScale(Scale(0, 4, 0), TimeSec(3, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1.5))
  EFFECT:Remove("effectBarrier01")
  EFFECT:Remove("effectBarrier02")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_HONOO_ENTRY"))
  EFFECT:Create("effectFire01", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire01", SymPos("P_EFF_FIRE_01"))
  EFFECT:Play("effectFire01")
  EFFECT:Create("effectFire02", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire02", SymPos("P_EFF_FIRE_02"))
  EFFECT:Play("effectFire02")
  EFFECT:Create("effectFire03", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire03", SymPos("P_EFF_FIRE_03"))
  EFFECT:Play("effectFire03")
  EFFECT:Create("effectFire04", SymEff("EV_FIRE_BLUEWHITE_LP"))
  EFFECT:SetPosition("effectFire04", SymPos("P_EFF_FIRE_04"))
  EFFECT:Play("effectFire04")
  CH("HERO"):ResetNeckRot(TimeSec(0.1))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):ResetNeckRot(TimeSec(0.1))
  CH("NYASUPAA"):ResetNeckRot(TimeSec(0.1))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(SymPos("P_EFF_FIRE_02"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(SymPos("P_EFF_FIRE_01"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P_EFF_FIRE_04"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):DirTo(SymPos("P_EFF_FIRE_03"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(SymPos("P_EFF_FIRE_04"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_HITOMOSHI_ENTRY"))
  EFFECT:ChangeColor("effectFire01", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.25))
  CH("HITOMOSHI"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI"):SetShadow(true)
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_08_1"))
  CAMERA:SetTgt(SymCam("CAMERA_08_1"))
  CAMERA:SetFovy(SymCam("CAMERA_08_1"))
  SOUND:PlaySe(SymSnd("SE_EVT_HITOMOSHI_ENTRY"))
  EFFECT:ChangeColor("effectFire04", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.25))
  CH("HITOMOSHI4"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI4"):SetShadow(true)
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(2), LINK_DIR.OFF)
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_08_2"))
  CAMERA:SetTgt(SymCam("CAMERA_08_2"))
  CAMERA:SetFovy(SymCam("CAMERA_08_2"))
  SOUND:PlaySe(SymSnd("SE_EVT_HITOMOSHI_ENTRY"))
  EFFECT:ChangeColor("effectFire03", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.25))
  CH("HITOMOSHI3"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI3"):SetShadow(true)
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(2), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_08_3"))
  CAMERA:SetTgt(SymCam("CAMERA_08_3"))
  CAMERA:SetFovy(SymCam("CAMERA_08_3"))
  SOUND:PlaySe(SymSnd("SE_EVT_HITOMOSHI_ENTRY"))
  EFFECT:ChangeColor("effectFire02", Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.25))
  CH("HITOMOSHI2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  CH("HITOMOSHI2"):SetShadow(true)
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(596212807)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 1257742443, PARTNER_1 = 1408012586})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = 2025964265, PARTNER_1 = 1641739176})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 781935983)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08_3"))
  CAMERA:SetTgt(SymCam("CAMERA_08_3"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(931157038)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08_2"))
  CAMERA:SetTgt(SymCam("CAMERA_08_2"))
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 20, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("NYASUPAA"), 481101805)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NUMERA"), 95827628)
  TASK:WaitTask()
  CH("NUMERA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05_5"))
  CAMERA:SetTgt(SymCam("CAMERA_05_5"))
  CAMERA:SetFovy(SymCam("CAMERA_05_5"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:SysMsg(-2110903709)
  WINDOW:SysMsg(-1691018462)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.2))
  SCREEN_A:FadeOut(TimeSec(0), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
end
function main09_inisienohoneatoboss1st03_end()
end
function main09_inisienohoneatoboss1st04_init()
end
function main09_inisienohoneatoboss1st04_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  CH("GIRATYINA_A"):SetScale(Scale(1.2))
  WINDOW:Talk(SymAct("GIRATYINA_A"), 311734333)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SENKOU"), Volume(256))
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  SAJI:CreateSajiPlayer("kage_04", "EV09_050_04_04")
  SJ("kage_04"):SetPosition(Vector2(200, 120))
  SJ("kage_04"):SetDrawPriority(200)
  SJ("kage_04"):Play(LOOP.ON)
  SCREEN_A:WhiteOut(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(0.05), true)
  TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  SCREEN_A:FadeInAll(TimeSec(0.05), true)
  TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  SCREEN_A:WhiteIn(TimeSec(0), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(0.1), true)
  SAJI:DestroySajiPlayer("kage_04")
  WINDOW:Talk(SymAct("GIRATYINA_A"), 193954172)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_11_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_GIRATYINA_ENTRY"))
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  CH("HERO"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("GIRATYINA_A"), Speed(500), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 547541695, PARTNER_1 = 968483838})
  subEveCloseMsg()
  WINDOW:Talk(SymAct("GIRATYINA_A"), 1995994425)
  WINDOW:CloseMessage()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("SHIKIJIKA_SPRING"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("NUMERA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  subEveFlash2()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("NYASUPAA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main09_inisienohoneatoboss1st04_end()
end
function groundEnd()
end
