dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main24_hajimarinomoribosswin01_init()
end
function main24_hajimarinomoribosswin01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  CH("KONOHANA"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CH("IBERUTARU"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CH("OOBEMU2"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CH("OOBEMU3"):SetMotion(SymMot("EV024_PAIN00"), LOOP.ON, TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("OOBEMU2"):SetVisible(false)
  CH("OOBEMU3"):SetVisible(false)
  CH("KONOHANA"):SetVisible(false)
  local taskDarkMatter00 = function()
    EFFECT:StartMotionBlur(0, 0, 0)
    EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.2))
    EFFECT:ChangeMotionBlurAlpha(0.5, TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_VOICE"), Volume(190))
    TASK:Sleep(TimeSec(0.5))
    EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.3))
    TASK:Sleep(TimeSec(0.3))
    EFFECT:EndMotionBlur()
  end
  local taskDarkMatter01 = function()
    EFFECT:StartMotionBlur(0, 0, 0)
    EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.2))
    EFFECT:ChangeMotionBlurAlpha(0.7, TimeSec(0.2))
    TASK:Sleep(TimeSec(0.7))
    EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.3))
    TASK:Sleep(TimeSec(0.3))
    EFFECT:EndMotionBlur()
  end
  SOUND:FadeInEnv(SymSnd("SE_EVT_DARKRING_LP"), TimeSec(0.5), Volume(128))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  local taskIberutaruShibari = function()
    EFFECT:Create("effectRinglp01", SymEff("EV_NIHIL_RING_MOVE_LP"))
    EFFECT:SetDir("effectRinglp01", RotateTarget(45))
    EFFECT:SetScale("effectRinglp01", Scale(0.5))
    EFFECT:SetPosition("effectRinglp01", SymPos("P_EFF_IBERUTARU"))
    EFFECT:Play("effectRinglp01")
    SOUND:PlaySe(SymSnd("SE_EVT_DARKRING_START"), Volume(256))
    CH("IBERUTARU"):SetMotion(SymMot("EV024_PAIN02"), LOOP.OFF)
    CH("IBERUTARU"):WaitPlayMotion()
    CH("IBERUTARU"):SetMotion(SymMot("EV024_PAIN03"), LOOP.ON)
  end
  TASK:Regist(taskIberutaruShibari)
  TASK:Regist(taskDarkMatter01)
  WINDOW:Talk(SymAct("IBERUTARU"), -1981579117)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  CH("KONOHANA"):SetVisible(true)
  CH("OOBEMU2"):SetVisible(true)
  CH("OOBEMU3"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  EFFECT:Create("effectRinglp02", SymEff("EV_NIHIL_RING_MOVE_LP"))
  EFFECT:SetDir("effectRinglp02", RotateTarget(0))
  EFFECT:SetScale("effectRinglp02", Scale(0.2))
  EFFECT:SetPosition("effectRinglp02", SymPos("P_EFF_KONOHANA"))
  EFFECT:Play("effectRinglp02")
  SOUND:PlaySe(SymSnd("SE_EVT_DARKRING_START"), Volume(256))
  TASK:Regist(taskDarkMatter01)
  TASK:Sleep(TimeSec(0.2))
  EFFECT:Create("effectRinglp03", SymEff("EV_NIHIL_RING_MOVE_LP"))
  EFFECT:SetDir("effectRinglp03", RotateTarget(-60))
  EFFECT:SetScale("effectRinglp03", Scale(0.2))
  EFFECT:SetPosition("effectRinglp03", SymPos("P_EFF_OOBEMU2"))
  EFFECT:Play("effectRinglp03")
  SOUND:PlaySe(SymSnd("SE_EVT_DARKRING_START"), Volume(256))
  TASK:Sleep(TimeSec(0.1))
  EFFECT:Create("effectRinglp04", SymEff("EV_NIHIL_RING_MOVE_LP"))
  EFFECT:SetDir("effectRinglp04", RotateTarget(125))
  EFFECT:SetScale("effectRinglp04", Scale(0.2))
  EFFECT:SetPosition("effectRinglp04", SymPos("P_EFF_OOBEMU3"))
  EFFECT:Play("effectRinglp04")
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("KONOHANA"), -1862749742)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(1))
  EFFECT:ChangeColor("effectRinglp01", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  EFFECT:Create("effectRingOut01", SymEff("EV_NIHIL_RING_MOVE_OUT"))
  EFFECT:SetPosition("effectRingOut01", SymPos("P_EFF_IBERUTARU"))
  EFFECT:Play("effectRingOut01")
  SOUND:FadeOutEnv(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_DARKRING_END"), Volume(256))
  EFFECT:ChangeColor("effectRinglp02", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  EFFECT:Create("effectRingOut02", SymEff("EV_NIHIL_RING_MOVE_OUT"))
  EFFECT:SetScale("effectRingOut02", Scale(0.3))
  EFFECT:SetPosition("effectRingOut02", SymPos("P_EFF_KONOHANA"))
  EFFECT:Play("effectRingOut02")
  EFFECT:ChangeColor("effectRinglp03", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  EFFECT:Create("effectRingOut03", SymEff("EV_NIHIL_RING_MOVE_OUT"))
  EFFECT:SetScale("effectRingOut03", Scale(0.3))
  EFFECT:SetPosition("effectRingOut03", SymPos("P_EFF_OOBEMU2"))
  EFFECT:Play("effectRingOut03")
  EFFECT:ChangeColor("effectRinglp04", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  EFFECT:Create("effectRingOut04", SymEff("EV_NIHIL_RING_MOVE_OUT"))
  EFFECT:SetScale("effectRingOut04", Scale(0.3))
  EFFECT:SetPosition("effectRingOut04", SymPos("P_EFF_OOBEMU3"))
  EFFECT:Play("effectRingOut04")
  TASK:Sleep(TimeSec(0.2))
  EFFECT:Remove("effectRinglp01")
  EFFECT:Remove("effectRinglp02")
  EFFECT:Remove("effectRinglp03")
  EFFECT:Remove("effectRinglp04")
  CH("IBERUTARU"):SetMotion(SymMot("EV000_WAIT02"), LOOP.ON, TimeSec(0.5))
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  CH("OOBEMU2"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.1))
  CH("OOBEMU3"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.5))
  CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU2"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU3"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU3"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("IBERUTARU"), -1143610863)
  WINDOW:CloseMessage()
  CH("IBERUTARU"):SetVisible(false)
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  local taskKonohana00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_02"), Volume(256))
    CH("KONOHANA"):SetManpu("MP_QUESTION")
    CH("KONOHANA"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
    CH("KONOHANA"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("KONOHANA"), Speed(500))
  end
  TASK:Regist(taskKonohana00)
  TASK:Sleep(TimeSec(0.2))
  local taskOobemu2_00 = function()
    CH("OOBEMU2"):SetManpu("MP_QUESTION")
    CH("OOBEMU2"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("OOBEMU2"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("OOBEMU2"), Speed(400))
  end
  TASK:Regist(taskOobemu2_00)
  TASK:Sleep(TimeSec(0.2))
  local taskOobemu3_00 = function()
    CH("OOBEMU3"):SetManpu("MP_QUESTION")
    CH("OOBEMU3"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("OOBEMU3"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("OOBEMU3"), Speed(400))
  end
  TASK:Regist(taskOobemu3_00)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), -1563503792)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("OOBEMU2"):SetManpu("MP_FLY_SWEAT")
  CH("OOBEMU2"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("OOBEMU2"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU2"), -309377641)
  WINDOW:CloseMessage()
  CH("IBERUTARU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(256))
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.02, TimeSec(0.2))
  EFFECT:ChangeMotionBlurAlpha(0.5, TimeSec(0.2))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU2"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("OOBEMU3"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU3"):WaitManpu()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  SOUND:FadeOutEnv(TimeSec(0.5))
  CH("IBERUTARU"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  CH("KONOHANA"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  CH("OOBEMU2"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  CH("OOBEMU3"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  SOUND:PlayEnv(SymSnd("SE_EVT_RELEASE"), Volume(256))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -191597354)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CH("IBERUTARU"):SetVisible(false)
  CH("KONOHANA"):SetVisible(false)
  CH("OOBEMU2"):SetVisible(false)
  CH("OOBEMU3"):SetVisible(false)
  EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.3))
  EFFECT:EndMotionBlur()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  SOUND:FadeOutEnv(TimeSec(0.5))
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("SEREBII"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("JIRAACHI"), -541513963)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -962455980, PARTNER_1 = 1094322843})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SEREBII"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SEREBII"), 1478573018)
  WINDOW:Talk(SymAct("SEREBII"), -1846046605)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("SEREBII"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("DENRYUU"), -1997758158)
  subEveCloseMsg()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1547570447, PARTNER_1 = -1160068176})
  subEveCloseMsg()
  local taskRun00 = function()
    CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
    CH("SEREBII"):RunTo(SymPos("P00_SEREBII"), Speed(3))
    CH("JIRAACHI"):RunTo(SymPos("P00_JIRAACHI"), Speed(3))
    TASK:Sleep(TimeSec(0.2))
    CH("NYASUPAA"):RunTo(SymPos("P00_NYASUPAA"), Speed(3))
    CH("DENRYUU"):RunTo(SymPos("P00_DENRYUU"), Speed(3))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("SEREBII"):SetManpu("MP_EXCLAMATION")
    CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskRun00)
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(taskDarkMatter00)
  WINDOW:SysMsg(-174369417)
  TASK:Sleep(TimeSec(1))
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("JIRAACHI"):SetManpu("MP_QUESTION")
  CH("JIRAACHI"):WaitManpu()
  CH("JIRAACHI"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("JIRAACHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("JIRAACHI"), -327130058)
  WINDOW:KeyWait()
  CH("NYASUPAA"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("JIRAACHI"), -944949259)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -558496076)
  WINDOW:Talk(SymAct("NYASUPAA"), 1496193659)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06_5"))
  CAMERA:SetTgt(SymCam("CAMERA_06_5"))
  CAMERA:SetFovy(SymCam("CAMERA_06_5"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("SEREBII"):SetManpu("MP_EXCLAMATION")
    CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskLookAt01)
  TASK:Regist(taskDarkMatter00)
  WINDOW:SysMsg(1077226298)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:SysMsg(-2092810339)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  local taskLookAt02 = function()
    CH("HERO"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("JIRAACHI"):DirTo(RotateTarget(-150), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(RotateTarget(10), Speed(500), ROT_TYPE.NEAR)
    CH("SEREBII"):DirTo(RotateTarget(-100), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("DENRYUU"):DirTo(RotateTarget(120), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1705439524, PARTNER_1 = -1317774049})
  WINDOW:SwitchTalk({PARTNER_0 = -1469092770, PARTNER_1 = -416351591})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SEREBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SEREBII"), -30028840)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06_5"))
  CAMERA:SetTgt(SymCam("CAMERA_06_5"))
  CAMERA:SetFovy(SymCam("CAMERA_06_5"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskDarkMatter00)
  local taskLookAt03 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("SEREBII"):SetManpu("MP_EXCLAMATION")
    CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    CH("JIRAACHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
    CH("SEREBII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("DENRYUU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt03)
  WINDOW:SysMsg(-719808485)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:SysMsg(-872175270)
  WINDOW:SysMsg(1268495765)
  WINDOW:SysMsg(1384154324)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(1006524664)
  WINDOW:Monologue(585460153)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(164117114)
  WINDOW:Monologue(282266427)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("JIRAACHI"), 1603444220)
  WINDOW:Talk(SymAct("JIRAACHI"), 1183427773)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  CAMERA:SetRotateZ(SymCam("CAMERA_12"))
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("SEREBII"):SetManpu("MP_EXCLAMATION")
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CAMERA:SetFovy(SymCam("CAMERA_13"))
  CAMERA:SetRotateZ(SymCam("CAMERA_13"))
  CH("DENRYUU"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("JIRAACHI"):DirTo(RotateTarget(20), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_SHOCK_R")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DENRYUU"), 1839529854)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main24_hajimarinomoribosswin01_end()
end
function main24_hajimarinomoribosswin02_init()
end
function main24_hajimarinomoribosswin02_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m24_060_02"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin02_cut_script_01()
  SOUND:PlayEnv(SymSnd("SE_EVT_SEIMEINOKI_LIFTUP_MAX"), Volume(128))
end
function main24_hajimarinomoribosswin02_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1958727231, PARTNER_1 = -215493904})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin02_end()
end
function main24_hajimarinomoribosswin02_1_init()
end
function main24_hajimarinomoribosswin02_1_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(256))
  SOUND:PlayEnv(SymSnd("SE_EVT_SEIMEINOKI_LIFTUP_MAX"), Volume(128))
  SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m24_060_02_1"))
  SOUND:PlaySe(SymSnd("SE_EVT_BAKIBAKI"), Volume(256))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin02_1_end()
end
function main24_hajimarinomoribosswin02_2_init()
end
function main24_hajimarinomoribosswin02_2_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(256))
  SOUND:PlayEnv(SymSnd("SE_EVT_SEIMEINOKI_LIFTUP_MAX"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  local taskSound00 = function()
    TASK:Sleep(TimeSec(50, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(28, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_BREAK"), Volume(64))
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_BREAK"), Volume(64))
  end
  TASK:Regist(taskSound00)
  CUT:Load(SymCut("m24_060_02_2"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin02_2_cut_script_01()
  SOUND:VolumeEnv(Volume(128), TimeSec(1.5))
end
function main24_hajimarinomoribosswin02_2_end()
end
function main24_hajimarinomoribosswin03_init()
end
function main24_hajimarinomoribosswin03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(60), RotateTarget(0), TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  EFFECT:Create("effectQuakeIceLp01", SymEff("EV_QUAKE_BROWN_LP"))
  EFFECT:SetPosition("effectQuakeIceLp01", SymPos("P01_EFF_EV_QUAKE_ICE_LP"))
  EFFECT:Play("effectQuakeIceLp01")
  SOUND:PlaySe(SymSnd("SE_EVT_EARTHQUAKE_CRASH_LP"), Volume(128))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(0.7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  local taskSmokeLp = function()
    function TaskL.Loop()
      EFFECT:Create("effectFallStoneSmoke01", SymEff("EV_FALL_STONE_SMOKE"))
      EFFECT:SetScale("effectFallStoneSmoke01", Scale(0.5))
      EFFECT:SetPosition("effectFallStoneSmoke01", SymPos("P01_EFF_NM_SMOKE_SHORT_WHITE"))
      EFFECT:Play("effectFallStoneSmoke01")
      TASK:Sleep(TimeSec(1))
      EFFECT:Create("effectFallStoneSmoke02", SymEff("EV_FALL_STONE_SMOKE"))
      EFFECT:SetScale("effectFallStoneSmoke02", Scale(0.4))
      EFFECT:SetPosition("effectFallStoneSmoke02", SymPos("P02_EFF_NM_SMOKE_SHORT_WHITE"))
      EFFECT:Play("effectFallStoneSmoke02")
      TASK:Sleep(TimeSec(1.5))
      EFFECT:Create("effectFallStoneSmoke03", SymEff("EV_FALL_STONE_SMOKE"))
      EFFECT:SetScale("effectFallStoneSmoke03", Scale(0.4))
      EFFECT:SetPosition("effectFallStoneSmoke03", SymPos("P03_EFF_NM_SMOKE_SHORT_WHITE"))
      EFFECT:Play("effectFallStoneSmoke03")
      TASK:Sleep(TimeSec(1))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskSmokeLp)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("HERO"):ResetNeckRot(TimeSec(0.15))
  SOUND:PlaySe(SymSnd("SE_EVT_DEGENE"), Volume(256))
  EFFECT:Create("effectShinkaReturn01", SymEff("EV_SHINKARETURN"))
  EFFECT:SetPosition("effectShinkaReturn01", CH("HERO"), BODY_POINT.CENTER)
  EFFECT:Play("effectShinkaReturn01")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.15))
  EFFECT:Create("effectShinkaReturn02", SymEff("EV_SHINKARETURN"))
  EFFECT:SetPosition("effectShinkaReturn02", CH("PARTNER"), BODY_POINT.CENTER)
  EFFECT:Play("effectShinkaReturn02")
  TASK:Sleep(TimeSec(0.3))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("DENRYUU"):ResetNeckRot(TimeSec(0.15))
    CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("NYASUPAA"):ResetNeckRot(TimeSec(0.15))
    CH("NYASUPAA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("SEREBII"):ResetNeckRot(TimeSec(0.15))
    CH("SEREBII"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("JIRAACHI"):ResetNeckRot(TimeSec(0.15))
    CH("JIRAACHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  CH("HERO"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(-15), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(15), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(20, TIME_TYPE.FRAME))
  CH("PARTNER"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(20, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.4))
  SCREEN_A:WhiteOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  EFFECT:Remove("effectQuakeIceLp01")
end
function main24_hajimarinomoribosswin03_end()
end
function main24_hajimarinomoribosswin05_init()
end
function main24_hajimarinomoribosswin05_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(128))
  SOUND:PlayEnv(SymSnd("SE_EVT_SEIMEINOKI_LIFTUP_MAX"), Volume(128))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(1, TIME_TYPE.FRAME))
  CH("PARTNER"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:Create("effectShinkaRetrunEnd", SymEff("EV_SHINKARETURN_END"))
  EFFECT:SetPosition("effectShinkaRetrunEnd", SymPos("P_EFF_EV_SHINKARETURN_END"))
  EFFECT:SetScale("effectShinkaRetrunEnd", Scale(0.6))
  EFFECT:Play("effectShinkaRetrunEnd")
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  EFFECT:Create("effectQuakeIceLp", SymEff("EV_QUAKE_BROWN_LP"))
  EFFECT:SetPosition("effectQuakeIceLp", SymPos("P01_EFF_EV_QUAKE_ICE_LP"))
  EFFECT:Play("effectQuakeIceLp")
  local taskSmokeLp = function()
    function TaskL.Loop()
      EFFECT:Create("effectFallStoneSmoke01", SymEff("EV_FALL_STONE_SMOKE"))
      EFFECT:SetScale("effectFallStoneSmoke01", Scale(0.5))
      EFFECT:SetPosition("effectFallStoneSmoke01", SymPos("P01_EFF_NM_SMOKE_SHORT_WHITE"))
      EFFECT:Play("effectFallStoneSmoke01")
      TASK:Sleep(TimeSec(1))
      EFFECT:Create("effectFallStoneSmoke02", SymEff("EV_FALL_STONE_SMOKE"))
      EFFECT:SetScale("effectFallStoneSmoke02", Scale(0.4))
      EFFECT:SetPosition("effectFallStoneSmoke02", SymPos("P02_EFF_NM_SMOKE_SHORT_WHITE"))
      EFFECT:Play("effectFallStoneSmoke02")
      TASK:Sleep(TimeSec(1.5))
      EFFECT:Create("effectFallStoneSmoke03", SymEff("EV_FALL_STONE_SMOKE"))
      EFFECT:SetScale("effectFallStoneSmoke03", Scale(0.4))
      EFFECT:SetPosition("effectFallStoneSmoke03", SymPos("P03_EFF_NM_SMOKE_SHORT_WHITE"))
      EFFECT:Play("effectFallStoneSmoke03")
      TASK:Sleep(TimeSec(1))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskSmokeLp)
  SOUND:FadeInBgm(SymSnd("SE_EVT_HERO_LIGHT_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
  CH("SEREBII"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):ChangeAddColor(Color(0, 0, 0, 1), TimeSec(30, TIME_TYPE.FRAME))
  CH("PARTNER"):ChangeAddColor(Color(0, 0, 0, 1), TimeSec(30, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(1.5))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -365108303, PARTNER_1 = -1507237823})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1087221504)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("NYASUPAA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(60), RotateTarget(0), TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("SEREBII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("JIRAACHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("NYASUPAA"), -1809907005)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("SEREBII"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SEREBII"), -1929104510)
  WINDOW:Talk(SymAct("SEREBII"), -1035623099)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetVisible(true)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("PARTNER"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -614558716, PARTNER_1 = -260847673})
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04"))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(4))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):ResetNeckRot(TimeSec(0.15))
  CH("NYASUPAA"):SetManpu("MP_SHOCK_R")
  CH("NYASUPAA"):ResetNeckRot(TimeSec(0.15))
  TASK:Sleep(TimeSec(0.1))
  CH("JIRAACHI"):SetManpu("MP_SHOCK_R")
  CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
  CH("SEREBII"):SetManpu("MP_SHOCK_R")
  CH("JIRAACHI"):ResetNeckRot(TimeSec(0.15))
  CH("DENRYUU"):ResetNeckRot(TimeSec(0.15))
  CH("SEREBII"):ResetNeckRot(TimeSec(0.15))
  TASK:Sleep(TimeSec(1))
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_EARTHQUAKE_CRASH_LP"), TimeSec(0.5))
  SOUND:FadeOutEnv(TimeSec(2))
  local taskBgm00 = function()
    SOUND:PlayBgm(SymSnd("BGM_EVE_TODOKU"), Volume(256))
  end
  TASK:Regist(taskBgm00)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-378997114)
  TASK:Sleep(TimeSec(0.7))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:Remove("effectQuakeIceLp")
end
function main24_hajimarinomoribosswin05_end()
end
function main24_hajimarinomoribosswin06_init()
end
function main24_hajimarinomoribosswin06_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CH("HERO"):SetShadow(false)
  CH("PARTNER"):SetShadow(false)
  CH("JIRAACHI"):SetShadow(false)
  CH("SEREBII"):SetShadow(false)
  CUT:Load(SymCut("m24_060_06"))
  local taskSound00 = function()
    TASK:Sleep(TimeSec(42, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_CRUSH"), Volume(64))
    TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_CRUSH"), Volume(32))
    TASK:Sleep(TimeSec(18, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(190))
  end
  TASK:Regist(taskSound00)
  local taskSound01 = function()
    TASK:Sleep(TimeSec(105, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(64))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(64))
    TASK:Sleep(TimeSec(17, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(64))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(64))
  end
  TASK:Regist(taskSound01)
  local taskSound02 = function()
    TASK:Sleep(TimeSec(165, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(64))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(64))
    TASK:Sleep(TimeSec(37, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    TASK:Sleep(TimeSec(40, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
  end
  TASK:Regist(taskSound02)
  local taskSound02_5 = function()
    TASK:Sleep(TimeSec(155, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_BREAK"), Volume(32))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(128))
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_BREAK"), Volume(128))
  end
  TASK:Regist(taskSound02_5)
  local taskSound03 = function()
    TASK:Sleep(TimeSec(264, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    TASK:Sleep(TimeSec(18, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    TASK:Sleep(TimeSec(18, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    TASK:Sleep(TimeSec(47, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_CRUSH"), Volume(32))
  end
  TASK:Regist(taskSound03)
  local taskSound04 = function()
    TASK:Sleep(TimeSec(327, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(25, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
  end
  TASK:Regist(taskSound04)
  local taskSound05 = function()
    TASK:Sleep(TimeSec(375, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(64))
    TASK:Sleep(TimeSec(16, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    TASK:Sleep(TimeSec(13, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_BREAK"), Volume(128))
    TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
  end
  TASK:Regist(taskSound05)
  local taskSound06 = function()
    TASK:Sleep(TimeSec(440, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(64))
    TASK:Sleep(TimeSec(7, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
    TASK:Sleep(TimeSec(19, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_LAND"), Volume(32))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_PARTNER_JUMP"), Volume(32))
  end
  TASK:Regist(taskSound06)
  local taskSound06_5 = function()
    TASK:Sleep(TimeSec(480, TIME_TYPE.FRAME))
    SOUND:FadeInEnv(SymSnd("SE_EVT_WINDNOISE_LP"), TimeSec(0.5), Volume(32))
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(64))
    TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(64))
    TASK:Sleep(TimeSec(327, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(128))
    TASK:Sleep(TimeSec(28, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_BREAK"), Volume(64))
    TASK:Sleep(TimeSec(37, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(64))
  end
  TASK:Regist(taskSound06_5)
  local taskSound07 = function()
    TASK:Sleep(TimeSec(720, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_FLUSH_02"), Volume(128))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(185, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_FLUSH_02"), Volume(128))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  end
  TASK:Regist(taskSound07)
  local taskSound08 = function()
    TASK:Sleep(TimeSec(1340, TIME_TYPE.FRAME))
    SOUND:FadeOutEnv(TimeSec(0.5))
  end
  TASK:Regist(taskSound08)
  local taskSound09 = function()
    TASK:Sleep(TimeSec(1844, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_HENSHIN"), Volume(128))
  end
  TASK:Regist(taskSound09)
  local taskSound10 = function()
    TASK:Sleep(TimeSec(1830, TIME_TYPE.FRAME))
    SOUND:FadeInEnv(SymSnd("SE_EVT_WINDNOISE_LP"), TimeSec(0.5), Volume(32))
    TASK:Sleep(TimeSec(130, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(64))
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_ROCK_FALL_HIGH"), Volume(64))
  end
  TASK:Regist(taskSound10)
  local taskSound11 = function()
    TASK:Sleep(TimeSec(2330, TIME_TYPE.FRAME))
    SOUND:FadeOutEnv(TimeSec(2.5))
  end
  TASK:Regist(taskSound11)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin06_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1861282377, PARTNER_1 = 2011945736})
  WINDOW:SwitchTalk({PARTNER_0 = 513083172, PARTNER_1 = 126760549})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_01_5()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 748905894, PARTNER_1 = 901272807})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_02()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 2063188512, PARTNER_1 = 1675817825})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_03()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("JIRAACHI"), 1221566626)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_04()
  WINDOW:SetWaitMode(TimeSec(0.5), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1372885475, PARTNER_1 = -699626196})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_05()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("SEREBII"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SEREBII"), -816333715)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_06()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 203466954, PARTNER_1 = 356227467})
  WINDOW:SwitchTalk({PARTNER_0 = 1041680968, PARTNER_1 = 655227657})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_06_5()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 1749839310, PARTNER_1 = 1901550735})
  WINDOW:SwitchTalk({PARTNER_0 = 1517948748, PARTNER_1 = 1130446349})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_07()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-990305598)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_filter()
  EFFECT:CreateRecollectionFilter()
end
function main24_hajimarinomoribosswin06_cut_talk_08()
  WINDOW:SetWaitMode(TimeSec(1.8), TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = -572386429, PARTNER_1 = -1264791633})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_09()
  WINDOW:SetWaitMode(TimeSec(1.7), TimeSec(1))
  WINDOW:Monologue(-1383596306)
  WINDOW:Monologue(-2035634899)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_10()
  local taskFilterEnd = function()
    TASK:Sleep(TimeSec(149, TIME_TYPE.FRAME))
    EFFECT:DestroyRecollectionFilter()
  end
  TASK:Regist(taskFilterEnd)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = -1615750036, PARTNER_1 = -789574997})
  WINDOW:SetWaitMode(TimeSec(1.3), TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = -907330582, PARTNER_1 = -490313687})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_11()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -69379736, PARTNER_1 = 2084914599})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_12()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1700689126, PARTNER_1 = -318775303})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_13()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -169546056, PARTNER_1 = -557204101})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_14()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -942502854, PARTNER_1 = -2003625219})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_cut_talk_15()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = -1853346884, PARTNER_1 = -1163560833})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin06_end()
end
function main24_hajimarinomoribosswin07_init()
end
function main24_hajimarinomoribosswin07_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  TASK:Sleep(TimeSec(2))
  SOUND:PlaySe(SymSnd("SE_EVT_DOSHU"))
  TASK:Sleep(TimeSec(1.2))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1.3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("DENRYUU"):SetMotion(SymMot("EV024_DOWN00"), LOOP.ON, TimeSec(0))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  CHARA:SetAllCharacterShadowVisible(true)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -1547810498, PARTNER_1 = 606492145})
  CH("PARTNER"):ResetShake()
  WINDOW:CloseMessage()
  CH("PARTNER"):SetMotionRaito(Raito(0.8))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(500), ROT_TYPE.LEFT)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1027433648, PARTNER_1 = 1413724316})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(0.7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("DENRYUU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("DENRYUU"), 1297648093)
  WINDOW:Talk(SymAct("DENRYUU"), 1718999582)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("SEREBII"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("JIRAACHI"):DirTo(CH("SEREBII"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 20, SymAct("SEREBII"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SEREBII"), 2137975647)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("JIRAACHI"), 808418712)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOKUTACHIHA_TOBERU"), Volume(256))
  CH("SEREBII"):RunTo(SymPos("P00_SEREBII"), Speed(3))
  CH("SEREBII"):MoveHeightTo(Height(5), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("JIRAACHI"):RunTo(SymPos("P00_JIRAACHI"), Speed(3))
  CH("JIRAACHI"):MoveHeightTo(Height(5), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CH("SEREBII"):SetPosition(SymPos("P01_SEREBII"))
  CH("JIRAACHI"):SetPosition(SymPos("P01_JIRAACHI"))
  CH("HERO"):SetDir(CH("SEREBII"))
  CH("PARTNER"):SetDir(CH("SEREBII"))
  CH("NYASUPAA"):SetDir(CH("SEREBII"))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("SEREBII"):WalkTo(SplinePath(SymSpl("S00_SEREBII")), Speed(4))
  CH("JIRAACHI"):WalkTo(SplinePath(SymSpl("S00_JIRAACHI")), Speed(4))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("NYASUPAA"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("HERO"):DirLockToChara(CH("SEREBII"))
  CH("PARTNER"):DirLockToChara(CH("SEREBII"))
  CH("NYASUPAA"):DirLockToChara(CH("SEREBII"))
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main24_hajimarinomoribosswin07_end()
end
function main24_hajimarinomoribosswin08_init()
end
function main24_hajimarinomoribosswin08_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOKUTACHIHA_TOBERU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(1))
  CH("SEREBII"):SetShadow(false)
  CH("JIRAACHI"):SetShadow(false)
  CUT:Load(SymCut("m24_060_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_WIND_LP"), Volume(256))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin08_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("SEREBII"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SEREBII"), 691293401)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin08_cut_talk_02()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("JIRAACHI"), 35200794)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin08_cut_talk_03()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("SEREBII"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SEREBII"), 453127771)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin08_cut_script_01()
  SOUND:FadeOutSe(SymSnd("SE_EVT_WIND_LP"), TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(2.5))
end
function main24_hajimarinomoribosswin08_end()
end
function main24_hajimarinomoribosswin09_init()
end
function main24_hajimarinomoribosswin09_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m24_060_09"))
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(190))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  SOUND:FadeOutEnv(TimeSec(0.5))
end
function main24_hajimarinomoribosswin09_end()
end
function main24_hajimarinomoribosswin10_init()
end
function main24_hajimarinomoribosswin10_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CUT:Load(SymCut("m24_060_10"))
  local taskSe00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_BLACK_SPREAD_LP"), Volume(256))
    TASK:Sleep(TimeSec(1))
    SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_JUUDEN_02_LP"), Volume(128))
  end
  TASK:Regist(taskSe00)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin10_cut_talk_01()
  WINDOW:SysMsg(-1667616108)
  TASK:Sleep(TimeSec(3.5))
  WINDOW:ForceCloseMessage()
end
function main24_hajimarinomoribosswin10_cut_script_01()
  SOUND:FadeOutSe(SymSnd("SE_EVT_BLACK_SPREAD_LP"), TimeSec(1))
  SOUND:FadeOutSe(SymSnd("SE_EVT_DEDENNE_JUUDEN_02_LP"), TimeSec(1))
end
function main24_hajimarinomoribosswin10_end()
end
function main24_hajimarinomoribosswin11_init()
end
function main24_hajimarinomoribosswin11_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetRotateZ(SymCam("CAMERA_00"))
  GM("BIGTREE"):SetScale(Scale(0.5))
  GM("CLOUD1"):SetPitch(RotateTarget(180))
  CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  GM("BIGTREE"):MoveHeightTo(Height(32), Speed(1))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(190))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  GM("BIGTREE"):SetScale(Scale(1))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetRotateZ(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-2055142443)
  WINDOW:SysMsg(1786907786)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main24_hajimarinomoribosswin11_end()
end
function main24_hajimarinomoribosswin12_init()
end
function main24_hajimarinomoribosswin12_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetNearFar(0.1, 10000)
  GM("EV01_EARTH"):SetScale(Scale(5))
  GM("EV01_SUN"):SetScale(Scale(15))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(30, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  GM("EV01_EARTH"):MoveTo(SymPos("P00_EARTH"), Speed(30))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SysMsg(1939422667)
  WINDOW:SysMsg(1488219656)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:ResetDefaultNearFar()
end
function main24_hajimarinomoribosswin12_end()
end
function main24_hajimarinomoribosswin13_init()
end
function main24_hajimarinomoribosswin13_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:SetRotateZ(SymCam("CAMERA_02"))
  GM("BIGTREE"):SetScale(Scale(0.5))
  GM("BIGTREE"):MoveHeightTo(Height(30.19), Speed(1))
  GM("TENKYU_CLOUD2"):SetVisible(false)
  GM("CLOUD1"):SetPitch(RotateTarget(180))
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SEREBII"):SetShadow(false)
  CH("JIRAACHI"):SetShadow(false)
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  GM("BIGTREE"):SetScale(Scale(0.3))
  GM("BIGTREE"):SetHeight(Height(30))
  GM("BIGTREE"):SetPosition(Vector(0, 40, 0))
  GM("BIGTREE"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  GM("BIGTREE"):MoveHeightTo(Height(100), Speed(1))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  GM("BIGTREE"):SetRoll(RotateTarget(-14))
  GM("TENKYU_CLOUD2"):SetVisible(true)
  GM("CLOUD1"):SetVisible(false)
  SOUND:VolumeEnv(Volume(64), TimeSec(0.25))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetRotateZ(SymCam("CAMERA_01"))
  WINDOW:SysMsg(1102012233)
  WINDOW:SysMsg(250530190)
  WINDOW:SysMsg(401995983)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  GM("BIGTREE"):ResetShake()
  CAMERA:SetRotateZ(Degree(0))
end
function main24_hajimarinomoribosswin13_end()
end
function main24_hajimarinomoribosswin14_init()
end
function main24_hajimarinomoribosswin14_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SysMsg(1020832524)
  WINDOW:SysMsg(633576013)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main24_hajimarinomoribosswin14_end()
end
function main24_hajimarinomoribosswin15_init()
end
function main24_hajimarinomoribosswin15_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("RUCHABURU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KUREFFI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("KAKUREON"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DESUKAAN"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(0.3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SysMsg(-1571060094)
  WINDOW:SysMsg(-1153386557)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main24_hajimarinomoribosswin15_end()
end
function main24_hajimarinomoribosswin16_init()
end
function main24_hajimarinomoribosswin16_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  WINDOW:SysMsg(-767661073)
  WINDOW:SysMsg(-886744402)
  WINDOW:SysMsg(-536344211)
  WINDOW:SysMsg(-116180948)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main24_hajimarinomoribosswin16_end()
end
function main24_hajimarinomoribosswin17_init()
end
function main24_hajimarinomoribosswin17_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SEREBII"):SetHeight(Height(2.8))
  CH("JIRAACHI"):SetHeight(Height(2.8))
  local taskSerebii00 = function()
    CH("SEREBII"):WalkTo(SymPos("P00_SEREBII"), Speed(1.5))
    CH("SEREBII"):MoveHeightTo(Height(0), Speed(2))
    CH("SEREBII"):WaitMove()
  end
  TASK:Regist(Group("grpSerebii"), taskSerebii00)
  local taskJiraachi00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("JIRAACHI"):WalkTo(SymPos("P00_JIRAACHI"), Speed(1.5))
    CH("JIRAACHI"):MoveHeightTo(Height(0), Speed(2))
  end
  TASK:Regist(taskJiraachi00)
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):ResetNeckRot(TimeSec(1))
  CH("PARTNER"):ResetNeckRot(TimeSec(1))
  CH("NYASUPAA"):ResetNeckRot(TimeSec(1))
  CH("DENRYUU"):ResetNeckRot(TimeSec(1))
  TASK:WaitTask(Group("grpSerebii"))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SEREBII"):SetManpu("MP_FLY_SWEAT")
  CH("SEREBII"):WaitManpu()
  CH("SEREBII"):SetFacialMotion(FACIAL_MOTION.SLEEP)
  WINDOW:DrawFace(324, 88, SymAct("SEREBII"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SEREBII"), -1236095253)
  WINDOW:CloseMessage()
  CH("SEREBII"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.2))
  subEveNo(CH("DENRYUU"))
  subEveNo(CH("DENRYUU"))
  TASK:Sleep(TimeSec(0.7))
  CH("DENRYUU"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("SEREBII"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CH("HERO"):WaitRotate()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1354129494)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-2073768855)
  WINDOW:SysMsg(-1652556504)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 451404263, PARTNER_1 = 66900134})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1064582143)
  WINDOW:SysMsg(-644811456)
  WINDOW:SysMsg(-222452093)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main24_hajimarinomoribosswin17_end()
end
function main24_hajimarinomoribosswin18_init()
end
function main24_hajimarinomoribosswin18_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  GM("EV01_EARTH"):SetScale(Scale(2))
  GM("EV01_SUN"):SetScale(Scale(11))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  GM("EV01_EARTH"):MoveTo(SymPos("P00_EARTH"), Speed(5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main24_hajimarinomoribosswin18_end()
end
function main24_hajimarinomoribosswin19_init()
end
function main24_hajimarinomoribosswin19_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.8))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(-341403710)
  WINDOW:Monologue(-1528364795)
  WINDOW:Monologue(-1107546044)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.2))
  EFFECT:ChangeMotionBlurAlpha(0.5, TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
    CH("DENRYUU"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):ResetNeckRot(TimeSec(0.15))
    CH("JIRAACHI"):ResetNeckRot(TimeSec(0.15))
    CH("DENRYUU"):ResetNeckRot(TimeSec(0.15))
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
    CH("SEREBII"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):ResetNeckRot(TimeSec(0.15))
    CH("NYASUPAA"):ResetNeckRot(TimeSec(0.15))
    CH("SEREBII"):ResetNeckRot(TimeSec(0.15))
  end
  TASK:Regist(taskLookAt00)
  SOUND:PlaySe(SymSnd("SE_EVT_KYUREMU_ROAR"), Volume(128))
  WINDOW:SysMsg(-1764662393)
  TASK:Sleep(TimeSec(0.7))
  EFFECT:ChangeMotionBlurAlpha(0, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.3))
  EFFECT:EndMotionBlur()
  WINDOW:ForceCloseMessage()
  local taskHero00 = function()
    CH("HERO"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("HERO"), Speed(600))
  end
  TASK:Regist(taskHero00)
  local taskPartner00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
    CH("PARTNER"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  TASK:Regist(taskPartner00)
  local taskSerebii00 = function()
    TASK:Sleep(TimeSec(0.1))
    CH("SEREBII"):SetManpu("MP_FLY_SWEAT")
    CH("SEREBII"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
    CH("SEREBII"):WaitRotate()
    TASK:Sleep(TimeSec(0.4))
    subEveLookAround(CH("SEREBII"), Speed(400))
  end
  TASK:Regist(taskSerebii00)
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(RotateTarget(10), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("NYASUPAA"):SetManpu("MP_FLY_SWEAT")
  CH("NYASUPAA"):WaitManpu()
  WINDOW:DrawFaceF(20, 20, SymAct("NYASUPAA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NYASUPAA"), -1882565946)
  WINDOW:Talk(SymAct("NYASUPAA"), 139611657)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("SEREBII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("SEREBII"):WaitRotate()
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("SEREBII"):SetManpu("MP_SHOCK_R")
  CH("SEREBII"):WaitManpu()
  WINDOW:DrawFaceF(324, 88, SymAct("SEREBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SEREBII"), 290029384)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  CH("JIRAACHI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("JIRAACHI"), 2016912228)
  WINDOW:Talk(SymAct("JIRAACHI"), 1630310949)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1241629158, PARTNER_1 = 1394274471})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  GM("EV24_GAREKI_2"):SetVisible(false)
  WINDOW:DrawFace(20, 88, SymAct("SEREBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SEREBII"), 475752032)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main24_hajimarinomoribosswin19_end()
end
function main24_hajimarinomoribosswin20_init()
end
function main24_hajimarinomoribosswin20_start()
  CH("DEOKISHISU_N"):SetShadow(false)
  CH("REKKUUZA_MEGA"):SetShadow(false)
  CH("REKKUUZA"):SetShadow(false)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlayEnv(SymSnd("SE_EVT_STOP_SEIMEINOKI_LP"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_KYUREMU_ROAR"), Volume(256))
  CUT:Load(SymCut("m24_060_20"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin20_cut_talk_01()
end
function main24_hajimarinomoribosswin20_cut_script_01()
  SOUND:PlaySe(SymSnd("SE_EVT_BEEM_LOOP"), Volume(190))
  SOUND:VolumeEnv(Volume(190), TimeSec(0.5))
end
function main24_hajimarinomoribosswin20_cut_script_02()
  SOUND:FadeOutEnv(TimeSec(1.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_POKEMON_NO_CHIKARA"), Volume(256))
end
function main24_hajimarinomoribosswin20_cut_talk_02()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("DEOKISHISU_N"), 88102689)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin20_cut_talk_03()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("DEOKISHISU_N"), 778896610)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin20_cut_script_03()
  SOUND:FadeOutSe(SymSnd("SE_EVT_BEEM_LOOP"), TimeSec(1))
  TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_REKKUUZA_SHINKA"), Volume(256))
end
function main24_hajimarinomoribosswin20_cut_script_04()
  SOUND:PlaySe(SymSnd("SE_EVT_MEGA_REKKUUZA_ATTACK"), Volume(256))
end
function main24_hajimarinomoribosswin20_cut_talk_04()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SysMsg(930493859)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin20_cut_script_05()
  SOUND:PlayEnv(SymSnd("SE_EVT_STOP_SEIMEINOKI_LP"), Volume(256))
end
function main24_hajimarinomoribosswin20_cut_talk_05()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SysMsg(-1326569108)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin20_cut_script_06()
  SOUND:FadeOutEnv(TimeSec(0.7))
end
function main24_hajimarinomoribosswin20_end()
end
function main24_hajimarinomoribosswin21_init()
end
function main24_hajimarinomoribosswin21_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_POKEMON_NO_CHIKARA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.8))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
    CH("DENRYUU"):SetManpu("MP_NOTICE_R")
    CH("PARTNER"):ResetNeckRot(TimeSec(0.15))
    CH("JIRAACHI"):ResetNeckRot(TimeSec(0.15))
    CH("DENRYUU"):ResetNeckRot(TimeSec(0.15))
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("NYASUPAA"):SetManpu("MP_NOTICE_L")
    CH("SEREBII"):SetManpu("MP_NOTICE_R")
    CH("HERO"):ResetNeckRot(TimeSec(0.15))
    CH("NYASUPAA"):ResetNeckRot(TimeSec(0.15))
    CH("SEREBII"):ResetNeckRot(TimeSec(0.15))
  end
  TASK:Regist(taskLookAt00)
  WINDOW:SysMsg(-1443555283)
  WINDOW:CloseMessage()
  local taskHero00 = function()
    CH("HERO"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("HERO"), Speed(600))
  end
  TASK:Regist(taskHero00)
  local taskPartner00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
    CH("PARTNER"):DirTo(RotateTarget(10), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  TASK:Regist(taskPartner00)
  local taskSerebii00 = function()
    TASK:Sleep(TimeSec(0.1))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("SEREBII"):SetManpu("MP_FLY_SWEAT")
    CH("SEREBII"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
    CH("SEREBII"):WaitRotate()
    TASK:Sleep(TimeSec(0.4))
    subEveLookAround(CH("SEREBII"), Speed(400))
  end
  TASK:Regist(taskSerebii00)
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(RotateTarget(10), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):DirTo(RotateTarget(30), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -438264867, PARTNER_1 = -50615652})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt01 = function()
    CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(2))
    CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(2))
    TASK:Sleep(TimeSec(0.2))
    CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(2))
    CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(3))
    TASK:Sleep(TimeSec(0.1))
    CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(3))
    CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(2))
  end
  TASK:Regist(taskLookAt01)
  WINDOW:SysMsg(-673777313)
  WINDOW:SysMsg(-825374690)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitRotate()
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -2121507111, PARTNER_1 = -1734905960})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main24_hajimarinomoribosswin21_end()
end
function main24_hajimarinomoribosswin22_init()
end
function main24_hajimarinomoribosswin22_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_POKEMON_NO_CHIKARA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow(SymCam("CAMERA_00_5"), Speed(1.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1279640485)
  WINDOW:SysMsg(-1432285926)
  WINDOW:SysMsg(758714837)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main24_hajimarinomoribosswin22_end()
end
function main24_hajimarinomoribosswin23_init()
end
function main24_hajimarinomoribosswin23_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_POKEMON_NO_CHIKARA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CHARA:SetAllCharacterShadowVisible(false)
  CH("MYUUTSUU_MEGA_Y"):SetEyeMotion(EYE_MOTION.CLOSE)
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SysMsg(874651796)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main24_hajimarinomoribosswin23_end()
end
function main24_hajimarinomoribosswin24_init()
end
function main24_hajimarinomoribosswin24_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_POKEMON_NO_CHIKARA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m24_060_24"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main24_hajimarinomoribosswin24_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SysMsg(1566375096)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main24_hajimarinomoribosswin24_end()
end
function main24_hajimarinomoribosswin25_init()
end
function main24_hajimarinomoribosswin25_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_POKEMON_NO_CHIKARA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:ChangeLightColor(Color(0.4, 0.4, 0.4, 1), TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NYASUPAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SEREBII"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("JIRAACHI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SysMsg(1145556473)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1869258298)
  WINDOW:CloseMessage()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("NYASUPAA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("JIRAACHI"):SetManpu("MP_SHOCK_R")
  CH("SEREBII"):SetManpu("MP_SHOCK_L")
  CH("DENRYUU"):SetManpu("MP_SHOCK_L")
  CH("DENRYUU"):WaitManpu()
  WINDOW:DrawFaceF(20, 88, SymAct("DENRYUU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DENRYUU"), 1987161979)
  subEveCloseMsg()
  WINDOW:SysMsg(959461820)
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetFacialMotion()
  CH("HERO"):ResetFacialMotion()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(0.3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(539691261)
  WINDOW:SysMsg(184965950)
  WINDOW:SysMsg(303917695)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1786415440)
  WINDOW:SysMsg(-1935783951)
  subEveCloseMsg()
  WINDOW:DrawFaceF(20, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1340691286)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1458725399)
  WINDOW:SysMsg(2111779284)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1690566805)
  WINDOW:SysMsg(730175058)
  WINDOW:SysMsg(849258259)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 431224016, PARTNER_1 = 11060625})
  WINDOW:SwitchTalk({PARTNER_0 = -2026841762, PARTNER_1 = -1641289697})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-145411021)
  WINDOW:SysMsg(-296876686)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("JIRAACHI"):ResetNeckRot(TimeSec(0.2))
  CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):ResetNeckRot(TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):ResetNeckRot(TimeSec(0.2))
  CH("DENRYUU"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("SEREBII"):ResetNeckRot(TimeSec(0.2))
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("JIRAACHI"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("JIRAACHI")
  })
  WINDOW:DrawFace(324, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -983345487)
  WINDOW:Talk(SymAct("JIRAACHI"), -596088848)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("PARTNER"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SEREBII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1824919241, PARTNER_1 = -1977433994})
  WINDOW:CloseMessage()
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -1592814667)
  WINDOW:Talk(SymAct("NYASUPAA"), -1206607116)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1066188347)
  WINDOW:Talk(SymAct("NYASUPAA"), 647466874)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(-40, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1355406235, PARTNER_1 = -1238559452})
  subEveCloseMsg()
  CH("DENRYUU"):DirTo(RotateTarget(150), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1660926233)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:MoveFollow2(SymCam("CAMERA_09_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -2078574682)
  WINDOW:Talk(SymAct("DENRYUU"), -883236511)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -767438816, PARTNER_1 = -110328861})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -529026398, PARTNER_1 = 1743761005})
  WINDOW:SwitchTalk({PARTNER_0 = 2129960748, PARTNER_1 = 394937088})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = 244412993, PARTNER_1 = 633086338})
  TASK:WaitTask()
  subEveCloseMsg()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(1017581763)
  WINDOW:Monologue(1944487428)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1795012421, PARTNER_1 = 1104209030})
  WINDOW:SwitchTalk({PARTNER_0 = 1489753543, PARTNER_1 = -548157176})
  WINDOW:SwitchTalk({PARTNER_0 = -968296375, PARTNER_1 = -334070236})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("JIRAACHI"):DirTo(CH("SEREBII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SEREBII"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  CH("SEREBII"):WaitRotate()
  CH("HERO"):ResetFacialMotion()
  CH("PARTNER"):ResetFacialMotion()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
    CH("DENRYUU"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
    CH("NYASUPAA"):DirTo(CH("JIRAACHI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("JIRAACHI"), -183677083)
  WINDOW:Talk(SymAct("JIRAACHI"), -568320858)
  WINDOW:Talk(SymAct("JIRAACHI"), -952422937)
  subEveCloseMsg()
  CH("SEREBII"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("SEREBII"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SEREBII"), -2005222624)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CH("SEREBII"):DirTo(RotateTarget(160), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("JIRAACHI"):DirTo(RotateTarget(160), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
  CH("PARTNER"):WaitMove()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("SEREBII"):SetManpu("MP_EXCLAMATION")
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1855878559, PARTNER_1 = -1169368670})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("SEREBII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1554519837, PARTNER_1 = 617608236})
  WINDOW:SwitchTalk({PARTNER_0 = 1037354349, PARTNER_1 = 1420433729})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SEREBII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SEREBII"), 1303455744)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1721531331, PARTNER_1 = 2139572866})
  WINDOW:SwitchTalk({PARTNER_0 = 818338885, PARTNER_1 = 702409988})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function main24_hajimarinomoribosswin25_end()
end
function groundEnd()
end
