dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main04_gakkouranomoriclear1st01_init()
end
function main04_gakkouranomoriclear1st01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 696169114, PARTNER_1 = 811959259})
  WINDOW:SwitchTalk({PARTNER_0 = 457756696, PARTNER_1 = 39051609})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NUMERA"), 1293055902)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1409894111, PARTNER_1 = 2133071132})
  WINDOW:SwitchTalk({PARTNER_0 = 1715414109, PARTNER_1 = -509134702})
  WINDOW:SwitchTalk({PARTNER_0 = -121894445, PARTNER_1 = -1998398937})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  WINDOW:DrawFace(324, 88, SymAct("NUMERA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NUMERA"), -1845892250)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskPartner00 = function()
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  local taskHero00 = function()
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    CH("HERO"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("HERO"), Speed(600))
  end
  TASK:Regist(taskPartner00)
  TASK:Regist(taskHero00)
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1160464219, PARTNER_1 = -1546679836})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -326230237, PARTNER_1 = -174772638})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-558334559)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -945599264, PARTNER_1 = 1077628975})
  WINDOW:SwitchTalk({PARTNER_0 = 1495294318, PARTNER_1 = -1705544247})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):ResetFacialMotion()
  local taskLookAroundHero00 = function()
    CH("HERO"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    subEveLookAround(CH("HERO"), Speed(400))
  end
  local taskLookAroundPartner00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    subEveLookAround02(CH("PARTNER"), Speed(350))
  end
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_02"), Volume(256))
  TASK:Regist(taskLookAroundPartner00)
  TASK:Regist(Group("grpHero"), taskLookAroundHero00)
  TASK:WaitTask(Group("grpHero"))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("HERO"):SetManpu("MP_NOTICE_R")
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskLookAt00)
  SOUND:PlaySe(SymSnd("SE_EVT_NYASUPAA_ALERT"), Volume(190))
  WINDOW:SysMsg(-2092153720)
  WINDOW:CloseMessage()
  WINDOW:SysMsg(-1470032053)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1317394934, PARTNER_1 = -29642547})
  subEveCloseMsg()
  WINDOW:SysMsg(-417300084)
  subEveCloseMsg()
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -871509425, PARTNER_1 = -719920370})
  subEveCloseMsg()
  WINDOW:SysMsg(1385103297)
  WINDOW:SysMsg(1268108928)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 585831084, PARTNER_1 = 1005593581})
  subEveCloseMsg()
  WINDOW:SysMsg(282947630)
  WINDOW:SysMsg(163987823)
  WINDOW:SysMsg(1183307688)
  subEveCloseMsg()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1604118249, PARTNER_1 = 1957803306})
  CH("PARTNER"):ResetManpu()
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1839891563, PARTNER_1 = -365782876})
  WINDOW:SwitchTalk({PARTNER_0 = -215373339, PARTNER_1 = -1086576107})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1507386540)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.LEFT)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(1))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(1.5))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(3))
  SOUND:FadeOutEnv(TimeSec(2.5))
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
end
function main04_gakkouranomoriclear1st01_end()
end
function main04_gakkouranomoriclear1st02_init()
end
function main04_gakkouranomoriclear1st02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("YANCHAMU"):SetVisible(false)
  CH("CHOBOMAKI"):SetVisible(false)
  CH("SHIKIJIKA_SPRING"):SetVisible(false)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHILDREN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitMove()
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1928705897, PARTNER_1 = -1810794026})
  WINDOW:SwitchTalk({PARTNER_0 = -615452911, PARTNER_1 = -1035215280})
  WINDOW:SwitchTalk({PARTNER_0 = -379155053, PARTNER_1 = -260195118})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("PARTNER"):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 2011537437, PARTNER_1 = 1862177116})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(125848944)
  WINDOW:Monologue(513506353)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 901132274, PARTNER_1 = 749543091})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1676445812, PARTNER_1 = 2063055157})
  subEveCloseMsg()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetManpu("MP_NOTICE_L")
    CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:Talk(SymAct("YANCHAMU"), 1373301494)
  subEveCloseMsg()
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1220664247)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -816199816, PARTNER_1 = -700254663})
  WINDOW:SwitchTalk({PARTNER_0 = 355852958, PARTNER_1 = 204395487})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT_LP")
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(4))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(1.2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  GM("EV04_FLAG"):SetVisible(false)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.GLADNESS)
  WINDOW:SwitchTalk({PARTNER_0 = 654540828, PARTNER_1 = 1041805661})
  WINDOW:CloseMessage()
  CH("YANCHAMU"):SetVisible(true)
  CH("CHOBOMAKI"):SetVisible(true)
  CH("SHIKIJIKA_SPRING"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("YANCHAMU"):RunTo(SymPos("P00_YANCHAMU"), Speed(3))
  CH("CHOBOMAKI"):RunTo(SymPos("P00_CHOBOMAKI"), Speed(3))
  CH("SHIKIJIKA_SPRING"):RunTo(SymPos("P00_SHIKIJIKA"), Speed(3))
  CH("YANCHAMU"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_SHOCK_R")
  CH("CHOBOMAKI"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 88, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), 1901668250)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.GLADNESS)
  WINDOW:SwitchTalk({PARTNER_0 = 1749161691, PARTNER_1 = 1131365656})
  WINDOW:SwitchTalk({PARTNER_0 = 1517581401, PARTNER_1 = -571709290})
  WINDOW:CloseMessage()
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):WaitManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_FLY_SWEAT")
  CH("YANCHAMU"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  TASK:Sleep(TimeSec(0.3))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(1), true)
  CH("PARTNER"):ResetManpu()
  TASK:Sleep(TimeSec(0.5))
end
function main04_gakkouranomoriclear1st02_end()
end
function main04_gakkouranomoriclear1st03_init()
end
function main04_gakkouranomoriclear1st03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0))
  CH("SHIKIJIKA_SPRING"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFaceF(172, 8, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -990422569)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1383496197, PARTNER_1 = -1265453894})
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1614813319)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -2036017608, PARTNER_1 = -907722497})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  WINDOW:DrawFace(324, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -788631106)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -70049155)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFaceF(172, 8, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -490204356)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetNeckRot(TimeSec(0.1))
  CH("HERO"):ResetNeckRot(TimeSec(0.1))
  CH("PARTNER"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("SHIKIJIKA_SPRING"):RunTo(SplinePath(SymPos("P00_SHIKIJIKA"), SymPos("P01_SHIKIJIKA")), Speed(4))
  local taskLookAt01 = function()
    CH("PARTNER"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(60), ROT_TYPE.NEAR)
    CH("YANCHAMU"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):SetManpu("MP_FLY_SWEAT")
    CH("CHOBOMAKI"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(350), ROT_TYPE.NEAR)
    CH("KAMONEGI"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  TASK:Sleep(TimeSec(3.5))
  TASK:Regist(subEveMoveDir2, {
    CH("KAMONEGI"),
    SymPos("P00_KAMONEGI"),
    Speed(1.5),
    SymPos("P00_KAMONEGI")
  })
  TASK:WaitTask()
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
    CH("YANCHAMU"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NYASUPAA"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.RIGHT)
  end
  TASK:Regist(taskLookAt02)
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 1699745779)
  WINDOW:Talk(SymAct("KAMONEGI"), 2085306034)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  CH("YANCHAMU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -169175635, PARTNER_1 = -319707924})
  subEveCloseMsg()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("YANCHAMU"):SetDir(CH("PARTNER"))
  TASK:Regist(subEveFukumiWarai, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), -941820113)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), -557332882)
  WINDOW:Talk(SymAct("KAMONEGI"), -1853468503)
  WINDOW:Talk(SymAct("KAMONEGI"), -2002951704)
  WINDOW:Talk(SymAct("KAMONEGI"), -1548733909)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(-1163197590)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("CHOBOMAKI"):SetDir(CH("HERO"))
  TASK:Regist(subEveFukumiWarai, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(324, 20, SymAct("CHOBOMAKI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHOBOMAKI"), 1026760613)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KAMONEGI"), 606613220)
  WINDOW:Talk(SymAct("KAMONEGI"), 1297543880)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1414382473, PARTNER_1 = 2137034826})
  WINDOW:CloseMessage()
  local taskLookAt03 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("KAMONEGI"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("NYASUPAA"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(200), ROT_TYPE.LEFT)
    TASK:Sleep(TimeSec(0.1))
    CH("CHOBOMAKI"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(200), ROT_TYPE.NEAR)
    CH("YANCHAMU"):DirTo(SymPos("P01_SHIKIJIKA"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt03)
  CH("PARTNER"):DirTo(SymPos("P00_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WalkTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER"), SymPos("P02_PARTNER")), Speed(1.5))
  TASK:Sleep(TimeSec(3.5))
  CH("NYASUPAA"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  CH("KAMONEGI"):DirTo(CH("NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFaceF(172, 8, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), 1719378187)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):RunTo(SplinePath(SymPos("P00_SHIKIJIKA"), SymPos("P01_SHIKIJIKA")), Speed(3))
  TASK:Sleep(TimeSec(1.5))
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("YANCHAMU"), 691681228)
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:CloseMessage()
  CH("KAMONEGI"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("KAMONEGI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("KAMONEGI"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("KAMONEGI")
  })
  WINDOW:DrawFace(20, 20, SymAct("KAMONEGI"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KAMONEGI"), 807470733)
  WINDOW:CloseMessage()
  CH("KAMONEGI"):ResetManpu()
  CH("YANCHAMU"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):ResetManpu()
  CH("YANCHAMU"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):DirTo(CH("KAMONEGI"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 453793102)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function main04_gakkouranomoriclear1st03_end()
end
function main04_gakkouranomoriclear1st04_init()
end
function main04_gakkouranomoriclear1st04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:SysMsg(35087375)
  SOUND:WaitSe(SymSnd("SE_EVT_SCHOOL_CHIME"))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -2054195008)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GIMMICK:SetupLoopPlaced(SymGA("SCHOOL_ROAD"), 0, -10)
  GIMMICK:MoveLoopPlaced(Speed(0.8))
  GIMMICK:SetLoopPlacedLeftMode()
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("HERO"):SetMotion(SymMot("WALK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("WALK"), LOOP.ON)
  SOUND:PlayBgm(SymSnd("BGM_EVE_KONOHANANOIE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFaceF(72, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1668003455, PARTNER_1 = 576464193})
  WINDOW:SwitchTalk({PARTNER_0 = 994513920, PARTNER_1 = 275400643})
  WINDOW:SwitchTalk({PARTNER_0 = 158430850, PARTNER_1 = 1177608261})
  WINDOW:CloseMessage()
  GIMMICK:MoveLoopPlaced(Speed(0))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("PARTNER"):DirTo(SymPos("P00_HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  local taskLookAt01 = function()
    CH("HERO"):ResetFacialMotion()
    CH("HERO"):WaitMove()
    CH("HERO"):ResetNeckRot(TimeSec(0.1))
    CH("HERO"):WaitNeckRot()
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1596707076, PARTNER_1 = 1946583751})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1830663046, PARTNER_1 = -360337591})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-207708664)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1696579036, PARTNER_1 = -2080672923})
  WINDOW:SwitchTalk({PARTNER_0 = -1462361946, PARTNER_1 = -1311960601})
  WINDOW:SwitchTalk({PARTNER_0 = -24344800, PARTNER_1 = -409487775})
  WINDOW:SwitchTalk({PARTNER_0 = -860166750, PARTNER_1 = -710814493})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetNeckRot(TimeSec(0.35))
  CH("PARTNER"):WaitNeckRot()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1379518508, PARTNER_1 = 1260583277})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-2007634486)
  WINDOW:CloseMessage()
  WINDOW:SysMsg(-1857102709)
  WINDOW:SelectStart()
  WINDOW:SelectChain(-1167880376, 1)
  WINDOW:SelectChain(-1552368119, 0)
  WINDOW:DefaultCursor(1)
  local id = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
  if id == 1 then
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    TASK:Regist(subEveJumpSurprise, {
      CH("PARTNER")
    })
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("PARTNER"):SetManpu("MP_SHOCK_R")
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
    WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
    WINDOW:SwitchTalk({PARTNER_0 = -331798322, PARTNER_1 = -182314609})
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
    CH("PARTNER"):WaitManpu()
    WINDOW:CloseMessage()
    CAMERA:SetEye(SymCam("CAMERA_01"))
    CAMERA:SetTgt(SymCam("CAMERA_01"))
    TASK:Sleep(TimeSec(0.2))
    WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
    WINDOW:Monologue(-569423284)
    WINDOW:Monologue(-954959091)
    WINDOW:CloseMessage()
    CAMERA:SetEye(SymCam("CAMERA_02"))
    CAMERA:SetTgt(SymCam("CAMERA_02"))
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
    CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
    CH("PARTNER"):WaitNeckRot()
    WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
    WINDOW:SwitchTalk({PARTNER_0 = 1082943426, PARTNER_1 = 1503090307})
    WINDOW:SwitchTalk({PARTNER_0 = 820611759, PARTNER_1 = 703773678})
    WINDOW:SwitchTalk({PARTNER_0 = 48228397, PARTNER_1 = 465885548})
    WINDOW:CloseMessage()
  else
    CAMERA:SetEye(SymCam("CAMERA_01"))
    CAMERA:SetTgt(SymCam("CAMERA_01"))
    TASK:Sleep(TimeSec(0.2))
    WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
    WINDOW:Monologue(1418022827)
    WINDOW:Monologue(1302232810)
    WINDOW:Monologue(1723018537)
    WINDOW:Monologue(2141723752)
    WINDOW:Monologue(-131071833)
    WINDOW:Monologue(-517262874)
    WINDOW:Monologue(-1388400106)
    WINDOW:CloseMessage()
    CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CAMERA:SetEye(SymCam("CAMERA_02"))
    CAMERA:SetTgt(SymCam("CAMERA_02"))
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    TASK:Regist(subEveJumpSurprise, {
      CH("PARTNER")
    })
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("PARTNER"):SetManpu("MP_SHOCK_R")
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
    WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
    WINDOW:SwitchTalk({PARTNER_0 = -1272609961, PARTNER_1 = -1626812268})
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
    CH("PARTNER"):WaitManpu()
    WINDOW:CloseMessage()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
    CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
    CH("PARTNER"):WaitNeckRot()
    WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
    WINDOW:SwitchTalk({PARTNER_0 = -2045517355, PARTNER_1 = -917342446})
    WINDOW:SwitchTalk({PARTNER_0 = -800504237, PARTNER_1 = -77326960})
    WINDOW:CloseMessage()
  end
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(0.25, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-494983983)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 1709651998, PARTNER_1 = 2096892255})
  WINDOW:SwitchTalk({PARTNER_0 = 360895859, PARTNER_1 = 211412018})
  WINDOW:SwitchTalk({PARTNER_0 = 666154993, PARTNER_1 = 1051690672})
  WINDOW:SwitchTalk({PARTNER_0 = 1911427191, PARTNER_1 = 1760895286})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(1138258677)
  WINDOW:Monologue(1522746292)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(-581214341)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(2))
  WINDOW:SysMsg(-1002410438)
  WINDOW:SysMsg(121076381)
  WINDOW:SysMsg(506219484)
  WINDOW:SysMsg(889264159)
  WINDOW:KeyWait()
  SCREEN_A:FadeOutAll(TimeSec(1.5), true)
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeInAll(TimeSec(0), true)
  TASK:Sleep(TimeSec(2))
end
function main04_gakkouranomoriclear1st04_end()
end
function main04_gakkouranomoriclear1st05_init()
end
function main04_gakkouranomoriclear1st05_start()
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 739912030)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetDir(RotateTarget(-45))
  CH("HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  local taskWakeUpHero = function()
    CH("HERO"):SetMotion(SymMot("EV001_SLEEP02"), LOOP.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  SOUND:PlayBgm(SymSnd("BGM_EVE_KONOHANANOIE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(Group("grpHero"), taskWakeUpHero)
  TASK:WaitTask(Group("grpHero"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveToHero(Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
end
function main04_gakkouranomoriclear1st05_end()
end
function groundEnd()
end
