dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main02_kowasounamoriclear1st01_init()
end
function main02_kowasounamoriclear1st01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-2124000410)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(-1736613337)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  CH("NUMERA"):WaitPlayMotion()
  CH("NUMERA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("NUMERA"):DirTo(RotateOffs(-90), Speed(800))
  CH("NUMERA"):WaitRotate()
  CH("NUMERA"):DirTo(RotateOffs(180), Speed(800))
  CH("NUMERA"):WaitRotate()
  CH("NUMERA"):DirTo(RotateOffs(-90), Speed(800))
  CH("NUMERA"):WaitRotate()
  CH("NUMERA"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct(""), -1286589980)
  WINDOW:CloseMessage()
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("NUMERA"):ResetShake()
  CH("NUMERA"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  CH("NUMERA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("NUMERA"):SetManpu("MP_SHOCK_L")
  CH("NUMERA"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
  CH("NUMERA"):MoveTo(SymPos("P00_NUMERA"), Speed(2.5), LINK_DIR.OFF)
  CH("NUMERA"):WaitMove()
  CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("NUMERA"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):WaitMove()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(GM("EV02_BIGPAPER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(-1437925211)
  WINDOW:Monologue(-452290974)
  WINDOW:Monologue(-65951965)
  WINDOW:Monologue(-683871008)
  WINDOW:Monologue(-836254303)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CH("HERO"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(1237309806)
  WINDOW:Monologue(1352984623)
  WINDOW:Monologue(-404353440)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  local taskNumera00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("NUMERA"):SetManpu("MP_SHOCK_R")
    TASK:Regist(subEveJumpSurprise, {
      CH("NUMERA")
    })
    TASK:Sleep(TimeSec(0.3))
    CH("NUMERA"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
    CH("NUMERA"):SetMotion(SymMot("ENDURE"), LOOP.ON)
    CH("NUMERA"):SetManpu("MP_FLY_SWEAT_LP")
  end
  TASK:Regist(taskNumera00)
  WINDOW:DrawFace(272, 16, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -16957663)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CH("NUMERA"):ResetShake()
  CH("NUMERA"):ResetManpu()
  CH("NUMERA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("NUMERA"):SetManpu("MP_NOTICE_R")
  CH("NUMERA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), -707760926)
  WINDOW:Talk(SymAct("NUMERA"), -859087453)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NUMERA"), -2088055964)
  WINDOW:KeyWait()
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT_LP")
  CH("NUMERA"):SetMotion(SymMot("EV002_CRY"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("NUMERA"), -1701709275)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_05"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(0.5))
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function main02_kowasounamoriclear1st01_end()
end
function main02_kowasounamoriclear1st02_init()
end
function main02_kowasounamoriclear1st02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("EV02_BIGPAPER"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("YANCHAMU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("CHOBOMAKI"):SetManpu("MP_SHOCK_R")
  CH("YANCHAMU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), -1313035802)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_03"), Volume(256))
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(GM("EV02_BIGPAPER"), Speed(350), ROT_TYPE.NEAR)
    CH("YANCHAMU"):DirTo(GM("EV02_BIGPAPER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("SHIKIJIKA_SPRING"):DirTo(GM("EV02_BIGPAPER"), Speed(350), ROT_TYPE.NEAR)
  end
  subEveNod(CH("NUMERA"))
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):WaitRotate()
  CH("NUMERA"):WalkTo(SymPos("P00_NUMERA"), Speed(1.5))
  TASK:Regist(taskLookAt01)
  CH("NUMERA"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  GM("EV02_BIGPAPER"):SetVisible(true)
  CH("NUMERA"):WalkTo(SymPos("P01_NUMERA"), Speed(1.5), LINK_DIR.OFF)
  CH("NUMERA"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("CHOBOMAKI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("CHOBOMAKI")
  })
  CH("CHOBOMAKI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -1465411417)
  subEveCloseMsg()
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUMERA"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  end
  CH("YANCHAMU"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(taskLookAt02)
  WINDOW:DrawFace(20, 20, SymAct("YANCHAMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YANCHAMU"), 792691816)
  WINDOW:CloseMessage()
  subEveNod(CH("NUMERA"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("YANCHAMU"):WalkTo(SymPos("P00_YANCHAMU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("NUMERA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):WalkTo(SymPos("P00_CHOBOMAKI"), Speed(1.5))
  CH("CHOBOMAKI"):WaitMove()
  CH("YANCHAMU"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.35))
  CH("CHOBOMAKI"):WaitMove()
  CH("YANCHAMU"):WaitNeckRot()
  TASK:Regist(subEveJump, {
    CH("YANCHAMU")
  })
  WINDOW:DrawFace(20, 20, SymAct("YANCHAMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANCHAMU"), 908375337)
  WINDOW:KeyWait()
  CH("NUMERA"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 20, SymAct("YANCHAMU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("YANCHAMU"), -179068530)
  WINDOW:CloseMessage()
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(272, 16, SymAct("NUMERA"), FACE_TYPE.SHOUT)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("NUMERA"), -330788657)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
  CH("CHOBOMAKI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("CHOBOMAKI")
  })
  WINDOW:DrawFace(20, 88, SymAct("CHOBOMAKI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("CHOBOMAKI"), -949632244)
  WINDOW:CloseMessage()
  CH("YANCHAMU"):ResetNeckRot(TimeSec(0.2))
  CH("YANCHAMU"):ResetManpu()
  CH("YANCHAMU"):DirTo(CH("CHOBOMAKI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("CHOBOMAKI"):ResetManpu()
  CH("CHOBOMAKI"):DirTo(CH("YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  CH("CHOBOMAKI"):WaitRotate()
  CH("YANCHAMU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("YANCHAMU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("YANCHAMU"), -562105779)
  WINDOW:CloseMessage()
  local taskLookAt03 = function()
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(SymPos("P01_YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("CHOBOMAKI"):DirTo(SymPos("P01_YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("NUMERA"):SetManpu("MP_SHOCK_L")
    CH("NUMERA"):DirTo(SymPos("P01_YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
    CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P01_YANCHAMU"), Speed(350), ROT_TYPE.NEAR)
  end
  CH("YANCHAMU"):WalkTo(SymPos("P01_YANCHAMU"), Speed(1.5))
  TASK:Regist(taskLookAt03)
  CH("YANCHAMU"):WaitMove()
  GM("EV02_BIGPAPER"):SetVisible(false)
  TASK:Sleep(TimeSec(0.3))
  CH("YANCHAMU"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  CH("YANCHAMU"):WaitRotate()
  CH("YANCHAMU"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("YANCHAMU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("YANCHAMU"), -1858116470)
  WINDOW:CloseMessage()
  CH("CHOBOMAKI"):SetManpu("MP_LAUGH_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_RUN_ESCAPE_01"), Volume(256))
  CH("YANCHAMU"):RunTo(SymPos("P02_YANCHAMU"), Speed(4))
  CH("CHOBOMAKI"):RunTo(SymPos("P01_CHOBOMAKI"), Speed(4))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(0), Speed(60), ROT_TYPE.NEAR)
  CH("NUMERA"):DirTo(RotateTarget(0), Speed(60), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("SHIKIJIKA_SPRING"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(1.3))
  CH("CHOBOMAKI"):ResetFacialMotion()
  CH("SHIKIJIKA_SPRING"):WalkTo(SymPos("P00_SHIKIJIKA"), Speed(1.5))
  CH("SHIKIJIKA_SPRING"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("SHIKIJIKA_SPRING")
  })
  WINDOW:DrawFace(324, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -2010884661)
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):ResetManpu()
  TASK:Sleep(TimeSec(1))
  CH("YANCHAMU"):ResetFacialMotion()
  WINDOW:DrawFace(324, 20, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1559689720)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("SHIKIJIKA_SPRING"):DirTo(CH("NUMERA"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("NUMERA"):ResetFacialMotion()
  CH("NUMERA"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1173211319)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1032465286)
  subEveCloseMsg()
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SAD)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NUMERA"), 613489351)
  WINDOW:Talk(SymAct("NUMERA"), 1307559659)
  subEveCloseMsg()
  CH("NUMERA"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1425340330)
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 2144969833)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NUMERA"), 1724028200)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 696452079)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 815280814)
  subEveCloseMsg()
  CH("NUMERA"):SetManpu("MP_FLY_SWEAT")
  CH("NUMERA"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("NUMERA"), 464871789)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 44978220)
  CH("NUMERA"):ResetFacialMotion()
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):WaitRotate()
  CH("NUMERA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -2060038941)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -1674740318)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_QUESTION")
  CH("SHIKIJIKA_SPRING"):WaitManpu()
  SOUND:FadeOutBgm(TimeSec(1.5))
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -801571246)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function main02_kowasounamoriclear1st02_end()
end
function main02_kowasounamoriclear1st03_init()
end
function main02_kowasounamoriclear1st03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:FadeInEnv(SymSnd("SE_ENV_FOREST_NIGHT_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(1), true)
  TASK:Sleep(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
end
function main02_kowasounamoriclear1st03_end()
end
function main02_kowasounamoriclear1st04_init()
end
function main02_kowasounamoriclear1st04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayEnv(SymSnd("SE_ENV_FOREST_NIGHT_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:Talk(SymAct("KONOHANA"), -920400109)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main02_kowasounamoriclear1st04_end()
end
function main02_kowasounamoriclear1st05_init()
end
function main02_kowasounamoriclear1st05_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KONOHANANOIE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  TASK:Regist(subEveJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KONOHANA"), -502358832)
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("KONOHANA")
  })
  WINDOW:Talk(SymAct("KONOHANA"), -82465391)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(-1269548202)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KONOHANA"), -1387329001)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -2040374828)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("HERO"):WaitNeckRot()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -1619433323)
  WINDOW:Talk(SymAct("KONOHANA"), 417428570)
  WINDOW:Talk(SymAct("KONOHANA"), 33178907)
  WINDOW:Talk(SymAct("KONOHANA"), 1753520439)
  WINDOW:Talk(SymAct("KONOHANA"), 1906288758)
  WINDOW:Talk(SymAct("KONOHANA"), 1521679285)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.EMOTION)
  WINDOW:Monologue(1135201012)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 216554547)
  WINDOW:Talk(SymAct("KONOHANA"), 368274802)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  SOUND:FadeOutBgm(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function main02_kowasounamoriclear1st05_end()
end
function groundEnd()
end
