dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main14_shinpinomoriclear1st01_init()
end
function main14_shinpinomoriclear1st01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 809990230, PARTNER_1 = 693913879})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 40966868)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 459942805, PARTNER_1 = 1412152658})
  WINDOW:CloseMessage()
end
function main14_shinpinomoriclear1st01_end()
end
function main14_shinpinomoriclear1st02_init()
end
function main14_shinpinomoriclear1st02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskHero00 = function()
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    CH("HERO"):DirTo(SymPos("P_RATYIASU"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    CH("HERO"):SetManpu("MP_EXCLAMATION")
  end
  local taskPartner00 = function()
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(SymPos("P_RATYIASU"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    CH("PARTNER"):SetManpu("MP_SHOCK_L")
  end
  local taskAaken00 = function()
    CH("AAKEN"):WalkTo(SymPos("P00_AAKEN"), Speed(1.5))
    CH("AAKEN"):WaitMove()
    CH("AAKEN"):DirTo(SymPos("P_RATYIASU"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskHero00)
  TASK:Regist(taskAaken00)
  TASK:Regist(Group("grpPartner"), taskPartner00)
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_04"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask(Group("grpPartner"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1295027219, PARTNER_1 = 1713233872})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveRunDir, {
    CH("AAKEN"),
    SymPos("P01_AAKEN"),
    Speed(3),
    SymPos("P_RATYIASU")
  })
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(3),
    SymPos("P_RATYIASU")
  })
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(3),
    SymPos("P_RATYIASU")
  })
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2131160721, PARTNER_1 = -123800994})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-511327457)
  WINDOW:Monologue(-1810075406)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1928904269, PARTNER_1 = -1507192208})
  WINDOW:SwitchTalk({PARTNER_0 = -1087298767, PARTNER_1 = -261048842})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -378829641, PARTNER_1 = -1035544716})
  WINDOW:SwitchTalk({PARTNER_0 = -614603211, PARTNER_1 = 1556478714})
  subEveCloseMsg()
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 1172229051)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -2035687652, PARTNER_1 = -1615663523})
  WINDOW:CloseMessage()
  CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -1264599650)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1383822113, PARTNER_1 = -490399208})
  WINDOW:CloseMessage()
  CH("AAKEN"):DirTo(SymPos("P_RATYIASU"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -69325991)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -789350246, PARTNER_1 = -907523621})
  WINDOW:SwitchTalk({PARTNER_0 = 1315984660, PARTNER_1 = 1466655829})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 1041610873)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CH("PARTNER"):RunTo(SplinePath(SymPos("P02_PARTNER"), SymPos("P03_PARTNER")), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):RunTo(SplinePath(SymPos("P02_HERO"), SymPos("P03_HERO")), Speed(3))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(3.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 655264056)
  WINDOW:Talk(SymAct("AAKEN"), 203676411)
  WINDOW:Talk(SymAct("AAKEN"), 356051898)
  WINDOW:Talk(SymAct("AAKEN"), 1517911421)
  WINDOW:Talk(SymAct("AAKEN"), 1130515516)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("AAKEN"):SetManpu("MP_UPSET_LP")
  TASK:Sleep(TimeSec(1))
  CH("AAKEN"):ResetManpu()
  CH("AAKEN"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.15))
  CH("AAKEN"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("AAKEN"), 1750015999)
  WINDOW:Talk(SymAct("AAKEN"), 1901342398)
  WINDOW:Talk(SymAct("AAKEN"), -154389903)
  WINDOW:CloseMessage()
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("AAKEN"):ResetNeckRot(TimeSec(0.15))
  CH("AAKEN"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("AAKEN"), -271121616)
  WINDOW:Talk(SymAct("AAKEN"), -1547534144)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("AAKEN"):ResetFacialMotion()
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -1160138367)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("AAKEN"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  subEveLookAround(CH("AAKEN"), Speed(600))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -1846222270)
  WINDOW:Talk(SymAct("AAKEN"), -1997548797)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("AAKEN"):RunTo(SplinePath(SymPos("P02_AAKEN"), SymPos("P03_AAKEN")), Speed(3))
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main14_shinpinomoriclear1st02_end()
end
function main14_shinpinomoriclear1st03_init()
end
function main14_shinpinomoriclear1st03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("AAKEN"):SetVisible(false)
  CH("ENTEI"):SetVisible(false)
  CH("FUSHIGIDANE"):SetShadowOnlyMode(true)
  CH("FUSHIGIDANE"):SetShadow(false)
  local taskHero00 = function()
    CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
    CH("HERO"):WaitMove()
    CH("HERO"):DirTo(SymPos("P_RATYIOSU"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    CH("HERO"):SetManpu("MP_EXCLAMATION")
  end
  local taskPartner00 = function()
    CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):DirTo(SymPos("P_RATYIOSU"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("PARTNER"):SetManpu("MP_SHOCK_L")
  end
  TASK:Regist(taskHero00)
  TASK:Regist(Group("grpPartner"), taskPartner00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask(Group("grpPartner"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -944880188, PARTNER_1 = -558533499})
  WINDOW:CloseMessage()
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(3),
    SymPos("P_RATYIOSU")
  })
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(3),
    SymPos("P_RATYIOSU")
  })
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -174577850, PARTNER_1 = -326953465})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1796934344, PARTNER_1 = 1912617865})
  WINDOW:SwitchTalk({PARTNER_0 = 461301669, PARTNER_1 = 40228580})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"), Volume(256))
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0.5))
  TASK:Sleep(TimeSec(0.5))
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  local taskPartner00 = function()
    CH("PARTNER"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
    subEveLookAround(CH("PARTNER"), Speed(600))
  end
  local taskHero00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(-90), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("HERO"), Speed(600))
  end
  TASK:Regist(taskPartner00)
  TASK:Regist(taskHero00)
  WINDOW:SysMsg(692618535)
  WINDOW:SysMsg(810792038)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2131894945, PARTNER_1 = 1711870944})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  EFFECT:Create("effectFireAppear", SymEff("EV_FIRE_APPEAR"))
  EFFECT:SetPosition("effectFireAppear", SymPos("P_EFF_EV_FIRE_APPEAR"))
  EFFECT:Play("effectFireAppear")
  SOUND:PlaySe(SymSnd("SE_EVT_ENTEI_APPEAR"))
  CH("PARTNER"):DirTo(CH("ENTEI"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("ENTEI"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  CAMERA:SetFovy(SymCam("CAMERA_04_1"))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04_2"))
  CAMERA:SetTgt(SymCam("CAMERA_04_2"))
  CAMERA:SetFovy(SymCam("CAMERA_04_2"))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04_3"))
  CAMERA:SetTgt(SymCam("CAMERA_04_3"))
  CAMERA:SetFovy(SymCam("CAMERA_04_3"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04_3"))
  CH("HERO"):SetVisible(false)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_04_4"))
  CAMERA:SetTgt(SymCam("CAMERA_04_4"))
  CAMERA:SetFovy(SymCam("CAMERA_04_4"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04_4"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("ENTEI"):SetVisible(true)
  EFFECT:Wait("effectFireAppear")
  EFFECT:Remove("effectFireAppear")
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetRotateZ(SymCam("CAMERA_05"))
  local taskEntei00 = function()
    CH("ENTEI"):SetMotion(SymMot("EV015_BARK00"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_ENTEI_ROAR"))
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    CH("ENTEI"):WaitPlayMotion()
    CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  end
  TASK:Regist(taskEntei00)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1.7))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_03"), Volume(256))
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04"))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1294221347, PARTNER_1 = 1413443938})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-744002131)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_DOTEKKOTSU"), Volume(256))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:Talk(SymAct(""), -893625108)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  WINDOW:SwitchTalk({PARTNER_0 = 164317259, PARTNER_1 = 282097930})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  WINDOW:Talk(SymAct(""), 1006447305)
  WINDOW:Talk(SymAct(""), 585505672)
  WINDOW:CloseMessage()
  TASK:Regist(taskEntei00)
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Create("effectFireAngry", SymEff("EV_FIRE_ANGRY"))
  EFFECT:SetPosition("effectFireAngry", SymPos("P_EFF_EV_FIRE_APPEAR"))
  EFFECT:Play("effectFireAngry")
  SOUND:PlaySe(SymSnd("SE_EVT_ENTEI_ANGRY"), Volume(256))
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1839697231, PARTNER_1 = 1958525966})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct(""), 1603399629)
  WINDOW:Talk(SymAct("ENTEI"), 1183506060)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1055735229, PARTNER_1 = -670436606})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:Talk(SymAct("ENTEI"), -1317589202)
  subEveCloseMsg()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1469309329, PARTNER_1 = -2092872276})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SOUND:FadeOutBgm(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):SetVisible(true)
  WINDOW:Narration(TimeSec(0), TimeSec(0), -1705345811)
  WINDOW:CloseMessage()
  local taskAaken00 = function()
    CH("AAKEN"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  end
  TASK:Regist(taskAaken00)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_06"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.5))
  CH("ENTEI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -719590870, PARTNER_1 = -872359061})
  WINDOW:CloseMessage()
  CH("ENTEI"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -416446296)
  WINDOW:Talk(SymAct("AAKEN"), -29967895)
  WINDOW:CloseMessage()
  CH("AAKEN"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("ENTEI"), 2041488678)
  WINDOW:CloseMessage()
  CH("AAKEN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 1622512743)
  WINDOW:Talk(SymAct("AAKEN"), -384549000)
  WINDOW:CloseMessage()
  CH("AAKEN"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("ENTEI"), -267448775)
  WINDOW:Talk(SymAct("ENTEI"), -618504710)
  WINDOW:Talk(SymAct("ENTEI"), -1036424005)
  WINDOW:CloseMessage()
  CH("AAKEN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CH("ENTEI"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.5))
  TASK:Sleep(TimeSec(1))
  CH("ENTEI"):WalkTo(SymPos("P00_ENTEI"), Speed(0.8), LINK_DIR.OFF)
  CH("ENTEI"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("ENTEI"), -1921451396)
  WINDOW:Talk(SymAct("ENTEI"), -1805399235)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(2.5))
  WINDOW:DrawFace(272, 16, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -1085368066)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  CH("AAKEN"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  EFFECT:Create("effectFireDisappear01", SymEff("EV_FIRE_DISAPPEAR"))
  EFFECT:SetPosition("effectFireDisappear01", SymPos("P00_EFF_EV_FIRE_DISAPPEAR"))
  EFFECT:Play("effectFireDisappear01")
  SOUND:PlaySe(SymSnd("SE_EVT_ENTEI_OUT"), Volume(256))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(1.5))
  TASK:Regist(taskEntei00)
  TASK:Sleep(TimeSec(0.8))
  CH("ENTEI"):ChangeColor(Color(1, 1, 1, 0), TimeSec(30, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1))
  CH("ENTEI"):SetVisible(false)
  CH("ENTEI"):SetShadow(false)
  TASK:Sleep(TimeSec(1.5))
  MAP:ChangeLightColor(Color(1, 1, 1, 1), TimeSec(1))
  TASK:Sleep(TimeSec(1.5))
  CH("AAKEN"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  local taskAaken01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("AAKEN"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.NEAR)
    CH("AAKEN"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("AAKEN"), Speed(400))
  end
  TASK:Regist(taskPartner00)
  TASK:Regist(taskHero00)
  TASK:Regist(taskAaken01)
  WINDOW:SysMsg(-1504335425)
  WINDOW:SysMsg(567129456)
  WINDOW:SysMsg(953582641)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("AAKEN"):SetShadow(false)
  CH("FUSHIGIDANE"):SetShadow(true)
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFaceF(324, 88, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  WINDOW:SwitchTalk({PARTNER_0 = 1369987101, PARTNER_1 = 1219717468})
  WINDOW:CloseMessage()
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("AAKEN"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  CH("AAKEN"):WaitNeckRot()
  CH("AAKEN"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("AAKEN"):SetMotionRaito(Raito(0.5))
  TASK:Sleep(TimeSec(1.3))
  CH("AAKEN"):ResetNeckRot(TimeSec(0.05))
  CH("AAKEN"):ResetFacialMotion()
  CH("AAKEN"):SetMotionRaito(Raito(1))
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  CH("AAKEN"):SetMotion(SymMot("EV014_DOWN00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.4))
  SOUND:PlaySe(SymSnd("SE_EVT_DOWN_LIGHT"), Volume(256))
  CH("AAKEN"):WaitPlayMotion()
  CH("AAKEN"):SetMotion(SymMot("EV014_DOWN01"), LOOP.ON)
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("AAKEN"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitRotate()
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P02_HERO"),
    Speed(3),
    SymPos("P01_AAKEN")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P02_PARTNER"),
    Speed(3),
    SymPos("P01_AAKEN")
  })
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1671314079, PARTNER_1 = 2055539678})
  subEveCloseMsg()
  CH("AAKEN"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("AAKEN"):ResetShake()
  WINDOW:DrawFace(72, 16, SymAct("AAKEN"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("AAKEN"), 902077721)
  WINDOW:Talk(SymAct("AAKEN"), 752856152)
  subEveCloseMsg()
  TASK:Regist(subEveNoNoNo, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 133365659, PARTNER_1 = 518639322})
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -1720593899, PARTNER_1 = -2140478636})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P03_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SymPos("P03_HERO"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):SetMotion(SymMot("EV018_CRY00"), LOOP.OFF)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetMotion(SymMot("EV018_CRY01"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
end
function main14_shinpinomoriclear1st03_end()
end
function main14_shinpinomoriclear1st04_init()
end
function main14_shinpinomoriclear1st04_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_04"), Volume(256))
  WINDOW:SwitchNaration(TimeSec(0.5), TimeSec(0.5), {PARTNER_0 = -401587693, PARTNER_1 = -250907822})
  WINDOW:SwitchNaration(TimeSec(0.5), TimeSec(0.5), {PARTNER_0 = -635035503, PARTNER_1 = -1019407920})
  WINDOW:SwitchNaration(TimeSec(0.5), TimeSec(0.5), {PARTNER_0 = -1937996009, PARTNER_1 = -1788365226})
  WINDOW:SwitchNaration(TimeSec(0.5), TimeSec(0.5), {PARTNER_0 = -1102387819, PARTNER_1 = -1487809324})
  WINDOW:SwitchNaration(TimeSec(0.5), TimeSec(0.5), {PARTNER_0 = 550094875, PARTNER_1 = 970127706})
  WINDOW:SwitchNaration(TimeSec(0.5), TimeSec(0.5), {PARTNER_0 = 1353459062, PARTNER_1 = 1236735031})
  WINDOW:CloseMessage()
end
function main14_shinpinomoriclear1st04_end()
end
function main14_shinpinomoriclear1st05_init()
end
function main14_shinpinomoriclear1st05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("HORUBII"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PEROPPAFU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("DENRYUU"):SetManpu("EV_EAT_LP")
  CH("DENRYUU"):SetMotionRaito(Raito(2))
  CH("DENRYUU"):SetMotion(SymMot("EV014_EAT00"), LOOP.ON)
  CH("HERO"):SetManpu("EV_EAT_LP")
  CH("HERO"):SetMotionRaito(Raito(2))
  CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("AAKEN"):SetManpu("EV_EAT_LP")
  CH("AAKEN"):SetMotionRaito(Raito(2))
  CH("AAKEN"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("HORUBII"):SetManpu("EV_EAT_LP")
  CH("HORUBII"):SetMotionRaito(Raito(2))
  CH("HORUBII"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):SetManpu("EV_EAT_LP")
  CH("DEDENNE"):SetMotionRaito(Raito(2))
  CH("DEDENNE"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("PARTNER"):SetManpu("EV_EAT_LP")
  CH("PARTNER"):SetMotionRaito(Raito(2))
  CH("PARTNER"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("JIRAACHI"):SetManpu("EV_EAT_LP")
  CH("JIRAACHI"):SetMotionRaito(Raito(2))
  CH("JIRAACHI"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("PEROPPAFU"):SetManpu("EV_EAT_LP")
  CH("PEROPPAFU"):SetMotionRaito(Raito(2))
  CH("PEROPPAFU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):SetManpu("EV_EAT_LP")
  CH("BUIZERU"):SetMotionRaito(Raito(2))
  CH("BUIZERU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("KUCHIITO"):SetManpu("EV_EAT_LP")
  CH("KUCHIITO"):SetMotionRaito(Raito(2))
  CH("KUCHIITO"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CAMERA:MoveFollow(SymCam("CAMERA_00_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_GATSUGATSU_LP"))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  WINDOW:SysMsg(1654278132)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(2072082101)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(885055602)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(769380659)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(116818672)
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_GATSUGATSU_LP"), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SwitchNaration(TimeSec(0.5), TimeSec(0.5), {PARTNER_0 = 535671729, PARTNER_1 = -1737117826})
  WINDOW:CloseMessage()
end
function main14_shinpinomoriclear1st05_end()
end
function main14_shinpinomoriclear1st06_init()
end
function main14_shinpinomoriclear1st06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SwitchSysMsg({PARTNER_0 = -2123456961, PARTNER_1 = 1108970136})
  WINDOW:SwitchSysMsg({PARTNER_0 = 1526905817, PARTNER_1 = 1882187802})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SysMsg(1765071195)
  WINDOW:SysMsg(645222300)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1064206045)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 339946782)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 223878239)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1967128432)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1814351407)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -89788931)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -474030916)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  TASK:Sleep(TimeSec(2))
end
function main14_shinpinomoriclear1st06_end()
end
function main14_shinpinomoriclear1st07_init()
end
function main14_shinpinomoriclear1st07_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main14_shinpinomoriclear1st07_end()
end
function main14_shinpinomoriclear1st08_init()
end
function main14_shinpinomoriclear1st08_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("AAKEN"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SAD)
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("AAKEN"), -929853569)
  WINDOW:Talk(SymAct("AAKEN"), -779567554)
  WINDOW:Talk(SymAct("AAKEN"), -1630983943)
  WINDOW:Talk(SymAct("AAKEN"), -2016273992)
  subEveCloseMsg()
  CH("AAKEN"):ResetFacialMotion()
  CH("AAKEN"):ResetNeckRot(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:Talk(SymAct("DENRYUU"), -1392555397)
  WINDOW:Talk(SymAct("DENRYUU"), -1243317446)
  WINDOW:Talk(SymAct("DENRYUU"), 847013877)
  WINDOW:Talk(SymAct("DENRYUU"), 728192692)
  WINDOW:Talk(SymAct("DENRYUU"), 1735578948)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetShake(Vector(0.005, 0, 0), TimeSec(0.4, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_NOTICE_R")
  CH("JIRAACHI"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.1))
  CH("KUCHIITO"):SetManpu("MP_NOTICE_R")
  CH("AAKEN"):SetManpu("MP_NOTICE_L")
  CH("AAKEN"):WaitManpu()
  CH("DEDENNE"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), 2120868869)
  WINDOW:Talk(SymAct("DEDENNE"), 1430566854)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:Talk(SymAct("DENRYUU"), 1281328775)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_QUESTION")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), 52301888)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("DENRYUU"):ResetShake()
  CH("DENRYUU"):SetManpu("MP_SPREE_LP")
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("DENRYUU")
  })
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:Talk(SymAct("DENRYUU"), 436543745)
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_RUN_ESCAPE"))
  CH("DENRYUU"):RunTo(SplinePath(SymSpl("L00_DENRYUU")), Speed(4))
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KUCHIITO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(2.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("AAKEN"):SetManpu("MP_SWEAT_L")
  CH("DEDENNE"):SetManpu("MP_SWEAT_L")
  CH("KUCHIITO"):SetManpu("MP_SWEAT_L")
  CH("JIRAACHI"):SetManpu("MP_SWEAT_L")
  CH("JIRAACHI"):WaitManpu()
  WINDOW:DrawFaceF(172, 40, SymAct("DEDENNE"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DEDENNE"), 824734402)
  subEveCloseMsg()
  CH("AAKEN"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("AAKEN"), 674448259)
  WINDOW:CloseMessage()
  CH("AAKEN"):ResetFacialMotion()
  CH("AAKEN"):ResetNeckRot(TimeSec(0.2))
  CH("AAKEN"):WaitNeckRot()
  CH("JIRAACHI"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KUCHIITO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("KUCHIITO"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 20, SymAct("KUCHIITO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KUCHIITO"), -1347723444)
  WINDOW:Talk(SymAct("KUCHIITO"), -1229951475)
  WINDOW:Talk(SymAct("KUCHIITO"), -540102111)
  subEveCloseMsg()
  CH("KUCHIITO"):ResetManpu()
  CH("KUCHIITO"):ResetFacialMotion()
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DEDENNE"), -959085728)
  subEveCloseMsg()
  CH("DEDENNE"):ResetFacialMotion()
  WINDOW:DrawFace(324, 20, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -302460765)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main14_shinpinomoriclear1st08_end()
end
function main14_shinpinomoriclear1st09_init()
end
function main14_shinpinomoriclear1st09_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_MOGUMOGU_01_LP"))
  WINDOW:SysMsg(-186392094)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1146980571)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1564916124)
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(-1986783833)
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_MOGUMOGU_01_LP"), TimeSec(0.5))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("DENRYUU"), -1869667098)
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 387397673)
  WINDOW:Talk(SymAct("DENRYUU"), 235669864)
  subEveCloseMsg()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("PEROPPAFU"), -847569457)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), -731894642)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetManpu("EV_EAT_LP")
  CH("DENRYUU"):SetMotion(SymMot("EV014_EAT00"), LOOP.ON, TimeSec(0))
  SOUND:PlaySe(SymSnd("SE_EVT_MOGUMOGU_02_LP"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PEROPPAFU"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PEROPPAFU")
  })
  CH("PEROPPAFU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("PEROPPAFU"), -11698355)
  WINDOW:Talk(SymAct("PEROPPAFU"), -430551540)
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_MOGUMOGU_02_LP"), TimeSec(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_02"), Volume(256))
  CH("DENRYUU"):ResetManpu()
  CH("DENRYUU"):SetMotion(SymMot("EV014_EAT01"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  WINDOW:DrawFace(324, 20, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1458054965)
  WINDOW:Talk(SymAct("DENRYUU"), -1341331062)
  WINDOW:Talk(SymAct("DENRYUU"), -1692288439)
  WINDOW:CloseMessage()
  CH("DENRYUU"):SetMotion(SymMot("EV014_EAT02"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_MOGUMOGU_02_LP"))
  CH("DENRYUU"):SetManpu("EV_EAT_LP")
  CH("DENRYUU"):SetMotion(SymMot("EV014_EAT00"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PEROPPAFU"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(324, 20, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -2110092536)
  WINDOW:Talk(SymAct("DENRYUU"), 94541767)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("PEROPPAFU"):RunTo(SymPos("P00_PEROPPAFU"), Speed(3))
  CH("PEROPPAFU"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  local taskPeroppafu00 = function()
    function TaskL.Loop()
      CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT_LP")
      TASK:Regist(subEveDoubleJump, {
        CH("PEROPPAFU")
      })
      TASK:Sleep(TimeSec(1))
      TASK:Regist(subEveDoubleJump, {
        CH("PEROPPAFU")
      })
      TASK:Sleep(TimeSec(2))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskPeroppafu00)
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("PEROPPAFU"), 481928838)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1976007338)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PEROPPAFU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1826376683)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 1206982696)
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_MOGUMOGU_02_LP"), TimeSec(1.5))
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function main14_shinpinomoriclear1st09_end()
end
function groundEnd()
end
