dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main17_choureiyokokujou01_init()
end
function main17_choureiyokokujou01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  GM("EXTRA_PAPER"):SetVisible(false)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("BUIZERU"):SetManpu("MP_EXCLAMATION")
  CH("PEROPPAFU"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("PEROPPAFU")
  })
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_SHOCK_L")
  CH("BUIZERU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BUIZERU"), -24874100)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("HORUBII")
  })
  WINDOW:DrawFace(324, 88, SymAct("HORUBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HORUBII"), -408993075)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -860745458)
  WINDOW:Talk(SymAct("DENRYUU"), -710336433)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("DENRYUU"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1696024952)
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(72, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -2081191991)
  WINDOW:CloseMessage()
  CH("DENRYUU"):DirTo(RotateTarget(0), Speed(60), ROT_TYPE.NEAR)
  TASK:Regist(subEveMoveDir, {
    CH("DEDENNE"),
    SymPos("P05_DEDENNE"),
    Speed(1.5),
    RotateTarget(0)
  })
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("KUCHIITO"):DirTo(SymPos("P05_DEDENNE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("BUIZERU"):DirTo(SymPos("P05_DEDENNE"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):DirTo(SymPos("P05_DEDENNE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(SymPos("P05_DEDENNE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(SymPos("P05_DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.7))
  GM("EXTRA_PAPER"):SetVisible(true)
  TASK:Sleep(TimeSec(0.5))
  CH("DEDENNE"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.2))
  CH("DEDENNE"):WaitNeckRot()
  WINDOW:SysMsg(-1461791734)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DEDENNE"), -1312430773)
  WINDOW:Talk(SymAct("DEDENNE"), 912128388)
  WINDOW:Talk(SymAct("DEDENNE"), 793168069)
  WINDOW:Talk(SymAct("DEDENNE"), 2014923308)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("JIRAACHI"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("BUIZERU"):SetManpu("MP_EXCLAMATION")
  CH("PEROPPAFU"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(324, 88, SymAct("HORUBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HORUBII"), 1627552621)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_SHOCK_L")
  CH("BUIZERU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BUIZERU"), 1244604590)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 1395923439)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DEDENNE"), 477466408)
  WINDOW:Talk(SymAct("DEDENNE"), 91143785)
  WINDOW:Talk(SymAct("DEDENNE"), 776203690)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):ResetNeckRot(TimeSec(0.15))
  WINDOW:DrawFace(72, 16, SymAct("DEDENNE"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DEDENNE"), 928570603)
  WINDOW:CloseMessage()
  GM("EXTRA_PAPER"):SetVisible(false)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PEROPPAFU"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KUCHIITO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -1329545180)
  WINDOW:Talk(SymAct("AAKEN"), -1445203611)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH("PEROPPAFU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("PEROPPAFU"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(324, 20, SymAct("PEROPPAFU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1789715906)
  WINDOW:CloseMessage()
  CH("PEROPPAFU"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("BUIZERU"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):WaitRotate()
  CH("BUIZERU"):SetManpu("MP_ANGRY_LP")
  local taskLookAt05 = function()
    CH("AAKEN"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("KUCHIITO"):DirTo(CH("PEROPPAFU"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt05)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:DrawFace(20, 20, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("BUIZERU"), 1941427331)
  WINDOW:Talk(SymAct("BUIZERU"), 1486522176)
  WINDOW:CloseMessage()
  CH("BUIZERU"):ResetManpu()
  CH("BUIZERU"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):WaitRotate()
  local taskLookAt06 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("AAKEN"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("KUCHIITO"):DirTo(CH("HORUBII"), Speed(200), ROT_TYPE.NEAR)
    CH("PEROPPAFU"):ResetFacialMotion()
    CH("PEROPPAFU"):DirTo(CH("HORUBII"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt06)
  WINDOW:DrawFace(72, 16, SymAct("HORUBII"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:Talk(SymAct("HORUBII"), 1099019777)
  WINDOW:Talk(SymAct("HORUBII"), 247472326)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 400232839)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("AAKEN"):DirTo(CH("DENRYUU"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HORUBII"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PEROPPAFU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("KUCHIITO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("DENRYUU"), 1022771780)
  WINDOW:Talk(SymAct("DENRYUU"), 636318469)
  WINDOW:Talk(SymAct("DENRYUU"), -1569361974)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("KUCHIITO"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
  CH("KUCHIITO"):WaitRotate()
  CH("DEDENNE"):DirTo(CH("KUCHIITO"), Speed(350), ROT_TYPE.NEAR)
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("BUIZERU"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
    CH("AAKEN"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(CH("DEDENNE"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("DEDENNE"), Speed(60), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(324, 20, SymAct("KUCHIITO"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KUCHIITO"), -1150394741)
  WINDOW:Talk(SymAct("KUCHIITO"), -770669913)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -888425498)
  WINDOW:Talk(SymAct("DEDENNE"), -534323163)
  WINDOW:Talk(SymAct("DEDENNE"), -113389212)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -1233369181)
  CH("DEDENNE"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("DENRYUU"), -1352173854)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("DENRYUU"), -2075515615)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
    CH("DENRYUU"):WaitRotate()
    CH("BUIZERU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("JIRAACHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("KUCHIITO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("PEROPPAFU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("DEDENNE"):DirTo(CH("PARTNER"), Speed(60), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1655630752, PARTNER_1 = 449382575})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 64109038)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1338489374, PARTNER_1 = 1457294175})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = 2113001628, PARTNER_1 = 1693116893})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 732659482, PARTNER_1 = 850415195})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GAYA_LP"))
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(1))
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("DENRYUU"):SetFacialMotion(FACIAL_MOTION.SAD)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("DENRYUU"):SetManpu("MP_SWEAT_L")
  CH("DENRYUU"):WaitManpu()
  local taskDenryuu01 = function()
    CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.1))
    CH("DENRYUU"):WaitNeckRot()
    CH("DENRYUU"):SetNeckRot(RotateTarget(30), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
    CH("DENRYUU"):WaitNeckRot()
    CH("DENRYUU"):SetNeckRot(RotateTarget(-30), RotateTarget(-20), RotateTarget(0), TimeSec(0.4))
    CH("DENRYUU"):WaitNeckRot()
    CH("DENRYUU"):SetNeckRot(RotateTarget(30), RotateTarget(-20), RotateTarget(0), TimeSec(0.4))
    CH("DENRYUU"):WaitNeckRot()
    CH("DENRYUU"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.2))
    CH("DENRYUU"):WaitNeckRot()
  end
  TASK:Regist(taskDenryuu01)
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_GAYA_LP"), TimeSec(1))
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DENRYUU"), 429727128)
  WINDOW:Talk(SymAct("DENRYUU"), 8793305)
  WINDOW:Talk(SymAct("DENRYUU"), -2028064746)
  WINDOW:Talk(SymAct("DENRYUU"), -1643839145)
  WINDOW:Talk(SymAct("DENRYUU"), -142877317)
  WINDOW:Talk(SymAct("DENRYUU"), -295637958)
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("DENRYUU"):ResetNeckRot(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -984760327, PARTNER_1 = -598307144})
  WINDOW:SwitchTalk({PARTNER_0 = -1827202945, PARTNER_1 = -1978914498})
  WINDOW:SwitchTalk({PARTNER_0 = -1591641347, PARTNER_1 = -1204139076})
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_03"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1067603827, PARTNER_1 = 649684530})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -439455083, PARTNER_1 = -53132332})
  WINDOW:SwitchTalk({PARTNER_0 = -671608809, PARTNER_1 = -823975594})
  WINDOW:SwitchTalk({PARTNER_0 = -2120042607, PARTNER_1 = -1732671792})
  WINDOW:SwitchTalk({PARTNER_0 = -1282091757, PARTNER_1 = -1433410478})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main17_choureiyokokujou01_end()
end
function main17_choureiyokokujou02_init()
end
function main17_choureiyokokujou02_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
end
function main17_choureiyokokujou02_end()
end
function main17_choureiyokokujou03_init()
end
function main17_choureiyokokujou03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  EFFECT:CreateRecollectionFilter()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 756545693, PARTNER_1 = 873253340})
  WINDOW:SwitchTalk({PARTNER_0 = 1567757808, PARTNER_1 = 1147741361})
  WINDOW:SwitchTalk({PARTNER_0 = 1866758002, PARTNER_1 = 1985955379})
  WINDOW:SwitchTalk({PARTNER_0 = 958320884, PARTNER_1 = 537256373})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
end
function main17_choureiyokokujou03_end()
end
function main17_choureiyokokujou04_init()
end
function main17_choureiyokokujou04_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_PARTNER_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = 187216502, PARTNER_1 = 305365815})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -1783914504)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  local taskLookAt00 = function()
    CH("DENRYUU"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("KUCHIITO"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
    CH("PEROPPAFU"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    CH("JIRAACHI"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("DEDENNE"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
    CH("BUIZERU"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -1934577991)
  WINDOW:Talk(SymAct("AAKEN"), 85001638)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_05"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("AAKEN"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 470430951)
  WINDOW:Talk(SymAct("AAKEN"), 925329188)
  WINDOW:Talk(SymAct("AAKEN"), 775706213)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 1635631266, PARTNER_1 = 2020012515})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt01 = function()
    CH("HERO"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HORUBII"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("KUCHIITO"):DirTo(CH("DENRYUU"), Speed(200), ROT_TYPE.NEAR)
    CH("PEROPPAFU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    CH("JIRAACHI"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("DEDENNE"):DirTo(CH("DENRYUU"), Speed(200), ROT_TYPE.NEAR)
    CH("BUIZERU"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  CH("AAKEN"):ResetFacialMotion()
  WINDOW:DrawFace(72, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:Talk(SymAct("DENRYUU"), 1397465632)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1246794593, PARTNER_1 = -842494034})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("DEDENNE"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -724320529)
  WINDOW:Talk(SymAct("DENRYUU"), -1112710461)
  WINDOW:Talk(SymAct("DENRYUU"), -1531554942)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("DENRYUU"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("DEDENNE"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:Talk(SymAct("DENRYUU"), -1885667263)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -1769983744)
  WINDOW:Talk(SymAct("AAKEN"), -641620025)
  WINDOW:Talk(SymAct("AAKEN"), -1059416442)
  WINDOW:CloseMessage()
  CH("DENRYUU"):DirTo(RotateTarget(0), Speed(60), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), -336083643)
  WINDOW:Talk(SymAct("DENRYUU"), -219352060)
  WINDOW:Talk(SymAct("DENRYUU"), 1970596043)
  WINDOW:Talk(SymAct("DENRYUU"), 1819269514)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("DENRYUU"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("DEDENNE"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 20, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DENRYUU"), 833068853)
  WINDOW:Talk(SymAct("DENRYUU"), 683454068)
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 59899319, PARTNER_1 = 445304054})
  WINDOW:SwitchTalk({PARTNER_0 = 1439390257, PARTNER_1 = 1288727408})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("DENRYUU"):DirTo(CH("JIRAACHI"), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("DEDENNE"):DirTo(CH("DENRYUU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("DENRYUU"), 1744648371)
  WINDOW:Talk(SymAct("DENRYUU"), 2129005042)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CH("JIRAACHI"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIRAACHI"), -109177539)
  WINDOW:CloseMessage()
  CH("JIRAACHI"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(172, 8, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -530242436)
  WINDOW:CloseMessage()
  CH("DENRYUU"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(324, 88, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), -1994655664)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:Talk(SymAct("PEROPPAFU"), -1878996719)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("DENRYUU"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  CH("DENRYUU"):WaitRotate()
  CH("DEDENNE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("DENRYUU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("DENRYUU"), -1154639150)
  WINDOW:Talk(SymAct("DENRYUU"), -1573475437)
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):SetManpu("MP_SPREE_LP")
  CH("AAKEN"):SetManpu("MP_SPREE_LP")
  CH("HORUBII"):SetManpu("MP_SPREE_LP")
  CH("BUIZERU"):SetManpu("MP_SPREE_LP")
  CH("PEROPPAFU"):SetManpu("MP_SPREE_LP")
  CH("KUCHIITO"):SetManpu("MP_SPREE_LP")
  CH("JIRAACHI"):SetManpu("MP_SPREE_LP")
  CH("HERO"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("DEDENNE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("AAKEN"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("HORUBII"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("BUIZERU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("PEROPPAFU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("KUCHIITO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("JIRAACHI"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("HERO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("PARTNER"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  WINDOW:SysMsg(-310952620)
  CH("PARTNER"):WaitPlayMotion()
  WINDOW:CloseMessage()
  CH("DEDENNE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HORUBII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("BUIZERU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PEROPPAFU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("KUCHIITO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("JIRAACHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DEDENNE"):ResetManpu()
  CH("AAKEN"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  CH("BUIZERU"):ResetManpu()
  CH("PEROPPAFU"):ResetManpu()
  CH("KUCHIITO"):ResetManpu()
  CH("HERO"):ResetManpu()
  CH("PARTNER"):ResetManpu()
  CH("JIRAACHI"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
  CH("HORUBII"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PEROPPAFU"):RunTo(SymPos("P00_PEROPPAFU"), Speed(3))
  CH("BUIZERU"):RunTo(SymPos("P00_BUIZERU"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("DENRYUU"):RunTo(SymPos("P00_DENRYUU"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):RunTo(SymPos("P00_DEDENNE"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("JIRAACHI"):RunTo(SplinePath(SymPos("P00_JIRAACHI"), SymPos("P01_JIRAACHI")), Speed(3))
  TASK:Sleep(TimeSec(0.5))
  CH("KUCHIITO"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(2.5))
  CH("HORUBII"):WalkTo(SymPos("P00_HORUBII"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("KUCHIITO"):WalkTo(SymPos("P00_KUCHIITO"), Speed(1.5))
  CH("PARTNER"):DirTo(SymPos("P00_HORUBII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P00_HORUBII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  CH("KUCHIITO"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), -194245611)
  WINDOW:Talk(SymAct("KUCHIITO"), -549363754)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("HORUBII"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("HORUBII"), -967151977)
  WINDOW:CloseMessage()
  CH("HORUBII"):RunTo(SymPos("P01_HORUBII"), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  CH("KUCHIITO"):RunTo(SymPos("P01_KUCHIITO"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_15"))
  CAMERA:SetTgt(SymCam("CAMERA_15"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1103262296, PARTNER_1 = 1490633497})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:MoveToHero(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
  TASK:Sleep(TimeSec(1))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
  subTowerUpdate()
end
function main17_choureiyokokujou04_end()
end
function groundEnd()
end
