dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function hanyou_choureipanuki01_init()
end
function hanyou_choureipanuki01_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHOUSADAN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("DENRYUU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(272, 16, SymAct("DENRYUU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("DENRYUU"), 1740405836)
  WINDOW:CloseMessage()
  CH("DENRYUU"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):SetManpu("MP_SPREE_LP")
  CH("AAKEN"):SetManpu("MP_SPREE_LP")
  CH("HORUBII"):SetManpu("MP_SPREE_LP")
  CH("BUIZERU"):SetManpu("MP_SPREE_LP")
  CH("PEROPPAFU"):SetManpu("MP_SPREE_LP")
  CH("KUCHIITO"):SetManpu("MP_SPREE_LP")
  CH("JIRAACHI"):SetManpu("MP_SPREE_LP")
  CH("HERO"):SetManpu("MP_SPREE_LP")
  CH("DEDENNE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("AAKEN"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("HORUBII"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("BUIZERU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("PEROPPAFU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("KUCHIITO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("JIRAACHI"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  CH("HERO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  WINDOW:SysMsg(2124893453)
  WINDOW:CloseMessage()
  CH("DEDENNE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HORUBII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("BUIZERU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PEROPPAFU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("KUCHIITO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("JIRAACHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DEDENNE"):ResetManpu()
  CH("AAKEN"):ResetManpu()
  CH("HORUBII"):ResetManpu()
  CH("BUIZERU"):ResetManpu()
  CH("PEROPPAFU"):ResetManpu()
  CH("KUCHIITO"):ResetManpu()
  CH("HERO"):ResetManpu()
  CH("JIRAACHI"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
  CH("HORUBII"):DirTo(SymPos("P00_HORUBII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PEROPPAFU"):RunTo(SymPos("P00_PEROPPAFU"), Speed(3))
  CH("BUIZERU"):RunTo(SymPos("P00_BUIZERU"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("HORUBII"):WalkTo(SymPos("P00_HORUBII"), Speed(3))
  CH("DENRYUU"):RunTo(SymPos("P00_DENRYUU"), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):RunTo(SymPos("P00_DEDENNE"), Speed(3))
  CH("KUCHIITO"):RunTo(SplinePath(SymPos("P00_KUCHIITO"), SymPos("P01_KUCHIITO")), Speed(3))
  TASK:Sleep(TimeSec(0.1))
  CH("JIRAACHI"):RunTo(SplinePath(SymPos("P00_JIRAACHI"), SymPos("P01_JIRAACHI")), Speed(3))
  TASK:Sleep(TimeSec(2.5))
  CAMERA:MoveToHero(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
  CH("AAKEN"):SetVisible(false)
  CH("HORUBII"):SetVisible(false)
  CH("PEROPPAFU"):SetVisible(false)
  CH("BUIZERU"):SetVisible(false)
  CH("DENRYUU"):SetVisible(false)
  CH("DEDENNE"):SetVisible(false)
  CH("KUCHIITO"):SetVisible(false)
  CH("JIRAACHI"):SetVisible(false)
  subTowerUpdate()
end
function hanyou_choureipanuki01_end()
end
function groundEnd()
end
