dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main18_nidometenkeiclear1st01_init()
end
function main18_nidometenkeiclear1st01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 218223799, PARTNER_1 = 337307126})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 1060615733)
  WINDOW:Talk(SymAct("AAKEN"), 640452468)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 1768755635)
  WINDOW:Talk(SymAct("KONOHANA"), 1886789874)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 1532719921)
  WINDOW:CloseMessage()
end
function main18_nidometenkeiclear1st01_end()
end
function main18_nidometenkeiclear1st02_init()
end
function main18_nidometenkeiclear1st02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
  CH("KONOHANA"):RunTo(SymPos("P00_KONOHANA"), Speed(3))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("KONOHANA"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 1111507568)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KODAIMOJI"), Volume(256))
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main18_nidometenkeiclear1st02_end()
end
function main18_nidometenkeiclear1st04_init()
end
function main18_nidometenkeiclear1st04_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KODAIMOJI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
  CH("KONOHANA"):RunTo(SymPos("P00_KONOHANA"), Speed(3))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("KONOHANA"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CH("AAKEN"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -975675713, PARTNER_1 = -591171586})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(202989786)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("AAKEN"):ResetNeckRot(TimeSec(0.15))
  CH("AAKEN"):WaitNeckRot()
  CH("AAKEN"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFaceF(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 352473499)
  WINDOW:CloseMessage()
  CH("KONOHANA"):ResetNeckRot(TimeSec(0.15))
  CH("KONOHANA"):WaitNeckRot()
  CH("KONOHANA"):WalkTo(SymPos("P01_KONOHANA"), Speed(2))
  CH("HERO"):ResetNeckRot(TimeSec(0.1))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.15))
  CH("KONOHANA"):WaitMove()
  WINDOW:DrawFaceF(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1043268184)
  CH("AAKEN"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main18_nidometenkeiclear1st04_end()
end
function main18_nidometenkeiclear1st05_init()
end
function main18_nidometenkeiclear1st05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KODAIMOJI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 657732377)
  WINDOW:Talk(SymAct("AAKEN"), 1752540638)
  WINDOW:Talk(SymAct("AAKEN"), 1903072415)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(1514391388)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main18_nidometenkeiclear1st05_end()
end
function main18_nidometenkeiclear1st06_init()
end
function main18_nidometenkeiclear1st06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KODAIMOJI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P00_PARTNER"),
    Speed(3),
    SymPos("P_SEKIHI")
  })
  CH("HERO"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(0, 15)
  WINDOW:SwitchTalk({PARTNER_0 = 1129903645, PARTNER_1 = -993989934})
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir, {
    CH("AAKEN"),
    SymPos("P00_AAKEN"),
    Speed(2),
    SymPos("P_SEKIHI")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P00_HERO"),
    Speed(2),
    SymPos("P_SEKIHI")
  })
  TASK:Regist(subEveMoveDir, {
    CH("KONOHANA"),
    SymPos("P00_KONOHANA"),
    Speed(2),
    SymPos("P_SEKIHI")
  })
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -572793965)
  WINDOW:Talk(SymAct("KONOHANA"), 514641716)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 129498741)
  WINDOW:Talk(SymAct("AAKEN"), 748334518)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_QUESTION")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), 897686775)
  WINDOW:CloseMessage()
  CH("AAKEN"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 2059405872)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("KONOHANA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("AAKEN"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(40, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1675311985, PARTNER_1 = 1224108210})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1374509555, PARTNER_1 = -696957636})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -814844803)
  TASK:WaitTask()
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1508857775, PARTNER_1 = -1089758960})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(40, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1809397037, PARTNER_1 = -1925317742})
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -1032032939)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -613983212)
  WINDOW:Talk(SymAct("AAKEN"), -263581737)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(172, 8, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -380551530, PARTNER_1 = 1858675289})
  WINDOW:SwitchTalk({PARTNER_0 = 2010256152, PARTNER_1 = 1002934504})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), 584884649)
  WINDOW:Talk(SymAct("KONOHANA"), 166851178)
  WINDOW:Talk(SymAct("KONOHANA"), 283820843)
  subEveCloseMsg()
  local taskPartner00 = function()
    subEveNod(CH("PARTNER"))
  end
  TASK:Regist(taskPartner00)
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1605064172, PARTNER_1 = 1185965229})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:DrawFaceOffset(40, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1839019886, PARTNER_1 = 1954940463})
  WINDOW:SwitchTalk({PARTNER_0 = -216130848, PARTNER_1 = -368759903})
  WINDOW:SwitchTalk({PARTNER_0 = -2089027699, PARTNER_1 = -1704933684})
  WINDOW:SwitchTalk({PARTNER_0 = -1320315633, PARTNER_1 = -1470716850})
  WINDOW:SwitchTalk({PARTNER_0 = -417910135, PARTNER_1 = -32767032})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -719237109)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -868589238)
  WINDOW:Talk(SymAct("KONOHANA"), 1268940165)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("HERO"), FACE_TYPE.CATCHBREATH)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Monologue(1387875524)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1848747933, PARTNER_1 = -1999279838})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(-170), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -1544013087, PARTNER_1 = -1159525472})
  WINDOW:SwitchTalk({PARTNER_0 = -173892249, PARTNER_1 = -323376090})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), -946536475)
  WINDOW:Talk(SymAct("KONOHANA"), -561000796)
  WINDOW:Talk(SymAct("KONOHANA"), 1494733419)
  WINDOW:Talk(SymAct("KONOHANA"), 1074586410)
  WINDOW:Talk(SymAct("KONOHANA"), 695353094)
  WINDOW:Talk(SymAct("KONOHANA"), 812191303)
  WINDOW:Talk(SymAct("KONOHANA"), 457465220)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  CH("AAKEN"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("AAKEN"), 39808197)
  WINDOW:Talk(SymAct("AAKEN"), 1293875714)
  WINDOW:CloseMessage()
  CH("AAKEN"):ResetFacialMotion()
  CH("AAKEN"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 1409665859)
  WINDOW:CloseMessage()
  CH("AAKEN"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 2133366912)
  WINDOW:Talk(SymAct("AAKEN"), 1714661825)
  subEveCloseMsg()
  local taskNotice00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):SetManpu("MP_NOTICE_R")
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("AAKEN"):SetManpu("MP_NOTICE_L")
    CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
    CH("KONOHANA"):WaitManpu()
  end
  TASK:Regist(taskNotice00)
  SOUND:FadeOutBgm(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNNE_ALERT"))
  WINDOW:SysMsg(-508840690)
  SOUND:WaitSe(SymSnd("SE_EVT_DEDENNNE_ALERT"))
  subEveCloseMsg()
  local taskHero00 = function()
    CH("HERO"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetMotion(SymMot("PUSH"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.2))
  local taskAaken00 = function()
    CH("AAKEN"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):WaitRotate()
    TASK:Sleep(TimeSec(0.4))
    CH("AAKEN"):SetMotion(SymMot("PUSH"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.3))
    CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.3))
    CH("AAKEN"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):WaitRotate()
  end
  TASK:Regist(taskAaken00)
  CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(1.5), Volume(256))
  WINDOW:SysMsg(-122649521)
  subEveCloseMsg()
  WINDOW:SysMsg(1896951632)
  WINDOW:SysMsg(1745493521)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(40, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 1126649298, PARTNER_1 = 1513913491})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 360573524)
  WINDOW:Talk(SymAct("AAKEN"), 208067349)
  subEveCloseMsg()
  WINDOW:SysMsg(659261654)
  WINDOW:SysMsg(1045477783)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -1178032808)
  subEveCloseMsg()
  WINDOW:SysMsg(-1596746727)
  WINDOW:CloseMessage()
  CH("AAKEN"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_QUESTION")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), -911390667)
  subEveCloseMsg()
  WINDOW:SysMsg(-793347724)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main18_nidometenkeiclear1st06_end()
end
function main18_nidometenkeiclear1st07_init()
end
function main18_nidometenkeiclear1st07_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskKuchiito00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(4.5))
      CH("KUCHIITO"):DirTo(RotateTarget(-160), Speed(60), ROT_TYPE.NEAR)
      CH("KUCHIITO"):WaitRotate()
      TASK:Sleep(TimeSec(6.5))
      CH("KUCHIITO"):DirTo(RotateTarget(180), Speed(60), ROT_TYPE.NEAR)
      CH("KUCHIITO"):WaitRotate()
      TASK:Sleep(TimeSec(7))
      CH("KUCHIITO"):DirTo(RotateTarget(160), Speed(60), ROT_TYPE.NEAR)
      CH("KUCHIITO"):WaitRotate()
      TASK:Sleep(TimeSec(8))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskKuchiito00)
  local taskBuizeru00 = function()
    function TaskL.Loop()
      CH("BUIZERU"):WalkTo(SymPos("P00_BUIZERU"), Speed(1.5))
      CH("BUIZERU"):WaitMove()
      TASK:Sleep(TimeSec(2.5))
      CH("BUIZERU"):DirTo(RotateTarget(-90), Speed(60), ROT_TYPE.NEAR)
      CH("BUIZERU"):WaitRotate()
      TASK:Sleep(TimeSec(5))
      CH("BUIZERU"):WalkTo(SymPos("P01_BUIZERU"), Speed(1.5))
      CH("BUIZERU"):WaitMove()
      TASK:Sleep(TimeSec(4.5))
      CH("BUIZERU"):DirTo(RotateTarget(140), Speed(200), ROT_TYPE.NEAR)
      CH("BUIZERU"):WaitRotate()
      TASK:Sleep(TimeSec(5.5))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskBuizeru00)
  local taskHorubii00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.5))
      subEveLookAround(CH("HORUBII"), Speed(500))
      TASK:Sleep(TimeSec(1.5))
      CH("HORUBII"):WalkTo(SymPos("P00_HORUBII"), Speed(2))
      CH("HORUBII"):WaitMove()
      TASK:Sleep(TimeSec(2.5))
      CH("HORUBII"):DirTo(RotateTarget(-120), Speed(200), ROT_TYPE.NEAR)
      CH("HORUBII"):WaitRotate()
      TASK:Sleep(TimeSec(4.5))
      CH("HORUBII"):WalkTo(SymPos("P01_HORUBII"), Speed(2))
      CH("HORUBII"):WaitMove()
      TASK:Sleep(TimeSec(3.5))
      CH("HORUBII"):DirTo(RotateTarget(40), Speed(350), ROT_TYPE.NEAR)
      CH("HORUBII"):WaitRotate()
      TASK:Sleep(TimeSec(4.5))
      CH("HORUBII"):WalkTo(SymPos("P02_HORUBII"), Speed(2))
      CH("HORUBII"):WaitMove()
      TASK:Sleep(TimeSec(3))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskHorubii00)
  CH("DEDENNE"):SetManpu("EV_ELECTRIC_TEL_LP")
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_ENV_CAVE_LP"), Volume(128))
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DEDENNE"), -73717065)
  WINDOW:Talk(SymAct("DEDENNE"), -494920714)
  WINDOW:Talk(SymAct("DEDENNE"), -1379824335)
  WINDOW:Talk(SymAct("DEDENNE"), -1260733328)
  subEveCloseMsg()
  WINDOW:SwitchTalk({PARTNER_0 = -1611141197, PARTNER_1 = -2031296782})
  WINDOW:SwitchTalk({PARTNER_0 = 24429117, PARTNER_1 = 409990012})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_FLY_SWEAT")
  CH("DEDENNE"):WaitManpu()
  CH("DEDENNE"):SetManpu("EV_ELECTRIC_TEL_LP")
  CH("DEDENNE"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DEDENNE"), -1459985192)
  WINDOW:CloseMessage()
  CH("DEDENNE"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("DEDENNE"):WaitManpu()
  CH("DEDENNE"):SetManpu("EV_ELECTRIC_TEL_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("DEDENNE"), -1310632551)
  WINDOW:Talk(SymAct("DEDENNE"), -1697905062)
  WINDOW:Talk(SymAct("DEDENNE"), -2083047653)
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_ENV_CAVE_LP"), TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("DEDENNE"):ResetManpu()
end
function main18_nidometenkeiclear1st07_end()
end
function main18_nidometenkeiclear1st08_init()
end
function main18_nidometenkeiclear1st08_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -862543396)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -712142691, PARTNER_1 = -23018658})
  subEveCloseMsg()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHUKEI"), Volume(256))
  WINDOW:SysMsg(-407113185)
  WINDOW:SysMsg(1612967632)
  WINDOW:SysMsg(2033770385)
  WINDOW:SysMsg(273023933)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(157102844)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("AAKEN"):SetManpu("MP_SHOCK_L")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 577790271)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 996888702)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("PARTNER"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(RotateTarget(-170), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1948960441, PARTNER_1 = 1831991288})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("KONOHANA"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("AAKEN"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:SysMsg(1176282171)
  WINDOW:SysMsg(1594332538)
  WINDOW:SysMsg(-660633163)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), -1048266508)
  WINDOW:Talk(SymAct("KONOHANA"), 49523795)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  CH("AAKEN"):DirTo(SymPos("P_SEKIHI"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 468229394)
  WINDOW:Talk(SymAct("AAKEN"), 818269905)
  WINDOW:CloseMessage()
  CH("AAKEN"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 702480272)
  WINDOW:Talk(SymAct("AAKEN"), 1721723223)
  subEveCloseMsg()
  WINDOW:DrawFace(172, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-40, 0)
  WINDOW:SwitchTalk({PARTNER_0 = 2139379734, PARTNER_1 = 1420364757})
  WINDOW:SwitchTalk({PARTNER_0 = 1303526036, PARTNER_1 = -903207333})
  WINDOW:SwitchTalk({PARTNER_0 = -751757542, PARTNER_1 = -1169175754})
  WINDOW:SwitchTalk({PARTNER_0 = -1554711945, PARTNER_1 = -2005292620})
  WINDOW:CloseMessage()
  CH("AAKEN"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1855809291, PARTNER_1 = -568127950})
  WINDOW:SwitchTalk({PARTNER_0 = -952615053, PARTNER_1 = -334140240})
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.2))
  local taskPartner00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_GAYA_LP"))
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):SetManpu("MP_SPREE_LP")
      CH("PARTNER"):SetMotion(SymMot("SPEAK"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):ResetManpu()
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Regist(subEveDoubleJump, {
        CH("PARTNER")
      })
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
    end
    function TaskL.Finish()
      SOUND:FadeOutSe(SymSnd("SE_EVT_GAYA_LP"), TimeSec(0.5))
      CH("PARTNER"):ResetManpu()
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("PARTNER"):SetMotionRaito(Raito(1))
      return
    end
  end
  TASK:Regist(Group("grpPartner"), taskPartner00)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(-183607823)
  WINDOW:Monologue(1922449726)
  WINDOW:Monologue(1804431487)
  WINDOW:Monologue(664335247)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("AAKEN"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:ExitNotifyTasks(Group("grpPartner"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1048822478, PARTNER_1 = 363761933})
  WINDOW:SwitchTalk({PARTNER_0 = 213229644, PARTNER_1 = 1140078219})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1525614538, PARTNER_1 = 1908560905})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("AAKEN"), 1759077704)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -280921721)
  WINDOW:Talk(SymAct("KONOHANA"), -161855290)
  subEveCloseMsg()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("HERO"):SetManpu("MP_NOTICE_R")
    CH("AAKEN"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):SetManpu("MP_NOTICE_L")
  end
  TASK:Regist(taskLookAt01)
  SOUND:FadeOutBgm(TimeSec(1))
  WINDOW:SysMsg(-1624992534)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeOut(TimeSec(0.1), true)
end
function main18_nidometenkeiclear1st08_end()
end
function main18_nidometenkeiclear1st09_init()
end
function main18_nidometenkeiclear1st09_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_DEDEEN"))
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(172, 8, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Monologue(-2042649173)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1391266200, PARTNER_1 = -1274427607})
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("AAKEN")
  })
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), -79146514)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("WARUBIARU"), -497852241)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_03"), Volume(256))
  CH("WARUBIARU"):WalkTo(SymPos("P00_WARUBIARU"), Speed(1))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -914476180, PARTNER_1 = -798686675})
  subEveCloseMsg()
  WINDOW:DrawFace(172, 8, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-20, 0)
  WINDOW:Monologue(1476206306)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 1323708323)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1919862012, PARTNER_1 = -1802892731})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -1079551610)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("WARUBIARU"):SetPosition(SymPos("P01_WARUBIARU"))
  CH("WARUBIARU"):WalkTo(SymPos("P02_WARUBIARU"), Speed(1))
  CH("WARUBIARU"):WaitMove()
  SOUND:FadeOutBgm(TimeSec(0.5))
  WINDOW:SysMsg(-1497601849)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("WARUBIARU"):SetManpu("MP_EXCLAMATION")
  CH("WARUBIARU"):WaitManpu()
  subEveCloseMsg()
  WINDOW:SysMsg(-369230336)
  WINDOW:CloseMessage()
  CH("WARUBIARU"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("WARUBIARU"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("WARUBIARU"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  CH("WARUBIARU"):WaitRotate()
  TASK:Sleep(TimeSec(0.4))
  WINDOW:DrawFace(324, 88, SymAct("WARUBIARU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIARU"), -253309119)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"), Volume(256))
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0.5))
  TASK:Sleep(TimeSec(0.3))
  CH("WARUBIARU"):SetManpu("MP_EXCLAMATION")
  CH("WARUBIARU"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeChange(Level(0.5), Level(1), TimeSec(0.3), true)
  SCREEN_A:FadeOut(TimeSec(0), false)
end
function main18_nidometenkeiclear1st09_end()
end
function main18_nidometenkeiclear1st14_init()
end
function main18_nidometenkeiclear1st14_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0))
  CUT:Load(SymCut("m18_110_14"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  MAP:ReturnLightColor(TimeSec(0, TIME_TYPE.FRAME))
end
function main18_nidometenkeiclear1st14_cut_01()
  SOUND:PlaySe(SymSnd("SE_EVT_RAIKOU_APPEAR_01"), Volume(256))
end
function main18_nidometenkeiclear1st14_cut_02()
  SOUND:PlaySe(SymSnd("SE_EVT_SUIKUN_APPEAR_01"), Volume(256))
end
function main18_nidometenkeiclear1st14_cut_03()
  SOUND:PlaySe(SymSnd("SE_EVT_RAIKOU_APPEAR_02"), Volume(256))
end
function main18_nidometenkeiclear1st14_cut_04()
  SOUND:PlaySe(SymSnd("SE_EVT_SUIKUN_APPEAR_02"), Volume(256))
end
function main18_nidometenkeiclear1st14_cut_04_5()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NANIKAGACHIGAU"), Volume(256))
end
function main18_nidometenkeiclear1st14_cut_05()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
end
function main18_nidometenkeiclear1st14_end()
end
function main18_nidometenkeiclear1st15_init()
end
function main18_nidometenkeiclear1st15_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NANIKAGACHIGAU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CH("WARUBIARU"):DirTo(CH("RAIKOU"), Speed(350), ROT_TYPE.NEAR)
  CH("WARUBIARU"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("WARUBIARU"):DirTo(CH("SUIKUN"), Speed(350), ROT_TYPE.NEAR)
  CH("WARUBIARU"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("WARUBIARU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("WARUBIARU"), -607413118)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct("SUIKUN"), -1026511421)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("WARUBIARU"):DirTo(CH("RAIKOU"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  CH("WARUBIARU"):WaitRotate()
  WINDOW:Talk(SymAct("RAIKOU"), 1162391820)
  WINDOW:Talk(SymAct("RAIKOU"), 1548976205)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("WARUBIARU"):SetDir(RotateTarget(-90))
  CH("WARUBIARU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(2))
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 892165217, PARTNER_1 = 741764384})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 119226083)
  WINDOW:Talk(SymAct("AAKEN"), 503320482)
  WINDOW:Talk(SymAct("AAKEN"), 1363253605)
  WINDOW:Talk(SymAct("AAKEN"), 1213900836)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 1668807655)
  WINDOW:Talk(SymAct("KONOHANA"), 2053950118)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -34285975, PARTNER_1 = -454039768})
  WINDOW:CloseMessage()
  CH("AAKEN"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("AAKEN"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  CH("AAKEN"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 1833847863)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1951759734, PARTNER_1 = 1601711797})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1180901364, PARTNER_1 = 153258291})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main18_nidometenkeiclear1st15_end()
end
function main18_nidometenkeiclear1st16_init()
end
function main18_nidometenkeiclear1st16_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NANIKAGACHIGAU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("WARUBIARU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CH("WARUBIARU"):DirTo(CH("RAIKOU"), Speed(350), ROT_TYPE.NEAR)
  CH("WARUBIARU"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("WARUBIARU"):DirTo(CH("SUIKUN"), Speed(350), ROT_TYPE.NEAR)
  CH("WARUBIARU"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("WARUBIARU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIARU"), 272218226)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  CH("WARUBIARU"):WalkTo(SymPos("P00_WARUBIARU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("RAIKOU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("SUIKUN"):SetManpu("MP_EXCLAMATION")
  CH("SUIKUN"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("RAIKOU"):DirTo(SymPos("P00_WARUBIARU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("SUIKUN"):DirTo(SymPos("P00_WARUBIARU"), Speed(350), ROT_TYPE.NEAR)
  CH("RAIKOU"):WaitRotate()
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("SUIKUN"):WaitRotate()
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("RAIKOU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("RAIKOU"), 991226801)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("WARUBIARU"):SetPosition(SymPos("P01_WARUBIARU"))
  CH("WARUBIARU"):WalkTo(SymPos("P00_WARUBIARU"), Speed(1.2))
  WINDOW:DrawFace(324, 88, SymAct("WARUBIARU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIARU"), 571464432)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("WARUBIARU"):SetPosition(SymPos("P02_WARUBIARU"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("KONOHANA"):ResetManpu()
  WINDOW:DrawFaceF(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1516779969, PARTNER_1 = -1131612290})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-705549486)
  WINDOW:Monologue(-857138669)
  WINDOW:Monologue(-406566448)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -18909039, PARTNER_1 = -1314984362})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("AAKEN"):SetVisible(false)
  CH("KONOHANA"):SetVisible(false)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CH("WARUBIARU"):WalkTo(SymPos("P00_WARUBIARU"), Speed(1))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("WARUBIARU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIARU"), -1467621609)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetDefaultGroundFovy()
end
function main18_nidometenkeiclear1st16_end()
end
function main18_nidometenkeiclear1st19_init()
end
function main18_nidometenkeiclear1st19_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NANIKAGACHIGAU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-2086105900)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -1699496555)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 489398618)
  WINDOW:Talk(SymAct("KONOHANA"), 70291483)
  subEveCloseMsg()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(778966646)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(CH("WARUBIARU"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(930424631)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("AAKEN"):SetVisible(false)
  CH("KONOHANA"):SetVisible(false)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("WARUBIARU"):WalkTo(SymPos("P00_WARUBIARU"), Speed(1))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 475559156)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CH("AAKEN"):SetVisible(true)
  CH("KONOHANA"):SetVisible(true)
  CH("WARUBIARU"):SetPosition(SymPos("P02_WARUBIARU"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(88294837)
  WINDOW:Monologue(1241699186)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("AAKEN"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  CH("HERO"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1394205235, PARTNER_1 = 2016719344})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 1630503089)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KONOHANA"), -424174466)
  subEveCloseMsg()
  CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-5460673)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main18_nidometenkeiclear1st19_end()
end
function main18_nidometenkeiclear1st22_init()
end
function main18_nidometenkeiclear1st22_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Load(SymCut("m18_110_22"))
  SOUND:FadeOutBgm(TimeSec(1.5))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main18_nidometenkeiclear1st22_cut_01()
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
end
function main18_nidometenkeiclear1st22_cut_02()
  SOUND:PlaySe(SymSnd("SE_EVT_CRYSTAL_ATTACK"), Volume(256))
end
function main18_nidometenkeiclear1st22_cut_03()
  SOUND:PlaySe(SymSnd("SE_EVT_CRYSTAL_LIGHT_01"), Volume(256))
end
function main18_nidometenkeiclear1st22_cut_04()
  SOUND:PlayEnv(SymSnd("SE_EVT_CRYSTAL_LIGHT_02_LP"), Volume(256))
end
function main18_nidometenkeiclear1st22_end()
end
function main18_nidometenkeiclear1st23_init()
end
function main18_nidometenkeiclear1st23_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  EFFECT:Create("effectLakeLuminousNotalLp", SymEff("EV_LAKE_LUMINOUS_NOTAL_LP"))
  EFFECT:SetPosition("effectLakeLuminousNotalLp", SymPos("P_EFF_EV_LAKE_LUMINOUS_LP"))
  EFFECT:Play("effectLakeLuminousNotalLp")
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("RAIKOU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("RAIKOU"), -1764593389)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  MAP:ReturnLightColor(TimeSec(45, TIME_TYPE.FRAME))
  EFFECT:Remove("effectLakeLuminousNotalLp")
  CAMERA:SetDefaultGroundFovy()
end
function main18_nidometenkeiclear1st23_end()
end
function main18_nidometenkeiclear1st24_init()
end
function main18_nidometenkeiclear1st24_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("KONOHANA"):SetMotion(SymMot("EV023_SHRINK01"), LOOP.ON, TimeSec(0))
  CH("AAKEN"):SetMotion(SymMot("ENDURE"), LOOP.ON, TimeSec(0))
  EFFECT:Create("effectLakeLuminousLp", SymEff("EV_LAKE_LUMINOUS_LP"))
  EFFECT:SetPosition("effectLakeLuminousLp", SymPos("P_EFF_EV_LAKE_LUMINOUS_LP"))
  EFFECT:Play("effectLakeLuminousLp")
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.7))
  SOUND:FadeOutEnv(TimeSec(2))
  SOUND:PlaySe(SymSnd("SE_EVT_CRYSTAL_LIGHT_03"), Volume(256))
  CAMERA:WaitMove()
  EFFECT:ChangeColor("effectLakeLuminousLp", Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  EFFECT:Create("effectLakeLuminousEd", SymEff("EV_LAKE_LUMINOUS_ED"))
  EFFECT:SetPosition("effectLakeLuminousEd", SymPos("P_EFF_EV_LAKE_LUMINOUS_LP"))
  EFFECT:Play("effectLakeLuminousEd")
  TASK:Sleep(TimeSec(3))
  MAP:ReturnLightColor(TimeSec(30, TIME_TYPE.FRAME))
  EFFECT:Wait("effectLakeLuminousEd")
  EFFECT:Remove("effectLakeLuminousEd")
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  CH("KONOHANA"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("AAKEN"):SetManpu("MP_NOTICE_R")
  CH("AAKEN"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  MAP:ReturnLightColor(TimeSec(45, TIME_TYPE.FRAME))
  EFFECT:Remove("effectLakeLuminousLp")
  CAMERA:SetDefaultGroundFovy()
end
function main18_nidometenkeiclear1st24_end()
end
function main18_nidometenkeiclear1st25_init()
end
function main18_nidometenkeiclear1st25_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1882636206, PARTNER_1 = -1528556655})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("PARTNER"):DirTo(CH("WARUBIARU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("WARUBIARU"), Speed(350), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("WARUBIARU"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("WARUBIARU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1107352880, PARTNER_1 = -222383081})
  WINDOW:SwitchTalk({PARTNER_0 = -341473962, PARTNER_1 = -1064773995})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("WARUBIARU"):SetManpu("MP_QUESTION")
  CH("WARUBIARU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("WARUBIARU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("WARUBIARU"), -644618284)
  WINDOW:DrawFace(324, 88, SymAct("WARUBIARU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WARUBIARU"), 1577843483)
  WINDOW:Talk(SymAct("WARUBIARU"), 1192282714)
  WINDOW:Talk(SymAct("WARUBIARU"), -2073567491)
  WINDOW:Talk(SymAct("WARUBIARU"), -1652756548)
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  CH("AAKEN"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1236157313, PARTNER_1 = -1354068674})
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-536142855)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_04"), Volume(256))
  TASK:Sleep(TimeSec(1))
  TASK:Regist(subEveFukumiWarai, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -116381000)
  WINDOW:Talk(SymAct("KONOHANA"), -767723141)
  WINDOW:Talk(SymAct("KONOHANA"), -886683590)
  WINDOW:CloseMessage()
  CH("AAKEN"):SetVisible(false)
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("KONOHANA"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("KONOHANA"):SetMotion(SymMot("EV016_LOOKUP00"), LOOP.OFF)
  CH("KONOHANA"):WaitPlayMotion()
  CH("KONOHANA"):SetMotion(SymMot("EV016_LOOKUP01"), LOOP.ON)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1287542005)
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.5))
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CH("AAKEN"):SetVisible(true)
  CH("KONOHANA"):SetMotion(SymMot("EV016_LOOKUP02"), LOOP.OFF)
  CH("KONOHANA"):WaitPlayMotion()
  CH("KONOHANA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1436902836)
  WINDOW:Talk(SymAct("KONOHANA"), 1021032856)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main18_nidometenkeiclear1st25_end()
end
function main18_nidometenkeiclear1st26_init()
end
function main18_nidometenkeiclear1st26_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  CUT:Load(SymCut("m18_110_26"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main18_nidometenkeiclear1st26_cut_script_01()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOHANA_AURA_01"), Volume(256))
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_KONOHANA_AURA_01_LP"), Volume(256))
  TASK:Sleep(TimeSec(45, TIME_TYPE.FRAME))
  SOUND:FadeOutSe(SymSnd("SE_EVT_KONOHANA_AURA_01_LP"), TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_KONOHANA_AURA_02_LP"), Volume(256))
end
function main18_nidometenkeiclear1st26_cut_talk_01()
  SOUND:FadeOutSe(SymSnd("SE_EVT_KONOHANA_AURA_02_LP"), TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA_CHOKUGEKI"), Volume(256))
  local taskSekikaSe = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKACHUU_LP"), Volume(256))
    TASK:Sleep(TimeSec(60, TIME_TYPE.FRAME))
    SOUND:FadeOutSe(SymSnd("SE_EVT_SEKIKACHUU_LP"), TimeSec(1.5))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(256))
  end
  TASK:Regist(taskSekikaSe)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("WARUBIARU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("WARUBIARU"), 633374937)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main18_nidometenkeiclear1st26_end()
end
function main18_nidometenkeiclear1st27_init()
end
function main18_nidometenkeiclear1st27_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  CH("RAIKOU"):SetVisible(false)
  CH("SUIKUN"):SetVisible(false)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 250469146)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 402057819, PARTNER_1 = 1488419996})
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetEyeMotion(EYE_MOTION.ANGRY)
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1101811165)
  WINDOW:Talk(SymAct("KONOHANA"), 1786846750)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):WaitManpu()
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1939484511)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -201182320)
  WINDOW:Talk(SymAct("KONOHANA"), -317127983)
  WINDOW:Talk(SymAct("KONOHANA"), -1593016031)
  WINDOW:Talk(SymAct("KONOHANA"), -1206407072)
  subEveCloseMsg()
  WINDOW:DrawFaceF(172, 8, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(70, 0)
  WINDOW:Monologue(-1824857181)
  subEveCloseMsg()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("KONOHANA"):SetManpu("MP_SHOCK_R")
    CH("PARTNER"):SetManpu("MP_SHOCK_L")
    CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskLookAt00)
  WINDOW:Talk(SymAct("RAIKOU"), -1977494814)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  CH("KONOHANA"):WaitRotate()
  CH("KONOHANA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("RAIKOU"):SetVisible(true)
  CH("SUIKUN"):SetVisible(true)
  local taskRaikou00 = function()
    CH("RAIKOU"):RunTo(SymPos("P00_RAIKOU"), Speed(3))
    CH("RAIKOU"):WaitMove()
    CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  end
  TASK:Regist(taskRaikou00)
  local taskSuikun00 = function()
    CH("SUIKUN"):RunTo(SymPos("P00_SUIKUN"), Speed(3))
    CH("SUIKUN"):WaitMove()
    CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  end
  TASK:Regist(taskSuikun00)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  local taskAaken00 = function()
    CH("AAKEN"):SetFacialMotion(FACIAL_MOTION.DECIDE)
    CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
    CH("AAKEN"):WaitMove()
    CH("AAKEN"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
    CH("AAKEN"):WaitRotate()
    CH("AAKEN"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  end
  TASK:Regist(taskAaken00)
  TASK:WaitTask()
  TASK:Sleep(TimeSec(1.5))
  CH("SUIKUN"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -983546843)
  WINDOW:Talk(SymAct("AAKEN"), -595888796)
  WINDOW:CloseMessage()
  CH("AAKEN"):SetNeckRot(RotateTarget(40), RotateTarget(0), RotateTarget(0), TimeSec(0.15))
  CH("AAKEN"):WaitNeckRot()
  CH("AAKEN"):SetManpu("MP_SPREE_LP")
  local taskPartner00 = function()
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):WaitManpu()
    CH("PARTNER"):DirTo(CH("AAKEN"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    CH("HERO"):DirTo(CH("AAKEN"), Speed(500), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskPartner00)
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), -145348953)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("AAKEN"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -296937498, PARTNER_1 = 1775569705})
  WINDOW:CloseMessage()
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(3))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("AAKEN"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 1892563560)
  WINDOW:CloseMessage()
  CH("AAKEN"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 431023684)
  WINDOW:Talk(SymAct("AAKEN"), 11261701)
  WINDOW:Talk(SymAct("AAKEN"), 730236102)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  subEveNod(CH("HERO"))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(849196423)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutBgm(TimeSec(0.7))
  SCREEN_A:FadeOut(TimeSec(0.1), true)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Narration(TimeSec(0), TimeSec(0), 2111578944)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:CloseMessage()
end
function main18_nidometenkeiclear1st27_end()
end
function main18_nidometenkeiclear1st28_init()
end
function main18_nidometenkeiclear1st28_start()
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m18_110_28"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main18_nidometenkeiclear1st28_cut_01()
  SOUND:PlaySe(SymSnd("SE_EVT_GETDARK"), Volume(256))
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0.5))
end
function main18_nidometenkeiclear1st28_cut_02()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_03"), Volume(256))
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(190))
  TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_APPEAR_01_LP"), Volume(190))
end
function main18_nidometenkeiclear1st28_cut_03()
  SOUND:FadeOutSe(SymSnd("SE_EVT_IBERUTARU_APPEAR_01_LP"), TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_APPEAR_02"), Volume(256))
  SOUND:FadeOutEnv(TimeSec(2))
end
function main18_nidometenkeiclear1st28_cut_04()
  SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(256))
  TASK:Sleep(TimeSec(48, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(256))
  TASK:Sleep(TimeSec(48, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(256))
end
function main18_nidometenkeiclear1st28_end()
end
function main18_nidometenkeiclear1st29_init()
end
function main18_nidometenkeiclear1st29_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  CAMERA:SetRotateZ(SymCam("CAMERA_10"))
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("AAKEN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0))
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  CH("IBERUTARU"):SetMotion(SymMot("EV000_WAIT02"), LOOP.ON, TimeSec(0))
  CH("IBERUTARU"):SetScale(Scale(1.2))
  CH("KONOHANA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  local taskIberutaruFly = function()
    function TaskL.Loop()
      SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(256))
      TASK:Sleep(TimeSec(48, TIME_TYPE.FRAME))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(Group("grpIberutaru"), taskIberutaruFly)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  TASK:Sleep(TimeSec(0.1))
  CH("RAIKOU"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("AAKEN"), 1690767873)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:SetRotateZ(Degree(0))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1340752322)
  WINDOW:SysMsg(1458663555)
  WINDOW:CloseMessage()
  CH("IBERUTARU"):SetDir(RotateTarget(75))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-781620148)
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("grpIberutaru"))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main18_nidometenkeiclear1st29_end()
end
function main18_nidometenkeiclear1st30_init()
end
function main18_nidometenkeiclear1st30_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  MAP:ChangeLightColor(Color(0.6, 0.6, 0.6, 1), TimeSec(0))
  CUT:Load(SymCut("m18_110_30"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  MAP:ReturnLightColor(TimeSec(0, TIME_TYPE.FRAME))
end
function main18_nidometenkeiclear1st30_cut_script_02()
  SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(256))
  TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  SOUND:PlayEnv(SymSnd("SE_EVT_KONOHANA_AURA_02_LP"), Volume(256))
end
function main18_nidometenkeiclear1st30_cut_script_01()
  MAP:ChangeLightColor(Color(0, 0, 0, 1), TimeSec(180, TIME_TYPE.FRAME))
end
function main18_nidometenkeiclear1st30_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -932029171, PARTNER_1 = 184895914})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SOUND:FadeOutEnv(TimeSec(1.5))
end
function main18_nidometenkeiclear1st30_end()
end
function main18_nidometenkeiclear1st31_init()
end
function main18_nidometenkeiclear1st31_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DARKMATTER_03"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("OOBEMU"):SetVisible(false)
  CH("OOBEMU2"):SetVisible(false)
  CH("OOBEMU3"):SetVisible(false)
  CH("DEDENNE"):SetManpu("EV_ELECTRIC_TEL_LP")
  SOUND:VolumeBgm(Volume(190), TimeSec(0.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("DEDENNE"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_NOTICE_R")
  CH("DEDENNE"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_QUESTION")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), 303986923)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("BUIZERU"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_NOTICE_R")
  CH("BUIZERU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BUIZERU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUIZERU"), 959654696)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("KUCHIITO"):SetManpu("MP_NOTICE_R")
  CH("KUCHIITO"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):SetManpu("MP_NOTICE_R")
  CH("HORUBII"):DirTo(CH("DEDENNE"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DEDENNE"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), 539499113)
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir, {
    CH("BUIZERU"),
    SymPos("P00_BUIZERU"),
    Speed(1.5),
    CH("DEDENNE")
  })
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 20, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), 1869188270)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir, {
    CH("KUCHIITO"),
    SymPos("P00_KUCHIITO"),
    Speed(1.5),
    CH("DEDENNE")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("HORUBII"),
    SymPos("P00_HORUBII"),
    Speed(2),
    CH("DEDENNE")
  })
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), 1987231215)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("KUCHIITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KUCHIITO"), 1566567980)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("HORUBII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("HORUBII"), 1145364333)
  subEveCloseMsg()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("DEDENNE"):SetManpu("MP_NOTICE_L")
    CH("KUCHIITO"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("BUIZERU"):SetManpu("MP_NOTICE_R")
    CH("HORUBII"):SetManpu("MP_EXCLAMATION")
    CH("HORUBII"):WaitManpu()
    CH("DEDENNE"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("KUCHIITO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("BUIZERU"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HORUBII"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  CH("OOBEMU"):SetVisible(true)
  CH("OOBEMU2"):SetVisible(true)
  CH("OOBEMU3"):SetVisible(true)
  SOUND:PlaySe(SymSnd("SE_EVT_OOBEMU_SPEAK"))
  WINDOW:SysMsg(-1008942174)
  TASK:Sleep(TimeSec(2))
  TASK:WaitTask()
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_QUESTION")
  CH("DEDENNE"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DEDENNE"), -624430365)
  WINDOW:Talk(SymAct("DEDENNE"), -1279709489)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("OOBEMU"):DirTo(CH("OOBEMU2"), Speed(350), ROT_TYPE.NEAR)
  CH("OOBEMU2"):DirTo(CH("OOBEMU3"), Speed(350), ROT_TYPE.NEAR)
  CH("OOBEMU3"):DirTo(CH("OOBEMU2"), Speed(350), ROT_TYPE.NEAR)
  CH("OOBEMU2"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU"):SetMotion(SymMot("EV100_TALK"), LOOP.ON)
  CH("OOBEMU2"):SetMotion(SymMot("EV100_TALK"), LOOP.ON)
  CH("OOBEMU3"):SetMotion(SymMot("EV100_TALK"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_OOBEMU_SPEAK"))
  WINDOW:SysMsg(-1432215666)
  SOUND:WaitSe(SymSnd("SE_EVT_OOBEMU_SPEAK"))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main18_nidometenkeiclear1st31_end()
end
function main18_nidometenkeiclear1st31_5_init()
end
function main18_nidometenkeiclear1st31_5_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m18_110_31_5"))
  SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutBgm(TimeSec(2.5))
  SOUND:FadeOutSe(SymSnd("SE_EVT_KONOHANA_AURA_02_LP"), TimeSec(2.5))
  TASK:Sleep(TimeSec(0.5))
  TASK:Sleep(TimeSec(1))
  TASK:Sleep(TimeSec(1))
end
function main18_nidometenkeiclear1st31_5_cut_01()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOHANA_AURA_01"), Volume(256))
  TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA_CHOKUGEKI"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_KONOHANA_AURA_02_LP"), Volume(256))
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
end
function main18_nidometenkeiclear1st31_5_end()
end
function main18_nidometenkeiclear1st32_init()
end
function main18_nidometenkeiclear1st32_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  MAP:SetVisibleMaterial("light0", false)
  MAP:SetVisibleMaterial("pyramid0", false)
  GM("STONE_PIKACHUU"):SetScale(Scale(1.1))
  GM("STONE_POKABU"):SetScale(Scale(1.1))
  GM("STONE_MIJUMARU"):SetScale(Scale(1.1))
  GM("STONE_TSUTAAJA"):SetScale(Scale(1.1))
  GM("STONE_FUSHIGIDANE"):SetScale(Scale(1.1))
  GM("STONE_HITOKAGE"):SetScale(Scale(1.1))
  GM("STONE_ZENIGAME"):SetScale(Scale(1.1))
  GM("STONE_CHIKORIITA"):SetScale(Scale(1.1))
  GM("STONE_HINOARASHI"):SetScale(Scale(1.1))
  GM("STONE_WANINOKO"):SetScale(Scale(1.1))
  GM("STONE_KIMORI"):SetScale(Scale(1.1))
  GM("STONE_ACHAMO"):SetScale(Scale(1.1))
  GM("STONE_MIZUGOROU"):SetScale(Scale(1.1))
  GM("STONE_NAETORU"):SetScale(Scale(1.1))
  GM("STONE_HIKOZARU"):SetScale(Scale(1.1))
  GM("STONE_POTCHAMA"):SetScale(Scale(1.1))
  GM("STONE_RIORU"):SetScale(Scale(1.1))
  GM("STONE_HARIMARON"):SetScale(Scale(1.1))
  GM("STONE_FOKKO"):SetScale(Scale(1.1))
  GM("STONE_KEROMATSU"):SetScale(Scale(1.1))
  GM("STONE_PIKACHUU_2"):SetScale(Scale(1.1))
  GM("STONE_POKABU_2"):SetScale(Scale(1.1))
  GM("STONE_MIJUMARU_2"):SetScale(Scale(1.1))
  GM("STONE_TSUTAAJA_2"):SetScale(Scale(1.1))
  GM("STONE_FUSHIGIDANE_2"):SetScale(Scale(1.1))
  GM("STONE_HITOKAGE_2"):SetScale(Scale(1.1))
  GM("STONE_ZENIGAME_2"):SetScale(Scale(1.1))
  GM("STONE_CHIKORIITA_2"):SetScale(Scale(1.1))
  GM("STONE_HINOARASHI_2"):SetScale(Scale(1.1))
  GM("STONE_WANINOKO_2"):SetScale(Scale(1.1))
  GM("STONE_KIMORI_2"):SetScale(Scale(1.1))
  GM("STONE_ACHAMO_2"):SetScale(Scale(1.1))
  GM("STONE_MIZUGOROU_2"):SetScale(Scale(1.1))
  GM("STONE_NAETORU_2"):SetScale(Scale(1.1))
  GM("STONE_HIKOZARU_2"):SetScale(Scale(1.1))
  GM("STONE_POTCHAMA_2"):SetScale(Scale(1.1))
  GM("STONE_RIORU_2"):SetScale(Scale(1.1))
  GM("STONE_HARIMARON_2"):SetScale(Scale(1.1))
  GM("STONE_FOKKO_2"):SetScale(Scale(1.1))
  GM("STONE_KEROMATSU_2"):SetScale(Scale(1.1))
  GM("STONE_PIKACHUU"):SetVisible(false)
  GM("STONE_POKABU"):SetVisible(false)
  GM("STONE_MIJUMARU"):SetVisible(false)
  GM("STONE_TSUTAAJA"):SetVisible(false)
  GM("STONE_FUSHIGIDANE"):SetVisible(false)
  GM("STONE_HITOKAGE"):SetVisible(false)
  GM("STONE_ZENIGAME"):SetVisible(false)
  GM("STONE_CHIKORIITA"):SetVisible(false)
  GM("STONE_HINOARASHI"):SetVisible(false)
  GM("STONE_WANINOKO"):SetVisible(false)
  GM("STONE_KIMORI"):SetVisible(false)
  GM("STONE_ACHAMO"):SetVisible(false)
  GM("STONE_MIZUGOROU"):SetVisible(false)
  GM("STONE_NAETORU"):SetVisible(false)
  GM("STONE_HIKOZARU"):SetVisible(false)
  GM("STONE_POTCHAMA"):SetVisible(false)
  GM("STONE_RIORU"):SetVisible(false)
  GM("STONE_HARIMARON"):SetVisible(false)
  GM("STONE_FOKKO"):SetVisible(false)
  GM("STONE_KEROMATSU"):SetVisible(false)
  GM("STONE_PIKACHUU_2"):SetVisible(false)
  GM("STONE_POKABU_2"):SetVisible(false)
  GM("STONE_MIJUMARU_2"):SetVisible(false)
  GM("STONE_TSUTAAJA_2"):SetVisible(false)
  GM("STONE_FUSHIGIDANE_2"):SetVisible(false)
  GM("STONE_HITOKAGE_2"):SetVisible(false)
  GM("STONE_ZENIGAME_2"):SetVisible(false)
  GM("STONE_CHIKORIITA_2"):SetVisible(false)
  GM("STONE_HINOARASHI_2"):SetVisible(false)
  GM("STONE_WANINOKO_2"):SetVisible(false)
  GM("STONE_KIMORI_2"):SetVisible(false)
  GM("STONE_ACHAMO_2"):SetVisible(false)
  GM("STONE_MIZUGOROU_2"):SetVisible(false)
  GM("STONE_NAETORU_2"):SetVisible(false)
  GM("STONE_HIKOZARU_2"):SetVisible(false)
  GM("STONE_POTCHAMA_2"):SetVisible(false)
  GM("STONE_RIORU_2"):SetVisible(false)
  GM("STONE_HARIMARON_2"):SetVisible(false)
  GM("STONE_FOKKO_2"):SetVisible(false)
  GM("STONE_KEROMATSU_2"):SetVisible(false)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 30 then
    GM("STONE_PIKACHUU"):SetVisible(true)
  elseif pokemonIndexHero == 595 then
    GM("STONE_POKABU"):SetVisible(true)
  elseif pokemonIndexHero == 598 then
    GM("STONE_MIJUMARU"):SetVisible(true)
  elseif pokemonIndexHero == 592 then
    GM("STONE_TSUTAAJA"):SetVisible(true)
  elseif pokemonIndexHero == 1 then
    GM("STONE_FUSHIGIDANE"):SetVisible(true)
  elseif pokemonIndexHero == 5 then
    GM("STONE_HITOKAGE"):SetVisible(true)
  elseif pokemonIndexHero == 10 then
    GM("STONE_ZENIGAME"):SetVisible(true)
  elseif pokemonIndexHero == 197 then
    GM("STONE_CHIKORIITA"):SetVisible(true)
  elseif pokemonIndexHero == 200 then
    GM("STONE_HINOARASHI"):SetVisible(true)
  elseif pokemonIndexHero == 203 then
    GM("STONE_WANINOKO"):SetVisible(true)
  elseif pokemonIndexHero == 322 then
    GM("STONE_KIMORI"):SetVisible(true)
  elseif pokemonIndexHero == 325 then
    GM("STONE_ACHAMO"):SetVisible(true)
  elseif pokemonIndexHero == 329 then
    GM("STONE_MIZUGOROU"):SetVisible(true)
  elseif pokemonIndexHero == 479 then
    GM("STONE_NAETORU"):SetVisible(true)
  elseif pokemonIndexHero == 482 then
    GM("STONE_HIKOZARU"):SetVisible(true)
  elseif pokemonIndexHero == 485 then
    GM("STONE_POTCHAMA"):SetVisible(true)
  elseif pokemonIndexHero == 537 then
    GM("STONE_RIORU"):SetVisible(true)
  elseif pokemonIndexHero == 766 then
    GM("STONE_HARIMARON"):SetVisible(true)
  elseif pokemonIndexHero == 769 then
    GM("STONE_FOKKO"):SetVisible(true)
  elseif pokemonIndexHero == 772 then
    GM("STONE_KEROMATSU"):SetVisible(true)
  end
  local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  if pokemonIndexPartner == 30 then
    GM("STONE_PIKACHUU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 595 then
    GM("STONE_POKABU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 598 then
    GM("STONE_MIJUMARU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 592 then
    GM("STONE_TSUTAAJA_2"):SetVisible(true)
  elseif pokemonIndexPartner == 1 then
    GM("STONE_FUSHIGIDANE_2"):SetVisible(true)
  elseif pokemonIndexPartner == 5 then
    GM("STONE_HITOKAGE_2"):SetVisible(true)
  elseif pokemonIndexPartner == 10 then
    GM("STONE_ZENIGAME_2"):SetVisible(true)
  elseif pokemonIndexPartner == 197 then
    GM("STONE_CHIKORIITA_2"):SetVisible(true)
  elseif pokemonIndexPartner == 200 then
    GM("STONE_HINOARASHI_2"):SetVisible(true)
  elseif pokemonIndexPartner == 203 then
    GM("STONE_WANINOKO_2"):SetVisible(true)
  elseif pokemonIndexPartner == 322 then
    GM("STONE_KIMORI_2"):SetVisible(true)
  elseif pokemonIndexPartner == 325 then
    GM("STONE_ACHAMO_2"):SetVisible(true)
  elseif pokemonIndexPartner == 329 then
    GM("STONE_MIZUGOROU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 479 then
    GM("STONE_NAETORU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 482 then
    GM("STONE_HIKOZARU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 485 then
    GM("STONE_POTCHAMA_2"):SetVisible(true)
  elseif pokemonIndexPartner == 537 then
    GM("STONE_RIORU_2"):SetVisible(true)
  elseif pokemonIndexPartner == 766 then
    GM("STONE_HARIMARON_2"):SetVisible(true)
  elseif pokemonIndexPartner == 769 then
    GM("STONE_FOKKO_2"):SetVisible(true)
  elseif pokemonIndexPartner == 772 then
    GM("STONE_KEROMATSU_2"):SetVisible(true)
  end
  CH("IBERUTARU"):SetMotion(SymMot("EV000_WAIT02"), LOOP.ON, TimeSec(0))
  local taskIberutaruFly00 = function()
    function TaskL.Loop()
      SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(32))
      TASK:Sleep(TimeSec(48, TIME_TYPE.FRAME))
    end
  end
  TASK:Regist(Group("grpIberutaru00"), taskIberutaruFly00)
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  subEveFadeAfterTime()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_01_5"))
  CAMERA:SetTgt(SymCam("CAMERA_01_5"))
  CAMERA:SetFovy(SymCam("CAMERA_01_5"))
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1.5))
  TASK:ExitNotifyTasks(Group("grpIberutaru00"))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  subEveFadeAfterTime()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CH("IBERUTARU"):SetMotion(SymMot("WAIT00"), LOOP.ON, TimeSec(0))
  CH("IBERUTARU"):SetMotion(SymMot("EV000_WAIT02"), LOOP.ON, TimeSec(0))
  local taskIberutaruFly02 = function()
    function TaskL.Loop()
      SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(92))
      TASK:Sleep(TimeSec(48, TIME_TYPE.FRAME))
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(Group("grpIberutaru02"), taskIberutaruFly02)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -2121315251)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1735099124)
  WINDOW:SysMsg(-673846325)
  WINDOW:SysMsg(-825304438)
  WINDOW:CloseMessage()
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 30 then
    GM("STONE_PIKACHUU"):SetVisible(false)
  elseif pokemonIndexHero == 595 then
    GM("STONE_POKABU"):SetVisible(false)
  elseif pokemonIndexHero == 598 then
    GM("STONE_MIJUMARU"):SetVisible(false)
  elseif pokemonIndexHero == 592 then
    GM("STONE_TSUTAAJA"):SetVisible(false)
  elseif pokemonIndexHero == 1 then
    GM("STONE_FUSHIGIDANE"):SetVisible(false)
  elseif pokemonIndexHero == 5 then
    GM("STONE_HITOKAGE"):SetVisible(false)
  elseif pokemonIndexHero == 10 then
    GM("STONE_ZENIGAME"):SetVisible(false)
  elseif pokemonIndexHero == 197 then
    GM("STONE_CHIKORIITA"):SetVisible(false)
  elseif pokemonIndexHero == 200 then
    GM("STONE_HINOARASHI"):SetVisible(false)
  elseif pokemonIndexHero == 203 then
    GM("STONE_WANINOKO"):SetVisible(false)
  elseif pokemonIndexHero == 322 then
    GM("STONE_KIMORI"):SetVisible(false)
  elseif pokemonIndexHero == 325 then
    GM("STONE_ACHAMO"):SetVisible(false)
  elseif pokemonIndexHero == 329 then
    GM("STONE_MIZUGOROU"):SetVisible(false)
  elseif pokemonIndexHero == 479 then
    GM("STONE_NAETORU"):SetVisible(false)
  elseif pokemonIndexHero == 482 then
    GM("STONE_HIKOZARU"):SetVisible(false)
  elseif pokemonIndexHero == 485 then
    GM("STONE_POTCHAMA"):SetVisible(false)
  elseif pokemonIndexHero == 537 then
    GM("STONE_RIORU"):SetVisible(false)
  elseif pokemonIndexHero == 766 then
    GM("STONE_HARIMARON"):SetVisible(false)
  elseif pokemonIndexHero == 769 then
    GM("STONE_FOKKO"):SetVisible(false)
  elseif pokemonIndexHero == 772 then
    GM("STONE_KEROMATSU"):SetVisible(false)
  end
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -438073015)
  WINDOW:Talk(SymAct("KONOHANA"), -50808824)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_05_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("IBERUTARU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0.3))
  CH("IBERUTARU"):WaitNeckRot()
  CAMERA:WaitMove()
  WINDOW:SysMsg(2069931207)
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("grpIberutaru02"))
  SOUND:FadeOutEnv(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main18_nidometenkeiclear1st32_end()
end
function main18_nidometenkeiclear1st33_init()
end
function main18_nidometenkeiclear1st33_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(1652266374)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function main18_nidometenkeiclear1st33_end()
end
function groundEnd()
end
