dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main25_darkmatter2boss01_init()
end
function main25_darkmatter2boss01_start()
  GM("EV255_DARK01"):SetMotion(SymMot("FINE_KEEP"), LOOP.ON)
  GM("DARKMATTER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  GM("DARKMATTER_TEST"):SetVisible(false)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetRotateZ(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetVisible(false)
  SOUND:FadeInBgm(SymSnd("BGM_EVE_UNIVERSE_01"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  EFFECT:Create("effectDarkHitStone", SymEff("EV_DARK_HIT_STONE"))
  EFFECT:SetPosition("effectDarkHitStone", SymPos("P_EFF_EV_DARK_HIT_STONE"))
  EFFECT:Play("effectDarkHitStone")
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER01_BREAK"))
  CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(2))
  SOUND:FadeInEnv(SymSnd("SE_EVT_DARKMATTER_LP"), TimeSec(0.5), Volume(128))
  CAMERA:SetRotateZ(Degree(0))
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1333477077, PARTNER_1 = 1449136020})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  local taskGuwawa00 = function()
    EFFECT:StartMotionBlur(0, 0, 0)
    EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0))
    EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0))
    TASK:Sleep(TimeSec(0.15))
    EFFECT:ChangeMotionBlurLevel(0, TimeSec(0.2))
    EFFECT:ChangeMotionBlurAlpha(1, TimeSec(0.2))
    TASK:Sleep(TimeSec(0.2))
    EFFECT:EndMotionBlur()
  end
  TASK:Regist(taskGuwawa00)
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_UMEKI"), Volume(190))
  WINDOW:SysMsg(2102221911)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetRotateZ(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(1683385622)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 722992081, PARTNER_1 = 839699088})
  WINDOW:SwitchTalk({PARTNER_0 = 421632339, PARTNER_1 = 3844114})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -2019380003, PARTNER_1 = -1632008804})
  WINDOW:CloseMessage()
  CAMERA:SetRotateZ(Degree(0))
  CH("DARKMATTER_02"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("HERO"):SetVisible(true)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("HERO"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_15"))
  CAMERA:SetTgt(SymCam("CAMERA_15"))
  CAMERA:SetFovy(SymCam("CAMERA_15"))
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(4))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Monologue(453845219)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  EFFECT:Remove("effectBgConLp")
  CH("DARKMATTER_02"):SetVisible(true)
  CH("HERO"):SetPosition(SymPos("P01_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  local taskHero00 = function()
    CH("HERO"):SetMotion(SymMot("EV018_ATTACK"), LOOP.OFF)
    CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(3))
    CH("HERO"):WaitMove()
    SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
    SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(0.1))
    SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
    TASK:Sleep(TimeSec(0.2))
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
    CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
    CH("HERO"):MoveTo(SymPos("P02_5_HERO"), Speed(4), LINK_DIR.OFF)
    CH("HERO"):WaitMove()
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.9))
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_UMEKI_02"), Volume(190))
  WINDOW:SysMsg(35000738)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:SysMsg(691749473)
  WINDOW:SysMsg(807432992)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("HERO"):SetPosition(SymPos("P03_HERO"))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetDir(RotateTarget(-170))
  CH("PARTNER"):SetVisible(true)
  CH("PARTNER"):SetDir(RotateTarget(180))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 2137122279, PARTNER_1 = 1719325862})
  WINDOW:SwitchTalk({PARTNER_0 = 1297581925, PARTNER_1 = 1414313508})
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  SOUND:FadeOutBgm(TimeSec(1.5))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(2))
  TASK:Sleep(TimeSec(0.3))
  local taskHoshikieru00 = function()
    GM("EV255_DARK01"):SetMotion(SymMot("DIE_START"), LOOP.OFF)
    GM("EV255_DARK01"):WaitPlayMotion()
    GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  end
  TASK:Regist(Group("grpHoshi"), taskHoshikieru00)
  TASK:Sleep(TimeSec(2, TIME_TYPE.FRAME))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(2))
  SOUND:PlaySe(SymSnd("SE_EVT_SEIMEINOKI_KARERU"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  CAMERA:SetRotateZ(SymCam("CAMERA_09"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(190))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.2))
  local taskHero01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(RotateTarget(135), Speed(200), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("HERO"), Speed(400))
  end
  local taskPartner00 = function()
    CH("PARTNER"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    subEveLookAround(CH("PARTNER"), Speed(400))
  end
  TASK:Regist(Group("grpHero"), taskHero01)
  TASK:Regist(Group("grpPartner"), taskPartner00)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -741037333, PARTNER_1 = -892363862})
  TASK:Sleep(TimeSec(0.5))
  TASK:Sleep(TimeSec(3))
  WINDOW:ForceCloseMessage()
  GM("DARKMATTER"):SetVisible(false)
  GM("DARKMATTER_TEST"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_09_1"))
  CAMERA:SetTgt(SymCam("CAMERA_09_1"))
  CAMERA:SetFovy(SymCam("CAMERA_09_1"))
  CAMERA:SetRotateZ(SymCam("CAMERA_09_1"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 163090189, PARTNER_1 = 279166540})
  TASK:Sleep(TimeSec(3))
  WINDOW:CloseMessage()
  GM("DARKMATTER"):SetVisible(true)
  GM("DARKMATTER_TEST"):SetVisible(false)
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(999222671)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(3.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  CAMERA:MoveFollow(SymCam("CAMERA_11_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(580246734)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1842629129, PARTNER_1 = 1959754568})
  subEveCloseMsg()
  WINDOW:SysMsg(1608657035)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1190730186)
  WINDOW:SysMsg(-1050606331)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CAMERA:SetFovy(SymCam("CAMERA_13"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-663079868)
  WINDOW:CloseMessage()
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(256))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  CAMERA:SetFovy(SymCam("CAMERA_14"))
  CAMERA:MoveFollow2(SymCam("CAMERA_14_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1325078424)
  WINDOW:SysMsg(-1474307799)
  WINDOW:SysMsg(-2093839638)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main25_darkmatter2boss01_end()
end
function main25_darkmatter2boss02_init()
end
function main25_darkmatter2boss02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(256))
  local taskSe00 = function()
    TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SAISEI_01"), Volume(190))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SAISEI_02_LP"), Volume(190))
  end
  TASK:Regist(taskSe00)
  local taskSe10 = function()
    TASK:Sleep(TimeSec(400, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SAISEI_03"), Volume(256))
  end
  TASK:Regist(taskSe10)
  CUT:Load(SymCut("m25_090_02"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss02_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1708541013, PARTNER_1 = -714592916})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss02_cut_talk_02()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  WINDOW:Monologue(-864871379)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SOUND:FadeOutEnv(TimeSec(2))
end
function main25_darkmatter2boss02_cut_talk_03()
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_CRY_TAKE04"), Volume(190))
  WINDOW:SetWaitMode(TimeSec(3), TimeSec(1))
  WINDOW:SysMsg(-413249554)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss02_cut_talk_04()
  SOUND:FadeInEnv(SymSnd("SE_EVT_HERO_LIGHT_LP"), TimeSec(0.5), Volume(256))
  CH("HERO"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(90, TIME_TYPE.FRAME))
  CH("PARTNER"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(90, TIME_TYPE.FRAME))
  WINDOW:SetWaitMode(TimeSec(1), TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = -29000017, PARTNER_1 = 2044551776})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss02_end()
end
function main25_darkmatter2boss02_5_init()
end
function main25_darkmatter2boss02_5_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  GM("DARKMATTER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("HERO"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(1, TIME_TYPE.FRAME))
  CH("PARTNER"):ChangeAddColor(Color(1, 1, 1, 1), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:Create("effectMatterWaveLp", SymEff("EV_MATER_WAVE_LP"))
  EFFECT:SetPosition("effectMatterWaveLp", SymPos("P_EFF_EV_MATER_WAVE_LP"))
  EFFECT:Play("effectMatterWaveLp")
  EFFECT:Create("effectShinkaRetrunLongEnd", SymEff("EV_SHINKARETURN_LONG_END"))
  EFFECT:SetPosition("effectShinkaRetrunLongEnd", SymPos("P_EFF_EV_SHINKARETURN_END"))
  EFFECT:Play("effectShinkaRetrunLongEnd")
  EFFECT:Create("effectShinkaRetrunLongEnd02", SymEff("EV_SHINKARETURN_LONG_END"))
  EFFECT:SetPosition("effectShinkaRetrunLongEnd02", SymPos("P_EFF_EV_SHINKARETURN_END_02"))
  EFFECT:Play("effectShinkaRetrunLongEnd02")
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  CH("HERO"):ChangeAddColor(Color(0, 0, 0, 1), TimeSec(30, TIME_TYPE.FRAME))
  CH("PARTNER"):ChangeAddColor(Color(0, 0, 0, 1), TimeSec(30, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(1))
  EFFECT:Remove("effectShinkaRetrunEnd")
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = 1623610145, PARTNER_1 = 752079057})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = 902357392, PARTNER_1 = 518369875})
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:Remove("effectShinkaRetrunLongEnd")
  EFFECT:Remove("effectShinkaRetrunLongEnd02")
  EFFECT:EndMotionBlur()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss02_5_end()
end
function main25_darkmatter2boss03_init()
end
function main25_darkmatter2boss03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_03"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  local taskSound00 = function()
    TASK:Sleep(TimeSec(210, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_COUNTER"), Volume(256))
  end
  TASK:Regist(taskSound00)
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss03_cut_talk_01()
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_CRY_TAKE04"), Volume(190))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SysMsg(134120210)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss03_cut_talk_02()
end
function main25_darkmatter2boss03_end()
end
function main25_darkmatter2boss05_init()
end
function main25_darkmatter2boss05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_05"))
  CHARA:SetAllCharacterShadowVisible(false)
  local taskSound00 = function()
    TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(256))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
  end
  TASK:Regist(taskSound00)
  local taskSound01 = function()
    TASK:Sleep(TimeSec(250, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(256))
    TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
  end
  TASK:Regist(taskSound01)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss05_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("DEOKISHISU_N"), 1220482517)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss05_cut_talk_02()
end
function main25_darkmatter2boss05_end()
end
function main25_darkmatter2boss06_init()
end
function main25_darkmatter2boss06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_06"))
  CHARA:SetAllCharacterShadowVisible(false)
  local taskSound00 = function()
    TASK:Sleep(TimeSec(65, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(256))
    TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
  end
  TASK:Regist(taskSound00)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss06_end()
end
function main25_darkmatter2boss07_init()
end
function main25_darkmatter2boss07_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CH("SEREBII"):SetShadow(false)
  CH("JIRAACHI"):SetShadow(false)
  CUT:Load(SymCut("m25_090_07"))
  local taskSound00 = function()
    TASK:Sleep(TimeSec(35, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  end
  TASK:Regist(taskSound00)
  local taskSound01 = function()
    TASK:Sleep(TimeSec(130, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
  end
  TASK:Regist(taskSound01)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss07_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Talk(SymAct("JIRAACHI"), 1369711764)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss07_end()
end
function main25_darkmatter2boss08_init()
end
function main25_darkmatter2boss08_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetNearFar(0.1, 10000)
  GM("EV01_EARTH"):SetScale(Scale(5))
  GM("EV01_SUN"):SetScale(Scale(15))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(30, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  GM("EV01_EARTH"):MoveTo(SymPos("P00_EARTH"), Speed(30))
  EFFECT:StartMotionBlur(0.04, 0.5, 0)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_CRY_TAKE04"), Volume(190))
  WINDOW:SysMsg(2055829335)
  TASK:Sleep(TimeSec(120, TIME_TYPE.FRAME))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:EndMotionBlur()
  CAMERA:ResetDefaultNearFar()
end
function main25_darkmatter2boss08_end()
end
function main25_darkmatter2boss09_init()
end
function main25_darkmatter2boss09_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_09"))
  CHARA:SetAllCharacterShadowVisible(false)
  local taskSound00 = function()
    TASK:Sleep(TimeSec(25, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(256))
  end
  TASK:Regist(taskSound00)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss09_end()
end
function main25_darkmatter2boss10_init()
end
function main25_darkmatter2boss10_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_10"))
  local taskSound00 = function()
    TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(256))
  end
  TASK:Regist(taskSound00)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss10_end()
end
function main25_darkmatter2boss11_init()
end
function main25_darkmatter2boss11_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KYUUCHI"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  GM("DARKMATTER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  GM("DARKMATTER"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CHARA:SetAllCharacterShadowVisible(false)
  EFFECT:Create("effectMatterWaveLp", SymEff("EV_MATER_WAVE_LP"))
  EFFECT:SetPosition("effectMatterWaveLp", SymPos("P_EFF_EV_MATER_WAVE_LP"))
  EFFECT:Play("effectMatterWaveLp")
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_CRY_TAKE04"), Volume(190))
  WINDOW:SysMsg(1670530582)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CAMERA:SetFovy(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:MoveFollow(SymCam("CAMERA_01_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(60, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectMatterWaveLp", Color(0, 0, 0, 0), TimeSec(60, TIME_TYPE.FRAME))
  GM("DARKMATTER"):ChangeColor(Color(1, 1, 1, 1), TimeSec(60, TIME_TYPE.FRAME))
  EFFECT:ChangeMotionBlurLevel(0, TimeSec(0.2))
  EFFECT:ChangeMotionBlurAlpha(1, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  EFFECT:EndMotionBlur()
  SOUND:FadeOutBgm(TimeSec(2.5))
  TASK:Sleep(TimeSec(2.5))
  EFFECT:Remove("effectMatterWaveLp")
  SOUND:FadeInEnv(SymSnd("BGM_EVE_UNIVERSE_05"), TimeSec(0.5), Volume(256))
  TASK:Sleep(TimeSec(1.3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HERO"):SetMotion(SymMot("EV021_DEPRESS01"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("EV021_DEPRESS01"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = -469083431, PARTNER_1 = -49189992})
  WINDOW:SwitchTalk({PARTNER_0 = -1804617804, PARTNER_1 = -1921743115})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  WINDOW:Monologue(-1504062154)
  WINDOW:CloseMessage()
  CH("DARKMATTER_03"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1086135177)
  WINDOW:SysMsg(-268209488)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-384285711)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04"))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", SymPos("P_EFF_BG_CONCENTRATION_LP"))
  EFFECT:Play("effectBgConLp")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1036709838, PARTNER_1 = -617733773})
  WINDOW:CloseMessage()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1555447228)
  WINDOW:CloseMessage()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("DARKMATTER_03"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  WINDOW:Monologue(1168968957)
  WINDOW:CloseMessage()
  CH("DARKMATTER_03"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-2032527270)
  WINDOW:SysMsg(-1614730981)
  WINDOW:SysMsg(-1259570472)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1376302183)
  WINDOW:SysMsg(-491332258)
  WINDOW:SysMsg(-72487905)
  WINDOW:SysMsg(-796868644)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  CAMERA:MoveFollow2(SymCam("CAMERA_09_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.1))
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):SetManpu("MP_EXCLAMATION")
  end
  TASK:Regist(taskLookAt00)
  WINDOW:Explanation(-912552291)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss11_end()
end
function main25_darkmatter2boss12_init()
end
function main25_darkmatter2boss12_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_12"))
  CHARA:SetAllCharacterShadowVisible(false)
  local taskIberutaruSe00 = function()
    SOUND:PlayBgm(SymSnd("BGM_EVE_YOWAKUTEMO_AGAKU"), Volume(256))
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_APPEAR_01_LP"), Volume(190))
    SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(190))
    TASK:Sleep(TimeSec(60, TIME_TYPE.FRAME))
    SOUND:FadeOutSe(SymSnd("SE_EVT_IBERUTARU_APPEAR_01_LP"), TimeSec(1.5))
    SOUND:FadeOutEnv(TimeSec(1.5))
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_APPEAR_02"), Volume(190))
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_HABATAKI"), Volume(190))
    TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_BEAM"), Volume(256))
  end
  TASK:Regist(taskIberutaruSe00)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss12_cut_talk_01()
  WINDOW:SetWaitMode(TimeSec(0.5), TimeSec(1))
  WINDOW:SysMsg(1308856914)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss12_cut_talk_02()
  local taskSe00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
    TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  end
  TASK:Regist(taskSe00)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1461232403, PARTNER_1 = 1046904639})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss12_cut_talk_03()
  SOUND:PlaySe(SymSnd("SE_EVT_GIRATYINA_DEATHCRY"), Volume(256))
  TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:SysMsg(662523518)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss12_end()
end
function main25_darkmatter2boss13_init()
end
function main25_darkmatter2boss13_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_YOWAKUTEMO_AGAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_13"))
  CHARA:SetAllCharacterShadowVisible(false)
  local taskSe00 = function()
    TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_BEAM_02_LP"), Volume(128))
  end
  TASK:Regist(taskSe00)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss13_cut_talk_01()
  local taskSeKonohana00 = function()
    TASK:Sleep(TimeSec(40, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(190))
    TASK:Sleep(TimeSec(40, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  end
  TASK:Regist(taskSeKonohana00)
  WINDOW:Talk(SymAct("KONOHANA"), 206577085)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
end
function main25_darkmatter2boss13_cut_script_01()
  SOUND:PlaySe(SymSnd("SE_EVT_FLASH_OUT"), Volume(256))
  TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_EXPLODE_CHARGE"), Volume(256))
end
function main25_darkmatter2boss13_cut_talk_02()
  local taskSeSoukougeki = function()
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARUGUMI_LP"), Volume(128))
  end
  TASK:Regist(taskSeSoukougeki)
  WINDOW:Talk(SymAct("OOBEMU"), 357248252)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
end
function main25_darkmatter2boss13_end()
end
function main25_darkmatter2boss13_5_init()
end
function main25_darkmatter2boss13_5_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_YOWAKUTEMO_AGAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  GM("DARKMATTER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetRotateZ(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("IBERUTARU"):SetMotion(SymMot("EV025_ATTACK"), LOOP.ON)
  CH("KONOHANA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("KONOHANA"):SetVisible(false)
  EFFECT:Create("effectObWazahitMultiLp03", SymEff("EV_OOBEMU_WAZAHIT_MULTI_LP"))
  EFFECT:SetPosition("effectObWazahitMultiLp03", SymPos("P_EFF_EV_DARK_HIT_STONE_03"))
  EFFECT:Play("effectObWazahitMultiLp03")
  EFFECT:SetDir("effectObWazahitMultiLp03", RotateTarget(130))
  EFFECT:Create("effectObWazahitMultiLp04", SymEff("EV_OOBEMU_WAZAHIT_MULTI_LP"))
  EFFECT:SetPosition("effectObWazahitMultiLp04", SymPos("P_EFF_EV_DARK_HIT_STONE_04"))
  EFFECT:Play("effectObWazahitMultiLp04")
  EFFECT:SetDir("effectObWazahitMultiLp04", RotateTarget(135))
  local taskOobemu01 = function()
    EFFECT:Create("effectObWazahitMultiLp01", SymEff("EV_OOBEMU_WAZAHIT_MULTI_LP"))
    EFFECT:SetPosition("effectObWazahitMultiLp01", SymPos("P_EFF_EV_DARK_HIT_STONE_01"))
    EFFECT:Play("effectObWazahitMultiLp01")
    EFFECT:SetDir("effectObWazahitMultiLp01", RotateTarget(115))
    EFFECT:ChangeColor("effectObWazahitMultiLp01", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
    CH("OOBEMU"):SetMotionRaito(Raito(2))
    CH("OOBEMU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  end
  TASK:Regist(taskOobemu01)
  local taskOobemu02 = function()
    EFFECT:Create("effectObWazahitMultiLp02", SymEff("EV_OOBEMU_WAZAHIT_MULTI_LP"))
    EFFECT:SetPosition("effectObWazahitMultiLp02", SymPos("P_EFF_EV_DARK_HIT_STONE_02"))
    EFFECT:Play("effectObWazahitMultiLp02")
    EFFECT:SetDir("effectObWazahitMultiLp02", RotateTarget(95))
    EFFECT:ChangeColor("effectObWazahitMultiLp02", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
    CH("OOBEMU2"):SetMotionRaito(Raito(2))
    CH("OOBEMU2"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  end
  TASK:Regist(taskOobemu02)
  EFFECT:Create("effectDeathWingLp", SymEff("EV_DEATHWING_REV_LP"))
  EFFECT:SetPosition("effectDeathWingLp", SymPos("P_EFF_EV_DEATHWING_LP"))
  EFFECT:SetScale("effectDeathWingLp", Scale(0.5, 0.5))
  EFFECT:SetDir("effectDeathWingLp", RotateTarget(52))
  EFFECT:Play("effectDeathWingLp")
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", SymPos("P_EFF_BG_CONCENTRATION_LP"))
  EFFECT:Play("effectBgConLp")
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  WINDOW:SwitchTalk({PARTNER_0 = 1510652475, PARTNER_1 = 1125223290})
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  SOUND:FadeOutSe(SymSnd("SE_EVT_IBERUTARUGUMI_LP"), TimeSec(10, TIME_TYPE.FRAME))
  CH("KONOHANA"):SetVisible(true)
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetRotateZ(SymCam("CAMERA_01"))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("KONOHANA"):SetMotion(SymMot("EV025_TIRED00"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KONOHANA"), 1748818105)
  WINDOW:Talk(SymAct("KONOHANA"), 1898441208)
  WINDOW:CloseMessage()
  GM("DARKMATTER"):SetPosition(SymPos("P00_GM_DARKMATTER"))
  GM("DARKMATTER"):SetScale(Scale(1.5))
  CH("DARKMATTER_03"):SetPosition(SymPos("P00_DARKMATTER03"))
  CH("DARKMATTER_03"):SetScale(Scale(1.8))
  EFFECT:ChangeColor("effectObWazahitMultiLp01", Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectObWazahitMultiLp02", Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectObWazahitMultiLp03", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  EFFECT:ChangeColor("effectObWazahitMultiLp04", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  EFFECT:SetPosition("effectDeathWingLp", SymPos("P_EFF_EV_DEATHWING_LP_04"))
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  CAMERA:SetFovy(SymCam("CAMERA_02_5"))
  local taskKonohana00 = function()
    CH("KONOHANA"):RunTo(SymPos("P00_KONOHANA"), Speed(3))
    CH("KONOHANA"):WaitMove()
    function TaskL.Loop()
      CH("KONOHANA"):SetMotion(SymMot("EV025_ATTACK"), LOOP.OFF)
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("KONOHANA"):SetManpu("EV_KONOHANA_HIT")
      SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
      CH("KONOHANA"):WaitPlayMotion()
      CH("KONOHANA"):SetMotion(SymMot("BATTLE"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(Group("grpKonohana"), taskKonohana00)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KONOHANA"), -155192009)
  WINDOW:CloseMessage()
  EFFECT:SetPosition("effectDeathWingLp", SymPos("P_EFF_EV_DEATHWING_LP"))
  EFFECT:StartMotionBlur(0.04, 0.5, 0)
  CH("DARKMATTER_03"):SetPosition(SymPos("P01_DARKMATTER03"))
  CH("DARKMATTER_03"):SetScale(Scale(1))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(0.5, TIME_TYPE.FRAME))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-274414474)
  WINDOW:SysMsg(1711632233)
  WINDOW:CloseMessage()
  EFFECT:Remove("effectDeathWingLp")
  EFFECT:Create("effectDeathwingBeamLp", SymEff("EV_DEATHWING_BEAM_LP"))
  EFFECT:SetPosition("effectDeathwingBeamLp", SymPos("P_EFF_EV_DEATHWING_LP_02"))
  EFFECT:SetScale("effectDeathwingBeamLp", Scale(0.25, 0.25))
  EFFECT:Play("effectDeathwingBeamLp")
  EFFECT:SetDir("effectDeathwingBeamLp", RotateTarget(52))
  EFFECT:Create("effectDeathwingImpactLp", SymEff("EV_DEATHWING_IMPACT_LP"))
  EFFECT:SetPosition("effectDeathwingImpactLp", SymPos("P_EFF_EV_DEATHWING_LP_03"))
  EFFECT:SetScale("effectDeathwingImpactLp", Scale(0.5, 0.5))
  EFFECT:SetDir("effectDeathwingImpactLp", RotateTarget(52))
  EFFECT:Play("effectDeathwingImpactLp")
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("IBERUTARU"), 2132696616)
  WINDOW:CloseMessage()
  EFFECT:Remove("effectDeathwingBeamLp")
  EFFECT:Remove("effectDeathwingImpactLp")
  EFFECT:Create("effectDeathWingLp02", SymEff("EV_DEATHWING_LP"))
  EFFECT:SetPosition("effectDeathWingLp02", SymPos("P_EFF_EV_DEATHWING_LP_02"))
  EFFECT:SetScale("effectDeathWingLp02", Scale(0.15, 0.15))
  EFFECT:SetDir("effectDeathWingLp02", RotateTarget(52))
  EFFECT:Play("effectDeathWingLp02")
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:SetRotateZ(SymCam("CAMERA_07"))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", SymPos("P_EFF_BG_CONCENTRATION_LP_02"))
  EFFECT:Play("effectBgConLp")
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("IBERUTARU"), 1412632043)
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("grpKonohana"))
  SOUND:FadeOutSe(SymSnd("SE_EVT_IBERUTARU_BEAM_02_LP"), TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:EndMotionBlur()
  EFFECT:Remove("effectDeathWingLp02")
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss13_5_end()
end
function main25_darkmatter2boss14_init()
end
function main25_darkmatter2boss14_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_YOWAKUTEMO_AGAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CUT:Load(SymCut("m25_090_14"))
  CHARA:SetAllCharacterShadowVisible(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
end
function main25_darkmatter2boss14_cut_talk_01()
  local taskSe00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_APPEAR_02"), Volume(190))
    TASK:Sleep(TimeSec(35, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_IBERUTARU_BEAM"), Volume(190))
    TASK:Sleep(TimeSec(45, TIME_TYPE.FRAME))
    SOUND:FadeOutSe(SymSnd("SE_EVT_IBERUTARU_BEAM"), TimeSec(0.5))
  end
  TASK:Regist(taskSe00)
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  WINDOW:SysMsg(1294482602)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss14_cut_script_01()
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_HONKI"), Volume(190))
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_CRY_TAKE04"), Volume(190))
end
function main25_darkmatter2boss14_cut_talk_02()
  local taskSe01 = function()
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_IMPACT"), Volume(190))
    TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_IMPACT"), Volume(190))
  end
  TASK:Regist(taskSe01)
  SOUND:FadeOutBgm(TimeSec(1))
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  WINDOW:SysMsg(40479341)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss14_cut_talk_03()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_04"), Volume(256))
  local taskSe01 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(190))
  end
  TASK:Regist(taskSe01)
  WINDOW:SetWaitMode(TimeSec(0.6), TimeSec(1))
  WINDOW:Talk(SymAct("IBERUTARU"), 460495660)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss14_cut_script_02()
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(190))
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(190))
end
function main25_darkmatter2boss14_cut_talk_04()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 811583727, PARTNER_1 = 692386222})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss14_cut_talk_05()
  local taskSe02 = function()
    TASK:Sleep(TimeSec(28, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_SEKIKA_ATTACK"), Volume(256))
    SOUND:PlaySe(SymSnd("SE_EVT_SEKIKA"), Volume(190))
  end
  TASK:Regist(taskSe02)
  WINDOW:SetWaitMode(TimeSec(0.7), TimeSec(0.3))
  WINDOW:Talk(SymAct("KONOHANA"), -1361255071)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss14_cut_talk_06()
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = -1211640800, PARTNER_1 = -558299124})
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main25_darkmatter2boss14_end()
end
function main25_darkmatter2boss15_init()
end
function main25_darkmatter2boss15_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  GM("EV01_EARTH"):SetScale(Scale(2))
  GM("EV01_SUN"):SetScale(Scale(11))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  GM("EV01_EARTH"):MoveTo(SymPos("P00_EARTH"), Speed(5))
  EFFECT:StartMotionBlur(0.04, 0.5, 0)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER_CRY_TAKE04"), Volume(190))
  WINDOW:SysMsg(-945669811)
  TASK:Sleep(TimeSec(3))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:EndMotionBlur()
end
function main25_darkmatter2boss15_end()
end
function main25_darkmatter2boss16_init()
end
function main25_darkmatter2boss16_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  EFFECT:Create("effectMatterWaveBeamLp", SymEff("EV_MATER_WAVE_BEAM_LP"))
  EFFECT:SetPosition("effectMatterWaveBeamLp", SymPos("P_EFF_EV_MATER_WAVE_BEAM_LP"))
  EFFECT:Play("effectMatterWaveBeamLp")
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -326145394, PARTNER_1 = -174826545})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(128))
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1160393464)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):ResetShake()
  WINDOW:SwitchTalk({PARTNER_0 = -1546716087, PARTNER_1 = -1998344310})
  WINDOW:SwitchTalk({PARTNER_0 = -1845977397, PARTNER_1 = 375423492})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(259765061)
  WINDOW:SysMsg(-794640410)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CH("HERO"):SetDir(RotateTarget(-170))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-910586201)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:EndMotionBlur()
  EFFECT:Remove("effectMatterWaveBeamLp")
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss16_end()
end
function main25_darkmatter2boss17_init()
end
function main25_darkmatter2boss17_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  GM("STONE_MYUUTSUU"):SetScale(Scale(1.4))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SysMsg(-493560476)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main25_darkmatter2boss17_end()
end
function main25_darkmatter2boss18_init()
end
function main25_darkmatter2boss18_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SysMsg(-74453979)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main25_darkmatter2boss18_end()
end
function main25_darkmatter2boss19_init()
end
function main25_darkmatter2boss19_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_04"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  EFFECT:Create("effectMatterWaveBeamLp", SymEff("EV_MATER_WAVE_BEAM_LP"))
  EFFECT:SetPosition("effectMatterWaveBeamLp", SymPos("P_EFF_EV_MATER_WAVE_BEAM_LP"))
  EFFECT:Play("effectMatterWaveBeamLp")
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SysMsg(-1261536542)
  WINDOW:SysMsg(-1378530397)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-2030561184)
  subEveCloseMsg()
  CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):ResetShake()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -1612502751, PARTNER_1 = 410727918})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(23069871)
  WINDOW:Monologue(1746851971)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(1896212930)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(1512618497)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:MoveFollow2(SymCam("CAMERA_04_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(1127451456)
  WINDOW:Monologue(208805255)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 359214278, PARTNER_1 = 1044676357})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(660557380)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = -1597549941, PARTNER_1 = -1176738870})
  WINDOW:SwitchTalk({PARTNER_0 = 2058057581, PARTNER_1 = 1672496684})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1218254319)
  WINDOW:CloseMessage()
  CH("HERO"):ResetFacialMotion()
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(1367745710)
  WINDOW:Monologue(516403817)
  WINDOW:Monologue(131892008)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectMatterWaveBeamLp")
  EFFECT:EndMotionBlur()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss19_end()
end
function main25_darkmatter2boss20_init()
end
function main25_darkmatter2boss20_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetRotateZ(SymCam("CAMERA_00"))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  EFFECT:Create("effectMatterWaveBeamLp", SymEff("EV_MATER_WAVE_BEAM_LP"))
  EFFECT:SetPosition("effectMatterWaveBeamLp", SymPos("P_EFF_EV_MATER_WAVE_BEAM_LP"))
  EFFECT:Play("effectMatterWaveBeamLp")
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  local taskHero00 = function()
    CH("HERO"):SetMotion(SymMot("EV018_LIES01"), LOOP.ON)
    CH("HERO"):MoveTo(SymPos("P00_HERO"), Speed(0.5))
    CH("HERO"):WaitMove()
    CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  end
  TASK:Regist(taskHero00)
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(2.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetRotateZ(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(754045163)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(2))
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(904585642)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1301086875)
  WINDOW:CloseMessage()
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-1419129820)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1038675960)
  WINDOW:CloseMessage()
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-619962039)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-266243446)
  WINDOW:CloseMessage()
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-382057525)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1501833972)
  WINDOW:CloseMessage()
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-1084169139)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1806846066)
  WINDOW:CloseMessage()
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-1923709233)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = 181312000, PARTNER_1 = 332770113})
  WINDOW:SwitchTalk({PARTNER_0 = 1606428849, PARTNER_1 = 1188764144})
  WINDOW:CloseMessage()
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.5))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(1844857395)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), 1961720690)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1001188789)
  WINDOW:CloseMessage()
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(582474996)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), 161124151)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(276938358)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), -1759927623)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  CH("HERO"):SetDir(RotateTarget(180))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 595 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 197 then
    CH("HERO"):MoveTo(SymPos("P01_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:SysMsg(-1912433672)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-411283500)
  WINDOW:SysMsg(-26771819)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:Remove("effectMatterWaveBeamLp")
  EFFECT:EndMotionBlur()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss20_end()
end
function main25_darkmatter2boss21_init()
end
function main25_darkmatter2boss21_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetRotateZ(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), -716559018)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main25_darkmatter2boss21_end()
end
function main25_darkmatter2boss22_init()
end
function main25_darkmatter2boss22_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  EFFECT:Create("effectMatterWaveBeamLp", SymEff("EV_MATER_WAVE_BEAM_LP"))
  EFFECT:SetPosition("effectMatterWaveBeamLp", SymPos("P_EFF_EV_MATER_WAVE_BEAM_LP"))
  EFFECT:Play("effectMatterWaveBeamLp")
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P00_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P00_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P00_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(32))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectMatterWaveBeamLp")
  EFFECT:EndMotionBlur()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss22_end()
end
function main25_darkmatter2boss23_init()
end
function main25_darkmatter2boss23_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), -867099625)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main25_darkmatter2boss23_end()
end
function main25_darkmatter2boss24_init()
end
function main25_darkmatter2boss24_start()
end
function main25_darkmatter2boss24_end()
end
function main25_darkmatter2boss25_init()
end
function main25_darkmatter2boss25_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  GM("STONE_MYUUTSUU"):SetScale(Scale(1.4))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), -2096067888)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main25_darkmatter2boss25_end()
end
function main25_darkmatter2boss26_init()
end
function main25_darkmatter2boss26_start()
end
function main25_darkmatter2boss26_end()
end
function main25_darkmatter2boss27_init()
end
function main25_darkmatter2boss27_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), -1710507119)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main25_darkmatter2boss27_end()
end
function main25_darkmatter2boss28_init()
end
function main25_darkmatter2boss28_start()
end
function main25_darkmatter2boss28_end()
end
function main25_darkmatter2boss29_init()
end
function main25_darkmatter2boss29_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  GM("STONE_ENTEI"):SetScale(Scale(1.5))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), -1322850222)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.5), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main25_darkmatter2boss29_end()
end
function main25_darkmatter2boss30_init()
end
function main25_darkmatter2boss30_start()
end
function main25_darkmatter2boss30_end()
end
function main25_darkmatter2boss31_init()
end
function main25_darkmatter2boss31_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetRotateZ(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), -1472341741)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  GM("STONE_KUCHIITO"):SetVisible(false)
  GM("STONE_HORUBII"):SetVisible(false)
  GM("STONE_BUIZERU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetRotateZ(SymCam("CAMERA_01"))
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(2))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), 799393244)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  GM("STONE_KUCHIITO"):SetVisible(true)
  GM("STONE_HORUBII"):SetVisible(true)
  GM("STONE_BUIZERU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetRotateZ(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  WINDOW:Narration(TimeSec(0.1), TimeSec(0.1), 918484125)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetRotateZ(Degree(0))
end
function main25_darkmatter2boss31_end()
end
function main25_darkmatter2boss32_init()
end
function main25_darkmatter2boss32_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  EFFECT:Create("effectMatterWaveBeamLp", SymEff("EV_MATER_WAVE_BEAM_LP"))
  EFFECT:SetPosition("effectMatterWaveBeamLp", SymPos("P_EFF_EV_MATER_WAVE_BEAM_LP"))
  EFFECT:Play("effectMatterWaveBeamLp")
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexHero = SymAct("HERO"):GetIndex()
  if pokemonIndexHero == 592 then
    CH("HERO"):MoveTo(SymPos("P00_5_HERO"), Speed(3))
  elseif pokemonIndexHero == 479 then
    CH("HERO"):MoveTo(SymPos("P00_5_HERO"), Speed(3))
  else
    CH("HERO"):MoveTo(SymPos("P00_HERO"), Speed(3))
  end
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(32))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):MoveTo(SymPos("P01_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("HERO"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = -171319238, PARTNER_1 = -321728133})
  WINDOW:SwitchTalk({PARTNER_0 = -939556168, PARTNER_1 = -555437063})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("PARTNER"):SetMotionRaito(Raito(0.7))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1851448002, PARTNER_1 = -2000808833})
  WINDOW:SwitchTalk({PARTNER_0 = -1550628932, PARTNER_1 = -1165461763})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(1024485938)
  WINDOW:Monologue(604724083)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:MoveFollow2(SymCam("CAMERA_04_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(1299547999)
  WINDOW:Monologue(1416541726)
  WINDOW:Monologue(2135156189)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  EFFECT:Remove("effectMatterWaveBeamLp")
  EFFECT:EndMotionBlur()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
end
function main25_darkmatter2boss32_end()
end
function main25_darkmatter2boss33_init()
end
function main25_darkmatter2boss33_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("NEITYIO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SHINBORAA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NEITYI"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("SABONEA"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("NOKUTASU"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("AABO"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1717097628)
  TASK:Sleep(TimeSec(3))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.5), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main25_darkmatter2boss33_end()
end
function main25_darkmatter2boss34_init()
end
function main25_darkmatter2boss34_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 689521243)
  TASK:Sleep(TimeSec(3))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.5), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main25_darkmatter2boss34_end()
end
function main25_darkmatter2boss35_init()
end
function main25_darkmatter2boss35_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("JUGON"):SetMotionRaito(Raito(0.8))
  CH("JUGON"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("RANTAAN"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("RANTAAN2"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CH("RANTAAN3"):SetNeckRot(RotateTarget(0), RotateTarget(30), RotateTarget(0), TimeSec(0))
  CAMERA:MoveFollow(SymCam("CAMERA_00_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0), false)
  SCREEN_A:FadeChange(Level(1), Level(0.6), TimeSec(0.3), true)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 805466906)
  TASK:Sleep(TimeSec(3))
  WINDOW:ForceCloseMessage()
  CH("JUGON"):SetHeight(Height(55.8844))
  CH("RANTAAN"):SetHeight(Height(55.3828))
  CH("RANTAAN2"):SetHeight(Height(55.3638))
  CH("RANTAAN3"):SetHeight(Height(55.724))
  CH("JUGON"):SetPosition(SymPos("P00_JUGON"))
  CH("RANTAAN"):SetPosition(SymPos("P00_RANTAAN"))
  CH("RANTAAN2"):SetPosition(SymPos("P00_RANTAAN2"))
  CH("RANTAAN3"):SetPosition(SymPos("P00_RANTAAN3"))
  CH("JUGON"):SetDir(RotateTarget(180))
  CH("RANTAAN"):SetDir(RotateTarget(180))
  CH("RANTAAN2"):SetDir(RotateTarget(180))
  CH("RANTAAN3"):SetDir(RotateTarget(180))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  WINDOW:Narration(TimeSec(0.2), TimeSec(0.2), 456073433)
  TASK:Sleep(TimeSec(3))
  WINDOW:ForceCloseMessage()
  SCREEN_A:FadeChange(Level(0.6), Level(1), TimeSec(0.5), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
end
function main25_darkmatter2boss35_end()
end
function main25_darkmatter2boss36_init()
end
function main25_darkmatter2boss36_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_AKIRAMERUNA"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  GM("EV255_DARK01"):SetMotion(SymMot("DIE_KEEP"), LOOP.ON)
  GM("DARKMATTER"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CHARA:SetAllCharacterShadowVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  EFFECT:Create("effectMatterWaveBeamLp", SymEff("EV_MATER_WAVE_BEAM_LP"))
  EFFECT:SetPosition("effectMatterWaveBeamLp", SymPos("P_EFF_EV_MATER_WAVE_BEAM_LP"))
  EFFECT:Play("effectMatterWaveBeamLp")
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(36966808)
  WINDOW:Monologue(-2052321961)
  WINDOW:CloseMessage()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("HERO"):SetVisible(false)
  EFFECT:EndMotionBlur()
  EFFECT:ChangeColor("effectMatterWaveBeamLp", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", SymPos("P_EFF_BG_CONCENTRATION_LP"))
  EFFECT:Play("effectBgConLp")
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(4))
  TASK:Sleep(TimeSec(1))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  EFFECT:Remove("effectBgConLp")
  EFFECT:ChangeColor("effectMatterWaveBeamLp", Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
  CH("HERO"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("PARTNER"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  if pokemonIndexPartner == 592 then
    CH("PARTNER"):MoveTo(SymPos("P00_5_PARTNER"), Speed(3))
  elseif pokemonIndexPartner == 479 then
    CH("PARTNER"):MoveTo(SymPos("P00_5_PARTNER"), Speed(3))
  else
    CH("PARTNER"):MoveTo(SymPos("P00_PARTNER"), Speed(3))
  end
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("PARTNER"):MoveTo(SymPos("P01_PARTNER"), Speed(2.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("DARKMATTER_03"):SetVisible(false)
  EFFECT:ChangeColor("effectMatterWaveBeamLp", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetRotateZ(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1665713130, PARTNER_1 = 353801993})
  WINDOW:CloseMessage()
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.03, TimeSec(0))
  EFFECT:ChangeMotionBlurAlpha(0.3, TimeSec(0))
  CH("HERO"):SetVisible(true)
  CH("DARKMATTER_03"):SetVisible(true)
  EFFECT:ChangeColor("effectMatterWaveBeamLp", Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
  CH("HERO"):SetPosition(SymPos("P02_HERO"))
  CH("HERO"):SetDir(RotateTarget(-150))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetRotateZ(SymCam("CAMERA_04"))
  CH("HERO"):SetNeckRot(RotateTarget(30), RotateTarget(0), RotateTarget(0), TimeSec(0.3))
  CH("HERO"):WaitNeckRot()
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(202221128)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetNeckRot(RotateTarget(-30), RotateTarget(0), RotateTarget(0), TimeSec(0.15))
  CH("PARTNER"):WaitNeckRot()
  CH("PARTNER"):SetNeckRot(RotateTarget(-30), RotateTarget(-30), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  CH("PARTNER"):SetNeckRot(RotateTarget(-30), RotateTarget(0), RotateTarget(0), TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  CH("PARTNER"):ResetNeckRot(TimeSec(0.15))
  CH("PARTNER"):WaitNeckRot()
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):ResetNeckRot(TimeSec(0.15))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.15))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  local taskHero00 = function()
    CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
    local pokemonIndexHero = SymAct("HERO"):GetIndex()
    if pokemonIndexHero == 592 then
      CH("HERO"):MoveTo(SymPos("P03_5_HERO"), Speed(3))
    elseif pokemonIndexHero == 1 then
      CH("HERO"):MoveTo(SymPos("P03_5_HERO"), Speed(3))
    elseif pokemonIndexHero == 479 then
      CH("HERO"):MoveTo(SymPos("P03_5_HERO"), Speed(3))
    elseif pokemonIndexHero == 595 then
      CH("HERO"):MoveTo(SymPos("P03_5_HERO"), Speed(3))
    elseif pokemonIndexHero == 197 then
      CH("HERO"):MoveTo(SymPos("P03_5_HERO"), Speed(3))
    else
      CH("HERO"):MoveTo(SymPos("P03_HERO"), Speed(3))
    end
    CH("HERO"):WaitMove()
    SOUND:PlaySe(SymSnd("SE_EVT_KONOAHAN_ATTACK"), Volume(256))
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(0.5))
    CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
    CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  end
  local taskPartner00 = function()
    CH("PARTNER"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
    local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
    if pokemonIndexPartner == 592 then
      CH("PARTNER"):MoveTo(SymPos("P00_5_PARTNER"), Speed(3))
    elseif pokemonIndexPartner == 479 then
      CH("PARTNER"):MoveTo(SymPos("P00_5_PARTNER"), Speed(3))
    else
      CH("PARTNER"):MoveTo(SymPos("P00_PARTNER"), Speed(3))
    end
    CH("PARTNER"):WaitMove()
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(0.5))
    CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
    CH("PARTNER"):MoveTo(SymPos("P01_PARTNER"), Speed(2.5), LINK_DIR.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  end
  TASK:Regist(taskHero00)
  TASK:Regist(taskPartner00)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(656471435)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Regist(taskHero00)
  TASK:Regist(taskPartner00)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1044104394, PARTNER_1 = 1903841805})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  TASK:Regist(taskHero00)
  TASK:Regist(taskPartner00)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(1751212876)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", SymPos("P_EFF_BG_CONCENTRATION_LP"))
  EFFECT:Play("effectBgConLp")
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1129066639)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  TASK:Regist(taskHero00)
  TASK:Regist(taskPartner00)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SwitchTalk({PARTNER_0 = 1515651534, PARTNER_1 = -573629183})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  EFFECT:Remove("effectBgConLp")
  EFFECT:ChangeColor("effectMatterWaveBeamLp", Color(0, 0, 0, 0), TimeSec(30, TIME_TYPE.FRAME))
  GM("DARKMATTER"):ChangeColor(Color(1, 1, 1, 1), TimeSec(30, TIME_TYPE.FRAME))
  EFFECT:EndMotionBlur()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  SOUND:PlaySe(SymSnd("SE_EVT_DARKMATTER02_BREAK_S"), Volume(256))
  CAMERA:SetShake(Vector2(0.03, 0.03), TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:Create("effectLastHitL", SymEff("EV_LAST_HIT_L"))
  EFFECT:SetPosition("effectLastHitL", SymPos("P_EFF_EV_LAST_HIT_L"))
  EFFECT:SetScale("effectLastHitL", Scale(0.15))
  EFFECT:Play("effectLastHitL")
  EFFECT:Create("effectLastHitR", SymEff("EV_LAST_HIT_R"))
  EFFECT:SetPosition("effectLastHitR", SymPos("P_EFF_EV_LAST_HIT_R"))
  EFFECT:SetScale("effectLastHitR", Scale(0.15))
  EFFECT:Play("effectLastHitR")
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(1.2))
  EFFECT:Remove("effectMatterWaveBeamLp")
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  GM("EV255_DARK01"):SetMotion(SymMot("REVIVE_START"), LOOP.OFF)
  EFFECT:Create("effectLastHit2L", SymEff("EV_LAST_HIT_2_L"))
  EFFECT:SetPosition("effectLastHit2L", SymPos("P_EFF_EV_LAST_HIT_2_L"))
  EFFECT:Play("effectLastHit2L")
  TASK:Sleep(TimeSec(0.1))
  EFFECT:Create("effectLastHit2R", SymEff("EV_LAST_HIT_2_R"))
  EFFECT:SetPosition("effectLastHit2R", SymPos("P_EFF_EV_LAST_HIT_2_R"))
  EFFECT:Play("effectLastHit2R")
  TASK:Sleep(TimeSec(0.1))
  EFFECT:Create("effectLastHit3L", SymEff("EV_LAST_HIT_3_L"))
  EFFECT:SetPosition("effectLastHit3L", SymPos("P_EFF_EV_LAST_HIT_3_L"))
  EFFECT:Play("effectLastHit3L")
  TASK:Sleep(TimeSec(0.5))
  TASK:Sleep(TimeSec(1))
  EFFECT:Create("effectTreeLight", SymEff("EV_TREE_LIGHT"))
  EFFECT:SetPosition("effectTreeLight", SymPos("P_EFF_EV_TREE_LIGHT"))
  EFFECT:Play("effectTreeLight")
  TASK:Sleep(TimeSec(1.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DARKMATTER_02"), Volume(256))
  TASK:Sleep(TimeSec(2))
  EFFECT:Remove("effectLastHit2L")
  EFFECT:Remove("effectLastHit2R")
  EFFECT:Remove("effectLastHit3L")
  GM("EV255_DARK01"):SetMotion(SymMot("REVIVE_KEEP"), LOOP.ON)
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  EFFECT:Create("effectLastHit4LP", SymEff("EV_LAST_HIT_4_LP"))
  EFFECT:SetPosition("effectLastHit4LP", SymPos("P_EFF_EV_LAST_HIT_4_LP"))
  EFFECT:SetScale("effectLastHit4LP", Scale(3))
  EFFECT:Play("effectLastHit4LP")
  CAMERA:MoveFollow2(SymCam("CAMERA_12_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-992728000)
  WINDOW:Monologue(-1381306260)
  WINDOW:CloseMessage()
  subEveFlash2()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  EFFECT:Remove("effectLastHit4LP")
  SYSTEM:SetNextDungeonBanner(false)
end
function main25_darkmatter2boss36_end()
end
function groundEnd()
end
