dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main07_ruchaburuopen01_init()
end
function main07_ruchaburuopen01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskHero00 = function()
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):DirTo(RotateTarget(-25), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskHero00)
  local taskPartner00 = function()
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):DirTo(RotateTarget(-25), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(RotateTarget(-25), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("PARTNER"):SetManpu("MP_NOTICE_L")
  end
  TASK:Regist(taskPartner00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("RUCHABURU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:Talk(SymAct("RUCHABURU"), -1176780404)
  WINDOW:Talk(SymAct("RUCHABURU"), -1597968179)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.4))
  CH("ROZERIA"):DirTo(CH("RUCHABURU"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  CH("RUCHABURU"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("RUCHABURU")
  })
  WINDOW:DrawFace(20, 88, SymAct("RUCHABURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RUCHABURU"), -1947360498)
  WINDOW:KeyWait()
  CH("RUCHABURU"):ResetManpu()
  WINDOW:Talk(SymAct("RUCHABURU"), -1829334449)
  WINDOW:CloseMessage()
  CH("RUCHABURU"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2.5))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("RUCHABURU"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  local taskRuchaburu00 = function()
    CH("RUCHABURU"):SetMotion(SymMot("ATTACK_ROUND"), LOOP.OFF)
    CH("RUCHABURU"):WaitPlayMotion()
    CH("RUCHABURU"):SetMotion(SymMot("ATTACK"), LOOP.OFF)
    CH("RUCHABURU"):WaitPlayMotion()
    CH("RUCHABURU"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("RUCHABURU"):WaitPlayMotion()
    CH("RUCHABURU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    subEveFlash2()
  end
  TASK:Regist(taskRuchaburu00)
  WINDOW:DrawFace(20, 88, SymAct("RUCHABURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RUCHABURU"), -575208312)
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("RUCHABURU")
  })
  WINDOW:Talk(SymAct("RUCHABURU"), -995346999)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("RUCHABURU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("RUCHABURU"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("RUCHABURU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RUCHABURU"), -276732406)
  WINDOW:KeyWait()
  TASK:Regist(taskRuchaburu00)
  WINDOW:Talk(SymAct("RUCHABURU"), -157657269)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_00"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SWEAT_L")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_SWEAT_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  WINDOW:SwitchTalk({PARTNER_0 = 1895975812, PARTNER_1 = 1746500293})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main07_ruchaburuopen01_end()
end
function groundEnd()
end
