dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main12_pokemonatlusga01_init()
end
function main12_pokemonatlusga01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:FadeInEnv(SymSnd("SE_EVT_ATLAS_WORK_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1254858467, PARTNER_1 = 1406185378})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(3))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(SymPos("P_ATLUS"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(SymPos("P_ATLUS"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.7))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(2029911137)
  WINDOW:Monologue(1642515744)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 782719975, PARTNER_1 = 935094950})
  WINDOW:SwitchTalk({PARTNER_0 = 479279461, PARTNER_1 = 92932132})
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(SymPos("P_ATLUS"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-2112744213)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(SymPos("P_ATLUS"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1693899350, PARTNER_1 = 1153898446})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1574708879, PARTNER_1 = 1995535692})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(1877623821)
  WINDOW:Monologue(548131530)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 967893899, PARTNER_1 = 312324168})
  WINDOW:SwitchTalk({PARTNER_0 = 193364233, PARTNER_1 = -1944150586})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
end
function main12_pokemonatlusga01_end()
end
function main12_pokemonatlusga02_init()
end
function main12_pokemonatlusga02_start()
end
function main12_pokemonatlusga02_end()
end
function main12_pokemonatlusga03_init()
end
function main12_pokemonatlusga03_start()
  SOUND:PlayEnv(SymSnd("SE_EVT_ATLAS_WORK_LP"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("POKEMON_ATLAS_D"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1794790265, PARTNER_1 = 1450358816})
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  SOUND:FadeInEnv(SymSnd("SE_EVT_DODODO_LP"), TimeSec(1.5), Volume(256))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_01"), Volume(256))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT_LP")
  TASK:Regist(subEveRunDir, {
    CH("PEROPPAFU"),
    SymPos("P00_PEROPPAFU"),
    Speed(3),
    RotateTarget(0)
  })
  WINDOW:Talk(SymAct(""), 1332316513)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P00_PARTNER"),
    Speed(2),
    RotateTarget(25)
  })
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P00_HERO"),
    Speed(2),
    RotateTarget(-25)
  })
  CH("AAKEN"):RunTo(SymPos("P00_AAKEN"), Speed(3))
  CH("DEDENNE"):RunTo(SymPos("P00_DEDENNE"), Speed(3))
  CH("BUIZERU"):RunTo(SymPos("P00_BUIZERU"), Speed(3))
  CH("HORUBII"):RunTo(SymPos("P00_HORUBII"), Speed(3))
  TASK:Sleep(TimeSec(1.5))
  SOUND:FadeOutEnv(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(2))
  CH("AAKEN"):WaitMove()
  CH("PEROPPAFU"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH("AAKEN"):SetManpu("MP_ANGRY_LP")
  TASK:Sleep(TimeSec(0.2))
  CH("HORUBII"):SetManpu("MP_ANGRY_LP")
  TASK:Sleep(TimeSec(0.3))
  CH("AAKEN"):ResetManpu()
  TASK:Sleep(TimeSec(0.3))
  CH("HORUBII"):ResetManpu()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_01_5"))
  CAMERA:SetTgt(SymCam("CAMERA_01_5"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1682234018, PARTNER_1 = 2103438307})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("BUIZERU")
  })
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct(""), 840858916)
  WINDOW:CloseMessage()
  CH("BUIZERU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_01_6"))
  CAMERA:SetTgt(SymCam("CAMERA_01_6"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT")
  CH("PEROPPAFU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PEROPPAFU"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(40, 0)
  WINDOW:Talk(SymAct("PEROPPAFU"), 721767525)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("HORUBII"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct(""), 2629542)
  WINDOW:CloseMessage()
  CH("HORUBII"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(272, 88, SymAct("DEDENNE"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct(""), 422784743)
  WINDOW:Talk(SymAct(""), -1632947672)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01_6"))
  CAMERA:SetTgt(SymCam("CAMERA_01_6"))
  CH("PEROPPAFU"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("PEROPPAFU"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT")
  CH("PEROPPAFU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PEROPPAFU"), FACE_TYPE.TEARS)
  WINDOW:DrawFaceOffset(40, 0)
  WINDOW:Talk(SymAct("PEROPPAFU"), -2018507927)
  WINDOW:Talk(SymAct("PEROPPAFU"), -288432315)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  local taskHouden00 = function()
    EFFECT:Create("effectHouden01", SymEff("CH_INVOKE"))
    EFFECT:SetPosition("effectHouden01", SymPos("P_EFF_HOUDEN01"))
    EFFECT:Play("effectHouden01")
    SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_JUUDEN_01"))
    CH("DEDENNE"):SetMotion(SymMot("ENDURE"), LOOP.ON)
    TASK:Sleep(TimeSec(0.7))
    SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_JUUDEN_02_LP"))
  end
  TASK:Regist(taskHouden00)
  local taskDelay00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("PEROPPAFU"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):SetManpu("MP_SHOCK_R")
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):SetManpu("MP_SHOCK_R")
  end
  TASK:Regist(taskDelay00)
  WINDOW:DrawFace(324, 88, SymAct("DEDENNE"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DEDENNE"), -136974844)
  WINDOW:Talk(SymAct("DEDENNE"), -587678265)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("DEDENNE"):ResetManpu()
  local taskDelay01 = function()
    TASK:Sleep(TimeSec(0.2))
    TASK:Regist(subEveJumpSurprise, {
      CH("PEROPPAFU")
    })
    TASK:Regist(subEveJumpSurprise, {
      CH("PARTNER")
    })
    TASK:Sleep(TimeSec(0.1))
    TASK:Regist(subEveJumpSurprise, {
      CH("HERO")
    })
  end
  TASK:Regist(taskDelay01)
  SOUND:FadeOutSe(SymSnd("SE_EVT_DEDENNE_JUUDEN_02_LP"), TimeSec(0.2))
  EFFECT:Create("effectHouden02", SymEff("NMC_LUMINOUS_YELLOW_ELECTRIC_BIG_YELLOW"))
  EFFECT:SetPosition("effectHouden02", SymPos("P_EFF_HOUDEN02"))
  EFFECT:Play("effectHouden02")
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_DENGEKI_01"))
  CH("DEDENNE"):SetMotion(SymMot("SPECIAL"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("PEROPPAFU"), -974943098)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:ForceCloseMessage()
  CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveRunDir, {
    CH("PEROPPAFU"),
    SymPos("P01_PEROPPAFU"),
    Speed(4),
    GM("POKEMON_ATLAS")
  })
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(4),
    GM("POKEMON_ATLAS")
  })
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(4),
    GM("POKEMON_ATLAS")
  })
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("DEDENNE"):WaitPlayMotion()
  CH("DEDENNE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  EFFECT:Create("effectLightning", SymEff("EV_LIGHTNING"))
  EFFECT:SetPosition("effectLightning", SymPos("P_EFF_LIGHTNING"))
  EFFECT:Play("effectLightning")
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_DENGEKI_02"))
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  SOUND:PlaySe(SymSnd("SE_EVT_DENKAI_LP"), Volume(256))
  EFFECT:Create("effectAtlasElectric", SymEff("EV_ATLAS_ELECTRIC_LP"))
  EFFECT:SetPosition("effectAtlasElectric", SymPos("P_EFF_ATLAS_ELEC"))
  EFFECT:Play("effectAtlasElectric")
  TASK:Sleep(TimeSec(1))
  CH("PEROPPAFU"):SetPosition(SymPos("P02_PEROPPAFU"))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PEROPPAFU"):SetManpu("MP_EXCLAMATION")
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("BUIZERU"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1969087935, PARTNER_1 = -1816581376})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_KAMAKURA_DESTROY"))
  CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:Create("effectBombdome", SymEff("EV_BOMBDOME"))
  EFFECT:SetPosition("effectBombdome", SymPos("P_EFF_BOMBDOME"))
  EFFECT:Play("effectBombdome")
  TASK:Sleep(TimeSec(0.2))
  GM("POKEMON_ATLAS"):SetVisible(false)
  GM("POKEMON_ATLAS_D"):SetVisible(true)
  TASK:Sleep(TimeSec(0.4))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("HORUBII"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("DEDENNE"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH("DEDENNE"):SetManpu("MP_ANGRY_LP")
  TASK:Sleep(TimeSec(0.3))
  CH("HORUBII"):SetManpu("MP_ANGRY_LP")
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):ResetManpu()
  CH("BUIZERU"):SetManpu("MP_ANGRY_LP")
  TASK:Sleep(TimeSec(0.4))
  CH("HORUBII"):ResetManpu()
  TASK:Sleep(TimeSec(0.1))
  CH("BUIZERU"):ResetManpu()
  TASK:Sleep(TimeSec(0.7))
  SOUND:FadeOutSe(SymSnd("SE_EVT_DENKAI_LP"), TimeSec(2))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("AAKEN"):SetManpu("MP_FLY_SWEAT")
  CH("AAKEN"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct(""), -1198229309)
  WINDOW:Talk(SymAct(""), -1584445054)
  WINDOW:Talk(SymAct(""), 639063373)
  WINDOW:CloseMessage()
  CH("BUIZERU"):DirTo(CH("AAKEN"), Speed(500), ROT_TYPE.NEAR)
  CH("BUIZERU"):WaitRotate()
  local taskDelay02 = function()
    CH("DEDENNE"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    CH("PEROPPAFU"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HORUBII"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(CH("AAKEN"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskDelay02)
  WINDOW:DrawFace(324, 20, SymAct("BUIZERU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct(""), 1057776652)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("DEDENNE")
  })
  WINDOW:DrawFace(172, 8, SymAct("DEDENNE"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DEDENNE"), 1931077628)
  WINDOW:Talk(SymAct("DEDENNE"), 1778570941)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_HARAHERI"), Volume(256))
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_EXCLAMATION")
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("BUIZERU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HORUBII"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):WaitManpu()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("DEDENNE"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUIZERU"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HORUBII"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveJump, {
    CH("PEROPPAFU")
  })
  WINDOW:DrawFace(272, 16, SymAct("PEROPPAFU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1093633406)
  WINDOW:KeyWait()
  CH("PEROPPAFU"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  CH("PEROPPAFU"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PEROPPAFU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(272, 16, SymAct("PEROPPAFU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("PEROPPAFU"), 1479849023)
  WINDOW:Talk(SymAct("PEROPPAFU"), 393552632)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_POTE"))
  CH("PEROPPAFU"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  CH("PEROPPAFU"):WaitPlayMotion()
  CH("PEROPPAFU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  CH("DEDENNE"):SetManpu("MP_EXCLAMATION")
  CH("BUIZERU"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):SetManpu("MP_EXCLAMATION")
  CH("HORUBII"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_08"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("HORUBII"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("HORUBII")
  })
  WINDOW:DrawFace(20, 88, SymAct("HORUBII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct(""), 242095033)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("AAKEN")
  })
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("AAKEN"), 625164410)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_09"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("BUIZERU"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BUIZERU"):SetManpu("MP_FLY_SWEAT")
  CH("BUIZERU"):WaitManpu()
  CH("HORUBII"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  CH("HERO"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BUIZERU"), 1012429115)
  subEveCloseMsg()
  CH("AAKEN"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  CH("DEDENNE"):SetMotion(SymMot("CONFUSE"), LOOP.ON)
  WINDOW:DrawFace(72, 16, SymAct("DEDENNE"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("DEDENNE"), -1145016844)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("DEDENNE"):SetManpu("MP_SHOCK_R")
  CH("DEDENNE"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("BUIZERU"):SetManpu("MP_SHOCK_L")
  CH("BUIZERU"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("AAKEN"):SetManpu("MP_SHOCK_R")
  CH("AAKEN"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("HORUBII"):SetManpu("MP_SHOCK_R")
  CH("HORUBII"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  CH("DEDENNE"):WaitPlayMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_POTE"))
  CH("DEDENNE"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  CH("BUIZERU"):WaitPlayMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_POTE"))
  CH("BUIZERU"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  CH("AAKEN"):WaitPlayMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_POTE"))
  CH("AAKEN"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  CH("HORUBII"):WaitPlayMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_POTE"))
  CH("HORUBII"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  CH("HERO"):RunTo(SymPos("P02_HERO"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):RunTo(SymPos("P02_PARTNER"), Speed(2))
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1562682187, PARTNER_1 = -878346087})
  WINDOW:CloseMessage()
  CH("BUIZERU"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CH("BUIZERU"):ResetShake()
  WINDOW:DrawFace(324, 20, SymAct("BUIZERU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BUIZERU"), -759254568)
  WINDOW:Talk(SymAct("BUIZERU"), -107748837)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_HARAHERI"), Volume(256))
  WINDOW:SysMsg(-527903910)
  TASK:Sleep(TimeSec(0.5))
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("DEDENNE"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("DEDENNE"), -1345763939)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("AAKEN"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("AAKEN"), -1227721508)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1644222689, PARTNER_1 = -2065426850})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("BUIZERU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BUIZERU"), 58460817)
  WINDOW:Talk(SymAct("BUIZERU"), 442973136)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PEROPPAFU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BUIZERU"), -653250697)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1073013194, PARTNER_1 = -349811211})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DEDENNE"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("DEDENNE"), -230851404)
  WINDOW:Talk(SymAct("DEDENNE"), -1115886989)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BUIZERU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("BUIZERU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BUIZERU"), -1536697550)
  WINDOW:Talk(SymAct("BUIZERU"), -1890940687)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1773028944, PARTNER_1 = 298427775})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 148018238, PARTNER_1 = 1638680594})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  CH("PARTNER"):RunTo(SplinePath(SymPos("P03_PARTNER"), SymPos("P04_PARTNER")), Speed(3))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):RunTo(SplinePath(SymPos("P03_HERO"), SymPos("P04_HERO")), Speed(3))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutBgm(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main12_pokemonatlusga03_end()
end
function groundEnd()
end
