dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main17_aratanaruyokokujou01_init()
end
function main17_aratanaruyokokujou01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 280021560)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MIRUTANKU"):SetVisible(false)
  TASK:Regist(subEveMoveDir, {
    CH("YAMIKARASU_TOWN"),
    SymPos("P00_YAMIKARASU"),
    Speed(1.5),
    RotateTarget(40)
  })
  SOUND:PlayBgm(SymSnd("BGM_EVE_WAIWAITOWN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("YAMIKARASU_TOWN"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Sleep(TimeSec(0.2))
  CH("YAMIKARASU_TOWN"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("YAMIKARASU"), 162265977)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  local taskMirutanku00 = function()
    CH("MIRUTANKU"):SetVisible(true)
    CH("MIRUTANKU"):SetNeckRot(RotateTarget(-30), RotateTarget(0), RotateTarget(0), TimeSec(0))
    CH("MIRUTANKU"):WalkTo(SymPos("P00_MIRUTANKU"), Speed(1.5))
    CH("MIRUTANKU"):WaitMove()
    CH("MIRUTANKU"):ResetNeckRot(TimeSec(0.1))
    CH("MIRUTANKU"):DirTo(CH("YAMIKARASU_TOWN"), Speed(350), ROT_TYPE.NEAR)
    CH("MIRUTANKU"):WaitRotate()
  end
  TASK:Regist(taskMirutanku00)
  TASK:Sleep(TimeSec(0.5))
  CH("MIRUTANKU"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("MIRUTANKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUTANKU"), 579250362)
  WINDOW:CloseMessage()
  CH("MIRUTANKU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("YAMIKARASU_TOWN"):ResetManpu()
  CH("YAMIKARASU_TOWN"):ResetFacialMotion()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("YAMIKARASU_TOWN"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.3))
  CH("YAMIKARASU_TOWN"):DirTo(SymPos("P00_MIRUTANKU"), Speed(350), ROT_TYPE.RIGHT)
  CH("YAMIKARASU_TOWN"):WaitRotate()
  CH("YAMIKARASU_TOWN"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(324, 88, SymAct("YAMIKARASU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1000184315)
  WINDOW:CloseMessage()
  CH("YAMIKARASU_TOWN"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("YAMIKARASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1960578876)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("MIRUTANKU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MIRUTANKU"), 1841774205)
  WINDOW:Talk(SymAct("MIRUTANKU"), 1189768638)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_04"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("MIRUTANKU"):WalkTo(SymPos("P01_MIRUTANKU"), Speed(1.5))
  CH("YAMIKARASU_TOWN"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("YAMIKARASU_TOWN"):DirLockToChara(CH("MIRUTANKU"))
  TASK:Sleep(TimeSec(1.7))
  CH("YAMIKARASU_TOWN"):DirLockOff()
  CH("YAMIKARASU_TOWN"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1609653503)
  WINDOW:Talk(SymAct("YAMIKARASU"), -664190928)
  WINDOW:CloseMessage()
  CH("YAMIKARASU_TOWN"):WalkTo(SymPos("P01_YAMIKARASU"), Speed(1.5))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main17_aratanaruyokokujou01_end()
end
function main17_aratanaruyokokujou02_init()
end
function main17_aratanaruyokokujou02_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_WAIWAITOWN_01"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("YAMIKARASU_TOWN"):WalkTo(SymPos("P00_YAMIKARASU"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("YAMIKARASU_TOWN"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("YAMIKARASU_TOWN"):SetManpu("MP_QUESTION")
  CH("YAMIKARASU_TOWN"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YAMIKARASU"), -1049464463)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1242416268)
  WINDOW:CloseMessage()
  CH("YAMIKARASU_TOWN"):WalkTo(SymPos("P01_YAMIKARASU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:FadeOutBgm(TimeSec(1))
  CH("YAMIKARASU_TOWN"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("YAMIKARASU_TOWN"):SetManpu("MP_EXCLAMATION")
  CH("YAMIKARASU_TOWN"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("YAMIKARASU_TOWN")
  })
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YAMIKARASU"), 1394013645)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  local taskYamikarasu00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("YAMIKARASU_TOWN"):SetManpu("MP_FLY_SWEAT")
    CH("YAMIKARASU_TOWN"):DirTo(CH("MIRUTANKU"), Speed(500), ROT_TYPE.NEAR)
    CH("YAMIKARASU_TOWN"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("YAMIKARASU_TOWN"):DirTo(CH("MASSUGUMA"), Speed(500), ROT_TYPE.NEAR)
    CH("YAMIKARASU_TOWN"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("YAMIKARASU_TOWN"):DirTo(CH("MIRUTANKU"), Speed(500), ROT_TYPE.NEAR)
    CH("YAMIKARASU_TOWN"):WaitRotate()
  end
  TASK:Regist(taskYamikarasu00)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YAMIKARASU"), 2017175054)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("KOROBOOSHI"):DirTo(CH("YAMIKARASU_TOWN"), Speed(350), ROT_TYPE.NEAR)
  CH("KOROBOOSHI"):WaitRotate()
  CH("YAMIKARASU_TOWN"):DirTo(CH("KOROBOOSHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("KOROBOOSHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KOROBOOSHI"), 1629525839)
  WINDOW:CloseMessage()
  CH("YAMIKARASU_TOWN"):WalkTo(SymPos("P02_YAMIKARASU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  CH("KOROBOOSHI"):DirTo(SymPos("P02_YAMIKARASU"), Speed(200), ROT_TYPE.NEAR)
  CH("MASSUGUMA"):DirTo(SymPos("P02_YAMIKARASU"), Speed(200), ROT_TYPE.NEAR)
  CH("YAMIKARASU_TOWN"):WaitMove()
  CH("YAMIKARASU_TOWN"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.15))
  CH("YAMIKARASU_TOWN"):WaitNeckRot()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("YAMIKARASU_TOWN"):ResetNeckRot(TimeSec(0.1))
  CH("YAMIKARASU_TOWN"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("YAMIKARASU_TOWN")
  })
  CH("YAMIKARASU_TOWN"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("YAMIKARASU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YAMIKARASU"), 778109320)
  CH("MIRUTANKU"):SetManpu("MP_EXCLAMATION")
  CH("MASSUGUMA"):SetManpu("MP_EXCLAMATION")
  CH("KOROBOOSHI"):SetManpu("MP_EXCLAMATION")
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Regist(taskYamikarasu00)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("YAMIKARASU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("YAMIKARASU"), 930754761)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main17_aratanaruyokokujou02_end()
end
function main17_aratanaruyokokujou03_init()
end
function main17_aratanaruyokokujou03_start()
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("WALLPAPER_MAIN_CAPTURE_BG01"))
  MAP:SetVisibleBG(true)
  WINDOW:BeginChapter()
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  SCREEN_A:FadeIn(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(1), false)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Chapter(TimeSec(1.5), TimeSec(1.5), 475489034)
  TASK:Sleep(TimeSec(3))
  SCREEN_A:FadeOutAll(TimeSec(1), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  WINDOW:EndChapter()
  WINDOW:ForceCloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main17_aratanaruyokokujou03_end()
end
function groundEnd()
end
