dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main08_miruhogguuwasaninaru01_init()
end
function main08_miruhogguuwasaninaru01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ZANNEN_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(272, 16, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), 1444417503)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), 1325612702)
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HASUBURERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("RATTA"):SetManpu("MP_NOTICE_R")
  CH("HASUBURERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("RATTA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HASUBURERO"):WaitRotate()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), 1680764253)
  WINDOW:Talk(SymAct("HASUBURERO"), 2100648988)
  WINDOW:Talk(SymAct("HASUBURERO"), 846514907)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 728759194, PARTNER_1 = 4368473})
  WINDOW:SwitchTalk({PARTNER_0 = 425302296, PARTNER_1 = -1631484457})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -2015710058)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1338191568, PARTNER_1 = -1457004431})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 20, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), -2113227854)
  WINDOW:Talk(SymAct("HASUBURERO"), -1693351181)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  CH("RATTA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -732949452, PARTNER_1 = -850713227})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("RATTA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RATTA"), -429492554)
  WINDOW:Talk(SymAct("RATTA"), -8566793)
  WINDOW:CloseMessage()
  CH("HASUBURERO"):DirTo(CH("RATTA"), Speed(350), ROT_TYPE.NEAR)
  CH("HASUBURERO"):WaitRotate()
  CH("HASUBURERO"):SetManpu("MP_LAUGH_LP")
  CH("RATTA"):DirTo(CH("HASUBURERO"), Speed(350), ROT_TYPE.NEAR)
  CH("RATTA"):WaitRotate()
  CH("RATTA"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(1.3))
  CH("HASUBURERO"):ResetManpu()
  CH("HASUBURERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("RATTA"):ResetManpu()
  CH("RATTA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HASUBURERO"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HASUBURERO"), 2028297016)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main08_miruhogguuwasaninaru01_end()
end
function groundEnd()
end
