dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main08_genbakenshou01_init()
end
function main08_genbakenshou01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  SOUND:FadeInEnv(SymSnd("SE_MAP_HILLSWIND_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.7))
  WINDOW:DrawFace(20, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 823381571)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitMove()
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveRunDir, {
    CH("SHIKIJIKA_SPRING"),
    SymPos("P00_SHIKIJIKA"),
    Speed(3),
    CH("HERO")
  })
  TASK:Regist(subEveRunDir, {
    CH("NUMERA"),
    SymPos("P00_NUMERA"),
    Speed(2.5),
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.7))
  CH("PARTNER"):DirTo(SymPos("P00_NUMERA"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(SymPos("P00_SHIKIJIKA"), Speed(200), ROT_TYPE.NEAR)
  TASK:WaitTask()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 671678210, PARTNER_1 = 52800705})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 440311168)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUMERA"), 1434389319)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1281636870, PARTNER_1 = 1732864453})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 2119325828)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -104184757)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("SHIKIJIKA_SPRING"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -523143926, PARTNER_1 = -2119466741})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SHIKIJIKA_SPRING"):RunTo(SymPos("P01_SHIKIJIKA"), Speed(2.5))
  TASK:Sleep(TimeSec(0.2))
  CH("NUMERA"):RunTo(SymPos("P01_NUMERA"), Speed(2.5))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):RunTo(SplinePath(SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(2.5))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):RunTo(SplinePath(SymPos("P01_PARTNER"), SymPos("P02_PARTNER")), Speed(2.5))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main08_genbakenshou01_end()
end
function main08_genbakenshou02_init()
end
function main08_genbakenshou02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("SHIKIJIKA_SPRING"):SetVisible(false)
  CH("NUMERA"):SetVisible(false)
  CH("REAKOIRU"):SetVisible(false)
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  WINDOW:DrawFace(20, 20, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -1733250998)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -1281498231)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("TABUNNE"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("TABUNNE"), -1434004792)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CH("SHIKIJIKA_SPRING"):SetVisible(true)
  CH("NUMERA"):SetVisible(true)
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(2.5))
  CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(2.5))
  CH("SHIKIJIKA_SPRING"):RunTo(SymPos("P00_SHIKIJIKA"), Speed(2.5))
  CH("NUMERA"):RunTo(SymPos("P00_NUMERA"), Speed(2.5))
  CH("NUMERA"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveDoubleJump, {
    CH("NUMERA")
  })
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NUMERA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NUMERA"), -439925745)
  WINDOW:CloseMessage()
  TASK:Regist(subEveRunDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(2.5),
    CH("HASUBURERO")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(2.5),
    CH("HASUBURERO")
  })
  TASK:Regist(subEveRunDir, {
    CH("SHIKIJIKA_SPRING"),
    SymPos("P01_SHIKIJIKA"),
    Speed(2.5),
    CH("HASUBURERO")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveRunDir, {
    CH("NUMERA"),
    SymPos("P01_NUMERA"),
    Speed(2.5),
    CH("HASUBURERO")
  })
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:WaitTask()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -52660914, PARTNER_1 = -672061811})
  WINDOW:CloseMessage()
  CH("HASUBURERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HASUBURERO"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("HASUBURERO"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(10, 0)
  WINDOW:Talk(SymAct("HASUBURERO"), -823519284)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("SHIKIJIKA_SPRING"):SetManpu("MP_EXCLAMATION")
  CH("NUMERA"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("NUMERA")
  })
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), 1232210691)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("TABUNNE"):SetManpu("MP_NOTICE_L")
  CH("TABUNNE"):WaitManpu()
  CH("TABUNNE"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("TABUNNE"):WaitRotate()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
    CH("HIYAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
    CH("ROZERIA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HASUBURERO"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
    CH("JIBAKOIRU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("KOIRU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("RATTA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(20, 20, SymAct("TABUNNE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TABUNNE"), 1349073474)
  subEveCloseMsg()
  TASK:WaitTask()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1826738459, PARTNER_1 = -1979375708})
  WINDOW:SwitchTalk({PARTNER_0 = -1591194521, PARTNER_1 = -1204585178})
  subEveCloseMsg()
  CH("TABUNNE"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 20, SymAct("TABUNNE"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("TABUNNE"), -143463455)
  WINDOW:Talk(SymAct("TABUNNE"), -295052640)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HASUBURERO"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("ROZERIA"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(20, 20, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -985364125)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -597706718)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 1539810541)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("JIBAKOIRU"):SetManpu("MP_FLY_SWEAT")
  CH("JIBAKOIRU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("JIBAKOIRU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 1121752492)
  subEveCloseMsg()
  CH("REAKOIRU"):SetVisible(true)
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.3))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("JIBAKOIRU"):SetManpu("MP_EXCLAMATION")
    CH("HASUBURERO"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("HIYAKKII"):SetManpu("MP_EXCLAMATION")
    CH("JIBAKOIRU"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("HIYAKKII"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("SHIKIJIKA_SPRING"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("ROZERIA"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HASUBURERO"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("KOIRU"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("RATTA"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  SOUND:FadeOutBgm(TimeSec(1))
  CH("TABUNNE"):ResetFacialMotion()
  WINDOW:Talk(SymAct("REAKOIRU"), 732055936)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("REAKOIRU"):RunTo(SymPos("P00_REAKOIRU"), Speed(3))
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  CH("REAKOIRU"):SetPosition(SymPos("P01_REAKOIRU"))
  CH("REAKOIRU"):RunTo(SymPos("P02_REAKOIRU"), Speed(2.5))
  local taskHero00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    CH("HERO"):DirTo(SymPos("P02_REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  local taskNumera00 = function()
    CH("NUMERA"):WalkTo(SymPos("P02_NUMERA"), Speed(1.5))
    CH("NUMERA"):WaitMove()
    CH("NUMERA"):DirTo(SymPos("P02_REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("NUMERA"):WaitRotate()
  end
  local taskHasuburero00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HASUBURERO"):WalkTo(SymPos("P00_HASUBURERO"), Speed(1.5))
    CH("HASUBURERO"):WaitMove()
    CH("HASUBURERO"):DirTo(SymPos("P02_REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("HASUBURERO"):WaitRotate()
  end
  local taskLookAt03 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("SHIKIJIKA_SPRING"):DirTo(SymPos("P02_REAKOIRU"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(SymPos("P02_REAKOIRU"), Speed(200), ROT_TYPE.NEAR)
    CH("ROZERIA"):DirTo(SymPos("P02_REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("KOIRU"):DirTo(SymPos("P02_REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("RATTA"):DirTo(SymPos("P02_REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
    CH("HIYAKKII"):DirTo(SymPos("P02_REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt03)
  TASK:Regist(taskHero00)
  TASK:Regist(taskNumera00)
  TASK:Regist(taskHasuburero00)
  CH("REAKOIRU"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("JIBAKOIRU"):SetManpu("MP_EXCLAMATION")
  CH("JIBAKOIRU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 851015873)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 429140738)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("REAKOIRU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("REAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("REAKOIRU"), 9378371)
  WINDOW:Talk(SymAct("REAKOIRU"), 1338936452)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("JIBAKOIRU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveJump, {
    CH("KOIRU")
  })
  CH("TABUNNE"):SetManpu("MP_EXCLAMATION")
  CH("HASUBURERO"):SetManpu("MP_EXCLAMATION")
  CH("HIYAKKII"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlayBgm(SymSnd("BGM_EVE_TENSION_01"), Volume(256))
  WINDOW:DrawFace(172, 8, SymAct("TABUNNE"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-30, 0)
  WINDOW:Talk(SymAct("TABUNNE"), 1456848325)
  WINDOW:CloseMessage()
  CH("REAKOIRU"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
  CH("REAKOIRU"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("REAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("REAKOIRU"), 2113465862)
  WINDOW:Talk(SymAct("REAKOIRU"), 1692655431)
  WINDOW:Talk(SymAct("REAKOIRU"), -478428280)
  WINDOW:Talk(SymAct("REAKOIRU"), -94309687)
  WINDOW:Talk(SymAct("REAKOIRU"), -1233817287)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("TABUNNE"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("HASUBURERO")
  })
  WINDOW:DrawFaceF(172, 8, SymAct("HASUBURERO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HASUBURERO"), -1351729032)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("RATTA"):SetManpu("MP_FLY_SWEAT")
  CH("RATTA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("RATTA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("RATTA"), -2075978821)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1655168262, PARTNER_1 = -770067395})
  WINDOW:CloseMessage()
  CH("SHIKIJIKA_SPRING"):SetPosition(SymPos("P01_5_SHIKIJIKA"))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("JIBAKOIRU"):WalkTo(SymPos("P00_JIBAKOIRU"), Speed(1.5))
  CH("JIBAKOIRU"):WaitMove()
  CH("JIBAKOIRU"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("JIBAKOIRU")
  })
  SOUND:FadeOutBgm(TimeSec(0.5))
  WINDOW:DrawFace(20, 20, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -889027204)
  WINDOW:CloseMessage()
  CH("JIBAKOIRU"):ResetManpu()
  CH("PARTNER"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  CH("SHIKIJIKA_SPRING"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("REAKOIRU"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  CH("ROZERIA"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("TABUNNE"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  CH("HIYAKKII"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.6))
  WINDOW:DrawFace(20, 20, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -533735745)
  WINDOW:Talk(SymAct("JIBAKOIRU"), -113973250)
  WINDOW:KeyWait()
  CH("JIBAKOIRU"):SetManpu("MP_SPREE_LP")
  WINDOW:Talk(SymAct("JIBAKOIRU"), 2125265713)
  WINDOW:CloseMessage()
  CH("JIBAKOIRU"):ResetManpu()
  CH("TABUNNE"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HIYAKKII"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  CH("REAKOIRU"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveMoveDir2, {
    CH("RATTA"),
    SymPos("P00_RATTA"),
    Speed(1.5),
    SymPos("P00_RATTA")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveMoveDir2, {
    CH("HASUBURERO"),
    SymPos("P01_HASUBURERO"),
    Speed(1.5),
    SymPos("P01_HASUBURERO")
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveMoveDir2, {
    CH("ROZERIA"),
    SymPos("P00_ROZERIA"),
    Speed(1.5),
    SymPos("P00_ROZERIA")
  })
  TASK:Sleep(TimeSec(3))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("JIBAKOIRU"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
  CH("JIBAKOIRU"):WaitRotate()
  CH("TABUNNE"):DirTo(CH("JIBAKOIRU"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("REAKOIRU"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KOIRU"):DirTo(CH("TABUNNE"), Speed(350), ROT_TYPE.NEAR)
  CH("HIYAKKII"):DirTo(CH("JIBAKOIRU"), Speed(200), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 1740098160)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_08"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("JIBAKOIRU"):DirTo(CH("REAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("REAKOIRU"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KOIRU"):DirTo(CH("JIBAKOIRU"), Speed(350), ROT_TYPE.NEAR)
  CH("JIBAKOIRU"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("JIBAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("JIBAKOIRU"), 248059484)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("REAKOIRU")
  })
  WINDOW:DrawFace(324, 88, SymAct("REAKOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("REAKOIRU"), 399648541)
  subEveCloseMsg()
  CH("KOIRU"):SetMotion(SymMot("ROUND"), LOOP.OFF)
  WINDOW:DrawFace(20, 88, SymAct("KOIRU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOIRU"), 1023374558)
  CH("KOIRU"):WaitPlayMotion()
  CH("KOIRU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:CloseMessage()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.5))
    CH("TABUNNE"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.RIGHT)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.RIGHT)
    CH("HIYAKKII"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  TASK:Regist(subEveMoveDir2, {
    CH("REAKOIRU"),
    SymPos("P03_REAKOIRU"),
    Speed(1.5),
    SymPos("P03_REAKOIRU")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir2, {
    CH("JIBAKOIRU"),
    SymPos("P01_JIBAKOIRU"),
    Speed(1.5),
    SymPos("P01_JIBAKOIRU")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir2, {
    CH("KOIRU"),
    SymPos("P00_KOIRU"),
    Speed(1.5),
    SymPos("P00_KOIRU")
  })
  TASK:Sleep(TimeSec(0.6))
  TASK:Regist(subEveMoveDir, {
    CH("SHIKIJIKA_SPRING"),
    SymPos("P02_SHIKIJIKA"),
    Speed(1.5),
    RotateTarget(0)
  })
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
end
function main08_genbakenshou02_end()
end
function groundEnd()
end
