dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main23_konohananowana01_init()
end
function main23_konohananowana01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("OOBEMU"):WalkTo(SymPos("P00_OOBEMU"), Speed(1.5))
  SOUND:PlayEnv(SymSnd("SE_EVT_DROP_WATER_LP"), Volume(128))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("OOBEMU"):WaitMove()
  TASK:Sleep(TimeSec(0.4))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -774301090, PARTNER_1 = -926799073})
  WINDOW:SwitchTalk({PARTNER_0 = -470845220, PARTNER_1 = -84653667})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  local taskHero00 = function()
    CH("HERO"):DirTo(RotateTarget(135), Speed(200), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.OFF)
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local taskPartner00 = function()
    CH("PARTNER"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.OFF)
    CH("PARTNER"):WaitPlayMotion()
    CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskPartner00)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1246372006, PARTNER_1 = -1397821925})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -2021409320, PARTNER_1 = -1634169703})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), 419467350)
  WINDOW:Talk(SymAct("OOBEMU"), 1810711)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(taskPartner00)
  WINDOW:DrawFace(324, 20, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(0, -10)
  WINDOW:Talk(SymAct("OOBEMU"), -8840432)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(190))
  CH("OOBEMU"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU"):WaitManpu()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:WaitTask()
  CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -429774255, PARTNER_1 = -850429550})
  WINDOW:SwitchTalk({PARTNER_0 = -732673837, PARTNER_1 = -1693065708})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -2112950443)
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.THINK)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1457275754, PARTNER_1 = -1338470953})
  WINDOW:SwitchTalk({PARTNER_0 = 933269784, PARTNER_1 = 784048217})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetFacialMotion()
  SOUND:FadeOutEnv(TimeSec(0.5))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -305351426)
  WINDOW:CloseMessage()
  TASK:Regist(subEveFukumiWarai, {
    CH("OOBEMU")
  })
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("OOBEMU"), -187202113)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("OOBEMU"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("OOBEMU")
  })
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -537209220)
  WINDOW:CloseMessage()
  CH("OOBEMU"):ResetManpu()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -958273731, PARTNER_1 = -1985973766})
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_03"), Volume(256))
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-1866776389)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1147792520, PARTNER_1 = -1567808967})
  WINDOW:SwitchTalk({PARTNER_0 = 622149366, PARTNER_1 = 1007554487})
  WINDOW:SwitchTalk({PARTNER_0 = 1433457563, PARTNER_1 = 1282138842})
  WINDOW:SwitchTalk({PARTNER_0 = 1732686105, PARTNER_1 = 2120056920})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), 823924383)
  WINDOW:Talk(SymAct("OOBEMU"), 671557598)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 53113885, PARTNER_1 = 439436636})
  WINDOW:SwitchTalk({PARTNER_0 = -1649845869, PARTNER_1 = -2068682542})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -928519390)
  WINDOW:Talk(SymAct("OOBEMU"), -776152477)
  WINDOW:Talk(SymAct("OOBEMU"), -91125344)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("PARTNER")
  })
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -477447967, PARTNER_1 = -1395970522})
  WINDOW:CloseMessage()
  SOUND:PlayEnv(SymSnd("SE_EVT_DROP_WATER_LP"), Volume(128))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), -1244651673)
  WINDOW:Talk(SymAct("OOBEMU"), -1627566940)
  WINDOW:Talk(SymAct("OOBEMU"), -2014937627)
  WINDOW:CloseMessage()
  CH("OOBEMU"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(8282410)
  WINDOW:CloseMessage()
  CH("OOBEMU"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("OOBEMU"), 426070123)
  WINDOW:Talk(SymAct("OOBEMU"), 1880853575)
  WINDOW:Talk(SymAct("OOBEMU"), 1761656070)
  WINDOW:Talk(SymAct("OOBEMU"), 1110306501)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1530322820, PARTNER_1 = 343361859})
  subEveCloseMsg()
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    CH("OOBEMU"):SetManpu("MP_EXCLAMATION")
    CH("PARTNER"):WaitManpu()
  end
  TASK:Regist(taskLookAt00)
  WINDOW:SysMsg(225212418)
  WINDOW:SysMsg(641805249)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  local taskHero01 = function()
    CH("HERO"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("HERO"), Speed(700))
  end
  local taskPartner01 = function()
    CH("PARTNER"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    subEveLookAround(CH("PARTNER"), Speed(700))
  end
  TASK:Regist(taskHero01)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskPartner01)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1062869632, PARTNER_1 = -1195243953})
  subEveCloseMsg()
  WINDOW:DrawFaceF(272, 16, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1579600114)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_WHITEOUT"))
  SCREEN_A:WhiteOut(TimeSec(0.5), true)
end
function main23_konohananowana01_end()
end
function main23_konohananowana02_init()
end
function main23_konohananowana02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("KONOHANA"):SetEyeMotion(EYE_MOTION.ANGRY)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  SCREEN_A:WhiteIn(TimeSec(0.3), false)
  local taskHero00 = function()
    CH("HERO"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2), LINK_DIR.OFF)
    CH("HERO"):WaitMove()
    CH("HERO"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  end
  TASK:Regist(taskHero00)
  local taskPartner00 = function()
    CH("PARTNER"):SetManpu("MP_EXCLAMATION")
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2), LINK_DIR.OFF)
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  end
  TASK:Regist(taskPartner00)
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlayEnv(SymSnd("SE_EVT_DROP_WATER_LP"), Volume(128))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1655579561)
  WINDOW:Talk(SymAct("KONOHANA"), 2075464424)
  WINDOW:Talk(SymAct("KONOHANA"), 1352155435)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("OOBEMU"), 1233350762)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 113436333)
  WINDOW:Talk(SymAct("KONOHANA"), 534370284)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(888439855)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 770684270)
  WINDOW:Talk(SymAct("KONOHANA"), -1434998367)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.2))
  CH("KONOHANA"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1284728608, PARTNER_1 = -636336948})
  WINDOW:SwitchTalk({PARTNER_0 = -1022790259, PARTNER_1 = -400284082})
  WINDOW:SwitchTalk({PARTNER_0 = -247523569, PARTNER_1 = -1099005496})
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = -1486507895, PARTNER_1 = -1941380278})
  WINDOW:SwitchTalk({PARTNER_0 = -1789668853, PARTNER_1 = 315346628})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 198246277)
  WINDOW:Talk(SymAct("KONOHANA"), -2106501990)
  WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(CH("OOBEMU"), Speed(60), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -1687525925)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1337510376)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1453586599, PARTNER_1 = -434269794})
  WINDOW:SwitchTalk({PARTNER_0 = -16342817, PARTNER_1 = -735317220})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -852442531)
  WINDOW:Talk(SymAct("KONOHANA"), 1252581010)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("OOBEMU"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.2))
  CH("OOBEMU"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), 1404301267)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 986526719)
  WINDOW:Talk(SymAct("KONOHANA"), 601227966)
  WINDOW:Talk(SymAct("KONOHANA"), 150688125)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU"):ResetNeckRot(TimeSec(0.1))
  CH("OOBEMU"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("OOBEMU"), 299917372)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1587672827)
  WINDOW:Talk(SymAct("KONOHANA"), 1203423162)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HERO"), 1821873273)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1972151608, PARTNER_1 = -233522697})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("OOBEMU"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.2))
  CH("OOBEMU"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), -351303498)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(60), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1580728520)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1193488777)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1812881994)
  WINDOW:Talk(SymAct("KONOHANA"), 1964331787)
  WINDOW:Talk(SymAct("KONOHANA"), 978634188)
  WINDOW:Talk(SymAct("KONOHANA"), 592442509)
  WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(RotateTarget(0), Speed(60), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 140683086)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 293180943, PARTNER_1 = -1763603776})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -1879393407)
  WINDOW:Talk(SymAct("KONOHANA"), -427530323)
  WINDOW:Talk(SymAct("KONOHANA"), -6334740)
  WINDOW:Talk(SymAct("KONOHANA"), -726530769)
  WINDOW:Talk(SymAct("KONOHANA"), -844549010)
  WINDOW:Talk(SymAct("KONOHANA"), -2098683223)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1678535704, PARTNER_1 = -1327579093})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1446645398)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:MoveFollow2(SymCam("CAMERA_07_5"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 777907621)
  WINDOW:Talk(SymAct("KONOHANA"), 927390948)
  WINDOW:Talk(SymAct("KONOHANA"), -198064061)
  WINDOW:Talk(SymAct("KONOHANA"), -315950846)
  WINDOW:Talk(SymAct("KONOHANA"), -972576063)
  WINDOW:Talk(SymAct("KONOHANA"), -551773312)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main23_konohananowana02_end()
end
function main23_konohananowana03_init()
end
function main23_konohananowana03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("KONOHANA"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0))
  EFFECT:CreateRecollectionFilter()
  CH("HERO"):SetVisibleScarf(false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-1872949945)
  WINDOW:SysMsg(-1991885818)
  WINDOW:SysMsg(-1570017339)
  WINDOW:SysMsg(-1150263676)
  WINDOW:SysMsg(1021854283)
  WINDOW:SysMsg(636711690)
  WINDOW:SysMsg(1284353830)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(1435934311)
  WINDOW:SysMsg(2126237092)
  WINDOW:SysMsg(1738603749)
  WINDOW:SysMsg(685861410)
  WINDOW:SysMsg(838490979)
  WINDOW:SysMsg(450300064)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  EFFECT:DestroyRecollectionFilter()
end
function main23_konohananowana03_end()
end
function main23_konohananowana04_init()
end
function main23_konohananowana04_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("OOBEMU"):SetMotion(SymMot("EV100_TALK"), LOOP.ON, TimeSec(0))
  CH("OOBEMU2"):SetMotion(SymMot("EV100_TALK"), LOOP.ON, TimeSec(0))
  CH("OOBEMU3"):SetMotion(SymMot("EV100_TALK"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetVisibleScarf(false)
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("OOBEMU2"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("OOBEMU3"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("OOBEMU"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("OOBEMU3"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("OOBEMU"):WaitRotate()
  CAMERA:MoveFollow(SymCam("CAMERA_07"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("OOBEMU3"):SetMotion(SymMot("DOUBLE"), LOOP.OFF)
  CH("OOBEMU3"):MoveTo(SymPos("P02_OOBEMU3"), Speed(2.5), LINK_DIR.ON)
  CH("HERO"):DirTo(CH("OOBEMU3"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), false)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("OOBEMU"):DirTo(SymPos("P02_HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("OOBEMU2"):DirTo(SymPos("P02_HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), false)
  CH("OOBEMU3"):WaitMove()
  CH("OOBEMU3"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(63715809)
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(CH("OOBEMU3"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_08"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("OOBEMU"):SetMotion(SymMot("DOUBLE"), LOOP.OFF)
  CH("OOBEMU"):MoveTo(SymPos("P01_OOBEMU"), Speed(2.5), LINK_DIR.ON)
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), false)
  CH("HERO"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
  CH("HERO"):MoveTo(SymPos("P03_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("OOBEMU2"):DirTo(SymPos("P03_HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), false)
  CH("OOBEMU"):WaitMove()
  CH("OOBEMU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("HERO"):WaitMove()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("HERO"):SetMotionRaito(Raito(2))
  CH("OOBEMU3"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-2074860242)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1655761809)
  WINDOW:SysMsg(-782592097)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  SYSTEM:SetForceSyncStop(false)
  EFFECT:DestroyRecollectionFilter()
end
function main23_konohananowana04_end()
end
function main23_konohananowana05_init()
end
function main23_konohananowana05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:SysMsg(-935221538)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  EFFECT:CreateRecollectionFilter()
  CH("HERO"):SetVisibleScarf(false)
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("OOBEMU"):SetMotion(SymMot("DOUBLE"), LOOP.OFF)
  CH("OOBEMU"):MoveTo(SymPos("P01_OOBEMU"), Speed(2.5), LINK_DIR.ON)
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), false)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
  CH("HERO"):MoveTo(SymPos("P02_HERO"), Speed(2.5), LINK_DIR.OFF)
  TASK:Regist(subEveJumpSurprise, {
    CH("KONOHANA")
  })
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), false)
  CH("OOBEMU"):WaitMove()
  CH("OOBEMU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("HERO"):WaitMove()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT_LP")
  CH("KONOHANA"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -479398627)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_06"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("OOBEMU2"):SetMotion(SymMot("DOUBLE"), LOOP.OFF)
  CH("OOBEMU2"):MoveTo(SymPos("P01_OOBEMU2"), Speed(3.5), LINK_DIR.ON)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(RotateOffs(-15), Speed(500))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), false)
  CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("KONOHANA"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
  CH("KONOHANA"):MoveTo(SymPos("P01_KONOHANA"), Speed(2.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), false)
  CH("HERO"):SetMotion(SymMot("EV000_SURPRISE"), LOOP.OFF)
  CH("HERO"):MoveTo(SymPos("P03_HERO"), Speed(2.5), LINK_DIR.OFF)
  CH("OOBEMU2"):WaitMove()
  CH("OOBEMU2"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("HERO"):WaitMove()
  CH("HERO"):SetMotion(SymMot("EV000_CSWAIT"), LOOP.ON)
  CH("KONOHANA"):WaitMove()
  CH("KONOHANA"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("OOBEMU3"):WalkTo(SymPos("P01_OOBEMU3"), Speed(1.5))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -92814244)
  WINDOW:Talk(SymAct("KONOHANA"), -1254731109)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_FOOT_STEP_01_LP"))
  CH("KONOHANA"):RunTo(SymPos("P02_KONOHANA"), Speed(4))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):RunTo(SymPos("P04_HERO"), Speed(4))
  CH("OOBEMU"):DirTo(RotateTarget(130), Speed(200), ROT_TYPE.NEAR)
  CH("OOBEMU2"):DirTo(RotateTarget(130), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.8))
  SOUND:FadeOutSe(SymSnd("SE_EVT_FOOT_STEP_01_LP"), TimeSec(0.5))
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1406311462)
  WINDOW:SysMsg(-2030030823)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  SYSTEM:SetForceSyncStop(false)
  EFFECT:DestroyRecollectionFilter()
end
function main23_konohananowana05_end()
end
function main23_konohananowana06_init()
end
function main23_konohananowana06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetVisibleScarf(false)
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -1642397352)
  WINDOW:Talk(SymAct("KONOHANA"), 428023191)
  WINDOW:Talk(SymAct("KONOHANA"), 9972950)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(1776742650)
  WINDOW:SysMsg(1895678395)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  SYSTEM:SetForceSyncStop(false)
  EFFECT:DestroyRecollectionFilter()
end
function main23_konohananowana06_end()
end
function main23_konohananowana07_init()
end
function main23_konohananowana07_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):SetVisibleScarf(true)
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1540395640, PARTNER_1 = 1120641849})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(72, 16, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 227161598)
  WINDOW:Talk(SymAct("KONOHANA"), 345048255)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(1069307772)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  SYSTEM:SetForceSyncStop(false)
  EFFECT:DestroyRecollectionFilter()
end
function main23_konohananowana07_end()
end
function main23_konohananowana08_init()
end
function main23_konohananowana08_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  TASK:Regist(subEveFukumiWarai, {
    CH("KONOHANA")
  })
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 648504893)
  WINDOW:Talk(SymAct("KONOHANA"), -1589675278)
  WINDOW:Talk(SymAct("KONOHANA"), -1205580877)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(2069061396)
  WINDOW:SysMsg(1648914005)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  SYSTEM:SetForceSyncStop(false)
  EFFECT:DestroyRecollectionFilter()
end
function main23_konohananowana08_end()
end
function main23_konohananowana09_init()
end
function main23_konohananowana09_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_KOKUHAKU"), Volume(256))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("KONOHANA"):SetEyeMotion(EYE_MOTION.ANGRY)
  CH("NYASUPAA"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1231371670, PARTNER_1 = 1350438103})
  WINDOW:SwitchTalk({PARTNER_0 = 524261904, PARTNER_1 = 103066449})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 755628178)
  WINDOW:Talk(SymAct("KONOHANA"), 873646547)
  WINDOW:Talk(SymAct("KONOHANA"), -1282747108)
  WINDOW:Talk(SymAct("KONOHANA"), -1433279395)
  WINDOW:Talk(SymAct("KONOHANA"), -1007732623)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.3))
  CH("HERO"):WaitNeckRot()
  WINDOW:Monologue(-621541072)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("KONOHANA"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  TASK:Sleep(TimeSec(1))
  CH("KONOHANA"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -237413645)
  WINDOW:Talk(SymAct("KONOHANA"), -389911630)
  WINDOW:Talk(SymAct("KONOHANA"), -1484522123)
  WINDOW:Talk(SymAct("KONOHANA"), -1097282508)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("HERO"):ResetNeckRot(TimeSec(0.15))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_SHOCK_L")
  CH("OOBEMU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("OOBEMU"), -1783259145)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_NOTICE_R")
  CH("KONOHANA"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -1934709066)
  WINDOW:Talk(SymAct("KONOHANA"), 188134009)
  WINDOW:Talk(SymAct("KONOHANA"), 304972600)
  WINDOW:Talk(SymAct("KONOHANA"), -1685313497)
  WINDOW:Talk(SymAct("KONOHANA"), -2104026778)
  WINDOW:KeyWait()
  SOUND:FadeOutBgm(TimeSec(2.5))
  WINDOW:Talk(SymAct("KONOHANA"), -1447408987)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_FLY_SWEAT")
  CH("OOBEMU"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.15))
  CH("OOBEMU"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), -1331594268)
  WINDOW:CloseMessage()
  SOUND:PlayEnv(SymSnd("SE_EVT_DROP_WATER_LP"), Volume(128))
  CH("KONOHANA"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -2036445, PARTNER_1 = -419701662})
  WINDOW:SwitchTalk({PARTNER_0 = -841576543, PARTNER_1 = -724713760})
  WINDOW:SwitchTalk({PARTNER_0 = 1398121007, PARTNER_1 = 1246663534})
  WINDOW:SwitchTalk({PARTNER_0 = 590368578, PARTNER_1 = 975928835})
  TASK:WaitTask()
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = 285617600, PARTNER_1 = 136125569})
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetVisible(true)
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1197247046)
  WINDOW:Talk(SymAct("KONOHANA"), 1581759239)
  WINDOW:Talk(SymAct("KONOHANA"), 1969940676)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU"):ResetNeckRot(TimeSec(0.15))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1819400581, PARTNER_1 = -337001142})
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -218958837)
  WINDOW:Talk(SymAct("KONOHANA"), -659787162)
  WINDOW:CloseMessage()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_04"), Volume(256))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutEnv(TimeSec(1.5))
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CH("NYASUPAA"):SetVisible(true)
  CH("NYASUPAA"):WalkTo(SymPos("P00_NYASUPAA"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("OOBEMU"):DirTo(SymPos("P00_NYASUPAA"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(SymPos("P00_NYASUPAA"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(SymPos("P00_NYASUPAA"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  TASK:Sleep(TimeSec(0.4))
  CH("OOBEMU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitRotate()
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  CH("NYASUPAA"):WaitMove()
  CH("KONOHANA"):DirTo(SymPos("P00_NYASUPAA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1044954329, PARTNER_1 = -359001884})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CH("NYASUPAA"):DirTo(CH("PARTNER"), Speed(60), ROT_TYPE.NEAR)
  CH("NYASUPAA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NYASUPAA"), -209641051)
  WINDOW:Talk(SymAct("NYASUPAA"), -1128220830)
  WINDOW:Talk(SymAct("NYASUPAA"), -1512339933)
  WINDOW:Talk(SymAct("NYASUPAA"), -1896426016)
  WINDOW:Talk(SymAct("NYASUPAA"), -1746017119)
  WINDOW:Talk(SymAct("NYASUPAA"), 276166766)
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NYASUPAA"), 158255407)
  WINDOW:KeyWait()
  CH("NYASUPAA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("NYASUPAA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NYASUPAA"), 1611666691)
  WINDOW:Talk(SymAct("NYASUPAA"), 2030773314)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):ResetFacialMotion()
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1378252673, PARTNER_1 = 1262307008})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 75288583)
  WINDOW:Talk(SymAct("KONOHANA"), 493347142)
  WINDOW:Talk(SymAct("KONOHANA"), 910865029)
  WINDOW:Talk(SymAct("KONOHANA"), 793871300)
  WINDOW:CloseMessage()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SAD)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.3))
  CH("HERO"):WaitNeckRot()
  WINDOW:Monologue(-1463181557)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  CH("KONOHANA"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("NYASUPAA"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -1311592886)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU"):WaitManpu()
  CH("OOBEMU"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  local taskLookAt00 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):ResetFacialMotion()
    CH("PARTNER"):ResetFacialMotion()
    CH("HERO"):ResetNeckRot(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("OOBEMU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt00)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1923463917)
  WINDOW:Talk(SymAct("KONOHANA"), 1807649708)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("OOBEMU"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.3))
  CH("OOBEMU"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("OOBEMU"), 1083431023)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1502144814)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), 382304233)
  WINDOW:Talk(SymAct("OOBEMU"), 265440936)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("OOBEMU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:Talk(SymAct("OOBEMU"), 620698987)
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1038363690)
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("OOBEMU"), -1166266139)
  WINDOW:Talk(SymAct("OOBEMU"), -1553530460)
  WINDOW:DrawFace(324, 88, SymAct("OOBEMU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("OOBEMU"), -904274552)
  WINDOW:CloseMessage()
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -754783031)
  WINDOW:Talk(SymAct("KONOHANA"), -131088630)
  WINDOW:Talk(SymAct("KONOHANA"), -516649397)
  WINDOW:Talk(SymAct("KONOHANA"), -1368057716)
  WINDOW:CloseMessage()
  CH("NYASUPAA"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):SetVisible(false)
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -1217517107, PARTNER_1 = -1673299442})
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CH("KONOHANA"):WalkTo(SymPos("P00_KONOHANA"), Speed(0.8))
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU2"):WalkTo(SymPos("P00_OOBEMU2"), Speed(0.8))
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU3"):WalkTo(SymPos("P00_OOBEMU3"), Speed(0.8))
  CH("KONOHANA"):WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), -2057811121)
  WINDOW:Talk(SymAct("KONOHANA"), 46159744)
  WINDOW:Talk(SymAct("KONOHANA"), 467363521)
  WINDOW:Talk(SymAct("KONOHANA"), 1473176881)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskAura00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_KONOHANA_AURA_01"), Volume(256))
    EFFECT:Create("effectNihilAuraSt", SymEff("EV_NIHIL_AURA_ST"))
    EFFECT:SetPosition("effectNihilAuraSt", SymPos("P_EFF_01"))
    EFFECT:Play("effectNihilAuraSt")
    TASK:Sleep(TimeSec(0.2))
    SOUND:PlaySe(SymSnd("SE_EVT_KONOHANA_AURA_01_LP"), Volume(256))
    EFFECT:Create("effectNihilAuraLp", SymEff("EV_NIHIL_AURA_LP"))
    EFFECT:SetPosition("effectNihilAuraLp", SymPos("P_EFF_01"))
    EFFECT:Play("effectNihilAuraLp")
  end
  CH("KONOHANA"):SetMotion(SymMot("EV018_SHADOW00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskAura00)
  CH("KONOHANA"):WaitPlayMotion()
  CH("KONOHANA"):SetMotion(SymMot("EV018_SHADOW01"), LOOP.ON)
  CH("OOBEMU2"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("OOBEMU3"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KONOHANA"), 1322636400)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  local taskAura01 = function()
    EFFECT:ChangeColor("effectNihilAuraLp", Color(1, 1, 1, 0), TimeSec(5, TIME_TYPE.FRAME))
    EFFECT:SetScale("effectNihilAuraLp", Scale(0.4))
    EFFECT:Create("effectNihilAuraBeam", SymEff("EV_NIHIL_AURA_BEAM"))
    EFFECT:SetPosition("effectNihilAuraBeam", SymPos("P_EFF_01_5"))
    EFFECT:Play("effectNihilAuraBeam")
    EFFECT:MoveTo("effectNihilAuraBeam", SymPos("P_EFF_02"), Speed(10))
  end
  TASK:Regist(taskAura01)
  CH("KONOHANA"):SetMotion(SymMot("EV018_SHADOW02"), LOOP.OFF)
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.OFF)
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_KONOHANA_AURA_01_LP"), TimeSec(0.25))
  SOUND:PlaySe(SymSnd("SE_EVT_FB_NAGIHARAU"))
  SCREEN_A:FadeOut(TimeSec(0.1), true)
  EFFECT:Remove("effectNihilAuraLp")
  EFFECT:Remove("effectNihilAuraBeam")
  WINDOW:Narration(TimeSec(0), TimeSec(0), 1710786483)
  WINDOW:CloseMessage()
end
function main23_konohananowana09_end()
end
function main23_konohananowana10_init()
end
function main23_konohananowana10_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON, TimeSec(0))
  CH("KONOHANA"):SetEyeMotion(EYE_MOTION.ANGRY)
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  CH("OOBEMU2"):SetManpu("MP_EXCLAMATION")
  CH("OOBEMU3"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):WalkTo(SymPos("P00_KONOHANA"), Speed(2), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("OOBEMU2"):WalkTo(SymPos("P00_OOBEMU2"), Speed(2), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("OOBEMU3"):WalkTo(SymPos("P00_OOBEMU3"), Speed(2), LINK_DIR.OFF)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("KONOHANA"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("KONOHANA"), 2095298290)
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("DENRYUU"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("DENRYUU"), 866263093)
  WINDOW:Talk(SymAct("DENRYUU"), 716771700)
  WINDOW:CloseMessage()
  CH("KONOHANA"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("DENRYUU"):SetMotion(SymMot("THROW"), LOOP.OFF)
  CH("DENRYUU"):WaitPlayMotion()
  CH("DENRYUU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  CH("DENRYUU"):SetVisible(false)
  CH("SEREBII"):SetVisible(false)
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  EFFECT:Create("effectLightningWarp01", SymEff("EV_LIGHTNING_WARP_ZOOM"))
  EFFECT:SetPosition("effectLightningWarp01", SymPos("P_EFF_LIGHTNING_WARP_01"))
  EFFECT:SetDir("effectLightningWarp01", RotateTarget(-30))
  SOUND:PlaySe(SymSnd("SE_EVT_DEDENNE_DENGEKI_02"))
  EFFECT:Play("effectLightningWarp01")
  local taskFlash00 = function()
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
    TASK:Sleep(TimeSec(0.1))
    SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
    TASK:Sleep(TimeSec(0.1))
    SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
    TASK:Sleep(TimeSec(0.1))
    SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  end
  TASK:Regist(taskFlash00)
  local taskKonohana_00 = function()
    CH("KONOHANA"):SetManpu("MP_SHOCK_R")
    CH("KONOHANA"):SetMotion(SymMot("EV023_SHRINK00"), LOOP.OFF)
    CH("KONOHANA"):WaitPlayMotion()
    CH("KONOHANA"):SetMotion(SymMot("EV023_SHRINK01"), LOOP.ON)
  end
  TASK:Regist(taskKonohana_00)
  TASK:Sleep(TimeSec(0.1))
  local taskOobemu2_00 = function()
    CH("OOBEMU2"):SetManpu("MP_SHOCK_R")
    CH("OOBEMU2"):SetMotion(SymMot("EV023_SHRINK00"), LOOP.OFF)
    CH("OOBEMU2"):WaitPlayMotion()
    CH("OOBEMU2"):SetMotion(SymMot("EV023_SHRINK01"), LOOP.ON)
  end
  TASK:Regist(taskOobemu2_00)
  local taskOobemu3_00 = function()
    CH("OOBEMU3"):SetManpu("MP_SHOCK_R")
    CH("OOBEMU3"):SetMotion(SymMot("EV023_SHRINK00"), LOOP.OFF)
    CH("OOBEMU3"):WaitPlayMotion()
    CH("OOBEMU3"):SetMotion(SymMot("EV023_SHRINK01"), LOOP.ON)
  end
  TASK:Regist(taskOobemu3_00)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(taskFlash00)
  TASK:Sleep(TimeSec(0.8))
  CH("DENRYUU"):SetVisible(true)
  CH("SEREBII"):SetVisible(true)
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CH("JIRAACHI"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("JIRAACHI"):DirTo(CH("SEREBII"), Speed(350), ROT_TYPE.NEAR)
  CH("JIRAACHI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("JIRAACHI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("JIRAACHI"), 26493623)
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  CH("HERO"):DirTo(CH("SEREBII"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("SEREBII"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CH("SEREBII"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
  CH("SEREBII"):WaitRotate()
  CH("SEREBII"):SetMotion(SymMot("CHARGE"), LOOP.OFF)
  EFFECT:Create("effectLuminousWarp", SymEff("EV_LUMINOUS_WARP"))
  EFFECT:SetPosition("effectLuminousWarp", SymPos("P_EFF_EV_LUMINOUS_WARP"))
  SOUND:PlaySe(SymSnd("SE_EVT_LIGHT_EX"))
  EFFECT:Play("effectLuminousWarp")
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.7))
  SCREEN_A:WhiteOutAll(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0), true)
  SCREEN_A:WhiteInAll(TimeSec(0.5), true)
end
function main23_konohananowana10_end()
end
function groundEnd()
end
