dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main21_chitenboss2nd01_init()
end
function main21_chitenboss2nd01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetRotateZ(SymCam("CAMERA_05"))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("KUCHIITO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("RAIKOU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("SUIKUN"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("ENTEI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_03"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), 952747455)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:SetRotateZ(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("RAIKOU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("RAIKOU"), 567473406)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:SetRotateZ(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("SUIKUN"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SUIKUN"), 184526653)
  WINDOW:CloseMessage()
  CAMERA:SetRotateZ(Degree(0))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:MoveFollow2(SymCam("CAMERA_08_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("ENTEI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("ENTEI"), 333747836)
  WINDOW:CloseMessage()
  subEveFlash2()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:SetNextDungeonBanner(false)
end
function main21_chitenboss2nd01_end()
end
function groundEnd()
end
