dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_moguryutankoubosswin01_init()
end
function main03_moguryutankoubosswin01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  CH("MOGURYUU"):SetVisible(false)
  CH("MOGURYUU2"):SetVisible(false)
  CH("MOGURYUU3"):SetVisible(false)
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("GABAITO"):SetMotion(SymMot("ENDURE"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(272, 16, SymAct("GABAITO"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("GABAITO"), -86665124)
  WINDOW:Talk(SymAct("GABAITO"), -472995555)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -924583202, PARTNER_1 = -772224097})
  WINDOW:SwitchTalk({PARTNER_0 = -1632019112, PARTNER_1 = -2019398631})
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  EFFECT:Create("effectBgConLp", SymEff("BG_CONCENTRATION_LP"))
  EFFECT:SetPosition("effectBgConLp", CH("GABAITO"), BODY_POINT.CENTER)
  EFFECT:Play("effectBgConLp")
  CAMERA:SetFovy(SymCam("CAMERA_02_5"))
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  CH("GABAITO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_DOTEKKOTSU"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:Talk(SymAct("GABAITO"), -1399898150)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetSisaRateVolume(Volume(1))
  EFFECT:Remove("effectBgConLp")
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1248588133, PARTNER_1 = 839651924})
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.2))
  local taskHeroLookAround = function()
    CH("HERO"):DirTo(RotateTarget(40), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(RotateTarget(170), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  local taskPartnerLookAround = function()
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):DirTo(RotateTarget(-40), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  WINDOW:Talk(SymAct("MOGURYUU"), 722936597)
  WINDOW:KeyWait()
  TASK:Regist(Group("hero"), taskHeroLookAround)
  TASK:Regist(Group("partner"), taskPartnerLookAround)
  CH("GABAITO"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("MOGURYUU"), -822497134)
  WINDOW:CloseMessage()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -673021485, PARTNER_1 = -53489136})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-439033007)
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  local taskMoguryuu_Entry = function()
    EFFECT:Create("effectSmoke01", SymEff("EV_SMOKE_BROWN"))
    EFFECT:SetPosition("effectSmoke01", SymPos("P01_EFF_SMOKE"))
    EFFECT:SetScale("effectSmoke01", Scale(2))
    EFFECT:Play("effectSmoke01")
    CH("MOGURYUU"):SetMotion(SymMot("EV003_APPEAR00"), LOOP.OFF, TimeSec(0))
    CH("MOGURYUU"):SetVisible(true)
    CH("MOGURYUU"):WaitPlayMotion()
    CH("MOGURYUU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local taskMoguryuu2_Entry = function()
    EFFECT:Create("effectSmoke02", SymEff("EV_SMOKE_BROWN"))
    EFFECT:SetPosition("effectSmoke02", SymPos("P02_EFF_SMOKE"))
    EFFECT:SetScale("effectSmoke02", Scale(2))
    EFFECT:Play("effectSmoke02")
    CH("MOGURYUU2"):SetMotion(SymMot("EV003_APPEAR00"), LOOP.OFF, TimeSec(0))
    CH("MOGURYUU2"):SetVisible(true)
    CH("MOGURYUU2"):WaitPlayMotion()
    CH("MOGURYUU2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local taskMoguryuu3_Entry = function()
    EFFECT:Create("effectSmoke03", SymEff("EV_SMOKE_BROWN"))
    EFFECT:SetPosition("effectSmoke03", SymPos("P03_EFF_SMOKE"))
    EFFECT:SetScale("effectSmoke03", Scale(2))
    EFFECT:Play("effectSmoke03")
    CH("MOGURYUU3"):SetMotion(SymMot("EV003_APPEAR00"), LOOP.OFF, TimeSec(0))
    CH("MOGURYUU3"):SetVisible(true)
    CH("MOGURYUU3"):WaitPlayMotion()
    CH("MOGURYUU3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  SOUND:FadeOutSe(SymSnd("SE_EVT_FIREBALL_COME_02_LP"), TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_DORYUUZU_APPEAR"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Regist(Group("moguryuu_1"), taskMoguryuu_Entry)
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_DORYUUZU_APPEAR"), Volume(256))
  TASK:Regist(Group("moguryuu_2"), taskMoguryuu2_Entry)
  TASK:Regist(Group("moguryuu_3"), taskMoguryuu3_Entry)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):DirTo(CH("MOGURYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.4))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("GABAITO"):SetManpu("MP_EXCLAMATION")
  CH("GABAITO"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), -1433045610)
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_01"), Volume(256))
  CH("MOGURYUU3"):DirTo(CH("GABAITO"), Speed(350), ROT_TYPE.NEAR)
  CH("MOGURYUU3"):WaitRotate()
  CH("MOGURYUU"):DirTo(CH("GABAITO"), Speed(350), ROT_TYPE.NEAR)
  local taskLookAt01 = function()
    CH("GABAITO"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("MOGURYUU3"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(324, 88, SymAct("MOGURYUU3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOGURYUU3"), -1282521897)
  WINDOW:Talk(SymAct("MOGURYUU3"), -1734142188)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_09"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("GABAITO"):DirTo(CH("MOGURYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("MOGURYUU"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(CH("MOGURYUU"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("MOGURYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOGURYUU"), -2118637995)
  WINDOW:Talk(SymAct("MOGURYUU"), 102775450)
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_11"))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), 523963355)
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("MOGURYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOGURYUU"), -598990980)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
  CH("MOGURYUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MOGURYUU3"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOGURYUU3"), -984142275)
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_12"))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  local taskLookAt03 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("GABAITO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU3"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt03)
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  CH("HERO"):DirTo(CH("GABAITO"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -293962242, PARTNER_1 = -144618305})
  WINDOW:SwitchTalk({PARTNER_0 = -1205806472, PARTNER_1 = -1589908679})
  WINDOW:SwitchTalk({PARTNER_0 = -1978222342, PARTNER_1 = -1827829317})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), 345347444)
  subEveCloseMsg()
  subEveNod(CH("PARTNER"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 227451957, PARTNER_1 = 1693480985})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), 2112571736)
  WINDOW:Talk(SymAct("GABAITO"), 1455823515)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GABAITO"):SetManpu("MP_FLY_SWEAT")
  CH("GABAITO"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("GABAITO"):WaitRotate()
  CH("GABAITO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.35))
  CH("GABAITO"):WaitNeckRot()
  WINDOW:DrawFace(20, 20, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), 1339894746)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 10272029, PARTNER_1 = 428313692})
  WINDOW:SwitchTalk({PARTNER_0 = 850059167, PARTNER_1 = 733081310})
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("MOGURYUU3"), -1406537199)
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  local taskLookAt04 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("MOGURYUU"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU3"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  end
  CH("GABAITO"):ResetNeckRot(TimeSec(0.3))
  CH("GABAITO"):WaitNeckRot()
  TASK:Regist(taskLookAt04)
  CH("GABAITO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("GABAITO"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), -1254964400)
  WINDOW:Talk(SymAct("GABAITO"), -114868064)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -532909599, PARTNER_1 = -888069598})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  CH("GABAITO"):WalkTo(SymPos("P00_GABAITO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("MOGURYUU"):WalkTo(SymPos("P00_MOGURYUU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("MOGURYUU2"):WalkTo(SymPos("P00_MOGURYUU2"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("MOGURYUU3"):WalkTo(SymPos("P00_MOGURYUU3"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main03_moguryutankoubosswin01_end()
end
function main03_moguryutankoubosswin02_init()
end
function main03_moguryutankoubosswin02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskMapIn00 = function()
    CH("GABAITO"):WalkTo(SymPos("P00_GABAITO"), Speed(1.5))
    CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU"):WalkTo(SymPos("P00_MOGURYUU"), Speed(1.5))
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU2"):WalkTo(SymPos("P00_MOGURYUU2"), Speed(1.5))
    TASK:Sleep(TimeSec(0.1))
    CH("MOGURYUU3"):WalkTo(SymPos("P00_MOGURYUU3"), Speed(1.5))
  end
  TASK:Regist(taskMapIn00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("GABAITO"):WaitMove()
  CH("GABAITO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  CH("GABAITO"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), -771091613)
  WINDOW:Talk(SymAct("GABAITO"), -1655994972)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAKIRA"), Volume(64))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -2075085595, PARTNER_1 = -1350703322})
  WINDOW:SwitchTalk({PARTNER_0 = -1234774425, PARTNER_1 = 838781608})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), 686160873)
  WINDOW:Talk(SymAct("GABAITO"), 1100687301)
  WINDOW:Talk(SymAct("GABAITO"), 1484789380)
  WINDOW:Talk(SymAct("GABAITO"), 1940735303)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("HERO"):SetDir(CH("GABAITO"))
  CH("PARTNER"):SetDir(CH("GABAITO"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GABAITO"):SetManpu("MP_FLY_SWEAT")
  CH("GABAITO"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("GABAITO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("GABAITO"), 1790342150)
  WINDOW:Talk(SymAct("GABAITO"), 637002433)
  WINDOW:Talk(SymAct("GABAITO"), 1022153600)
  WINDOW:CloseMessage()
  CH("MOGURYUU"):SetDir(CH("PARTNER"))
  CH("MOGURYUU2"):SetDir(CH("PARTNER"))
  CH("MOGURYUU3"):SetDir(CH("PARTNER"))
  CH("GABAITO"):SetDir(CH("PARTNER"))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("MOGURYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("MOGURYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("MOGURYUU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("MOGURYUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MOGURYUU"), 398557251)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MOGURYUU2"):SetManpu("MP_FLY_SWEAT")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("MOGURYUU2"), Speed(350), ROT_TYPE.NEAR)
  CH("MOGURYUU2"):WaitManpu()
  WINDOW:DrawFace(72, 88, SymAct("MOGURYUU3"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MOGURYUU3"), 249213186)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1992118835, PARTNER_1 = -1873175412})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1395558443, PARTNER_1 = 1245034858})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1629022889, PARTNER_1 = 2013518824})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 927092015, PARTNER_1 = 777616494})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  local taskPartner00 = function()
    TASK:Regist(subEveDoubleJump, {
      CH("PARTNER")
    })
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(CH("GABAITO"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("MOGURYUU2"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  TASK:Regist(taskPartner00)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 91500461, PARTNER_1 = 477044460})
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1678310877, PARTNER_1 = -2098449566})
  WINDOW:SwitchTalk({PARTNER_0 = -342692018, PARTNER_1 = -225845745})
  WINDOW:SwitchTalk({PARTNER_0 = -643527220, PARTNER_1 = -1061176179})
  WINDOW:SwitchTalk({PARTNER_0 = -1879168438, PARTNER_1 = -1763370229})
  WINDOW:KeyWait()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1110947640, PARTNER_1 = -1529644663})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1.5))
end
function main03_moguryutankoubosswin02_end()
end
function groundEnd()
end
