dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function sub01_omoidasu01_init()
end
function sub01_omoidasu01_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  local taskHero00 = function()
    CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("HERO"):SetManpu("MP_SHOCK_R")
    CH("HERO"):SetMotion(SymMot("DAMAGE"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.15))
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
    CH("HERO"):WaitPlayMotion()
    CH("HERO"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(-908734345)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-791748298)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
end
function sub01_omoidasu01_end()
end
function sub01_omoidasu02_init()
end
function sub01_omoidasu02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:CreateRecollectionFilter()
  CH("MYUU"):SetMotion(SymMot("SB001_SLEEP03"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SAD)
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  WINDOW:SysMsg(-68963595)
  WINDOW:SysMsg(-487029836)
  WINDOW:SysMsg(-1380379277)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  SCREEN_A:WhiteChange(Level(0), Level(1), TimeSec(0.02), true)
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeOut(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.1))
  EFFECT:DestroyRecollectionFilter()
end
function sub01_omoidasu02_end()
end
function sub01_omoidasu03_init()
end
function sub01_omoidasu03_start()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  SCREEN_A:FadeIn(TimeSec(0.1), true)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-1264442318)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function sub01_omoidasu03_end()
end
function groundEnd()
end
