dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main02_konohananoiede01_init()
end
function main02_konohananoiede01_start()
  MAP:SetVisible(false)
  MAP:SetBG(SymImg("WALLPAPER_MAIN_CAPTURE_BG01"))
  MAP:SetVisibleBG(true)
  WINDOW:BeginChapter()
  SCREEN_A:FadeOutAll(TimeSec(0), true)
  SCREEN_A:FadeIn(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(1), false)
  WINDOW:SetWaitMode(TimeSec(2), TimeSec(1))
  WINDOW:Chapter(TimeSec(1.5), TimeSec(1.5), 1383911373)
  TASK:Sleep(TimeSec(3))
  SCREEN_A:FadeOutAll(TimeSec(1), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  WINDOW:EndChapter()
  WINDOW:ForceCloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
end
function main02_konohananoiede01_end()
end
function main02_konohananoiede02_init()
end
function main02_konohananoiede02_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KONOHANA"):RunTo(SplinePath(SymPos("P00_KONOHANA"), SymPos("P01_KONOHANA"), SymPos("P02_KONOHANA")), Speed(2.5))
  CH("HERO"):RunTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(2.5))
  SOUND:FadeInEnv(SymSnd("SE_MAP_HILLSWIND_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(4))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main02_konohananoiede02_end()
end
function main02_konohananoiede03_init()
end
function main02_konohananoiede03_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("KONOHANA"):WalkTo(SymPos("P00_KONOHANA"), Speed(1.5))
  SOUND:PlayEnv(SymSnd("SE_MAP_HILLSWIND_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("KONOHANA"):WaitMove()
  CH("KONOHANA"):DirTo(SymPos("P00_HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1265106572)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("KONOHANA"):DirTo(SymPos("P00_HOUSE"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):DirTo(SymPos("P00_HOUSE"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1615506767)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.3))
  CH("KONOHANA"):WalkTo(SymPos("P01_KONOHANA"), Speed(1.5))
  TASK:Sleep(TimeSec(0.7))
  CH("HERO"):WalkTo(SymPos("P01_KONOHANA"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutEnv(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
end
function main02_konohananoiede03_end()
end
function main02_konohananoiede04_init()
end
function main02_konohananoiede04_start()
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KONOHANA"):WalkTo(SplinePath(SymPos("P00_KONOHANA"), SymPos("P01_KONOHANA"), SymPos("P02_KONOHANA")), Speed(1.5))
  CH("HERO"):WalkTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(1.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_KONOHANANOIE"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.7))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  WINDOW:DrawFaceF(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 2035391502)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
  CAMERA:WaitMove()
  CH("KONOHANA"):WaitMove()
  WINDOW:DrawFaceF(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 907021001)
  WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 789265288)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01_5"))
  CAMERA:SetTgt(SymCam("CAMERA_01_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), 69625931)
  WINDOW:Talk(SymAct("KONOHANA"), 490559754)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01_7"))
  CAMERA:SetTgt(SymCam("CAMERA_01_7"))
  WINDOW:Monologue(-1700444731)
  CH("HERO"):WaitNeckRot()
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01_5"))
  CAMERA:SetTgt(SymCam("CAMERA_01_5"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KONOHANA"), -2084670332)
  WINDOW:KeyWait()
  CH("KONOHANA"):DirTo(RotateTarget(-90), Speed(60), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:Talk(SymAct("KONOHANA"), 1403807543)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1253529206)
  WINDOW:Talk(SymAct("KONOHANA"), 1637483957)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01_7"))
  CAMERA:SetTgt(SymCam("CAMERA_01_7"))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.25))
  CAMERA:SetEye(SymCam("CAMERA_01_5"))
  CAMERA:SetTgt(SymCam("CAMERA_01_5"))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 2021733620)
  WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(RotateTarget(-30), Speed(200), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 935371315)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_EXCLAMATION")
  CH("KONOHANA"):WaitManpu()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 786142066)
  WINDOW:Talk(SymAct("KONOHANA"), 100057265)
  WINDOW:Talk(SymAct("KONOHANA"), 485356016)
  WINDOW:Talk(SymAct("KONOHANA"), -1686770369)
  WINDOW:Talk(SymAct("KONOHANA"), -2106663810)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("KONOHANA"):WalkTo(SymPos("P03_KONOHANA"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):WalkTo(SymPos("P03_HERO"), Speed(1.5))
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(SymPos("P03_KONOHANA"), Speed(350), ROT_TYPE.LEFT)
  CH("KONOHANA"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1092208857)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  CH("KONOHANA"):WalkTo(SplinePath(SymPos("P00_KONOHANA"), SymPos("P04_KONOHANA")), Speed(1.5))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("KONOHANA"):SetVisible(false)
  CAMERA:ResetSisaRateVolume()
  CAMERA:ResetSisaAzimuthDifferenceVolume()
end
function main02_konohananoiede04_end()
end
function groundEnd()
end
