dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function sub01_seireinosakyuuclear1st01_init()
end
function sub01_seireinosakyuuclear1st01_start()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetSisaRateVolume(Volume(0.5))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(-2016839615)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1630385920)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(3))
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHUKEI"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  TASK:Sleep(TimeSec(1.5))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.2))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CH("HERO"):WaitMove()
  WINDOW:DrawFaceF(172, 8, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct(""), -1241572669)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1394332798)
  subEveCloseMsg()
  WINDOW:DrawFaceF(172, 8, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct(""), -475677371)
  WINDOW:Talk(SymAct(""), -88175612)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("NEITYIO"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("NEITYIO"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct(""), -778838073)
  WINDOW:DrawFace(72, 16, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), -930550138)
  WINDOW:Talk(SymAct("NEITYIO"), 1326510665)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), 1443611400)
  WINDOW:Talk(SymAct("NEITYIO"), -1851833366)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  WINDOW:DrawFace(20, 20, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), -2004585813)
  WINDOW:CloseMessage()
  CH("NEITYIO"):WalkTo(SymPos("P00_NEITYIO"), Speed(1))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:SetFovy(SymCam("CAMERA_02"))
  CH("NEITYIO"):WaitMove()
  CH("NEITYIO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.3))
  CH("NEITYIO"):WaitNeckRot()
  WINDOW:SysMsg(-1549196952)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), -1162735575)
  WINDOW:Talk(SymAct("NEITYIO"), -168589586)
  WINDOW:Talk(SymAct("NEITYIO"), -320292945)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  local taskNeityio00 = function()
    CH("NEITYIO"):ResetNeckRot(TimeSec(0.15))
    CH("NEITYIO"):SetMotion(SymMot("SB001_SCARE00"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.2))
    CAMERA:MoveFollow2(SymCam("CAMERA_04_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    CH("NEITYIO"):WaitPlayMotion()
    CH("NEITYIO"):SetMotion(SymMot("SB001_SCARE01"), LOOP.ON)
  end
  TASK:Regist(taskNeityio00)
  local taskHero00 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("HERO"):SetManpu("MP_SHOCK_L")
    CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(2), LINK_DIR.OFF)
  end
  TASK:Regist(taskHero00)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_NEITYO_KUEEE"), Volume(256))
  WINDOW:SysMsg(-943332244)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-555821779)
  WINDOW:CloseMessage()
  CH("NEITYIO"):SetMotion(SymMot("SB001_SCARE02"), LOOP.OFF)
  CH("NEITYIO"):WaitPlayMotion()
  CH("NEITYIO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CHUKEI"), Volume(256))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), 1497811426)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HERO"):SetManpu("MP_FLY_SWEAT")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1079900323)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), -2094339068)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1708008123)
  WINDOW:Monologue(-1323528570)
  WINDOW:Monologue(-1475887161)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), -414832384)
  WINDOW:Talk(SymAct("NEITYIO"), -27453375)
  WINDOW:Talk(SymAct("NEITYIO"), -714060926)
  WINDOW:Talk(SymAct("NEITYIO"), -865371453)
  WINDOW:Talk(SymAct("NEITYIO"), 1274242572)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(1390958413)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), 999721825)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(579713568)
  WINDOW:Monologue(161540579)
  WINDOW:Monologue(280746146)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):RunTo(SymPos("P03_HERO"), Speed(3))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(2.5))
  SOUND:FadeOutBgm(TimeSec(2.5))
  SOUND:FadeInEnv(SymSnd("SE_ENV_CLIFF_LP"), TimeSec(1), Volume(256))
  CH("NEITYIO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("NEITYIO"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("NEITYIO"):WalkTo(SymPos("P01_NEITYIO"), Speed(1.2))
  CH("NEITYIO"):WaitMove()
  TASK:Sleep(TimeSec(2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFaceF(172, 8, SymAct("NEITYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NEITYIO"), 1610239589)
  WINDOW:Talk(SymAct("NEITYIO"), 1189183268)
  WINDOW:Talk(SymAct("NEITYIO"), 1842097383)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
end
function sub01_seireinosakyuuclear1st01_end()
end
function groundEnd()
end
