dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_inisienohoneatochukeiyarare01_init()
end
function main09_inisienohoneatochukeiyarare01_start()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -1318768553, PARTNER_1 = -1468137194})
  WINDOW:KeyWait()
  SCREEN_A:FadeOutAll(TimeSec(0.5), true)
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("SE_ENV_CLIFF_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -2091691307, PARTNER_1 = -1706531948})
  subEveCloseMsg()
  CH("PARTNER"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("SHIKIJIKA_SPRING"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("SHIKIJIKA_SPRING"), -720767661)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("NYASUPAA"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("NYASUPAA"), -871185390)
  WINDOW:CloseMessage()
  CAMERA:MoveToHero(Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
end
function main09_inisienohoneatochukeiyarare01_end()
end
function groundEnd()
end
